import type { CategoryContent } from '../row.js';

export const ANATOMY: CategoryContent = {
  bscba: [
    [
      'Hoeveel hoofdtypes van botten worden in de menselijke anatomie ingedeeld op basis van hun vorm?',
      [
        'Vier: lang, kort, plat en onregelmatig',
        'Drie: lang, kort en plat',
        'Vijf: lang, kort, plat, onregelmatig en sesamoïd',
        'Zes: lang, kort, plat, onregelmatig, pneumatisch en dicht',
      ],
      0,
      'Botten worden op basis van vorm in vier typen ingedeeld: lang (femur), kort (carpalen), plat (borstbeen) en onregelmatig (wervels).',
    ],
    [
      'Welk van het volgende beschrijft het best de structuur van een synoviale gewricht?',
      [
        'Botuiteindes met hyaline kraakbeen in een vloeistofkapsel',
        'Botten bij elkaar gehouden door vezelig bindweefsel zonder ruimte ertussen',
        'Kraakbeenachtige schijf die twee botuiteindes volledig samensmelten',
        'Twee botten verbonden door elastische ligamenten die een semi-mobiel gewricht vormen',
      ],
      0,
      'Synoviale gewrichten hebben hyaline kraakbeen op articulaire oppervlakken, een synoviale membraan in de kapsel en synoviale vloeistof voor smering.',
    ],
    [
      'Wat is het primaire structurele verschil tussen Type I en Type II spiervezels?',
      [
        'Type I is slow-twitch en oxidatief; Type II is fast-twitch en glycolytisch',
        'Type I vezels worden uitsluitend in het hart gevonden; Type II in skeletspier',
        'Type II vezels bevatten meer mitochondriën en voeren aërobe metabolisme uit',
        'Type I vezels hebben dikker myofilamenten en genereren meer kracht',
      ],
      0,
      'Type I vezels blinken uit in duurzame, lage-kraft activiteit via oxidatieve metabolisme. Type II specialiseren zich in snelle, krachtige contractie via glycolyse.',
    ],
    [
      'Welke twee grote bloedvaten bereiken het rechter atrium?',
      [
        'Bovenste en onderste holle aderen',
        'Linker- en rechterpulmonale slagaders',
        'Linker- en rechterpulmonale aders',
        'Aorta en coronair sinus',
      ],
      0,
      'De bovenste holle ader drainerrt hoofd, nek en bovenste ledematen; de onderste holle ader drainerrt alles onder het diafragma.',
    ],
    [
      'Welke hartkamer heeft de dikste myocardiale wand?',
      [
        'Linker ventrikel',
        'Rechter ventrikel',
        'Linker atrium',
        'Rechter atrium',
      ],
      0,
      'De linker ventrikel pompt bloed tegen hoge weerstand, wat dikke wanden (8–15 mm) vereist. De rechter ventrikel is dunner (2–5 mm).',
    ],
    [
      'Wat is de naam van de buis waar bloed van het hart naar het lichaam stroomt?',
      [
        'Aorta',
        'Halsslagader',
        'Pulmonale slagader',
        'Sleutelbeenarterie',
      ],
      0,
      'De aorta is de grootste slagader die uit de linker ventrikel entspringt en naar alle weefsels takelt.',
    ],
    [
      'Op welk anatomisch punt splitst de luchtpijp zich in twee primaire bronchi?',
      [
        'De carina',
        'De glottis',
        'De hilum',
        'De sternale hoek',
      ],
      0,
      'De carina is de nok waar de luchtpijp zich in linker- en rechterhoofdebronchi splitst op T4-T5 wervelhoogte.',
    ],
    [
      'Hoeveel lobben heeft de rechterlongin?',
      [
        'Drie',
        'Twee',
        'Vier',
        'Vijf',
      ],
      0,
      'De rechterlongin heeft drie lobben (boven, midden, onder) gescheiden door schuine en horizontale fissuren. De linker heeft slechts twee lobben.',
    ],
    [
      'Welke structuur voorkomt dat voedsel tijdens het slikken in de luchtpijp komt?',
      [
        'Epiglottis',
        'Zachte gehemelte',
        'Arytenöïde kraakbeen',
        'Stemlippen',
      ],
      0,
      'De epiglottis is een bladvormig kraakbeen dat zich tijdens het slikken over de larynxingang vouwen, wat de luchtweg beschermt.',
    ],
    [
      'Wat voor soort epitheel bekleedt de slokdarm?',
      [
        'Meerlagig plaveiselepitheel',
        'Eenvoudig kubisch epitheel',
        'Overgangsepitheel',
        'Pseudogelaagd trilharig epitheel',
      ],
      0,
      'Meerlagig plaveiselepitheel bestand tegen mechanische schuring van voedsel en mist de klieren en ploien van de maag.',
    ],
    [
      'Wat is de primaire functie van de fundus van de maag?',
      [
        'Maagsapafscheiding',
        'Bergting van voedsel en begin mixen',
        'Pylorische sfincter controle',
        'Opname van voedingsstoffen',
      ],
      0,
      'De fundus bevat maagstelklieren (wand-, hoofd-, slijmklieren) die zuur, pepsine en beschermende slijm afscheiden.',
    ],
    [
      'Waar is de lever primair aan vastgehecht?',
      [
        'Diafragma via het falksvormige ligament',
        'Maag via het gastrohepale ligament',
        'Milt via het gastrospleenligament',
        'Alvleesklier via pancreatiocoduodenale aders',
      ],
      0,
      'Het falksvormige ligament (ventrale mesenterium) en coronaire ligamenten hechten de lever aan het diafragma en voorste buikwand.',
    ],
    [
      'De functionele filtereenheden van de nier worden genoemd?',
      [
        'Nefronen',
        'Glomeruli',
        'Tubuli',
        'Piramiden',
      ],
      0,
      'Elk nefron bestaat uit een renaal corpusculum (glomerulus + Bowman\'s capsule) en reale tubulus. De nier bevat ongeveer 1 miljoen nefronen.',
    ],
    [
      'Welke nierkamer bevat de glomeruli en proximale gewonden tubuli?',
      [
        'Nierschors',
        'Niermerg',
        'Nierbecken',
        'Nierkolom',
      ],
      0,
      'De nierschors bevat alle glomeruli en proximale/distale gewonden tubuli. Het merg bevat de Henle-lus en verzamelbuizen.',
    ],
    [
      'Wat is de anatomische term voor waar een spier aan het bewegende bot hecht?',
      [
        'Aanhechting',
        'Oorsprong',
        'Spierbuik',
        'Fascie',
      ],
      0,
      'De aanhechting is waar aan het bewegende bot (meestal distaal). De oorsprong is de vaste aanhechting (meestal proximaal). Beide heten enthesen.',
    ],
  ],
  msc: [
    [
      'In de microstructuur van compact bot, waruit bestaat het Haversian systeem?',
      [
        'Concentrische lamellen rond een kanaal met vaten en zenuwen',
        'Radiërend trabeculae van sponsbotten ondersteund door een dichte buitenschaal',
        'Langsgericht rijen van osteocyten ingebed in evenwijdige collageenvezels',
        'Onderling verbonden holten gevoerd door osteoblasten en gescheiden door gemineraliseerde septa',
      ],
      0,
      'Een Haversian (osteon) systeem is de kleinste structurele eenheid: concentrische ringen van botmatrix (lamellen) rond een osteoniekanaal.',
    ],
    [
      'Uit welk kiemlaag ontstaat embryologisch het synoviale membraan van gewrichten?',
      [
        'Laterale plaat mesoderm',
        'Paraxiale mesoderm',
        'Ectoderm',
        'Endoderm',
      ],
      0,
      'Het synoviale membraan en gewrichtscapsule ontwikkelen zich uit laterale plaat (somatische) mesoderm rond het ontwikkelende kraakbeenmodel.',
    ],
    [
      'Welk collagentype vormt het merendeel van het fibrокraakbeen in peesbot aanhechting?',
      [
        'Type I collageen',
        'Type II collageen',
        'Type III collageen',
        'Type IV collageen',
      ],
      0,
      'Type I collageen domineert de enthesis fibrocartilage, georganiseerd in gegradeerde zones (pees, ongecalcificeerd kraakbeen, bot).',
    ],
    [
      'In spierfysiologie, wat is de structurele relatie tussen Z-schijf en dunne filamenten?',
      [
        'Dunne filamenten verankeren aan Z-schijven en overlappen midden',
        'Dunne filamenten strekken zich uit van Z-schijven naar myosine koppen in de A-band',
        'Z-schijven bestaan geheel uit actine en tropomyosine moleculen',
        'Dunne filamenten zijn loodrecht aan Z-schijven bevestigd via titin moleculen',
      ],
      0,
      'Dunne filamenten verankerd aan Z-schijven via α-actinine en CapZ eiwitten, strekken zich naar de M-lijn. Dit bepaalt sarcomeerlengte.',
    ],
    [
      'De coronaire circulatie wordt vooral gevoed door takken van welke vaten vanuit de aorta?',
      [
        'L/R kroonslagaders',
        'Tussenribslagaders',
        'Interne borstbeemslagader',
        'Longarteriële takken',
      ],
      0,
      'De linker- en rechterkroonslagaders ontkomen uit sinussen van Valsalva (aortaklapaanhechtingspunten) en voeden myocardium en epicardium.',
    ],
    [
      'Welke anatomische structuur vertraagt geleiding tussen atria en ventrikels?',
      [
        'AV-knoop',
        'Sinusknoop',
        'His bundel',
        'Purkinje vezels',
      ],
      0,
      'De AV-knoop heeft langzame geleiding (~0.05 m/s) door kleine celdiameter en schaarse gap junctions, zodat atria eerst kunnen samentrekken.',
    ],
    [
      'Welk orgaan voert bloed rechtstreeks via de portalader naar de lever?',
      [
        'Darmkanaal en milt',
        'Hart en longen',
        'Nieren en bijnierkliertjes',
        'Hersenen en ruggenmerg',
      ],
      0,
      'De portalader voert bloed van het maagdarmkanaal af en levert voedselrijk bloed aan hepatocyten voor eersteklasse metabolisme.',
    ],
    [
      'Wanneer het diafragma samentrekt, wat gebeurt er met de intralong druk?',
      [
        'De druk wordt negatief (subatmosferisch)',
        'De druk stijgt boven atmosferische druk',
        'De druk blijft constant',
        'De druk wordt gelijk aan atmosferische druk',
      ],
      0,
      'Diafragmacontractie vergroot thoraxvolume, waardoor intralong druk negatief wordt. Lucht stroomt in volgend drukgradiënt.',
    ],
    [
      'Wat is uniek aan pulmonale slagaders dat zij voeren?',
      [
        'Zuurstofarm bloed',
        'Zuurstofrijk bloed',
        'Gemengd arterieel en veneus bloed',
        'Lymphvocht',
      ],
      0,
      'Pulmonale slagaders zijn de enige systemische slagaders die zuurstofarm bloed voeren van rechter ventrikel naar longen voor gasuitwisseling.',
    ],
    [
      'Wat houdt de gastro-esofageale overgang normaal gesloten?',
      [
        'De LES',
        'Bovenste slokdarmsfincter',
        'Pylorische sfincter',
        'Ileocecale klep',
      ],
      0,
      'De LES is een zone van hogedruk gladde spier (30–40 mmHg) innerveerd door vaguszenuw, opent zich tijdens slikken.',
    ],
    [
      'De bloed-zaadbalgen barrière ontstaat uit strakke juncties tussen welk celtype?',
      [
        'Sertoli cellen',
        'Leydig cellen',
        'Spermatogonia',
        'Peritubulaire myoïde cellen',
      ],
      0,
      'Sertoli cel strakke juncties vormen de bloed-testis barrière, scheidend basale spermatogonia van meiose kiemcellen.',
    ],
    [
      'Welke embryologische kiemlaag geeft aanleiding tot het urogenitale systeem?',
      [
        'Intermediaire mesoderm',
        'Laterale plaat mesoderm',
        'Paraxiale mesoderm',
        'Endoderm',
      ],
      0,
      'Intermediaire mesoderm (tussen paraxiale en laterale plaat mesoderm) geeft aanleiding tot nieren, ureters, gonaden en geslachtskanalen.',
    ],
    [
      'De ductus arteriosus verbindt embryologisch welke twee vaten?',
      [
        'Pulmonale slagader naar aorta',
        'Bovenste naar onderste holle ader',
        'Navelstrengslagader naar portalader',
        'Linker atrium naar rechter atrium',
      ],
      0,
      'De ductus arteriosus passeert niet-functionele fetale longen door bloed van pulmonale slagader naar aortaboog te leiden. Sluit na geboorte.',
    ],
    [
      'Perimysium is het bindweefsel dat omgeeft?',
      [
        'Spiervezelgroepjes',
        'Individuele spiervezels',
        'De gehele skeletspier',
        'Myofilamenten in sarcomeer',
      ],
      0,
      'Perimysium omhult spiervezelgroepjes ter ondersteuning van ordening. Endomysium omgeeft individuele vezels; epimysium omgeeft gehele spier.',
    ],
    [
      'De portaltriade in leverhistologie bestaat uit welke drie structuren?',
      [
        'Leverarterie, portalader en galbuis',
        'Leverader, leverarterie en galbuis',
        'Sinusoid, hepatocyt en Kupffer cel',
        'Centraallobulaire ader, stellaat cel en galkanaal',
      ],
      0,
      'Elke portaltriade (in hoeken van leverlobuli) bevat een tak van leverarterie, portalader en galbuis die parallel lopen.',
    ],
  ],
  phd: [
    [
      'Botremodellering wordt gecoördineerd door welk moleculair signalpad geactiveerd door mechanische belasting?',
      [
        'Wnt/β-catenine via mechanotransductie',
        'Notch signalering in osteoblasten differentiatie',
        'Hedgehog signalering in osteoklasten activatie',
        'FGF receptor signalering in endochondrale osificatie',
      ],
      0,
      'Osteocyten voelen mechanische belasting via integrines en ionkanalen, activeren Wnt/β-catenine om sclerostine te onderdrukken en botvorming te bevorderen.',
    ],
    [
      'In de enthesis bevat gemineraliseerde fibrocartilage calciumhydroxyapatiet kristallen op welke hoek tot collageenvezels?',
      [
        '45 graden',
        'Evenwijdig (0 graden)',
        'Loodrecht (90 graden)',
        'Willekeurig (variabele hoeken)',
      ],
      0,
      'De geclassificeerde kraakbeenzone van enthesis heeft apatietkristallen op ~45° tot collageenvezels, wat een gegradeerde mechanische overgang creëert.',
    ],
    [
      'Draait de myosine kop tijdens powerstroke rond welk functioneel gebied?',
      [
        'Het nekgebied tussen domein en hefboomarm',
        'De ATP bindingzak in nucleotide bindingnauw',
        'De actine bindingsinterface op het onderste 50 kDa domein',
        'Het regeleiwitlichte keten aan het eind van hefboomarm',
      ],
      0,
      'De nekstreek (converter domein) van myosine werkt als hefboomschanier. Conformatiewijzigingen vergroten kleine ataire bewegingen tot grote verplaatsing.',
    ],
    [
      'De coronaire circulatie vertoont metabolische autoregulatie door welk primair mechanisme?',
      [
        'Adenosine verlaagt arterioolweerstand',
        'Myogeen respons op perfusiedrukveranderingen',
        'Sympathische systeemvasocontrictie',
        'Endotheliale stikstofmonoxide productie uit schuif',
      ],
      0,
      'Verhoogde hartspierstofwisseling putt ATP, genereert adenosine dat A2A receptoren op gladde spier activeert, wat vasodilatie veroorzaakt.',
    ],
    [
      'Fetale shunting via foramen ovale blijft door welk drukgradiëntmechanisme behouden?',
      [
        'Linkerkamer druk exceed rechterkamer, houdend septum primum klep open',
        'Rechterkamer druk exceed linkerkamer, forcerend bloed over defect',
        'De ductus venosus leidt bloed rechtstreeks naar linkerkamer',
        'Voorkeurspulmonale vasculaire dilatatie verhoogt links-naar-rechts shunting',
      ],
      0,
      'Het foramen ovale werkt als eenrichtingsklep: wanneer linkerkamerdruk na geboorte stijgt, sluiten de septum primum het gat.',
    ],
    [
      'Accessoire respiratiespieren, inclusief scalenen en sternocleidomastoid, hechten aan welke ribben?',
      [
        'Eerste en tweede ribben',
        'Vijfde en zesde ribben',
        'Achtste tot twaalfde ribben',
        'Alle ribben gelijk van eerste tot twaalfde',
      ],
      0,
      'Scalenen hechten aan ribben 1–2; sternocleidomastoid helpt rib 1. Deze spieren tillen de thoraxwand op tijdens geforceerde inademing.',
    ],
    [
      'De bloed-lucht barrière van alveolus bestaat uit hoeveel cellagen in totaal?',
      [
        'Drie: epitheel, basale membraan, endotheel',
        'Twee: alveolus epitheel en capillair endotheel alleen',
        'Vier: inclusief duidelijke intersticiële laag',
        'Vijf: met extra oppervlaktespanning producerende laag',
      ],
      0,
      'De barrière is ~0.5 μm dik: alveolus epitheel (type I cellen), gefuseerde basale membranen en capillair endotheel. Dunheid minimaliseert diffusieafstand.',
    ],
    [
      'In ventilatie-perfusie matching, welke anatomische factor creëert regionale bloedstroommverschillen?',
      [
        'Zwaartekracht geeft drukgradiënt door de long',
        'Differentiaalbepaling van pulmonale slagaders per lob',
        'Voorkeur bronchiaal dilatatie in apicale segmenten',
        'Ongelijke surfactantverspreiding over longgebieden',
      ],
      0,
      'Zwaartekracht creëert verticale drukgradiënt: apicale zones (lage perfusie) hebben hoge V/Q; basale zones (hoge perfusie) hebben lage V/Q.',
    ],
    [
      'Het darmepitheel wordt elke 3–5 dagen vernieuwd door stamcel proliferatie in welke cryptstructuur?',
      [
        'Lieberkuhn crypten',
        'Brunner klieren',
        'Peyer vlekken',
        'Plicae circulares',
      ],
      0,
      'Stamcellen in cryptbases delen, genereren enterocyten die villi omhoog migreren en worden afgevoerd aan top, handhaven continue epitheelomzetting.',
    ],
    [
      'De sphincter van Oddi regelt stroming in welk orgaan via de grote duodenum papil?',
      [
        'Duodenum, via de grote papil',
        'Jejunum via ligament van Treitz',
        'Maag via pylorische sfincter',
        'Ileum via ileocecale klep',
      ],
      0,
      'De sphincter van Oddi regelt gal en alvleesklier jusstroom in duodenum. Cholecystokinine veroorzaakt ontspanning tijdens vertering.',
    ],
    [
      'Wat detecteert het juxtaglomerulaire apparaat en wat leidt tot renineafscheiding?',
      [
        'Lage perfusiedruk of laag natrium bij macula densa',
        'Verhoogde filteringsdruk in Bowman capsule',
        'Verhoging van glomerulaire filtratie snelheid boven basaal',
        'Hyperkaliëmie gedetecteerd door granulaire cellen',
      ],
      0,
      'Baroreceptoren in afferente arteriolen voelen hypotensie; chemoreceptoren (macula densa) voelen lage NaCl. Beide activeren renineafscheiding.',
    ],
    [
      'De Müller (paramesonefros) buis geeft aanleiding tot welke vrouwelijke voortplantingsstructuren?',
      [
        'Fallopian buizen en baarmoeder',
        'Eierstokken en follikelcellen',
        'Vagina en vestibulaire klieren alleen',
        'Clitoris en grote vestibulaire klieren',
      ],
      0,
      'De Müller buizen smelten caudaal om baarmoeder en vagina te vormen; craniaal vormen zij fallopian buizen. Anti-Müller hormoon onderdrukt bij mannen.',
    ],
    [
      'Wat hecht het gubernaculum testis aan tijdens testiculaire daling?',
      [
        'Het scrotum via mesenchymale condensatie',
        'De epididymis via mesorchium',
        'De interne spermatische fascie rechtstreeks',
        'Het liesligament via cremaster spier',
      ],
      0,
      'Het gubernaculum is mesenchymale verdichting die testis aan de labioscrotal zwellingen verankert, gidst transinguinale daling via differentiële groei.',
    ],
    [
      'Uit welke vier embryologische bronnen desenvolt het diafragma?',
      [
        'Septum transversum, pleuroperitonale plooien, slokdarmmesenterium, lichaamswand',
        'Laterale plaat mesoderm, intermediaire mesoderm, somatische mesoderm en endoderm',
        'Paraxiale mesoderm alleen, gesegmenteerd in phrenische somites',
        'Neurale kristcellen migrerend ventraal van hersenstam',
      ],
      0,
      'Het diafragma\'s centrale tendon (septum transversum), crura (dorsaal slokdarmsmesenterium) en perifere musculatuur (lichaamsrand) vormen tegen ~week 8 zwangerschap.',
    ],
    [
      'In de vrouwelijke urethra, wat zijn parauretrale klieren (Skene klieren) embryologisch homoloog aan?',
      [
        'De prostaatklier',
        'Bulbourethrale (Cowper) klieren',
        'Littré urethralekelieren',
        'Zaadblaasjes',
      ],
      0,
      'Skene klieren ontstaan uit urethrale endoderm gelijk prostaat, dit maakt zij prostaat homologen. Zij scheidden zwak zuur vocht af.',
    ],
  ],
  professor: [
    [
      'Mechanische belasting induceert osteocyten dendrieten om signalen door welk extracellulair mechanisme over te dragen?',
      [
        'Vloeistofschuif activeert connexine-43, wat sclerostine verlaagt',
        'Direct contact tussen osteocytenprocessen en osteoklasten voorganger via RANKL downregulatie',
        'Verhoogde intersticiële vloeistofdruk triggert osteoprotegerine afscheiding van benliggende cellen',
        'Mechanische vervorming van integrine-rijke focale adhesies vrijstellende sequestered BMP-6',
      ],
      0,
      'Osteocyten dendrieten voelen vloeistofstroom door lacunocanaliculaire netwerken. Dit activeert Wnt signaling, verlaagt sclerostine en verhoogt OPG/RANKL verhouding.',
    ],
    [
      'De ultrastructurele geometrie van geclassificeerde fibrocartilage enthesis omvat apatietkristallen in voorkeur oriëntatie. Wat is gevolg van anisotropie?',
      [
        'Heterogene stress dissipeert energie aan het grensvlak',
        'Uniforme mineralisatie over zone voorkomt microbarst voortplanting in aangrenzend bot',
        'Georiënteerde kristallen verhogen wateropname, verbeteren viscoëlastische dempering',
        'Kristal anisotropie laat snelle adaptieve remodellering toe in antwoord op veranderde belastingsrichting',
      ],
      0,
      'Hoekige apatietkristallen (45° tot vezels) creëren gegradeerde stijfheid, verspreiden stress heterogeen en voorkomen catastrofale falen op pees-bot interface.',
    ],
    [
      'De myosine powerstroke genereert kracht via conformatiewijziging waar converter domein ~70° rond nekgebied draait. Wat maakt overgang energetisch gunstig?',
      [
        'Fosfaatafgifte verlaagt de pre-powerstroke energie',
        'ATP terugbinding stabiliseert onmiddellijk post-powerstroke toestand, drij overgang voorwaarts',
        'Actine binding verhoogt activeringsenergie omgekeerde reactie, maakt terugstappen verwaarloosbaar',
        'Thermische energie bij lichaamstemperatuur gelijk ~3 pN·nm werkuitvoering per slag',
      ],
      0,
      'Fosfaatafgifte verlaagt myosine naar lagere-energietoestand gustend powerstroke. ~50 kJ/mol energie van ATP hydrolyse maakt 70° draai exergoon.',
    ],
    [
      'De fetale ductus venosus laat placenta bloed hepatische sinusoïden passeren. Wat is embryologisch lot na geboorte en wat genetische factor regelt sluiting?',
      [
        'Vernauwt bij hogere portalflux, dan verwijderd door endotheel',
        'Blijft patent in 30% volwassenen als anatomisch variant',
        'Involueert via apoptose getriggerd door HIF-1α in antwoord verhoogde zuurstoftensie',
        'Mechanisch gesloten door navelstrengthrombose voor hepatische circulatie matuur',
      ],
      0,
      'De ductus venosus sluit functioneel uren na geboorte wanneer portaldruk stijgt. Endotheel proliferatie verwijdert tot ligamentum venosum in weken.',
    ],
    [
      'In coronaire autoregulatie wordt relatie tussen coronaire bloedstroom en hartspierstofwisseling constant gehouden. Welk arteriool mechanisme verklaar dit?',
      [
        'Adenosine uit ATP catabolisme activeert A2A, tegen vasoconstrictie',
        'Myogene mechanismen voelen transmulaire drukveranderingen via mechanoreceptor ionkanalen',
        'Endotheliale stikstofmonoxide productie proportioneel stofwisselingsnelheid',
        'Sympathische zenuwterugtrekking vermindert α-adrenergische toon tijdens verhoogde metabolische vraag',
      ],
      0,
      'Hartstofwisseling genereert adenosine als ATP gehydrolyseerd. Adenosine werkt op A2A receptoren om vasodilatatie, handhaving constant stroom-naar-metabolische vraag.',
    ],
    [
      'De scalenen (ventrale, middel, achter) innerveerd door welke cervicale zenuuwortels en mechanische rol gedurende geforceerde inademing?',
      [
        'Cervicaal 3–8; tillen ribben 1–2, verruimen thoraxinlaat',
        'Cervicaal 1–2 alleen; comprimeren thoraxkaviteit voor uitademing',
        'Thoracaal 1–4; stabiliseren mediastinum',
        'Cervicaal 5–7; drukken ribben 3–6 omlaag gedurende rustige ademen',
      ],
      0,
      'Scalenen (C3–C8) hechten aan ribben 1–2. Gedurende geforceerde ademhaling tillen zij ribben craniaal, vergroten superieure thoraxopening.',
    ],
    [
      'De pulmonale circulatie vertoont unieke naleggeneidsconstituering tegenover systemische circulatie. Hoe beïnvloedt zwaartekrachthydrostatische druk capillair rekrutering en regionale V/Q?',
      [
        'Top is ventilatie-beperkt; basis is perfusie-beperkt',
        'Apicale capillairen maximaal gerekruteerd; basale capillairen blijven ingeduwen wegens lage transmulaire druk',
        'Zwaartekracht heeft verwaarloosbaar effect; regionale V/Q verschillen worden geheel bepaald door bronchiaal toon',
        'Hydrostatische druk verhoogt capillair permeabiliteit uniform, vermindert diffusieafstand globaal',
      ],
      0,
      'Zwaartekracht creëert verticale hydrostatische gradiënten. Apicale zones hebben lage perfusie; basale zones hebben hoge capillair transmulaire druk en distensie.',
    ],
    [
      'Het kleine darmenepitheel vertoont proliferatie-differentiatie gradiënt met stamcellen in crypten delend elke 24–48 uur. Welke moleculaire factoren regelen transit vergroting?',
      [
        'Wnt hoog in crypten; BMP/TGF-β hoog op villi, tegengesteld',
        'Notch signalering uitsluitend in transit-amplifië cellen blokkeert verdere deling',
        'Hedgehog liganden afgezonderd apicaal verdrijven differentiëren cellen basaal',
        'FGF10 van mesenchymale fibroblasten stimuleert alle epitheliale proliferatie uniform',
      ],
      0,
      'Hoog Wnt in crypten bevordert stamcelle; verhoogd BMP op villi bevordert differentiatie. Dit tegengestelde gradiënt drijft richtingsmigratie en celfaat.',
    ],
    [
      'Galzuur-afhankelijke activatie van farnesoid X receptor (FXR) in ileal enterocyten triggert welke darme en hepatische terugkoppellussen?',
      [
        'FGF19 remt CYP7A1, wat galzuursynthese verlaagt',
        'Rechtstreekse hepatocyt activering van SREBP-2 verhoogt cholesterol opname en synthese',
        'Verminderde portal glucosesignalering downregulatoren hepatische lipogenese',
        'Ilale barrièreverstenging voorkomt secundaire galzuur absorptie, vermindert enterohepatal circulatie',
      ],
      0,
      'Ilale FXR activering triggert FGF19 afscheiding. FGF19 werkt op hepatische FGFR4 om SHP te induceren en CYP7A1 te onderdrukken, vermindert galzuursynthese.',
    ],
    [
      'Het tubuloglomerulaire feedback (TGF) mechanisme detecteert natriumchloride concentratiewijzigingen macula densa en modulen glomerulaire filtratiesnelheid?',
      [
        'NKCC2-opname geeft adenosine af, wat de afferente arteriool vernauwt',
        'Macula densa cellen voelen rechtstreeks angiotensin II in juxtaglomerulaire ruimte',
        'Verhoogde intraglomerulaire druk opent rechtstreeks mechanoreceptoren op granulaire cellen',
        'Prostaglandine E2 vrijgesteld van verzamelbuiscellen remt renine afscheiding systemisch',
      ],
      0,
      'NaCl opname via NKCC2 verhoogt metabolisme en purinerge signalering. ATP/adenosine veroorzaakt afferente arteriool vasocontrictie, vermindert GFR en renine afscheiding.',
    ],
    [
      'Anti-Müller hormoon (AMH), afgezonderd door Sertoli cellen, onderdrukt Müller buikontwikkeling in mannen via welke receptor en intracellulaire signalering?',
      [
        'Type II serine/threonine kinase receptor activeert SMAD2/3-SMAD4',
        'Estrogeen receptor β op Müller mesenchym, blokkeert paracrien Wnt signalering',
        'Notch signalering in mesonefros mesenchym triggert caspase-gemedieerde Müller buis apoptose',
        'TrkB tyrosine kinase receptor in ducaal epitheel activeert FoxA2-afhankelijke differentiatie in Wolffian structuren',
      ],
      0,
      'AMH bindt type II serine/threonine kinase receptoren (AMHR2), rekruteert type I receptoren (ALK2/3). SMAD2/3-SMAD4 activering blokkeert Müller lot genen.',
    ],
    [
      'Het gubernaculaire mesenchym van fetale testis expresseert welke groeifactoren en transcriptiefactoren bevorderend daling?',
      [
        'INSL3 van Leydig cellen activeert RXFP2, verhoogt desmine voor migratie',
        'BMP4 van coeloomisch epitheel drijft gubernaculaire ossificatie',
        'Sonic hedgehog van mesonefros mesenchym triggert apoptose-gedreven gubernaculaire resorptie',
        'GDNF van ureterische buis trekt testiculaire kiemcellen aan via RET signalering',
      ],
      0,
      'INSL3-RXFP2 signalering in gubernaculaire cellen regulaat desmine (myofibroblast merker) en migratiegen. Dit is essentieel voor testiculaire daling.',
    ],
    [
      'Het diafragma\'s musculatisering omvat ingroei van phrenische (C3–C5) en lagere intercostale (T7–T12) motorneuron axonen. Wat embryologisch proces verklaar duale innervatie?',
      [
        'Phrenische zenuw naar centrale tendon; intercostale zenuwen naar lichaamswandspier',
        'Diafragma ontstaat alleen uit paraxiale mesoderm, duaal innervatie weerspiegelt plurisegmentale myotoom basis',
        'Phrenische en intercostal zenuwen ondergaan uitgebreide commissurale verbindingen postnaal',
        'Lager cervicaal en thoracaal motorpool ondergaan Hox genafhankelijke migratie naar het zich ontwikkelende diafragma',
      ],
      0,
      'Duaal innervatie weerspiegelt ontwikkelingbasissen: phrenische zenuw innerveer centrale tendon (mesoderm nabij hart); intercostal zenuwen innerveer musculaire periferie.',
    ],
    [
      'Het vrouwelijk orgasme omvat gecoördineerde ritmische contracties (0.8 Hz) van baarmoeder, vagina en beklemmingsspieren. Wat is fysiologische basis verhoogde geslachtsbloedstroom?',
      [
        'NO/VIP vasocongestie en adrenergische myotonia; norepinephrine drijft refracteraire periode',
        'Estrogeen upgradeert α-adrenergische receptoren, veroorzaakt vasocontrictie en myotonia omgekeerd door oxytocine gedurende orgasme',
        'Parasympathische vasodilatie gevolgd door sympathische remming gedurende refracteraire periode',
        'Pelavische splanchnische zenuwstimulatie triggert rechtstreeks ritmische baarmoedercontracties onafhankelijk hormonale factoren',
      ],
      0,
      'NO/VIP veroorzaken vasocongestie en bloedstroom; sympathische toon produceert myotonia. Post-orgasme, verhoogde norepinephrine veroorzaakt adrenergische-gemedieerde remming.',
    ],
    [
      'In het zich ontwikkelende cardiovasculaire systeem ondergaan endotheelcellen EMT om neural kristaf te vormen. Welk transcriptiefactornetwerk beheerst endocardiale kussensinvasie?',
      [
        'Snail/Slug remmen E-cadherin, met Wnt/β-catenine en Notch',
        'Rechtstreeks MyoD-afhankelijke myogene differentiatie van endotheelcellen in cardiomyocyten',
        'HIF-1α-afhankelijke metabolische verschuiving van oxidatieve fosforylatie naar glycolyse',
        'Krüppel-achtige factor 4 (KLF4) reactivering van pluripotent genexpressieprogramma',
      ],
      0,
      'Snail/Slug onderdrukken E-cadherin, toestaan endotheel migratie. Wnt/β-catenine en Notch samen drijven mesenchymale differentiatie in kussenweefselvorming.',
    ],
  ],
};
