import type { CategoryContent } from '../row.js';

export const ASSYRIA: CategoryContent = {
  bscba: [
    [
      'Welke Assyrische koning bouwde de eerste permanente hoofdstad in Ashur na het consolideren van zijn macht en richtte daar een blijvend koninklijk paleisjcomplex in?',
      ['Shamshi-Adad I', 'Ashur-uballit I', 'Tiglath-Pileser I', 'Adad-nirari I'],
      0,
      'Shamshi-Adad I (r. 1814-1791 BCE) was een vroege expansionist die een territoriale staat schtte. Hij bouwde monumentale architectuur in Ashur, hoewel zijn verovering niet lang standhield. Zijn regering markeerde een overgang van stadstaat naar regionale macht.',
    ],
    [
      'De Assyrische praktijk om paleiswanden te bekleden met monumentale stenen reliëfs van koninklijke jachten, veldslagen en religieuze ceremonies diende welke primaire functie buiten decoratie?',
      ['Propaganda, die koninklijke macht en goddelijke gunst aan bezoekers en onderdanen toonde', 'Een religieus ritueel om het paleis aan beschermende goden te binden', 'Een administratief register voor het bijhouden van belastingbetalingen en volkstelling', 'Een historische kroniek bedoeld als vervanging voor schriftelijke cuneïforme records'],
      0,
      'Paleisstenen reliëfs dienden als visuele propaganda, die koninklijke overwinningen, jachtkunst en religieuze vroomheid aan alle bezoekers toonden. De scènes waren in narratieve sequenties over meerdere registers gerangschikt. Dit visuele boodschappen versterkten koninklijke autoriteit.',
    ],
    [
      'Welke Assyrische koning staat bekend om zijn uitgebreide militaire campagnes tegen talrijke vijanden in de Levant, en omdat hij het Black Obelisk monument liet maken?',
      ['Shalmaneser III', 'Shalmaneser II', 'Shalmaneser V', 'Shalmaneser I'],
      0,
      'Shalmaneser III (r. 858-824 BCE) ondernam regelmatige campagnes in Syrië-Palestina en staat vooral bekend om de Black Obelisk, een gesneden stenen monument waarop zijn militaire prestaties en tributebringers uit verschillende veroverde volkeren stonden afgebeeld.',
    ],
    [
      'De god Adad, bekend als de Assyrische stormgod, werd geassocieerd met welk natuurverschijnsel dat hem in landbouw- en militaire contexten belangrijk maakte?',
      ['Donder, bliksem en regen', 'De overstroming van rivieren', 'Zonsverduisteringen en hemelse voortekenen', 'Woestijnwinden en zandstormen'],
      0,
      'Adad beheerste regen en stormen, wat hem vitaal maakte voor landbouwwelvaart in Mesopotamië\'s semi-ariide klimaat. Zijn donder en bliksem hadden ook metaforische betekenis in oorlogsvoering. Koningen riepen hem aan voor strijd.',
    ],
    [
      'De Assyrische militaire innovatie van het gebruik van gespecialiseerde beleg-uitrusting met rammen, torens en georganiseerde aanvallsteams is goed gedocumenteerd op paleisstenen reliëfs. Welke heersers regering toonde de meeste uitgebreide afbeeldingen van belegeringsoorlogsvoering in gesneden steen?',
      ['Sennacherib', 'Ashurnasirpal II', 'Ashurbanipal', 'Tiglath-Pileser III'],
      0,
      'Sennacheribs paleisstenen reliëfs in Nineveh wijdde uitgebreide narratieve sequenties aan belegeningsscènes, vooral de beroemde belegering van Lachisch. Deze reliëfs zijn onder de meest informatieve Assyrische bronnen voor het reconstrueren van belegeringstractieken.',
    ],
    [
      'Nineveh\'s positie als grote stad langs welke rivier maakte het strategisch belangrijk voor handel en militaire logistiek in Mesopotamië?',
      ['De Tigris-rivier', 'De Eufraat-rivier', 'De Grote Zab-rivier', 'De Diyala-rivier'],
      0,
      'Nineveh lag aan de oostoever van de Tigris-rivier, wat het toegang gaf tot watertransport voor goederen en legereenheden. Deze locatie maakte het een ideale hoofdstad voor machtsuiting naar het zuiden en westen. De Tigrisvallei bood natuurlijke handelsroutes.',
    ],
    [
      'Cuneïforme schrijvers in Assyrië registreerden koninklijke decreten op kleitabletten. Welk materiaal werd meestal gebruikt voor de stylus van de schrijver die deze indrukken maakte?',
      ['Een rietje onder een hoek gesneden', 'Een in vorm gesneden houten stok', 'Een bot instrument geslepen tot een punt', 'Een bronzen of koperen gereedschap'],
      0,
      'Mesopotamische schrijvers gebruikten riet uit moerassen, gesneden onder een hoek om wigvormige indrukken in zachte klei te maken. Dit eenvoudige gereedschap bewees duurzaam en effectief voor duizenden jaren van vastlegging. De techniek vereiste training.',
    ],
    [
      'Welke Assyrische koning ondernam massale bouwprojecten in Kalhu (Nimrud), waaronder de bouw van een paleiszaal en complex poortenstelsel?',
      ['Ashurnasirpal II', 'Ashur-dan II', 'Tiglath-Pileser III', 'Sargon II'],
      0,
      'Ashurnasirpal II (r. 883-859 BCE) maakte Kalhu zijn primaire koninklijke residentie en investeerde zwaar in monumentale bouw daar, waaronder paleizen, tempels en verdedigingswerken. Zijn bouwprogramma vestigde Kalhu als belangrijk Assyrisch machtcentrum.',
    ],
    [
      'De Assyrische gewoonte van het registreren van militaire prestaties en ontvangen tributen op monumentale stèles en obelisken diende welk publiek?',
      ['Toekomstige heersers en nageslacht, voor een blijvend eervolle geschiedenis', 'Buitenlandse vazallen, hen dwingend Assyrische macht te onthouden', 'Priesters voor tempelrituelen als naslagrewerk', 'Schrijversscholen als leerteksten voor cuneïforme leerlingen'],
      0,
      'Monumenten verkondigen prestaties blijvend aan heersers, onderdanen en buitenlandse bezoekers. Steen is duurzamer dan papyrus. Plaatsing in zichtbare stadsgelegenheden zorgde voor voortdurende blootstelling.',
    ],
    [
      'Welke god, geassocieerd met schrijven en schrijverwijsheid, had een speciale plaats aan het Assyrische hof waar geletterde ambtenaren en geleerden dienden?',
      ['Nabu', 'Enki', 'Nisaba', 'Dumuzid'],
      0,
      'Nabu, god van schrijven en wijsheid, was patroon van schrijvers en geleerden in heel Mesopotamië, met bijzondere prominentie aan het Assyrische hof waar geletterde elite de kroon dienden. Tempels aan Nabu waren huisvesting voor schrijversscholen en bibliotheekcolecties.',
    ],
    [
      'Welk materiaal werd meestal gebruikt in Assyrische militaire wapenuitrusting om bescherming tegen pijlen en wapens in gevechten te geven?',
      ['IJzer en brons verwerkt tot borststukken en schubben', 'Dikke leerondersteuning versterkt met plantaardig materiaal', 'Verharde klei en gebakken bakstenen stukken', 'Geweven riet behandeld met boomhars'],
      0,
      'Assyrische soldaten droegen wapenuitrusting van ijzer en brons, verwerkt tot schubben of borststukken. Metallurgische bewerking in Mesopotamië was ver genoeg gevorderd voor massaproductie. Rijke soldaten konden zich uitgebreider bronzen stukken veroorloven.',
    ],
    [
      'Het Assyrische systeem van wegen en wegstations onderhouden door de koninklijke regering diende vooral welke bestuurlijke en militaire functie?',
      ['Snelle troepenbewegingen en communicatie over het imperium', 'Handelsregulering en belastingheffing van kooplieden', 'Religieuze pelgrimsroutes naar grote tempels', 'Landbouwonderzoek en volkstellingsvergaring'],
      0,
      'Het wegennet maakte snelle troependeploying en koninklijke correspondentie mogelijk via relaisstations met verse paarden en voorraden. Deze infrastructuur was kritisch voor het controleren van verre provincies. Bodes konden in dagen honderden mijlen afleggen.',
    ],
    [
      'De rituele praktijk van Assyrische koningen die uitgebreide jachtscènes in paleisstenen reliëfs presenteren weerspiegelde welk aspect van koninklijke ideologie?',
      ['Demonstratie van de persoonlijke dapperheid van de koning en heerschappij over de natuur', 'Religieuze verplichting aan bosgodheden voor oogstzegenging', 'Militaire trainingsregistratie voor soldaten', 'Economische boekhouding van vlees verdeeld aan het hof'],
      0,
      'Jachtreliëfs toonden de koning als machtig en in staat gevaarlijke dieren te beheersen, versterkend zijn imago van sterkte en geschiktheid tot heerschappij. Exotische jachten toonden koninklijke toegang tot verre landen. Deze scènes dienden propagandadoelen.',
    ],
    [
      'Assyrische koningen namen de titel "koning van het universum" aan, deels om militaire expansie te rechtvaardigen als vervulling van welk ideologisch concept?',
      ['Lotsbeschikking door goden om alle landen onder Assyrische heerschappij te brengen', 'Natuurlijke superioriteit van Mesopotamische volkeren boven vreemdelingen', 'Verplichting Mesopotamische landbouwtechnieken uit te breiden', 'Verplichte tributes te verzamelen voor tempelkonstruktie'],
      0,
      'Assyrische ideologie beschreef imperiale expansie als goddelijk bevolen, met de koning als instrument der goden om de wereld te verenigen. Dit theologisch rechtvaardigen maakte verovering als kosmische noodzakelijkheid verschijnen. Religieuze teksten versterkten dit zicht.',
    ],
    [
      'Welke van het volgende claimden Assyrische koningen NIET meestal in hun koninklijke inscripties om macht en goddelijke gunst uit te stijgen?',
      ['Persoonlijk auteurschap van juridische codes die het imperium regelden', 'Succesvolle militaire campagnes en territoriale verovering', 'Bouw van monumentale tempels en paleizen', 'Zegrijke jachten en heerschappij over gevaarlijke dieren'],
      0,
      'Assyrische koningen verkondigen regelmatig militaire overwinningen en bouwprojecten, maar claimden zelden juridische code auteurschap zoals Babylonische koningen deden. Zij presenteerden zich als krijgers en bouwers, niet als wetgevers. Administratieve rechtvaardigheid viel aan benoemde ambtenaren.',
    ],
  ],
  msc: [
    [
      'Welke Neo-Assyrische koning verliet Kalhu (Nimrud) als primaire koninklijke residentie en bouwde een geheel nieuwe hoofdstad, Dur-Sharrukin, slechts om hij bijna onmiddellijk na zijn dood opnieuw verlaten te worden?',
      ['Sargon II', 'Ashurnasirpal II', 'Tiglath-Pileser III', 'Shalmaneser V'],
      0,
      'Sargon II (r. 722-705 BCE) stichtte Dur-Sharrukin als doelgebouwde hoofdstad, maar zijn zoon Sennacherib verschoof het hof bijna onmiddellijk naar Nineveh na Sargons dood. Sargons begraving weg van huis las men als slecht voorteken. Dur-Sharrukin was een vroege belangrijke opgravingsplek.',
    ],
    [
      'Veel tabletten uit Ashurbanipal\'s bibliotheek in Nineveh dragen een formulaïsche schrijversnota die de koninklijke eigendom beweert en iedereen vloekt die het tablet beschadigt of steelt. Dergelijke eigendomsnota\'s worden technisch wat genoemd in de Assyrologie?',
      ['Colofon', 'Incipit', 'Docket', 'Envelopetablet'],
      0,
      'Een colofon is de sluitnota op een cuneïforme tablet. Ashurbanipal\'s bibliotheekcolofons zijn uitgebreide, en bevatten vaak de naam van de koning en vervloekingen tegen beschadiging of diefstal. Deze colofons bevestigen Ashurbanipal\'s eigen initiatief voor verzameling.',
    ],
    [
      'De samengestelde beschermingsfiguren geplaatst aan Assyrische poortgangen, combin een menselijk hoofd met een stier- of leeuwenlichaam en vleugels, zijn bekend onder welke naam?',
      ['Lamassu', 'Anzu', 'Apkallu', 'Kuribu'],
      0,
      'Lamassu-figuren werden in paren uitgehakt aan paleizen en stadpoorten in Nimrud, Khorsabad en Nineveh om kwaad af te weren en koninklijke macht uit te stralen. Ze werden dikwijls met vijf poten gesneden voor optisch effect van volledigheid. Apkallu verwijst naar geveilde figuren voor rituelen.',
    ],
    [
      'Welke Assyrische koning wordt vooral herinnerd voor het belegeren van Jeruzalem, het vernietigen van Babylon als vergelding voor herhaalde opstand, en voor paleisstenen reliëfs van zijn belegering van Lachisch?',
      ['Sennacherib', 'Sargon II', 'Esarhaddon', 'Ashurbanipal'],
      0,
      'Sennacherib (r. 705-681 BCE) campagneerde tegen Juda in 701 BCE en veroverde Lachisch maar faalde Jeruzalem in te nemen. Hij plunderde Babylon in 689 BCE, een religieus schokacte. Zijn zoon Esarhaddon herbouwde het later. Sennacherib werd vermoord door één van zijn zonen.',
    ],
    [
      'Welke Assyrische koning ondernam een groot herbouwproject van Babylon nadat zijn vader het vernield had, en herstelde tempels ervan en regeerde zelf kort als koning van Babylon naast zijn Assyrische troon?',
      ['Esarhaddon', 'Sennacherib', 'Shalmaneser III', 'Adad-nirari II'],
      0,
      'Esarhaddon (r. 681-669 BCE) erfde beschadigde relaties met Babylon en reageerde met massief herbouw van tempels. Hij benoemde zijn zoon Ashurbanipal als erfgenaam en gaf zijn andere zoon Shamash-shum-ukin het koningschap van Babylon. Esarhaddon breidt Assyrische macht tot Egypte uit.',
    ],
    [
      'Het bereik van het Neo-Assyrische imperium hing zwaar af van een systeem van provincies geleid door benoemde gouverneurs direct rapporterend aan de koning, een structuur vooral geassocieerd met hervorming door welke heersers?',
      ['Tiglath-Pileser III', 'Ashurnasirpal II', 'Sargon II', 'Shalmaneser III'],
      0,
      'Tiglath-Pileser III (r. 745-727 BCE) herstructureerde veroverde gebieden in kleinere provincies onder koninklijk benoemde ambtenaren in plaats van lokale dynaste. Hij breidt massale deportatie uit. Deze hervormingen zetten Assyrië om in een echt territoraal imperium.',
    ],
    [
      'Ashurbanipal\'s regering werd verstoord door burgeroorlog tegen zijn eigen broer, die als onderkoningin in Babylon heerste en een grote opstand tegen Assyrische suprematie leidde. Wat was de naam van deze broer?',
      ['Shamash-shum-ukin', 'Sin-shar-ishkun', 'Ashur-etil-ilani', 'Sin-shumu-lishir'],
      0,
      'Shamash-shum-ukin, door vader Esarhaddon als Babylonisch koning benoemd, veracht zijn ondergeschikte status en bouwde coalitie tegen Ashurbanipal rond 652 BCE. Na langdurige belegering onderdrukte deze de opstand. De episode toont fragiliteit.',
    ],
    [
      'Welke godheid stond aan het hoofd van het Assyrische pantheon en diende als beschermgod van de stad die het imperium zijn naam gaf?',
      ['Ashur', 'Marduk', 'Enlil', 'Ninurta'],
      0,
      'Ashur was beschermgod van de stad Ashur op de Tigris, verheven tot hoofd van het staatspantheon naarmate de stad een imperiaal centrum werd. Dit verschilde van Babylon, waar Marduk oppermacht hield. Assyrische koningen herschreven soms scheppingsmythen.',
    ],
    [
      'De Mesopotamische godin geassocieerd met liefde, seksualiteit en oorlog, wiens planetaire tegenhanger Venus was en wiens afdaling naar de onderwereld bekend is, was voor Assyriërs en Babyloniërs als wie bekend?',
      ['Ishtar', 'Ereshkigal', 'Ninlil', 'Gula'],
      0,
      'Ishtar (Akkadische vorm van Sumerische Inanna) combineerde erotische liefde en oorlogsvoering. Haar koppeling aan Venus gaf haar symbolische verbinding met omkering en transformatie. Assyrische koningen riepen Ishtar aan als oorlogsgoddin.',
    ],
    [
      'De praktijk van strategische massale deportatie van veroverde volkeren, verbrekend lokale identiteiten terwijl bevolkingen over het imperium werden verplaatst, is meest uitgebreid gedocumenteerd in welke periode van Assyrische geschiedenis?',
      ['Neo-Assyrisch, ruwweg 912-609 BCE', 'Midden-Assyrisch, ruwweg 1365-935 BCE', 'Oud-Assyrisch, ruwweg 1975-1378 BCE', 'Laat-Assyrisch, na 609 BCE'],
      0,
      'De Neo-Assyrische periode, vooral van Tiglath-Pileser III af, systematiseerde massale deportatie als bestuurstool, verplaatsing van tienduizenden volkeren om lokaal verzet te verzwakken. Cuneïforme records documenteren deportatielijsten. Dit beleid verscherpte onder opeenvolgende koningen.',
    ],
    [
      'Het Aramese taal verdreef geleidelijk Akkadisch als lingua franca van het Neo-Assyrische imperium ondanks militaire suprematie, welke ontwikkeling weerspiegelt dit?',
      ['Praktische voordelen van alfabetisch schrift over cuneïforme in dagelijkse vastlegging', 'Doelbewuste Assyrische politiek om Akkadische scholastische tradities te onderdrukken', 'Religieuze invloed van Aramese godheden op Assyrisch hof theologie', 'Militaire druk van Aramese stamverbonden'],
      0,
      'Aramees alfabetisch schrift was sneller aan te leren dan cuneïforms complex systeem. Zelfs Assyrische ambtenaren gebruikten het voor routinetaken. Dit weerspiegelt praktische efficiëntie boven politieke voorkeur.',
    ],
    [
      'De zogenaamde "tributeprocressies" uitgebreid afgebeeld in Neo-Assyrische paleisstenen reliëfs dienden welke primaire functie buiten eenvoudige registratie van inkomende goederen?',
      ['Visuele beweegreden van universele onderdaning aan Assyrische koninklijke autoriteit', 'Boekhoudkundig register voor belastingambtenaren', 'Historische records van individuele vastalstaten', 'Religieus documentatie voor tempel votiefen'],
      0,
      'Tributescènes toonden verre heersers zichzelf vernederend voor de Assyrische koning, die universele macht verkondigde. Deze reliëfs waren zichtbaar voor ambtenaren en delegaties. Dit visuele boodschappen was even belangrijk.',
    ],
    [
      'Welk scholastisch perspectief betoogt dat de relatie tussen Assyrische vasalkoningen en het imperiaal centrum minder puur exploitatief was dan dikwijls afgebeeld?',
      ['Sommige vassalen handhaafden echte religieuze kulten aan Assyrische godheden en deelnamen in Akkadische traditie', 'Vasalkoninkrijken werden uiteindelijk volledige onafhankelijkheid verleend', 'Tributebetalingen werden vrijwillig verhoogd door vassalen om keizerlijke gunst', 'Vassalen werden routinematig bevorderd tot adviseursfuncties in Nineveh hof'],
      0,
      'Vasalkoningen die Assyrische religieuze praktijken aannamen suggeren culturele integratie voorbij onderwerping. Sommige geleerden betogen dit toont een complex patroon-klant relatie. Echter, macht bleef ongelijk.',
    ],
    [
      'De praktijk van vestiging van een gestandaardiseerde "Assyrische" stijl in monumentale architectuur, inscripties en kunstmotieven over het imperium diende welk bestuursdoel?',
      ['Visuele uniformiteit die keizerlijke eenheid en Assyrische culturele dominantie over veroverde gebieden beweert', 'Constructiekosten reducering via gestandaardiseerde ontwerpen', 'Training van lokale architecten volgens regionale normen', 'Eerbetoon aan individuele regionale kunsttradities'],
      0,
      'Assyrische architecturale normen over het imperium versterkten visueel integratie in een eengemaakt politiek stelsel. Gestandaardiseerde stijlen maakten het imperium visueel herkenbaar. Dit esthetische uniformiteit vulde militaire integratie aan.',
    ],
    [
      'Welke Neo-Assyrische koning\'s regering zag het imperium zijn grootste territoriale omvang bereiken voordat interne conflicten en externe druk de snelle verval begon?',
      ['Ashurbanipal', 'Sennacherib', 'Tiglath-Pileser III', 'Esarhaddon'],
      0,
      'Ashurbanipal\'s regering (668-631 BCE) markeerde het imperium\'s grootste territoriale omvang, uitstrekkend van Egypte naar de Perzische Golf. Zijn opvolgers troffen interne successieconflicten. Binnen generatie na zijn dood stortte het imperium ineen.',
    ],
  ],
  phd: [
    [
      'Het Assyrische koninklijke verplichtingsstelsel dat onderdanen tot arbeid of militaire dienst voor de kroon dwong, onderscheiden van belasting in zilver of goederen, wordt in cuneïforme administratieve teksten genoemd door welke term?',
      ['Ilku', 'Kudurru', 'Sattukku', 'Zukru'],
      0,
      'Ilku was een dienstplicht—militair of arbeid—verschuldigd voor door koninklijke gunst verleende land. Dit parallelle systeem liet de staat arbeid mobiliseren zonder zilver te betalen en diende als ingebed landobligatie.',
    ],
    [
      'De uitgebreide loyaliteitseeden opgelegd door Esarhaddon aan vasalheersers om zijn gekozen successie te verzekeren, overlevend in meervoudige cuneïforme kopieën waaronder tablet gevonden aan Tell Tayinat, zijn algemeen bekend onder welke naam?',
      ['De Vasalverdragen van Esarhaddon', 'De Sfire Verdragen', 'De Amarna Correspondentie', 'Het Sultantepe Archiefonderdeel'],
      0,
      'De Vasalverdragen van Esarhaddon (672 BCE) eisten loyaliteit jegens Ashurbanipal en Shamash-shum-ukin. Tell Tayinat kopie toonde eedteksten in tempels van vasalstaten. De verdragen vertonen opvallende structuurparallellen.',
    ],
    [
      'De slag van 853 BCE waarin een coalitie van Levantijnse staten waaronder Israël onder Ahab Shalmaneser III\'s oprukkend Assyrisch leger onderstelde, beschreven in Assyrische koninklijke inscripties hoewel uitkomst betwijfeld, werd bevochten nabij welke plaats?',
      ['Qarqar', 'Megiddo', 'Carchemish', 'Hazor'],
      0,
      'De Slag van Qarqar (853 BCE) tussen Shalmaneser III en een coalitie onder Hadadezer, met Ahab\'s strijdwagens. Shalmaneser claimt zege, maar het Assyrische leger veroverde de regio pas jaren later. Eerste getoetste Israëlische moment in externe bronnen.',
    ],
    [
      'De Assyrische praktijk van massale bevolkingsoverdracht, gebruikt om lokale politieke identiteiten te breken en geschoold arbeid over het imperium te herdelen, is meest nauw geassocieerd met intensivering onder welke beleidsvoerende hervormerking?',
      ['Tiglath-Pileser III', 'Sargon II', 'Ashurnasirpal II', 'Sennacherib'],
      0,
      'Tiglath-Pileser III systematiseerde deportatie, verplaatsend populaties in tienduizendtallen per campagne om lokale identiteiten te breken. Deporteerden werden als functionerende gemeenschappen hergeplaatst, productief voor het imperium.',
    ],
    [
      'De Assyrische geleerden die hemelse en aardseverschijnselen voor het koninklijke hof vertolkten trokken zwaar op een kanonieke tekstuele traditie. Welk voorteken compendium vormde de grondslag van hemelse voorzeggingen aan het hof van Ashurbanipal?',
      ['Enuma Anu Enlil', 'Shumma Izbu', 'Shumma Alu Ina Mele Shakin', 'Bit Meseri'],
      0,
      'Enuma Anu Enlil was het meester compendium van hemelse voortekenen, met veel tabletten overlevend aan Nineveh. Neo-Assyrische geleerdebrieven citeren het direct, toonend kanonieke status. Shumma Izbu dekte afwijkend-geboorte voortekenen. Shumma Alu richtte zich op aardse verschijnselen.',
    ],
    [
      'Het Neo-Assyrische dateringstelsel dat elk jaar met de naam van roterend koninklijk of elite-ambtenaar identificeerde in plaats van regeneratiejaarvellen, gebruikte ambtenaren bekend onder welke titel?',
      ['Limmu', 'Sukkallu', 'Rab shaqe', 'Turtanu'],
      0,
      'Het Limmu-stelsel wijdde elk jaar aan een ambtenaar, getrokken in rotatie uit hoge rangen inclusief de koning zelf. Administrative en juridische documenten dateren gebeurtenissen door het jaar\'s Limmu-ambtenaar naam. Limmu-lijsten in de Assyrische Eponiemkroniek staan precies chronologie toe.',
    ],
    [
      'De Nimrud-ivoren, enorme schat van gesneden ivoormeubelbeslagen en decoratiepanelen opgegraven uit Assyrische paleisvindplaatsen, zijn kunsthistorisch betekenisvol vooral omdat zij aantonen wat?',
      ['Sterke stilistische invloed van Fenicische en Syrische werkplaatsen in een Assyrische imperiaal context', 'Eerder onbekende zuiver inheemse Assyrische ivoorsculptuurschool zonder externe invloed', 'Vroegste bekende ivoorbelegring in Mesopotamische meubelen, voordat Sumerische voorbeelden', 'Direct Egyptische fabricage en export van gereedgemaakte stukken naar Assyrië zonder lokale aanpassingen'],
      0,
      'Nimrud-ivoren tonen motieven uit Syrische en Fenicische kunst—tribut, roven of commissies van Levantijnse ambachtslieden. Dit mengsel helpt Fenicische en Noord-Syrische decoratieve kunsttraditie reconstrueren.',
    ],
    [
      'De Til-Tuba-relief gesneden voor Ashurbanipal\'s paleis toont de Assyrische overwinning over welke rivaal macht aan de Slag van de Ulai-rivier, een gebeurtenis zo belangrijk dat dood van verslagenkonin gruwelijke detail wordt afgetoond?',
      ['Elam', 'Urartu', 'De Meders', 'Egypte (de Koeshitische Vijfentwintigde Dynastie)'],
      0,
      'De Til-Tuba-relief gedenkt Ashurbanipal\'s 653 BCE overwinning over Elam aan de Slag van de Ulai-rivier, toont Elamitische koning Teumman\'s dood in grafische narrrative detail. De relief toont afgehakte koppen en Elamitische soldaten verdrinken in de rivier.',
    ],
    [
      'De uiteindelijke instorting van het Assyrische imperium in 612 BCE, met vernietiging van Nineveh, werd uitgevoerd door coalitie combineerend de Meders met welke andere grote macht?',
      ['De Neo-Babyloniërs onder Nabopolassar', 'De Elamieten onder Teumman\'s opvolgers', 'De Lydiërs onder Alyattes', 'De Egyptenaren onder Psamtik I'],
      0,
      'Nabopolassar vestigde zich als koning in Babylon in 626 BCE en alliantie met Medisch koning Cyaxares om gezamenlijk Nineveh in 612 BCE beleg en vernietigen. Deze alliantie werd bevestigd door dynastiek huwelijk. De plundering was grondige. De Babylonische Kroniekletters zijn waardevolle bronnen.',
    ],
    [
      'De Midden-Assyrische Wetten, set cuneïforme juridische tablets opgegraven aan Ashur en meestal gedateerd rond 14e-11e eeuwen BCE, wordt bijzonder gewaardeerd door geslacht- en familiewethistorici voor ongewoon gedetailleerde bepalingen over welk onderwerp?',
      ['Juridische status, sluierplichting en eigendomsrechten van vrouwen', 'Schuldslavernij contracten en rentetalingplafonds op landbouwleningen', 'Procedures voor bijzetting van grensgeschillen tussen tempeleigendommen', 'Regelingen voor vrijlating van krijgsgevangenen'],
      0,
      'Tablet A van de Midden-Assyrische Wetten is dicht met regels onderscheidend welke vrouwencategorieën in publiek moesten sluieren, samen met strenge straffen voor mishandeling en matrimoniale eigendomsgeschillen. Dit maakt het een rijke bron voor vrouwenrechtspositie reconstructie in Mesopotamië.',
    ],
    [
      'De Neo-Assyrische rechtspraktijk van "afgeslagen oren" of "afgeslagen handen" straffen gerapporteerd in bepaalde administratieve teksten weerspiegelt welk aspect van Assyrische rechtvaardiging?',
      ['Gedifferentieerde straffen geschaald naar sociale status, met elite misdadigers humiliation in plaats van executie', 'Doelbewust beleid van fysieke verstumming gericht op slavenpopulaties uitsluitend', 'Religieuze verplichting aan Shamash vereisend zichtbare transformatie van misdadigers', 'Mislukt vroeg juridisch hervormen snel na implementering verlaten'],
      0,
      'Assyrische teksten registreren getrapt straffen: lagere status misdadigers verstumming, hogere rangen boetes of verbanning. Deze zijn zichtbaar in administratieve tablets. Dit weerspiegelt statusbewuste juridische denken.',
    ],
    [
      'Het fenomeen van Neo-Assyrische koninklijke inscripties doelbewust onderdrukkend of uitwissend vorige koning verwijzing is meest duidelijk zichtbaar in Sennacherib\'s rekening van Babylon\'s vernietiging. Wat weerspiegelt dit?',
      ['Doelbewuste "damnatio memoriae"-achtige praktijk ontkenning van gelegitimeerde voorganger', 'Technische schrijvingsconsventie zonder werkelijke politieke gevoelen', 'Babylonische invloed op Assyrische geschiedenisschrijvingspraktijken', 'Inspanning om monumental tekstfysieke maat te reduceren'],
      0,
      'Sennacherib vermeed opvallend noeming van zijn vader Sargon II ondanks Sargon\'s grootte, mogelijk omdat Sargon in slag stierf weg van huis, gelezen als slecht voorteken. Deze uitwissing delegitimeerde zijn regering. Dit gat in het record was zelf politieke boodschapping.',
    ],
    [
      'De kleitablet voorteken-rapporten verzonden door geleerden en ambtenaren aan Neo-Assyrische koningen betreffende hemelsverschijnselen lieten regelmatig welk kenmerk weg dat standaard in ander Assyrisch administratief overleg verschijnt?',
      ['De dateringstelsels (Limmu jaar-identificaties of regeringsjaren)', 'Formele groeten en gebeden voor lange koningsleven', 'Verwijzingen naar schrijver\'s familie of huishouding', 'Instructies voor archivering of tablet opslag'],
      0,
      'Voorteken-rapporten naar de koning ontbreken doorgaans dateringstelsels ongelikt administratieve correspondentie, zich focusend op hemelsverschijnselen en interpretatie. Dit suggereert onmiddellijkheid belangrijk was meer dan nauwkeurigheid. Het contrast benadrukt divination spoedige noodzaak.',
    ],
    [
      'De praktijk van selectief kopiëring of "redactie" van cuneïforme teksten in Ashurbanipal\'s bibliotheek, soms weglatend secties van mythen of narratieven, wordt geïnterpreteerd als weerspiegelend wat?',
      ['Doelbewuste curatie om bepaalde theologische boodschappen te benadrukken terwijl competitieve versies worden onderdrukt', 'Onopzettelijk beschadiging aan tablets tijdens Nineveh\'s plundering', 'Schrijveersfouten ontstaan uit snelle kopiewerking onder tijdsdruk', 'Religieuze verbod tegen hele tekstvervoering woordelijks'],
      0,
      'Sommige Ashurbanipal bibliotheekteksten tonen tekenen van doelbewuste rediging, secties weglatend mogelijks om koningsideologie uit te lijnen of alternatieven te onderdrukken. Deze curatie vormde welke mytheversies overleefden. Het patroon suggereert doelbewuste selectie ondanks moeilijkheden.',
    ],
    [
      'Het zogenaamde "vervangingskonings ritual" gedocumenteerd in Mesopotamische geleerdebrieven en Enuma Anu Enlil voortekenen aanroepend betrokken enthroning van burger tijdelijk. Wat was het ritueel\'s onderliggende doel?',
      ['Absorptie van voorspeld koninklijk onfortuin op vervanger zodat echte koning beschermd kon blijven', 'Test van hofambtenaren loyaliteit door valse kroning blootstelling', 'Onderwijzing echte koning over bescheidenheid via burgerbrief waarneming', 'Goddelijke gunst meer gelijk over bevolking door ceremoniële verhoging verdelen'],
      0,
      'Wanneer voortekenen ramp voor echte koning voorspelden, werd vervanger verheven ramp absorptie, dan discreet verwijderd. Dit rituaal legde slecht lot af. De praktijk toont hoe Mesopotamische geleerden divination met politiek ritueel integreerde.',
    ],
  ],
  professor: [
    [
      'De Assyrische geleerdebrieven verzonden naar koningen zoals Esarhaddon en Ashurbanipal, in welke hofastronomen hemelse en aardse voortekenen voor koninklijke besluitvorming vertolkten, worden gezamenlijk bestudeerd door moderne Assyriologen primair uit archieven geassocieerd met welke plaats?',
      ['Nineveh', 'Kalhu (Nimrud)', 'Ashur', 'Dur-Sharrukin'],
      0,
      'Meeste Neo-Assyrische astrologiebrieven stammen uit Nineveh\'s koninklijk archief, reflecterend de stad\'s rol als regeringszetel. Brieven van geleerden legden voortekenen uit voor koninklijke ritual reacties.',
    ],
    [
      'Een cuneïforme tabletcopie van Esarhaddon\'s Vasalverdragen werd gevonden aan Tell Tayinat in context suggestief documunt lopende ritueel of cultische betekenis in plaats van puur gearchiveerd juridisch register. Wat was die vindstelling context?',
      ['Geplaatst in tempel\'s binnenste heiligdom, ogenschijnlijk gepositioneerd voor lopende rituele aandacht', 'Begegeven onder stad\'s voornaamste ceremoniële poort drempel als onderdeel arbeitsintenseive grondingsdeposiet ritual', 'Verzegeld in koninklijke sarcofaag naast lokale vasal heerscher overstetfenis', 'Doelbewust verbrijzeld en over paleisthronoommuur verspreid'],
      0,
      'Tell Tayinat tablet van Esarhaddon\'s 672 BCE verdrag werd in tempel\'s heiligdom opgegraven, suggestief voor ritual gebruik. Dit voedde discussies van parallellen met Hebreeuwse bijbelse verbond taal en ideologie.',
    ],
    [
      'De "Nineveh Rapport" corpus van Neo-Assyrische hemelse divinatieoverlegtering trok zwaar op enorm gestandaardiseerd voorteken compendium ordend rond maanen-, zonne-, planetaire en weerverschijnselen. Wat is deze compendium naam?',
      ['Enuma Anu Enlil', 'Shumma Izbu', 'Shumma Alu Ina Mele Shakin', 'Bit Meseri'],
      0,
      'Enuma Anu Enlil was het voorteken compendium dat hofgeleerden voor eclips en hemelsverschijnselen aanwendden. Neo-Assyrische brieven citeren het direct. Shumma Izbu omvatte afwijkende-geboorte voortekenen. Alle drie waren Mesopotamische divinatie specialismen.',
    ],
    [
      'De uitgebreide Oud-Assyrische koopman archief documenteerend lange-afstandshandel in tin en textiel tussen stad Ashur en Anatolië, bevattend duizenden private cuneïforme brieven en contracten, was ontdekt primair aan welke plaats, gekend in teksten zelf als karum (handelskolonie)?',
      ['Kanesh (Kültepe)', 'Alalakh', 'Emar', 'Carchemish'],
      0,
      'Kültepe/Kanesh in Anatolië leverde tienduizenden tablets van Oud-Assyrische koopmansfamilies, documenteerend tweede-millennia handelsnetwerk. Deze karum archieven zijn waardevol als private handels- en familierecords, geen koninklijke propaganda.',
    ],
    [
      'De "Gebroken Obelisk," een fragmentair Assyrisch monument nu in het Brits Museum registreerend militaire campagnes, jacht-exploits en bouwwerken, wordt algemeen op stilistische en interne gronden toegekend aan welke koning, hoewel het tekstgedeelte dat hem zou hebben genaamd verloren aan beschadiging?',
      ['Ashur-bel-kala', 'Tiglath-Pileser I', 'Ashur-dan II', 'Adad-nirari II'],
      0,
      'Gebroken Obelisk uit Nineveh verliest noeming van patroon; Ashur-bel-kala (11e eeuw BCE) wordt meest breed aanvaard. Omdat weinig Midden-Assyrische monumenten intact overleven, helpt zelfs beschadigde toewijzing.',
    ],
    [
      'De zogenaamde "Nimrud Wijnlijsten," Neo-Assyrische administratieve tablets registreerend wijnrationale distributie onder genaamde hofindividuen, worden door historici vooral gewaardeerd omdat zij wat voorzien?',
      ['Gedetailleerde moment van Neo-Assyrische hofhiërarchie, listenambtenaren, afhankelijken en huishoudstaf naar rang', 'Enig overlevend Assyrisch prijsindexspoor wijncost ten aanzien zilver over ruwweg decennium', 'Vroegste geregistreerde beschrijving viticultuurtechnieken gebruikt in Zagros voetheuvel wijngaarden', 'Bewijs van groot-schaal Assyrische wijnexport verzonden naar Fenicische handelspartners bij Tyrus en Sidon'],
      0,
      'Nimrud Wijnlijsten geven granuleus inzicht in koninklijk huishouden door ration aan ambtenaren, ambachtslui, gijzelaars en vermaakgevers.',
    ],
    [
      'Welke Midden-Assyrische koning ondernam uitgebreide herbouwen en versteviging van Ashur stad zelf, creërend paleiscomplex dat model zou dienen voor latere Assyrische koninklijke residenseontwerp?',
      ['Ashur-dan I', 'Ashur-dan II', 'Ashur-uballit I', 'Ninurta-Apal-Ekur'],
      0,
      'Ashur-dan I (r. 1179-1133 BCE) herbouwde tempels en stelde architectuurpatronen vast die latere residenties beïnvloedden. Zijn regering markeerde stabiliteit en culturele bloei. Constructieprojecten geven cruciaal voorkeur-bewijs.',
    ],
    [
      'De Rassam Cylinder, inscriptie van Ashurbanipal detailleerend militaire campagnes en religieuze vroomheid, voorziet crucial informatie over welke grensregio\'s onderwerping en tribut onder zijn regering?',
      ['Arabië', 'Egypte', 'Urartu', 'De Kaukasus'],
      0,
      'Rassam Cylinder documenteert Ashurbanipal\'s campagnes breidend Assyrische controle in Arabië en onderwerping van Arabische stammen. Het voorziet vroegste gedetailleerde tekstdocumentatie van Assyrische Arabische volkeren inhoud en exemplifieert Ashurbanipal\'s imperiaal prestige-vastlegging.',
    ],
    [
      'Ashurnasirpal II\'s beroemde paleis aan Kalhu (Nimrud) bevatte troonkamer wier reliëfsculpturen koninklijke macht via scènes van goddelijke audiëntie en bescherming afbeeldde. Welk materiaal domineerde in deze troonkamer reliëfs?',
      ['Gesneden stenen gips plagaten in registers', 'Glazurig en geschilderde keramische tegels', 'Houten panelen bekleed met goudfolie', 'Gesmeed bronzen panelen gezet in stenen muren'],
      0,
      'Troonkamer reliëfs aan Kalhu waren uit gips steen gesneden, zacht materiaal detail narratieve scènes in horizontale registers toestekend. Deze reliëfs dienden als permanente koninklijke theologie. Gips\'s wittheid contrasteerde voor geschilderd detail nu grotendeels vervaagd.',
    ],
    [
      'Welke scholastieke tekst, geproduceerd in Ashurbanipal\'s schrijverscirkels, probeerde gestandaardiseerde opsomming van Mesopotamische goden in hiërarchische orde met domeinen en relaties?',
      ['De Anu Enlil Lijst', 'De Enuma Elish', 'De Atrahasis Epos', 'De Tintir Lijst'],
      0,
      'Anu Enlil traditie probeerde systematische ordening van goddelijke figuren in kosmische orde, circulerend in Ashurbanipal\'s bibliotheek. Compilaties weerspiegelen late Assyrische scholastieke ambities voor kennisordening.',
    ],
    [
      'De Ninurta, gekend als de Assyrische strijdgod en zoon van Enlil, werd geassocieerd met welke natuurlijke en krijgs domeinen?',
      ['Jacht, oorlogsvoering en overstromingswaters', 'Landbouw en seizoenregens', 'Muziek en artistieke kunsten', 'Dood en onderwereld'],
      0,
      'Ninurta belichaamde zowel krijgskunst als dominantie over destructieve krachten, door koningen geëerd voor jacht en gevechts dapperheid. Zijn epitheta benadrukt sterkte en zege. Tempels aan hem bestonden over Assyrische gebieden.',
    ],
    [
      'De Shamash, zongod vereerd door Mesopotamië, hield wat speciale belang in Assyrische religieuze ideologie?',
      ['Rechtspreker van rechtvaardigheid en hanter van goddelijk wetten en waarheid', 'Graanplaatser zorgende jaarlijkse oogsten', 'Onderwereld veerboot meester en doodsleider', 'Stormgod beheersting weer en regenval'],
      0,
      'Shamash als rechter vertegenwoordigde rechtvaardigheid en rechtschapenheid, eigenschap Assyrische koningen claimden te belichamen. Zijn rol als kosmisch rechter sloot aan met koninklijke gerechtelijke autoriteit. Het aanroepen van Shamash rechtvaardigt koningslegitimiteit.',
    ],
    [
      'Het recente scholastieken debat over of bepaalde Midden-Assyrische-era inscripties werkelijke historische gebeurtenissen registreren of ideologische "letterkundigse" constructie vertegenwoordigen weerspiegelt wat breder uitdaging in Oud-Oosters historiografie?',
      ['Onderscheid tussen feitelijke militaire rapportage en propagandistische overdrijving in koninklijke inscripties zonder externe bevestiging', 'Bepaling of Akkadische cuneïforme historische gebeurtenissen korrect kan coderen', 'Bepaling of Mesopotamische koningen geletterd genoeg waren voor historische teksten commissie', 'Bepaling of onschriftelijke mondelinge tradities uit latere documenten kunnen worden betrouwbaar gereconstrueerd'],
      0,
      'Geleerden erkennen Assyrische inscripties feiten en propaganda vervloeiing, met overdreven tellingen. Zonder externe verificatie wordt bepaling van werkelijke historische gebeurtenissen moeilijk. Dit verschuift hoe historici inscripties als ideologie gebruiken.',
    ],
    [
      'De praktijk van inwerkening van buitenlandse-herkomst geleerden, waaronder Aramese en Babylonische schrijvers, aan Ashurbanipal\'s hof ondanks Assyrische politieke dominantie suggeert wat over Neo-Assyrische instellingen tegenover intellectueel gezag?',
      ['Intellectueel prestige was toegekend aan niet-Assyrische scholastieke tradities, koninklijk legitimiteit van buitenlandse experts aanstelling afleidend', 'Assyriërs vermeden doelbewust eigen scholastieken klasse ontwikkeling om hofrivalen te voorkomen', 'Buitenlandse geleerden werden getekend en dwtonggesteld werken tegen wil te produceren', 'Ashurbanipal persoonlijk vetted alle buitenlandse intellectuelen voor loyaliteit voor aanstelling'],
      0,
      'Ashurbanipal huurde geleerden uit Babylon, Aramea en elders, suggesterend Assyrische militaire dominantie intellectuele gezag niet noodzakelijk gaf. Niet-Assyrische geleerden droegen prestige in speciale velden. Dit intellectueel pluralisme naast politieke hiërarchie coexisteerde.',
    ],
    [
      'Hoe vergelijkt het bewijsmateriaal van Assyrische imperiaal structuurinstorting in 612 BCE historiografisch met eerdere voorspelllingen of profetieën in cuneïforme bronnen uit Assyrische archieven?',
      ['Gelijktijdige cuneïforme bronnen bevatten geen voorspellende waarschuwingen, toch latere bronnen claimden astrologers merktekenen zagen; stilte suggereert propagandaoverlay', 'Meervoudige pre-instorting voorteken-rapporten expliciet imperium vernietiging voorspelden binnen generatie', 'Babylonische bronnen onderdrukte doelbewust Assyrische voorspellingteksten om psychologische verovering voorbereiding te voorkomen', 'Cuneïforme archieven behouden gedetailleerde astrologusdebat over welke interpretaties zouden beproefd nauwkeurig'],
      0,
      'Voorteken rapporten uit Ashurbanipal\'s heerschappij bevatten geen instortingsvoorspellingen, creërend puzzel: ofgeleerden tekenen misten of traditie betekenissen retroactief imposeerde. Dit toont hoe scholastieke gemeenschappen narratieven vormen.',
    ],
  ],
};
