import type { CategoryContent } from '../row.js';

export const AUSTRIAN_HISTORY: CategoryContent = {
  bscba: [
    [
      'Welke dynastie regeerde Oostenrijk voordat de Habsburgers zich aan het einde van de 13e eeuw aan de macht grepen?',
      [
        'Babenberg',
        'Salisch',
        'Ottonisch',
        'Karolingisch',
      ],
      0,
      'De Babenbergers regeerden de Mark en Hertogdom Oostenrijk van ongeveer 976 tot 1246, toen het geslacht uitstierf. De Habsburgers werden later de dominante dynastie.',
    ],
    [
      'In welk jaar ontbond het Austro-Hongaarse Rijk zich formeel?',
      [
        '1918',
        '1920',
        '1919',
        '1922',
      ],
      0,
      'Oostenrijk-Hongarije stortte in 1918 in na de nederlaag in de Eerste Wereldoorlog. Het Verdrag van Saint-Germain in 1919 beëindigde het rijk formeel.',
    ],
    [
      'Wie was de laatst regerende keizer van Oostenrijk-Hongarije?',
      [
        'Franciscus Jozef',
        'Karels I',
        'Maximiliaan I',
        'Ferdinand I',
      ],
      0,
      'Karels I was de laatste keizer en regeerde van 1916 tot zijn abdicatie in november 1918 toen het rijk instortte.',
    ],
    [
      'In welk jaar verklaarde Oostenrijk zich republiek na de ondergang van het rijk?',
      [
        '1918',
        '1919',
        '1920',
        '1917',
      ],
      0,
      'Oostenrijk verklaarde zich in 1918 federale republiek na de ontbinding van Oostenrijk-Hongarije, de Eerste Oostenrijkse Republiek.',
    ],
    [
      'Wat was de belangrijkste politieke gebeurtenis in Oostenrijk in 1938?',
      [
        'Anschluss met nazi-Duitsland',
        'Onafhankelijkheidsverklaring van Hongarije',
        'Restauratie van de Habsburgse monarchie',
        'Verkiezing van de eerste republiceinse president',
      ],
      0,
      'De Anschluss verenigde Oostenrijk in maart 1938 met nazi-Duitsland, wat de onafhankelijkheid van Oostenrijk beëindigde tot na de Tweede Wereldoorlog.',
    ],
    [
      'Wat was de hoofdstad van het middeleeuwse Hertogdom Oostenrijk onder Babenbergse regel?',
      [
        'Wenen',
        'Salzburg',
        'Graz',
        'Linz',
      ],
      0,
      'Wenen was de hoofdstad van het Hertogdom Oostenrijk onder de Babenbergers en bleef daarna de voornaamste Habsburgse zetel.',
    ],
    [
      'Welk verdrag verdelde Oostenrijk-Hongarije formeel na de Eerste Wereldoorlog?',
      [
        'Saint-Germain',
        'Verdrag van Versailles',
        'Verdrag van Trianon',
        'Verdrag van Brest-Litovsk',
      ],
      0,
      'Het Verdrag van Saint-Germain (1919) ontbond Oostenrijk-Hongarije formeel en stelde Oostenrijk in als kleine onafhankelijke republiek.',
    ],
    [
      'In welk jaar herkwam Oostenrijk volledige soevereiniteit en verklaarde het permanente neutraliteit?',
      [
        '1955',
        '1945',
        '1950',
        '1960',
      ],
      0,
      'Oostenrijk herkwam volledige onafhankelijkheid in 1955 en verklaarde tegelijkertijd eeuwige neutraliteit, die internationaal werd erkend.',
    ],
    [
      'Welke godsdienst domineerde het Oostenrijkse Rijk gedurende het grootste deel van zijn geschiedenis?',
      [
        'Rooms-katholicisme',
        'Luthers protestantisme',
        'Oost-orthodoxie',
        'Calvinisme',
      ],
      0,
      'De Oostenrijkse Habsburgse staat was overwegend katholiek, en katholicisme bleef centraal voor Oostenrijkse identiteit en bestuur.',
    ],
    [
      'Welke regio was de originele machtsbasis van het Babenberg-dynastieën?',
      [
        'De Mark Oostenrijk',
        'De Alpenvallei van Tirol',
        'De vlaktes van Moravië',
        'De bossen van Bohemen',
      ],
      0,
      'De Babenbergers begonnen als margrazen van de Mark Oostenrijk, een grensgebied langs de Donau als verdedigingsbuffer.',
    ],
    [
      'In welk jaar trad Oostenrijk toe tot de Europese Unie?',
      [
        '1995',
        '1992',
        '2000',
        '1998',
      ],
      0,
      'Oostenrijk trad in 1995 toe tot de Europese Unie, wat decennia officiële neutraliteit in aangepaste vorm via lidmaatschap beëindigde.',
    ],
    [
      'Hoe heette de Oostenrijkse staat na de Eerste Wereldoorlog en vóór de Tweede Wereldoorlog?',
      [
        'Eerste Oostenrijkse Republiek',
        'Tweede Oostenrijkse Republiek',
        'Oostenrijkse Confederatie',
        'Oostenrijkse Federale Staat',
      ],
      0,
      'De periode van 1918 tot 1938 staat bekend als de Eerste Oostenrijkse Republiek, eindigend met nazi-annexatie.',
    ],
    [
      'Welke grote Europese stad was gedurende het Habsburgse tijdperk de hoofdstad van Oostenrijk?',
      [
        'Wenen',
        'Praag',
        'Boedapest',
        'Triëst',
      ],
      0,
      'Wenen was de hoofdstad van het aartshertogdom, toen keizerrijk, als voornaamste zetel van de Habsburgse dynastie.',
    ],
    [
      'Welke gebeurtenis in 1246 beëindigde de Babenbergse regering in Oostenrijk?',
      [
        'Dood van de laatste Babenbergse hertog',
        'Invasie door Hongaarse troepen',
        'Verovering door de heilige-Romeinse keizer',
        'Boerenelopstand',
      ],
      0,
      'De dood van hertog Frederik II (Frederik de Krijger) in 1246 beëindigde de Babenbergse lijn, wat tot erfenisveten leidde.',
    ],
    [
      'Hoe bevrijdde Oostenrijk zich van nazi-bezetting na de Tweede Wereldoorlog?',
      [
        'Bevrijd door geallieerde troepen, later neutraal',
        'Het werd onmiddellijk verdeeld onder nabuurlanden',
        'Het bleef verdeeld als Duitsland tot 1990',
        'Oostenrijk eenmaakde zich vrijwillig met West-Duitsland',
      ],
      0,
      'Geallieerde troepen bevrijdden Oostenrijk van 1944-1945. Het Oostenrijkse Staatsverdrag (1955) herstelde onafhankelijkheid met verplichte neutraliteit.',
    ],
  ],
  msc: [
    [
      'In welk jaar stelde Leopolds V, de Babenbergse markgraaf, zijn lijn in als onafhankelijke heersers gescheiden van de directe autoriteit van de heilige-Romeinse keizer?',
      [
        '976',
        '1018',
        '1055',
        '1122',
      ],
      0,
      'Leopold I (Liutpold) stichtte rond 976 het Babenberg-dynastieën als markgraaf van de Mark Oostenrijk onder nominale keizerlijke suzereiniteit.',
    ],
    [
      'Welke constitutionele regeling karakteriseerde de relatie tussen Oostenrijk en Hongarije in het door het Austro-Hongaarse Compromis ingestelde rijk?',
      [
        'Duaal koningschap met twee kronen',
        'Eenheidsstaat met Boedapest als enige hoofdstad',
        'Confederatie onder een enig parlement',
        'Persoonlijke unie zonder gedeelde soevereiniteit',
      ],
      0,
      'De Ausgleich (Compromis) van 1867 creëerde een duaal koningschap met Oostenrijk en Hongarije als gelijke staten met alleen gedeelde buitenlandse zaken.',
    ],
    [
      'Welke Habsburgse keizer convoceerde het Congres van Wenen, dat Europa na de Napoleontische Oorlogen reorganiseerde?',
      [
        'Franciscus I',
        'Jozef II',
        'Leopold II',
        'Karel VI',
      ],
      0,
      'Keizer Franciscus I organiseerde via zijn minister van buitenlandse zaken Metternich het Congres van Wenen in 1815.',
    ],
    [
      'Wat was de voornaamste reden dat de Eerste Oostenrijkse Republiek in 1919 een federaal regeringsstelsel aannam?',
      [
        'Om macht tussen Wenen en de regio\'s te balanceren',
        'Omdat het verdrag het als vredesverplichting vereiste',
        'Om voorbereiding op vereniging met Duitsland',
        'Om leaguevereisten voor lidmaatschap in te voldoen',
      ],
      0,
      'Oostenrijks federale structuur verdeelde macht tussen staten, compenserend voor drastisch verminderd grondgebied en bevolking.',
    ],
    [
      'Welke muziekale en culturele beweging was nauw verbonden met laat-19e-eeuws Wenen onder Habsburgse regel?',
      [
        'De Weense Wals-traditie',
        'Impressionisme in schilderkunst',
        'Romantisch nationalisme in literatuur',
        'Duits expressionistisch theater',
      ],
      0,
      'De wals en componisten als Johann Strauss II belichaamden Wenes globale culturele prestige en verfijnde hofcultuur.',
    ],
    [
      'In welk jaar annexeerde het nazi-regime Oostenrijk, en wat was de officiële Duitse term voor deze handeling?',
      [
        '1938; Anschluss',
        '1936; Lebensraum',
        '1940; Reichsgaue',
        '1935; Gleichschaltung',
      ],
      0,
      'De Anschluss (unie/verbinding) van 1938 absorbeerde Oostenrijk in het Duitse Rijk onder Hitler, wat onafhankelijkheid beëindigde.',
    ],
    [
      'Welke van het volgende was geen grote etnische groep die onafhankelijkheid of autonomie in Oostenrijk-Hongarije aan het begin van de 20e eeuw nastreefde?',
      [
        'Vlaamse',
        'Polen',
        'Roemenen',
        'Zuid-Slavische',
      ],
      0,
      'Vlaamse nationalisme was verbonden aan België, niet Oostenrijk-Hongarije. Polen, Roemenen en Zuid-Slavische groepen streefden autonomie in het rijk na.',
    ],
    [
      'Wat was het Metternich-Systeem, en welk tijdperk domineerde het?',
      [
        'Conservatieve orde ingesteld in 1815-1848',
        'Oostenrijkse parlementaire democratie van 1867-1914',
        'Habsburgse militaire strategie gebruikt tegen Pruisen',
        'Economische unie tussen Oostenrijk en Duitsland',
      ],
      0,
      'Klemens von Metternichs diplomatisch systeem handhaafde conservatieve orde en Oostenrijkse hegemonie in Centraal-Europa tot 1848.',
    ],
    [
      'Waarom verklaarde Oostenrijk in 1914 onwillig de oorlog aan Servië, wat de Eerste Wereldoorlog op de Balkan initieerde?',
      [
        'Moord op aartshertog Frans Ferdinand',
        'Uitbreiding van territoriale claims op de Balkan',
        'Verbondenheidsplicht aan Duitse invasie van België',
        'Maritieme blokkade opgelegd door Groot-Brittannië',
      ],
      0,
      'De moord op erfgenaam Frans Ferdinand in juni 1914 leidde tot Oostenrijks ultimatum aan Servië en veroorzaakte de Eerste Wereldoorlog.',
    ],
    [
      'In welke economische en handelsblok trad Oostenrijk in 1972 toe, wat een verschuiving naar Westeuropese integratie weerspiegelde?',
      [
        'Europese Vrijhandelsbond (EFTA)',
        'Europese Economische Gemeenschap (EEG)',
        'COMECON',
        'Benelux-Unie',
      ],
      0,
      'Oostenrijk trad in 1972 tot EFTA toe, handelsrelaties met West-Europa stellende zonder officiële neutraliteit op te geven tijdens de Koude Oorlog.',
    ],
    [
      'Welk middeleeuwse juridische voorrecht verhief Oostenrijk van markgraafschap tot hertogdom met speciale status?',
      [
        'Privilegium Minus',
        'Gouden Bul van 1222',
        'Magna Carta van 1215',
        'Vrede van Westfalen',
      ],
      0,
      'Het Privilegium Minus (1156) verleende Oostenrijk onafhankelijkheid van Beiers oppergezag en stelde het in als hertogdom onder keizerlijke bescherming.',
    ],
    [
      'Welke rol speelde het Oostenrijkse Staatsverdrag van 1955 bij beëindiging van bezetting na de Tweede Wereldoorlog?',
      [
        'Herstelde soevereiniteit in ruil voor neutraliteit',
        'Verdeelde Oostenrijk in aparte zones onder Sovjet- en westerse controle',
        'Vereiste onmiddellijk NAVO-lidmaatschap',
        'Overdroeg Tirol permanent aan Italië',
      ],
      0,
      'Het Oostenrijkse Staatsverdrag van 1955 herstelde volledige onafhankelijkheid en soevereiniteit met verplichte neutraliteit.',
    ],
    [
      'Welke grote hervorming stelde keizers Jozef II na met modernisering maar destabilisering van het keizerrijk?',
      [
        'Verlicht absolutisme',
        'Feodale decentralisering naar lokale adel',
        'Democratisering via algemeen kiesrecht',
        'Verzwakking van katholicisme\'s invloed',
      ],
      0,
      'Jozef II\'s verlichte absolutisme centraliseerde autoriteit maar vervreemde adel en etnische groepen, wat lange-termijn instabiliteit creëerde.',
    ],
    [
      'Welke Babenberg-heerser verhief Wenen tot prominentie als belangrijk handels- en strategisch centrum aan de Donau?',
      [
        'Hendrik II Jasomirgott',
        'Leopold de Glorieuze',
        'Albert de Wijze',
        'Frederik de Krijger',
      ],
      0,
      'Hendrik II Jasomirgott (1141-1177) maakte Wenen zijn hoofdstad en verleende uitgebreide handelsrechten, wat het tot belangrijk centrum transformeerde.',
    ],
    [
      'Waarom werd de Eerste Oostenrijkse Republiek in 1919 aanvankelijk belet uit eenmaking met Duitsland, een doel dat veel Oostenrijkers voorstelden?',
      [
        'Het Verdrag van Saint-Germain verbood het',
        'Oostenrijk koos vrijwillig onafhankelijk te blijven',
        'Duitsland weigerde de unificatievoorstellen',
        'De Volkenbond mandateerde ertegen',
      ],
      0,
      'Het Verdrag van Saint-Germain (1919) verbood de Anschluss ter voorkoming van Duitse dominantie, wat later door nazi-Duitsland werd geschonden.',
    ],
  ],
  phd: [
    [
      'Het Privilegium Minus van 1156 verhief Oostenrijks status vooral om welk strategisch doel voor de heilige-Romeinse keizer te bereiken?',
      [
        'Een bufferstaat tegen Beieren en Hongarije',
        'Centraliseerde Duitse macht tegen Franse agressie',
        'Stelde tegenmacht tegen pauselijke gezag in Italië in',
        'Verschafte marinebasis voor Middellandse-Zeehandel',
      ],
      0,
      'Het privilege beloonde Babenbergse militaire diensten terwijl onafhankelijke Mark Oostenrijk als strategische grenswacht werd ingesteld.',
    ],
    [
      'Hoe droeg de etnische samenstelling en nationalistische bewegingen in Oostenrijk-Hongarije bij tot uiteindelijke ontbinding?',
      [
        'Concurrerende etnische claims fragmenteerden het rijk',
        'Etnische homogeniteit paradoxaal veroorzaakte stagnatie en burgeroorlog',
        'Het rijk had geen nationalistische bewegingen voor 1914',
        'Nationalisme was geheel externe uitvinding van verdraglanden',
      ],
      0,
      'Slavische, Hongaarse, Roemeense en andere groepen streefden decennia autonomie na; WOI-verliezen versnelden centrifugale krachten tot volledige afscheiding.',
    ],
    [
      'Welk historiografisch debat omringt Jozef II\'s regering aangaande bestuurscentralisatie en etnische spanningen?',
      [
        'Of zijn hervormingen het rijk versterkten of destabiliseerden',
        'Of hij meer door Verlichting of Contrareformatie-ideologie werd beïnvloed',
        'Of hij opzettelijk de ontbinding van het keizerrijk planende',
        'Of zijn militaire campagnes strategisch zuiver waren',
      ],
      0,
      'Geschiedkundigen debatteren of Jozef\'s rationaliserend absolutisme noodzakelijke modernisering of katalysator voor nationalistische wrok was.',
    ],
    [
      'Het Austro-Hongaarse Compromis van 1867 creëerde duaal koningschap deels als reactie op welke militaire nederlaag?',
      [
        'Pruisische overwinning in de Zevenweken-Oorlog',
        'Ottomaanse verovering van Hongarije in 1526',
        'Napoleontische victorieën onder het Franse Rijk',
        'Britse maritieme dominantie in mondiale handel',
      ],
      0,
      'Oostenrijks verlies aan Pruisen in 1866 dwong hervorming; de Ausgleich verhief Hongarije tot gelijke status ter handhaving van stabiliteit.',
    ],
    [
      'Welk aspect van Wenes positie als keizerlijke hoofdstad versterkte Oostenrijkse culturele en diplomatieke invloed ondanks dalende militair-economische macht na 1870?',
      [
        'Wenes rol als kosmopolitaans intellectueel centrum',
        'Ligging op centrale handelsroutes waarborg commerciële dominantie',
        'Directe militaire controle over de Middellandse Zee',
        'Exclusieve alliantie met Groot-Brittannië en Frankrijk',
      ],
      0,
      'Wenes culturele prestige—muziek, filosofie, psychologie, literatuur—handhaafde Habsburgse zachte macht ondanks groeiende Pruisische dominantie.',
    ],
    [
      'Hoe hervormd de ontbinding van Oostenrijk-Hongarije in 1918 de politieke kaart van Centraal-Europa, en welk beginsel regelde territoriale verdelingen?',
      [
        'Zelfbepaling creëerde nieuwe natiestaten',
        'Overwinnaars herverdeelden grondgebied als verovering',
        'Oostenrijk en Hongarije bleven intact maar als bezette kolonies',
        'Geen significante grensveranderingen vonden plaats',
      ],
      0,
      'De verdragen van 1919 pasten zelfbepaling inconsistent toe, wat staten als Tsjechoslowakije en Joegoslavië met grote minderheden creëerde.',
    ],
    [
      'Waarom nam Oostenrijk een quasi-presidentieel federaal systeem in zijn grondwet van 1920 aan in plaats van puur parlementair?',
      [
        'Om uitvoerende stabiliteit te creëren',
        'Omdat verdraglanden het mandateerden',
        'Omdat Oostenrijk altijd presidentiële systemen gebruikte',
        'Ter voorbereiding op eenmaking met Duitsland',
      ],
      0,
      'Een krachtige presidentiële macht was bedoeld voor uitvoerend continuïteit; echter persisteerden verfassingsconflicten tussen Parlement en President.',
    ],
    [
      'Wat was de Ständestaat, en hoe vertegenwoordigde het Oostenrijks streven nazi- en Sovjet-invloed in de jaren 30 af te weren?',
      [
        'Austro-fascistische korporatieve staat onder Dollfuß',
        'Socialistische arbeidersbewging tegen nazi-expansie',
        'Restauratie van de Habsburgse monarchie in ballingschap',
        'Internationale pacifistische organisatie',
      ],
      0,
      'De Ständestaat van 1934-1938 onder Dollfuß streefde katholiek autoritair alternatief voor zowel nazi-totalitarisme als communisme na.',
    ],
    [
      'Hoe onderscheidden Oostenrijkse Verzetsbeweging zich van verzet in ander bezet gebieden?',
      [
        'Beperkt door ambiguïteit over Oostenrijkse identiteit',
        'Het was niet-bestaand en Oostenrijk volledig collaboreerde',
        'Oostenrijkers bevrijdden zich onmiddellijk zonder extern hulp',
        'Oostenrijk had uniform verzet over alle politieke groepen',
      ],
      0,
      'Oostenrijkers\'s complexe relatie tot de Anschluss van 1938 (sommigen verwelkomden het) fragmenteerden verzet gedurende WWII-bezetting.',
    ],
    [
      'Welke rol speelde de Oostenrijkse Communistische Partij in de nabesluit Tweede Republiek, en waarom bleef zij marginaal ondanks Sovjet-bezetting?',
      [
        'Zwak door katholieke identiteit',
        'Zij greep onmiddellijk na 1945 macht',
        'Oostenrijk had geen communistische aanwezigheid',
        'De communistische partij domineerde nabesluitpolitiek',
      ],
      0,
      'Hoewel Sovjet\'s oost-Oostenrijk bezetten, beperkte Oostenrijkse katholicisme en westverhoudingen communistische winsten; het verdrag van 1955 verder Sovjet-invloed.',
    ],
    [
      'Hoe kon Oostenrijks militaire neutraliteit na de oorlog het toestaan om in 1995 tot de EU toe te treden zonder ook bij de NAVO aan te sluiten?',
      [
        'EU-lidmaatschap is verenigbaar met militaire neutraliteit',
        'Oostenrijk sloot zich heimelijk aan bij NAVO in 1995',
        'Neutraliteit en EU-lidmaatschap zijn contradictoir; Oostenrijk schond zijn verdrag',
        'Oostenrijk is eigenlijk geen EU-lid',
      ],
      0,
      'Het Oostenrijkse Staatsverdrag van 1955 bond neutraliteit alleen aan militaire niet-betrokkenheid; EU-lidmaatschap (economisch en politiek) is niet tegengesteld.',
    ],
    [
      'Hoe relateert het ineenstorting van het Metternich-Systeem in 1848 aan nationalistische en liberale opstanden in Habsburgse gebieden?',
      [
        'Revoluties overweldigden Metternich\'s systeem',
        'Revoluties vonden niet in Oostenrijk plaats',
        'Metternich preventeerde succesvol alle hervorming',
        'Nationalisme ontstond niet voor 1900',
      ],
      0,
      'Opstandingen van 1848 over het rijk besprongen zowel autocratisme als multinationaal hegemonie; hoewel onderdrukt, bleken systeemfragilieit.',
    ],
    [
      'Welke intellectuelen en bewegingen gecentreerd in Wenen gedurende laat-19e en vroeg-20e eeuwen geldt als grondleggers van moderne gedachte?',
      [
        'Freud, Mahler, Schönberg en de Weense Kring',
        'Alleen politieke theoretici belangrijk voor Wenes invloed',
        'Wenen produceerde geen significante denkers',
        'Alle importante modernisme ontstond in Duitsland',
      ],
      0,
      'Wenen was knexus van psychologische, muzikale, filosofische en artistieke innovatie die 20e-eeuwse intellectueel leven wereldwijd hervormd.',
    ],
    [
      'Hoe vormde Oostenrijks geografische locatie tussen Duitse en Ottomaans-Balkan-sferen zijn middeleeuwse ontwikkeling onder de Babenbergers?',
      [
        'Grensligging vereiste militaire kracht en allianties',
        'Geografie was irrelevant voor Oostenrijkse ontwikkeling',
        'Oostenrijk stond altijd onder Ottomaanse regel',
        'Oostenrijk had geen strategisch belang',
      ],
      0,
      'De Donau-gang en keizerlijke banden stelden Wenen in als vitale grenspost en militaire sterkte, wat Babenberg-expansie voortdreef.',
    ],
    [
      'Welke historiografische herbeoordeling is over Oostenrijkse medeplichtigheid aan nazi-misdaden en het nabesluither-narratief van Oostenrijk als "eerste slachtoffer" ontstaan?',
      [
        'Oostenrijkse medeplichtigheid overtreft slachtofferstatus',
        'Oostenrijk was geheel medeplichtig zonder slachtoffelementen',
        'Oostenrijk was geheel onschuldig zonder collaboratie',
        'Historisch debat over dit onderwerp bestaat niet',
      ],
      0,
      'Sinds jaren 1980 hebben historici het "slachtoffer"-narratief betwist, documentering aanzienlijke nazi-steun en deelname aan Oostenrijks oorlogsmisdaden.',
    ],
  ],
  professor: [
    [
      'In de historiografie van het Babenberg-dynastieën, welk bewijs betwist het traditioneel narratief van continu territoriale expansie, en hoe herzien moderne geleerden periodisatie?',
      [
        'Niet-lineaire consolidatie met terugvallen',
        'Geen bewijs betwist expansie-narratief',
        'Babenbergers hadden minimale territoriale controle',
        'Expansie was continu en onbetwist',
      ],
      0,
      'Paleografische en cartografische heraanalyse tonen "markgraafschap" was gefragmenteerd; consolidatie was langzamer en meervecht dan traditionele historiografie beweerde.',
    ],
    [
      'Hoe herkaderen postkoloniale en transnationaal benaderingen Austro-Hongaarse interne diversiteit, voorbijgaand "gevangenis van volkeren"-metafoor?',
      [
        'Agentschap, hybriditeit en gedeelde keizerlijke structuren',
        'Postkoloniale theorie is onrelevant aan Oostenrijk-Hongarije',
        '"Gevangenis van volkeren" blijft enig juist kader',
        'Oostenrijk-Hongarije was geheel homogeen',
      ],
      0,
      'Recente geleerdsheid (Judson, Rozenblit) benadrukt gedeeld keizerlijk project, elitaire kosmopolitanisme en onderhandelde identiteiten boven lineaire onderdrukking.',
    ],
    [
      'Welke rol speelde het Austro-Hongaarse Gemeenschappelijk Leger in handhaving keizerlijke samenhang, en hoe destabiliseerden taalkundige en nationale loyaliteitsespanningen het?',
      [
        'Een integratief instituut onder druk van massapolitiek',
        'Het leger had geen interne spanningen',
        'Het leger was uit enige etnische groep samengesteld',
        'Taalkundige verschillen beïnvloedden leger-functie niet',
      ],
      0,
      'Het k.u.k. Leger symboliseerde keizerlijke eenheid maar stond stijgende muiterijen, desertie en bevelsverwarring in WOI waar soldaten\' nationale loyaliteiten keizerlijke plicht overschreden.',
    ],
    [
      'Hoe betwisten revisionist-accounts van de overgang 1918-1920 het idee van onvermijdbare ondergangkolaps, en welke toevalligheid kon uitkomsten wijzigen?',
      [
        'Mislukte federalisme en diplomatieke misstappen',
        'Ineenstorting was geheel onvermijdelijk zonder toevalligheid',
        'Historici hebben de transperiode niet bestudeerd',
        'Slechts één uitkomst was mogelijk',
      ],
      0,
      'Geleerden (Suppan, Taylor) betwisten verschillende federalism- en grondwettelijke hervormingen de waarde stabiliseerden; ineenstorting rolde deels uit politieke miscalculatie.',
    ],
    [
      'Op welke wijzen beïnvloedde territoriale vermindering van de Eerste Oostenrijkse Republiek nationale identiteitsconstruct, en hoe ontstonden concurrerende "Oostenrijksheid"-visies?',
      [
        'Een identiteitsvacuüm van concurrerende visies',
        'Oostenrijkse identiteit was voor 1918 vast ingesteld',
        'Er was geen identiteitsdebat in de republiek',
        'Alle Oostenrijkers waren het op nationale identiteit eens',
      ],
      0,
      'De republiek worstelde tussen Duitse nationale identiteit (unie met Weimar), katholiek korporatisme en onderscheidend Oostenrijks patriotisme; fragmentatie mogelijk nazi-appel.',
    ],
    [
      'Hoe verschillen recente transnationaal-geschiedenissen van antisemitisme in Oostenrijk van eerder-accounts die externe nazificatie beschuldigden?',
      [
        'Inheems antisemitisme van vóór Hitler',
        'Oostenrijk had geen antisemitisch traditie voor Nazisme',
        'Antisemitisme begon enkel met Hitler\'s aankomst',
        'Oostenrijk was geheel vrij van religieus vooroordeel',
      ],
      0,
      'Historici (Rozenblit, Pollack) traceren 19e-eeuwse Austro-Hongaarse antisemitisme door Lueger\'s Wenen; Nazisme capitaliseerde op reeds-bestaande vijandigheid.',
    ],
    [
      'Welk historiografisch debat omringt Oostenrijks Anschluss 1938: moet het gelezen als annexatie, nationale eenwording of iets complexer?',
      [
        'Dwang, manipulatie en verdeelde opinie',
        'Anschluss was unaniem populaire steun',
        'Het was puur buitenlandse verovering zonder Oostenrijkse deelname',
        'Geen geleerde debat over dit onderwerp bestaat',
      ],
      0,
      'Post-jaren 1980 revisionism (Hanisch, Botz) compliceren vroegere "slachtoffer"-narratieven, documentering aanzienlijke Nazi-steun ondanks dwingende maatregelen.',
    ],
    [
      'Hoe navigeerde Oostenrijkse katholieke intellectuele tradities de ideologische crisis van jaren 1920-1930, in het bijzonder kerkantwoord aan communisme en fascisme?',
      [
        'Een katholieke derde weg naar autoritarisme',
        'De Katholieke Kerk bleef politiek neutraal gedurende',
        'Katholicisme had geen invloed op Oostenrijkse politiek',
        'De Kerk steunde exclusief democratie',
      ],
      0,
      'Austro-katholiek denken ontwikkelde korporatieve alternatieven voor liberale democratie en socialisme; Kerkesteun voor Dollfuß\'s Ständestaat weerspiegelde deze baan.',
    ],
    [
      'Welke rol speelden Wenes intellectuele gemeenschappen (Weense Kring, Tweede Weense School, Freudiaanse kringen) in productie van ballingschapintellectuelen die herbouw van geallieerde nabesluit vormden?',
      [
        'Gedwongen emigratie vormde het bezettingsbeleid',
        'Wenen had geen intellectuele invloed op nabesluitplanning',
        'Emigratie had geen effecten op geallieerd beleid',
        'Weense intellectuelen bleven gedurende in Oostenrijk',
      ],
      0,
      'Ballingschap-Oostenrijkers in geallieerde dienst (Morgenstern, Helmer) vormden bezettingsbeleidsheid; culturele emigratie-netwerken beïnvloedden hoe geallieerden Oostenrijks nabesluit-rol begrepen.',
    ],
    [
      'Op welke wijze vertegenwoordigt het Oostenrijkse Staatsverdrag (1955) bijzondere Koude-Oorlog-regeling, en hoe verschillen Sovjet-concessies van Duitse en Koreaanse verdelingen?',
      [
        'Consensuele terugtrekking, geen verdeling',
        'Oostenrijk was verdeeld als Duitsland',
        'De Sovjet\'s bereikten territoriale concessies',
        'Het verdrag loste niets op',
      ],
      0,
      'Het verdrag van 1955 staat anomalisch: Sovjet\'s aanvaardden Oostenrijkse onafhankelijkheid met verplichte neutraliteit boven vervolgde verdeiling of satellietstatus als in Duitsland.',
    ],
    [
      'Hoe verklaren historici Oostenrijks betrekkelijk vredige nabesluittransitie en snelle integratie in democratische westerse structuren, vergeleken met andere opvolgerstaten?',
      [
        'Katholieke consensus en Marshall-steun',
        'Oostenrijk stond grotere uitdagingen dan andere staten',
        'De transitie was geheel vredig zonder moeilijkheden',
        'Oostenrijk integgreerde niet in westers-structuren',
      ],
      0,
      'Oostenrijks katholiek-socialistisch groot-coalitie (1945-1966) en westers Koude-Oorlog-steun overwonnen denazificatiespanningen; nabesluitconsensus maakten snellere stabilisatie mogelijk.',
    ],
    [
      'Welke interpretatieve kaders hebben geleerden toegepast ter begrijping van Habsburgse monarchie\'s lange overleving (ruwweg 1282-1918) relatief aan andere Europese imperia?',
      [
        'Dynastieke veerkracht en huwelijksallianties',
        'Habsburgers hadden geen speciale voordelen',
        'Enkel militaire kracht handhaafde de monarchie',
        'Het Habsburgse rijk stond altijd op rand van ineenstorting',
      ],
      0,
      'Historici benadrukken adaptieve bestuur, internationaal-elite gedeelde investering in keizerrijk en Habsburgers\' strategische huwelijksstrategie als structurele handhavers.',
    ],
    [
      'Hoe geldt het concept "supernationalisme" op laat Oostenrijk-Hongarije, en welke grondwettelijke hervorming 1914-1918 de waarde behouden beoogden?',
      [
        'Popovici\'s federalisme-plan voor "Groter-Oostenrijk"',
        'Supernationalisme had geen relevantie aan Oostenrijk-Hongarije',
        'Geen grondwettelijke hervormingsprojecten bestonden',
        'Oorlog begon met grondwettelijk consensus',
      ],
      0,
      'Interoorlog- en oorlogstijd-intellectuelen beelden federale supranationale structuren; deze bleven onverwezenlijkt wanneer nationalistische partijen compromis afwezen en militaire nederlaag opties sloten.',
    ],
    [
      'Wat de "Oostenrijkse vraag" in Koude-Oorlog-diplomatieke geschiedenis verwijst, en waarom Oostenrijks hereniging en neutralisering als model of precedent behandeld?',
      [
        'Een sjabloon voor Duitse hereniging, nooit toegepast',
        'Er was geen Oostenrijkse vraag in Koude-Oorlog-diplomatie',
        'Oostenrijks status had geen diplomatieke betekenis',
        'Oostenrijks situatie rechtstreeks Duitse vraag oplosste',
      ],
      0,
      'De Oostenrijkse regeling van 1955 suggereerde verdeiling kon via onderhandeling en neutraliteit omgekeerd; Koude-Oorlog-stijfheid preventeerde dit model op Duitsland of Korea toepassen.',
    ],
    [
      'Hoe hebben milieu- en ruimtehistorici Wenes rol in het Habsburgse Rijk herraming, in het bijzonder betrekking grondstofstromen, infrastructuur en staduitbreiding als keizerlijke hoofdstad?',
      [
        'Wenes groei steunde op keizerlijke hulpbronnen',
        'Wenes ontwikkeling was puur intern',
        'De stad had minimale keizerlijke belang',
        'Infrastructuur had geen rol in keizerlijke macht',
      ],
      0,
      'Recente milieuw-geschiedsheid (Orban) traceren Wenes voedsel/energieafhankelijkheid van Donau-graan en provinciale hulpmiddelen, stedelijke expansie aan keizerlijke dominantie linkerend.',
    ],
  ],
};
