import type { CategoryContent } from '../row.js';

export const FRENCH_HISTORY: CategoryContent = {
  bscba: [
    [
      'Welke Frankische dynastie, bekend om hun "langharige koningen", regeerde vóór de Karolingen?',
      [
        'De Merovingische dynastie',
        'De Visigotische dynastie',
        'De Ostrogotische dynastie',
        'De Vandaalse dynastie',
      ],
      0,
      'De Merovingen (481–751) waren de eerste Frankische dynastie, genoemd naar legendarische voorouder Merovech. Hun macht verzwakte naarmate de Paleismeesters sterker werden.',
    ],
    [
      'Wat was de betekenis van Karels de Grotes kroning op Eerste Kerstdag 800?',
      [
        'Hij werd gekroond tot Heilige Roomse Keizer',
        'Hij werd de eerste christelijke koning van Frankrijk',
        'Hij riep zichzelf uit tot Paus van de Westerse Kerk',
        'Hij veroverde Rome en stichtte een nieuwe religieuze hoofdstad',
      ],
      0,
      'Karels kroning door Paus Leo III stichtte het Heilige Roomse Rijk en symboliseerde de fusie van Frankische macht met pauselijke autoriteit in het Westen.',
    ],
    [
      'Welke dynastie, gesticht door Hugo Capet, maakte Parijs tot haar machtsbasis en domineerde Frankrijk geleidelijk?',
      [
        'De Kapetingische dynastie',
        'De Karolingische dynastie',
        'De Anjou-dynastie',
        'De Bourgondische dynastie',
      ],
      0,
      'De Kapetingen (987–1328) bouwden hun koninkrijk uit de Île-de-France en gebruikten feodale relaties en huwelijken om hun domein eeuwenlang uit te breiden.',
    ],
    [
      'Wat was de voornaamste oorzaak van de Honderdjarige Oorlog tussen Engeland en Frankrijk?',
      [
        'Engelse aanspraken op de Franse troon',
        'Franse invasie van Engelse grondgebieden in Brittannië',
        'Religieuze verschillen tussen Engelse katholieken en Franse protestanten',
        'Handelsdisputen over controle van Middellandse Zeehavens',
      ],
      0,
      'De Honderdjarige Oorlog (1337–1453) ontstond uit Engelse dynastieke aanspraken op Frankrijk, voortvloeiend uit de Normandische Verovering en Angevinse bezittingen.',
    ],
    [
      'Wie was Jeanne d\'Arc en wat was haar rol in de Honderdjarige Oorlog?',
      [
        'Een Franse boerenmeisje dat Franse troepen aanvoerde',
        'Een Engelse generaal die Franse legers bij Crécy versloeg',
        'Een Franse adelvrouw die vredesverdragen met Engeland onderhandelde',
        'Een Franse geleerde die militaire strategie aan de dauphin doceerde',
      ],
      0,
      'Jeanne d\'Arc (1412–1431) claimde goddelijke inspiratie, motiveerde Franse troepen, en zorgde voor de kroning van de dauphin. Zij werd later door de Engelsen terechtgesteld.',
    ],
    [
      'Welk stelsel van bestuur kenmerkte de regering van Lodewijk XIV?',
      [
        'Absolute monarchie, gecentraliseerd bij de koning',
        'Grondwettelijke monarchie met een machtig parlement',
        'Democratische republiek met gekozen functionarissen',
        'Feodale stelsel met machtige onafhankelijke edelen',
      ],
      0,
      'Lodewijk XIV (r. 1643–1715) belichaamde absolute monarchie. Hij centraliseerde macht, verplaatste het hof naar Versailles en verzwakte de onafhankelijkheid van adel.',
    ],
    [
      'Wat was het Edict van Nantes (1598) en wie beschermde het?',
      [
        'Hendrik IV\'s decreet van religieuze tolerantie voor hugenoten',
        'Lodewijk XIV\'s wet die alle protestantse kerken in Frankrijk verbood',
        'Een pauselijke bul die de autoriteit van de Paus in Frankrijk stelde',
        'Een feodale overeenkomst tussen de koning en Franse adel',
      ],
      0,
      'Het Edict van Nantes verleende hugenoten (Franse protestanten) religievrijheid en politieke rechten. Lodewijk XIV heffen het in 1685 op, wat vervolgingen intensiveerde.',
    ],
    [
      'Welke gebeurtenis in 1789 wordt beschouwd als symbolisch begin van de Franse Revolutie?',
      [
        'De bestorming van de Bastille door Parijzenaars',
        'De executie van Koning Lodewijk XVI',
        'De Verklaring van de Rechten van de Mens',
        'De oproeping van de Staten-Generaal',
      ],
      0,
      'Op 14 juli 1789 stormden Parijzenaars de Bastille, symbool van koninklijke tirannie. De gebeurtenis markeert het begin van de Revolutie en is Frans nationale feestdag.',
    ],
    [
      'Welke periode zag snelle executies tijdens de Franse Revolutie, inclusief Koning Lodewijk XVI?',
      [
        'De Schrikbewind onder Robespierre',
        'De Directoire-periode van gematigde republikanisme',
        'Het Consulaat onder Napoleons leiderschap',
        'De Restauratie onder Lodewijk XVIII',
      ],
      0,
      'De Schrikbewind (1793–1794) onder Maximiliaan Robespierre zag massale gillotine-executies, inclusief Lodewijk XVI, Marie Antoinette en duizenden tegenstanders van de Revolutie.',
    ],
    [
      'Hoe steeg Napoleon Bonaparte naar de macht in Frankrijk?',
      [
        'Via de Coup van 18 Brumaire in 1799',
        'Door democratisch verkezen te worden tot president',
        'Door de troon te erven van Koning Lodewijk XVI',
        'Door een populaire boerenopstand tegen adel aan te voeren',
      ],
      0,
      'De Coup van 18 Brumaire (9 november 1799) bracht Napoleon aan de macht als Consul. Hij gebruikte de onpopulariteit en zwakheid van de Directoire uit midden in oorlog en economische crisis.',
    ],
    [
      'Wat was het voornaamste doel van het Napoleonisch Wetboek dat in 1804 werd ingevoerd?',
      [
        'Het invoeren van uniform Frans burgerlijk recht',
        'Het bevestigen van absolute macht van de Katholieke Kerk in alle juridische aangelegenheden',
        'Het herstellen van feodale privileges voor Franse adel',
        'Het stellen van een onafhankelijk wetgevend lichaam los van het bestuur',
      ],
      0,
      'Het Napoleonisch Wetboek standaardiseerde Frans recht en verving een lappendeken van feodale gewoontes. Het beïnvloedde rechtsstelsels in heel Europa en benadrukte wereldse burgerrechten.',
    ],
    [
      'Hoe reageerde het Congres van Wenen (1814–1815) op Napoleons nederlaag?',
      [
        'Het herstelde de Bourbonische monarchie onder Lodewijk XVIII',
        'Het elimineerde Frankrijk volledig en verdeelde zijn grondgebied onder buurlanden',
        'Het stichte een democratische republiek in heel Europa',
        'Het benoemde Napoleons zoon tot regent van een verzwakt Frankrijk',
      ],
      0,
      'Het Congres van Wenen herstelde de Bourbonische monarchie en machtsevenwicht in Europa. Frankrijk werd tot zijn grenzen van 1789 teruggebracht maar bleef een grootmacht.',
    ],
    [
      'Wat was de uitkomst van de Revolutie van 1848 in Frankrijk?',
      [
        'Het stichte de Tweede Republiek en breidde stemrecht uit',
        'Het beëindigde permanent de Franse monarchie en stelde democratisch bestuur in',
        'Het leidde tot onmiddellijke eenmaking van alle Europese staten',
        'Het herstelde de Bourbondynastie tot absolute macht',
      ],
      0,
      'De Revolutie van 1848 creëerde de Tweede Republiek en breidde stemrecht uit. Zij schaffte slavernij af. De republiek was echter kortstondig; Napoleon III nam de macht in 1852.',
    ],
    [
      'Welke Franse staatsman en militaire held leidde de Vrije Franse verzet tijdens Wereldoorlog II?',
      [
        'Charles de Gaulle',
        'Pierre Laval',
        'Philippe Pétain',
        'Jean Monnet',
      ],
      0,
      'Charles de Gaulle (1890–1970) organiseerde de Vrije Franse troepen, verzette zich tegen het Vichy-regime en leidde Frankrijk na de bevrijding. Hij stichte later de Vijfde Republiek.',
    ],
    [
      'Welk stelsel van bestuur werd ingesteld door de Vijfde Republiek-grondwet in 1958?',
      [
        'Een semi-presidentieel stelsel met gekozen president',
        'Een absolute monarchie met enkel ceremoniële bevoegdheden',
        'Een zuivere parlementaire democratie zonder apart bestuur',
        'Een militaire dictatuur onder rechtstreeks bevel van de Gaulle',
      ],
      0,
      'De Vijfde Republiek (1958–heden) schiep een semi-presidentieel stelsel dat presidentiële en parlementaire macht in balans houdt. Het is nog steeds Frans grondwettelijk kader.',
    ],
  ],
  msc: [
    [
      'Welke Merovingische praktijk van het verdeelde koninkrijk gelijk onder zonen schepsloze instabiliteit en regionale fragmentatie?',
      [
        'Deelbare erfenis, die het koninkrijk onder erfgenamen verdeelde',
        'Eerstgeboorterecht, dat alle rijkdom op de eerstgeborene concentreerde',
        'Matrilineale opvolging, macht in vrouwelijke regenten plaatsend',
        'Electieve monarchie, voortdurend wedstrijden onder adelen nodig',
      ],
      0,
      'Deelbare erfenis betekende vorstendommen verdeeld onder erfgenamen, Australië, Neustrië en Aquitanië creerend. Deze fragmentatie stelde Paleismeesters in staat macht te concentreren door opvolgingsruzies te manipuleren.',
    ],
    [
      'Welke militaire innovatie gebruikte Pepin III om Lombardijen te verslaan en pauselijke alliantie veilig te stellen?',
      [
        'Zware cavalerie met stijgbeugels domineerde het slagveld',
        'Marineeskaders die Middellandse Zeeroutes naar Byzantijnse territoria controleerden',
        'Grieks vuur-technologie, aangenomen uit Byzantijnse bronnen, voor belegeringsoorlogvoering',
        'Olifanten geïmporteerd uit Noord-Afrika voor psychologisch effect tegen vijanden',
      ],
      0,
      'Pepin III (Pepin de Korte) zette zware cavalerie met stijgbeugels in, Frankische oorlogvoering revolutionering. Zijn victorieën op Lombardijen wonnen pauselijke dankbaarheid en legitimeerden zijn dynastie.',
    ],
    [
      'Welk onderwijs- en cultuurprogramma implementeerde Karel de Grote om zijn rijk te versterken?',
      [
        'De Karolingische Renaissance, klassiek leren herlevend',
        'Een stelsel van wereldse universiteiten die Griekse filosofie en retorica doceerden',
        'Verplichte militaire academies voor training van adellijke officieren',
        'Handwerkscholen die kooplieden geavanceerde boekhouding en navigatie onderwezen',
      ],
      0,
      'Karels Karolingische Renaissance herstelde klassieke teksten, standaardiseerde Latijnse schrift (Karolingisch minusculum), en bevorderde geestelijkheid alfabetisering. Deze culturele heropleving beïnvloedde middeleeuws Europa.',
    ],
    [
      'Hoe beïnvloedde het Verdrag van Verdun (843) de structuur en erfenis van het Karolingische Rijk?',
      [
        'Het verdeelde het rijk in drie koninkrijken',
        'Het verenigde alle Frankische territoria onder rechtstreeks bewind van één erfgenaam',
        'Het overdroeg keizerlijke autoriteit volledig aan Byzantijnse Keizer',
        'Het schaffte feodalisme af en stelde rechtstreeks koninklijk bestuur over alle regio\'s in',
      ],
      0,
      'Verdun verdeelde Karels rijk onder zijn kleinzonen. De deling creëerde proto-Frankrijk, proto-Duitsland en een omstreden middelveld, stellend Europese politieke basisstructuur.',
    ],
    [
      'Welke feodale strategie gebruikte Filips Augustus (r. 1180–1223) om Kapetingisch domein ten koste van Anjou uit te breiden?',
      [
        'Hij gebruikte Jans zwakte om Normandische en Angevinse landen in beslag te nemen',
        'Hij kocht Engelse territoria van opeenvolgende bankrotte Engelse koningen',
        'Hij huwde de dochter van de Engelse koning om Engelse troon voor zijn erfgenamen op te eisen',
        'Hij onderhandelde handelsovereenkomsten die Engelse kooplieden van Franse havens isoleerden',
      ],
      0,
      'Filips Augustus gebruikte Jans ongepopulariteit en verlies van Normandië. Voor 1202 had Filips meeste Angevinse Franse bezittingen veroverd, Kapetingisch grondgebied verdrievoudigend.',
    ],
    [
      'Welk religieus conflict besprak de Albigense Kruistocht (1209–1229) in Zuid-Frankrijk?',
      [
        'Een kruistocht tegen Cathare ketters in Occitanië',
        'Een conflict tussen Franse katholieken en Moslimindringers uit Noord-Afrika',
        'Een burgeroorlog tussen rivaliserende Kapetingische erfgenamen om de troon',
        'Een opstand van zuidelijke adelen tegen Noord-Franse belastingen',
      ],
      0,
      'De Albigense Kruistocht vernietigde Cathare ketterij in Languedoc en bracht welgestelde zuidelijke territoria onder rechtstreeks Kapetingisch bestuur. De Inquisitie consolideerde katholieke ortodoxie.',
    ],
    [
      'Welke rol speelde Jeanne d\'Arc\'s proces en executie in Engelse politieke legitimiteit?',
      [
        'Haar veroordeling door een pro-Engels hof werd een verzet-symbool',
        'Haar executie demoraleerde permanent de Fransen en garandeerde Engels overwinning in de Honderdjarige Oorlog',
        'Haar proces stelde Engelse juridische autoriteit over Franse kerkelijke aangelegenheden in',
        'Haar executie verenigde Engelse en Franse kerken onder pauselijke controle',
      ],
      0,
      'Jeanne werd in 1431 wegens ketterij door een pro-Engelse hof berecht en verbrand. Haar martelaarschap, later door Frankrijk gebruikt, symboliseerde Engelse onderdrukking en droeg bij tot Engels verlies.',
    ],
    [
      'Hoe weerspiegelden de Godsdienstoorlogen (1562–1598) conflicten voorbij zuivere sectaire doctrine?',
      [
        'Ze betroffen factiestrijd tussen Guise- en Bourbonfamilies',
        'Ze waren zuiver theologische debatten over schriftinterpretatie zonder politieke dimensie',
        'Ze waren burgeroorlogen tussen boeren en adel over landherverdelding',
        'Ze waren buitenlandse invasies door Spaanse en Italiaanse katholieke legers naar territoriaal verovering',
      ],
      0,
      'De Godsdienstoorlogen betrokken dynastieke rivaliteit, adellijke factionisme en internationaal ingrijpen, met protestantisme en katholicisme als banieren voor politieke rivaliteit eerder dan alleen oorzaken.',
    ],
    [
      'Welk economisch beleid implementeerde Jean-Baptiste Colbert om Frankrijk onder Lodewijk XIV te versterken?',
      [
        'Mercantilisme: vervaardiging bevorderen en bullion accumuleren',
        'Vrij handelen met alle Europese naties en koloniale territoria',
        'Feodale-stijl landbouwgemeenten zonder centraal fiscaal controle',
        'Rechtstreeks staatseigendom van alle koopvaardijschepen en handelsmaatschappijen',
      ],
      0,
      'Colberts mercantilisme stimuleerde Franse vervaardiging, bouwde marine, charterde handelsmaatschappijen en genereerde koninklijk inkomen via tarieven en koloniale handelsmonopolies.',
    ],
    [
      'Welke rol speelde het Parlement van Parijs (juridisch lichaam, geen legislatuur) bij oppositie tegen 18e-eeuwse fiscale hervorming?',
      [
        'Het blokkeerde belastinghervormingen door edic niet te registreren',
        'Het ondersteunde kroon door alle voorgestelde fiscale maatregelen in te voeren',
        'Het trachtte democratische stemrechten voor alle Franse onderwerpen in te stellen',
        'Het bondelde zich met buitenlandse mogendheden om Franse staatconsolidatie te voorkomen',
      ],
      0,
      'Het Parlement van Parijs blokkeerde fiscale edic via registratieweigering. Deze juridische obstructie door gepriviligeerde parlementairen vertraagde noodzakelijke hervormingen en verdiepte fiscale crisis.',
    ],
    [
      'Hoe beïnvloedden verlichtingsfilosofieën, bepaaldelijk van Diderot en Rousseau, Frans Revolutionair ideologie?',
      [
        'Ze bevorderden rationele kritiek op monarchie en volkssoevereiniteit',
        'Ze verdedigden feodalisme en adellijk privilege als natuurlijk en goddelijk bevolen',
        'Ze pleitten voor sterkere centrale monarchie en uitgebreide koninklijke autoriteit',
        'Ze wezen alle sociale organisatievormen af als inherent corrupt',
      ],
      0,
      'Verlichtingsdenkers attackeerden willekeurige autoriteit, bevorderden rede en individuele rechten, theoriseerden populaire soevereiniteit. Deze ideeën inspireerden rechtstreeks Revolutionaire vrijheid- en gelijkheidsvorderingen.',
    ],
    [
      'Welke transformatie trachtte de Civiele Constitutie van de Geestelijkheid (1790), en welke tegenstand lokte het uit?',
      [
        'Het onderwierp de Kerk aan staatsautoriteit, wat een pauselijk schisma uitlokte',
        'Het verleende Kerk onbeperkte controle over staatsbelastingen en juridische autoriteit',
        'Het schaffte alle religieuze instellingen af en converteerde kerken naar openbare pakhuizen',
        'Het herstelde feodale kerkgoederen en versterkte pauselijke autoriteit over Frankrijk',
      ],
      0,
      'De Civiele Constitutie maakte geestelijken staatsambtenaren en onderwerpen de Kerk aan de staat. Paus Pius VI veroordeelde het, splitstend Franse katholieken en voedend tegen-revolutionaire bewegingen.',
    ],
    [
      'Hoe markeerde de Thermidoriaanse Reactie (juli 1794) een keerpunt in de Revolutie?',
      [
        'Het executeerde Robespierre en beëindigde het Schrikbewind',
        'Het verstevigde radicaal Jacobijn controle en versnelde executies',
        'Het herstelde Bourbonische monarchie tot absolute macht onmiddellijk',
        'Het stelde democratisch socialisme als Frans bestuurideologie in',
      ],
      0,
      'De val van Robespierre op 9 Thermidor beëindigde de Schrikbewind. De Thermidorianen stelden meer gematigde, eigendom-gebaseerde republiek in, stellend Napoleons weg voor.',
    ],
    [
      'Welke militaire crisis steide de Directoire uit voor Napoleons coup in 1799?',
      [
        'Militaire verliezen en royalistische opstanden destabiliseerden de Republiek',
        'Napoleon stapte vrijwillig naar voren om buitenlandse monarchie van Frankrijk af te houden',
        'De Directoire zocht democratie verruiming via militaire revolutionair raad',
        'Brittannië versloeg Frans vloot beslissend, stellers Napoleon defensieve noodzaak maken',
      ],
      0,
      'De Directoire faced militaire nederlagen, financiële instorting, royalistische opleving en buitenlandse invasiedreiging. Deze crises erodeerden burgerordeslegitimiteit en stellers Napoleons machtsovernaam mogelijk.',
    ],
    [
      'Hoe demonstreerden de Honderd Dagen (maart–juni 1815) Napoleons blijvend appel en zijn grenzen?',
      [
        'Hij motiveerde loyale legers maar verloor beslissend bij Waterloo',
        'Hij veroverde Europa met succes en stelde permanente dynastie in',
        'Hij abdikeerde vrijwillig om Bourbons zonder militair gevecht te herstellen',
        'Hij werd onmiddellijk gearresteerd en geëxecuteerd na ontsnappping',
      ],
      0,
      'Soldaten verzamelden rond Napoleons banier in 1815, stellend zijn populariteit. Europese legers versloegen hem echter bij Waterloo, stellend zijn persoonlijke magnetisme coalitiepower niet kon overwinnen.',
    ],
  ],
  phd: [
    [
      'Wat onderscheidde Australische hegemonie van Neutriaanse politieke structuren in vroege Merovingische periode, en wat dreef hun rivaliteit?',
      [
        'Australische militaire aristocratie botste met Neustrische hofelite om de koning',
        'Australië was Romeinse provincie terwijl Neutrië volledig Germanisch zonder institutionele structuren was',
        'Neutrië hield altijd meer rijkdom, terwijl Australië zuiver op militaire verovering leunde',
        'Ze praktiseerden fundamentaal verschillende religies, met Australië heiden en Neutrië katholiek',
      ],
      0,
      'Australische en Neutriaanse adelen mededingerden om zwakke Merovingische koningencontrole. Deze factionalisme fragmenteerde koninkrijk en stellers Paleismeesters—oorspronkelijk Australische ambtenaren—macht consolideren.',
    ],
    [
      'Hoe stelden Pepin III\'s introductie van zware cavalerie tactiek en het feodale contractstelsel Karolingische militaire suprematie in?',
      [
        'Bereden ridders met stijgbeugels en feodale verplichting schiepen een superieur leger',
        'Pepin vond katapult en buskruit uit, stellend technologische dominantie',
        'Hij trainde uitsluitend boerenlegers gebruikmakend van conscriptie en massale mobilisatie',
        'Hij leunde volledig op Byzantijnse soldaten-van-fortuin voor alle militaire campagnes',
      ],
      0,
      'Pepins zware cavalerie leunde op stijgbeugels, schokttactieken stellend. Het feodale stelsel bond adelen als vasallen verplicht tot militaire dienst, decentralijzeerd maar gecoördineerd krijgersclas stellend.',
    ],
    [
      'Welke pedagogische hervormingen in de Karolingische Renaissance, bepaaldelijk Karels Admonitio Generalis, transformeerden alfabetisering en intellectuele cultuur?',
      [
        'Standaardschrift, kloosteralfabetisering en geestelijke onderwijshervorming',
        'Hij schaffte Latijn af en bevorderde alleen Germanische talen voor bestuur',
        'Hij sloot alle kloosters en stelde uitsluitend seculiere universiteiten voor adel in',
        'Hij imposeerde enkel Latijns dialect wat regionale taalvariatie elimineerde',
      ],
      0,
      'Karels edic standaardiseerde schrift, verplichte kloosters onderwijzen, en klassieke teksten gecorrigeerd. Karolingisch minusculum stelde gemakkelijker kopiëren en lezen—informatietechnologische revolutie—in.',
    ],
    [
      'Hoe bereikten Kapetingische feodale strategieën, bepaaldelijk huwelijkallianties en systematische vassal-litigatie, dominantie zonder aanvankelijk superieure militaire kracht?',
      [
        'Via huwelijken in grote feoddommen en kerkelijke hoven tegen rivalen',
        'Via militaire campagnes alle territoria in eerste generatie verovering',
        'Via koopman-rijkdom geaccumuleerd alle gronden aankoop',
        'Via verplichte religieuze conversie loyaliteit consolidering',
      ],
      0,
      'Kapetingen breidden via strategische huwelijken (Aquitanië, Bretagne winnen), vassalage-rechtgreep gebruikmakend magnaten uitdagen, kerkelijke allianties. Militaire verovering kwam later, na politieke consolidatie.',
    ],
    [
      'Welke structurele zwakheid in Angevinse erfenisstelsel gebruikte Filips Augustus om Engelse bezittingen in Frankrijk te fragmenteren?',
      [
        'Jans baronnenopstand liet Filips zijn landen in beslag nemen',
        'De Angevinse erfenis was te welvarend om effectief te verdedigen',
        'Engelse barone overdroegen vrijwillig hun Franse gronden aan Kapetingische kroon',
        'Een verdrag droeg Angevinse eigendom automatisch aan Kapetingische lijn over',
      ],
      0,
      'Jans onpopulariteit, conflict met Engelse barone, militaire onbekwaamheid schiepen mogelijkheden. Filips gebruikte deze divisies uit, Normandië, Anjou, Maine onder feodale recht inbeslagtellend.',
    ],
    [
      'Hoe beïnvloedde de integratie van Bedelmonniken-orden in hofcultuur en intellectuele netwerken laatmiddeleeuws Kapetingisch bestuur?',
      [
        'Dominicanen en Franciscanen werden koninklijke adviseurs en pauselijke belangenbehartigers',
        'Ze scheidden volledig geestelijke en wereldlijke autoriteit, weigering politiek engagement',
        'Ze elimineerden Benedictijnse monastickisme en consolideerden alle religieuze autoriteit in Rome',
        'Ze stelden onafhankelijke communes in die koninklijke jurisdictie beperkte',
      ],
      0,
      'Bedelmonniken werden biechtvaders, theologen, politieke adviseurs aan koningen. Ze linkten pauselijke autoriteit aan koninklijke legitimiteit terwijl onderwijzing en doctrinel orthodoxie bevorderden.',
    ],
    [
      'Welke rol speelde Salische wet-doctrine in Valois-opvolging legitimering en Engelse aanspraakafsluiting na 1328?',
      [
        'Franse juristen riepen Salische wet aan om de Engelse aanspraak uit te sluiten',
        'Salische wet werd 14e-eeuw uitgevonden om Engelse aanspraken tegen Frankrijk te ondersteunen',
        'Het was Romeinse wetprincipe zonder verbinding middeleeuwse opvolging',
        'Het stelde mannelijke electieve monarchie eerder dan erfelijke opvolging in',
      ],
      0,
      'Na 1328 gebruikten Franse juristen Salische wet om Edwards III aanspraken (via moeder afstamming) uit te sluiten. Deze doctrine werd Franstalig nationale-identiteitsgrondslag en Valois-heerschappij legitimeerde.',
    ],
    [
      'Hoe hervormdde factiestrijd tijdens de Fronde (1648–1653)—tussen kroon, Parlement, adel—koninklijke absolutisme?',
      [
        'De Fronde liet Lodewijk XIV macht centraliseren en adel ontwapenen',
        'De Fronde stelde succesvol parlementaire democratie en permanente koninklijke-autoriteitsbeperkering in',
        'De Fronde was boerenopstand zonder elite-machtsstructuur impact',
        'Het resulteerde in onmiddellijk feodale onafhankelijkheidsherstel aan regionale adelen',
      ],
      0,
      'Fronde toonde kroon adel en Parlement existentiële dreigingen vormden. Lodewijk XIV\'s reactie was berekende centralisatie: hij verplaatste hofje naar Versailles magnates supervisering en onwapening voor.',
    ],
    [
      'Welke fiscale crisis-mechanismes—belastingfarming, ambtsvenaligheid, inflatie—schiepen structurele deficits wat laat-18e-eeuwse monarchie destabiliseerden?',
      [
        'Belastingfarming en venale ambten schiepen chronische deficits',
        'De monarchie besteedde geld opzettelijk adel te verzwakken',
        'Frankrijk had geen werkelijke fiscale crisis; Revolutie was zuiver ideologisch',
        'Buitenlandse leningen elimineerden alle Franse staatsfinanciële druk',
      ],
      0,
      'Belastingfarming verrijkte financiers, niet kroon. Venaalsambten consumeerden kapitaal. Inflatie reduceerde reëel inkomen terwijl onkosten stegen. Deze structurele deficits maakten monarchie steeds insolvent voor 1789.',
    ],
    [
      'Hoe belichaamden parlementaire tegenstand tegen koninklijke edic—bepaaldelijk Maupeou-hervormingen (1768–1774)—rivaliserende soevereiniteitsconcepten?',
      [
        'Parlements riepen oude grondwetsrechten tegen de monarchie aan',
        'Parlements waren enige legitieme autoriteit en wisten altijd koninklijke hervormingen af',
        'Maupeou-hervormingen waren voorbijgaand en zouden geen blijvende impact hebben',
        'Parlements en kroon werkten altijd samen zonder conflict',
      ],
      0,
      'Parlements gebruikten "remonstrantie" edic-tegenstand, stellend "Frankrijk\'s oude grondwet" vertegenwoordiging. Maupeou verdreef hen, absolute soevereiniteit asserting. Hun recall (1774) absolutisme-beperkingen signaleerde.',
    ],
    [
      'Hoe beïnvloedde fysiocratische theorie—stellend land is enige rijkdombron en enkel-belastingproposering—voor-Revolutionaire fiscale debat?',
      [
        'Fysiocraten tartten handelsprivilege maar vervreemdden financiers',
        'Fysiocraten implementeerden succesvol hun stelsel en elimineerden alle deficits',
        'Ze hadden geen 18e-eeuws-gedachte invloed en werden volledig verworpen',
        'Hun theorie verstevigde belastingfarming en venaalsambten',
      ],
      0,
      'Turgot en Necker riepen fysiocratische ideeën aan belastingfarming en monopolies aan te vallen. Fysiocratische proposering bedriegde gevestigde financiële belangen, triggering backlash wat hervorming-inspanningen verzwakte.',
    ],
    [
      'Welke grondwetse ambiguïteit en geestelijke tegenstand tegen Civiele Constitutie van Geestelijkheid schiepen na-1791 tegen-revolutionaire recrutering?',
      [
        'Niet-eedige priesters werden verzetssymbolen in het westen',
        'Alle geestelijken omarmden dol de Civiele Constitutie zonder tegenstand',
        'Het had geen religieuze dimensie en was zuiver fiscale maatregel',
        'De Constitutie verenigde alle geestelijken achter Revolutionair-regering',
      ],
      0,
      'De Civiele Constitutie splitste geestelijkheid in "constitutioneel" en "niet-eedige" facties. De schisma stelde conservatieve organiseerders katholieken mobiel maken rond religieus grief, Vendéenne-opstandingen voedend.',
    ],
    [
      'Hoe rechtvaardigd Robespierre\'s Comité voor Publieke Veiligheid escalerend terreur via "deugd" en algemeenzin-discourse?',
      [
        'Robespierre zag terreur als noodzakelijk voor de volkswil',
        'Robespierre was geheel terreu-tegengesteld en werkte executies voorkoming',
        'Het Comité gebruikte terreur zonder ideologische rechtvaardiging',
        'Robespierre accepteerde klassieke liberalisme en onvoorwaardelijke individurechten',
      ],
      0,
      'Robespierre fuseerde Rousseau-volkswil met terreur: volksvijanden versperden deugd; hun eliminatie zuiverde Republiek. Deze ideologie rechtvaardigd ongekende geweld als moreel handelen.',
    ],
    [
      'Welke rol speelde massale conscriptie (levée en masse, 1793) in Revolutionaire en Napoleonse militaire dominantie, en hoe transformeerde het oorlogvoering?',
      [
        'Het schiep enorme legers die professionele troepen overweldigden',
        'Massale conscriptie was onpopulair en werd nooit werkelijk geïmplementeerd',
        'Het werd gebruikt uitsluitend marine en had geen landkrijgswerkingeffect',
        'Andere Europese naties hadden groterere conscipitieprogramma\'s reeds geïmplementeerd',
      ],
      0,
      'De levée en masse mobiliseerde gehele bevolkingen als soldaten. Revolutionaire en Napoleonse legers waren 200.000–400.000, tradititonele-krachten verre te boven. Deze transformatie maakte Frankrijk twee decennia militair dominant.',
    ],
    [
      'Hoe hermodelde Napoleons Continentaal Stelsel—Britse handelsblocade—Europese economische-integratie en genereerde tegenstand tegen Franstalige dominantie uiteindelijk?',
      [
        'Het verrijkte Franse vervaardigers maar verarmde bondgenoten',
        'Het Continentaal Stelsel elimineerde alle internationale handel permanent',
        'Het werd universeel geprezen en verstevigde Franstalige allianties',
        'Brittannië was economisch verwoest en Frankrijkkapitulatie',
      ],
      0,
      'Het Continentaal Stelsel subordineerde geallieerde economieën Franse belangen. Economische hardheid bezette territoria genereerde nationalisme en ressentiment, zwakkend Napoleons coalitiebouw.',
    ],
  ],
  professor: [
    [
      'Hoe institutionaliseerden compositiones (Merovingische erfenis-verdeelingscompositieregels) politiek stelsel wat centraal-autorite paradoxaal verzwakte terwijl latere feodale-hiërarchievoorafstand etableerde?',
      [
        'Compositiones lieten ambtenaren macht van zwakke koningen overnemen',
        'Compositiones schaffte erfenis volkomen af en instaleerde gekozen regeerders',
        'Ze verstevigden centrale monarchie door alle macht in één erfgenaam concentrering',
        'Ze waren uit Rome geïmporteerd en hadden niets met Frankische gewoon',
      ],
      0,
      'Compositiones regulariseerden erfgenaamverdeling maar schiepen machtsvacuüms. Mayors gebruikten fractieuzeopvolgingsruzies, hun administratieve-controle gebruikmakend zich van paleisambtenaren tot quasi-soevereine magnaten transformeren.',
    ],
    [
      'In welke mate constringeerde vroeg-Karolingische fiscale crisis—uit dalende poenitentiele-belastingen en monetisering-uitdagingen voortvloeiend—Pepin III en Karelsuitbreidingsmogelijkheden militair?',
      [
        'Fiscale tekorten dwongen tot herverdeling van kerkgronden als leengoed',
        'Ze hadden onbeperkte geldmiddelen en faces nooit fiscale-beperkingen',
        'Fiscale-beleid was irrelevant militaire-mogelijkheid of feodalisme-vorming',
        'De Kerk financierden alle militaire campagnes via tienden en libre-donatie-middelen',
      ],
      0,
      'Pepins Kerk-grond-seculière (laymen-bevorderde-confiscatie, loyaal-volgeling-begiftiging) fiscale-crises adresseerden terwijl krijgers aan kroon via grondgift-vassalage bondelden—proto-feodale innovatie.',
    ],
    [
      'Hoe voorzegde laat-7e-eeuwse Neutriaanse hegemonie onder Paleismeesters (bepaaldelijk Pippinid-clan) administratieve-kantoor-transformatie naar politieke-dynastieën?',
      [
        'Mayors zetten erfelijk ambt en schatkistcontrole om in dynastieke macht',
        'Mayors waren voorbijgaande ambtenaren zonder macht-accumulatie of dynastie-stichting mogelijkheid',
        'Administratieve-ambten waren altijd politieke-macht-scheiding',
        'De Pippinids hielden nooit ambt en hadden geen Merovingische-bestuurs-rol',
      ],
      0,
      'Paleismeesters gebruikten administratieve-huishouds-controle patronage-netwerk-bouw, gronden- en ambten-verdeling, dynastie-erfenis-claim-establering. Deze ambt-naar-dynastie-transformatie feodalisme voorafschepping.',
    ],
    [
      'Welk historiografisch-debat adresseert Benedictijnse-klooster-hervorming (Cluny, later Cîteaux) Kapetingische-wereldlijke-autoriteit-enablement of -constrictering in 11e–13e-eeuwen?',
      [
        'Geleerden debatteren of kloosterhervorming koninklijke legitimiteit versterkte',
        'Alle kloosters waren volledig aan kroon onderworpen alle-tijdsperiodes',
        'Kloosters en wereldlijke-regeerders hadden nul interactie',
        'Benedictijnse-hervorming was zuiver-geestelijke-beweging zonder politieke-implicatie',
      ],
      0,
      'Cluny en Cîteaux winnen lokale-jurisdictie-uitzonderingen, Kapetingisch-controle-zwakking. Koninklijke-patronage-ondersteunde-hervorming legitimiteit-aankoop toch. Het gevolg was gemengd: kerkelijke-macht groeide terwijl Kapetingen prestige wonnen.',
    ],
    [
      'Hoe exponeerde Kapetingische-huwelijks-strategie—Eleonore van Aquitanië huwelijk aan Lodewijk VII, dan Hendrik II Engeland, dan Angevijnse-grondgebied-controle—dynastieke-fragilititeit en voorboden Honderdjarig-Oorlog?',
      [
        'Eleonore\'s huwelijk bracht Aquitanië naar de Angevijnen.',
        'Eleonore\'s-huwelijken hadden politieke-betekenis nul',
        'De huwelijken verenigden Frankrijk permanent conflictloos',
        'Eleonore was nooit betrokken politieke-huwelijken of bestuur',
      ],
      0,
      'Eleonore bracht Aquitanië Lodewijk toe, dan Hendrik II\'s-Angevijnse-imperium overdracht. Haar-huwelijken verstevigden Kapetingisch-prestige paradoxaal terwijl de rivaal (Angevinse) creeerden die hen drie-eeuwen bedriegde.',
    ],
    [
      'In welke mate hermodelde Bedelmonniken-orden\'s-intellectuele-onafhankelijkheid en stedelijke-preek pauselijke-autoriteit en wereldlijke-koninklijke-ideologie in 13e-eeuw?',
      [
        'Bedelmonniken werden tussenpersonen tussen paus en koningen',
        'Bedelmonniken waren volkomen lokale-bisschoppen-subordinatie zonder onafhankelijke-rol',
        'Ze verworpen volkomen pauselijke-autoriteit en verdedigden revolutionair-democratie',
        'Ze hadden geen stedelijke-leven of populair-preek-verbinding',
      ],
      0,
      'Dominicanen dienden pauselijke-belangen via-inquisitie; Franciscanen benadrukt evangelische-armoede. Beiden embedden pauselijke-autoriteit in leke-religieuze-praktijk terwijl koninklijks-jurisdictie-uitbreidingsclaim theologische-legitimiteit leverden.',
    ],
    [
      'Hoe construeerde Valois-legitimiteit-doctrine—Salische-wet, Filips III-afstamming, simbolieke-Engels-"usurpering"-onderscheiding—proto-nationalistische-Franse-identiteit wat dynastieke-particulariteit-voorbijwas?',
      [
        'Valois-juristen gebruikten Salische wet tegen Engelse aanspraken',
        'Nationale-identiteit bestond voor Valois en had Valois-verbinding nul',
        'Salische-wet was universeel-aanvaard en speelde legitimiteits-dispute-rol nul',
        'De Valois hadden geen bijzondere Frans-identiteit of legitimiteits-aanspraak',
      ],
      0,
      'Valois-juristen manipuleerden Salische-wet, vooroudersvoorbijgaand, anti-Engels-sentiment "Frankrijk" als erfelijk-entiteit argumen. Dit nationalisme uitstelde uiteindelijk dynastieke-doodgaan; de natie overleefde haar koningen.',
    ],
    [
      'Hoe exponeerde aristocratische-factionering van de Fronde—vermomd in feodale-homage-relaties en parlementaire-grondwets-beweringen—absolute-monarchie en adellijk-privilege ideologische-contradicties?',
      [
        'Frondeurs verzetten zich tegen centralisatie maar faalden.',
        'De Fronde stelde succesvol democratisch-regering in',
        'Er waren geen-contradicties tussen absolutisme en adellijk-privilege',
        'De Fronde was zuiver boerenopstand',
      ],
      0,
      'Fronde-rebellen gebruikten feodale-taal en parlementaire-grondwets-constitutionalisering Lodewijk XIV-centralisatie-tegenstand. Hun-onderdrukking toonde absolutisme feodale-reciprociteit en jurisdictie-pluralisme-vernietiging vereiste.',
    ],
    [
      'In welke mate vertegenwoordigde intendant-stelsel—kroon-directe-autoriteit-centralisatie adel-autoriteit bypassing—feodale-personalisme naar rationeel-juridische-autoriteit-transformatie?',
      [
        'Salarisambtenaren vervingen erfelijke ambtsdragers.',
        'Intendants waren feodale-vasallen zonder nieuwe-kenmerken versus vroegere-ambtenaren',
        'Ze hadden geen bestuur of administratieve-structuur-impact',
        'Het intendant-stelsel verstevigde feodale-adellijk-onafhankelijkheid',
      ],
      0,
      'Intendants vervangden venaalsambten (erfelijk-ambten) salarisbenoeming. Deze feodale-vervanging naar rationele-bureaucratie transformatie ongekende-staats-centralisatie en adellijk-administratieve-autoriteit-verdrijving stelde.',
    ],
    [
      'Hoe structureerde rivaliserende-economische-theorie—fysiocratische-grond-rijkdom vs. mercantilist-handel/vervaardiging—ideologische-strijd laat-18e-eeuwse-hof-politiek fiscale-hervorming?',
      [
        'Fysiocraten verzetten zich tegen belastingfarming en gilden.',
        'Fysiocratische en mercantilist-economisten waren volkomen akkoord',
        'Economische-theorie had geen werkelijke-politieke-hervorming-invloed',
        'Het hof had geen abstract-economische-debat-belangstelling',
      ],
      0,
      'Fysiocraten vertegenwoordigden grond-rijkdom en attackeerden financiers; mercantilisten verdedigden gild-monopolies en bevoordeel-kooplui. Hervorming-pogingen coordinated oppositie-gezicht omdat fiscale-verandering meervoudige-elite-belangen bedreigde gelijktijdig.',
    ],
    [
      'Welk historiografisch-debat omringt Gallicanism-relatie-naar-Franse-soevereiniteit: Stelden kerkelijke-autonomie-staat-sterkte-of-constricte-religieuze-en-jurisdictie-autoriteit in?',
      [
        'Gallicanisme versterkte en beperkte koninklijke macht tegelijk',
        'Gallicanism schaffte volkomen koninklijke-religieuze-autoriteit af',
        'De Kerk handhaafde absolute-staat-controle-onafhankelijkheid',
        'Gallicanism was zuiver-theologie-concept zonder politieke-implicatie',
      ],
      0,
      'Gallicanism verdedigde Franse-pauselijke-onafhankelijkheid terwijl de Kerk staat-onderworpen. Bisschoppen behielden toch uitzonderingen en jurisdictie-beweringen. Dit schiep compromis: religieuze-staat-autoriteit-onderwerping-onderwerpen, toch niet volkomen-subordinatie.',
    ],
    [
      'Hoe exponeerde Septemberslachting-sociale-samenstelling (1792)—niet georganiseerd-morden maar spontane-menigtemassiver—Revolutionaire-publieksorde-ineenstorting en terreur-opkomst als ongearticuleerde-populaire-praktijk?',
      [
        'Parijse menigten doodden geestelijken en adel zonder staatsleiding',
        'Septemberslachtpartijen waren volledig regering-orchestratie en niet spontaan',
        'Ze hadden Schrikbewind-nul-verbinding',
        'De menigten waren minuscule minderheid met verwaarloosbare-historische-impact',
      ],
      0,
      'Septemberslachtpartijen (1.200+ door-menigten-doden) voorafgingen Schrikbewind. Ze exposeerden hoe revolutionaire-schrik populaire-geweld kon motiveren zonder staat-organisatie—Schrikbewind-voorbode.',
    ],
    [
      'In welke mate vertegenwoordigde Vendéenne-opstand (1793–1796) tegen-revolutionaire-boeren-opstand vs. gecoördineerd-royalistische-insurrectie, en wat exponeren debat ländlicher-politisering?',
      [
        'Historici debatteren autonome opstand versus elitecoördinatie',
        'De Vendée was volledig boeren-democratisch-opstand zonder klassencomplex',
        'Het was uitsluitend elite-samenzwering zonder boeren-deelneming',
        'Vendéenne-regio was niet politiek-actief tijdens Revolutie',
      ],
      0,
      'Vendéenne-rebellie mengde autonome-grief (conscriptie-weerstand, religieuze-verdediging) met elite-coordinering. Deze ambiguïteit exponeerde hoe ländliche-bevolkingen Revolutionaire-actoren-werden terwijl manipulatie-onderworpen.',
    ],
    [
      'Hoe schiepen Directoire-structurele-instabiliteit—oscillering oligarchische-democratische-fracties, onvermogen stabiele-eigendom- en leger-loyaliteit-beveiligering—Napoleons-coup-van-18-Brumaire-voorbijgaande-rationalisatie-stabilisatie?',
      [
        'Napoleon bood onstabiele oligarchen een stabiliteitsdeal.',
        'De Directoire was hoog-stabiel en faces geen-crises',
        'De coup was volledig-onwillekeurig en onvolledig-geplanned',
        'De Directoire kon gemakkelijk aangepast hebben en zonder-Napoleon overleefd',
      ],
      0,
      'Directoire-factionalisering, kiezers-onvoorspelbaarheid, militaire-fragmentatie, fiscale-zwakheid schiepen endemische-instabiliteit. Bonaparte stelde oligarchen-koophandel: militaire-orde tegen-eigendom en handel-zekerheid.',
    ],
    [
      'In welke mate schiepen Napoleonisch-Wetboek-eigendom-wetgeving-codificatie, feodalisme-afschaffen, wereldlijke-burgerrecht-rechtsvergelijking-jurisprudentie-revolutie eerder dan louter-Revolutionaire-beleid-implementatie?',
      [
        'Het Wetboek verving gewoonterecht door gepubliceerde wetten.',
        'Het Wetboek was zuiver-administratief zonder filosofische-innovatie',
        'Het was volkomen-feodale-recht-afleiding zonder verandering',
        'Juridische-filosofie was irrelevant Wetboek-construering',
      ],
      0,
      'Het Wetboek-systeem, geschreven, gepubliceerd, format vervangde feodale-recht-ondoorzichtigheid en gewoontevariant. Deze ongeschreven-gewoonterecht naar gerationaliseersde-codes-verschuiving veranderde juridische-autoriteit zelf—methodologische-revolutie.',
    ],
  ],
};
