import type { CategoryContent } from '../row.js';

export const ITALIAN_HISTORY: CategoryContent = {
  bscba: [
    [
      'Welke Italiaanse stadstaat werd de dominante maritieme macht in de Middellandse Zee en controleerde handelsroutes naar het Oosten vanaf de 9e eeuw?',
      [
        'Venetië',
        'Genua',
        'Florence',
        'Milaan',
      ],
      0,
      'Venetië bouwde een uitgebreid maritiem rijk en handelsnetwerk dat tot de Napoleontische verovering de Middellandse Zee domineerde.',
    ],
    [
      'De rijkdom en Renaissance-mecenaat van de familie Medici waren gecentreerd in welke Italiaanse stad?',
      [
        'Florence',
        'Venetië',
        'Rome',
        'Napels',
      ],
      0,
      'De Medici regeerden Florence als handelaren en bankiers, waardoor zij kunstaars steunden en pausen en koninginnen voortbrachten.',
    ],
    [
      'Wat is de term voor de 19e-eeuwse Italiaanse nationalistische beweging die het schiereiland verenigde?',
      [
        'Risorgimento',
        'Restaurazione',
        'Renouveau',
        'Republica',
      ],
      0,
      'Risorgimento ("wederopstanding") verenigde Italië vanuit fragmentatie en beëindigde eeuwen van buitenlandse overheersing.',
    ],
    [
      'Welke militaire generaal leidde vrijwilligers om Sicilië en Napels in 1860-1861 te veroveren?',
      [
        'Giuseppe Garibaldi',
        'Victor Emmanuel II',
        'Camillo Cavour',
        'Luigi Settimbrini',
      ],
      0,
      'Garibaldi\'s Duizenden veroverden Sicilië en Napels, waardoor de politieke eenheid van het koninkrijk rechtstreeks mogelijk werd.',
    ],
    [
      'Welke Piemontese staatsman organiseerde de diplomatieke en politieke eenheid van Italië?',
      [
        'Camillo Cavour',
        'Giuseppe Mazzini',
        'Giuseppe Garibaldi',
        'Victor Emmanuel II',
      ],
      0,
      'Cavour, minister-president van Piëmont, gebruikte allianties en diplomatie om Piëmont als centrum van eenheid te positioneren.',
    ],
    [
      'In welk jaar werd het Koninkrijk Italië officieel uitgeroepen?',
      [
        '1861',
        '1848',
        '1815',
        '1870',
      ],
      0,
      'Het Koninkrijk Italië werd op 17 maart 1861 onder Victor Emmanuel II uitgeroepen, hoewel Rome pas in 1870 werd geïncorporeerd.',
    ],
    [
      'Welke dictator kwam aan de macht in Italië via de Mars op Rome in 1922?',
      [
        'Benito Mussolini',
        'Victor Emmanuel III',
        'Francesco Crispi',
        'Luigi Facta',
      ],
      0,
      'Mussolini\'s Zwarthemden marcheerden in 1922 op Rome, waardoor de koning hem benoemde tot minister-president.',
    ],
    [
      'Welke grote gebeurtenis in 1870 voltooide de Italiaanse territoriale eenheid?',
      [
        'Italiaanse troepen veroverden Rome en annexeerden pauselijke gebieden',
        'Paus Pius IX sloot zich vrijwillig aan bij het koninkrijk',
        'Internationale mogendheden gaven Rome aan Italië',
        'Het Vaticaan sloot een vredesverdrag',
      ],
      0,
      'In 1870 doorbraken Italiaanse troepen de muren van Rome, eindigde de pauselijke wereldlijke macht en voltooide de eenheid.',
    ],
    [
      'In welk jaar werd de Italiaanse Republiek opgericht, ter vervanging van de monarchie?',
      [
        '1946',
        '1943',
        '1948',
        '1950',
      ],
      0,
      'Een referendum in juni 1946 schrapte de monarchie; Italië\'s nieuwe grondwet trad in werking in januari 1948.',
    ],
    [
      'Welke vreemde mogendheid domineerde veel van Italië in de 16e en 17e eeuw via koninkrijken en stadstaatcontrole?',
      [
        'Spanje',
        'Frankrijk',
        'Oostenrijk',
        'Het Ottomaanse Rijk',
      ],
      0,
      'Spanje regeerde Zuid-Italië en hield Milaan na de Italiaanse Oorlogen, domineerde twee eeuwen lang het schiereiland.',
    ],
    [
      'Na de Napoleontische Oorlogen, welke vreemde mogendheid hield Lombardije en Venetië?',
      [
        'Oostenrijk',
        'Frankrijk',
        'Rusland',
        'Pruisen',
      ],
      0,
      'Oostenrijk controleerde Lombardije en Venetië, waardoor het de belangrijkste hinderpaal voor Noord-Italiaanse eenheid werd.',
    ],
    [
      'Welke revolutionair stichtte Jong Italië, een geheime beweging die eenheid bevorderde?',
      [
        'Giuseppe Mazzini',
        'Camillo Cavour',
        'Victor Emmanuel II',
        'Niccolò Machiavelli',
      ],
      0,
      'Mazzini richtte Jong Italië (1831) op om nationalistische actie aan te sporen, hoewel zijn republicanisme aan Cavours monarchie verloor.',
    ],
    [
      'Welk Noord-Italiaans koninkrijk werd het politieke en militaire centrum van eenheid?',
      [
        'Piëmont',
        'Lombardije',
        'Venetië',
        'Savoye',
      ],
      0,
      'Piëmont, onder het Huis Savoye, had Italië\'s sterkste leger en duidelijkste eenheidsvisioen.',
    ],
    [
      'Welke Middellandse Zee-stadstaat was behalve Venetië een beroemde middeleeuwse en Renaissance maritieme macht?',
      [
        'Genua',
        'Amalfi',
        'Pisa',
        'Salerno',
      ],
      0,
      'Genua rivaliseerde met Venetië als maritieme republiek, controleerde handel in Middellandse Zee en Zwarte Zee.',
    ],
    [
      'Welk verdrag in 1929 loste de "Romeinse Vraag" op door de onafhankelijkheid van Vaticaanstad vast te stellen?',
      [
        'Lateraansverdrag',
        'Verdrag van Rome',
        'Conciliair Akkoord',
        'Pauselijk Handvest',
      ],
      0,
      'Het Lateraansverdrag creëerde Vaticaanstad als onafhankelijke staat en beëindigde pauselijke territoriale geschillen.',
    ],
  ],
  msc: [
    [
      'Waarom prevaleert Cavours monarchistische aanpak uiteindelijk over Mazzini\'s republicaans ideaal?',
      [
        'Piëmont\'s militaire kracht en diplomatieke vaardigheid ondermijnden grassroots-bewegingen; realisme bewees effectiever dan ideologie',
        'Republieken waren inherent instabiel',
        'Het pausdom eiste een monarchie',
        'Mazzini controleerde het leger',
      ],
      0,
      'Cavour\'s pragmatische diplomatie en Piëmont\'s macht versloegen Mazzini\'s federalistisch republicanisme.',
    ],
    [
      'Onder het Verdrag van Turijn (1860) wat cedeerde Piëmont aan Frankrijk?',
      [
        'Nice en Savoye',
        'Piëmont zelf',
        'Lombardije en Venetië',
        'Sicilië en Napels',
      ],
      0,
      'Cavour verhandelde Nice en Savoye voor Frankrijk, waardoor hij cruciale steun tegen Oostenrijk verkreeg.',
    ],
    [
      'Het conflict tussen Mazzini\'s visie en Cavour\'s strategie resulteerde in welk gevolg?',
      [
        'Eenheid als constitutionele monarchie, niet als republiek',
        'Italië werd een kerkelijke theocratie',
        'Italië splitste in onafhankelijke republieken',
        'Mazzini\'s model werd universeel aanvaard',
      ],
      0,
      'Cavour\'s realisme beveiligde eenheid als monarchie onder het Huis Savoye.',
    ],
    [
      'De Italiaanse Oorlogen (1494-1559) ontstonden vooral uit rivaliteit tussen welke twee mogendheden?',
      [
        'Spanje en Frankrijk',
        'Venetië en het Pausdom',
        'Oostenrijk en Pruisen',
        'Ottomaanse Rijk en Venetië',
      ],
      0,
      'Habsburgers (Spanje) en Valois (Frankrijk) vochten voor Italiaanse controle, waardoor het schiereiland verdeeld bleef.',
    ],
    [
      'Welk geslacht regeerde het Koninkrijk der Twee Siciliën (Napels en Sicilië) na 1713?',
      [
        'Het Huis Bourbon',
        'Het Huis Valois',
        'Het Huis Habsburg',
        'Het Huis Oranje',
      ],
      0,
      'Bourbonkoning regeerden Napels en Sicilië als welvarend koninkrijk apart van Noord-Italië.',
    ],
    [
      'Welke jurisconsult uit de Verlichting\'s verhandeling over misdaad en straf hervormdde Europese wetgeving?',
      [
        'Cesare Beccaria',
        'Giovanni Vico',
        'Niccolò Machiavelli',
        'Antonio Genovesi',
      ],
      0,
      'Beccaria\'s werk uit 1764 tegen foltering en doodstraf beïnvloedde de moderne strafwetgeving.',
    ],
    [
      'Het Congres van Wenen (1815) fragmenteerde Italië opzettelijk onder Oostenrijkse dominantie. Wat was Metternich\'s doel?',
      [
        'Het voorkomen van toekomstige eenheid door evenwicht van zwakke, concurrerende staten te handhaven',
        'Italië onmiddellijk te eenigen',
        'Een Italiaanse republiek in te stellen',
        'Pauselijke wereldlijke macht te herstellen',
      ],
      0,
      'Metternich\'s Weense regeling bracht Italië terug tot fragmentatie om nationalistische uitdagingen te voorkomen.',
    ],
    [
      'Wie commandeerde Italiaanse troepen die Rome in 1870 veroverden?',
      [
        'Generaal Raffaele Cadorna',
        'Giuseppe Garibaldi',
        'Koning Victor Emmanuel II',
        'Camillo Cavour',
      ],
      0,
      'Generaal Cadorna\'s troepen doorbraken Rome\'s muren, eindigde de pauselijke wereldlijke macht.',
    ],
    [
      'Italië\'s alliantie met Pruisen in 1866 in de Austro-Pruisische Oorlog stelde het in staat welk grondgebied te verwerven?',
      [
        'Venetië',
        'Piëmont',
        'Toscane',
        'Sicilië',
      ],
      0,
      'Pruisische overwinning stelde Italië in staat Venetië te veroveren, het laatste grote Italiaanse grondgebied van Oostenrijk.',
    ],
    [
      'Het Lateraansverdrag (1929) stelde wat in met betrekking tot de pauselijke status?',
      [
        'Vaticaanstad als onafhankelijke soevereine staat onder de Paus',
        'Volledige pauselijke herstel van de Pauselijke Staten',
        'Gezamenlijk bestuur van Rome door Paus en Italië',
        'Volledige scheiding van kerk en staat',
      ],
      0,
      'Het verdrag creëerde Vaticaanstad en loste de "Romeinse Vraag" van pauselijke onafhankelijkheid op.',
    ],
    [
      'Mussolini\'s Pact of Steel uit 1939 met nazi-Duitsland verbond Italië waaraan?',
      [
        'Onvoorwaardelijke militaire steun aan Duitsland in elk conflict',
        'Fusie van Italiaanse en Duitse regeringen',
        'Overdracht van Italiaanse koloniën aan Duitsland',
        'Onmiddellijke aanvaarding van nazi-rassenwatten',
      ],
      0,
      'Het Pact of Steel bond Italië militair aan Duitsland, leidend tot WWII-betrokkenheid.',
    ],
    [
      'Na Italië\'s wapenstilstand met de Geallieerden in 1943 welke marionettenstad stichtte Duitsland in het noorden?',
      [
        'De Italiaanse Sociale Republiek',
        'De Voorlopige Italiaanse Regering',
        'Het Noord-Italiaans Koninkrijk',
        'De Fascistische Democratische Republiek',
      ],
      0,
      'Duitsland creëerde de Italiaanse Sociale Republiek als nazimarionettensat in bezet Noord-Italië.',
    ],
    [
      'Welk corruptieschandaal in de late jaren 1980 en vroege jaren 1990 destabiliseerde de Eerste Republiek?',
      [
        'Tangentopoli',
        'Mafia Maxima',
        'Operazione Cristallo',
        'Scandalo Europeo',
      ],
      0,
      'Tangentopoli ("Omkoopstad") onthulde systemische corruptie, triggerde onderzoeken die de Eerste Republiek destabiliseerden.',
    ],
    [
      'Waarom was Piëmont\'s alpine geografische positie voordelig voor eenheid?',
      [
        'Het liep door de Alpen heen, controleerde Italiaanse en trans-Alpijnse middelen, waardoor diplomatieke hefboomwerking ontstond',
        'Het was de rijkste regio in Italië',
        'Het had de grootste bevolking',
        'Het werd beschermd voor alle invasies',
      ],
      0,
      'Savoye\'s duaal-monarchie-positie stelde Cavour in staat te onderhandelen met Frankrijk terwijl hij Italiaanse hegemonie bouwde.',
    ],
    [
      'Hoe beïnvloedde de dominantie van Piemontese en Toscaanse dialecten tijdens eenheid de Italiaanse taal?',
      [
        'Piëmont\'s politiek leiderschap en Toscane\'s literaire erfgoed maakten hun dialecten de basis van standaard-Italiaans',
        'De Paus bepaalde dat alleen Piemontees zou worden gesproken',
        'Alle Italianen spraken van nature dezelfde dialect',
        'Zuid-Italianen weigerden andere dialecten te leren',
      ],
      0,
      'Piëmont\'s macht en Toscane\'s literaire prestige stelden hun varianten als basis van modern Italiaans vast.',
    ],
  ],
  phd: [
    [
      'Hoe institutionaliseerde de Vrede van Westfalen (1648) Italiaanse fragmentatie onder Habsburg-dualisme?',
      [
        'Het bevestigde de verdeling van Italië tussen Oostenrijkse en Spaanse sferen, voorkwam eenheid voor 123 jaar',
        'Het verleende Frankrijk volledige dominantie over Italië',
        'Het herstelde het Romeinse Rijk onder pauselijk gezag',
        'Het stichtte het eerste verenigde Italiaanse koninkrijk',
      ],
      0,
      'Westfalen sloot Italië in Habsburgse controle, fragmenteerde het schiereiland tot Napoleontische verstoring.',
    ],
    [
      'Wat was de strategische doctrine achter Metternich\'s opzettelijke Italiaanse fragmentatie na 1815?',
      [
        'Verenigd Italië zou Oostenrijkse Middellandse Zee-hegemonie bedreigen; zwakke, concurrerende staten dienden Oostenrijkse veiligheid',
        'Metternich geloofde dat Italië te democratisch zou worden',
        'Hij wilde pauselijke politieke macht versterken',
        'Hij ondersteunde Italiaanse onafhankelijkheid en nationalisme',
      ],
      0,
      'Metternich\'s concert rationaliseerde fragmentatie als noodzakelijk om zowel Franse als Italiaanse nationalisme in te dammen.',
    ],
    [
      'Waarom hervormdden de mislukte liberaal-nationalistische opstandingen 1848-49 de Italiaanse politieke strategie?',
      [
        'Militaire nederlagen door Oostenrijk en regionale verdeling discrediteerden volksrevolutie, heroriënteerden élites naar diplomatiek en militair vakmanschap',
        'De opstandingen waren onmiddellijk succesvol',
        'Er was geen militaire nederlaag',
        'Italianen verwerpen nationalisme volledig',
      ],
      0,
      'De ineenstorting in 1848-49 discrediteerde volksbewegingen, opende pad naar Cavours elitegeleid realisme.',
    ],
    [
      'Hoe divergeerde Garibaldi\'s pragmatische aanvaarding van Victor Emmanuel II van Mazzini\'s republicanisme?',
      [
        'Garibaldi prioriteerde eenheid boven ideologie; Mazzini verwerpen monarchie, creëerden breuk die Cavour uitbuitte',
        'Mazzini leidde monarchistische samenzweringen',
        'Garibaldi wilde het Pausdom herstellen',
        'Ze hadden identieke politieke visies',
      ],
      0,
      'Garibaldi\'s bereidheid Savoye aan te accepteren maakte Cavour\'s monarchistische schikking mogelijk, isoleerde Mazzini\'s republicanisme.',
    ],
    [
      'Wat was het "Non expedit"-decreet, en hoe belemmerden het de Italiaanse natiebouw?',
      [
        'Pius IX verbood katholieke deelname aan het nieuwe koninkrijk, vervreemden het pausdom en verzwakten democratische deelname',
        'Het verplichtte katholieken eenheid te ondersteunen',
        'Het verordonneerde pauselijk gezag over heel Italië',
        'Het schrapte Italiaanse taal en cultuur',
      ],
      0,
      'Non expedit isoleerde het pausdom 60 jaar uit Italiaans burgerleven, fragmenteerde institutionele eenheid.',
    ],
    [
      'Welke structurele factoren maakten Zuid-Italië chronisch onderontwikkeld na eenheid?',
      [
        'Eeuwen van feodale latifundia, Bourbonverwaarlozing van infrastructuur, Risorgimento-hulpbronnentrekking noordwaarts creëerden aanhoudende ongelijkheid',
        'Zuid-Italianen waren van nature minder capabel',
        'De Mafia veroorzaakte alleen armoedte',
        'Het Noorden had geen feodale geschiedenis',
      ],
      0,
      'Mezzogiorno\'s feodale landbouw, zwakke industrie, en brigandage bleken weerbarstig tegen Piemontese modernisering.',
    ],
    [
      'De zuidelijke "brigandage-oorlog" (1861-1876) weerspiegelde welk onderliggend sociaal conflict?',
      [
        'Landloze boeren, weerstand tegen militaire dienst, Piemontese militaire onderdrukking creëerden quasi-guerrilla-plattelandsinsurrectie',
        'Spaanse indringers startten de opstandingen',
        'Buitenlandse huurlingen veroorzaakten brigandage alleen',
        'Het was puur een Mafia-criminaliteit',
      ],
      0,
      'Brigandage in Mezzogiorno weerspiegelde echte campagnegrieven, onderdrukt door harde bezetting zonder hervorming.',
    ],
    [
      'Wat karakteriseerde Giovanni Giolitti\'s regering (1903-1914) als overgangsperiode tussen liberaal Italië en fascisme?',
      [
        'Strategische kiesrechtsuitbreiding en arbeidsbesprekingen zonder fundamentele structuurherstel, stelde diepere verandering uit',
        'Volledige afwijzing van democratie',
        'Totale alliantie met het Pausdom tegen secularisme',
        'Herstel van absolute monarchie',
      ],
      0,
      'Giolitti\'s flexibel liberalisme verbreedde stemrecht terwijl conservatieve élites behield, stagneerde transformatieve hervorming.',
    ],
    [
      'Hoe voedde de notie van "vittoria mutilata" (verminkste overwinning) wrok na Wereldoorlog I?',
      [
        'Italië won maar mislukte alle beloofde Italianstalige gebieden (Fiume, Dalmatie) te verwerven, creëerden nationalistische grieven fascisme uitbuitte',
        'Italië verloor de hele oorlog',
        'Italië verkreeg meer dan beloofd',
        'Italië was nooit betrokken bij WWI',
      ],
      0,
      'Naoorlogs territoriaal teleurstelling en nationalistische wrok creëerden condities voor Mussolini\'s fascistische opkomst.',
    ],
    [
      'Wat was de filosofische basis van Mussolini\'s corporatistisch economisch model?',
      [
        'Staatsgecontroleerde syndicaten organiseerden arbeid en kapitaal, schrapten klassenconflict en vrije markten voor totale mobilisatie',
        'Vestiging van vrij-marktkapitalisme',
        'Welverdeling aan arbeiders alleen',
        'Herstel van feodale landbouwstelsels',
      ],
      0,
      'Italiaans corporatisme integreerde alle producenten in fascistische syndicaten, schrapte onafhankelijke markten en vakbonden.',
    ],
    [
      'Hoe verschilden Italië\'s rassenwatten van 1938 aanvankelijk van nazi-Duitsland\'s implementatie?',
      [
        'Italiaanse watten werden minder streng afgedwongen wegens sociale en katholieke weerstand; WWII-onheil maakte latere vervolging mogelijk',
        'Italiaanse rassenwatten waren onmiddellijk even streng',
        'Italië stelde nooit rassenwatten in',
        'Italië overtrof onmiddellijk nazi-rassenmaatregelen',
      ],
      0,
      'Italiaans fascisme nam rassenwatten aan voor nazi-afstemming, maar sociale weerstand verzwakte handhaving tot Duitse bezetting.',
    ],
    [
      'Welke paradoxale politieke status ontstond uit Italië\'s september 1943 wapenstilstand en latere oorlogsverklaring?',
      [
        'Italië werd medevechter die met geallieerden vocht terwijl het noorden Duitse-bezet bleef, splitste de natie militair en ideologisch',
        'Italië trok zich vreedzaam geheel terug van WWII',
        'Italië bleef onder Mussolini verenigd',
        'Duitsland evacueerde Italië onmiddellijk',
      ],
      0,
      'Badoglio\'s wapenstilstand splitste Italië tussen geallieerde zuiden en Duitse-marionettennoorden, creëerde medevechtersparadox.',
    ],
    [
      'Hoe hervormdde de Italiaanse Communistische Partij (PCI) institutionele status het naoorlogse democratie?',
      [
        'PCI\'s electorale legitimiteit en weigeringvan macht stelden het als permanente oppositie die centrumhegemonie intemde en pluralisme institutionaliseerde',
        'De PCI grepen onmiddellijk totale macht',
        'Het had geen electorale steun',
        'Het verwerpen alle democratische deelname',
      ],
      0,
      'PCI\'s democratische legitimiteit voorkwam éénpartijenhegemonie, institutionaliseerde linkse inbreng in de Eerste Republiek.',
    ],
    [
      'Welk institutioneel kenmerk van de Eerste Republiek ondermijnden Tangentopoli\'s onthullingen fundamenteel?',
      [
        '"partitocrazia"-systeem dat Italiaanse politiek sinds 1948 structureerde, triggerde grondwettelijke en electorale overgang',
        'Het had geen institutioneel gevolg',
        'Het versterkte de monarchie',
        'Het verminderde stemrechten',
      ],
      0,
      'Tangentopoli ontmantelde naoorlogse partijen (DC, PSI) en triggerde electorale hervorming, beëindigde Eerste Republiek\'s consensusmodel.',
    ],
    [
      'Hoe vooruitgelopen Petrarca\'s artikulatie van humanistische deugd in de 14e eeuw op Florentijnse burgerrepublicanisme?',
      [
        'Petrarca\'s verheffen van klassieke retoriek en deugd als burgergereedschappen werd fundamenteel voor Florentijnse republicanse ideologie',
        'Petrarca vond fascisme uit',
        'Petrarca was monarchist',
        'Klassiek leren speelde geen rol in Renaissance-politiek',
      ],
      0,
      'Petrarcaanse humanisme\'s link tussen tekstuele deugd en burgerbetrokkenheid ondersteunde Florentijnse republicanse zelfbewustzijn.',
    ],
  ],
  professor: [
    [
      'Hoe vertegenwoordigde Florence\'s catasto-hervorming van 1427 technologische en bestuurlijke innovatie die staatsvoeding hervormdde?',
      [
        'Gestandaardiseerde eigendomstelling en progressieve belasting maakten directe vermogensbeoordeling mogelijk, voorkwam moderne bureaucratische centralisatie en Medici\'s financieel-politieke apparaat',
        'Het schrapte alle belasting',
        'Het herstelde puur feodalisme',
        'Het vond aandelenmarkten uit',
      ],
      0,
      'Catasto\'s gererationaliseerde documentgestuurde beoordeling werd fundamenteel voor vroegmoderne staatsvoeding en fiscale controle.',
    ],
    [
      'Hoe zowel mogelijk gemaakt als beperkt het condottieri-systeem gecentraliseerde Italiaanse staatsontwikkeling?',
      [
        'Huurlingaannemers bevrijdden stadsstaten van feodale legering terwijl ze gezamenlijk militair bevel voorkwamen, maakten territoriële expansie mogelijk maar belemmerde nationale integratie',
        'Condottieri hadden geen politieke invloed',
        'Ze vereinigden onmiddellijk Italië',
        'Ze schrapten alle militaire activiteit',
      ],
      0,
      'Condottieri professionaliseerden oorlogvoering maar fragmenteerden militaire loyaliteit, belemmerde nationale verdediging tot natiestaat-era.',
    ],
    [
      'Hoe veranderden het Verdrag van Utrecht (1713) en latere Bourbonregalisme de ecclesiastische-politieke balans in Napels?',
      [
        'Utrecht bevestigde Bourbonhegemonie terwijl pauselijke seculiere vorderingen verminderde, stelde regalist onderwerping van kerkbenoemingen aan staatsautoriteit vast',
        'Het Pausdom verkreeg volledige territoriale controle',
        'Ecclesiastische autoriteit werd geheel afgeschaft',
        'Het verdrag had geen politieke gevolgen',
      ],
      0,
      'Bourbonregalisme onderwierp kerkbenoemingen aan staatsautoriteit, verminderde pauselijke invloed en maakte Verlichtingshervorming mogelijk.',
    ],
    [
      'Welke ideologische erfenis lieten de mislukte Jacobijnse republieken (1799-1815) ondanks militaire ineenstorting onder Wenen na?',
      [
        'Constitutionele vertegenwoordiging, secularisering, nationalisme werden modellen die herleefden in 1820, 1848 en Risorgimento',
        'Jacobijnisme had geen blijvende intellectuele erfenis',
        'De Jacobijnen verenigden Italië onmiddellijk',
        'Nationalisme werd na 1815 uitgevonden',
      ],
      0,
      'Hoewel militair verslagen, injeceerden Jacobijnse republieken grondwettelijke en nationalistische idealen die voortdurend herleefden.',
    ],
    [
      'Hoe wijken Cavour\'s realisme af van de mislukte opstandingen 1848-49, en wat was zijn kernstrategische inzicht?',
      [
        'Cavour verliet volksnationalisme voor grootmacht-alliantiediplomatiek, erkende dat alleen elitaire diplomatie Oostenrijk kon verslaan',
        'Cavour ondersteunde uitsluitend volksrevolutie',
        'Hij verwierpen alle banden met vreemde machten',
        'Hij vertrouwde alleen op diplomatieke brieven',
      ],
      0,
      'Cavour\'s pragmatische verschuiving van grassroots naar diplomatieke diplomatie maakte eenheid mogelijk waar ideologie alleen mislukte.',
    ],
    [
      'Wat was het strategische belang van het geheime Plombières-akkoord (1858) tussen Cavour en Napoleon III?',
      [
        'Het beveiligde Franse militaire steun tegen Oostenrijk maar verbond Italië tot Nice en Savoye afstand, stelde eenheid\'s seculier-monarchistische karakter vast op kosten van nationalisme',
        'Plombières verbood enige Franse alliantie',
        'Het garandeerde Italië zou Franse kolonie worden',
        'Het stelde onmiddellijk pauselijk gezag vast',
      ],
      0,
      'Plombières-pakket verhandelde Savoye-gebieden voor doorslaggevend ingrijpen, institutionaliseerde eenheid\'s monarchist-seculier trajectory.',
    ],
    [
      'Hoe bemoeilijkten de structurele onderontwikkeling van zuidelijke Mezzogiorno—geworteld in latifundia-feodalisme—naoorlogse nationale integratie?',
      [
        'Eeuwen landbouw op grote landgoederen, brigandage, Piemontese koloniale hulpbrontrekking creëerden aanhoudende klasse- en regionale dualisme die assimilatie weerstonden',
        'Het Zuiden was onmiddellijk welvarend',
        'Structurele ongelijkheid kwam alleen van de Mafia',
        'Noord en Zuid waren gelijk ontwikkeld',
      ],
      0,
      'Questione meridionale\'s feodale erfenis en trekking in stand held regionale dualisme in modern Italië.',
    ],
    [
      'Waarom diende Giovanni Gentile\'s filosofisch actualisme, vastgelegd in Riforma Gentile (1923), fascistische totalitaire pedagogie?',
      [
        'Gentile\'s metafysisch nationalisme verheffen staatsethiek als geschieden\'s verwerkelijking, rechtvaardigen individu-onderwerping aan fascistische collectieve wil',
        'Gentile verzette zich tegen fascisme',
        'Hij pleitte voor zuiver individualisme',
        'Zijn filosofie had geen relatie tot onderwijs',
      ],
      0,
      'Gentile\'s actualisme verschafte filosofische legitimiteit voor fascistische totalitaire pedagogie en jeugdindoctrinatie.',
    ],
    [
      'Hoe onthulden Italiaanse interneringskampen in Libië, Griekenland, en Balkan (1940-43) fascistische imperiale methodologie verschillend van nazi-genocide?',
      [
        'Italiaanse kampen vertrouwden op dwangarbeid, honger, blootstelling eerder dan industriële uitroeiing, onthulden fascistische rassengeweld over Middellandse Zee',
        'Italië stelde nooit kampen in',
        'Italiaanse sterfte was alleen van natuurlijke oorzaken',
        'Kampen waren zuiver voor criminele rehabilitatie',
      ],
      0,
      'Italiaanse interneringskampen doodden duizenden door opzettelijke ontbering, onthulden fascisme\'s dodelijke rassenideologie buiten nazi-typologie.',
    ],
    [
      'Welke institutionele mechanismen maakten PCI\'s integratie in Eerste Republiek consensus ondanks Koude Oorlog anticommunisme mogelijk?',
      [
        'Proportionele vertegenwoordiging en grondwettelijke beperkingen maakten grote-partijconsensus hegemoon, inlijfdden communistische legitimiteit als aanhoudende structurele oppositie',
        'De PCI werd onmiddellijk uitgesloten van politiek',
        'De PCI en fascisten vereinigden',
        'Italië had geen naoorlogse democratische instellingen',
      ],
      0,
      'Proportionele vertegenwoordiging institutionaliseerde communistische deelname, maakte PCI permanente oppositie die uitvoerend gezag intdemde.',
    ],
    [
      'Hoe hervormdden Mussolini\'s interventie in Wereldoorlog I (1915) en latere nederlaag fascisme\'s ontstane ideologie?',
      [
        'WWI\'s "verminkste overwinning"-gat tussen nationalistische verwachtingen en territoriaal winst, gecombineerd met biennio rosso-crisis, creëerden psychische en materiële condities voor fascistische opkomst',
        'Italië won volledige overwinning',
        'Italië leed geen slachtoffers',
        'Naoorlogse welvaart schrapte fascisme',
      ],
      0,
      'Naoorlogs wrok en 1919-22 biennio rosso-crisis creëerden institutionele vacuüm fascisme vulde.',
    ],
    [
      'Wat vertegenwoordigden het Verdrag van Maastricht (1992) en euroverandering (1999-2002) symbolisch voor Italiaanse naoorlogse soevereiniteit?',
      [
        'Vrijwillige supranationale integratie onderwierpen autonome fiscale politiek aan ECB-regels, inverteren 150 jaar Risorgimento-monetair nationalisme',
        'Italië verwerpen de euro permanent',
        'Maastricht had geen economisch gevolg',
        'Italië gaf vrijwillig alle soevereiniteit op',
      ],
      0,
      'Euro-overdracht markeerde diepe heronderhandeling nationalistische monetaire autonomie tijdens eenheid vastgesteld.',
    ],
    [
      'Hoe verschilde Mazzini\'s "guerra popolare" (volksorlog)-ideologie van massamassale campagneinsurrectie van Cavour\'s elitaire diplomatieke realisme?',
      [
        'Mazzini beeldde federaal republicanisme in door grassroots-opstand; Cavour vertrouwde op diplomatieke staatschaff, welke structureel superieur bleek',
        'Mazzini ondersteunde monarchie en Cavour republicanisme',
        'Ze hadden identieke visies',
        'Volksbewegingen slaagden onmiddellijk',
      ],
      0,
      'Mazzini\'s ideologie werd door Cavour\'s diplomatie buitengesloten, institutionaliseerde monarchie boven massamarionettica.',
    ],
    [
      'Wat onthulden Silvio Berlusconi\'s meerdere premierschap (1994-2011) over grondwettelijke spanningen in Tweede Republiek?',
      [
        'Zijn mediabezitstoewijzingsconflicten, gerechtelijke vorderingen voor corruptie, institutionele uitdagingen testen grondwettelijke grenzen op uitvoerend gezag en onthulden democratische kwetsbaarheid',
        'Berlusconi had geen politieke invloed',
        'Hij herstelde fascisme onmiddellijk',
        'Grondwettelijk recht versterkte zich zonder controversie',
      ],
      0,
      'Berlusconi\'s media-politieke hybride en anti-institutionele retoriek testten Italië\'s grondwettelijke beperkingen.',
    ],
    [
      'Hoe hervormdde de pauselijke "wereldlijke macht"-verlies in 1870 en oplossing in Lateraansverdrag (1929) kerk-staatsrelaties in verenigd Italië?',
      [
        'De verlies in 1870 creëerde "Romeinse Vraag", vervreemden het pausdom totdat 1929 Vaticaanstad\'s soevereiniteit conflict oploste, institutionaliseerde separatie',
        'Het Pausdom heroverde alle wereldlijke macht',
        'Kerk en staat werden onmiddellijk gescheiden',
        'Het Lateraansverdrag had geen gevolgen',
      ],
      0,
      'Lateraansverdrag\'s Vaticaanstad-oplossing loste 59 jaar pauselijke-staatconflict op, institutionaliseerde ecclesiastische onafhankelijkheid.',
    ],
  ],
};
