import type { CategoryContent } from '../row.js';

/** Nederlands & internationaal IE-recht. */

export const LAWIP: CategoryContent = {
  graduate: [
    [
      'Uit hoeveel boeken is het Nederlandse Burgerlijk Wetboek opgebouwd?',
      ['tien', 'zes', 'vier', 'acht'],
      0,
      'Het BW loopt van Boek 1 (personen- en familierecht) tot Boek 10 (internationaal privaatrecht), met de Boeken 7 en 7A voor specifieke overeenkomsten. Het verving in fasen, van 1970 tot 1992, het oude wetboek uit 1838.',
    ],
    [
      'Wat is de beste omschrijving van de Hoge Raad der Nederlanden?',
      [
        'De hoogste rechter in civiele, strafrechtelijke en fiscale zaken, die toetst op rechtsvragen',
        'Het grondwettelijk hof dat door de Staten-Generaal aangenomen wetten ongrondwettig kan verklaren',
        'De hoogste bestuursrechter voor geschillen met de overheid',
        'Het gerecht dat ministers berecht voor ambtsmisdrijven',
      ],
      0,
      'De Hoge Raad beoordeelt geen feiten opnieuw; het is een cassatierechter die toetst of het recht juist is toegepast. In Nederland toetst de rechter wetten niet aan de Grondwet - artikel 120 van de Grondwet verbiedt dit uitdrukkelijk.',
    ],
    [
      'Wanneer wordt een merk vatbaar voor verval wegens "verwording tot soortnaam"?',
      [
        'Wanneer het door eigen nalatigheid van de merkhouder de gewone benaming van het product wordt in het algemeen taalgebruik',
        'Wanneer het door een licentienemer wordt gebruikt zonder schriftelijke licentieovereenkomst',
        'Wanneer het is geregistreerd in een klasse die niet overeenkomt met het feitelijke gebruik',
        'Wanneer het niet binnen vijf jaar na de oorspronkelijke aanvraagdatum wordt vernieuwd in het betreffende nationale merkenregister',
      ],
      0,
      '"Aspirine" en "escalator" verloren in de VS beide op deze manier hun merkbescherming. Houders verweren zich hiertegen door generiek gebruik te bestrijden en het merk altijd te combineren met de soortnaam van het product, zoals "Velcro-klittenband".',
    ],
    [
      'Wat mag een aangesloten land onder de Berner Conventie niet als voorwaarde stellen voor auteursrechtelijke bescherming?',
      [
        'Enige formaliteit, zoals registratie of een copyrightvermelding',
        'Publicatie in het land van herkomst',
        'Vertaling naar de taal van het land dat bescherming claimt',
        'Betaling van een aanvraagvergoeding aan een nationaal auteursrechtenbureau',
      ],
      0,
      'Het "geen formaliteiten"-beginsel van Berne (artikel 5(2)) is de reden dat auteursrecht bijna overal automatisch ontstaat bij het creëren van het werk. De VS trad pas in 1989 tot Berne toe en moest daarvoor de verplichte copyrightvermelding afschaffen.',
    ],
    [
      'Wat is de standaard minimumtermijn voor auteursrecht onder de Berner Conventie?',
      [
        'Het leven van de auteur plus 50 jaar',
        'Het leven van de auteur plus 70 jaar',
        '50 jaar na eerste publicatie, ongeacht het auteurschap',
        '25 jaar na het ontstaan van het werk',
      ],
      0,
      'Berne stelt de ondergrens op leven-plus-50; de EU verhoogde haar eigen termijn in 1993 naar leven-plus-70, en de VS volgde dat in 1998 met de Sonny Bono Act. Veel landen houden nog altijd het Berne-minimum aan.',
    ],
    [
      'Wat voor recht verleent het Europees Octrooibureau?',
      [
        'Een bundel nationale octrooien in de aangewezen staten, geen enkel EU-breed octrooi',
        'Een enkel octrooi dat in elke EU-lidstaat op identieke wijze afdwingbaar is',
        'Een octrooi dat alleen geldt in Duitsland, Frankrijk en het VK, zonder mogelijkheid tot uitbreiding naar enige andere verdragsstaat',
        'Een voorlopig recht dat door elk land afzonderlijk door het eigen octrooibureau moet worden bevestigd',
      ],
      0,
      'Een "Europees octrooi" dat door het EOB onder het Europees Octrooiverdrag wordt verleend, is in feite een bundel: het moet in elk aangewezen land worden gevalideerd en kan daar afzonderlijk worden herroepen of gelicentieerd. Het eenheidsoctrooi, dat pas echt één enkel recht creëert, is pas in 2023 operationeel geworden.',
    ],
    [
      'Om patenteerbaar te zijn in de meeste rechtssystemen moet een uitvinding nieuw, niet-voor-de-hand-liggend (inventief) zijn en wat nog meer?',
      ['Vatbaar voor toepassing op het gebied van de nijverheid', 'Aangevraagd door een rechtspersoon', 'Een jaar geheim gehouden voor de aanvraag', 'Herleid tot een fysiek prototype'],
      0,
      'Nieuwheid, inventiviteit en industriële toepasbaarheid zijn de drie pijlers van het EOV (artikel 52). "Reduction to practice" is een specifiek Amerikaans historisch begrip uit het oude first-to-invent-systeem, geen algemene vereiste.',
    ],
    [
      'Waar staat het Nederlandse woord "auteursrecht" het meest direct voor?',
      ['Het recht van de auteur', 'Uitgeeflicentie', 'Bedrijfsgeheim', 'Modelrecht'],
      0,
      'Continentaal-Europese systemen, waaronder het Nederlandse, benaderen auteursrecht als een "recht van de auteur", gericht op de persoonlijke en morele band van de maker met het werk, in tegenstelling tot de Angelsaksische "copyright"-traditie, die historisch draaide om het economische recht om te kopiëren.',
    ],
    [
      'Wat maakt het Benelux-merken- en modellensysteem ongewoon?',
      [
        'Het registreert één merk dat geldig is in België, Nederland en Luxemburg als één gebied',
        'Het vereist afzonderlijke aanvragen in elk van de drie landen',
        'Het dekt alleen merken, geen modellen, omdat modelbescherming uitsluitend door het nationale bureau van elk land wordt afgehandeld',
        'Het verleent bescherming automatisch, zonder enige registratie',
      ],
      0,
      'Het Benelux-Bureau voor de Intellectuele Eigendom (BOIP) bestond al vóór het EU-merkensysteem en voert nog steeds een echt uniforme registratie voor de drie landen, een van de oudste supranationale IE-regimes in de wereld.',
    ],
    [
      'Hoe functioneert WIPO, de Wereldorganisatie voor de Intellectuele Eigendom?',
      [
        'Als gespecialiseerd agentschap van de Verenigde Naties dat IE-verdragen beheert',
        'Als onderdeel van de Wereldhandelsorganisatie, specifiek belast met het handhaven van handelsgerelateerde sancties',
        'Als EU-instelling met gezag alleen over de lidstaten',
        'Als particuliere branchevereniging zonder rol bij het opstellen van verdragen',
      ],
      0,
      'WIPO werd in 1974 een gespecialiseerd VN-agentschap en beheert verdragen zoals het Verdrag van Parijs, de Berner Conventie, het PCT en het Protocol van Madrid, maar heeft geen eigen handhavingsbevoegdheid - die ligt bij de nationale rechter en, voor handelsgerelateerde geschillen, bij de WTO.',
    ],
    [
      'Wat maakt het "prioriteitsrecht" van het Verdrag van Parijs mogelijk voor een aanvrager die in een aangesloten land een octrooi of merk aanvraagt?',
      [
        'Binnen een gestelde termijn in andere aangesloten landen aanvragen met behoud van de oorspronkelijke aanvraagdatum',
        'Automatisch bescherming krijgen in elk ander aangesloten land',
        'De beschermingstermijn in het land van eerste aanvraag verlengen met een periode gelijk aan de prioriteitstermijn zelf',
        'De aanvraag zonder formele overdracht overdragen aan een andere aanvrager',
      ],
      0,
      'De prioriteitstermijn is 12 maanden voor octrooien en 6 maanden voor merken en modellen. Deze bestaat juist omdat gelijktijdig wereldwijd aanvragen nooit realistisch was, zodat het Verdrag een latere buitenlandse aanvraag laat gelden als was die op de eerste aanvraagdatum ingediend.',
    ],
    [
      'De economische rechten in een auteursrechtelijk beschermd werk (bijv. reproductie, distributie) verschillen van morele rechten vooral omdat morele rechten wat doen?',
      [
        'De persoonlijke band van de auteur met het werk beschermen (naamsvermelding, integriteit) en doorgaans niet overdraagbaar zijn',
        'Vrij gekocht en verkocht kunnen worden als elk ander eigendom',
        'Alleen bestaan in common-law-rechtsstelsels, waar ze voor het eerst werden vastgelegd in wetten uit het begin van de twintigste eeuw over kunstwerken en literaire werken',
        'Onmiddellijk vervallen bij de eerste publicatie van het werk',
      ],
      0,
      'Morele rechten - het recht op naamsvermelding en het recht tegen aantasting of verminking van het werk - worden in de meeste civielrechtelijke stelsels, waaronder het Nederlandse, als onvervreemdbaar behandeld, ook nadat de economische rechten zijn overgedragen of verkocht.',
    ],
    [
      'Wat doet een aanvullend beschermingscertificaat (ABC) onder EU-recht voor een geoctrooieerd geneesmiddel of gewasbeschermingsmiddel?',
      [
        'Het verlengt de exclusiviteit na de twintigjarige octrooitermijn, met maximaal vijf jaar, ter compensatie van tijd verloren aan de regelgevende marktvergunningsprocedure',
        'Het verleent een geheel nieuwe octrooitermijn van twintig jaar die pas ingaat zodra de termijn van het oorspronkelijke octrooi volledig is verstreken',
        'Het zet het octrooi om in een merkregistratie voor hetzelfde product voor onbepaalde tijd',
        'Het verdubbelt automatisch het licentietarief dat een generieke fabrikant voor de rest van de octrooitermijn moet betalen',
      ],
      0,
      'ABC\'s bestaan omdat geneesmiddelen en landbouwchemicaliën vaak jaren van regelgevend onderzoek nodig hebben voordat ze op de markt mogen komen, waardoor stilletjes wordt ingeleverd op de effectieve jaren octrooibescherming die er daadwerkelijk zijn om het product te verkopen. EU-Verordening 469/2009 (geneesmiddelen) en 1610/96 (gewasbeschermingsmiddelen) herstellen tot vijf extra jaren, berekend uit het verschil tussen aanvraag en eerste marktvergunning, verminderd met vijf jaar. De regeling werd in de jaren negentig deels ingevoerd om aan te sluiten bij de Amerikaanse termijnherstelregels onder de Hatch-Waxman Act, zodat in de EU gevestigde innovators niet in het nadeel waren tegenover Amerikaanse concurrenten. Bovenop het reguliere ABC is een extra verlenging van zes maanden voor pediatrisch gebruik mogelijk als de houder onderzoek verricht dat vereist is onder de EU-verordening inzake geneesmiddelen voor kinderen.',
    ],
    [
      'Wat bereikt een aanvraag onder het Patent Cooperation Treaty (PCT) precies?',
      [
        'Het regelt één internationale aanvraag die de prioriteitsdatum behoudt en toetreding tot de nationale of regionale fase uitstelt, zonder zelf een octrooi te verlenen',
        'Het verleent één uniform octrooi dat automatisch op identieke wijze afdwingbaar is in elk van de bij het PCT aangesloten staten',
        'Het leidt automatisch tot verlening van een Europees octrooi zonder enig onderzoek door het EOB',
        'Het levert een octrooitermijnverlenging op die identiek is in effect aan een aanvullend beschermingscertificaat',
      ],
      0,
      'Het PCT, sinds de inwerkingtreding in 1978 beheerd door WIPO, laat een aanvrager één internationale aanvraag indienen en een internationaal onderzoeksrapport en voorlopig advies ontvangen, maar de daadwerkelijke beslissing over verlening blijft volledig bij elk nationaal of regionaal bureau, zoals het EOB, zodra de aanvrager de "nationale fase" ingaat, doorgaans zo\'n 30 of 31 maanden na de prioriteitsdatum. Dit levert waardevolle tijd op en centraliseert de vroege kosten, terwijl de veel duurdere beslissing over welke specifieke landen het waard zijn om afzonderlijk voor te betalen wordt uitgesteld. Het heeft geen enkele relatie met merken of modellen, die in plaats daarvan via het afzonderlijke Protocol van Madrid en het Haags Systeem lopen. WIPO meldt dat het PCT inmiddels ruim 250.000 internationale aanvragen per jaar ontvangt, wat het de drukste enkele toegangspoort in wereldwijde octrooiaanvragen maakt.',
    ],
    [
      'Onder de EU-richtlijn bedrijfsgeheimen (2016/943) komt informatie alleen in aanmerking voor bescherming als bedrijfsgeheim wanneer aan welke combinatie van voorwaarden is voldaan?',
      [
        'Geheimhouding, commerciële waarde die aan die geheimhouding wordt ontleend, en redelijke maatregelen van de houder om ze geheim te houden',
        'De informatie is formeel geregistreerd bij een nationaal of EU-bureau voor intellectuele eigendom',
        'De informatie is alleen bekendgemaakt onder een formeel ondertekende, notarieel bekrachtigde geheimhoudings- en vertrouwelijkheidsovereenkomst die specifiek tussen de twee betrokken commerciële partijen is onderhandeld',
        'De informatie heeft ononderbroken minstens vijf volledige jaren geheim bestaan voordat een vordering wordt ingesteld',
      ],
      0,
      'In tegenstelling tot octrooien of merken is bescherming van bedrijfsgeheimen niet geregistreerd en wordt zij louter bepaald door drie cumulatieve voorwaarden in artikel 2 van de richtlijn, die nauw aansluiten bij artikel 39 van de TRIPS-overeenkomst: de informatie moet geheim zijn, ze moet commerciële waarde hebben precies omdat ze geheim is, en de houder moet redelijke maatregelen hebben genomen om dat zo te houden. De richtlijn van 2016 harmoniseerde wat voorheen een lappendeken was van nationale leerstukken van oneerlijke concurrentie en contractenrecht in de EU-lidstaten, en gaf houders van bedrijfsgeheimen voor het eerst een echt uniform civielrechtelijk rechtsmiddel tegen onrechtmatig gebruik. De richtlijn werd ook opgesteld met oog voor het parallelle Amerikaanse kader, de Defend Trade Secrets Act, aangenomen in hetzelfde jaar, waardoor twee rechtstradities die geheimhouding meer dan een eeuw heel verschillend hadden benaderd naar elkaar toe groeiden.',
    ],
  ],
  phd: [
    [
      'Welke factoren weegt de "verwarringsgevaar"-toets in het EU-merkenrecht onder de EUTMV samen?',
      [
        'De gelijkenis van de tekens, de gelijkenis van de waren/diensten, en het onderscheidend vermogen van het oudere merk, globaal beoordeeld',
        'Alleen of de twee merken visueel identiek zijn',
        'Alleen de reputatie van het later aangevraagde merk, ongeacht enige gelijkenis tussen de waren of diensten onder elk teken of het onderscheidend vermogen van het oudere merk zelf',
        'Alleen of de waren in dezelfde fysieke winkels worden verkocht',
      ],
      0,
      'De "globale beoordeling" van het HvJEU, uit zaken als Sabel/Puma en Canon/MGM, behandelt deze factoren als onderling afhankelijk - een zeer onderscheidend ouder merk kan verwarring veroorzaken zelfs bij een tamelijk ongelijkend later teken, omdat onderscheidend vermogen en gelijkenis tegen elkaar afgewogen worden.',
    ],
    [
      'Waar gaat artikel 17 van de EU-richtlijn auteursrecht uit 2019 (voorheen het omstreden "artikel 13") primair over?',
      [
        'De aansprakelijkheid van online platforms voor het delen van content voor auteursrechtinbreukmakende uploads van gebruikers',
        'De harmonisatie van de auteursrechttermijn tussen lidstaten, een onderwerp dat juist wordt geregeld in de afzonderlijke Termijnrichtlijn van 1993',
        'Het recht van academische auteurs om het auteursrecht op wetenschappelijke artikelen te behouden',
        'De omvang van de uitzondering voor privékopiëren van fysieke media',
      ],
      0,
      'Artikel 17 maakt platforms zoals YouTube direct aansprakelijk voor niet-toegestane uploads, tenzij zij licenties verkrijgen of "beste inspanningen" leveren om de beschikbaarheid van gemelde werken te voorkomen - een verschuiving ten opzichte van het eerdere "veilige haven"-model voor hostingaansprakelijkheid onder de Richtlijn elektronische handel.',
    ],
    [
      'Waarover heeft het Uniform Octrooigerecht (UPC), dat in 2023 van start ging, rechtsmacht?',
      [
        'Inbreuk en geldigheid van Europese octrooien en eenheidsoctrooien in de deelnemende lidstaten',
        'Alleen eenheidsoctrooien, niet klassieke Europese octrooien',
        'Alleen octrooigeschillen over geneesmiddelen',
        'Merkgeschillen binnen de EU, een aangelegenheid die juist uitsluitend is voorbehouden aan het EUIPO en nationale merkenrechters',
      ],
      0,
      'Het UPC geeft één rechtssysteem rechtsmacht over zowel het nieuwe eenheidsoctrooi als, gedurende een overgangsperiode, klassieke Europese octrooien (behalve bij opt-out), waardoor het niet langer nodig is inbreuk in elk land afzonderlijk te bepleiten - de grootste structurele verandering in de Europese octrooiprocesvoering in decennia.',
    ],
    [
      'In Windsurfing Chiemsee/Huber (1999) behandelde het HvJEU de vraag of een geografische naam als merk kan functioneren, en oordeelde het wat?',
      [
        'Een geografische naam kan worden geregistreerd als zij door gebruik onderscheidend vermogen heeft verkregen, ook al zijn zuiver beschrijvende geografische termen normaal uitgesloten',
        'Geografische namen kunnen onder geen enkele omstandigheid als merk worden geregistreerd',
        'Geografische namen zijn automatisch registreerbaar wanneer de betreffende waren niet daadwerkelijk op die plaats worden geproduceerd',
        'Geografische aanduidingen beschermd onder afzonderlijke EU-kwaliteitsregelingen voor landbouwproducten en gewone merken worden als volledig identieke juridische begrippen behandeld die dezelfde registratieroute vereisen',
      ],
      0,
      'De zaak betrof "Chiemsee", de naam van een Beiers meer, gebruikt voor de verkoop van sportkleding, en het HvJEU oordeelde dat de Merkenrichtlijn beschrijvende geografische termen van registratie uitsluit, tenzij het merk onderscheidend vermogen, of ingeburgerdheid, door gebruik heeft verkregen, wat betekent dat het publiek die naam nu associeert met een specifieke handelsoorsprong in plaats van louter de plaats zelf. De regel voorkomt dat één handelaar een plaatsnaam monopoliseert die concurrenten legitiem nodig hebben om te beschrijven waar hun eigen waren daadwerkelijk vandaan komen, terwijl een merk dat aantoonbaar erkenning heeft verworven door daadwerkelijk marktgebruik toch wordt beloond. Dezelfde logica van verkregen onderscheidend vermogen verklaart waarom een simpele geografische term zelden op eigen kracht wordt geregistreerd, maar een specifiek, gestileerd gebruik dat decennialang is opgebouwd soms wel. Het blijft een van de fundamentele arresten van het HvJEU over absolute weigeringsgronden onder wat nu artikel 4 van de EU-Merkenrichtlijn is.',
    ],
    [
      'In Brüstle/Greenpeace (2011) legde het HvJEU de uitsluiting van octrooien op toepassingen van menselijke embryo\'s uit de Biotechnologierichtlijn op welke manier uit?',
      [
        'De uitsluiting geldt voor elke menselijke eicel vanaf het moment van bevruchting die in staat is menselijke ontwikkeling in gang te zetten, inclusief het gebruik van stamcellen verkregen door vernietiging van een embryo',
        'De uitsluiting geldt alleen voor embryo\'s ouder dan veertien dagen',
        'De uitsluiting geldt alleen voor gekloonde embryo\'s ontstaan door celkerntransplantatie, niet voor natuurlijk bevruchte embryo\'s',
        'De richtlijn beperkt octrooien op biotechnologische uitvindingen met embryonaal materiaal op geen enkele manier',
      ],
      0,
      'De Duitse neurobioloog Oliver Brüstle hield een octrooi op neurale precursorcellen afgeleid van menselijke embryonale stamcellen, en Greenpeace vocht dit aan onder de uitsluiting in Richtlijn 98/44/EG van "toepassingen van menselijke embryo\'s voor industriële of commerciële doeleinden"; het HvJEU gaf die uitdrukking een autonome, ruime, EU-brede betekenis in plaats van deze over te laten aan uiteenlopende nationale moraliteitsnormen. De uitspraak sloot in feite EU-octrooien uit op uitvindingen die de voorafgaande vernietiging van een menselijk embryo vereisen, ook al was het geoctrooieerde zelf de resulterende cellijn, niet het embryo. Dit werd later verfijnd in International Stem Cell Corporation/Comptroller General (2014), waarin werd geoordeeld dat parthenoten - onbevruchte eicellen die zijn gestimuleerd om te delen maar niet in staat zijn zich tot een mens te ontwikkelen - buiten de uitsluiting vallen. Deze reeks zaken toont octrooigemachtigden die soms genoodzaakt zijn oprecht omstreden bio-ethische grenzen te beoordelen in plaats van louter technische.',
    ],
    [
      'Wat betekent het leerstuk van "uitputting van rechten" in het EU-merken- en auteursrecht?',
      [
        'Zodra goederen met toestemming van de rechthebbende voor het eerst in de EER op de markt zijn gebracht, kan de rechthebbende verdere doorverkoop binnen de EER niet tegenhouden',
        'Een merkrecht vervalt permanent na tien jaar',
        'Auteursrecht kan niet worden uitgeput, alleen merken, omdat auteursrecht in de meeste civielrechtelijke stelsels wordt behandeld als een persoonlijk recht dat permanent aan de auteur verbonden blijft, ongeacht enige verkoop',
        'Een rechthebbende kan parallelimport van waar dan ook tegenhouden zodra de goederen de fabriek hebben verlaten',
      ],
      0,
      'Dit is de juridische basis voor de interne markt van de EU voor originele goederen: zaken als Silhouette/Hartlauer bevestigden dat de EU regionale (niet internationale) uitputting toepast, zodat een rechthebbende parallelimport van buiten de EER WEL kan tegenhouden, ook na een met toestemming verrichte eerste verkoop binnen de EER.',
    ],
    [
      'In Google France/Louis Vuitton (2010) oordeelde het HvJEU dat een zoekmachine die het merk van een concurrent als betaald zoekwoord verkoopt wat doet?',
      [
        'Maakt zelf geen inbreuk op het merk, maar de adverteerder die het zoekwoord koopt kan inbreuk maken als de resulterende advertentie de herkomst- of reclamefunctie van het merk schaadt',
        'Maakt altijd inbreuk op het merk, ongeacht hoe duidelijk de resulterende gesponsorde advertentie de eigen goederen van de adverteerder onderscheidt van die van de merkhouder, en ongeacht enige daadwerkelijke verwarring',
        'Maakt nooit inbreuk, onder welke omstandigheden dan ook, omdat het kopen van een zoekwoord geen "gebruik" is door wie dan ook in het economisch verkeer',
        'Maakt alleen inbreuk als de zoekmachine zelf, in plaats van de adverteerder, rechtstreeks profijt trekt van die specifieke zoekwoordverkoop',
      ],
      0,
      'Het Hof verdeelde de aansprakelijkheid nauwkeurig: Googles eigen handelen bij het verkopen van zoekwoorden was geen "gebruik in het economisch verkeer" van het merk op een manier die zelf inbreuk vormde, maar als de resulterende gesponsorde advertentie zo onduidelijk was dat een redelijk geïnformeerde internetgebruiker niet kon zien of de geadverteerde goederen van de merkhouder of een concurrent kwamen, schaadde dat de essentiële herkomstfunctie van het merk en kon de adverteerder aansprakelijk zijn. Dit trok een scherpe grens tussen neutrale technische tussenkomst en werkelijk verwarrend gebruik, en het model werd later in Interflora/Marks & Spencer (2011) uitgebreid tot de "investeringsfunctie" van een bekend merk naast de herkomstfunctie. Zoekwoordreclame blijft een van de meest bevochten hoeken van het EU-merkenrecht, juist omdat het beoordelen van de "duidelijkheid" van een advertentie zo feitelijk specifiek is. De onderliggende klacht van Louis Vuitton betrof concurrenten die de eigen merknaam kochten om aan nepgoederen verwante producten te adverteren, wat het geschil helemaal tot bij het HvJEU bracht.',
    ],
    [
      'Waarom was TRIPS (de WTO-overeenkomst inzake de handelsaspecten van de intellectuele eigendom) van belang?',
      [
        'Het verplichtte WTO-leden tot minimale IE-normen die via de WTO-geschillenbeslechting afdwingbaar zijn',
        'Het schafte octrooien op geneesmiddelen in ontwikkelingslanden af',
        'Het verving de Berner en de Parijse Conventie volledig',
        'Het creëerde WIPO als nieuwe internationale organisatie, terwijl WIPO in werkelijkheid al twee decennia eerder bestond als een gespecialiseerd VN-agentschap',
      ],
      0,
      'TRIPS (1994) was de eerste IE-overeenkomst met een bindend handhavingsmechanisme dat kruislingse retaliatie mogelijk maakt - een WTO-lid dat in overtreding wordt bevonden kan handelssancties krijgen in geheel andere sectoren, wat veel sterker is dan wat de WIPO-verdragen alleen boden.',
    ],
    [
      'L\'Oréal/Bellure (2009) breidde de merkbescherming voor merken met reputatie uit tot wat, verder dan de traditionele verwarringstoets?',
      [
        'Het onrechtmatig voordeel trekken uit de reputatie van het merk door meeliften, ook zonder verwarringsgevaar en zonder schade aan het onderscheidend vermogen van het merk',
        'Alleen gevallen waarin het nagemaakte product een verpakkingsontwerp gebruikte dat identiek was, in plaats van slechts vergelijkbaar, met het origineel',
        'Alleen nepgoederen die een merk dragen dat identiek is in plaats van slechts vergelijkbaar',
        'Alleen situaties waarin bewezen wordt dat de totale omzet van de gedaagde in die specifieke productmarkt, over de betreffende inbreukperiode, de vergelijkbare omzet van de merkhouder zelf overtrof',
      ],
      0,
      'Bellure verkocht "geursimulatie"-parfums met vergelijkingslijsten die openlijk L\'Oréals bekende geuren bij naam noemden, zonder iemand te verwarren over de herkomst, maar het HvJEU oordeelde dat bescherming tegen het "trekken van onrechtmatig voordeel" uit het imago van een bekend merk geen verwarring of zelfs schade vereist - simpelweg meeliften om de eigen verkoop van de imitator te vergroten is voldoende. Dit was omstreden omdat het de investering en imagowaarde van een bekend merk in feite als een bijna zelfstandig eigendomsrecht beschermt, ver voorbij de traditionele rechtvaardiging van het voorkomen van misleiding van consumenten. Hetzelfde arrest oordeelde ook dat regels voor vergelijkende reclame niet gebruikt kunnen worden om anderszins inbreukmakend meeliften te legitimeren, waarmee een verdediging werd afgesloten die Bellure daarnaast had geprobeerd. Het blijft een veelaangehaald voorbeeld van hoe het EU-merkenrecht opschuift naar bescherming van het merkimago als zodanig, een verschuiving die sommige wetenschappers nog steeds te ver vinden gaan ten opzichte van de traditionele herkomstfunctie van het merk.',
    ],
    [
      'Waarover ging het arrest van het HvJEU in Levola Hengelo/Smilde Foods (2018)?',
      [
        'Of de smaak van een voedingsproduct auteursrechtelijk beschermd kan worden',
        'Of het recept van een Nederlandse kaasspread als literair werk beschermd kan worden',
        'Of het merk "Heks\'nkaas" zelf beschermd kan worden',
        'Of het verpakkingsontwerp van een smeerkaas beschermd kan worden',
      ],
      0,
      'Het HvJEU oordeelde dat smaak niet auteursrechtelijk beschermd kan worden omdat deze niet met voldoende precisie en objectiviteit kan worden vastgesteld om aan het "werk"-vereiste onder het EU-auteursrecht te voldoen - een Nederlandse zaak (over de kruidenkaasspread Heks\'nkaas) die een echt open leerstellige vraag beslechtte.',
    ],
    [
      'Wat maakt het Protocol van Madrid mogelijk voor een merkhouder?',
      [
        'Eén internationale aanvraag indienen die meerdere aangesloten landen aanwijst via één door WIPO beheerde procedure',
        'Een enkel merk verkrijgen dat automatisch wereldwijd geldig is',
        'Nationaal onderzoek in elk aangewezen land volledig overslaan',
        'Een merk registreren dat generiek is in het land van herkomst, iets wat geen internationaal of nationaal merkensysteem toestaat, welke aanvraagroute ook wordt gevolgd',
      ],
      0,
      'Madrid centraliseert aanvraag en vernieuwing administratief, maar het bureau van elk aangewezen land onderzoekt het merk nog steeds naar zijn eigen materiële recht en kan het weigeren - het is een aanvraaggemak, geen enkel eenheidsrecht, wat vaak tot verwarring leidt.',
    ],
    [
      'De leer van "first sale" in het Amerikaanse auteursrecht en "uitputting" in het EU-recht beperken allebei welk recht?',
      [
        'Het distributierecht, zodra een specifiek exemplaar rechtmatig is verkocht',
        'Het reproductierecht voor digitale exemplaren',
        'Het morele recht op naamsvermelding, dat in de meeste rechtsstelsels door geen enkele verkoop van een fysiek of digitaal exemplaar kan worden uitgeput',
        'Het recht om het werk in het openbaar uit te voeren',
      ],
      0,
      'Beide leerstukken laten de eigenaar van een rechtmatig verkregen fysiek exemplaar dit doorverkopen of uitlenen zonder verdere toestemming van de rechthebbende, omdat het distributierecht wordt beschouwd als uitgeput door de eerste toegestane verkoop van dat specifieke exemplaar - hoewel EU-rechtspraak (zoals UsedSoft) op omstreden wijze een versie hiervan ook toepaste op sommige gedownloade software.',
    ],
    [
      'In Stichting Brein/Ziggo en XS4ALL (2017) oordeelde het HvJEU dat het exploiteren van een online indexeringsplatform als The Pirate Bay wat inhoudt?',
      [
        'Een "mededeling aan het publiek" onder de InfoSoc-richtlijn, waarmee de exploitanten van het platform zelf aansprakelijk zijn, niet alleen de individuele uploaders',
        'Louter passief hosten dat beschermd wordt door de veilige haven van de Richtlijn elektronische handel, zonder enige aansprakelijkheid',
        'Rechtmatig handelen, omdat het indexeringsplatform zelf geen van de daadwerkelijke auteursrechtelijk beschermde bestanden opslaat, alleen hyperlinks, magnet-links en bijbehorende beschrijvende metadata',
        'Merkinbreuk in plaats van een auteursrechtelijke aangelegenheid, omdat het indexeren van content in essentie een merkfunctie is',
      ],
      0,
      'Deze Nederlandse verwijzingszaak, aangespannen door anti-piraterijstichting Brein tegen twee Nederlandse internetproviders die zij tot blokkering van de site wilde dwingen, oordeelde dat Pirate Bay\'s exploitanten door het indexeren en categoriseren van torrentbestanden, met volledige kennis dat de meeste naar inbreukmakende content verwezen, een "onmisbare rol" speelden ver voorbij neutrale technische facilitering, waardoor ze zelf mededelers aan het publiek werden, ook al stonden de daadwerkelijke bestanden op de eigen computers van gebruikers via peer-to-peer-delen. Dat sloot een gat waardoor indexeringssites konden beweren dat ze slechts naar materiaal linkten in plaats van zelf iets inbreukmakends te hosten. De uitspraak maakte direct het blokkeringsbevel tegen Pirate Bay mogelijk waartegen Ziggo en XS4ALL zich jarenlang hadden verzet. Hij past in een leerstellige lijn met GS Media en Renckhoff, allemaal deel van de geleidelijke uitbreiding door het HvJEU van "mededeling aan het publiek" tot internettussenpersonen die eerdere rechtspraak in een grijs gebied had gelaten.',
    ],
    [
      'Wat staat de EU-"SPC-fabricagevrijstelling" uit 2019 (Verordening 2019/933) toe, als uitzondering op de exclusiviteit van het aanvullend beschermingscertificaat?',
      [
        'In de EU gevestigde fabrikanten van generieke en biosimilaire producten mogen het beschermde product tijdens de ABC-termijn produceren, uitsluitend voor export naar niet-EU-markten of voor voorraadopbouw binnen de EU vóór het verstrijken van het certificaat',
        'Elke fabrikant wereldwijd mag het ABC-beschermde product vrij binnen de EU verkopen tijdens de looptijd van het certificaat',
        'ABC-houders moeten hun product op FRAND-achtige voorwaarden licentiëren aan minstens één generieke of biosimilaire concurrent zodra het certificaat door het bevoegde nationale octrooibureau formeel wordt verleend',
        'De ABC-termijn wordt met twee jaar verkort voor elk vrijstellingsverzoek dat een aanvrager met succes indient',
      ],
      0,
      'Voor deze wijziging bevonden in de EU gevestigde generieke fabrikanten zich in een echt concurrentienadeel tegenover rivalen in landen zonder gelijkwaardig termijnverlengingsregime, omdat zij niet eens voor export mochten produceren terwijl het ABC nog liep, waardoor ze jaren aan opstarttijd verloren ten opzichte van concurrenten in het buitenland. De vrijstelling laat hen, onder strikte meldings- en etiketteringsvoorwaarden, produceren puur voor niet-EU-exportmarkten of voor voorraadopbouw, zodat een generieke versie op precies de dag dat het ABC verstrijkt in de EU kan worden gelanceerd. Het was een bewust industriebeleidscompromis tussen innoverende farmaceutische bedrijven en de lobby van generieke en biosimilaire fabrikanten. De vrijstelling geldt alleen voor ABC\'s aangevraagd op of na 1 juli 2019, met een gefaseerde overgang voor eerdere certificaten, zodat het praktische effect op de markt jaren nodig had om zich volledig te manifesteren.',
    ],
    [
      'Waartegen biedt een niet-ingeschreven Gemeenschapsmodel onder het EU-modellenrecht de houder specifiek bescherming?',
      [
        'Alleen tegen opzettelijk kopiëren, niet tegen onafhankelijke totstandkoming van een gelijkend ontwerp',
        'Tegen elk identiek of gelijkend ontwerp, ongeacht hoe het is ontstaan',
        'Tegen niets - niet-ingeschreven modellen krijgen geen bescherming op EU-niveau',
        'Alleen tegen modellen die zijn ingeschreven in dezelfde lidstaat als de houder, een aanpak die het EU-regime helemaal niet volgt',
      ],
      0,
      'Dit is het belangrijkste praktische verschil met een ingeschreven Gemeenschapsmodel, dat een echt monopolierecht is dat zelfs geldt tegen onafhankelijke ontwerpers: het niet-ingeschreven recht (dat slechts drie jaar duurt) vereist het bewijs dat de vermeende inbreukmaker het ontwerp daadwerkelijk heeft gekopieerd.',
    ],
  ],
  professor: [
    [
      'In Sabam/Netlog (2012) en Scarlet Extended/SABAM (2011) oordeelde het HvJEU dat het verplichten van een internetprovider tot het installeren van een algemeen filtersysteem tegen auteursrechtinbreuk in strijd zou zijn met wat?',
      [
        'Het verbod op het opleggen van een algemene toezichtsverplichting onder de Richtlijn elektronische handel, afgewogen tegen grondrechten',
        'De minimumtermijnvereiste van de Berner Conventie',
        'Het beginsel van nationale behandeling van het Verdrag van Parijs',
        'Het Verdrag van Rome inzake naburige rechten van uitvoerende kunstenaars, een instrument dat een geheel andere categorie naburige rechten regelt die niets met filterverplichtingen te maken heeft',
      ],
      0,
      'Het Hof oordeelde dat zulke filterverplichtingen artikel 15 van de Richtlijn elektronische handel (geen algemene toezichtsplicht) zouden schenden en de vrijheid van ondernemerschap van de provider en de rechten van gebruikers op gegevensbescherming en vrije meningsuiting onevenredig zouden belasten - een redenering die later werd gecompliceerd, maar niet omgekeerd, door artikel 17 van de auteursrechtrichtlijn uit 2019, dat het Hof afzonderlijk moest verenigen in Polen/Parlement en Raad (2022).',
    ],
    [
      'Waarin was het Benelux-Gerechtshof, opgericht in 1974, historisch van betekenis?',
      [
        'Een van de vroegste internationale gerechten met de bevoegdheid prejudiciële beslissingen te geven over gemeenschappelijke Benelux-wetgeving, waaronder uniform merken- en modellenrecht',
        'De hoogste beroepsinstantie voor alle Nederlandse strafzaken, een functie die in werkelijkheid altijd uitsluitend bij de Hoge Raad der Nederlanden heeft berust',
        'Het eerste gerecht dat de leer van rechtstreekse werking van het HvJEU toepaste',
        'Het gerecht dat het grensgeschil tussen Nederland en België over Baarle-Nassau beslechtte',
      ],
      0,
      'Het ging vooraf aan, en diende deels als model voor, het prejudiciële mechanisme dat later enorm werd opgeschaald door het HvJEU, en was decennialang de gezaghebbende uitlegger van de Uniforme Benelux-wet inzake merken en modellen, voordat unificatie op EU-niveau grotendeels zijn IE-rechtspraak verving.',
    ],
    [
      'Wat oordeelde Svensson/Retriever Sverige (2014) over hyperlinken naar een werk dat al vrij online beschikbaar is met toestemming van de rechthebbende?',
      [
        'Dit vereist geen afzonderlijke toestemming van de rechthebbende, omdat er geen mededeling wordt gedaan aan een "nieuw publiek" naast degenen die de oorspronkelijke plaatsing al bereikte',
        'Het maakt altijd inbreuk op het auteursrecht, ongeacht de beschikbaarheid van de doelinhoud of hoe de oorspronkelijke rechthebbende deze eerst publiceerde',
        'Het maakt alleen inbreuk wanneer de link gebruikmaakt van framing-technieken in plaats van een gewone klikbare hyperlink',
        'Het vereist alleen afzonderlijke toestemming zodra de website die linkt zelf een abonnementskosten begint te vragen aan bezoekers voor toegang tot haar eigen pagina\'s',
      ],
      0,
      'Zweedse journalisten daagden een nieuwsaggregatiesite voor de rechter voor het linken naar hun vrij en rechtmatig toegankelijke artikelen, en het HvJEU oordeelde dat, omdat de rechthebbende de werken al toegankelijk had gemaakt voor alle internetgebruikers bij de eerste plaatsing, een verdere hyperlink geen "nieuw publiek" bereikt dat niet al onder die oorspronkelijke toestemming viel, zodat er geen nieuwe mededelingshandeling ontstaat die afzonderlijke toestemming vereist. Het Hof liet open, en beantwoordde later anders in GS Media en Renckhoff, wat gebeurt wanneer de doelinhoud achter een betaalmuur staat of zonder toestemming van de rechthebbende werd geplaatst. Het begrip "nieuw publiek" ontstond hier niet zelf; het werd overgenomen uit eerdere rechtspraak over satelliet- en kabeldoorgifte, SGAE/Rafael Hoteles, en hergebruikt voor de context van internethyperlinks. Dat hergebruik van één flexibele leerstellige toets over zeer verschillende technologieën is een terugkerend kenmerk van hoe de auteursrechtelijke rechtspraak van het HvJEU zich sinds de InfoSoc-richtlijn heeft ontwikkeld.',
    ],
    [
      'In het arrest Football Dataco/Yahoo! (2012) van het HvJEU oordeelde het Hof dat auteursrechtelijke bescherming van een databank onder de Databankrichtlijn wat specifiek vereist, en wat uitsluit?',
      [
        'Originele selectie of rangschikking die de vrije creatieve keuzes van de auteur weerspiegelt, met uitsluiting van aanzienlijke arbeid en vakkundigheid bij het verzamelen van de gegevens',
        'Alleen dat er aanzienlijke financiële investering is gedaan om de gegevens samen te stellen',
        'Dat de databank bij een nationaal IE-bureau is geregistreerd voordat een procedure wordt gestart',
        'Dat de gegevens zelf origineel zijn, ongeacht de rangschikking, een vereiste dat de Databankrichtlijn in werkelijkheid niet stelt aan auteursrechtelijke bescherming',
      ],
      0,
      'Dit ontkoppelde auteursrechtelijke bescherming van het afzonderlijke sui-generis databankrecht (dat wel investering in het verkrijgen, controleren en presenteren van gegevens beschermt): "zweet van het voorhoofd" alleen - hier, de vakkundigheid in het plannen van voetbalwedstrijden - kan geen auteursrecht vestigen, alleen echte creatieve selectie of rangschikking kan dat.',
    ],
    [
      'Op welk specifiek scenario ging de leer uit IHT Internationale Heiztechnik/Ideal-Standard (1994) over merkuitputting binnen concernherstructureringen in?',
      [
        'Of een merk dat aan een niet-verbonden entiteit in één lidstaat is overgedragen, nog kon worden ingezet om invoer van originele goederen met hetzelfde merk uit een andere lidstaat te blokkeren nadat de overdracht de economische band had doorgesneden',
        'Of een franchisenemer een merk mocht gebruiken na afloop van de franchiseovereenkomst',
        'Of een merk gelijktijdig door twee niet-verbonden bedrijven in verschillende EU-staten kon worden geregistreerd',
        'Of merkrechten het faillissement van de oorspronkelijke eigenaar overleven, een afzonderlijke insolventierechtelijke vraag die wordt beheerst door nationale faillissementswetten en de EU-Insolventieverordening, niet door de merkuitputtingsrechtspraak van het HvJEU die in deze verwijzing aan de orde was',
      ],
      0,
      'Het HvJEU oordeelde dat wanneer merkrechten in verschillende staten in handen zijn van entiteiten zonder voortdurende economische band, de verkrijger WEL invoer van de originele goederen van de andere partij onder dat merk kan blokkeren - vrijwillige versnippering van eigendom doorbreekt uitputting, in tegenstelling tot een enkele bedrijfsreorganisatie met behoud van eenheid van zeggenschap.',
    ],
    [
      'GS Media/Sanoma (2016) breidde de "nieuw publiek"-analyse voor hyperlinks uit tot content die zonder toestemming van de rechthebbende is geplaatst, en liet aansprakelijkheid vooral van wat afhangen?',
      [
        'Of de linker wist of had moeten weten dat de gelinkte content onrechtmatig was geplaatst, met een vermoeden van wetenschap wanneer de link wordt geplaatst met winstoogmerk',
        'Of de gelinkte content is gehost op een server die fysiek buiten de Europese Unie staat',
        'Of de link een verkorte URL gebruikt in plaats van het oorspronkelijke, onverkorte webadres',
        'Of de oorspronkelijke inbreukmaker die de onrechtmatige content het eerst plaatste, al is geïdentificeerd en elders met succes is aangeklaagd',
      ],
      0,
      'De Nederlandse roddelsite GeenStijl, via uitgever GS Media, linkte naar uitgelekte, ongepubliceerde Playboy-foto\'s die op een site van een derde stonden, zonder toestemming van Sanoma, en het HvJEU oordeelde dat dit een niet-toegestane mededeling aan een "nieuw publiek" kon vormen - maar liet aansprakelijkheid specifiek afhangen van de daadwerkelijke of geachte wetenschap van de linker over de onrechtmatige plaatsing, met een weerlegbaar vermoeden van die wetenschap wanneer het linken met winstoogmerk gebeurt. Dit beslechtte echte onzekerheid over of gewone internetgebruikers risico lopen op aansprakelijkheid door simpelweg te linken naar iets dat achteraf illegaal blijkt te zijn, waardoor te goeder trouw handelende niet-commerciële linkers werden beschermd terwijl winstgedreven aggregators aan een strengere norm werden onderworpen. GeenStijl had Sanoma specifiek getergd door telkens een nieuwe link te publiceren zodra een kopie werd verwijderd, een detail waar de conclusie van de advocaat-generaal nadrukkelijk naar verwees. De uitspraak wordt vaak samen met Svensson en Renckhoff gelezen als de driedelige kaart van het HvJEU van hoe verschillend het EU-auteursrecht linken, opnieuw linken na verwijdering, en volledig herhosten behandelt.',
    ],
    [
      'Artikel 6bis van de Berner Conventie, over morele rechten, werd door de Verenigde Staten historisch vooral weerstaan wegens spanning met welk kenmerk van de Amerikaanse auteursrechtpraktijk van vóór 1976?',
      [
        'De "work made for hire"-leer, waaronder de werkgever, niet de individuele maker, als auteur wordt aangemerkt',
        'Het ontbreken van een auteursrechtregistratiesysteem',
        'De kortere Amerikaanse auteursrechttermijn ten opzichte van Europa',
        'De Amerikaanse praktijk om auteursrecht alleen aan eigen burgers te verlenen, een beperking die in werkelijkheid nooit heeft bestaan in het Amerikaanse auteursrecht',
      ],
      0,
      'Work-for-hire wijst het oorspronkelijke auteurschap zelf toe aan de werkgever, wat ongemakkelijk staat tegenover een moreel recht dat is gebaseerd op een persoonlijke band tussen een individuele maker en het werk - deels waarom de VS, bij toetreding tot Berne in 1989, het standpunt innam dat het bestaande Amerikaanse recht (merkachtige remedies tegen oneerlijke concurrentie en smaad) al voldeed, in plaats van een algemene wet over morele rechten in te voeren.',
    ],
    [
      'De "essentiële functie"-leer van het HvJEU, ontwikkeld vanaf Hoffmann-La Roche/Centrafarm (1978), omschrijft de kernfunctie van een merk als wat?',
      [
        'Het waarborgen van de herkomstidentiteit van de gemerkte waren of diensten voor de consument',
        'Het maximaliseren van het economisch rendement voor de rechthebbende',
        'Het voorkomen dat enige derde ooit een gelijkend teken gebruikt',
        'Het aanduiden van de geografische oorsprong van de goederen, een functie die in plaats daarvan wordt vervuld door geografische aanduidingen, niet door het gewone merkenrecht',
      ],
      0,
      'Deze "herkomstfunctie"-redenering (een Nederlandse verwijzingszaak, tegen de Nederlandse geneesmiddelenherverpakker Centrafarm) is het leerstellige aangrijpingspunt dat het HvJEU nog altijd gebruikt om te bepalen hoe ver een merkhouder herverpakking, rebranding en parallelhandel mag beheersen - bescherming reikt alleen zo ver als nodig om die herkomstgarantie te bewaren, niet om de houder tegen alle concurrentie te beschermen.',
    ],
    [
      'Wat oordeelde Land Nordrhein-Westfalen/Renckhoff (2018) over een leerling die een vrij toegankelijke foto, eerder met toestemming van de auteur geplaatst, opnieuw uploadt naar een schoolwebsite?',
      [
        'Dit is een nieuwe mededeling aan het publiek die opnieuw toestemming vereist, omdat de foto op een andere, van de oorspronkelijke plaatsing onafhankelijke server werd geplaatst',
        'Er ontstaat helemaal geen nieuwe mededeling, omdat de foto al vrij en rechtmatig toegankelijk was gemaakt voor elke internetgebruiker, ruim voordat de leerling deze opnieuw uploadde',
        'Dit maakt alleen inbreuk op morele rechten, niet op de economische reproductie- of mededelingsrechten',
        'Dit is toegestaan onder de EU-citaatuitzondering, omdat de herupload een educatief doel diende',
      ],
      0,
      'In tegenstelling tot hyperlinken, dat alleen naar content wijst die nog op de oorspronkelijke host staat, haalt het daadwerkelijk kopiëren en opnieuw uploaden van een bestand naar een onafhankelijke server de blijvende zeggenschap van de rechthebbende over dat specifieke exemplaar volledig uit handen - als de oorspronkelijke plaatsing later wordt verwijderd, blijft de onafhankelijk geherupdate kopie desalniettemin bestaan, wat het Hof beschouwde als een materieel andere, extra handeling die eigen toestemming vereist. Dit trok een scherpe leerstellige grens tussen linken, doorgaans veilig zolang het doel rechtmatig beschikbaar blijft, en herhosten, dat doorgaans nieuwe toestemming vereist, gebaseerd op de verschillende mate van blijvende zeggenschap die de rechthebbende in elk scenario behoudt. Het onderliggende geschil betrof een Spaanse reisfoto die werd hergebruikt voor een aardrijkskundepresentatie van een leerling, nauwelijks het soort zaak dat men zou verwachten in de auteursrechtelijke rechtspraak van het HvJEU op zo\'n grote leerstellige schaal. De uitspraak kreeg kritiek van sommige auteursrechtwetenschappers die stelden dat zij de praktische realiteit onderschat dat de meeste heruploade content, eenmaal vrij openbaar, weinig resterende economische schade oplevert door een verdere, niet-commerciële kopie.',
    ],
    [
      'Wat beschermde de Nederlandse "geschriftenbescherming", een sui-generis regeling in het Nederlandse auteursrecht, vóór haar afschaffing in 2018?',
      [
        'Niet-originele geschriften (zoals dienstroosters of catalogi) die het "eigen, oorspronkelijke karakter" missen dat nodig is voor volledig auteursrecht',
        'Mondelinge folklore en ongeschreven tradities',
        'Specifiek broncode van computers',
        'Foto\'s zonder artistieke waarde, een categorie die in werkelijkheid nooit onder deze specifiek op geschriften gerichte sui-generis leer viel',
      ],
      0,
      'Deze uniek Nederlandse leer gaf een dunne bescherming (vooral tegen letterlijk overnemen) aan louter feitelijke of functionele teksten die de gewone drempel van oorspronkelijkheid niet haalden; zij werd door wetswijziging geschrapt nadat de rechtspraaklijn van het HvJEU in Football Dataco en Infopaq duidelijk maakte dat het EU-auteursrecht een echte oorspronkelijkheidsnorm vereiste, zonder ruimte voor een lichtere nationale regeling.',
    ],
    [
      'In Huawei/ZTE (2015) stelde het HvJEU een onderhandelingskader vast dat bepaalt wanneer het verzoek van een houder van een standaard-essentieel octrooi om een verbod wat doet?',
      [
        'Kan een misbruik van machtspositie onder artikel 102 VWEU opleveren, tenzij de SEO-houder eerst bepaalde te-goeder-trouw-licentiestappen doorloopt voordat hij een procedure start',
        'Is automatisch en in elk geval een misbruik van machtspositie, ongeacht het eerdere gedrag van beide partijen',
        'Kan nooit een misbruik van machtspositie onder artikel 102 VWEU opleveren, omdat octrooirechten als absoluut worden behandeld en volledig immuun zijn voor mededingingsrechtelijke toetsing onder vaste EU-rechtspraak',
        'Hangt uitsluitend af van de vraag of de gebruiker al een geheimhoudingsovereenkomst met de octrooihouder heeft ondertekend',
      ],
      0,
      'Huawei bezat octrooien die essentieel waren voor een telecomstandaard en had zich bij een standaardisatie-organisatie verplicht deze op FRAND-voorwaarden (fair, redelijk en niet-discriminerend) te licentiëren; het Hof oordeelde dat het aanvragen van een verbod tegen een bereidwillige licentienemer artikel 102 kan schenden, tenzij de SEO-houder de vermeende inbreukmaker eerst waarschuwt, een specifiek schriftelijk FRAND-aanbod doet, en de gebruiker daarna voortvarend en te goeder trouw reageert, bijvoorbeeld door zekerheid of een gemotiveerd tegenaanbod te bieden. Dit weegt de eigendomsrechten van de SEO-houder af tegen het risico dat dreigingen met een verbod de licentiehouder dwingen tot royalty\'s ver boven de werkelijke FRAND-waarde, een verschijnsel dat mededingingswetenschappers "hold-up" noemen, wat enorm van belang is gezien hoe dwingend een verbod wordt wanneer een enkele standaard, zoals een mobiel netwerkprotocol, voor elke concurrent praktisch onvermijdelijk is. Nationale rechters, vooral in Duitsland en het VK, zijn sindsdien merkbaar uit elkaar gaan lopen in hoe strikt zij elke stap van de zogenoemde Huawei-volgorde toepassen, waardoor SEO-verbodsprocedures een van de meest forumshoppende terreinen van de Europese octrooipraktijk zijn. De zaak zelf ontstond uit een geschil over LTE-essentiële octrooien op het hoogtepunt van de smartphoneoctrooioorlogen van het begin van de jaren 2010.',
    ],
    [
      'Aan welke twee voorwaarden moet een "parodie" volgens het arrest van het HvJEU in Deckmyn/Vandersteen (2014) over de parodie-uitzondering onder de InfoSoc-richtlijn voldoen, zonder andere vaak veronderstelde voorwaarden te moeten vervullen?',
      [
        'Het oorspronkelijke werk oproepen terwijl het merkbaar afwijkt daarvan, en een uiting van humor of spot vormen, zonder dat eigen oorspronkelijkheid of expliciete vermelding van komische bedoeling nodig is',
        'Geregistreerd zijn als parodie bij een nationale auteursrechtinstantie en voorafgaande toestemming van de oorspronkelijke auteur verkrijgen, formaliteiten die geen enkel EU-lidstaats auteursrecht in werkelijkheid vereist voor de uitzondering',
        'Niet-commercieel zijn en alleen voor privé, persoonlijk gebruik worden ingezet',
        'Korter zijn dan het oorspronkelijke werk en niet meer dan tien procent daarvan gebruiken',
      ],
      0,
      'Het Hof oordeelde ook, ongewoon, dat nationale rechters de legitieme belangen van de oorspronkelijke auteur moeten afwegen tegen vrijheid van meningsuiting - en in het onderliggende geschil, een Belgische zaak over een racistische bewerking van een omslag van het stripverhaal "Suske en Wiske", liet dit ruimte voor het falen van het parodieverweer als de boodschap van de parodie een discriminerende boodschap overbracht die de reputatie van de oorspronkelijke auteur schaadde.',
    ],
    [
      'Behandelde Sky plc/SkyKick UK Ltd (2020) de vraag of het registreren van een merk voor een uitzonderlijk brede specificatie, zoals eenvoudigweg "computersoftware", wat kan opleveren?',
      [
        'Kwade trouw, althans deels, als er geen werkelijke intentie was om het merk over de volle breedte van de opgeëiste waren of diensten te gebruiken',
        'Een automatische grond om de gehele registratie te herroepen, ongeacht enig daadwerkelijk gebruik dat wordt aangetoond voor engere waren daarbinnen',
        'Een strafbaar feit onder het EU-merkenrecht',
        'Een grond voor het betreffende nationale of EU-merkenbureau om registratie al vóór verlening uitdrukkelijk te weigeren, een materiële toetsing die het HvJEU verklaarde dat zulke bureaus in feite verplicht zijn uit te voeren in de onderzoeksfase',
      ],
      0,
      'Cloudmigratiebedrijf voor e-mail SkyKick, aangeklaagd door omroep Sky wegens merken die enorme categorieën dekten, waaronder simpelweg "computersoftware", betoogde dat Sky\'s registraties deels ongeldig waren wegens gebrek aan duidelijkheid en deels te kwader trouw waren aangevraagd zonder werkelijke intentie ze zo breed te gebruiken; het HvJEU oordeelde dat een te brede specificatie niet automatisch ongeldig is wegens gebrek aan duidelijkheid of nauwkeurigheid, maar dat kwade trouw een registratie deels ongeldig kan maken, voor de waren of diensten waarvoor nooit werkelijk gebruik was bedoeld, terwijl zij standhoudt voor waren die daadwerkelijk bedoeld en gebruikt waren. Dit was praktisch van belang omdat brede "portfolio"-aanvragen een gangbaar defensief procesmiddel zijn, en de uitspraak gaf gedaagden een echte, zij het beperkte, manier om zulke registraties terug te snoeien in plaats van een alles-of-niets geldigheidsstrijd te voeren. In de terugverwezen Britse uitspraak werden Sky\'s merken deels te kwader trouw geacht voor delen van de wijdlopige specificatie, maar Sky won toch zijn onderliggende inbreukvordering tegen SkyKick op de engere waren die overeind bleven. De zaak is nu een standaardverwijzing in advies aan merkaanvragers over de risico\'s van het opblazen van een specificatie ver voorbij werkelijke commerciële plannen.',
    ],
    [
      'De rechtspraaklijnen "Slovak Telekom" en het eerdere "Bronner" van het HvJEU over weigering van licentie of levering als misbruik van machtspositie onder artikel 102 VWEU zijn leerstellig van belang voor het IE-recht omdat zij bepalen wanneer wat moet wijken voor het mededingingsrecht?',
      [
        'Het recht van een IE-houder om een licentie te weigeren, in beperkte gevallen waarin weigering concurrentie op een verwante markt uitsluit en de input werkelijk onmisbaar is',
        'Alle octrooien vervallen automatisch zodra de houder in enige markt een machtspositie heeft',
        'Merkhouders moeten in elke EU-lidstaat op verzoek licentiëren aan concurrenten',
        'Auteursrecht kan onder geen enkele omstandigheid worden afgedwongen tegen een onderneming met machtspositie, een algemene regel die geen enkele EU-mededingings- of auteursrechtelijke instantie in enige gepubliceerde beslissing ooit heeft aangenomen',
      ],
      0,
      'Bronner (1998) stelde een strenge onmisbaarheid-plus-uitsluitingstoets vast die verplichte licentiëring onder het mededingingsrecht echt uitzonderlijk maakte (in contrast met de eerdere, meer interventionistische Magill-zaak), en deze spanning tussen het belonen van door IE gedreven investering en het voorkomen van concurrentiebeperkende uitsluiting blijft een van de meest leerstellig betwiste kruispunten tussen IE-recht en mededingingsrecht in de EU.',
    ],
    [
      'Welke vraag van rechtsmacht onder de EU-Merkenverordening behandelde AMS Neve/Heritage Audio (2019)?',
      [
        'Of een rechter in de lidstaat waar consumenten worden aangetrokken door online reclame en verkoopaanbiedingen rechtsmacht heeft over een vordering wegens inbreuk op een EU-merk, ook als de gedaagde elders gevestigd is',
        'Of een EU-merk überhaupt buiten de enkele lidstaat waarin het oorspronkelijk werd geregistreerd, kan worden afgedwongen',
        'Of rechtsmacht altijd uitsluitend bij de rechter van het land van vestiging of oprichting van de gedaagde ligt, ongeacht waar in de EU enige daadwerkelijke commerciële schade voor de merkhouder feitelijk is ontstaan',
        'Of merkgeschillen via arbitrage moeten worden beslecht in plaats van via een procedure zodra een EU-merk is verleend',
      ],
      0,
      'Het in het VK gevestigde AMS Neve klaagde het Spaanse bedrijf Heritage Audio in het VK aan wegens vermeend inbreukmakende online advertenties en verkoop gericht op Britse consumenten, en het HvJEU oordeelde dat "de lidstaat waar de inbreukmakende handeling is verricht" onder de EUM-verordening ook de staat omvat waar de door onlinecontent aangetrokken consumenten of handelaren zich bevinden, niet alleen de staat waar de gedaagde het materiaal fysiek publiceerde of gevestigd is. Dit was van enorm belang voor onlinehandel, omdat het een rechthebbende toestaat te procederen waar de commerciële schade daadwerkelijk landt, in plaats van gedwongen te worden elke verkoper in zijn eigen thuisjurisdictie te achtervolgen. De "gerichtheid"-toets die het Hof toepaste volgt vergelijkbare redeneringen uit eerdere rechtspraak van het HvJEU over rechtsmacht bij online smaad en consumentenovereenkomsten, wat laat zien dat het EU-internationaal privaatrecht convergeert naar één algemene aanpak om te bepalen waar een online handeling daadwerkelijk plaatsvindt. AMS Neve is een Britse fabrikant van audioapparatuur, vooral bekend van klassieke analoge studiomengpanelen, wat het onderliggende merkgeschil een merkwaardig nichesfeer van hoogwaardige opnamestudio\'s geeft voor een zaak die uiteindelijk de EU-doctrine over online-rechtsmacht heeft herschapen.',
    ],
  ],
};
