import type { CategoryContent } from '../row.js';

export const MATERIALS_SCIENCE: CategoryContent = {
  bscba: [
    [
      'Welke term beschrijft de regelmatige, zich herhalende 3D-rangschikking van atomen in een kristallijn materiaal?',
      [
        'Kristalrooster',
        'Amorf structuur',
        'Korrelgrens',
        'Eenheidscel',
      ],
      0,
      'Een kristalrooster is het zich herhalende patroon van atomen; \'eenheidscel\' verwijst naar de kleinste zich herhalende eenheid erin.',
    ],
    [
      'Welke van deze is een primaire maatstaf voor de weerstand van een materiaal tegen permanente vervorming onder belasting?',
      [
        'Vloeispanning',
        'Thermische geleiding',
        'Brekingsindex',
        'Permeabiliteit',
      ],
      0,
      'Vloeispanning markeert de spanningsgrens waarboven een materiaal permanent vervormt. Andere eigenschappen meten ander gedrag.',
    ],
    [
      'Welke as van een fasediagram stelt typisch samenstelling in een binair legersysteem voor?',
      [
        'Horizontaal (x-as)',
        'Verticaal (y-as)',
        'Diagonaal',
        'Radiaal',
      ],
      0,
      'Fasediagrammen gebruiken de horizontale as voor samenstelling en de verticale as voor temperatuur in standaard binaire systemen.',
    ],
    [
      'Welke materiaalklasse wordt gedefinieerd door lange-ketenorganische moleculen met herhalende eenheden?',
      [
        'Polymeren',
        'Keramiek',
        'Metalen',
        'Composieten',
      ],
      0,
      'Polymeren bestaan uit monomeren die in lange ketens zijn verbonden. Keramiek bestaat uit anorganische verbindingen, metalen zijn elementair/gelegeerd, composieten combineren matrix en versterking.',
    ],
    [
      'Wat is het primaire bindingsmechanisme in keramische materialen?',
      [
        'Ionische en covalente binding',
        'Metallische binding',
        'Waterstofbinding',
        'Van der Waalskrachten',
      ],
      0,
      'Keramiek is afhankelijk van ionische en covalente bindingen tussen atomen. Metalen gebruiken metallische binding; polymeren gebruiken covalente ruggengraat met zwakkere secundaire krachten.',
    ],
    [
      'In metallurgie, wat is een legering?',
      [
        'Een mengsel van twee of meer elementen waarvan minstens één een metaal is',
        'Een zuiver metaalelement',
        'Een chemische verbinding met vaste stoichiometrie',
        'Een gelaagde structuur van verschillende metalen',
      ],
      0,
      'Een legering is een metallische mengsel (vaste oplossing, intermetallisch of multifase) ontworpen om eigenschappen te verbeteren ten opzichte van het basismetaal.',
    ],
    [
      'Welke mechanische eigenschap beschrijft het vermogen van een materiaal om energie op te nemen voordat het breekt?',
      [
        'Taaiheid',
        'Hardheid',
        'Stijfheid',
        'Ductiliteit',
      ],
      0,
      'Taaiheid combineert sterkte en ductiliteit en meet opgenomen energie tijdens breuk. Hardheid weerstaat indrukking; stijfheid weerstaat vervorming; ductiliteit is permanente vervormingscapaciteit.',
    ],
    [
      'Welke techniek meet de weerstand van een materiaaloppervlak tegen krassen of indrukking?',
      [
        'Hardheidstest',
        'Trektest',
        'Thermische analyse',
        'Röntgendiffractie',
      ],
      0,
      'Hardneidstests (Vickers, Rockwell, Brinell) kwantificeren oppervlakteweerstand. Trektesting meet sterkte/ductiliteit; thermische analyse volgt faseveranderingen; röntgendiffractie identificeert kristalstructuur.',
    ],
    [
      'Welke van deze is een primaire toepassing voor halfgeleiders in materiaalkunde?',
      [
        'Het beheersen van elektrische geleidbaarheid in apparaten',
        'Dragende structuurcomponenten',
        'Het verbeteren van polymeersterkte',
        'Het verhogen van keramische taaiheid',
      ],
      0,
      'Halfgeleiders (Si, Ge, GaAs) zijn ontworpen voor gecontroleerde elektrische eigenschappen. De andere opties beschrijven verschillende materialfuncties.',
    ],
    [
      'Wat is een composietmateriaal?',
      [
        'Twee of meer samenstellende materialen met verschillende eigenschappen, gecombineerd om gewenste prestaties te bereiken',
        'Een enkel zuiver element met meerdere kristallijne fasen',
        'Een legering met precies drie componenten',
        'Een polymeer versterkt met alleen inerte vullers',
      ],
      0,
      'Composieten combineren opzettelijk matrix en versterking (vezels, deeltjes, enz.) om de sterktes van elk onderdeel te benutten.',
    ],
    [
      'In de materiaalkunde, waar verwijst de term \'korrel\' naar?',
      [
        'Een enkele kristalregio binnen een polykristallijn materiaal',
        'Een standaard voor classificatie van deeltjesgrootte',
        'De textuur van een polymeeroppervlak',
        'Een defect in een keramische structuur',
      ],
      0,
      'Een korrel is één kristallijn domein; korrels worden gescheiden door korrelgrenzen. Korrelgrootte beïnvloedt materiaaleigenschappen dramatisch.',
    ],
    [
      'Welke van deze stelt de hoogste pakketdichtheid voor bollen in een rooster voor?',
      [
        'Kubisch vlakgecentreerd of hexagonaal dicht gepakt',
        'Eenvoudige kubisch',
        'Kubisch lichaamsgecentreerd',
        'Diamantkubisch',
      ],
      0,
      'FCC en HCP bereiken beide ~74% pakketdichtheid. Eenvoudige kubisch is ~52%, BCC is ~68%, diamantkubisch is ~34%.',
    ],
    [
      'Wat bereikt \'gloeien\' in metaalbewerking?',
      [
        'Verhitten en langzaam afkoelen om interne spanning te verminderen en ductiliteit te verbeteren',
        'Snel afkoelen om hardheid te verhogen',
        'Legeren met koolstof om staal te versterken',
        'Het oppervlak polijsten om het uiterlijk te verbeteren',
      ],
      0,
      'Gloeien verlicht spanning, kristalliseert de structuur opnieuw en verzacht het metaal. Snel afkoelen (blussen) verhardde; legeren voegt sterkte toe; polijsten is cosmetisch.',
    ],
    [
      'Welke eigenschap beschrijft de neiging van een materiaal om energie op te nemen en vervolgens vrij te geven wanneer het elastisch wordt vervormd?',
      [
        'Veerkracht',
        'Breekbaarheid',
        'Kneedbaarheid',
        'Transparantie',
      ],
      0,
      'Veerkracht is het elastische energieopnamecapaciteit. Breekbaarheid betekent beperkte plastische vervorming voor breuk; kneedbaarheid is vormveranderingsvermogen; transparantie is lichtdoorlaatbaarheid.',
    ],
    [
      'Welke structuurkenmerk maakt polymeren flexibel in vergelijking met metalen?',
      [
        'Zwakkere secundaire bindingen (van der Waalskrachten) tussen ketens, waardoor schuiven en rotatie mogelijk zijn',
        'Lagere atoommassa',
        'Lagere smelttemperaturen',
        'Willekeurige atoomarrangementen',
      ],
      0,
      'Polymeerketens worden bijeengehouden door zwakke secundaire krachten, waardoor kettingbeweging mogelijk is. Metalen hebben stijve metallische binding door de hele structuur.',
    ],
  ],
  msc: [
    [
      'Wat is de betekenis van het eutectisch punt op een binair fasediagram?',
      [
        'De samenstelling met de laagste smelttemperatuur waar alle fasen tegelijk solidificeren in evenwicht',
        'Het punt van maximale oplosbaarheid van het ene metaal in het ander',
        'De samenstelling waar mechanische eigenschappen optimaal zijn',
        'De kritieke temperatuur waarboven het systeem een enkele fase wordt',
      ],
      0,
      'Het eutectisch punt is de samenstelling met de laagste smelttemperatuur; alle samenstellende stoffen kristalliseren tegelijk bij constante temperatuur, met karakteristieke lamellaire microstructuur.',
    ],
    [
      'In polymeerwetenschap, welke term beschrijft de mate waarin polymeerketens in geordende, regelmatige arrays zijn gerangschikt?',
      [
        'Kristalliniteit',
        'Polymerisatie',
        'Vertakking',
        'Vervetting',
      ],
      0,
      'Kristalliniteit meet geordende tegen amorfe kettingverpakking; hoge kristalliniteit verhoogt sterkte en smeltpunt. Polymerisatie is kettinggroei; vertakking en vervetting veranderen topologie.',
    ],
    [
      'Welke keramische fabricagetechniek omvat het oplossen van voorloperingsmaterialen en het vormen van een gel die wordt gedroogd en gesinterd?',
      [
        'Sol-gelsynthese',
        'Droog persen',
        'Gietwerkprocédé',
        'Heet persen',
      ],
      0,
      'Sol-gel produceert fijne, homogene keramiek bij lage temperaturen via voorloperingsgelatie. Persen en gieten gebruiken voorgevormde poeders; heet persen combineert druk en warmte.',
    ],
    [
      'Welk mechanisme stelt martensitische transformatie in staal in staat om hardheid te produceren?',
      [
        'Diffusieloze atoomherrangschikking die een overreverzadigde vaste oplossing van koolstof creëert',
        'Nucleatie en groei van cementiedeltjes',
        'Korrelvereffening door snelle afkoeling',
        'Neerslag van intermetallische fasen',
      ],
      0,
      'Martensiet vormt via een diffusieloze (athermale) schuiftransformatie, waarbij koolstofatomen worden opgesloten en stijve, harde kristalstructuur wordt gecreëerd.',
    ],
    [
      'In breukmechanica, wat kenmerkt de spanningsintensiteitsfactor (K)?',
      [
        'De ernst van het spanningsveld van de scheurtip, voorspellend scheurgroeiwaarchijnlijkheid',
        'De totale sterkte van het materiaal',
        'De ductiliteit van het materiaal',
        'De temperatuur waarop breuk optreedt',
      ],
      0,
      'K kwantificeert scheurtipspanningsconcentratie; breuk treedt op wanneer K de kritieke breuksoepelheid (K_IC) overschrijdt. Het verbindt materiaaleigenschappen met defectgrootte en spanning.',
    ],
    [
      'Wat is het primaire voordeel van het toevoegen van versterkingevezels aan een polymeermatrix in composieten?',
      [
        'Vezels bieden hoge stijfheid en sterkte terwijl matrix taaiheid en beschadigingstolerantie biedt',
        'Vezels verminderen de totale dichtheid van de composiet',
        'Vezels voorkomen dat de matrix kristalliseert',
        'Vezels vergroten de transparantie van het materiaal',
      ],
      0,
      'Met vezels versterkte composieten benutten vezels sterkte/stijfheid met matrixductiliteit, wat superieure specifieke (gewichtsgerekende) eigenschappen bereikt.',
    ],
    [
      'Welke karakteriseringstechniek gebruikt een röntgenstraalbundel die door kristalvlakken wordt afgebogen om fasen en roosterparameters te identificeren?',
      [
        'Röntgendiffractie (XRD)',
        'Differentiaalscanningcalorimetrie (DSC)',
        'Transmissie-elektronenmicroscopie (TEM)',
        'Atoomkrachtmicroscopie (AFM)',
      ],
      0,
      'XRD past de wet van Bragg toe op kristalvlakken en produceert diffractiepatronen die fasen identificeren en roosterconstanten kwantificeren. DSC meet thermische gebeurtenissen; TEM en AFM leggen structuur in beeld.',
    ],
    [
      'Wat is het Hall-effect in halfgeleiders en waarom is het significant?',
      [
        'Een transversale spanning verschijnt wanneer stroom door een geleider in een magnetisch veld gaat, wat het dragertype en concentratie onthult',
        'De verandering in bandgapenergie bij aangelegde spanning',
        'De opwekking van licht wanneer stroom door een junctie vloeit',
        'De weerstandsverandering bij zeer lage temperaturen',
      ],
      0,
      'Hall-effect (transversale spanning van stroom × magnetisch veld) meet laaddragersdichtheid en -type. Het is cruciaal voor karakterisering van halfgeleiderdoping en mobiliteit.',
    ],
    [
      'In legeringsontwerp, wat is een vaste-oplossingsversterkingsmechanisme?',
      [
        'Opgeloste soluteatomen vervormen het rooster, waardoor dislocatieverplaatsing wordt belemmerd',
        'Neerslag van een tweede fase aan korrelgrenzen',
        'Vorming van nieuwe kristallijne fasen met verschillende structuren',
        'Vermindering van korrelgrootte door korrelgrenzen vast te zetten',
      ],
      0,
      'Soluteatomen creëren lokale roostervervormingen die dislocatieslip blokkeren, wat vloeispanning verhoogt zonder aparte deeltjes toe te voegen.',
    ],
    [
      'Welke eigenschap van een polymeer wordt gemeten door trektesting met veel lagere snelheid dan normaal om afhankelijk van tijd gedrag aan het licht te brengen?',
      [
        'Kruipweerstand (weerstand tegen voortdurende vervorming onder constante spanning)',
        'Slagsterkte',
        'Scheurweerstand',
        'Oppervlaktehardheid',
      ],
      0,
      'Kruiptesting past constante spanning toe bij lage verwringingssnelheid om permanente vervorming over tijd te kwantificeren—kritiek voor polymeren met langdurige belasting.',
    ],
    [
      'Welke nanomate riaalvorm bestaat uit éénatomdikke koolstofplaten in een zeshoekig rooster?',
      [
        'Grafeen',
        'Koolstofnanobuizen',
        'Fullerenen',
        'Nanodeeltjes',
      ],
      0,
      'Grafeen is een 2D-allotropie met uitzonderlijke sterkte, geleiding en stijfheid. Nanobuizen zijn 1D opgerolde grafeen; fullerenen zijn 0D kooimoleculen; nanodeeltjes zijn massieve bollen.',
    ],
    [
      'Wat is de rol van een dislocatie in plastische vervorming van kristallijne materialen?',
      [
        'Een lijndefect dat door het rooster beweegt, wat atomaire afschuiving mogelijk maakt zonder alle bindingen tegelijk te breken',
        'Een puntdefect veroorzaakt door ontbrekende atomen op roosterlokaties',
        'Een korrelgrens die twee kristaloriëntaties scheidt',
        'Een stapelfout in een gelaagde structuur',
      ],
      0,
      'Dislocaties (lijndefecten) bewegen door afschuiving, wat plastische stroming mogelijk maakt bij spanningen veel onder theoretische limieten. Andere defecten beïnvloeden gedrag anders.',
    ],
    [
      'In materiaalkunde-karakterisering, welk fenomeen meet differentiaalscanningcalorimetrie (DSC)?',
      [
        'Warmtestroom in of uit een monster als temperatuur verandert, wat faseveranderingen en reactiekinetiek onthult',
        'De kristallijne structuur van het monster',
        'De oppervlakteruwheid en topografie',
        'De elektrische geleidbaarheid tegen temperatuur',
      ],
      0,
      'DSC meet warmtestroom (endo/exotherm) om smelting, kristallisatie, glastransities en ontleding op te sporen. XRD onthult structuur; AFM geeft topologie in kaart; andere methoden meten geleidbaarheid.',
    ],
    [
      'Wat is het primaire mechanisme waarmee korrelgrenstechniek de breuksoepelheid in keramiek verbetert?',
      [
        'Gecontroleerde interkristallijne kristallografie vertraagt scheurvoortplanting door gemengde-mode breuken af te dwingen',
        'Het totale aantal korrels in het materiaal vergroten',
        'Kleine hoeveelheden ductiele fasen aan grenzen toevoegen',
        'Alle korrelgrenzen elimineren via enkelvoudige kristalgroei',
      ],
      0,
      'Afgestemde korrelgrenzentypen (bijvoorbeeld tweelingkorrelgrenzen van hogere orde) buigen en stompen scheuren af, wat energieabsorptie voor breuk verhoogt.',
    ],
    [
      'Wat is de betekenis van de Schmid-factor in het bepalen van de gemakkelijkheid van dislocatieslip op een bepaald glidsysteem?',
      [
        'Het kwantificeert de opgeloste afschuifspanning op een glidvlak als τ = σ·cos(φ)·cos(λ), wat voorspelt welke systemen eerst activeren onder belasting',
        'Het meet de totale dislocatiedichtheid in het materiaal',
        'Het beheert de thermische stabiliteit van dislocaties',
        'Het bepaalt de snelheid van dislocatienucleatie',
      ],
      0,
      'Schmid-factor m = cos(φ)cos(λ) voorspelt systeemactivering bij glidding; systemen met hoogste m buigen eerst. Kritieke opgeloste afschuifspanning τ_CRSS is onafhankelijk van σ-grootte.',
    ],
  ],
  phd: [
    [
      'Wat onthult het Gibbs-vrije-energieoppervlak wanneer het wordt uitgezet als functie van samenstelling en temperatuur in een ternair fasediagram?',
      [
        'De thermodynamische stabiliteit van fasen, met fasegrenzen gedefinieerd door dubbele raaklijnconstructies',
        'De mechanische eigenschappen van elke fase als functie van samenstelling',
        'Het kinetische traject waarlangs een fase in een ander transformeert',
        'Het elektrische-geleiding-oppervlak van het legeringssysteem',
      ],
      0,
      'G(X,T)-oppervlakken identificeren stabiele fasen; fasegrenzen ontstaan uit gemeenschappelijke raakpunten. Dit is de thermodynamische basis van fasediagrammen.',
    ],
    [
      'In materiaaldegradatie, wat is de rol van elektrochemisch potentiaal in putcorrosie van geparenteerde metalen?',
      [
        'Wanneer de aangelegde potentiaal het putpotentiaal overschrijdt, breekt de passieve film af, waardoor een autocatalytische zure put ontstaat',
        'Het potentiaal bepaalt de snelheid van uniforme corrosie over het oppervlak',
        'Het elektrochemische potentiaal beheert de dikte van de oxidlaag',
        'Het bepaalt direct de mechanische sterkte van het gecorrodeerde materiaal',
      ],
      0,
      'Putcorrosie ontstaat wanneer aangelegde of gelokaliseerde potentiaal E_pit overschrijdt, wat de passiverende oxidfilm afbreekt en zelf-voortplantende corrosie triggert.',
    ],
    [
      'Wat is de oorsprong van de glastransitieftemperatuur (T_g) in amorfe polymeren, en hoe verschilt het van kristallijn smelten?',
      [
        'T_g is een kinetische overgang waar kettingmobiliteit bevriezen (geen langafstandsorderverlies); T_m is thermodynamische fasewijziging in geordende kristallen',
        'T_g treedt bij hogere temperaturen op dan T_m in alle polymeren',
        'T_g vereist een kristalstructuur om te worden gedefinieerd',
        'Zowel T_g als T_m meten dezelfde thermodynamische gebeurtenis',
      ],
      0,
      'T_g is een kinetische overgang (kettingbevriezing/ontdooiing); T_m is een ware faseovergang die geordende kristallen smelt. Ze weerspiegelen verschillende fysische fenomenen.',
    ],
    [
      'In halfgeleiderfysica, wat bepaalt de breedte van de depletieregion in een p-n junctie bij thermisch evenwicht?',
      [
        'Het ingebouwde potentiaal en de doperingsconcentraties van beide zijden, via de Poisson-vergelijking-oplossing',
        'De aangelegde externe spanning',
        'De thermische energie van de ladingsdragers',
        'De bandgapenergie van het materiaal',
      ],
      0,
      'Depletiebreedte W ∝ √(V_bi/[eN_A+eN_D]) uit de Poisson-vergelijking; ingebouwde potentiaal (ln(N_A N_D / n_i²)) en doperingsniveaus beheersen het.',
    ],
    [
      'Wat is de betekenis van de Burgers-vector in het karakteriseren van dislocaties, en hoe verhoudt het zich tot het dislocatietype?',
      [
        'Het specificeert de grootte en richting van roostervervormingen; randdislocaties hebben b loodrecht op de lijnrichting, schroef heeft b parallel',
        'Het bepaalt de energie die nodig is om de dislocatie te vormen',
        'Het beheert of de dislocatie via klim of glijden kan bewegen',
        'Het meet de afstand die de dislocatie door het kristal heeft bewogen',
      ],
      0,
      'Burgers-vector b kenmerkt het defect; voor rand b ⊥ lijnrichting, voor schroef b ∥ lijnrichting. b-grootte geeft roostervervormening en energie aan.',
    ],
    [
      'In composietmechanica, wat voorspelt de mengselverhoudingsregel, en onder welke belastingconditie is het het nauwkeurigst?',
      [
        'Een lineaire composieteigenschap als gewogen gemiddelden van samenstellingseigenschappen; het nauwkeurigst voor longitudinale (vezel-parallelle) belasting',
        'De breukspanning van de composiet ongeacht belastingsrichting',
        'De thermische expansiecoëfficiënt van alle vezelversterkte composieten',
        'De elektrische geleidbaarheid van keramische matrixcomposieten',
      ],
      0,
      'Mengselverhoudingsregel: E_c = V_f E_f + V_m E_m is nauwkeurig voor longitudinale belasting waar belastingen rechtstreeks via vezels worden overgedragen.',
    ],
    [
      'Welke mechanismen domineren verbetering van breuksoepelheid in transformatie-verharde zirkonia-keramiek?',
      [
        'Spanningsgeïnduceerde tetragonaal-naar-monoklien-fasetransformatie absorbeert energie en creëert residuale drukspanning',
        'Plastische vervorming van korrelgrenzen',
        'Microscheuring voor de scheurtip',
        'Neerslag van een metallische fase',
      ],
      0,
      'De tetragonale fase van zirkonia is metastabiel; scheurtipspanning triggert transformatie naar monoklien, wat volumeexpansie creëert die scheuren comprimeert en energie dissipeert.',
    ],
    [
      'In nanomaterialen, wat is de rol van de oppervlakte-naar-volume-verhouding in het veranderen van materiaaleigenschappen ten opzichte van de bulk?',
      [
        'Bij kleine afmetingen domineert oppervlakte-energie, wat thermodynamisch evenwicht verschuift, smelt-/transitiepunten verlaagt en diffusietarief verhoogt',
        'Oppervlakte-effecten zijn verwaarloosbaar onder 100 nm',
        'Oppervlakteatomen zijn chemisch identiek aan bulkatomen',
        'Nanomaterialen hebben altijd hogere smeltpunten dan bulk',
      ],
      0,
      'Naarmate de grootte afneemt, neemt S/V toe; oppervlakte-energie wordt dominant, verlaagt T_m (Gibbs-Thomson), verhoogt sintering/diffusie, wijzigt thermodynamische stabiliteit.',
    ],
    [
      'Wat is de fysische basis van het Griffith-criterium voor breuk van brosse materialen, en wat voorspelt het?',
      [
        'Breuk treedt op wanneer elastische vervormingsenergie vrijgegeven door scheurgroei gelijk is aan oppervlakte-energie nodig om nieuwe oppervlakken te creëren',
        'Breuk wordt zuiver door spanning beheert en is onafhankelijk van foutgrootte',
        'Alle materialen bezwijken bij dezelfde aangelegde spanning als scheuren aanwezig zijn',
        'Plastische vervorming treedt altijd voor breuk op',
      ],
      0,
      'Griffith: spanning vereist voor breuk σ = √(2Eγ/πa) neemt af met foutgrootte a. Energiebalans (elastische vrijgave versus oppervlaktecreatie) voorspelt instabiliteit.',
    ],
    [
      'In legerings-thermodynamica, wat geeft een negatieve mengingswarmte aan, en hoe beïnvloedt het fasestabiliteit?',
      [
        'Gunstige atoominteracties; het systeem bevordert menging, stabiliseert vaste oplossing en verhoogt consolute-temperatuur',
        'Afstotende interacties die altijd fasescheiding veroorzaken',
        'Geen effect op fasestabiliteit of fasediagramvorm',
        'Een indicator dat de legering amorf zal zijn',
      ],
      0,
      'Negatieve ΔH_mix bevordert atoominteractie en homogene menging; fasescheiding treedt op bij grotere |ΔS|. Positieve ΔH_mix drijft fasesplitsing aan.',
    ],
    [
      'Welke informatie biedt transmissie-elektronenmicroscopie (TEM) die rastereelektronenmicroscopie (SEM) niet kan?',
      [
        'Real-space kristalstructuur en roosterdefecten met atoomresolutie; SEM is oppervlakte-beperkt met nanometer-ruimtelijke resolutie',
        'Hogere bedrijfsspanningen voor diepere penetratie',
        'Betere kleurafbeelding van monsteroppervlakken',
        'Snellere analyse van grote monstergebieden',
      ],
      0,
      'TEM stuurt elektronen door dunne monsters, wat atoomstructuur, dislocaties en interfaces onthult (nm–Å resolutie); SEM beeldt oppervlakken topografisch af (nm resolutie).',
    ],
    [
      'In biomaterialen, wat is osseo-integratie, en welke materiaal- en oppervlakteeigenschappen verbeteren het?',
      [
        'Directe bot-implantaatcontact bereikt door bioactieve oppervlaktechemie en oppervlakteruwheid die celadhesie en mineralisatie bevorderen',
        'Implantaatmaterialen die volledig inert en niet-reactief zijn',
        'Elk metalen implantaat dat lange-termijn stabiliteit in het lichaam bereikt',
        'De inkapseling van een implantaat in littekenweefsel',
      ],
      0,
      'Osseo-integratie vereist bioactieve oppervlakken (TiO₂, hydroxylgroepen, calciumfosfaat) en ruwheid (microschaal) voor osteoblastenhechting en botvorming.',
    ],
    [
      'Wat is de theoretische vloeispanning van een perfect kristal, en hoe vergelijkt werkelijke vloeispanning zich vanwege dislocaties?',
      [
        'Theorie voorspelt ~G/30 (waarbij G is afschuifmodulus); echte materialen buigen bij ~G/100–G/1000 omdat dislocaties bij veel lagere spanning bewegen',
        'Werkelijke vloeispanning overschrijdt altijd theoretische sterkte',
        'Dislocaties verhogen de spanning die nodig is om het materiaal te vervormen',
        'Perfecte kristallen zijn onmogelijk, dus theorie is irrelevant',
      ],
      0,
      'Perfect kristal: σ_th ≈ G/30 (alle bindingen breken tegelijkertijd). Dislocaties staan afschuiving via herrangschikking toe, wat waargenomen σ_y met 1–2 orden van grootte verlaagt.',
    ],
    [
      'In verwerkings-structuur-eigenschap-relaties, hoe verandert snelle solidificatie de microstructuur en vergroot vaste-oplossingsgrenzen in legeringen?',
      [
        'Snelle afkoeling onderdrukt diffusie, wat niet-evenwichtssolute-niveaus (omzeilt evenwichtsfasediagram) in de val zet en metastabiele fasen mogelijk maakt',
        'Snelle afkoeling produceert altijd evenwichtsfasen',
        'Afkoelingssnelheid heeft geen effect op vaste oplosbaarheid',
        'Alleen korrelgrootte wordt beïnvloed; samenstelling blijft evenwicht',
      ],
      0,
      'Snelle solidificatie onderdrukt diffusie kinetisch; soluteatomen worden ingesloten, wat evenwichtsoplosbaarheid overschrijdt en niet-evenwichtige vaste oplossingen en metastabiele fasen vormt.',
    ],
    [
      'Wat is de relatie tussen stapelfoutenergie (SFE) en dislocatietype in FCC-metalen?',
      [
        'Lage SFE vermindert dislocatie-kruisglij-activiteit en vernauwd partiële scheiding, wat vervormingstwinning en lagere verfestigingssnelheden bevordert',
        'SFE bepaalt de glijrichting in BCC-metalen',
        'Hoge SFE leidt altijd tot brosse breuk',
        'SFE is onafhankelijk van legeringssamenstelling',
      ],
      0,
      'Lage SFE (bijv. Cu, Ag legeringen) verbreed partiële dislocatiescheiding, belemmert kruisglij en bevordert twinning; hoge SFE (Al, Ni) bevordert gemakkelijk kruisglij en verharding.',
    ],
  ],
  professor: [
    [
      'In thermodynamische modellering van multicomponent-legeringen, wat is de fysische en wiskundige betekenis van de excess Gibbs-energie (G^ex) in het bepalen van fasestabiliteit en ordening?',
      [
        'G^ex beschrijft afwijkingen van ideale menging door inter-atoominteracties; zijn samenstelling en temperatuursafhankelijkheid beheert mengbaarheidskloven, ordeningtransities en kritieke fenomenen',
        'G^ex is altijd nul in alle echte materialen',
        'G^ex beïnvloedt alleen de entropieterm, niet enthalpie',
        'G^ex is zuiver empirisch zonder fysische basis',
      ],
      0,
      'G^ex (niet-ideale bijdrage) ontstaat uit atoominteracties; zijn vorm bepaalt fasediagramtopologie—mengbaarheidskloven, consolute-punten en orde-wanorde-overgangen.',
    ],
    [
      'Wat verklaart het Cottrell-atmosfeermodel in ijzerhoudende metallurgie, en hoe verhoudt het zich tot dynamische vervormingsveroudering en het Portevin–Le Chatelier-effect?',
      [
        'Koolstof-/stikstofatmosferen rond dislocaties creëren dynamische vergrendeling; bij bepaalde vervormingssnelheden veroorzaken herhaalde vergrendeling/ontgrendeling gekartelde spanning-vervormingscurven en vervormingsinstabiliteit',
        'Het Cottrell-model is alleen van toepassing op statische sterkte, niet op dynamisch gedrag',
        'Het voorspelt dat dynamische vervormingsveroudering het materiaal altijd verzacht',
        'Cottrell-atmosferen zijn irrelevant voor moderne legeringen',
      ],
      0,
      'Cottrell-atmosferen (solute-dislocatie-wolken) spelden dislocaties dynamisch vast; concurrentie tussen diffusie-gesteunde ontvergrendeling en hervergrending produceert PLC-effect (stroomkarteling).',
    ],
    [
      'In breukmechanica, wat onderscheidt K-gedomineerd (lineaire elastische breukmechanica, LEFM) van J-integraal-gedomineerd (elastisch-plastische breukmechanica, EPFM) regimes, en wanneer is elk van toepassing?',
      [
        'LEFM (K) is van toepassing wanneer de plastische zone klein is ten opzichte van foutgrootte; J-integraal (EPFM) legt niet-lineair gedrag vast wanneer de plastische zone groot is; overgang gedefinieerd door B > 25(K_IC/σ_Y)²',
        'K en J zijn wiskundig equivalent en geven altijd dezelfde resultaten',
        'J-integraal wordt alleen gebruikt voor keramiek, K voor metalen',
        'LEFM is het enige geldige breukcriterium voor alle materialen',
      ],
      0,
      'LEFM: kleine plastische zone (B, a >> p_y); geldig wanneer σ_Y, elastisch materiaal. EPFM: grote plastische zone; J-integraal legt niet-lineaire pad-onafhankelijkheid vast.',
    ],
    [
      'Welke rol spelen coherentievervormingen in precipitate-versterkingsmechanismen, en hoe verlaagt oververoudering sterkte?',
      [
        'Coherente precipitaten veroorzaken roostervervormingen die dislocatieverplaatsing belemmeren; oververoudering maakt deeltjes grover, vermindert vervormingsvelden en dislocatie-interacties (Orowan-looping domineert)',
        'Coherentievervormingen bevorderen altijd plastische vervorming',
        'Oververoudering verhoogt hardheid indefinitief',
        'Precipitaatgrootte heeft geen effect op dislocatieverharding',
      ],
      0,
      'Coherente vervormingen maximaliseren snijweerstand; naarmate deeltjes via diffusie grover worden, nemen elastische vervormingen af en neemt Orowan-afstand toe, wat hardheid vermindert.',
    ],
    [
      'In oppervlakte-thermodynamica, wat is de relatie tussen oppervlakte-energie (γ), oppervlakte-overmaat en grensvlak-segregatie, en waarom segregeren bepaalde elementen bij voorkeur?',
      [
        'Atomen met lagere bulkcohesieve energie segregeren om grensvlak-energie te verminderen; adsorptie wordt aangedreven door ΔG_ads = ΔH_ads - TΔS_ads < 0',
        'Oppervlakte-energie is altijd gelijk aan bulkenergie',
        'Segregatie heeft geen thermodynamische drijvende kracht',
        'Alle elementen segregeren met gelijke snelheden ongeacht eigenschappen',
      ],
      0,
      'Segregatie minimaliseert G_interface; elementen met zwakke bulkcohesie en hoge oppervlakte-affiniteit (lage γ, gunstige ΔH_ads) adsorberen bij voorkeur op defecten.',
    ],
    [
      'Wat is de oorsprong van het piëzo-elektrische effect in kristallen, en waarom is het verboden in materialen met inversiesymmetrie?',
      [
        'Niet-centrosymmetrische kristallen missen inversiesymmetrie, dus elastische vervormingen kunnen ionen verplaatsen, netto dipolmoment creëren (polarisatie ∝ vervormingen); inversiesymmetrie vereist dat tegengestelde verplaatsingen opheffen',
        'Piëzo-elektriciteit ontstaat alleen uit metallische binding',
        'Inversiesymmetrie vergroot het piëzo-elektrische respons',
        'Het piëzo-elektrische effect is zuiver elektronisch zonder ionverplaatsing',
      ],
      0,
      'Piëzo-elektriciteit: vervormingen breken symmetrie, creëert ongecompenseerde lading. Inversiesymmetrie maakt vervormingen equivalent aan -vervormingen, dus netto dipool = 0.',
    ],
    [
      'In de theorie van martensitische fasetransformaties, wat is de roosterdeformatiegradiënt, en hoe verhoudt Bain-vervormingen zich tot roostercorrespondentie en oriëntatierelatie?',
      [
        'De deformatiegradiënt F beschrijft roostervervormingen; Bain-vervormingen (tetragonale verstoring van austeniet) gecombineerd met rosterrotatie geeft het habitvlak en oriëntatierelatie (OR)',
        'Martensitische transformatie is zuiver reconstructief, zonder roostervervormingen',
        'De roostercorrespondentie is willekeurig en niet gerelateerd aan OR',
        'Bain-vervormingen en habitvlak zijn onafhankelijke parameters',
      ],
      0,
      'F = R·U; Bain-vervormingen (rosteruitrekking naar martensiet) + stijve rotatie R bepalen habitvlak (invariant-vlak-vervormingstoestand) en kristal-OR.',
    ],
    [
      'Wat is het mechanisme van scheurbemiddeling in vezelversterkte composieten, en hoe draagt werklengte van vezeltrekking bij aan breuksoepelheid?',
      [
        'Ongebroken vezels over een scheur dragen spanning nadat de matrix bezwijkt; uittrekwerk (wrijving × ingebedde lengte) dissipeert energie en verhoogt G_IC',
        'Scheurbemiddeling door vezels vermindert composietstijfheid',
        'Uittrekwerk is altijd verwaarloosbaar in vergelijking met matrixtaaiheid',
        'Vezels moeten breken opdat de composiet bezwijkt',
      ],
      0,
      'Bemiddelde vezels dragen σ_f = τ√(2ρ_f λ) (afschuivertragings); L_eff uittreklengte en grensvlakwrijving τ beheersen W_pullout, verhogen rechtstreeks K_IC of G_IC.',
    ],
    [
      'In halfgeleiderbandstructuur-engineering, wat bereikt het concept van \'bandgap-engineering\' via heterojonctie, en welke rol speelt vervormingen?',
      [
        'Rooster-niet-overeenkomende lagen creëren vervormde heterostructuren, verschuiven bandgaps en bandoffsets, stellen type-I/type-II-uitlijningen en kwantumbeperkingseffecten mogelijk',
        'Bandgap-engineering geldt alleen voor elementaire halfgeleiders',
        'Vervormingen verslechteren altijd halfgeleiderprestaties',
        'Bandoffsets worden uitsluitend bepaald door doperingsniveaus',
      ],
      0,
      'Epitactische vervormingen in niet-overeenkomende heterostructuren verschuiven E_g en ΔE_c/ΔE_v offsets, stellen op maat afgesnede banduitlijning voor apparaten mogelijk (LED\'s, lasers, thermisch-elektrisch).',
    ],
    [
      'Wat is het Mullins-effect in elastomeren, en welke moleculaire mechanismen beheersen spannsingsverzwakking en hysterese in gevulde polymeren?',
      [
        'Spannsingsverzwakking door verstoring van vulling-polymeer-binding en vullingagglomeraatafbraak; hysterese door vullingherrangschikking en kettingslip (viskeuze demping)',
        'Het Mullins-effect treedt alleen op in ongevulde elastomeren',
        'Gevulde polymeren vertonen altijd constant spanning-vervormingsgedrag bij herbelasting',
        'Hysterese is zuiver elastisch zonder viskeuze bijdrage',
      ],
      0,
      'Mullins-effect: cyclische belasting breekt vulling-polymeer-interfaces en agglomeraten; lagere modulus bij herbelasting door onomkeerbare structuurveranderingen en viskeuze dissipatie.',
    ],
    [
      'In hoge-temperatuurkruip van keramiek en metalen, wat is de fysische basis van diffusionele kruip (Nabarro-Herring- en Coble-mechanismen), en hoe schalen ze met spanning en korrelgrootte?',
      [
        'Leegteloca-diffusie uit spannningsgeconcentreerde regio\'s; N-H: korrelinterieur-diffusie (ε̇ ∝ σ/d²); Coble: korrelgrens-diffusie (ε̇ ∝ σ/d³); beide ∝ D·σ/kT',
        'Diffusionele kruip is altijd sneller dan dislocatiekruip',
        'Korrelgrootte heeft geen effect op kruipsnelheid',
        'Kruip is zuiver elastische vervorming bij hoge temperatuur',
      ],
      0,
      'N-H (interieur-diffusie) en Coble (korrelgrens-diffusie) schalen met σ en omgekeerde macht van d; snelheden ∝ D(T)σ. Dominant bij lage σ, hoge T.',
    ],
    [
      'Wat is de fysische betekenis van de Debye-temperatuur (Θ_D) in het bepalen van rooster- en warmtetransporteigenschappen, en hoe verhoudt het zich tot mechanische eigenschappen van materialen?',
      [
        'Θ_D ∝ √(stijfheid)/√(dichtheid) stelt de fononafsnijding en thermische capaciteit in; hoge Θ_D correleert met hoge geluidsnelheid, elastische modulus en slechte thermische geleiding in keramiek',
        'Debye-temperatuur beïnvloedt alleen optische eigenschappen',
        'Hoge Θ_D betekent altijd betere thermische geleiding',
        'Θ_D is onafhankelijk van elastische eigenschappen',
      ],
      0,
      'Θ_D ≈ ℏω_D/k_B ∝ v_s; hoge Θ_D geeft stijf rooster aan (hoge E, v_s). Fononenverstrooiing en gemiddelde vrije weg beheersen κ onafhankelijk.',
    ],
    [
      'In heterogene nucleatie, welke rol spelen contacthoek en oppervlakte-energieverschil in het verminderen van kritieke kerngrootte in vergelijking met homogene nucleatie?',
      [
        'Lagere contacthoek θ vermindert kritieke kerngrootte via geometriefactor f(θ) = (2-3cosθ+cos³θ)/4; kleine θ bevordert nucleatie door grensvlak-energiekosten te verminderen',
        'Contacthoek beïnvloedt alleen bevochtigung, niet nucleatie',
        'Homogene en heterogene nucleatie hebben identieke kritieke afmetingen',
        'Oppervlakte-energieverschillen zijn altijd verwaarloosbaar voor nucleatie',
      ],
      0,
      'Kritieke straal: r* = 2γ_SL cosθ/(ρΔg); als θ → 0, r* → min; activeringsenergie ΔG* ∝ f(θ)·γ³/ΔG², wat heterogene paden bevordert.',
    ],
    [
      'Wat is het mechanisme en de betekenis van korrelgroei in nanokristallijne materialen, en waarom is de Zener-speldkracht onvoldoende om nanometerachtige korrels bij verhoogde temperatuur te stabiliseren?',
      [
        'Oppervlakte-energieaangedreven korrelgroei (korrelgrenzen verlagen energie naarmate d toeneemt); Zener-speld (F ∝ Z·r/d) faalt bij d → nm omdat Z naar nul gaat en T-geactiveerde beweging speld overwint',
        'Nanokristallijne materialen groeien nooit, ongeacht temperatuur',
        'Korrelgroei wordt zuiver beheert door dislocatiedichtheid, niet door korrelgrenzen',
        'Zener-speld wordt sterker bij kleinere korrelgroottes',
      ],
      0,
      'Korrelgroei: dE/dd ∝ -2γ/d (vermindert G); Zener: F_Z = Z·r/d verzwakt naarmate d krimpt en precipitaatdichtheid daalt; thermische activering overwint zwakke speld.',
    ],
    [
      'In de context van computationele materiaalkunde, wat is dichtheidsfunctionaaltheorie (DFT), en welke benadering (bijv. LDA, GGA) beperkt fundamenteel zijn voorspellende nauwkeurigheid voor grondtoestandeigenschappen?',
      [
        'DFT lost de Kohn-Sham-vergelijkingen zelf-consistent op; LDA/GGA-uitwisselings-correlatiebenaderingen laten hogere-orde-correlatieeffecten achterwege, veroorzakend systematische fouten in bandgaps, transitiebarrières en sterk-gecorreleerde systemen',
        'DFT lost direct de volledige Schrödinger-vergelijking zonder benadering op',
        'LDA en GGA zijn exacte functionalen zonder fouten',
        'DFT kan structuureigenschappen niet voorspellen, alleen elektronische',
      ],
      0,
      'DFT-basis: grondtoestands-E uniek bepaald door n(r); Kohn-Sham is exact maar E_xc[n] is onbekend. LDA/GGA benaderen E_xc, introduceren systematische fouten in bandstructuur en barrières.',
    ],
  ],
};
