import type { CategoryContent } from '../row.js';

export const ORGANIC_CHEMISTRY: CategoryContent = {
  bscba: [
    [
      'Welk reactietype wordt gekenmerkt door een nucleofiel dat in één stap een koolstof met een goede vertrekgroep aanvalt met inversie van stereochemie?',
      [
        'Bimoleculaire nucleofiele substitutie (SN2)',
        'Unimoleculaire eliminatie (E1)',
        'Elektrofiele aromatische substitutie (EAS)',
        'Nucleofiele acylsubstitutie',
      ],
      0,
      'SN2 is aanval van achter in één stap met inversie van stereochemie. E1 is unimoleculair met racemisatie; EAS en acylsubstitutie verschillen mechanistisch.',
    ],
    [
      'Wat is de primaire functionele groep aanwezig in een carboxylzuur?',
      [
        'Carbonyl gebonden aan hydroxyl (carboxylgroep, -COOH)',
        'Een aldehyde met extra zuurstof',
        'Een ester op een primair alcohol',
        'Een keton met een nabije hydroxylgroep',
      ],
      0,
      'De carboxylgroep -COOH bestaat uit C=O en O-H. Aldehyden, esters en ketonen zijn verschillende functionele groepen met onderscheiden chemie.',
    ],
    [
      'In een E2-eliminatiereactie, welke ruimtelijke relatie hebben de waterstof en vertrekgroep?',
      [
        'Anti (of antiperiplanair) arrangement',
        'Gauche arrangement',
        'Eclipsed arrangement',
        'Geen specifieke ruimtelijke eis',
      ],
      0,
      'E2 vereist antiperiplanaire geometrie voor gelijktijdige C-H en C-LG breking. Gauche en eclipsed zijn geen eisen; E2 is stereospecifiek.',
    ],
    [
      'Welk reagens wordt gewoonlijk gebruikt om een primair alcohol tot aldehyde te oxideren?',
      [
        'Pyridinium chlorochromaat (PCC)',
        'Kaliumpermanganaat (KMnO4)',
        'Lithiumaluminium hydride (LiAlH4)',
        'Natriumborhydride (NaBH4)',
      ],
      0,
      'PCC oxideert primaire alcoholen selectief tot aldehyden onder milde voorwaarden. KMnO4 over-oxideert; LiAlH4 en NaBH4 zijn reductiemiddelen.',
    ],
    [
      'Wat beschrijft de term "regioselectiviteit" in organische reacties?',
      [
        'Voorkeurvorming van één positie-isomeer boven een ander',
        'Voorkeur voor één stereoisomeer boven een ander',
        'De snelheid waarmee een reactie evenwicht bereikt',
        'De hoeveelheid nevenproduct gevormd',
      ],
      0,
      'Regioselectiviteit verwijst naar welke regio van een molecuul reageert. Stereoselectiviteit betreft stereoisomeren; reactiesnelheid en opbrengst zijn afzonderlijke concepten.',
    ],
    [
      'Welke stelling beschrijft correct een Grignard reagens (RMgX)?',
      [
        'Een organometaallische nucleofiel zeer reactief tegenover carbonylverbindingen',
        'Een alkylhalogenide gebruikt in eliminatiereacties',
        'Een katalytische soort voor hydrogenering',
        'Een oxidatiemiddel voor primaire alcoholen',
      ],
      0,
      'Grignard reagens zijn organometaallische nucleofielen waardevol voor C-C bindingsvorming met carbonylen. Alkylhalogeniden zijn elektrofielen; Grignards zijn geen katalysatoren of oxidatiemiddelen.',
    ],
    [
      'Wat is de relatie tussen (R)-glyceraldehyde en (S)-glyceraldehyde?',
      [
        'Het zijn enantiomeren',
        'Het zijn diastereomeren',
        'Het zijn constitutionele isomeren',
        'Het zijn dezelfde molecuul',
      ],
      0,
      'Enantiomeren zijn niet-superimponeerbare spiegelbeelden die op één chiraalbasis verschillen. Diastereomeren verschillen op enkele maar niet alle stereocentra; constitutionele isomeren hebben verschillende connectiviteit.',
    ],
    [
      'In nucleofiele acylsubstitutie, welk intermediair ontstaat nadat de nucleofiel de carbonyl aanvalt?',
      [
        'Een tetrahedraal intermediair',
        'Een carbokation',
        'Een enolaat anion',
        'Een epoxide',
      ],
      0,
      'Nucleofiele aanval op een platte sp² koolstof vormt een tetrahedraal intermediair. Carbokationen, enolaten en epoxiden zijn verschillende soorten.',
    ],
    [
      'Welke functionele groep oxideert het gemakkelijkst onder milde voorwaarden?',
      [
        'Een primair alcohol',
        'Een ether',
        'Een amide',
        'Een alkeen',
      ],
      0,
      'Primaire alcoholen oxideren gemakkelijk door chroom(VI) en andere milde oxidatiemiddelen tot aldehyden. Ethers, amiden en alkenen weerstaan oxidatie onder normale omstandigheden.',
    ],
    [
      'Wat voor molecuul ontstaat uit een Diels-Alder reactie?',
      [
        'Een cyclohexeen (zesbands ring met één dubbele binding)',
        'Een cyclobuteen (vierbands ring)',
        'Een bicyclisch verbinding',
        'Een open-keten diene',
      ],
      0,
      'De [4+2] Diels-Alder cyclotoevoeging vormt een zesbands ring. Cyclobuteen ontstaat uit [2+2]; bicyclische producten vereisen meerdere reacties; open-keten producten zijn geen cycloadditen.',
    ],
    [
      'In SN1 mechanisme, wat is de snelheidsbepalende stap?',
      [
        'Carbokation vorming (heterolyse C-LG binding breking)',
        'Nucleofiel aanval op de C-LG binding',
        'Herrangschikking van de alkylketen',
        'Vertrek van de vertrekgroep na nucleofiel binden',
      ],
      0,
      'De langzame stap in SN1 is vorming van het carbokation intermediair. Nucleofiel aanval is snel; herrangschikking is optioneel; LG vertrek voorafgaat nucleofiel binding.',
    ],
    [
      'Welk verbinding is een primair amine?',
      [
        'CH3-CH2-NH2',
        'CH3-CH2-NH-CH3',
        '(CH3)3N',
        'C6H5-NH2 met een benzylsubstituent op N',
      ],
      0,
      'Een primair amine heeft één alkyl-/arylgroep op stikstof en twee waterstofatomen. Secundaire aminen hebben twee groepen; tertiaire aminen hebben drie; de laatste optie is secundair.',
    ],
    [
      'Wat is de stereochemische uitkomst van hydrogenering van een alkeen met H2 en katalysator?',
      [
        'Syn toevoeging (H-atomen voegen toe aan dezelfde zijde)',
        'Anti toevoeging (H-atomen voegen toe aan tegenovergestelde zijden)',
        'Een mengsel van syn en anti producten',
        'Inversie van de dubbele bindingsgeometrie',
      ],
      0,
      'Katalytische hydrogenering voegt beide H-atomen toe aan dezelfde zijde van de alkeen (syn). Anti toevoeging treedt op met halogenen; mengsels en geometrische inversie treden niet op.',
    ],
    [
      'Welke stelling beschrijft Markovnikov\'s regel?',
      [
        'Bij toevoeging aan ongelijke alkenen voegt de nucleofiel toe aan de koolstof met meer waterstof (meer gesubstitueerde koolstof krijgt meer negatieve groep)',
        'Bij eliminatie is het meer gesubstitueerde alkeen altijd het belangrijkste product',
        'Bij substitutie worden primaire koolstoffen altijd eerder aangevallen dan secundaire',
        'Racemische mengsels vormen altijd in polaire oplosmiddelen',
      ],
      0,
      'Markovnikov\'s regel voorspelt regioselectiviteit: H voegt toe aan de koolstof met meer H (minder gesubstitueerde). Het bepaalt niet eliminatieselectiviteit of substitutiepatronen.',
    ],
    [
      'Welke functionele groep ontstaat wanneer een keton door natriumborhydride wordt gereduceerd?',
      [
        'Een secundair alcohol',
        'Een primair alcohol',
        'Een alkaan',
        'Een aldehyde',
      ],
      0,
      'NaBH4 reduceert ketonen (en aldehyden) tot alcoholen; ketonen geven secundaire alcoholen. Primaire alcoholen komen uit aldehyden; alkanen vereisen sterkere reductiemiddelen.',
    ],
  ],
  msc: [
    [
      'In het SN1 mechanisme van een secundaire alkylhalogenide, welke factor stabiliseert het carbokation intermediair het meest?',
      [
        'Hyperconjugatie en inductieve effecten van α-alkylgroepen',
        'Resonantiestabilisatie van een aangrenzende aromatische ring',
        'Solvatatie door polaire protonenafgeving oplosmiddelen',
        'Sterische verlichting bij vertrek van vertrekgroep',
      ],
      0,
      'Hyperconjugatie en inductieve donatie van nabije koolstoffen stabiliseren secundaire carbokationen. Aromatische resonantie geldt alleen voor benzyl; solvatatie helpt snelheid maar stabiliseert intermediaten niet.',
    ],
    [
      'Waarom ondergaat 1,2-dimethyloxirane (propyleenoxide) regioselectieve ringopening naar de minder gesubstitueerde koolstof wanneer aangevallen door nucleofiel in basisvoorwaarden?',
      [
        'SN2-achtige aanval van achter op de minder belemmerde koolstof',
        'Directe nucleofiel benadering naar het meer gesubstitueerde centrum vanwege elektrostatische polariteit',
        'Carbokation vorming liever op de meer gesubstitueerde plaats',
        'Sterische blokkering van de meer gesubstitueerde koolstof door methylgroepen',
      ],
      0,
      'Epoxide SN2 ringopening voorkort de minst belemmerde koolstof via aanval van achter. Anders dan carbokation vorming is epoxide opening onder basis/nucleofiele voorwaarden bimoleculair; meer gesubstitueerde koolstof is sterisch geblokkeerd.',
    ],
    [
      'In E1cb (conjugaatbasis) eliminatie, welk intermediair is essentieel vóór C-H bindingsbreking?',
      [
        'Een enolaat of carbanion gevormd door deprotonering',
        'Een carbokation intermediair',
        'Een cyclisch drieledige ring intermediair',
        'Een π-complex met de basiscatalysator',
      ],
      0,
      'E1cb deprotonering gaat aan LG verlies vooraf, vormend enolaat/carbanion. Dit ordent als E1-achtig (E) maar carbanion-afhankelijk (1cb), onderscheiden van carbokation E1 of syn E2.',
    ],
    [
      'Welke combinatie van factoren maakt een verbinding een slechte Diels-Alder dienophiel?',
      [
        'Een elektron-donerende groep op de dubbele binding en lage sterische eis',
        'Elektron-onttrekkende groepen (EWGs) op de dubbele binding',
        'Sterische hindering van omringende bulkige groepen',
        'Hoge symmetrie van de dienophiel',
      ],
      0,
      'Diels-Alder dienofielen moeten elektron-deficiënt zijn (EWGs versnellen). Elektron-donoren deactiveren; sterische eis bemoeilijkt benadering maar is niet inherent disqualificerend; symmetrie is orthogonaal.',
    ],
    [
      'In de Wittig reactie, welk intermediair ontstaat nadat het ylide de aldehyde carbonyl aanvalt?',
      [
        'Een betaïne (1,2-dipolar zwitterion) die sluit tot een oxirane',
        'Een ylide-aldehyde adduct dat onmiddellijk fosfineoxide uitstoot',
        'Een carbokation-fosfoniumintemediair',
        'Een enol gestabiliseerd door het fosforatoom',
      ],
      0,
      'Wittig ylide aanval geeft betaïne, die sluit tot drieledige oxirane; decompositie geeft alkeen en fosfineoxide. Andere opties geven foutieve volgorde.',
    ],
    [
      'Waarom ondergaat E2 eliminatie van een primaire alkylhalogenide zelden plaats ondanks gunstige kinetiek, terwijl secundaire en tertiaire alkylhalogeniden gemakkelijk E2 ondergaan?',
      [
        'Primaire carbokationen zijn uiterst onstabiel; SN2 is kinetisch en thermodynamisch bevorderd',
        'Primaire C-H bindingen zijn te sterk om te breken',
        'Basiskatalytische isomerisatie blokkeert eliminatie',
        'Oplosmiddelviscositeit remt E2 voorkeur bij primaire sites',
      ],
      0,
      'Primaire alkylhalogeniden kiezen SN2 boven E2 omdat het primaire carbokation drastisch onstabiel is; bimoleculaire substitutie overwint unimoleculaire eliminatie. C-H sterkte is niet de barrière; isomerisatie en solventeffecten zijn geen primaire factoren.',
    ],
    [
      'In retrosyntetische analyse, wat betrekking heeft het "umpoled carbonyl" concept?',
      [
        'Omgekeerde polariteit van een koolstof van elektrofiel naar nucleofiel',
        'Omzetting van een keton naar enol voor selectieve substitutie',
        'Introductie van stereocentra via aldolcondensatie',
        'Activering van carbonyl via bescherming als ketal',
      ],
      0,
      'Umpolung (Duits "polariteitsomkering") zet normaal elektrofiele koolstof om in nucleofiel (bijv. via dithianen). Enolisatie, aldol en ketalbeveiliging zijn andere transformaties.',
    ],
    [
      'Wat is de stereochemische uitkomst van een [2,3]-sigmatrope verschuiving van een allylsulfoxide in de Mislow herschikking?',
      [
        'Suprafaciale herschikking met inversie op sulfoxide zwavel en allylkoolstof',
        'Antarafaciale herschikking die nieuwe alkeen-geometrie genereert',
        'Geen netto verandering in stereochemie op beide centra',
        'Exclusieve vorming van (R,R)-diastereomeer ongeacht startmateriaal',
      ],
      0,
      'De [2,3]-sigmatrope verschuiving is suprafaciaal; beide zwavelinversie en allylkoolstof inversie treden op, met voorspelbare uitkomst. Antarafaciaal, geen verandering en diastereomeer exclusiviteit zijn onjuist.',
    ],
    [
      'In de Heck reactie gekatalyseerd door Pd(0), wat is de eerste stap na oxidatieve toevoeging van het organische halogenide?',
      [
        'Migratietoevoeging van alkeen in de Pd-C binding',
        'Coördinatie van alkeen aan het Pd centrum',
        'Reductieve eliminatie om het gekoppelde product te vormen',
        'β-waterstof eliminatie van het alkylpalladium',
      ],
      0,
      'Na oxidatieve toevoeging coördineert de alkeen aan Pd en voegt in in de Pd-alkylbinding (migratietoevoeging). Reductieve eliminatie is finaal; β-waterstof eliminatie volgt toevoeging.',
    ],
    [
      'Wat is het fundamentele verschil tussen diastereomeer en enantiomeer in het context van prochiraaliteit?',
      [
        'Enantiotope groepen zijn diastereomer naar elkaar in aanwezigheid van chirale reagens; diastereotope groepen hebben intrinsiek verschillende chemische verschuivingen',
        'Beide zijn onzichtbaar voor achirale reagens; beide vereisen chirale vergelijking om te detecteren',
        'Enantiotope groepen vereisen spiegelvlak; diastereotope groepen niet',
        'Enantiomeren zijn alleen onderscheidend door chirale oplosmiddelen; diastereomeren hebben altijd verschillende NMR signalen',
      ],
      0,
      'Enantiotope groepen worden diastereomeer wanneer behandeld met chirale reagens. Diastereotope groepen zijn intrinsiek verschillend (verschillende NMR in achirale oplosmiddelen). Beide verduidelijken symmetrieanalyse.',
    ],
    [
      'In olefine metathese gekatalyseerd door Grubbs katalysator, wat is de metaal-carbeen soort die reactie initieert?',
      [
        'Een ruthenium alkyliden (Ru=CH-R) complex dat [2+2]-toevoegt aan olefine',
        'Een ruthenium carbokation gecoördineerd aan kationisch fosfine',
        'Een metathese complex dat gelijktijdig twee olefinen bindt',
        'Een wolfraam alkyliden dat minder selectief is dan Ru-gebaseerde katalysatoren',
      ],
      0,
      'Grubbs katalysator is Ru(II) alkyliden dat reageert met olefinen via [2+2] cyclotoevoeging van Ru=C π-binding. Carbokation, dubbel-olefine binding en wolfraamvergelijking zijn onnauwkeurig.',
    ],
    [
      'Waarom is de Cope herschikking een [3,3]-sigmatrope verschuiving in plaats van [1,5]-verschuiving?',
      [
        '[3,3]-verschuiving is suprafaciaal en thermisch toegestaan volgens Woodward-Hoffmann regels (4n+2 elektronen); [1,5] is antarafaciaal en verboden',
        '[1,5]-verschuivingen vereisen chiralcentrum dat selectiviteit bepaalt',
        'De Cope herschikking vormt zesbands overgangstoestand geometrisch incompatibel met [1,5]',
        'Alleen [3,3]-verschuivingen zijn mogelijk in 1,5-dienen vanwege moleculaire symmetrie',
      ],
      0,
      'Cope herschikking betreft 6π elektronen (4n+2, n=1), makend suprafaciaal [3,3]-verschuiving thermisch toegestaan. [1,5]-verschuiving zou antarafaciaal met 6π zijn, verboden. Chiraliteit, overgangstoestand grootte en symmetrie zijn niet primair.',
    ],
    [
      'In beschermingsgroepenstrategia, welke eigenschap maakt benzylethers geschikt voor alcoholbescherming in meerstappen synthese?',
      [
        'Gemakkelijk gekliefd door hydrogenolise (H2/Pd) en resistent tegen waterige zuur/basis, mogelijk orthogonale bescherming',
        'Orthogonaal aan acetylesters via selectieve verseiffing',
        'Stabiel onder zowel zure als basische waterige voorwaarden, maar gekliefd door sterke oxidatiemiddelen',
        'Gemakkelijk geïnstalleerd door Williamson ether synthese en gekliefd door excess Grignard reagens',
      ],
      0,
      'Benzylethers worden reductief gekliefd (H2/Pd-C) en stabiel onder zuur/basis, mogelijk onafhankelijke manipulatie van andere groepen. Acetylesters, sterke oxidatiemiddelen en Grignard klieving zijn niet karakteristiek.',
    ],
    [
      'Wat betekent de term "diastereofaciale selectiviteit" (of "diastereofaciale discriminatie") in asymmetrische synthese?',
      [
        'Voorkeurs aanval op één zijde van prochiraalbasis door chirale reagens of katalysator',
        'Selectieve vorming van één geometrische isomeer van alkeen',
        'Voorkeurs reactie op één stereogecenterd positie in meso verbinding',
        'De neiging van enantiomeren om apart te kristalliseren',
      ],
      0,
      'Diastereofaciale selectiviteit beschrijft hoe chirale katalysator/reagens onderscheid kan maken tussen twee zijden van prochiraalgroep, vormend één diastereomeer. Geometrische isomerisatie, meso reactiviteit en kristallisatie zijn afzonderlijke concepten.',
    ],
    [
      'In natuurproductsynthese, waarom is asymmetrische Sharpless dihydroxylatie (AD) veel gebruikt ondanks stoichiometrische chirale ligand?',
      [
        'Het biedt hoge enantioselectiviteit, 1,2-diol functionaliteit en katalytische omzet op osmium en chirale ligand',
        'Het is economischer dan chirale hulpstof methoden en vormt enkel één stereoisomeer',
        'Het werkt als echte katalytische proces met substechiometrisch osmium',
        'Het vereist geen beschermingsgroepen en is compatibel met alle functionele groepen',
      ],
      0,
      'Sharpless AD is waardevol voor hoge ee en directe syn-diol vorming; osmium wordt gerecycled (katalytisch), hoewel AD reagens en ligandstoichiometrie bereid moeten. Stoichiometrische ligand en compatibiliteit zijn reëel.',
    ],
  ],
  phd: [
    [
      'In de Eschenmoser-Claisen herschikking, wat is het intermediair dat thermale [3,3]-sigmatrope verschuiving triggert?',
      [
        'Vorming van allylisch ketenen aminal (imidaat) uit allylisch alcohol en zwaveljlide precursor',
        'Een carbokation gegenereerd uit zuurgekataliseerde activering van hydroxylgroep',
        'Een enolaat gevormd door deprotonering van β-waterstof',
        'Een concerted intermediair waarin allylisch C-O binding synchroon breekt met C-C vorming',
      ],
      0,
      'Eschenmoser-Claisen gebruikt ketenen aminal intermediair (of equivalente imidaat/zwaveljlide complex) dat [3,3]-herschikking ondergaat. Carbokation, enolaat en directe concerted paden geven foutieve mechanisme.',
    ],
    [
      'Leg stereoelectronische eis uit voor efficiënte nucleofiele verdringing in Finkelstein reactie en relatie tot oplosbaarheid en reactiviteit van metaalhalogeniden.',
      [
        'Primaire of secundaire alkylhalogeniden in aprote oplosmiddelen; SN2 inversie verbeterd omdat aprote oplosmiddelen kation solvateren niet anion, nucleofilie stijgt zonder SN1 concurrentie',
        'Tertiaire halogeniden ondergaan E2 voorkeur vanwege sterische hindering, polaire protische oplosmiddelen onderdrukken nucleofilie',
        'Reactie is zuiver thermodynamisch bepaald door stabiliteit producten en metaalhalogenide kristallisatie',
        'Alkylflouriden zijn meest reactief omdat C-F bindingen naar nucleofiel gepolariseerd zijn',
      ],
      0,
      'Finkelstein slaagt met primaire/secundaire halogeniden in aprote oplosmiddelen (verhoogde anion nucleofilie, onderdrukte carbokationen). Tertiaire substraten elimineren; protische oplosmiddelen schaden nucleofilie.',
    ],
    [
      'In pericyclische [4+2] Diels-Alder reactie, wat voorspelt orbitalensymmetrieanalyse over toegestane versus verboden stereoelectronische paden?',
      [
        'Suprafaciaal [4+2] is toegestaan (4n elektronen, n=1); antarafaciaal [4+2] is verboden door Woodward-Hoffmann regels',
        'Beide suprafaciale en antarafaciale [4+2] paden zijn gelijk toegestaan vanwege symmetrie van geconjugeerde dienen',
        'Antarafaciaal [4+2] voorkeur wanneer elektron-onttrekkende groepen op dienophiel aanwezig',
        'Diels-Alder is inherent [2+4] reactie (dienophiel eerst genoemd), verandert toegestaan/verboden toewijzing',
      ],
      0,
      '[4+2] met 6π elektronen (4n+2) is suprafaciaal-toegestaan. Antarafaciaal zou tegenovergestelde orbitaaloverlap vereisen, geometrisch onhaalbaar voor dienen/dienofielen.',
    ],
    [
      'In overgangsmetaalkatalyse, wat is het mechanisme waardoor oxidatieve toevoeging van organisch halogenide aan Pd(0) verschilt in regioselectiviteit en mechanisme van SN2 verdringing?',
      [
        'Oxidatieve toevoeging treedt op aan metaal met twee-elektron transfer en vorming σ-complex (PdII-R en PdII-X); SN2 is nucleofiel aanval op koolstof met inversie',
        'Beide gaan door dezelfde carbokation intermediair, maar metaal stabiliseert ander stereoisomeer',
        'Oxidatieve toevoeging voorkeur secundaire halogeniden; SN2 voorkeur primaire halogeniden voor dezelfde substraat',
        'Regioselectiviteit bepaald door ionische sterkte oplosmiddel en halogenide grootte',
      ],
      0,
      'Oxidatieve toevoeging voegt Pd(0) in in C-X binding, vormend Pd(II)-C en Pd(II)-X. SN2 is nucleofiel aanval op koolstof met inversie. Mechanismen en substraten verschillen fundamenteel.',
    ],
    [
      'In Cope herschikking van gesubstitueerde 1,5-hexadieen met elektron-donerende en elektron-onttrekkende groepen, hoe beïnvloeden substituent elektronische effecten en sterische hindering overgangstoestand?',
      [
        'Elektronische activering (EWGs op terminal koolstoffen, EDGs op interne) verlaagt ΔG‡; sterische congestie verhindert herschikking',
        'EDGs versnellen reactie uniform ongeacht positie; sterische effecten verwaarloosbaar',
        'Herschikking is onder orbitale controle, elektronische effecten irrelevant',
        'Substituent effecten additief en verhogen ΔG‡ lineair met elektron-donerende groepen aantal',
      ],
      0,
      'Cope herschikking volgt pericyclische (orbitale) controleregels; elektronische effecten (EWGs versnellen) en sterische bulk op zesbands overgangstoestand beïnvloeden beide snelheid. EDGs niet uniform; orbitale controle sluit elektronische uit.',
    ],
    [
      'In katalytische enantioselectieve C-H functionalisatie, welk strategisch voordeel biedt asymmetrische katalyse via chirale richtingsgroep boven stoichiometrische chirale hulpstof?',
      [
        'Katalytische omzet verlaagt chirale ligand of substraatmodificatie nodig; plaats-selectiviteit gecontroleerd door richtingsgroep coördinatie aan metaal',
        'Richtingsgroepen altijd selectiever dan stoichiometrische hulpstoffen omdat blijvend bevestigd',
        'C-H functionalisatie vereist stoichiometrische chirale hulpstoffen; katalytische methoden kunnen enantioselectiviteit niet bereiken',
        'Stereoselectiviteit zuiver bepaald door katalysatorsterische bulk, onafhankelijk substraat',
      ],
      0,
      'Katalytische C-H functionalisatie met richtingsgroepen gebruikt substechiometrische katalysator en chirale liganden. Stoichiometrische hulpstoffen vereisen 1:1 ratio; plaats-selectiviteit is chelatiegecontroleerd.',
    ],
    [
      'In retrosyntetische planning van doel met meerdere stereocentra, wat is strategisch voordeel van "asymmetrische synthetische equivalent" (of "asymmetrische Umpolung")?',
      [
        'Staat stereochemie introductie toe in vroeg stadium via enkele enantioselectieve transformatie, verminderend meervoudige stereoselektieve stappen',
        'Vermindert totaalstappen door eliminatie chirale reagens nodig',
        'Garandeert alle volgende transformaties treden op met dezelfde relatieve stereochemie',
        'Alleen toepasbaar op natuurproducten met enkel stereocentrum',
      ],
      0,
      'Asymmetrische synthetische equivalenten stellen stereochemie vroeg in via enantioselectieve reactie, veel volgende stereoselektieve transformaties verminderd.',
    ],
    [
      'Leg de oorsprong van afwijkende regioselectiviteit uit in intramoleculaire Heck reactie wanneer carbopalladium intermediair zowel 5-exo-trig als 6-endo-trig cyclisatie kan ondergaan.',
      [
        '5-exo-trig pad kinetisch bevorderd door Baldwin regels (exo-trig toegestaan; sneller), hoewel 6-endo-trig thermodynamisch stabiel',
        '6-endo-trig altijd sneller vanwege geometrie Pd-alkeen π-complex',
        'Selectiviteit zuiver thermodynamisch afhankelijk van stabiliteit twee mogelijke carbokationen',
        'Endo-trig en exo-trig regels gelden alleen niet-katalytische reacties',
      ],
      0,
      'Baldwin regels bevoordelen 5-exo-trig (snellere kinetiek) boven 6-endo-trig (langzamer). Pd katalysator stabiliseert exo pad. Kinetische ring-sluitingselectiviteit overwint thermodynamica.',
    ],
    [
      'In polymeerchemie, wat is sleutel mechanistisch onderscheid tussen keten-groei polymerisatie via vrije radicalen versus levende anionische polymerisatie in termen keteindiging en molgewichtsverdeling?',
      [
        'Vrije radicaal polymerisatie ondergaat willekeurige beëindiging (koppeling of disproportionering), brede polydispersiteit; levende anionische geen beëindigingsstap, mogend gecontroleerde ketenlengtes en smalle Mw verdeling',
        'Levende anionische polymerisatie sneller maar lijdt aan bredere molgewichtsverdeling',
        'Vrije radicalen geven perfect uniforme ketenlengtes; anionische polymerisatie willekeurige lengtes',
        'Beide mechanismen geven identieke polydispersiteit indices met dezelfde monomeer',
      ],
      0,
      'Vrije radicaal polymerisatie beëindigt willekeurig (brede Mw). Levende anionische geen beëindiging (dormante carbanion stabiel), smalle Mw en gecontroleerde groei.',
    ],
    [
      'In natuurproductsynthese, wat is doel van "strategische bindingsdisconnectie" in retrosyntetische analyse en hoe verschilt van "tactische disconnectie"?',
      [
        'Strategische disconnectie breekt doel in grote, gemakkelijk gesynthetiseerde fragmenten die algehele complexiteit verminderen; tactische disconnectie lokaal, beschermingsgroep of regioscheikundige besluiten',
        'Strategische disconnectie altijd middenin molecuul; tactische disconnectie altijd aan uiteinden',
        'Beide verwijzen hetzelfde concept, maar "strategisch" gebruikt complexe doelen en "tactisch" eenvoudige',
        'Strategische disconnectie eerste, in orde, zonder flexibiliteit in planningsvolgorde',
      ],
      0,
      'Strategische disconnectie verminderen doel naar sleutel bouwblokken (vereenvoudigend synthetische boom); tactische disconnectie behandelt functionaalgroepmaskers en regiocontrole. Positie en flexibiliteit variëren; concepten onderscheiden in doel en bereik.',
    ],
    [
      'In Cram chelatie model voor asymmetrische inductie, waarom chelatie van nucleofiel (of Grignard) door β-amino alcohol of hydroxylgroep overschrijft Felkin-Anh sterische controle?',
      [
        'Chelaat richt nucleofiel op vaste zijde van carbonyl, oriënteer antiperiplanair aan chelatie groep en overschrijft Felkin sterische argumenten',
        'Chelatie verzwakt C=O binding, koolstof elektrofieler en minder afhankelijk sterische oriëntatie',
        'Felkin-Anh controle geldt alleen niet-chelatie Grignard reagens',
        'Chelatie en Felkin-Anh gelijk belangrijk en geen enkele regel overschrijft selectiviteit',
      ],
      0,
      'Cram chelatie creëert starre richtingsgeometrie één zijde favorerend; stereochemische bias overschrijft Felkin-Anh sterische argumenten. Bindingsactivering en Grignard type niet primair; modellen soms concurrerend.',
    ],
    [
      'In enantioselectieve epoxidatie (bijv. Jacobsen katalysator of Katsuki methode), wat is stereochemische rol chirale ligand in enantioselectiviteit bepalen van één zijde prochiraal olefine aanval?',
      [
        'Chirale katalysator zak creëert diastereomere overgangtoestanden voor twee olefine zijden benadering, één diastereomeer significant lager energie',
        'Katalysator onderscheidt geen olefine zijden; enantioselectiviteit ontstaat zuiver olefine intrinsieke reactiviteit',
        'Bulkige ligand blokkeert fysiek één olefine zijde, verhindert benadering die richting',
        'Ligand induceert tijdelijke chiralcentrum op olefine zelf, richting volgende reactie',
      ],
      0,
      'Asymmetrische epoxidatie gebruikt chirale metaalcomplex creërend diastereomere TS met één benadering significant bevorderd (prochiraal zijde discriminatie).',
    ],
    [
      'In Ireland-Claisen herschikking, wat is voordeel gebruik silylketenen acetal boven vrije enolaat in termen reactiemechanisme en selectiviteit?',
      [
        'Silylketenen acetal is pre-georganiseerd, thermisch stabiel (niet basis-gevoelig), ondergaat schonere [3,3]-herschikking zonder bijreacties, Si-O binding faciliteert overgangstoestand organisatie',
        'Silylgroep werkt als vertrekgroep, zettend herschikking om in SN2 substitutie',
        'Vrije enolaten selectiever maar vereisen stoichiometrische basis; silylacetalen elimineren behoefte',
        'Silylketenen acetal en vrije enolaat geven identieke resultaten, enkel basis differ vereist',
      ],
      0,
      'Silylketenen acetalen zijn pre-georganiseerd, bankstabiel en ondergaan [3,3]-herschikking schoon met minimale bijreacties; Si-O binding helpt overgangstoestand stabilisatie. Si geen vertrekgroep; basisbehoefte en reactiviteit verschillen; resultaten niet identiek.',
    ],
    [
      'In cascade reacties (of domino reacties), wat bepaalt "auto-katalytische" of "auto-voortplantende" aard bepaalde multi-component cyclisaties?',
      [
        'Product(en) vroege stap dienen als reactant(en) of katalysator(en) volgende stap, creërend zelf-sustaining reactiesequentie zonder reagens toevoeging',
        'Alle cascade reacties inherent auto-katalytisch wanneer uitgevoerd in één pot',
        'Reactie sneller als product voortdurend uit reactiemengsel wordt verwijderd',
        'Auto-katalyse alleen mogelijk in meerstaps synthesen met minstens drie verschillend reagens',
      ],
      0,
      'Cascade reacties zelf-voortplanten wanneer vroeg product reageert als partner of katalysator volgende stap (echte auto-katalyse). Niet alle één-pot reacties zijn cascades; product verwijdering niet definiërend; reagensaantal irrelevant.',
    ],
    [
      'In klikchemie, bijzonder koper(I)-gekatalyseerde azide-alkyn cyclotoevoeging (CuAAC), waarom is Cu(I) katalysator essentieel voor regioselectiviteit en reactiesnelheid controle?',
      [
        'Cu(I) activeert alkyn via complexatie, verlaagt HOMO-LUMO gat en mogelijk concerted [3+2] cyclotoevoeging tot 1,4-digesubstitueerde triazool als kinetisch product',
        'Cu(I) werkt als simpel tegenion zonder elektronisch effect alkyn',
        'Reactie gelijk snel zonder koper, maar koper toegevoegd voor veiligheidredenen',
        'Cu(I) katalyseren herschikking initiaal 1,5-triazool isomeer naar thermodynamisch 1,4-product',
      ],
      0,
      'Cu(I) complxeert alkyn, verlaagt HOMO en mogend concerted [3+2] cyclotoevoeging. 1,4-regioisomeer vormt direct (kinetisch product), niet via herschikking.',
    ],
  ],
  professor: [
    [
      'In overgangsmetaal-gekatalyseerde C-H functionalisatie, leg selectiviteit uit dat ortho, meta, para-substitutie in areen C-H activering beheerst wanneer richtingsgroep niet sterk coördinerende atoom.',
      [
        'Elektronische en sterische eigenschappen areen en zwakke chelatie of waterstofbinding interacties tussen katalysator en substraat bepalen plaats selectiviteit; ortho-selectiviteit ontstaat vaak gunstige chelatie, terwijl meta/para ontstaat elektronische of sterische effecten',
        'Para-selectiviteit universeel voorkeur vanwege resonantiestabilisatie areen π-systeem',
        'Meta-selectiviteit onmogelijk in aromatische C-H activering tenzij deactivering groep aanwezig',
        'Ortho, meta, para-substitutie treden op gelijke waarschijnlijkheid tenzij sterk chelatie richtingsgroep geïntroduceerd',
      ],
      0,
      'C-H activering selectiviteit ontstaat chelatie geometrie, elektronische factoren en sterische bulk. Zwakke waterstofbinding en secundaire chelatie moduleren ortho/meta/para selectiviteit.',
    ],
    [
      'In context fotochemische [2+2] cyclotoevoeging versus thermale Diels-Alder cyclotoevoeging, hoe Woodward-Hoffmann regels verklaren schijnbare "omkering" stereochemische toegestaan/verboden paden?',
      [
        'Thermaal [4+2] suprafaciaal-toegestaan (6π, 4n+2); fotochemische [2+2] (4π, 4n) suprafaciaal-toegestaan. Thermaal [2+2] (4π, 4n) suprafaciaal-verboden antarafaciaal-toegestaan (geometrisch moeilijk). Fotoon elektronische staat verandert orbitalensymmetrierelaties.',
        'Fotochemie eenvoudig versnelt thermale paden zonder selectieregels verandering',
        'Diels-Alder reacties zijn fotochemisch terwijl [2+2] cycloaddities thermaal, nooit tegengesteld',
        '"Omkering" kunstgreep oplosmiddeleffecten, niet orbitalensymmetrie',
      ],
      0,
      '[2+2] fotochemisch suprafaciaal-toegestaan omdat foton promotie elektronische configuratie verandert, uitkomsten versus thermaal omkeert. Orbitalensymmetrie, niet oplosmiddel, beheerst.',
    ],
    [
      'In enantioselectieve fase-overdrachtskatalyse, welke katalysatorontwerpkenmerken (of katalysatorstructuurmotief) stelt chirale kwaternaire ammonium ion hoge enantiocontrole mogelijk in reacties als asymmetrische epoxidatie of enolaat alkylatie?',
      [
        'Bulkige, stijf verbonden chirale groepen (vaak spiro of binaphthyl-gebaseerd) op ammonium kation creëren chirale omgeving organiserend ion-paar en schilderend één enolaat zijde aanval tegen',
        'Eenvoudige alkylketens ammonium centrum voldoende wanneer oplosmiddel zorgvuldig gekozen',
        'Tegenion (bijv. OH⁻ vs. Cl⁻) exclusieve bron stereochemische controle, onafhankelijk ammonium structuur',
        'Fase-overdrachtskatalyse niet bereikt hoge enantioselectiviteit omdat interface inherent achirale',
      ],
      0,
      'Bulkige, chirale kwaternaire ammonium katalysatoren (bijv. Maruoka ontwerpen) organiseren ion-paar geometrie en schilderen enolaat zijden, hogeee. Alkylketens alleen geen enantiocontrole; tegenion secundair; moderne PTC zeer hoge ee via ligandontwerp.',
    ],
    [
      'In natuurproductsynthese, "Kishi regel" (of uitgebreide selectiviteitsmodellen) geleidt 1,3-asymmetrische inductie in aciclische polyolsystemen; leg mechanistische basis uit waarom anti-Felkin trajectorie vaak onverwachte gevallen waarneemt.',
      [
        'Sterische en elektronische interacties (verborgen sterische/eenzaam paar effecten) in nucleofiel benadering of hydride aan chirale β-gesubstitueerde aldehyde kunnen conformaties bevoordelen verschillend Felkin-Anh voorspelling; conformatie evenwichten en waterstofbinding moduleren selectiviteit',
        'Anti-Felkin uitkomsten altijd vanwege chelatie en nooit zonder hydroxyl of amino groep β-positie',
        'Kishi regel en Felkin-Anh model tegenstrijdig, één moet altijd andere overschrijven',
        'Anti-Felkin selectiviteit ontstaat zuiver elektronische activering aldehyde koolstof door aangrenzend elektron-onttrekkende groepen',
      ],
      0,
      'Kishi/anti-Felkin uitkomsten weerspiegelen conformatie mobiliteit en waterstofbinding voorbij sterische eenvoudige argumenten. Modellen complementair, niet tegenstrijdig.',
    ],
    [
      'In katalytische asymmetrische C-C koppeling via Pd-gekatalyseerde kruis-koppeling, leg oorsprong enantiotrouwheid uit (of gebrek) wanneer Pd-alkyl intermediair stereogene koolstof draagt.',
      [
        'Enantiotrouwheid hangt af Pd-C bindingsstabiliteit en reductieve eliminatiesnelheid relatief β-waterstof eliminatie en isomerisatie; stereogene Pd-alkyl dat reductief elimineert sneller dan racemisatie behoudt enantiozuiverheid',
        'Pd-alkyl intermediaten altijd stereochemie inversie tijdens koppeling vanwege oxidatieve toevoegingnnatuur',
        'Enantiotrouwheid onmogelijk in kruis-koppeling; stereogene alkylgroepen altijd verloren of verward',
        'Alleen chirale liganden op palladium kunnen stereochemische trouwheid induceren; substraatstereoochemie irrelevant',
      ],
      0,
      'Enantiotrouwheid hangt af snelheden: snelle reductieve eliminatie overwint β-waterstof eliminatie en isomerisatie. Substraatstereoochemie en reactiviteit essentieel.',
    ],
    [
      'In polymeersyntheseeg, leg uit waarom gecontroleerde radicaalpolymerisatie (ATRP of RAFT) smalle polydispersiteit en blokko-polymeren toegang mogelijk maakt, contrasteerend mechanisme met levende anionische polymerisatie.',
      [
        'CRP handhaaft evenwicht tussen dormant alkylhalogenide en actief radicaal, houdt [radicaal] laag en minimaliseert beëindiging; RAFT gebruikt keten-overdracht evenwicht. Anionische polymerisatie irreversibel groeiend (geen dormant), sneller, maar functionaalgroep incompatibel.',
        'ATRP en RAFT gebruiken anionische intermediaten, essentieel gelijk aan levende anionische polymerisatie',
        'Levende anionische polymerisatie breder polydispersiteit dan ATRP omdat geen evenwichtcontrole',
        'Gecontroleerde radicaalpolymerisatie kan blokko-polymeren niet maken omdat radicalen niet lang genoeg leven',
      ],
      0,
      'CRP (ATRP/RAFT) handhaaft lage [radicaal] via dormant/actief evenwicht (gecontroleerde groei, smalle Mw). Anionische direct groeiend (geen dormant), veel functionaalgroepen incompatibel.',
    ],
    [
      'In totaalsynthese van complexe natuurproduct, hoe "beschermingsgroep-vrij" of "minimalist beschermingsgroep" strategieën verschillen in filosofie en uitvoering van traditionele routes, wat zijn sleutel synthetische uitdagingen?',
      [
        'Beschermingsgroep-vrije synthese exploiteert inherente chemoselectiviteit en reactiviteitverschillen, verminderend of eliminerend covalente bescherming; vereist precieze functionaalgroepvolgorde, orthogonale reactiviteit en vaak hoge-temperatuur of onconventionele voorwaarden',
        'Beschermingsgroep-vrije synthese alleen mogelijk voor natuurproducten met enkel functionaalgroep',
        'Traditionele routes universeel korter dan beschermingsgroep-vrije routes',
        'Beschermingsgroep-vrije synthese gebruikt dezelfde reagens en transformaties als traditionele synthesen, enkel benaming verschillend',
      ],
      0,
      'Beschermingsgroep-vrije synthese berust op chemoselectiviteit en reactiviteittrends, stapcount en afval verminderd. Niet beperkt mono-functionaal doelen; stapcount varieert; benadering gebruikt verschillende reagenskeuzens.',
    ],
    [
      'In asymmetrische katalyse gebruik chirale bisfosfine liganden (bijv. BINAP, DuPhos), leg oorsprong "beet hoek" uit en hoe het reactiviteit en enantioselectiviteit beïnvloedt in kruis-koppeling of hydrogeningereacties.',
      [
        'Beethoek (P-M-P) bepaalt geometrie metaal coördinatiesfeer, stuurend sterische benadering coördinatieplek en benadering oriëntatie; smalle beethoek (bijv. DuPhos) creëert beperkend zak, terwijl brede beethoek (bijv. BINAP) groter substraat benadering toestaat',
        'Beethoek bepaald zuiver lengte fosfor-bevattende linker en beïnvloedt niet reactiviteit',
        'Alle chirale bisfosfines hebben dezelfde beethoek ongeacht structuur',
        'Beethoek beïnvloedt katalysatorkleur en oplosbaarheid maar niet reactiviteit of selectiviteit',
      ],
      0,
      'Beethoek (P-M-P) bepaalt metaal coördinatiegeometrie en sterische congestie, beheerst reactiviteit en enantioselectiviteit. Linkerrigiditeit en ruggegraatgeometrie bepalen het.',
    ],
    [
      'In synthetische organische chemie, wat is doel en mechanistische voordeel gebruik "bulkige nucleofiel" of "geremd reductiemiddel" in selectieve transformatie waar kleinere nucleofiel zou lijden bijreacties?',
      [
        'Bulkige nucleofielen verminderen sterisch belemmerde of secundaire/tertiaire elektrofiele centra benadering door sterische uitsluiting, onderdrukkend ongewenste reacties minder belemmerde sites (bijv. LiAlH(OtBu)3 vs. LiAlH4 selectieve ketoon reductie aanwezigheid aldehyden of esters)',
        'Bulkige nucleofielen sneller dan kleine vanwege elektronische activering',
        'Bulkige nucleofielen kunnen sterisch belemmerde sites niet benaderen, dus gebruikt wanneer selectiviteit minder belemmerde sites gewenst',
        'Nucleofiel grootte onafhankelijk selectiviteit; alleen oplosmiddelpolariteit belang',
      ],
      0,
      'Bulkige nucleofielen vallen minder belemmerde sites aan via sterische uitsluiting (DIBAL-H, LTBA), mogend selectieve reducties. Selectiviteit ontstaat sterische congestie rond nucleofiel.',
    ],
    [
      'In context organokatalyse (imidazolidinon of thiourea katalyse), leg uit hoe waterstofbinding tussen katalysator en substraat chirale microomgeving creëert leidend hoge enantioselectiviteit zonder metaalcentrum.',
      [
        'Waterstofbinding katalysator functionaalgroepen (bijv. N-H en C=O in imidazolidinon, N-H in thioureas) naar substraat carbonyl of andere polaire groepen pre-organiseert substraat en diastereomeer onderscheidt twee enantiogezydes; overgangstoestand gestabiliseerd via laag-barrière waterstofbinding',
        'Waterstofbinding organokatalyse incidenteel en draagt niet selectiviteit bij',
        'Organokatalysatoren bereiken selectiviteit zuiver sterische bulk, geen elektrostatisch of waterstofbinding component',
        'Waterstofbinding en overgangstoestandorganisatie relevant alleen metaalkatalyse',
      ],
      0,
      'Organokatalytische waterstofbinding creëert diastereomeer substraat-katalysator complexen en stabiliseert één TS, mogend hoge ee. Waterstofbindingen en elektrostatica dominant.',
    ],
    [
      'In macrocyclische synthese en ring-sluitende metathese (RCM), leg uit hoe substraatstructuur (ringgrootte, alkeen geometrie en substitutiepatroon) RCM evenwicht en kinetiek beïnvloedt en neiging naar ongewenste oligomerisatie.',
      [
        'RCM selectiviteit beheerst Thorpe-Ingold effecten (spanning verlichting), thermodynamische alkeen productsstabiliteit en kinetiek cyclisatie relatief bimoleculeaire olefine metathese (intermoleculaire koppeling en oligomerisatie); groter, minder gespannen ringen bevoordelen RCM wanneer kinetieke factoren (intramoleculaire concentratie, chelatie) overwinnen entropie barrières',
        'Alle ringgrootten sluiten gelijk efficiënt in RCM',
        'RCM oligomerisatie onvermijdbaar en kan niet onderdrukt substraatontwerp',
        'Alkeen geometrie (E/Z) irrelevant RCM selectiviteit en productdistributie',
      ],
      0,
      'RCM succes hangt Thorpe-Ingold spanningsverlichting, TS geometrie en intramoleculaire kinetieke voordeel af. Oligomerisatierisico schaalt substraatconcentratie.',
    ],
    [
      'In totaalsyntheseplanning, wat onderscheidt "sleutel strategische transformatie" van routine stap, hoe leidt dit retrosyntetische analyse?',
      [
        'Sleuteltransformatie creëert meerdere stereocentra of complexe ringsystemen één stap; ontdekking bepaalt vaak gehele synthetische strategie en maakt mogelijk kortere routes ondanks matige opbrengst',
        'Sleuteltransformaties altijd finale stappen synthese',
        'Alle transformaties gelijk belangrijk in routeoptimalisatie',
        'Sleuteltransformaties moeten reacties goed-gevestigd literatuur met >95% opbrengst',
      ],
      0,
      'Sleutelstrategische transformaties creëren complexiteit efficiënt (stereocentra, ringen); bepalen strategie zelfs niet finale stappen of perfect hoge-opbrengst. Routine stappen gebouwd op gevestigde kennis.',
    ],
    [
      'In fotochemische organische synthese, leg verschil uit tussen Type I en Type II fotochemische mechanisme in termen fotogeiniteerde intermediaten en selectiviteit uitkomsten.',
      [
        'Type I (radicaalspad): aangeslagen staat haalt H af of fragmentatie geeft radicalen; Type II (energieoverdracht): aangeslagen staat overdraagt energie grondtoestand substraat of triplet-zuurstof, genererend singlet-zuurstof soorten of substraat triplet',
        'Beide typen genereren identieke producten en verschillen enkel mechanisme nomenclatuur',
        'Type I vereist zichtbaarlicht; Type II vereist UV licht',
        'Type II sneller omdat singlet-zuurstof reactiever radicalen',
      ],
      0,
      'Type I fotochemie: aangeslagen staat genereert radicalen (H-afleiding, fragmentatie). Type II: aangeslagen staat overdraagt energie (bijv. O₂, singlet-zuurstofvorming). Verschillende mechanismen, selectiviteit.',
    ],
    [
      'In enzymatische katalyse toegepast organische synthese, wat voordeel geleide evolutie enzymen boven engineeren enkele actieve plaats op structuur voorspellingen?',
      [
        'Geleide evolutie bemonstert uit sequentiereeks iteratief, identificerend varianten verbeterde keersnelheid, substraat bereik of nieuwe selectiviteit zonder structuurkennis; mutagenese screening verslaat rationaal ontwerp niet-intuïtieve oplossingen',
        'Geleide evolutie langzamer en minder efficiënt rationaal ontwerp',
        'Rationaal ontwerp vindt altijd optimaal enzymvarianten eerst',
        'Geleide evolutie kan niet enantioselectiviteit bereiken voorbij start enzym',
      ],
      0,
      'Geleide evolutie (mutagenese + screening) bemonstert sequentieruimte empirisch, vaak niet-voor-de-hand-liggende oplossingen vinden rationaal ontwerp overwinnend. Mogelijk substraatbereik expansie en geheel nieuwe selectiviteit.',
    ],
    [
      'In groene chemie en atoomeconomie, hoe "atoomeconomie" concept verschilt van "opbrengst" in evalueren milieugunstigheid synthese route?',
      [
        'Atoomeconomie meet fractie atomen uit startmaterialen geïncorporeerd eindig product (theoretisch max 100%); opbrengst meet percentage theoretisch product verkregen. Beide essentieel—hoge atoomeconomie met lage opbrengst verspilt atomen en oplosmiddel; lage atoomeconomie verspilt grondstof ondanks opbrengst',
        'Atoomeconomie en opbrengst identieke termen',
        'Opbrengst belangrijker atoomeconomie omdat hoge opbrengst minimaal afval betekent',
        'Atoomeconomie irrelevant wanneer reactie uitgevoerd groene oplosmiddel',
      ],
      0,
      'Atoomeconomie (fractie startingsatomen eindproduct, theoriegebaseerd) en opbrengst (werkelijk vs. theoretisch, experiment-gebaseerd) orthogonale metrieken. Beide belang evalueren groene chemie.',
    ],
  ],
};
