import type { CategoryContent } from '../row.js';

export const PAINTERS: CategoryContent = {
  bscba: [
    [
      'Welke Renaissanceschilder staat vooral bekend om zijn gedetailleerde koepelfrescans in de Brancacci-kapel?',
      [
        'Masaccio',
        'Rafaël',
        'Donatello',
        'Ghirlandaio',
      ],
      0,
      'Masaccio\'s werk in de Brancacci-kapel (1425–1428) pionierde lineair perspectief en anatomische nauwkeurigheid, wat hem tot een fundamentale figuur in de Renaissancekunst maakte.',
    ],
    [
      'Welke schildertechniek bestaat uit het aanbrengen van pigment op nat pleisterwerk, dat tijdens het drogen chemisch bindt?',
      [
        'Fresco',
        'Tempera',
        'Encaustiek',
        'Glazuren',
      ],
      0,
      'Fresco (Italiaans: "vers") is de enige schildertechniek waarbij pigment onderdeel wordt van het pleisterwerk zelf, wat het zeer duurzaam maakt maar geen fouten toelaat.',
    ],
    [
      'Welke beweging uit de late 19e eeuw gaf prioriteit aan licht, kleur en het voorbijgaande moment boven narratieve details?',
      [
        'Impressionisme',
        'Romantiek',
        'Symbolisme',
        'Barok',
      ],
      0,
      'Impressionisten als Monet en Renoir verbraken met de academische traditie door buiten te schilderen en vorm op te lossen in kleur- en lichteffecten.',
    ],
    [
      'Wie schilderde "De sterrenhemel"?',
      [
        'Vincent van Gogh',
        'Paul Cézanne',
        'Henri de Toulouse-Lautrec',
        'Édouard Manet',
      ],
      0,
      'Van Goghs meesterwerk uit 1889 gebruikt wervelende penseelstreken en levendige kleuren om een nachtelijke hemel boven een Frans dorp uit te beelden, wat Post-Impressionisme belichaamt.',
    ],
    [
      'Welke doorzichtige verflaag, aangebracht over droog onderwerk, voegt glans en diepte toe?',
      [
        'Glanslaag',
        'Impasto',
        'Scumble',
        'Grisaille',
      ],
      0,
      'Glazuren bestaan uit dunne, doorschijnende verflagen die onderliggende lagen zichtbaar laten worden, wat optische kleurmengeling en diepte in oude meesters creëert.',
    ],
    [
      'Wat is het voornaamste drageroppervlak voor de meeste Europese olieverfschilderijen sinds de Renaissance?',
      [
        'Canvas',
        'Houten paneel',
        'Koperen plaat',
        'Perkament',
      ],
      0,
      'Canvas werd na circa 1500 standard voor olieverfschilderijen omdat het goedkoper was dan houten panelen, lichter en gemakkelijker te vervoeren en op te slaan.',
    ],
    [
      'Welke kunstbeweging verwerkte het academische naturalisme af en koos voor emotionele expressie en levendige, niet-natuurlijke kleuren?',
      [
        'Expressionisme',
        'Realisme',
        'Neoclassicisme',
        'Academicisme',
      ],
      0,
      'Expressionisten (vroege 20e eeuw) als Kirchner en Kandinsky gaven prioriteit aan subjectief gevoel en vervormde vorm om psychologische toestanden uit te drukken.',
    ],
    [
      'Wie schilderde "De geboorte van Venus"?',
      [
        'Sandro Botticelli',
        'Leonardo da Vinci',
        'Michelangelo',
        'Brunelleschi',
      ],
      0,
      'Botticelli\'s meesterwerk uit circa 1485, in de Uffizi Gallery, belichaamt Renaissanceschoonheid met vloeiende lijnen en mythologische onderwerpen.',
    ],
    [
      'Welke vroege temperatechniek gebruikte eigeel als bindmiddel en produceerde matte afwerkingen?',
      [
        'Eitemperatechniek',
        'Olie-alkyd',
        'Acryl',
        'Fresco secco',
      ],
      0,
      'Eitemperatechniek was voor de Renaissance het dominante medium; pigmenten gemengd met eigeel droogden snel en konden niet als olieverf mengen.',
    ],
    [
      'Welke kunstbeweging uit de 17e eeuw dramatiseerde licht en schaduw voor emotionele intensiteit?',
      [
        'Barok',
        'Rococo',
        'Manierisme',
        'Hoge Renaissance',
      ],
      0,
      'Barokkunstenaars als Caravaggio gebruikten chiaroscuro (sterke licht-donkercontrasten) en dynamische compositie om theatrale, emotioneel geladen scènes te creëren.',
    ],
    [
      'Wat is de dikke, zichtbaar getextureerde verfaanbreng die fysieke dimensie op canvas creëert?',
      [
        'Impasto',
        'Sfumato',
        'Chiaroscuro',
        'Pentimento',
      ],
      0,
      'Impasto is zichtbare penseelwerk of palet-mesaanbreng waarbij verf dik op het oppervlak ligt, licht vangt en tactiele textuur creëert.',
    ],
    [
      'Wie is de Nederlandse Post-Impressionist vooral beroemd om zijn zonnebloem- en graanveldschilderijen?',
      [
        'Vincent van Gogh',
        'Paul Gauguin',
        'Georges Seurat',
        'Edvard Munch',
      ],
      0,
      'Van Gogh creëerde zijn zonnebloemenreeks in Arles, Frankrijk (1888–1889); de schilderijen gebruiken symbolisme en expressieve kleur om schoonheid uit te drukken.',
    ],
    [
      'Welk compositieprincipe plaatst het onderwerp buiten het centrum op ongeveer een derde van het beeld?',
      [
        'Derdelingenregel',
        'Gulden snede',
        'Lineair perspectief',
        'Bilaterale symmetrie',
      ],
      0,
      'De derdelingenregel, afgeleid van Renaissanceproporties, creëert visueel evenwicht door brandpunten weg van het centrum te plaatsen.',
    ],
    [
      'Welke Italiaanse Renaissancemeester schilderde "De School van Athene" in het Vaticaan?',
      [
        'Rafaël',
        'Michelangelo',
        'Leonardo da Vinci',
        'Botticelli',
      ],
      0,
      'Rafaël\'s monumentale fresco (1509–1511) in de Vaticaanse Stanza della Segnatura stelt klassieke filosofen voor in harmonieuze Renaissancecompositie.',
    ],
    [
      'Welke term beschrijft de geleidelijke, bijna onzichtbare menging van tonen voor zachte overgangen?',
      [
        'Sfumato',
        'Chiaroscuro',
        'Tenebrisme',
        'Pointillisme',
      ],
      0,
      'Sfumato, gepioneerd door Leonardo da Vinci, vervaagt randen en tonen zo subtiel dat omlijningen lijken op te lossen, wat atmosferisch perspectief creëert.',
    ],
  ],
  msc: [
    [
      'In vroeg Nederlands schilderwerk stond welke revolutionaire techniek schilders toe om doorschijnende olieverglazuren met ongekende helderheid te stapelen?',
      [
        'Opeenvolgende dunne olieglazuren',
        'De Venetiaanse methode van tempera onder olie',
        'Het gebruik van walnootolie in plaats van lijnzaadolie',
        'Het voormengen van pigmenten met gemalen glas',
      ],
      0,
      'Jan van Eyck en zijn tijdgenoten perfectioneerden de olieverglazuurtechniek, wat minuscule detail en juweelachtige kleur toestond die tempera niet kon evenaren.',
    ],
    [
      'Wat vereist "sfumato" technisch dat "chiaroscuro" niet vereist?',
      [
        'Onwaarneembare toonovergangen',
        'Dramatisch contrast tussen licht- en schaduwzones',
        'Een koele tint in schaduw en warm in licht',
        'Meerdere voorbereidende ondertekenigen',
      ],
      0,
      'Sfumato vereist optische menging waarbij tonen zo soepel overgaan dat randen verdwijnen; chiaroscuro tolerantieert zichtbare schaduwgrenzen, wat sfumato technisch veeleisender maakt.',
    ],
    [
      'Welke Italiaanse meester\'s werkplaats perfectioneerde de techniek waarbij leerlingen composities aanlegden terwijl de meester gezichten verfijnde?',
      [
        'Rafaël',
        'Michelangelo',
        'Caravaggio',
        'Parmigianino',
      ],
      0,
      'Rafaël\'s werkplaats werkte volgens arbeidsverdeling; zijn leerlingen (Giulio Romano, Giovanni da Udine) voerden voorbereiding uit, wat commissies versnelde.',
    ],
    [
      'Wat is de standaard voorbereidende laag voor olieverfschildering op canvas die de weving afdicht en een stabiele ondergrond vormt?',
      [
        'Gesso',
        'Vernis',
        'Alleen lijnzaadolie',
        'Wit loodverf',
      ],
      0,
      'Gesso, een traditionele grond van calciumsulfaat en dierlijke lijm, creëert een niet-absorberend oppervlak dat olie absorptie in canvas vezelavoorkomen en verfafzetting waarborgt.',
    ],
    [
      'In Renaissanceperspectiefleer, wat is het verdwijnpunt waar orthogonale lijnen in lineair perspectief convergeren?',
      [
        'Waar parallelle lijnen samenkomen op de horizon',
        'Het verst zichtbare object in het schilderij',
        'Het helderste gebied van de compositie',
        'Het precieze midden van het canvas',
      ],
      0,
      'Het verdwijnpunt, mathematisch bepaald door Brunelleschi en getheoreerd door Alberti, creëert illusie van driedimensionale ruimte op vlak oppervlak.',
    ],
    [
      'Welke Venetiaanse meester uit de 16e eeuw pionierde het creëren van vorm vooral door kleur in plaats van lijn?',
      [
        'Titiaan',
        'Tintoretto',
        'Veronese',
        'Paolo Uccello',
      ],
      0,
      'Titiaan ontwikkelde de "malerische" benadering, benadrukkend kleurarmonieën en penseelwerk boven precieze tekenwerk, wat alle volgende Europese tradities beïnvloedde.',
    ],
    [
      'Waar verwijst "pentimento" naar in bewaarings- en kunstgeschiedenis?',
      [
        'Een spoor van een eerdere compositie',
        'Een scheur in oude verf veroorzaakt door temperatuursverandering',
        'De handtekening of monogram verborgen in een schilderij',
        'Het verwijderen van vernis tijdens restauratie',
      ],
      0,
      'Pentimento (Italiaans: "berouw") toont de tweede gedachte van een kunstenaar; röntgenfotografie onthult vaak eerdere compositionele versies onder de uiteindelijke verflagen.',
    ],
    [
      'Welke Noord-Renaissance schilder ontwikkelde de techniek van witte lijnranden rond figuren om omtrek te versterken?',
      [
        'Albrecht Dürer',
        'Lucas Cranach',
        'Matthias Grünewald',
        'Hans Burgkmair',
      ],
      0,
      'Dürer paste deze techniek uit Vlaamse praktijk aan, waarbij fijne witte of heldere omlijningen randen scherp definiëren, karakteristiek voor Noord-Renaissance panelen.',
    ],
    [
      'Wat is de dunne onderchilderingslaag in olieverfschildering, vaak in monochroom, die tonale waarden en vorm bepaalt?',
      [
        'Onderverf',
        'Imprimatura',
        'Glanslaag',
        'Waterkleur',
      ],
      0,
      'Onderchildering kaart waarden en compositie uit voordat glazuren; sinopia (voor fresco) is de voorbereidende tekening op de arriccio die het fresco werk leidt.',
    ],
    [
      'Welke Barok schilder pionierde "tenebrisme," een extreme vorm van chiaroscuro met vrijwel hele scènes in duisternis?',
      [
        'Caravaggio',
        'Artemisia Gentileschi',
        'Rembrandt',
        'Peter Paul Rubens',
      ],
      0,
      'Caravaggio\'s tenebrisme isoleert verlichte figuren tegen bijna totale duisternis, wat psychologisch drama en theatrale lichtleiding creëert.',
    ],
    [
      'Wat is "distemper"-schildering, een techniek verschillend van tempera, en waar werd het historisch vooral gebruikt?',
      [
        'Waterbasis verf op lijmbasis',
        'Een techniek met ei en olie gecombineerd',
        'Een fresco-variant met kalk en zand',
        'Een encaustiek-tempera hybride uit 15e-eeuws Italië',
      ],
      0,
      'Distemper (lijmbasis) werd waardevol voor toneeldecoratief werk en decoratieve muurschilderingen waar duurzaamheid minder kritisch was; het blijft vergankelijk.',
    ],
    [
      'In Hoge Renaissance-compositie, wat is het principe van "figura serpentinata" of de serpentijnvormige figuur?',
      [
        'Een verlengde, zwiepende figuurhouding',
        'Een geometrische regeling van meerdere figuren in diagonale lijnen',
        'De plaatsing van figuren in strikte bilaterale symmetrie',
        'Het gebruik van groene en blauwe tonen voor visuele serpentijnpatronen',
      ],
      0,
      'Serpentijnfiguren, exemplarisch in Manierisme, gebruiken zwierige contrapposto die het lichaam verlengt en krult voor elegante, dynamische composities.',
    ],
    [
      'Wat is de voornaamste reden waarom Renaissance en Barok schilders lijnzaadolie boven andere bindmiddelen voorkeurden?',
      [
        'Het droogt door oxidatie tot een harde, duurzame laag',
        'Het droogt sneller dan walnootolie',
        'Het voorkomt scheurvormming beter dan andere oliën',
        'Het produceert een glanzend oppervlak zonder extra vernis',
      ],
      0,
      'Lijnzaadolie oxideert (polymeriseert) met gecontroleerde snelheid, wat een sterke, flexibele film creëert die niet significant verdonkert; andere oliën werden vermeden vanwege mindere duurzaamheid.',
    ],
    [
      'Welk iconografisch symbool verschijnt herhaaldelijk in Noord-Renaissance schilderwerk om goddelijke aanwezigheid te vertegenwoordigen?',
      [
        'Gouden achtergrond',
        'De afwezigheid van schaduwen',
        'Exclusief rood pigment',
        'Waterweerspiegelingen',
      ],
      0,
      'Goudfolie en goudverf achtergronden, een Middeleeuwse erfenis in Noord-Renaissance, betekenden heilige ruimte en het onwezenlijke goddelijke, onderscheiden van aardse naturalisme.',
    ],
    [
      'Waar slaat "intonaco" op in fresco-techniek en waarom is de kwaliteit ervan kritiek?',
      [
        'De laatste natte pleisterlaag',
        'De voorbereidende houtskool onderteekening',
        'De droge zand- en kalkmortelgrondlaag',
        'Het kleurpigment gemengd in pleisterwerk',
      ],
      0,
      'Intonaco moet gelijkmatig gehydrateerd en dun genoeg zijn voor chemische binding; mindere kwaliteit voorkomt juiste pigmentafzetting, wat fresco vervalt en afschilfers.',
    ],
  ],
  phd: [
    [
      'Verklaar in Laat-Gotisch en Vroeg-Nederlands schilderwerk de overgang van tempera naar olie en implicaties voor sculpturaal illusionisme.',
      [
        'Trage droging en transparantie gaven gelaagde optische diepte',
        'Tempera droogde te snel, wat gedetailleerde onderchildering voor anatomie voorkwam',
        'Oliepigmenten waren chemisch simpelweg levendiger dan temperaatpigmenten',
        'Olie stelde kunstenaars in staat grotere canvas dan tempera ondersteuning te schilderen',
      ],
      0,
      'Vlaamse meesters als Rogier van der Weyden gebruikten olieverglazuren om vorm subtiel door kleur zonder lijn te modelleren, sculpturaal driedimensionaal effect bereikend.',
    ],
    [
      'Wat onderscheidt Titiaan\'s late "gebroken kleur"-techniek van vroegere Venetiaanse kleurfocus qua penseelwerk en optische mengling?',
      [
        'Zichtbare streken die optisch mengen in het oog',
        'Vroeg-Titiaan mengde alle kleuren volledig op de palet',
        'Gebroken kleur vereist zichtbare monochroom onderchildering',
        'De techniek is louter pigmentkeuze, geen toepassingsmethode',
      ],
      0,
      'Titiaan\'s laat-werken passen verf los aan in parallelle streken waar kleuren in het oog van beschouwer mengen; deze optische benadering beïnvloedde coloristen eeuwen later.',
    ],
    [
      'Verklaar de scheikunde waarom loodwit universeel werd gekozen boven ander wit in oude meester olieverfschildering ondanks bekende toxiciteit.',
      [
        'Het oxideert snel en droogt zonder te vergelen',
        'Het reflecteert meer licht dan ander pigment',
        'Het was het enige beschikbare witte pigment in Renaissance Europa',
        'Het voorkomt scheuren in het schilderij door tijd',
      ],
      0,
      'Loodwit oxideert snel met warmte, wat verffilmvorming versnelt en vergeling voorkomt die ander wit vertoonde; toxiciteit werd acceptabel geacht gegeven superieur rendement.',
    ],
    [
      'In Hoge Renaissance narratieve compositie, welk structuurprincipe gebruikte Rafaël om meerdere brandpunten te verenigen zonder hiërarchische overheersing?',
      [
        'Driehoekige figuurgroepering met gestaffelde diepten',
        'Centraal verdwijnpunt waarvan alle elementen uitstralen',
        'Volledige symmetrie rond vertikale as',
        'Diagonale horizon lijnen aandacht naar linksboven forcerend',
      ],
      0,
      'Rafaël\'s driehoekige figuurschikkingen (zichtbaar in Vaticaanfrescans) leiden oog door onderling verbonden vlakken; deze geometrische harmonie werd canonieke Renaissance-compositie.',
    ],
    [
      'Wat is de specifieke rol van "arriccio" en "sinopia" lagen in echte frescotech niek en hoe beïnvloeden zij artistieke werkflow?',
      [
        'Arriccio ontvangt de sinopia-onderteekening',
        'Zij zijn dezelfde laag met verschillende namen',
        'Slechts één wordt gebruikt in Klassiek Romeins fresco',
        'Zij worden aangebracht nadat de geverfd laag droogt',
      ],
      0,
      'Sinopia op arriccio stelt kunstenaar in staat compositie gedetailleerd te plannen; zodra intonaco aangebracht, veranderingen onmogelijk, sinopia essentiële planningsfase.',
    ],
    [
      'Bespreek hoe Noord-Renaissance schilders atmosferisch perspectief door kleurgradiëring anders inbouwden dan Italiaans lineair perspectief.',
      [
        'Blauwgrijze tinting in de verte',
        'Zij gebruikten dezelfde technieken als Italiaanse schilders',
        'Noord-schilders verworpen perspectief totaal',
        'Alleen Italiaanse schilders begrepen kleurperspectief',
      ],
      0,
      'Noord-Renaissance gebruikte kleurafdracht naar koelere tonen en lagere verzadiging voor afstand, perspectief optisch bereikend; dit complementeerde in plaats van vervangend lineair perspectief.',
    ],
    [
      'Wat is "fustaanbekleding" in historische verfterminologie en welk pigmentinstabiliteit droeg het risico?',
      [
        'Kleurstoffen die onvoorspelbaar vervagen',
        'Een technische term voor impasto aanbreng',
        'Een specifiek bindmiddel van katoen',
        'Een archaïsche term voor glazuurtech niek',
      ],
      0,
      'Fustaanpigmenten (organische lacken als meekrap) zijn vergankelijk; handelaren verkochten soms als permanente pigmenten, wat kleurverlies als tintverschuivingen in oude schilderijen veroorzaakte.',
    ],
    [
      'Verklaar de technische reden waarom Caravaggio\'s tenebrisme specifieke studiolichting en verfformule innovaties vereiste.',
      [
        'Snel-droogende, dekkende verf met hoge tintingskracht',
        'Hij vond specifiek tenebrisme pigment uit',
        'De techniek vereiste alleen donkerder pigmenten, geen speciale formulering',
        'Het was louter onderwerpkwestie, geen technische aanpassing',
      ],
      0,
      'Caravaggio\'s hoog-contrast stijl vereiste zelfverzekerde waardeplaatsing van start; hij gebruikte loodwit royaal en werkte onder directioneel studiolight.',
    ],
    [
      'Wat onthult röntgenfotografie over Rembrandt\'s correctiepatro nen wat suggest een doelbewust revisieaanpak verschillend van andere Barok schilders?',
      [
        'Uitgebreide, methodische pentimenti',
        'Rembrandt maakte nooit correcties',
        'Zijn pentimenti zijn willekeurig en onvoorzichtig',
        'Röntgenfotografie kan Rembrandt\'s technieken niet onthullen',
      ],
      0,
      'Röntgenstralen tonen Rembrandt\'s systematische heropposing van figuren en gesturherkalibrering; dit suggereert generatief proces favoring spontane revisie boven vaste voorbereiding.',
    ],
    [
      'In Barok ikonografie, verklaar de symbolische functie van specifieke kleurreeksen (bijv. rood-blauw-goud) in Mariële beelden.',
      [
        'Passie (rood), deugd (blauw), majesteit (goud)',
        'Kleuren waren willekeurig zonder symbolische betekenis',
        'Alleen blauw had religieuze betekenis',
        'Kleuursymboliek veranderde elk eeuw zonder consistent heid',
      ],
      0,
      'Mariële kleursymboliek werd gecodificeerd in Middeleeuwse en Renaissance ikonografische teksten; rood-blauw-goud combinaties verschenen doelbewust theologische betekenis visueel vast te leggen.',
    ],
    [
      'Wat bewijs bewarengenomen (craquelure patronen, verflaagsamenstelling) onthult over verschil tussen authentieke Oude Meesters en 18e-eeuwse kopieën of veranderingen?',
      [
        'Leeftijdspecifieke craquelure bij de periode',
        'Alle oude schilderijen hebben identieke craquelure',
        'Craquelure is louter decoratief en betekenisloos',
        'Bewaartechnieken kunnen vervalsingen niet detecteren',
      ],
      0,
      'Leeftijd-specifieke craquelure, pigmentbeschikbaarheid tijdlijnen en bindmiddel-oxidatiepatronen bieden chronologische vingerafdrukken; anachronismen ontmaskeren kopieën of uitgebreide latere herzieningwerk.',
    ],
    [
      'Verklaar hoe de theoretische herontdekking en toepassing van Vitruuviaanse verhoudingen in Renaissance schildering afweek van Middeleeuwse geometrische schema\'s.',
      [
        'Vitruviaanse verhoudingen uit anatomie, niet symbolische meetkunde',
        'Beiden zijn identiek',
        'Vitruviaanse verhoudingen werden in Renaissance uitgevonden zonder klassieke bron',
        'Middeleeuwse schilders gebruikten nooit geometrische schema\'s',
      ],
      0,
      'Brunelleschi en Alberti pasten Vitruvius\'s mensgebonden verhoudingen toe (bijv. 1:2:3 spacing), die Middeleeuwse symbolische geometrie vervingen met op waargenomen anatomische harmonie gebaseerde ratio\'s.',
    ],
    [
      'In de restauratie van een Barok canvas, welk bewijs zou onderscheid maken tussen originele verf, vroege vernisvergelingen en latere hertekeningen?',
      [
        'IR en UV tonen vernisouderdom en hertekening',
        'Er is geen manier om deze te onderscheiden',
        'Alle oude schilderijen zien er identiek uit onder beeldvorming',
        'Alleen chemische analyse werkt, beeldvorming helpt niet',
      ],
      0,
      'IR toont originele verf\'s rijpheid, UV fluorescense markeert moderne hertekenmaterialen, stratigrafische analyse onthult vernislagen; deze diagnostische tools combineren restauratiegeschiedenis in kaart.',
    ],
    [
      'Wat beschrijft de dichotomie "Venetiaans colorisme" tegenover "Florentijnse tekening" in Renaissance kunstkritiek in termen van onderliggende artistieke filosofie?',
      [
        'Florentijnse lijnvorm versus Venetiaanse kleurharmonie',
        'Venetiaanse schilders waren slechter in tekenen dan Florentijnse schilders',
        'Het is louter geografische gemak zonder filosofische grondslag',
        'Beide scholen gebruikten identieke methoden',
      ],
      0,
      'De dichotomie weerspiegelt Renaissance humanisme\'s intellect- versus zintuigpolaire: Florence benadrukte rationale ontwerp (disegno), Venetië vierde optische kleur en visueel genoegen (colorito).',
    ],
    [
      'Verklaar het technische doel van "waterverf"-lagen in aquarel- en gouachevoorbereiding wat hen onderscheidde van tempera en olie-technieken.',
      [
        'Waterverflagen vereisen absorberend papier, geen gesso',
        'Waterverflagen zijn identiek aan glazuren',
        'Aquarel en gouache zijn oliën',
        'Waterverftech niek vereist loodwit als olieverfschildering',
      ],
      0,
      'Papierabsorptie stelt transparante waterverflagen toe snel te drogen en optisch te mengen; gesso-gebonden panelen van tempera en olie vereisen mechanische mengling, niet optische lagen.',
    ],
  ],
  professor: [
    [
      'Analyseer kritisch hoe de moleculaire polymerisatiekinetiek van verschillende bindmiddelen (walnut vs. lijnzaad vs. saffraan oliën) de haalbaarheid van specifieke Venetiaanse coloristtechnieken bepaalde.',
      [
        'Lijnzaads trage oxidatie maakte gelaagde natte menging mogelijk',
        'Alle oliën polymeriseren identiek',
        'Pigmentkleur bepaalt bindmiddelgedrag',
        'Oliekeuse was louter esthetisch zonder technische gevolg',
      ],
      0,
      'Walnut\'s snelle polymerisatie en saffraan\'s slecht drogen maakten ze ongeschikt voor optische natte-blending; lijnzaad\'s controleerbare kineti ek ondersteunde Venetiaanse gebroken-kleur effecten onmogelijk in ander medium.',
    ],
    [
      'Bespreek hoe fresco\'s afhankelijkheid van kalkkarbonatisering als bindmechanisme onomkeerbare compositiekeuzen oplegde en Noord-Renaissance verwerping van de techniek vormde.',
      [
        'Fresco\'s onomkeerbare binding dreef schilders naar olie',
        'Fresco is onderworpen duurzamer dan olie',
        'Noord-schilders kozen gewoon olie om esthetische redenen',
        'Fresco karbonatisering is ogenblikkelijk en omkeerbaar',
      ],
      0,
      'Zodra intonaco instelde, pentimenti waren onmogelijk; olie\'s herzienbaarheid (drogen staat raspening en overchildering toe) aligneerde met Renaissance klemtoon op intellectuele verfijning en werkplaatsarbeidsverdeling.',
    ],
    [
      'In hedendaagse bewaringswetenschappen, verklaar het epistemologische probleem van schilderijtoewijzing via pigmentanalyse wanneer post-productieveranderingsgeschiedenis onbekend is.',
      [
        'Pigmentanalyse bewijst geen authenticiteit alleen',
        'Pigmentanalyse bewijst definitief autheurschap',
        'Moderne pigmenten bevinden zich nooit in oude schilderijen',
        'Gewijzigde schilderijen tonen altijd zichtbare getuigenissen',
      ],
      0,
      'Pigmentanalyse biedt getuigenissen (anachronistische lapis lazuli suggereert 20e-eeuwse hertekening) maar kan authenticiteit alleen niet bewijzen; fragmentarische restauratiedocumentatie verergert epistemologische onzekerheid.',
    ],
    [
      'Analyseer hoe Caravaggio\'s technische keuzes (specifieke loodwit opaciteit, snel-instelling formulering, éénzitting uitvoeringsstrategie) zijn conceptuele vormmodelleringbenadering weerspiegelden en beperkten.',
      [
        'Hoog loodwit maakte gedurfde modellering mogelijk',
        'Caravaggio gebruikte standaard Renaissance-technieken',
        'Technische keuzes hadden geen relatie met zijn esthetiek',
        'Caravaggio gebruikte altijd traag-droogende oliën',
      ],
      0,
      'Caravaggio\'s gedocumenteerde snelle uitvoering (vaak éénzitting) vereiste hoog-opaciteit, snel-droogende verf; deze technische beperking dwong directe, emotioneel onmiddellijke licht-schaduw modellering zonder verfijningsglazen af.',
    ],
    [
      'Wat onthullen recente neutronactiveringsanalyses van Rembrandt\'s late werken over zijn sourcing van zeldzame-aarddelementenrijke okers en verhouding tot stilistische evolutie?',
      [
        'Sporen lanthanide wijzen op fijnere, later geïmporteerde okers',
        'Neutronanalyse kan sporelementen niet detecteren',
        'Rembrandt\'s pigmentbronnen veranderden nooit',
        'Aarddelementelsamenstelling is irrelevant voor kleurverschijning',
      ],
      0,
      'Neutronactivering detecteerde verschoven zeldzame-aarde profielen in Rembrandt\'s late werken; deze alignen met gedocumenteerde verhoogde import premium okers naar Amsterdam, stylistische datering en bronsingshypothesen ondersteunend.',
    ],
    [
      'Kritiseer de interpretatieve limieten van Panofsky\'s drieledige ikonografische methodologie op 15e-eeuws Nederlands schilderwerk gegeven opkomend getuigenis van werkplaatsspecifieke symbolische codes.',
      [
        'Gildes hadden codes die Panofsky miste',
        'Panofsky\'s methode is universeel toepasselijk',
        'Werkplaatsen ontwikkelden nooit unieke symbolische codes',
        'Ikonografie is irrelevant voor schilderijnanalyse',
      ],
      0,
      'Gildespeficitieke heraldrie en patroon-familiesymbolische voorkeuren creëerden gelokaliseerde ikonografische "dialecten"; Panofsky\'s gegeneraliseerde lezing mist deze doelbewuste, ondocumenteerde werkplaats-level betekenissen.',
    ],
    [
      'Analyseer de theoretische implicaties van "kunsthistorisch subliem" zoals geformuleerd in laat-18e-eeuwse landschapschildering en verhouding tot gelijktijdige Kantiaanse esthetica.',
      [
        'Turner en Friedrich visualiseerden Kant\'s sublieme',
        'Kant\'s esthetica hebben geen verbinding met schildering',
        'Het sublieme in kunst voorafgaat Kant',
        'Landschapschilders engageerden zich nooit met filosofie',
      ],
      0,
      'Turner en Friedrich\'s composities belichamen doelbewust Kantiaans subliem: overweldigende schaal, vormeloze vastheid en menselijke onbetekenisheid visualiseren Kant\'s fenomenologische beschrijving van wiskundig/dynamisch subliem.',
    ],
    [
      'In de historiografie van kunsthistorische methodologie, verklaar hoe formalistische abstractie van ikonografie (Fry, Greenberg) paradoxaal interpretatie van abstracte en niet-representationele werken mogelijk maakte en beperkte.',
      [
        'Formalisme sloot historische context uit',
        'Formalisme en abstractie zijn ongerelat',
        'Formalisme maakte alle historische interpretaties gelijk mogelijk',
        'Abstracte schilderij vereiste geen kritische methodologie',
      ],
      0,
      'Formalisme bevrijdde abstracte kunst van ikonografisch decoderen (nodig) maar dogmatisch exclusief historische, biografische en materiële contexten (beperkend); deze methodische asymmetrie vormt nog hedendaagse abstractiekritiek.',
    ],
    [
      'Wat onthult röntgenstraldiffractie-kristallografie van middeleeuwse vergulde oppervlakken over regionale onderscheidingen in goudslaan en bladdikte wat traditionele kunstgeschiedenis niet kan benaderen?',
      [
        'Italiaans goud is grover dan Vlaams',
        'Al middeleeuws goudblad is identiek',
        'Röntgenstraldiffractie kan goudkenmerken niet meten',
        'Goudslaa ntechniek was nooit regionaal onderscheiden',
      ],
      0,
      'XRD toont Italiaans goud vertoont groverekristallografie (dikker slaan, minder verfijning), terwijl Vlaams goud fijner is (arbeidsintensief); deze technische handtekeningen spiegelen werkplaatsmiddelen en handelsnetwerktoegang.',
    ],
    [
      'Bespreek hoe scholaratische hertoewijzing van werken voormalig aan Artemisia Gentileschi toegerekend epistemologische verschuivingen vereiste in hoe geslacht, archiefsafwezigheid en stilistieke analyse intersectaken.',
      [
        'Archieven verhulden haar; studie herstelde haar werk',
        'Gentileschi\'s werk werd altijd correct toegerekend',
        'Geslacht beïnvloedt nooit kunsthistorische toewijzing',
        'Archiefetuigenissen zijn irrelevant voor toewijzing',
      ],
      0,
      'Gentileschi\'s herstel hing af van archiefondezoek (genegeerde commissiedocumenten), formale analyse (haar distinctieve chiaroscuro en figurale energie) en feminist historiografie te integreren om mistoeschrijving af te breken.',
    ],
    [
      'Analyseer de technische en conceptuele betekenis van "tempera-olie emulsie"-praktijk in 15e-eeuws Vlaams schilderwerk als transitietechnologie discretemediaclassificaties overbruggend.',
      [
        'Hybrides mengden de voordelen van elk medium',
        'Tempera en olie werden nooit gemengd',
        'Emulsietechniek werd in 19e eeuw uitgevonden',
        'Mediahybriditeit heeft geen technische betekenis',
      ],
      0,
      'Nederlands schilders mengden experimenteel tempera en olie, elk voordeel exploiteerend (snel-instelling tempera onderchildering, olie glazuurverfijning); technologische pragmatisme trompetteerde ideologische puurheid.',
    ],
    [
      'In hedendaagse bewaringscthica, bespreek de interpretatieve en filosofische inzetten van kiezen tussen herzienbaarheid en esthetische interventie in "hertekening" van significante verfverlies.',
      [
        'Herzienbaarheid houdt opties open',
        'Herzienbaarheid is altijd ethisch superieur',
        'Esthetische voltooiing is altijd correct',
        'Bewaringscethica zijn irrelevant voor schilderijarestauratie',
      ],
      0,
      'Herzienbaarheid bewaart toekomstige herundezoek maar aanvaardt esthetische incompleteness; integratie riskeert getuigenis obfuscatie en legt present-smak als historische feit af. Dit dilemma heeft geen universele oplossing.',
    ],
    [
      'Hoe beïnvloedt het optische fenomeen "halatie" (licht passerend door transparante verflagen en terugkaatsend) de fenomenologische ervaring van oude meester-geglazuurde oppervlakken in galerieverlichting contexten?',
      [
        'Lichtverstrooiing creëert een hoekafhankelijke gloed',
        'Halatie is een fotografisch artefact irrelevant voor schildering',
        'Geglazuurde oppervlakken zijn optisch statisch',
        'Galerielichting heeft geen effect op waarneming',
      ],
      0,
      'Halatie produceert de optische "gloed" waarnemers in Oude Meesters rapporteren; licht binnengaat transparante glazuren, intern reflecteert, uitgangt onder verande rde hoeken. Dit hoekafhankelijk effect verklaart waarom reproducties ervaren luminositeit niet overbrengen.',
    ],
    [
      'Kritiseer kritisch hoe postkoloniale kunstgeschiedenis het "Oriëntale invloeds"-verhaal in Renaissance-schildering hermonteerd, diffusionistkaders verwerping die Europa als passieve ontvanger positioneerden.',
      [
        'Handelsuitwisseling was onderhandeld, geen eenrichting',
        'Renaissance schilders kopeerden Oriëntale kunst passief',
        'Handel beïnvloedde Europese schilderij techniek niet',
        'Postkoloniaal kritiek is irrelevant voor schilderij geschiedenis',
      ],
      0,
      'Postkoloniaal scholaraat toont lajisoucing, Islamitisch papierebruik en glazuurtechnieken waren onderhandelde uitwisselingen, niet passieve lening; Renaissance-appropriatie impliceert strategische transformatie, niet simpele navolging.',
    ],
    [
      'In recente scholaraat over schilder\'s optische gereedschappen (camera obscura, prismen, spiegels), verklaar het epistemologische probleem: optische verificatie (mechanische reproductie) versus doelbewuste artistieke interpretatie.',
      [
        'Optische hulpmiddelen tonen technisch vermogen, geen creatieve intentie',
        'Optische gereedschappen bewijzen schilderijen zijn mechanische reproducties',
        'Kunstenaars gebruikten nooit optische toestellen',
        'Optische hulpmiddelen elimineren artistieke interpretatie totaal',
      ],
      0,
      'Optisch gereedschap gebruik (technisch verifieerbaar) impliceert niet artistieke agency eliminering; schilders selecteerden, vervormden en herstelden optisch afgeleide afbeeldingen. Gereedschapsp resence ≠ autoriteitspassiviteit.',
    ],
  ],
};
