import type { CategoryContent } from '../row.js';

export const PHOTOGRAPHY: CategoryContent = {
  bscba: [
    [
      'Welk materiaal vormt het reflectieve oppervlak van een daguerreotype?',
      [
        'Zilveren gecoate koperen plaat',
        'Gepolijst glas met kwikbacking',
        'Staniol gelamineerd op messing',
        'Aluminium-legering met zilverni­traatcoating',
      ],
      0,
      'Daguerreotypes bestaan uit een zilveren laag op koper, die de stijve, reflectieve ondergrond biedt die nodig is voor het beeld.',
    ],
    [
      'Welke chemische verbinding vormt de lichtgevoelige laag in natte collodium-fotografie?',
      [
        'Zilveriodide opgelost in collodium',
        'Zilverchlor­ide in gelati­nesuspensie',
        'Zilverbromide-kristallen in eierwit',
        'Kopersulfaat gemengd met kalium­permanganaat',
      ],
      0,
      'Natte collodium gebruikt jodium gemengd met collodium (nitrocellulose opgelost in ether), gevoeliggemaakt door onderdompeling in zilverni­traat.',
    ],
    [
      'Welk voordeel boden droge-platgelamine-emulsies ten opzichte van natte collodiumplaten?',
      [
        'Konden dagen of weken na voorbereiding belicht worden',
        'Vereisten geen chemische verwerking in de donkere kamer',
        'Produceerden beelden met meer detail dan elk ander proces',
        'Konden gemakkelijk hergebruikt worden door de emulsie te verwijderen',
      ],
      0,
      'Droge gelatieplaten waren vooraf gecoat en konden voor gebruik lange tijd opgeslagen worden, waardoor ter plaatse voorbereiding niet nodig was.',
    ],
    [
      'Wat meet ISO-snelheid in film en digitale sensoren?',
      [
        'Lichtgevoeligheid van het beeldvormingsmedium',
        'De maximale diafragmaopening van de lens',
        'De duur van de blootstelling in seconden',
        'De kleurtemperatuur van de lichtbron',
      ],
      0,
      'ISO kwantificeert gevoeligheid voor licht: hogere ISO betekent meer gevoeligheid, maar meestal met zichtbaar korrel of ruis.',
    ],
    [
      'Wat vertegenwoordigt een f-getal?',
      [
        'De verhouding van de brandpuntsafstand van de lens tot de diafragmadoorsnede',
        'De maximale sluitertijd beschikbaar op de camera',
        'Het aantal kleurenfilters in het optische pad',
        'De afstand waarop de lens de scherpste focus geeft',
      ],
      0,
      'F-getallen (f/1.8, f/4, f/16, enz.) drukken diafragmagrootte uit als verhouding; lagere nummers betekenen bredere diafrагма\'s en meer licht.',
    ],
    [
      'Welke fotografische beweging legde nadruk op zachte focus, handgekleurde afdrukken en schildersachtige kwaliteiten?',
      [
        'Pictorialisme',
        'Rechtlijnige fotografie',
        'Constructivisme',
        'Fotojournalistiek',
      ],
      0,
      'Pictorialisme (einde 19de–begin 20ste eeuw) imiteerde schilderkunst door opzettelijke zachtheid, textuur en manipulatie.',
    ],
    [
      'Wat is de primaire functie van een donkerkamer-veiligheidslicht?',
      [
        'Staat veilig werk toe zonder film te belichten',
        'Het leveren van warmte voor chemische reacties tijdens filmontwikkeling',
        'Het controleren van de dichtheid van chemische oplossingen',
        'Het elimineren van stofdeeltjes uit de donkerkamelucht',
      ],
      0,
      'Veiligheidslampen (meestal rood of amber) zenden golflengten uit die fotografische emulsies niet kunnen waarnemen, zodat veilig gewerkt kan worden.',
    ],
    [
      'Wat vertegenwoordigt Zone V in Ansel Adams\' Zonesysteem?',
      [
        'Middelgrijs (18% reflectie)',
        'Zuiver zwart zonder detail',
        'Zuiver wit zonder detail',
        'De gemiddelde helderheid van landschapschaduw',
      ],
      0,
      'Zone V is de referentie-midtoon van het systeem met 18% reflectie. Zones erboven en eronder hebben relaties in stappen van één blende.',
    ],
    [
      'Welke techniek omvat het selectief blokkeren van licht tijdens vergroting om gebieden van een fotoafdruk donkerder te maken?',
      [
        'Afscherming',
        'Branden',
        'Solarisatie',
        'Intensificatie',
      ],
      0,
      'Afscherming houdt licht tegen en maakt gebieden lichter. Branden voegt licht toe om gebieden donkerder te maken—complementaire darkroom-technieken.',
    ],
    [
      'Welke bekende Amerikaanse fotograaf staat bekend om landschappen in groot formaat en het Zonesysteem?',
      [
        'Ansel Adams',
        'Edward Weston',
        'Walker Evans',
        'Alfred Stieglitz',
      ],
      0,
      'Ansel Adams was een pionier van het Zonesysteem en creëerde iconische zwart-witlandschappen van het Amerikaanse Westen.',
    ],
    [
      'Welke chemische verbinding wordt op glas of papier aangebracht om een albumine-afdruk te maken?',
      [
        'Eierwit met zilvernitraat',
        'Gelatine opgelost in kalium­chloride',
        'Wasemulsie met cadmium­sulfide',
        'Zetmeelpasta met kopperacetaat',
      ],
      0,
      'Albumine-afdrukken gebruiken een laag eierwit op papier om een glad oppervlak te creëren, vervolgens gevoeliggemaakt met zilverni­traat.',
    ],
    [
      'Waaronder staat het "calotype"-proces ook bekend?',
      [
        'Talbotype',
        'Daguerreotype-variant',
        'Ferrotype-proces',
        'Droge gelatieplaat',
      ],
      0,
      'Het calotype, uitgevonden door Talbot in 1841, produceerde een negatief op papier—de voorloper van de moderne negatief-gebaseerde fotografie.',
    ],
    [
      'Waarnaar verwijst "het beslissende moment" in straatfotografie?',
      [
        'Het moment waarop compositie en betekenis samenvallen',
        'Het exacte moment waarop de film moet worden ontwikkeld',
        'Het moment waarop de camerasluiter maximale snelheid bereikt',
        'Het moment waarop natuurlijk licht het voordeligst is',
      ],
      0,
      'Henri Cartier-Bresson\'s term voor het vastleggen van het exacte moment van perfecte compositie en betekenis in een ontplooide scène.',
    ],
    [
      'Wat is het primaire doel van filmkorrel in zwart-witfotografie?',
      [
        'Een bijproduct van hoe zilverhalidekorrels het beeld vormen',
        'Het wordt toegevoegd tijdens afdrukken om vervagingvan het beeld te voorkomen',
        'Het verbetert de scherpheid van fijne details',
        'Het zorgt ervoor dat licht gelijkmatig over de afdruk wordt gereflecteerd',
      ],
      0,
      'Korrel ontstaat uit individuele zilverhalidestalten in de emulsie; fijnere korrel betekent hogere resolutie maar lagere gevoeligheid.',
    ],
    [
      'Welke Amerikaanse fotograaf creëerde een systematisch documentatieproject voor de Farm Security Administration?',
      [
        'Walker Evans',
        'Margaret Bourke-White',
        'Paul Strand',
        'Minor White',
      ],
      0,
      'Walker Evans creëerde een typologisch archief van Amerikaanse plattelandscultuur in de jaren 1930 voor de FSA, wat documentaire fotografie beïnvloedde.',
    ],
  ],

  msc: [
    [
      'Waarom verschijnt een daguerreotypebeld gespiegeld (lateraal omgekeerd)?',
      [
        'Het enkele spiegelachtige oppervlak reflecteert licht onder de hoek van de cameralens',
        'Het zilveren plateerproces keert de moleculaire structuur om',
        'Daguerreotypes vereisten altijd een spiegel die ervoor werd geplaatst voor het bekijken',
        'Het beeld werd chemisch omgekeerd tijdens het gevoeligmakingsproces',
      ],
      0,
      'Daguerreotypes zijn unieke omgekeerde beelden omdat licht direct het gepolijste metalen oppervlak belicht zonder tussenliggende filmlagen.',
    ],
    [
      'Hoe verschilde natte-collodium-fotografie fundamenteel van eerdere calotype-processen?',
      [
        'Collodium hechtte aan glas, wat meer detail gaf dan papier',
        'Calotypes gebruikten zilverni­traat terwijl collodium alleen jodiumverbindingen gebruikte',
        'Collodium-platen konden onbeperkt voor blootstelling worden opgeslagen',
        'Natte-collodium-fotografie produceerde zichtbare korrel terwijl calotypes graanvrij waren',
      ],
      0,
      'Glassubstraten en collodium-emulsie boden superieure resolutie en schonere negatieve dan papier; collodium domineerde van 1850–1880.',
    ],
    [
      'Op welke manier kenmerkt de sensitometrische curve (D-log E) filmgedrag?',
      [
        'Zet dichtheid uit tegen log-blootstelling',
        'Het meet de tijd die nodig is voor chemische ontwikkeling bij verschillende temperaturen',
        'Het voorspelt hoe de korrelgrootte verandert onder verschillende verlichtingsomstandigheden',
        'Het geeft aan de kleurverschuiving die optreedt in verouderde emulsies',
      ],
      0,
      'De D-log(E)-curve kaart dichtheid versus log-blootstelling in kaart en onthult filmlatitude, gamma en gevoeligheid—kerngegevens.',
    ],
    [
      'Waarom is hyperfocale afstand belangrijk in fotografie met groot formaat?',
      [
        'Maximaliseert scherptediepte van dichtbij tot veraf',
        'Dit verhindert optische vervorming in groothoeklensen',
        'Dit bepaalt de optimale sluitertijd voor hanteren',
        'Dit compenseert de balgenverlenging op viewcamera\'s',
      ],
      0,
      'Focus stellen op hyperfocale afstand zorgt voor aanvaardbare scherpheid van halverwege die afstand tot oneindig.',
    ],
    [
      'Wat was het filosofische verschil tussen Pictorialisme en Rechtlijnige Fotografie?',
      [
        'Artistieke manipulatie versus ongemanipuleerde onderwerponthulling',
        'Rechtlijnige fotografen gebruikten kleurenfilm terwijl Pictorialisten alleen zwart-wit gebruikten',
        'Pictorialisten vereisten speciale lenzen terwijl Rechtlijnige fotografen standaardlenzen gebruikten',
        'Rechtlijnige fotografie werkte alleen buiten; Pictorialisme vereiste studiolichting',
      ],
      0,
      'Rechtlijnige fotografie (Weston, Adams) wees Pictoriaalse hand-manipulatie af en bepleitte scherpe focus en fotografische vorm.',
    ],
    [
      'Welke fotografische beweging documenteerde expliciet armoede en verplaatsing in het platteland van Amerika tijdens de Grote Depressie?',
      [
        'FSA-fotografie (1935–1944)',
        'Pictorialistische beweging (1890–1910)',
        'Modernistische abstractie (1920–1940)',
        'Photo-Secession-groep (1905–1917)',
      ],
      0,
      'De FSA huurde fotografen in om plattelandseomstandigheden en hervestigingsinspanningen in kaart te brengen—fundamentele documentaire fotografie.',
    ],
    [
      'Wat is de chemische basis voor archivalische duurzaamheid in platina-afdrukken versus gelatine-zilveren afdrukken?',
      [
        'Platina is inert; gelatine-zilver kan in de loop der tijd degraderen',
        'Gelatine bevat natuurlijke conserveermiddelen die platina ontberen',
        'Platina-afdrukken vereisen speciale lichtbronnen om stabiel te blijven',
        'Gelatine-afdrukken verbleken alleen als ze aan vocht worden blootgesteld',
      ],
      0,
      'Platina-metaal is inert en extreem stabiel; gelatine-zilveren afdrukken degraderen als onvolledige fixering reactieve verbindingen achterlaat.',
    ],
    [
      'Waarom vereist branden van bepaalde gebieden in darkroom-vergroting nauwkeurige belichtingstijdberekening?',
      [
        'Te veel branden verzwart papier; te weinig doet niets',
        'Branden kan chemische reacties veroorzaken die giftige dampen vrijstellen',
        'De papieeremulsie wordt tijdelijk ongevoelig nadat de initiële blootstelling heeft plaatsgevonden',
        'Brandtijd beïnvloedt rechtstreeks de verzadiging van kleur in zwart-witafdrukken',
      ],
      0,
      'Branden voegt gelokaliseerde blootstelling toe; miscalculatie geeft troebele zwartes (teveel) of verwaarloosbare verdonkering (te weinig).',
    ],
    [
      'Welke rol speelde de Photo-Secession bij het vestigen van fotografie als beeldende kunst?',
      [
        'Het toonde fotografie naast schilderkunst en sculptuur',
        'Het vond het eerste kleurenfotografieproces uit',
        'Het ontwikkelde de eerste geautomatiseerde cameramechanismen',
        'Het stelde octrooiwetten vast die fotografische uitvindingen beschermden',
      ],
      0,
      'Stieglitz\' Photo-Secession (1902) tentoonstelde fotografie in kunstgalerieën en publiceerde Camera Notes, wat fotografie als ernstige kunst legitimeerde.',
    ],
    [
      'Hoe beïnvloedt sensorderemosaïque de beeldkwaliteit in digitale camera\'s?',
      [
        'Algoritmen reconstrueren kleurenbeelden uit Bayer-gegevens',
        'Demosaïque heeft geen effect op beeldkwaliteit; het is puur een mechanisch proces',
        'Demosaïque verhoogt het effectieve pixelaantal van de sensor',
        'Demosaïque is alleen nodig voor zwart-witdigitale fotografie',
      ],
      0,
      'Bayer-sensoren leggen slechts één kleur per pixel vast; demosaïque reconstrueert volledige RGB. Kwaliteit hangt af van algoritme-verfijning.',
    ],
    [
      'Wat is het principe achter Ansel Adams\' Zonesysteem voorbij praktische meting?',
      [
        'Linkt blootstelling, ontwikkeling en afdrukken aan voorgeziene tonen',
        'Het maakt lichtsensoren volledig overbodig',
        'Het werkt alleen met camera\'s in groot formaat',
        'Het garandeert dat alle filmtypen identieke toonen produceren',
      ],
      0,
      'Het Zonesysteem linkt blootstelling en ontwikkeling aan visualisatie: elke zone-stap controleert tonale scheiding opzettelijk.',
    ],
    [
      'Waarom bleef natte-collodium-fotografie dominant ondanks de uitvinding van droge-gelatine-emulsies?',
      [
        'Collodium bood betere kwaliteit zonder voorbereiding nodig',
        'Natte platen waren goedkoper in de fabricage',
        'Droge platen konden niet buiten gebruikt worden',
        'Collodium was gemakkelijker gevoeligmaken dan gelatine',
      ],
      0,
      'Natte-plaatbeeldkwaliteit was superieur en onmiddellijk; gelatine had ~15 jaar ontwikkeling nodig voordat gelijkwaardige prestaties werden bereikt.',
    ],
    [
      'In kleurenfotofilm, wat veroorzaakt de kleurverschuiving in tungsteen-gebalanceerde film die in daglicht wordt blootgesteld?',
      [
        'Daglichts blauwe kleurtemperatuur overweldigt tungsteen-balans',
        'Tungsteen-film corrigeert automatisch voor elke lichtbron',
        'Daglicht bevat ultraviolet dat kleurdyes bleekt',
        'De filmfilters reageren chemisch op zonlicht',
      ],
      0,
      'Tungsteen-film (3200K) ziet er excessief blauw uit in daglicht (5500K); daglicht-film ziet er oranje uit onder tungsteen.',
    ],
    [
      'Wat betekende Edward Weston met "previsuralisatie" in zijn fotografische praktijk?',
      [
        'Mentaal samenstellen van de afdruk voor de sluiter valt',
        'Meerdere belichtingen gebruiken om verschillende composities te stapelen',
        'Hetzelfde onderwerp herhaaldelijk fotograferen tot de gewenste hoek wordt bereikt',
        'Composities in potlood schetsen voordat de camera wordt opgesteld',
      ],
      0,
      'Weston\'s previsualisatie betekende het zien van het volledige tonale bereik en compositie voor blootstelling—niet afhankelijk van darkroom-redding.',
    ],
    [
      'Hoe beïnvloedde straatfotograaf Henri Cartier-Bresson\'s keuze voor telemeteramera zijn werk?',
      [
        'Compact en stil, wat onopvallende observatie mogelijk maakte',
        'Telemeters produceerden scherpere beelden dan viewcamera\'s',
        'Telemeters waren de enige camera\'s die destijds kleurenfotografie konden doen',
        'Telemeters hadden superieure autofocus-systemen',
      ],
      0,
      'De Leica-telemeter was compact, stil en had een helder framezoeker—ideaal voor onopvallende straatfotografie.',
    ],
  ],

  phd: [
    [
      'Waarom plaatsten daguerreotype-fabrikanten koper specifiek met zilver in plaats van massieve zilveren platen te gebruiken?',
      [
        'Koper is goedkoper en stijf; zilvercoating geeft reflectiviteit',
        'Zilver was te bros voor de polijsting die voor gevoeligmaking nodig was',
        'De oxidatie van koper creëerde de lichtgevoelige laag tijdens jodiumblootstelling',
        'Massief zilver reageerde chemisch met jodiumverbinding en vernietigde beelden',
      ],
      0,
      'Koperen onderbouw zorgt voor mechanische kracht; dunne zilveren coating is voldoende voor reflectie en kosteneffectief.',
    ],
    [
      'Wat is de chemische rol van jodium versus latere broomtoevoegingen in natte collodium?',
      [
        'Jodium is het primaire halide; broomide versnelt gevoeligmaking',
        'Jodium en broomide produceren identieke gevoeligmakingssnelheden en gevoeligheid',
        'Broomide maakte zilverni­traatonderdompeling onnodig',
        'Jodium maakte platen instabiel; broomide lost dit volledig op',
      ],
      0,
      'Jodium is het basis-halide; toegevoegde broomiden en chloriden verhogen gevoeligmakingssnelheid zonder het basisproces te wijzigen.',
    ],
    [
      'Hoe introduceren Bayer CFA-arrays en demosaïque-algoritmen kleurartefacten in digitale sensoren?',
      [
        'Mislukte interpolatie bij randen creëert kleuringrand',
        'Bayer-arrays reduceren automatisch kleurverzadiging in alle beelden',
        'Demosaïque wazig alle kleurinformatie uniform',
        'Kleurartefacten treden alleen op bij defecte sensoren',
      ],
      0,
      'Bayer-interpolatie bij randen kan kleuren verkeerd toewijzen; slechte demosaïque creëert artefacten vooral bij overgangen.',
    ],
    [
      'Wat veroorzaakt in gelatieemulusie-veroudering de fysieke blaarvorming en vervelling van droge glasplaten?',
      [
        'Verschillende expansiecoëfficiënten tussen gelatine en glas',
        'Oxidatie van zilverhalidestalten',
        'Bacteriële groei tussen gelatine en glas',
        'Thermische expansie van de koperen onderlaag',
      ],
      0,
      'Gelatine en glas hebben verschillende expansiecoëfficiënten; vochtfluctuatie creëert spanning. Residuale solventwandering versnelt schade.',
    ],
    [
      'Wat onderscheidt apochromatische lensorrectie van standaard achromatische ontwerpen?',
      [
        'Corrigeert chromatische aberratie op drie golflengten, niet twee',
        'Apochromatische lenzen gebruiken reflectieve coatings terwijl achromatische lenzen alleen breking gebruiken',
        'Apochromatische lenzen zijn alleen bruikbaar in ultraviolette golflengten',
        'Apochromatische en achromatische lenzen zijn functioneel identiek',
      ],
      0,
      'Apo-ontwerpen corrigeren drie spectrale lijnen (vs. twee in achromatisch); superieure kleurregistratie, vooral bij grote diafrагма\'s.',
    ],
    [
      'Hoe verschillen ontwikkelingskinetica tussen fenidoon en hydroquinon-ontwikkelaars?',
      [
        'Fenidoon ontwikkelt sneller; hydroquinon geeft hogere contrast',
        'Hydroquinon is sneller maar produceert meer korrel',
        'Fenidoon vereist hogere temperaturen dan hydroquinon',
        'Beide ontwikkelaars produceren identieke contraastcurven',
      ],
      0,
      'Fenidoon werkt snel en zacht (betere schaduwscheiding); hydroquinon is langzamer maar produceert hogere contrast en duurzaamheid.',
    ],
    [
      'Welke filosofische en artistieke premises lagen ten grondslag aan het Pictorialistische beweging en de afstemming ervan op Symbolisme?',
      [
        'Pictorialisten putten uit Symbolistische stemming en subjectiviteit',
        'Pictorialisme was puur een technische fotografische innovatie zonder verband met kunstbewegingen',
        'Pictorialisten wezen alle fijne kunstbeïnvloedingen expliciet af',
        'Pictorialisme sloot aan op Realisme, niet Symbolisme',
      ],
      0,
      'Pictorialisten omarmen Symbolistische idealen: emotie en interpretatie boven documentatie; kunst als binnenvisie, niet externe feit.',
    ],
    [
      'Welke methodologische benadering gebruikte Walker Evans in zijn Farm Security Administration-typologische documentatie?',
      [
        'Systematisch frontaal framen om een objectief archief op te bouwen',
        'Zeer subjectieve emotionele portretten die individueel lijden benadrukken',
        'Schildersachtige compositie die fijne kunstesthetica imiteert',
        'Sequentieel verhaalvertelling volging van families gedurende jaren',
      ],
      0,
      'Evans ontwikkelde een typologische methode: herhaalde frontale hoeken, doffelichting, systematische catalogisering—een gehavende archiefesthetiek.',
    ],
    [
      'Hoe zorgen platina-afdruk metaal-zoutinteracties voor buitengewone duurzaamheid vergeleken met andere afdrukmethoden?',
      [
        'Platina deponeert inert metaal in vezels dat niet kan oxideren',
        'Platina-afdrukken gebruiken speciale lak-coatings die lichtblootstelling voorkomen',
        'Platina-afdrukken gebruiken archivaal papier dat gelatinaprocessen niet kunnen openen',
        'Platina- en gelatine-afdrukken zijn even permanent',
      ],
      0,
      'Platina deponeert elementair Pt; chemisch inert, weert het verbleking. Gelatine-zilver is afhankelijk van gereduceerd zilver—gemakkelijk geoxideerd.',
    ],
    [
      'Wat is het doel van microlenzen boven individuele fotodioden in Bayer CFA-architectuur?',
      [
        'Microlenzen richten licht op het actieve fotodiodegebied',
        'Microlenzen elimineren hete pixels',
        'Microlenzen scheiden kleurkanalen mechanisch',
        'Microlenzen dienen alleen esthetische doeleinden en beïnvloeden beeldkwaliteit niet',
      ],
      0,
      'Microlenzen concentreren licht op het actieve fotodiode-gebied en verbeteren lichtverzamelingefficiëntie bij hoge pixeldichtheid.',
    ],
    [
      'Wat onderscheidt digitale raw-bestandsgegevensverwerking (demosaïque, witbalans) van in-camera JPEG-rendering?',
      [
        'Raw behoudt ondemosaïqueerde gegevens; JPEG past vaste verwerking toe',
        'Raw-bestanden kunnen niet afgedrukt worden en JPEG-bestanden kunnen alleen afgedrukt worden',
        'Raw-bestanden hebben altijd lagere resolutie dan JPEG\'s',
        'Raw- en JPEG-bestanden zijn identiek na demosaïque',
      ],
      0,
      'Raw behoudt Bayer-gegevens voor flexibele nabewerking; JPEG past vaste demosaïque-algoritmen en kleurwetenschap in-camera toe.',
    ],
    [
      'Hoe evolueerden early-filmstocks met betrekking tot emulsiegevoeligheid en kleurweergave?',
      [
        'Ortochromatisch maakte plaats voor panchromatisch, dan kleurenfilm',
        'Filmstocks zijn chemisch onveranderd gebleven sinds uitvinding',
        'Kleurenfilm bestaat sinds de jaren 1920 maar werd om kostenredenen onderdrukt',
        'Panchromatische film ging chronologisch aan ortochromatische film vooraf',
      ],
      0,
      'Ortho-stocks (rood-blind) domineerden stille films; panchromatisch arriveerde jaren 1920–30. Kleurenfilm (jaren 1950 midden) verscheen halverwege 20ste eeuw.',
    ],
    [
      'Welke technische beperkingen legde groot-formatnegatief-grootte op Adams\' visualisatiepraktijk?',
      [
        'Groot-formaten gaven uitzonderlijk detail maar vereisten precisie',
        'Groot-formaten stonden onbeperkt bracketing en testopnamen toe',
        'Groot-formaten produceerden beelden identiek in kwaliteit aan 35mm-film',
        'Groot-formaten hadden geen impact op visualisatie omdat afdrukken altijd konden worden vergroot',
      ],
      0,
      '8x10-negatieven bieden ongeëvenaard resolutie en schaduwscheiding maar vereisen nauwkeurige blootstelling; elk blad kost tijd en materialen.',
    ],
    [
      'Hoe steunden fotografische formele eigenschappen (scherpe focus, hoog contrast, ongebruikelijke hoeken) in Constructivistische en Bauhaus-bewegingen modernistische visuele ideologie?',
      [
        'Fotografie\'s mechanische objectiviteit paste bij modernistische idealen',
        'Fotografie had geen verbinding met Constructivisme of Bauhaus',
        'Fotografie werd door Constructivisten afgewezen als onvoldoende artistiek',
        'Constructivisten gebruikten fotografie alleen voor documentaire doeleinden',
      ],
      0,
      'Constructivisten waardeerden fotografische schijnbare objectiviteit en geometrisch potentieel; scherpe focus en hoeken pasten bij modernistische esthetica.',
    ],
    [
      'Welke optische en functionele afwegingen legt het teleméter-focusseersysteem op wijd-hoekdekking op?',
      [
        'Bredere lenzen reduceren parallaxbasis en schaden focusnauwkeurigheid',
        'Telemeters werken perfect op alle brandpuntsafstanden',
        'Telemeters zijn het nauwkeurigst met brede lenzen',
        'Brede-hoeklenzen maken telemeter-focus onnodig',
      ],
      0,
      'Telemeter-basis is vast; bredere lenzen vergroten parallaxfouten. Onder ~35mm wordt focussen via telemeter onpraktisch.',
    ],
  ],

  professor: [
    [
      'Waarom gebruikten daguerreotype-fabrikanten broomdampgevoeligmaking na initiële jodiumcoating op zilveren oppervlakken?',
      [
        'Broomide verlengde spectrale respons en verkortte belichtingstijden',
        'Broomide verwijderde jodiumverbindingen die het beeld verontreinigden',
        'Broomide verbeterde de reflectiviteit van het zilveren oppervlak',
        'Broomide en jodium vervulden identieke gevoeligmakingsrollen',
      ],
      0,
      'Broomide-toevoeging aan jodium-daguerreotypes verhoogde gevoeligheid door halide-respons te vergroten; belichtingstijden daalden drastisch.',
    ],
    [
      'Hoe bepaalden ijzeroxide- en collodium-verhoudingen in ferrotype (tintype) -emulsieformulering beelddichtheid en duurzaamheid?',
      [
        'Ijzeroxide bepaalde dichtheid; collodium-verhouding bepaalde flexibiliteit',
        'Ijzeroxide en collodium waren onafhankelijke componenten',
        'Ferrotypes gebruikten zilverhalidestalten, niet ijzeroxide',
        'Ferrotype-samenstelling was gestandaardiseerd en varieerde nooit',
      ],
      0,
      'Tintype-emulsies gebruikten ijzeroxide gesuspendeerd in collodium; verhoudingen balanceerden dichtheid, adhesie en milieu-spanningsbestendigheid.',
    ],
    [
      'Hoe verschillen Color Filter Array-demosaïque-algoritmen (lineaire interpolatie vs. gradiënt-gebaseerd vs. machine learning) bij het omgaan met aliasing en kleuringrand?',
      [
        'Lineair geeft ingrand bij randen; gradiëntmethoden behouden overgangen beter',
        'Alle demosaïque-methoden produceren identieke resultaten',
        'Lineaire interpolatie is superieur aan alle andere methoden',
        'CFA-demosaïque heeft geen effect op aliasing',
      ],
      0,
      'Lineaire demosaïque veroorzaakt ingrand; gradiënt-bewuste algoritmen onderdrukken het door randrichting te respecteren. ML generaliseert voorbij hand-gecodeerde regels.',
    ],
    [
      'Wat onthult de vorm van de teespits van de D-log(E)-curve in sensitometrie over filmgedrag in schaduwen?',
      [
        'Teespits-helling en lengte geven schaduwlatitude aan',
        'De teespits is niet gerelateerd aan schaduwweergave',
        'Een steile teespits produceert altijd beter schaduwdetail',
        'De teespits beïnvloedt alleen lichtgedrag',
      ],
      0,
      'Curve-teespits bepaalt schaduwgedrag: steile teespits comprimeert schaduwen, zachte teespits behoudt detail; lengte controleert schaduwlatitude.',
    ],
    [
      'Hoe verminderen apochromatische lensontwerpen voorbij eenvoudige brandpuntafstandcorrectie residuele laterale kleur en sferochromatisme?',
      [
        'Fluoriet of speciaal glas vermindert het secundaire spectrum',
        'Apochromatische lenzen elimineren alle optische aberraties',
        'Apochromatische lenzen werken alleen bij gesloten diafrагма\'s',
        'Laterale kleur wordt alleen door software gecorrigeerd, niet optisch',
      ],
      0,
      'Apo-lenzen gebruiken anomaal-dispersie-elementen (fluoriet, speciaal glas) om secundair spectrum voorbij standaard achromatische grenzen te onderdrukken.',
    ],
    [
      'Hoe beïnvloeden pH en buffercapaciteit van ontwikkelaarsoplossingen in zwart-witfilmontwikkeling de snelheid en selectiviteit van ontwikkelingreacties?',
      [
        'pH ~10.5 activeert de ontwikkelaar; buffers stabiliseren pH',
        'pH heeft geen effect op ontwikkelingchemie',
        'Lagere pH versnelt altijd ontwikkeling',
        'Buffers zijn onbelangrijk in ontwikkelaarssamenstelling',
      ],
      0,
      'Optimale pH (~10.5) balanceert ontwikkelingskinetica met veiligheid. Buffers handhaven pH-stabiliteit, waardoor consistent, voorspelbaar ontwikkeling wordt gegarandeerd.',
    ],
    [
      'Wat onthult de theoretische afstemming van de Pictorialistische beweging met Art Nouveau en literaire Decadentie over de culturele positie van vroege fotografie?',
      [
        'Fotografie als subjectieve kunst, afgestemd op Symbolistische idealen',
        'Pictorialisme was puur technisch zonder culturele context',
        'Pictorialisten stemden af op wetenschappelijk positivisme en wezen subjectiviteit af',
        'Fotografiese culturele rol was gedurende de 19de eeuw identiek aan schilderkunst',
      ],
      0,
      'Pictorialisten omarmden Decadente en Art Nouveau-esthetica: progress-narratief afwijzend, subjectiviteit stellingnemend, kunst tegen industrie positionerend.',
    ],
    [
      'Hoe divergeerde Walker Evans\' FSA-archief-methodologie, zijn conceptueel raamwerk van "American photographs" als etnografische typologie, van documentaire traditie?',
      [
        'Systematische, frontale typologie in plaats van narratieve framing',
        'Evans gebruikte standaard fotojournalistieke narratieve vertelling',
        'Evans verwierp systematische methodologie ten gunste van zuiver intuïtieve selectie',
        'Evans\' werk kon niet onderscheiden worden van andere FSA-fotografen\'s benaderingen',
      ],
      0,
      'Evans\' typologische methode—frontaal, doffelichting, catalogisering—creëerde een etnografische inventaris in plaats van narratieve documentatie.',
    ],
    [
      'Hoe controleren de oxidatietoestanden van platina-zouten (II vs. IV) en ijzer(III)-verbindingen in platina-afdrukken het gevoeligmakingsbereik en de afdrukkleur?',
      [
        'IJzerzouten bepalen gevoeligmaking; platina-toestand bepaalt de toon',
        'Platina heeft slechts één oxidatietoestand in afdrukken',
        'IJzer(III)-zouten hebben geen rol in platina-afdrukken',
        'Oxidatietoestanden beïnvloeden afdrukkleur of gevoeligheid niet',
      ],
      0,
      'IJzer(III)-verbindingsverhouding controleert gevoeligmaking; platina-depositie-toestand bepaalt toon—koude grijs van Pt⁴⁺, warmer van Pt²⁺.',
    ],
    [
      'Hoe domineren leesfout versus foton-schotruis in digitaal licht-vastleggen met lage lichtsterkte, en hoe proberen hoge-ISO-algoritmen elk te onderdrukken?',
      [
        'Leesfout domineert bij zwak licht; hoge-ISO versterkt het signaal',
        'Leesruis en foton-schotruis zijn identiek',
        'Hoge-ISO-versterking elimineert beide ruistypen volledig',
        'Foton-schotruis treedt alleen op met hoge ISO',
      ],
      0,
      'Leesfout domineert schaduwen bij basis-ISO; hoge-ISO-versterking helpt foton-ruis te domineren. Algoritmen gebruiken temporale filtratie en frame-stacking.',
    ],
    [
      'Hoe breiden moderne sensitometrische benaderingen Ansel Adams\' origineel negen-zone-raamwerk uit naar digitale vastlegging en raw-bestandoptimalisatie?',
      [
        'Histogram-gebaseerde zone-afbeelding en raw-latitude-optimalisatie',
        'Zonesysteem is in het digitale tijdperk verouderd',
        'Digitale bestanden hebben geen equivalent van Zones',
        'Moderne digitale praktijk verliet Adams\' raamwerk volledig',
      ],
      0,
      'Digitale Zone-extensies gebruiken histogrammen en raw-latitude; raw-vastlegging herstelt schaduwdetail onmogelijk in dia-film, wat Adams\' model uitbreidt.',
    ],
    [
      'Welke chemische emulsie-innovaties in de verschuiving van ortochromatisch naar panchromatisch filmmateriaal in motionpictures (1925–1935) maakten rood-gevoeligheidsverlenging mogelijk?',
      [
        'Merocyanine en andere spectrale gevoeligmakers verschoven piekrespons naar rood',
        'Rode gevoeligheid verscheen spontaan zonder chemische innovatie',
        'Rode gevoeligheid was altijd aanwezig maar gemaskeerd door kleuren',
        'Panchromatisch film vereiste geen chemische veranderingen van ortochromatische stock',
      ],
      0,
      'Spectrale gevoeligmakers (merocyanine-kleuren) verlengden piektrespons in rood; vereiste nieuwe emulsiechemie en fabricageprecisie.',
    ],
    [
      'Hoe vormden de mechanische beperkingen en precisieëisen van groot-formatatie-camerabediening Ansel Adams\' en andere meesters\' visuele conceptualisering?',
      [
        'Traagheid en kosten dwongen visualisatiediscipline af',
        'Groot-format legde geen beperkingen op aan fotografen\'s denken',
        'Groot-format maakte visualisatie onmogelijk vanwege kleine grondglas',
        'Camerabewegingen waren puur voor technische correctie, niet creatieve intentie',
      ],
      0,
      'Viewcamera\'s bewuste snelheid en precisieregeling dwingt zorgvuldige compositie; bewegingen werden opzettelijke ontwerphulpmiddelen, geen correcties.',
    ],
    [
      'Op welke manieren positioneerde de Russische Constructivistische omhelzing van fotografie (bv. Rodchenko, Lisitsky) het medium als ideologisch afgestemd op revolutionaire modernisme?',
      [
        'Fotografiese mechanische objectiviteit paste bij Marxistisch materialisme',
        'Constructivisten wezen fotografie af als burgerlijk',
        'Fotografie was toevallig voor Constructivisme\'s kernideologie',
        'Constructivisten gebruikten fotografie identiek aan traditionele beeldende kunst',
      ],
      0,
      'Constructivisten zagen fotografie\'se mechanische basis als bewijs van arbeiderscultuur; hoge hoeken en insnijding stelden ontwerp tegenover natuur.',
    ],
    [
      'Hoe stellen de optische eigenschappen van telemeter-conjugaat-prism-ontwerpen (scheidingsafstand, prismageometrie) de grenzen van nauwkeurig focussen over brandpuntsafstanden?',
      [
        'Vaste basisafstand maakt groothoekfocussen onpraktisch',
        'Telemetergeometrie is niet gerelateerd aan prestatie op brandpuntsafstand',
        'Telemeters zijn op alle brandpuntsafstanden even nauwkeurig',
        'Prismageometrie verandert automatisch voor elke lens',
      ],
      0,
      'Vaste basis betekent kortere lenzen reduceren parallax-vergroting; bij brede hoeken daalt de parallaxhoek onder focussoresolutie.',
    ],
  ],
};
