import type { CategoryContent } from '../row.js';

/**
 * Film & TV Technology (1980-Now).
 */

export const SCREEN_TECH: CategoryContent = {
  bscba: [
    [
      'Wat staat de afkorting "fps" voor in video en cinematografie?',
      ['Beelden per seconde', 'Veld per monster', 'Frequentie van het beeldsignaal', 'Filmverwerkingsstandaard'],
      0,
      'FPS (beelden per seconde) meet hoeveel individuele beelden per seconde weergegeven worden, rechtstreeks beïnvloedend de waargenomen bewegingsvloeibaarheid en zichtbare bewegingsonscherpte.',
    ],
    [
      'Welke kleurruimte gebruikt rood, groen en blauw als zijn drie primaire kleurkanalen?',
      ['RGB', 'CMYK', 'HSL', 'YUV'],
      0,
      'RGB (rood, groen, blauw) is de standaard kleurruimte voor digitale camera\'s en schermen, waar alle zichtbare kleuren ontstaan door variatie in intensiteit van deze drie primaire kanalen.',
    ],
    [
      'Wat is de standaardframerate die traditioneel in bioscooptheaters wordt gebruikt?',
      ['24 beelden per seconde', '30 beelden per seconde', '60 beelden per seconde', '120 beelden per seconde'],
      0,
      'Cinema gebruikt sinds de jaren 1920 bij de introductie van gesynchroniseerd geluid 24fps als standaard, en dit blijft vandaag de dag de wereldwijde bioscoopstandaard.',
    ],
    [
      'Wat is de primaire functie van een codec in digitale video?',
      ['Comprimeert en decomprimieert videogegevens voor efficiënte opslag en verzending', 'Meet kleurnauwkeurigheid tussen verschillende camera\'s', 'Converteert filmbeelden naar digitaal formaat', 'Synchroniseert audio met video tijdens afspelen'],
      0,
      'Een codec (coder-decoder) comprimeert video voor opslag of verzending en decomprimieert deze voor afspelen, waardoor efficiënte verwerking van grote videobestanden mogelijk wordt.',
    ],
    [
      'Waarvoor wordt chroma-key-compositie primair gebruikt?',
      ['Het vervangen van een gekleurde achtergrond met een ander beeld', 'Ongewenste kleurkleuring in beelden corrigeren', 'Gevoelige uitzendinhoud versleutelen', 'Het meten van omgevingslicht op set'],
      0,
      'Chroma key stelt filmmakers in staat om een effen gekleurde achtergrond uit beelden te verwijderen en er een nieuwe in te composeren, essentieel voor greenscreen en studiovisuele-effecten.',
    ],
    [
      'Welke beeldverhouding komt het beste overeen met de originele bioscoopstandaard?',
      ['1.37:1 (Academy)', '1.85:1', '2.39:1 (Anamorfisch)', '16:9 (Breedbeeld)'],
      0,
      'De Academy-beeldverhouding van 1.37:1 was gedurende decennia de standaard voor bioscoopfilms voordat breedbeeldformaten in de jaren 1950 gangbaar werden.',
    ],
    [
      'Waarvoor wordt motion capture (mocap) primair in film en animatie gebruikt?',
      ['Het opnemen van acteurbewegingen om digitale karakteranimatie aan te sturen', 'Fotograferen van levende acteurs voor traditionele matte paintings', 'Het stabiliseren van wankele handheld-cameraopnames', 'Het detecteren van artefacten in gecomprimeerde videostromen'],
      0,
      'Motion capture registreert fysieke bewegingen van een acteur met behulp van markers, vertaalt deze naar digitale personages en bewaart natuurlijke prestatie- en bewegingskwaliteit.',
    ],
    [
      'Wat is het primaire doel van kleurcorrectie in postproductie?',
      ['Kleur, helderheid en contrast aanpassen voor een gewenste visuele stijl', 'Beschadigde of gekraste film uit originele negatieven repareren', 'Ongewenste objecten uit achtergrondscenery verwijderen', 'Beelden van meerdere camera\'s met verschillende sensoren synchroniseren'],
      0,
      'Kleurcorrectie past kleur, helderheid en contrast aan om stemming en visuele continuïteit tot stand te brengen, waardoor ruw materiaal in een gepolijst eindresultaat wordt omgezet.',
    ],
    [
      'Wat is een digital intermediate (DI) in film-postproductie?',
      ['Het converteren van filmbeelden naar digitale vorm voor kleurcorrectie en effecten', 'De eerste ruwe montage die aan studiobonzen wordt getoond', 'Een veiligheidsback-up van het originele cameranegatief', 'Een gecomprimeerd formaat gebruikt voor distributie van dailies aan extern team'],
      0,
      'Een digital intermediate stelt filmmakers in staat om digitale kleurcorrectie en effectenwerk uit te voeren voordat naar film of digitale afleveringsformaten wordt gerendered.',
    ],
    [
      'Wat beschrijft resolutie in digitale video het beste?',
      ['Het aantal horizontale en verticale pixels in een afbeelding', 'De framerate waarmee de video is opgenomen', 'De kleurbitdiepte toegewezen per kanaal', 'Het dynamisch bereik of helderheid van een camera'],
      0,
      'Resolutie verwijst naar de pixelafmetingen van een videoafbeelding, zoals 1920x1080 of 3840x2160, wat de zichtbare scherpte en fijndetail beïnvloedt.',
    ],
    [
      'Wat is het primaire voordeel van RAW-videoformaten in vergelijking met gecomprimeerde formaten?',
      ['Het behouden van maximale sensorgegevens voor flexibiliteit in kleurcorrectiewerk', 'Het bereiken van snellere bestandsoverdrachtsnelheden via netwerken', 'Het verminderen van opslagvereisten door kleinere bestandsgrootte', 'Betere compatibiliteit met consumentenapparatuur'],
      0,
      'RAW-video legt ongeverwerkte sensorgegevens zonder compressie of kleurverwerking vast, waardoor maximale informatie voor creatieve en correctieve aanpassingen behouden blijft.',
    ],
    [
      'Wat is een LED-wand (of "Volume") in virtuele productie?',
      ['Een scherm met live-gerenderde achtergronden achter acteurs zonder greenscreen', 'Een wand met lampen voor verlichting en illuminatie van studiostellen', 'Een opslagapparaat voor opnamen van extra gelijktijdige camerakanten', 'Een projectiescherm dat vooraf opgenomen omgevingsachtergronden weergeeft'],
      0,
      'LED-wanden in virtuele productie geven fotorealistische omgevingen weer die in real-time worden gerenderd, waardoor acteurs en camera\'s op een natuurlijke manier met achtergronden kunnen interageren.',
    ],
    [
      'Waar staat het acroniem HDR voor in videotechnologie?',
      ['High Dynamic Range', 'High Definition Recording', 'Horizontal Display Resolution', 'High Density Rendering'],
      0,
      'HDR (High Dynamic Range)-video legt een breder bereik van helderheid vast dan standaardvideo, wat meer detail in zowel heldere hoogtepunten als donkere schaduwen weergeeft.',
    ],
    [
      'In professionele audio, waar staat PCM voor?',
      ['Pulse Code Modulation', 'Phase-Corrected Measurement', 'Progressive Codec Mapping', 'Perceptual Color Model'],
      0,
      'PCM (Pulse Code Modulation) is het standaard digitale audioformaat dat geluidsgolven met regelmatige intervallen bemonstert, gebruikt in uitzending en professionele opname.',
    ],
    [
      'Wat onderscheidt een digitale bioscoopprojector primair van filmprojectie?',
      ['Het gebruiken van elektronische beeldvormingstechnologie in plaats van mechanische filmprojectie', 'Het vereisen van speciaal vervaardigde zilveren projectieschermen', 'Het onvermogen om stereoscopische 3D-inhoud weer te geven', 'Het produceren van minder helderheid dan traditionele filmprojectoren'],
      0,
      'Digitale bioscoopprojectoren gebruiken elektronische beeldvormingstechnologie zoals DLP of lasers in plaats van mechanische filmprojectie, wat formaatflexibiliteit en gemakkelijkere distributie biedt.',
    ],
  ],
  msc: [
    [
      'Welke speelfilm uit 1985 bevat de scène die algemeen wordt gezien als het eerste volledig computer-gegenereerde personage in een live-action film?',
      ['Young Sherlock Holmes', 'Tron', 'The Last Starfighter', 'Flight of the Navigator'],
      0,
      'De glas-in-loodridder uit kerkraam in Young Sherlock Holmes (1985) werd gerenderd door Lucasfilm Graphics, onder leiding van John Lasseter. Dit personage wordt gezien als eerste volledig CG-personage in live-action.',
    ],
    [
      'Welke film uit 1995 wordt erkend als de eerste langspeelfilm die volledig met computeranimatie is gemaakt, zonder traditionele cel-animatie of live-action beelden?',
      ['Toy Story', 'Toy Story 2', 'A Bug\'s Life', 'The Lion King'],
      0,
      'Toy Story, uitgebracht door Pixar in november 1995, was eerste volledig CGI-film gerenderd met RenderMan. Film bewees CG-animatie langspeelverhaal kon dragen. Dit leidde tot deal voor tien films.',
    ],
    [
      'Welk non-lineair montagesysteem, uitgebracht in 1989 op Apple Macintosh II-hardware, werd het eerste NLE-systeem dat op grote schaal werd toegepast in de Hollywood-postproductie voor films en televisie?',
      ['Avid Media Composer', 'Lightworks', 'EditDroid', 'Final Cut Pro'],
      0,
      'Avid Media Composer gelanceerd 1989, vervangde Moviola als industriestandaard. Editors konden gedigitaliseerde beelden non-lineair op Mac monteren voordat conformering naar film.',
    ],
    [
      'Welke film uit 1992 was de eerste die in de bioscoop werd uitgebracht met een Dolby Digital 5.1-surroundgeluidsspoor?',
      ['Batman Returns', 'Terminator 2: Judgment Day', 'Jurassic Park', 'Star Trek VI: The Undiscovered Country'],
      0,
      'Batman Returns eerste film met Dolby Digital 5.1-surroundgeluid in bioscoop juni 1992. Zes kanalen digitale audio optisch gecodeerd op 35mm-kopie.',
    ],
    [
      'Wat is volgens de Digital Cinema Initiatives (DCI)-specificatie de pixelresolutie van het \'cinema 4K\'-digitale projectieformaat?',
      ['4096 x 2160', '3840 x 2160', '4096 x 2304', '4320 x 2160'],
      0,
      'DCI definieert cinema 4K als 4096x2160 versus consumenten 3840x2160. JPEG2000-compressie en XYZ-kleurruimte. Één digitale kopie op compatibele projector wereldwijd.',
    ],
    [
      'Het \'bullet time\'-effect in The Matrix (1999), waarbij een figuur in slow motion draait terwijl de camera hem lijkt te omcirkelen, werd voornamelijk bereikt met welke techniek?',
      ['Een reeks stilstaande camera\'s die in een getimede volgorde afgaan rondom het onderwerp', 'Een enkele high-speed filmcamera op een gemotoriseerde dollyrail', 'Real-time computer-gegenereerde dubbelgangers gecomponeerd over levende acteurs', 'Een draaiende rig van spiegels die één centrale camera weerspiegelen'],
      0,
      'Manex bouwde ongeveer 120 camera\'s in boog die synchroon afgingen. Elk beeld vastlegde andere hoek bevroren moment. Digitale interpolatie maakte vloeiende beweging.',
    ],
    [
      'Welke digitale cinemacamera, gelanceerd in 2007 tegen ongeveer een tiende van de prijs van vergelijkbare concurrenten, wordt algemeen gezien als de aanjager van betaalbare 4K-cinematografie onder onafhankelijke filmmakers?',
      ['RED One', 'Sony CineAlta F900', 'Panavision Genesis', 'ARRI D-20'],
      0,
      'RED One kwam 2007 op markt, legde 4K-beeld vast op compact flash tegen veel lagere prijs dan Sony/Panavision. Modulaire body trok onafhankelijke producties aan.',
    ],
    [
      'De Steadicam, een op het lichaam gemonteerde rig die vloeiende handheld tracking-shots zonder dollyrail mogelijk maakte, werd uitgevonden door wie?',
      ['Garrett Brown', 'Douglas Trumbull', 'Vilmos Zsigmond', 'Haskell Wexler'],
      0,
      'Garrett Brown ontwikkelde Steadicam halverwege jaren zeventig met harnas en veerarm isolerend camerabew eging. Hulpmiddel jaren-tachtig-cinematografie inclusief The Shining.',
    ],
    [
      'Welke digitale cinemacamera, geïntroduceerd in 2010, verving snel oudere tape- en CCD-gebaseerde systemen en werd een industriestandaard-werkpaard op Hollywood-producties gedurende de jaren 2010?',
      ['ARRI Alexa', 'Sony F65', 'RED Epic', 'Panavision Genesis'],
      0,
      'ARRI Alexa uitgebracht 2010 combineerde CMOS-sensor met kleurwetenschap en latitude van filmstock. ALEV-sensor en Log-C-encoding gaven breed dynamisch bereik.',
    ],
    [
      'De formaatoorlog in 2008 tussen HD-DVD en Blu-ray voor de volgende generatie thuisvideo werd grotendeels in het voordeel van Blu-ray beslecht na welke cruciale gebeurtenis?',
      ['Warner Bros. kondigde aan dat het films exclusief op Blu-ray zou uitbrengen', 'De FCC verklaarde Blu-ray tot het enige wettelijke HD-formaat', 'Netflix kondigde aan alleen nog Blu-ray-schijven per post te verzenden', 'Toshiba\'s HD-DVD-spelers werden terugroepen wegens brandgevaar'],
      0,
      'Warner Bros. kondigde in januari 2008 aan HD-DVD te laten vallen en toekomstige titels exclusief op Blu-ray uit te brengen. Dit deed steun van studios overslaan naar Sony\'s formaat. Blu-ray\'s aanwezigheid in PlayStation 3 gaf het al een grote installed base.',
    ],
    [
      'De vertolking van Gollum door Andy Serkis in The Lord of the Rings: The Two Towers (2002), gemaakt via motion capture op de set en CG-animatie, werd geproduceerd door welk visuele-effectenbedrijf?',
      ['Weta Digital', 'Industrial Light & Magic', 'Digital Domain', 'Rhythm & Hues'],
      0,
      'Weta Digital ontwikkelde motion-capture-pipeline waarmee Serkis vertolking Gollum aanstuurde. Vroege mijlpaal voor performance capture. Succes leidde tot Kong en Avatar.',
    ],
    [
      'Wat betekent de term \'digital intermediate\' (DI) in film-postproductie?',
      ['Het scannen van filmbeelden naar digitale vorm voor kleurcorrectie en effectenwerk, voordat het wordt uitgevoerd naar film of digitale formaten', 'De ruwe montage die aan een studio wordt getoond voordat visuele-effectenshots zijn afgewerkt', 'Een secundaire digitale audiomix die alleen wordt gebruikt voor thuisvideo-releases', 'De tussenfilmstock die wordt gebruikt om een cameranegatief te dupliceren'],
      0,
      'Het digital-intermediate-proces scant filmnegatief of leest digitale camerabestanden in tot hoge-resolutie formaat. Kleurcorrectie, effectcompositie en montagebeslissingen gebeuren digitaal voordat output naar nieuwe filmkopie of digital cinema package.',
    ],
    [
      'IMAX\'s digitale projectiesysteem, geïntroduceerd rond 2008 als alternatief voor het traditionele 70mm IMAX-filmformaat, gebruikt welke projectiemethode?',
      ['Twee gesynchroniseerde 2K digitale projectoren', 'Een enkele 8K-laserprojector met dubbele-lens optiek', 'Drievoudige 35mm-film die op hoge snelheid draait', 'Een enkele 4K DLP-projector met een breder gate-openingsformaat'],
      0,
      'IMAX Digital koppelde twee 2K digitale projectoren die synchroon draaiden in plaats van het veel grotere 15/70-filmformaat. Dit stelde meer bioscopen in staat goedkoop IMAX-schermen te installeren zonder kosten en logistiek van enorme filmkopieën.',
    ],
    [
      'Welke technologie, uitgebracht door Apple in 2009, werd de dominante methode waarmee streamingdiensten zoals Netflix een videostream leveren die de kwaliteit automatisch aanpast aan de wisselende internetverbinding van een kijker?',
      ['HTTP Live Streaming (HLS)', 'Real-Time Streaming Protocol (RTSP)', 'Flash Video (FLV) progressive download', 'BitTorrent-gebaseerde peer-distributie'],
      0,
      'HTTP Live Streaming, geïntroduceerd door Apple in 2009, breekt video op in segmenten met meerdere bitrates. De speler schakelt in real time tussen segmenten op basis van bandbreedte via gewone HTTP. Dit werd de basis voor Netflix, YouTube en andere platforms.',
    ],
    [
      'Dolby Atmos, een object-gebaseerd bioscoop-surroundformaat waarmee individuele geluidselementen onafhankelijk van vaste kanalen geplaatst en bewogen kunnen worden, ging in première in de bioscoop met welke film uit 2012?',
      ['Brave', 'The Avengers', 'The Hobbit: An Unexpected Journey', 'Skyfall'],
      0,
      'Dolby Atmos ging in première met Pixar\'s Brave in juni 2012 en introduceerde \'geluidsobjecten\' geplaatst in driedimensionale bioscoopruimte, inclusief overhead. Een renderer kaart objecten dynamisch af op hoeveel luidsprekers in elke zaal aanwezig zijn.',
    ],
  ],
  phd: [
    [
      'Pixar\'s eigen systeem, dat gedurende de jaren negentig werd gebruikt om traditioneel met de hand getekende animatiecellen digitaal in te kleuren en te composeren, en dat voor het eerst werd toegepast op The Rescuers Down Under (1990), heette hoe?',
      ['CAPS (Computer Animation Production System)', 'SoftImage, een op zichzelf staand 3D-animatiepakket dat niets met 2D-celwerk te maken heeft', 'Wavefront Explore, een vroeg Unix-gebaseerd 3D-render- en modelleergereedschap', 'Cintel Digital, een telecinescanner die wordt gebruikt om film naar video over te zetten'],
      0,
      'CAPS, gezamenlijk ontwikkeld door Pixar en Disney, verving het fotochemische proces van met de hand inkten en inkleuren. Kunstenaars konden gescande lijntekeningen digitaal kleuren en samenstellen met programmeerbare camerabewegingen. The Rescuers Down Under (1990) was eerste film ermee.',
    ],
    [
      'De transformatiescène van welke film uit 1988, geproduceerd door ILM, wordt algemeen gezien als de scène die de term \'morphing\' en de digitale vervorm/overvloei-techniek populair maakte, later veel uitgebreider gebruikt voor het vloeibare metalen T-1000 in Terminator 2?',
      ['Willow', 'The Abyss', 'Indiana Jones and the Last Crusade', 'Star Trek V: The Final Frontier'],
      0,
      'ILM-programmeur Doug Smythe schreef morphingsoftware voor Willow (1988), waarbij wezenstadia vervormd en overvloeide. Dit werd basis voor vloeibaar-metalen morphing in Terminator 2 (1991), waar T-1000 tussen vormen leek te smelten.',
    ],
    [
      'De machines van welke werkstationfabrikant, geprezen tot in de late jaren tachtig en jaren negentig vanwege hardware-versnelde 3D-graphics, waren het standaardplatform van ILM, Pixar en andere VFX-huizen voordat in de jaren 2000 werd overgestapt op Linux-gebaseerde PC-renderfarms?',
      ['Silicon Graphics (SGI)', 'Sun Microsystems', 'NeXT', 'Digital Equipment Corporation (DEC)'],
      0,
      'Silicon Graphics-werkstations met IRIX domineerden highend graphics tot jaren negentig vanwege hardware voor 3D-rendering. Zij waren achter iconisch werk bij ILM, Pixar, waaronder Jurassic Park. Begin jaren 2000 stapten studio\'s over op Linux-PC\'s die goedkoper waren.',
    ],
    [
      'Het Digital Cinema Package (DCP)-formaat dat door de DCI-specificatie wordt voorgeschreven, comprimeert beelddata met welke beeldcompressiestandaard?',
      ['JPEG2000', 'H.264/AVC', 'ProRes 4444', 'MPEG-2'],
      0,
      'DCI vereist elk beeld als onafhankelijk JPEG2000-beeld in plaats van inter-frame videocompressie. Dit vereenvoudigt decodering en vermijdt bewegingscompensatie-artefacten. DCP verpakt JPEG2000-beelden, PCM-audio, watermerken en AES-encryptie in MXF-container.',
    ],
    [
      'ARRI\'s Alexa-cameralijn biedt bij sommige modellen een echte \'global shutter\'-optie, die welk specifiek artefact vermijdt dat gebruikelijk is bij rolling-shutter CMOS-sensoren?',
      ['Scheeftrekking of \'jello\'-vervorming van snel bewegende objecten die regel voor regel in plaats van in één keer worden vastgelegd', 'Kleurmoirépatronen die ontstaan wanneer fijne herhalende texturen zoals stofweefsels aliasing veroorzaken tegen het pixelraster van de sensor', 'Verhoogde schaduwruis en verminderd detail in weinig licht door kleinere fotosites van de sensor', 'Verminderd dynamisch bereik en highlight roll-off door beperkte diepte van de fotosite-putten'],
      0,
      'Rolling-shutter-sensors lezen beeldrijen sequentieel, waardoor snelle beweging scheef lijkt (\'jello\'-vervorming). Global-shutter belicht alle pixels tegelijk, eliminerend scheeftrekking. Meeste cinemacamera\'s gebruiken rolling shutter en beheren artefact via sluiterhoek.',
    ],
    [
      'De real-time, in-camera visuele-effectentechniek gebruikt bij The Mandalorian (2019), die traditionele greenscreen verving door fotorealistische achtergronden die live worden gerenderd op een rondlopende LED-wand, staat bekend onder welke naam?',
      ['StageCraft', 'Volumetric Capture', 'The Volume Engine', 'LightCraft'],
      0,
      'StageCraft omringt acteurs met LED-wand weergevend omgevingen in real-time. Getrackt voor camera-positie. Correcte parallax zodat cinematografen belichting in-camera vastleggen.',
    ],
    [
      'Welke VFX-studio ontwikkelde de \'Massive\'-software die wordt gebruikt om autonome, individueel reagerende menigten van duizenden digitale personages te simuleren, voor het eerst ingezet voor de slagveldscènes in The Lord of the Rings: The Two Towers (2002)?',
      ['Weta Digital', 'Digital Domain', 'Framestore', 'Industrial Light & Magic'],
      0,
      'Weta Digital\'s Stephen Regelous bouwde Massive om tienduizenden soldaten/orks aan te animeren met eigen AI-logica. Menigten bewogen met organische variatie in plaats van gekopieerd-en-geplakte extra\'s. Massive werd daarna commercieel product voor menigte- en zwermsimulatiewerk.',
    ],
    [
      'Digitale verjonging van Robert De Niro over verschillende decennia in The Irishman (2019) leunde primair op welke visuele-effectenaanpak in plaats van gewone digitale make-up geschilderd over het echte gezicht van de acteur?',
      ['Gesynchroniseerde getuigecamera\'s die 3D-gezichtsdata vastleggen naast de hoofdcamera, gebruikt om digitaal een jonger gezicht te reconstrueren', 'Deepfake-achtige neurale-netwerk-gezichtswisseling getraind op archiefbeelden van de jongere versie van de acteur, frame voor frame toegepast in postproductie', 'Prosthetische siliconen make-up gecombineerd met kleurcorrectie en diffusiefilters om zichtbare huidtextuur op camera te verminderen', 'Dichte motion-capture-markers verspreid over het gezicht van de acteur die een volledig synthetische CG-digitale dubbelganger aansturen, gebouwd uit scandata'],
      0,
      'ILM bouwde aangepaste rig met drie getuigecamera\'s naast hoofdcamera om De Niro\'s gezicht vast te leggen. Dit genereerde 3D-data voor digitale reconstructie en verjonging zonder motion-capture-markers. Acteurs konden natuurlijk spelen terwijl VFX-kunstenaars jongere gezichten opbouwden.',
    ],
    [
      'Chroma-key-compositie geeft traditioneel de voorkeur aan groene of blauwe schermen boven andere kleuren, primair vanwege welke technische reden?',
      ['Groen en blauw liggen het verst van menselijke huidtinten en komen het minst voor in de meeste onderwerpen, waardoor ze het makkelijkst schoon uit te sleutelen zijn, terwijl groen specifiek ook een schonere matte geeft door hoe digitale sensoren kleur samplen', 'Groene en blauwe pigmenten waren historisch de goedkoopste en meest lichtbestendige verfkleuren om te fabriceren en te onderhouden op grote studioachtergronden gedurende lange opnameschema\'s', 'Groene en blauwe schermen reflecteren meetbaar minder infrarood licht, waarvan men dacht dat het het risico op hitteopbouw en overhitting door nabije wolfraambelichtingsapparatuur verminderde', 'Uitzendstandaarden, geërfd uit het analoge televisietijdperk, wijzen specifiek groen en blauw aan als de enige twee kleurtinten die keying- en encoderingsapparatuur volledig kan verwijderen zonder zichtbare compressie- of ringing-artefacten te introduceren'],
      0,
      'Blauw en groen liggen ver van huidtinten, dus makkelijk isoleerbaar. Groen is nu voorkeur omdat digitale sensoren Bayer-patroon gebruiken met twee keer zoveel groene fotosites, wat schoner kanaal voor matte opbouw geeft.',
    ],
    [
      'Dolby Vision en HDR10 zijn beide high-dynamic-range-videostandaarden, maar Dolby Vision onderscheidt zich vooral door welke technische functie?',
      ['Dynamische, per-scène metadata die het scherm vertelt hoe helderheid en kleur per shot moeten worden afgebeeld, in plaats van één statische waarde voor het hele programma', 'Een hoger maximaal helderheidsplafond van 10.000 nits versus HDR10\'s vaste, onveranderlijke limiet van 1.000 nits, uniform opgelegd aan alle ondersteunde content, schermen en masteringpipelines', 'Native mastering- en leveringsondersteuning voor volledige 12-bit kleurdiepte versus HDR10\'s vaste 8-bit diepte die overal in de metadatastandaard is gespecificeerd', 'Een verplichte weergave van 120 beelden per seconde, specifiek bedoeld om bewegingsonscherpte in zeer heldere highlightgebieden te verminderen'],
      0,
      'Beide gebruiken PQ-overdrachtsfunctie voor breder helderheidsbereik. HDR10 heeft statische metadata voor hele programma. Dolby Vision heeft dynamische metadata per scène/beeld, wat nauwkeurigere tone-mapping mogelijk maakt.',
    ],
    [
      'Voor The Hobbit: An Unexpected Journey (2012) filmde en bracht Peter Jackson de film uit met een hoge framerate van 48 beelden per seconde, met gebruik van welk digitaal cinemacamerasysteem om die framerate native in stereoscopische 3D vast te leggen?',
      ['RED Epic', 'ARRI Alexa Studio', 'Sony F65', 'Panavision Genesis'],
      0,
      'Hobbit-trilogie werd gefilmd op RED Epic-camera\'s, gekozen omdat zij native 48fps in stereoscopische 3D vastleggen. Jackson wilde strobing en bewegingsonscherpte van 3D-24fps verminderen. De ultravloeiende beweging werd echter als storend \'video-achtig\' ervaren.',
    ],
    [
      'Bij Avatar (2009) legde Weta Digital gedetailleerde gezichtsvertolking vast met een lichtgewicht headsetcamera gecombineerd met James Camerons previsualisatiesysteem op de set, waarmee hij door de zoeker acteurs kon zien samengesteld in de virtuele wereld in real time. Hoe heette dit real-time compositiesysteem?',
      ['Simulcam', 'Emotion Capture Suite', 'Contour Reality Capture', 'FaceRig'],
      0,
      'Simulcam-systeem van Cameron zag real-time compositie van acteurs tegen Pandora-omgeving terwijl er werd gefilmd. Gezichtsdata werd later gebruikt voor Na\'vi-animatie. Het systeem liet Cameron compositie en enscenering tegen virtuele wereld sturen.',
    ],
    [
      'DaVinci Resolve, nu de dominante professionele kleurgradingapplicatie, was oorspronkelijk gebouwd rond welke hardware-gebaseerde workflow voordat het vooral een softwaretool werd?',
      ['Een toegewijd hardware kleurcorrectiesysteem verkocht door da Vinci Systems, vooral gebruikt voor telecinewerk waarbij film naar video werd overgezet', 'Een plug-insuite die exclusief werd gebundeld met Avid Media Composer, specifiek gebruikt voor online montage-afwerking in plaats van standalone grading', 'Een clouddienst voor rendering die kleurgegradeerde dailies \'s nachts naar studio-executives en regisseurs streamde voor goedkeuring', 'Een propriëtair formaat om lookup-tables direct op fysieke filmnegatieven te coderen tijdens de printfase'],
      0,
      'Da Vinci Systems bouwde hardware kleurcorrectiesystemen voor telecine-suites. Blackmagic Design kocht het bedrijf in 2009, bouwde software opnieuw als Resolve en verlaagde prijs drastisch, uiteindelijk met gratis versie.',
    ],
    [
      'Het Academy Color Encoding System (ACES), ontwikkeld door de Academy of Motion Picture Arts and Sciences en sinds begin jaren 2010 in toenemende mate toegepast, lost primair welk productieprobleem op?',
      ['Een gestandaardiseerde, apparaatonafhankelijke kleurruimte waardoor beelden van verschillende camera\'s consistent gegradeerd kunnen worden, met een voorspelbaar pad naar elk uitvoerformaat', 'Verliesvrij comprimeren van raw camerabestanden met een door de studio voorgeschreven codec om opslag- en data-wranglingkosten op de set te verminderen bij grote multicamera-producties', 'Cryptografisch versleutelen van dailies-beelden tijdens transport van de set naar een externe postproductie- of VFX-faciliteit in het buitenland', 'Automatisch matchen van kleur, belichting en witbalans tussen shots gemonteerd uit verschillende takes van dezelfde scène tijdens de online-conformfase'],
      0,
      'ACES defineert apparaatonafhankelijke werkkleurruimte met gestandaardiseerde transforms voor camera\'s en schermen. Beelden van Alexa, RED en iPhone kunnen in dezelfde pipeline worden ingebracht voor output naar DCP, broadcast of toekomstig formaat.',
    ],
    [
      'Digitale \'draadverwijdering\' en rigverwijdering, die door de jaren negentig heen routinematige VFX-taken werden, werden primair mogelijk gemaakt door welke onderliggende beeldbewerkingstechniek?',
      ['Beeld-voor-beeld digitaal schilderen en klonen, getrackt door de shot, waarbij nabijgelegen achtergrondpixels over de draad of rig worden gelegd', 'Automatisch machine-learning inpainting getraind op een zeer grote database van vergelijkbare achtergrondtexturen, objectvormen en materiaalpatronen', 'Optische printtechnieken die een duplicaat-negatief fysiek opnieuw belichtten met de draad gemaskeerd via een met de hand gesneden matte', 'Chroma-key-verwijdering van draden die vooraf zijn geschilderd in een specifieke ultraviolet-reflecterende verf, alleen zichtbaar onder UV-belichting'],
      0,
      'Digitale draadverwijdering werkt beeld voor beeld door draadpad te tracken en erover heen te schilderen met nabijgelegen achtergrondpixels. Dit is handmatig-maar-tool-ondersteund proces. Werd vooral prominent bij wire-fu in The Matrix en Crouching Tiger.',
    ],
  ],
  professor: [
    [
      'De ASC-CDL (American Society of Cinematographers Color Decision List), een gestandaardiseerd metadataformaat voor draagbare basiskleurgradingbeslissingen, definieert een gradingaanpassing met precies welke drie parameters per kleurkanaal, plus één algemene waarde?',
      ['Slope, offset en power per RGB-kanaal, plus een algemene saturatiewaarde', 'Gain, gamma en pedestal per RGB-kanaal, plus een algemene contrastwaarde', 'Lift, gamma en gain per RGB-kanaal, plus een algemene belichtingswaarde', 'Hue, saturatie en luminantie per RGB-kanaal, plus een algemene witbalanswaarde'],
      0,
      'ASC-CDL definieert kleurcorrectie als slope (gain-achtig), offset (lift-achtig) en power (gamma-achtig) per RGB, plus saturatieaanpassing. Dit draagbare parameterset kan reizen tussen softwarepakketten als XML zonder propriëtaire effectinbakking.',
    ],
    [
      'Pixar\'s RenderMan-renderer, fundamenteel voor bijna alle grote CG-langspeelanimatie door de jaren negentig en 2000 heen, was oorspronkelijk gebouwd rond welk render-algoritme voordat latere versies path tracing en ray tracing-ondersteuning toevoegden?',
      ['REYES (Renders Everything You Ever Saw), een op micropolygonen gebaseerd scanline-render-algoritme', 'Photon mapping gecombineerd met irradiance caching om globale belichting te benaderen voor offline rendering', 'Radiosity-gebaseerde eindige-elementenrendering die diffuse lichttransport oplost over polygoonpatches', 'Signed-distance-field ray marching, een techniek die meer wordt geassocieerd met procedurele en demoscene-rendering'],
      0,
      'REYES verdeelt oppervlakken in micropolygonen ter grootte van pixel en shadt efficiënt in scanline-pipeline. Dit was sneller dan ray tracers voor rijk geschaduwde oppervlakken. RenderMan voegde in 2014 path tracing (RIS) toe voor fysica-gebaseerde rendering.',
    ],
    [
      'De Digital Light Processing (DLP)-chip van Texas Instruments, gebruikt in de meeste digitale bioscoopprojectoren, vertrouwt op welk kerncomponent om een beeld te vormen?',
      ['Een digital micromirror device (DMD): een chip bedekt met miljoenen scharnierende spiegeltjes die kantelen om licht naar of weg van de lens te weerspiegelen', 'Een liquid-crystal-paneel, vaak met LCOS (liquid crystal on silicon)-technologie, dat de polarisatie van licht dat door elke pixel gaat draait om te regelen hoeveel licht de lens bereikt', 'Een reeks individueel adresseerbare laserdiodes die direct op het schermoppervlak worden gericht zonder enige tussenliggende beeldvormende chip', 'Een fosforgecoate beeldbuis die drie afzonderlijke kleurenstralen in rasterregels over het scherm scant'],
      0,
      'DLP Cinema gebruikt digital micromirror device: chip met miljoen spiegeltjes die duizenden per seconde kantelen. Aan-tijd per spiegeltje bepaalt waargenomen helderheid. Dit verschilt van LCD/LCOS die licht via polarisatie moduleert.',
    ],
    [
      'In JPEG2000, de compressiestandaard die verplicht is voor Digital Cinema Packages, wordt beelddata getransformeerd met welke wiskundige techniek, ter onderscheiding van de discrete cosinustransformatie die in JPEG en MPEG wordt gebruikt?',
      ['De discrete wavelettransformatie (DWT)', 'De Hadamard-transformatie', 'Fast Fourier transform (FFT) met adaptieve kwantisatie', 'Vectorkwantisatie tegen een vaste codeboek'],
      0,
      'JPEG2000 gebruikt discrete wavelettransformatie in plaats van DCT, die beeld ontleedt in resolutie-subbanden. Dit vermijdt blokkerige macroblok-artefacten en maakt soepelere kwaliteitsdegradatie mogelijk. Per-beeld-onafhankelijke compressie vereenvoudigt bioscoop-projectie.',
    ],
    [
      'De AV1-videocodec, ontwikkeld door de Alliance for Open Media en sinds eind jaren 2010 in toenemende mate gebruikt door grote streamingplatforms, werd primair gemaakt om welk probleem op te lossen voor de bedrijven die erachter staan?',
      ['De licentievergoedingen vermijden die worden geheven voor HEVC (H.265) door een even efficiënte, royaltyvrije open codec aan te bieden', 'Framerates boven 120fps mogelijk maken, wat de specificatie van HEVC hard beperkt tot 60fps', '16-bit kleurdiepte ondersteunen, wat de specificatie van HEVC beperkt tot 10-bit', 'De decodeervertraging voor live sportuitzendingen verminderen tot onder wat enige eerdere codec kon bereiken'],
      0,
      'HEVC raakte verstrikt in duur patentlicentielandschap. Google, Netflix, Amazon en Microsoft vormden Alliance for Open Media en brachten AV1 uit als royaltyvrij alternatief. AV1 behaalt betere compressie-efficiëntie tegen hogere computationele kosten.',
    ],
    [
      'Cinemaformaten met hoge framerate zoals 48fps of 60fps kampen met een uitdaging die verband houdt met hoe beelden beweging samplen: welk visueel artefact vermindert het verhogen van de opnamesnelheid primair vergeleken met traditionele 24fps?',
      ['Bewegingsonscherpte en strobing bij snel bewegende onderwerpen of pans, omdat elk beeld een kortere tijdsschijf integreert relatief aan de beweging', 'Kleurbanding over vloeiende verlopen veroorzaakt door onvoldoende bitdiepte per gecodeerd beeld bij hogere framerates', 'Chromatische aberratie geïntroduceerd door camerelementen die niet snel genoeg opnieuw kunnen scherpstellen tussen snel opeenvolgende belichtingen bij verhoogde opnamesnelheden', 'Rolling-shutter-scheeftrekking specifiek voor de uitleestiming van CMOS-sensoren, die geen verband heeft met de gekozen framerate'],
      0,
      'Hogere framerate verkort tijd per beeld, vermindert bewegingsonscherpte en strobing. Dit produceert vloeiender, scherper beeld. Afweging: verminderde onscherpte kan onwezenlijk \'vloeiend\' of \'video-achtig\' lijken.',
    ],
    [
      'Volumetrische opnamerigs, gebruikt om volledig driedimensionale, viewpoint-onafhankelijke digitale opnames van een live vertolking te maken voor VR- en virtuele-productiepipelines, vertrouwen doorgaans op welke kernopnameopstelling?',
      ['Een grote reeks gesynchroniseerde camera\'s, vaak van tientallen tot meer dan honderd, rondom het onderwerp, waarvan de beelden worden gecombineerd tot een 3D-mesh met textuur per beeld', 'Een enkele hoge-resolutie LIDAR-scanner die langzaam roterend rondom het stilstaande onderwerp veegt', 'Een stereocamerapaar gecombineerd met een inertiaal motion-capturepak dat direct door de vertolker wordt gedragen', 'Een consumentendieptesensor van hetzelfde basistype dat in motiongaminghardware wordt gebruikt, maar aanzienlijk opgeschaald in resolutie, framerate en effectief opnamebereik voor professioneel gebruik'],
      0,
      'Volumetrische opnamestudio\'s omringen vertolker met tientallen tot honderd camera\'s plus dieptesensoren. Software reconstrueert volledige 3D-mesh per beeld. Asset kan vanuit elke hoek in real-time bekeken en herbelicht worden.',
    ],
    [
      'Neural radiance fields (NeRF), een machine-learningtechniek die een fotorealistische 3D-scène reconstrueert uit een set 2D-foto\'s, hebben vroege experimentele adoptie gezien in VFX- en virtuele-productiepipelines primair voor welk doel?',
      ['Het genereren van fotorealistische, vrij navigeerbare 3D-achtergronden of decor-uitbreidingen uit gewone foto\'s, zonder geometrie met de hand te modelleren', 'Automatisch dialoog-nauwkeurig gesynchroniseerde lipsync-gezichtsanimatie genereren uit een audiospoor, met een apart getraind neuraal-netwerkmodel dat losstaat van de scènereconstructiepipeline', 'Traditionele motion-capturemarkers vervangen door skelet-poseschatting vanuit een enkele ongemarkeerde handheldcamera', 'Verliesvrij comprimeren van raw camerabeelden voor goedkopere langetermijnarchivering op studioservers'],
      0,
      'NeRF traint neuraal netwerk om straling en dichtheid van scène te representeren als continue functie. Renderer genereert fotorealistische nieuwe aanzichten. Dit is sneller alternatief voor fotogrammetrie en handmatig omgevingsmodelleren voor achtergronden en LED-volume-content.',
    ],
    [
      'IMAX\'s laserverlichte digitale projectiesysteem, geïntroduceerd om het kwaliteitsverschil met traditionele 70mm IMAX-film te dichten, verbetert primair op welk specifiek punt ten opzichte van eerdere xenonlamp-digitale projectie?',
      ['Aanzienlijk hogere haalbare contrastverhouding en zwartniveaus, samen met een breder kleurengamma, in plaats van simpelweg hogere raw-resolutie', 'Een verdubbeling van de maximale framerate van 60fps naar 120fps voor vloeiendere beweging', 'De mogelijkheid om voor het eerst in echte 15/70-filmequivalente resolutie te projecteren vanuit een digitale bron', 'Het elimineren van de noodzaak van een zilverbekleed projectiescherm dat voorheen vereist was voor 3D-vertoningen'],
      0,
      'IMAX-laserprojectiesystemen gebruiken laserlichtbronnen in plaats van xenonlampen, mogelijk makend diepere zwartniveaus en hogere contrastverhoudingen met breder kleurengamma. Dit pakt kritiek aan dat digitale IMAX vlak overkwam versus 70mm.',
    ],
    [
      'SMPTE ST 2084, de overdrachtsfunctie die ten grondslag ligt aan zowel HDR10 als Dolby Vision, is beter bekend onder welke naam, verwijzend naar het perceptueel-gebaseerde ontwerpdoel?',
      ['De Perceptual Quantizer (PQ)-curve', 'De Hybrid Log-Gamma (HLG)-curve', 'De Rec. 709-gammacurve', 'De S-Log3-overdrachtsfunctie'],
      0,
      'Perceptual Quantizer kaart codewaarden af op absolute helderheidsniveaus volgens menselijk contrastgevoeligheid over breder bereik. HDR10 en Dolby Vision kunnen highlights veel helderder dan 100 nits SDR-referentie specificeren.',
    ],
    [
      'Hoeveel discrete audio-elementen kan een Dolby Atmos bioscoopmix gelijktijdig bevatten, waarbij traditionele kanaalbedden worden gecombineerd met onafhankelijk gepositioneerde geluidsobjecten, volgens Dolby\'s gepubliceerde specificatie?',
      ['Tot 128 gelijktijdige audio-elementen, een mix van kanaalgebaseerde bedden en dynamische objecten', 'Tot 64 gelijktijdige audio-elementen', 'Tot 256 gelijktijdige audio-elementen', 'Een onbeperkt aantal, alleen beperkt door het beschikbare spooraantal van de mixengineer'],
      0,
      'Dolby Atmos-bioscoopspecificatie staat tot 128 gelijktijdige audio-elementen toe, mix van bedkanalen en dynamisch gepositioneerde objecten. Renderer beeldt objecten af op zaalconfiguratie. Master schaalt correct van multiplex tot vlaggenschip zonder apart mengsel.',
    ],
    [
      'Weta Digital\'s renderfarm voor Avatar (2009), een van de grootste toegewijde renderfarms die destijds ooit voor één film was samengesteld, draaide op welk besturingssysteem?',
      ['Linux, een cluster van Linux-gebaseerde renderblades', 'Een aangepaste fork van IRIX, specifiek onderhouden door Weta', 'Windows Server, gekozen voor compatibiliteit met Autodesk\'s Maya', 'Solaris, geërfd van Weta\'s eerdere Sun Microsystems-infrastructuur'],
      0,
      'Weta Digital\'s renderfarm met ongeveer 40.000 processorkernen draaide op Linux, weerspiegelend bredere verschuiving van propriëtaire Unix naar Linux-gebaseerde commodity-hardware. Dit liet goedkoper opschalen dan propriëtaire hardware, mogelijk makend complexere CG-omgevingen.',
    ],
    [
      'Het Bayer-filterpatroon, bijna universeel op digitale camera\'s met één sensor, waaronder de meeste cinemacamera\'s, rangschikt kleurfilters over fotosites in welke verhouding rood, groen en blauw?',
      ['Één rood, twee groene en één blauw filter per herhalend 2x2-blok, dus twee keer zoveel groene fotosites als rode of blauwe', 'Een gelijke verdeling van één rood, één groen, één blauw herhaald over een 3x3-blok, met de vierde cel ongefilterd gelaten voor luminantie', 'Twee rode en twee blauwe fotosites die afwisselen in schaakbordpatroon, waarbij groen volledig wordt afgeleid via interpolatie van beide', 'Één rood, één groen, één blauw en één toegewijde witte ongefilterde fotosite per herhalend 2x2-blok'],
      0,
      'Bayer-patroon gebruikt 2x2-blok met twee groene fotosites tegenover elkaar, plus één rood en één blauw. Menselijk oog is gevoeligst voor groen, dus verdubbeling vergt waargenomen scherpte. Camera interpoleert ontbrekende kleur per fotosite.',
    ],
    [
      'Gaussian splatting, een real-time 3D-scènereconstructie- en rendertechniek die rond 2023 opkwam als sneller alternatief voor NeRF, representeert een vastgelegde scène als welk soort onderliggende datastructuur?',
      ['Een grote verzameling doorschijnende 3D-Gaussische ellipsoïden, elk met positie, schaal, oriëntatie en kleur, geoptimaliseerd om de bronfoto\'s te reproduceren', 'Een dicht voxelraster dat per-voxel opaciteit en kleurwaarden opslaat, uniform gesampled met een vaste ruimtelijke resolutie door de hele scène', 'Een enkele continue neurale-netwerkfunctie die per pixel wordt opgevraagd bij het renderen, structureel en architectonisch identiek aan NeRF\'s impliciete representatie maar geïmplementeerd met een kleiner, sneller netwerk', 'Een traditioneel getextureerd polygoonmesh gegenereerd via multi-view fotogrammetrie, met Gaussiaanse vervaging alleen toegepast op ver weg liggende achtergrondgeometrie'],
      0,
      'Gaussian splatting representeert scène als miljoenen 3D-Gaussische ellipsoïden met positie, schaal, oriëntatie en kleur. Dit rendert nieuwe gezichtspunten extreem snel via direct splatten. Combinatie van kwaliteit en snelheid maakt het aantrekkelijk voor LED-volumes.',
    ],
    [
      'In de broadcasttechniek bestaat de \'drop-frame\'-variant van SMPTE-timecode specifiek om welke discrepantie op te lossen?',
      ['NTSC\'s werkelijke framerate van 29,97fps tegenover een timecodeteller die in gehele stappen van 30fps telt, wat anders zou afwijken van de werkelijke verstreken klokijd', 'Het verschil tussen PAL\'s uitzendstandaard van 25 beelden per seconde en films traditionele 24fps-snelheid bij het converteren van Europese broadcast-masters voor Noord-Amerikaanse bioscoop- en thuisvideodistributie', 'Audio-samplerateafwijking tussen opnames van 48kHz en 44,1kHz die gesynchroniseerd zijn op hetzelfde productietimecode-spoor', 'De kleine afwijking die wordt geïntroduceerd wanneer de 24fps-master van een digital cinema package wordt vertoond op de licht afwijkende zaalframerate van een bioscoop'],
      0,
      'NTSC-video is 29,97fps niet 30fps, verlaging van 1953 voor signaalinterferentie. Timecodeteller op 30fps zou over lang programma afwijken. Drop-frame compenseert door beeldnummers over te slaan (niet video), houdt timecode gesynchroniseerd met werkelijke klokijd.',
    ],
  ],
};
