import type { CategoryContent } from './row.js';

/**
 * Fashion & Fashion History (1940-Now), Historic Fashion (Early Middle Ages-1850).
 */

export const FASHION_MODERN: CategoryContent = {
  bscba: [
    [
      'Which designer is most famous for the "New Look" silhouette of the 1940s, featuring a cinched waist and full skirt?',
      ['Christian Dior', 'Cristóbal Balenciaga', 'Coco Chanel', 'Pierre Cardin'],
      0,
      'Dior\'s 1947 debut collection revolutionized postwar fashion with its emphasis on a narrow waist and voluminous skirt, using unprecedented amounts of fabric after years of wartime rationing.',
    ],
    [
      'What synthetic fiber, patented in 1958, allowed garments to stretch and recover, transforming the design of swimwear and activewear?',
      ['Lycra/Spandex', 'Nylon', 'Rayon', 'Polyester'],
      0,
      'DuPont\'s Lycra, or spandex, could stretch to several times its length and snap back, revolutionizing close-fitting garments without need for complex tailoring techniques.',
    ],
    [
      'Which 1960s British designer popularized the miniskirt through her King\'s Road boutique, Bazaar?',
      ['Mary Quant', 'Yves Saint Laurent', 'André Courrèges', 'Pierre Cardin'],
      0,
      'Mary Quant\'s miniskirts reached a young, working-class audience in London and made her designs a symbol of 1960s youth culture and British fashion independence.',
    ],
    [
      'What innovative fiber was developed by W.L. Gore in 1969 and became essential to weatherproof, breathable outdoor fashion?',
      ['Gore-Tex', 'Neoprene', 'Tyvek', 'Polar fleece'],
      0,
      'Gore-Tex\'s microporous membrane blocked water while allowing vapor to escape, becoming crucial to technical and later high-fashion outerwear design.',
    ],
    [
      'Which 1993 Perry Ellis collection, featuring flannel and slip dresses in luxury fabrics, got its designer fired shortly after showing?',
      ['Marc Jacobs', 'Todd Oldham', 'Isaac Mizrahi', 'Anna Sui'],
      0,
      'Marc Jacobs remade grunge subculture in couture-grade materials, a vision the brand\'s corporate owners rejected despite later recognition as a fashion landmark.',
    ],
    [
      'What group of Belgian designers, graduating from Antwerp\'s Royal Academy, gained international attention in the 1980s?',
      ['The Antwerp Six', 'The Amsterdam Collective', 'Brussels Design Union', 'Ghent Guild Members'],
      0,
      'Six Belgian graduates including Dries Van Noten showed together in London and established Antwerp as a serious fashion training ground distinct from Paris and Milan.',
    ],
    [
      'In 1987, Louis Vuitton merged with which company to form the modern LVMH conglomerate?',
      ['Moët Hennessy', 'Christian Dior SE', 'Kering (then PPR)', 'Richemont'],
      0,
      'The merger of Louis Vuitton with Moët Hennessy created the model for a multi-brand luxury holding company that later expanded to control numerous heritage houses.',
    ],
    [
      'What term describes the late 1980s through mid-2000s trend of luxury bags and accessories covered in large, visible monogram logos?',
      ['Logomania', 'Brand saturation', 'Visual merchandising', 'Luxury maximalism'],
      0,
      'Logomania emphasized brand recognition itself as the primary selling point, particularly with monogram prints from Louis Vuitton, Gucci, and Dior.',
    ],
    [
      'In 1994, which designer took over creative direction of Gucci and revived the struggling Italian house through sleek minimalism?',
      ['Tom Ford', 'Domenico Dolce', 'Marco Bizzarri', 'Frida Giannini'],
      0,
      'Ford\'s body-conscious tailoring and sexually charged aesthetic transformed Gucci into one of the fastest-growing luxury brands of the late 1990s.',
    ],
    [
      'What does the term "fast fashion" refer to in the modern retail industry?',
      ['Rapid design-to-store production cycles', 'Expensive limited editions', 'Handmade artisanal garments', 'Seasonal clearance sales'],
      0,
      'Fast fashion describes the ability to move designs from concept to retail shelves in weeks rather than months, pioneered by retailers like Zara.',
    ],
    [
      'Which 1970s minimalist designer became famous for elegant shirtdresses made from a suede-like synthetic fabric called Ultrasuede?',
      ['Halston', 'Calvin Klein', 'Donna Karan', 'Ralph Lauren'],
      0,
      'Halston\'s fluid, unstructured designs in Ultrasuede became a Studio 54 signature and defined minimalist luxury fashion of the 1970s.',
    ],
    [
      'Which Japanese designer launched the Pleats Please line in 1993, featuring permanently heat-set pleats?',
      ['Issey Miyake', 'Rei Kawakubo', 'Yohji Yamamoto', 'Kenzo Takada'],
      0,
      'Miyake\'s innovation involved cutting oversized garments then heat-pressing them to set permanent pleats that allowed stretch and recovery without elastic fibers.',
    ],
    [
      'Alexander McQueen served as head designer at which historic Paris couture house from 1996 to 2001?',
      ['Givenchy', 'Dior', 'Balenciaga', 'Chloé'],
      0,
      'McQueen\'s tenure at Givenchy was marked by creative tension with the house\'s conservative clientele before he departed to focus on his own Gucci-backed label.',
    ],
    [
      'Vivienne Westwood and Malcolm McLaren\'s King\'s Road boutique was called what during its punk-era phase from 1974 to 1976?',
      ['SEX', 'Let It Rock', 'Seditionaries', 'World\'s End'],
      0,
      'The SEX shop sold rubber, bondage straps, and safety-pinned fabrics that directly fed punk aesthetics and became foundational to street-fashion history.',
    ],
    [
      'Which Italian luxury brand\'s 1985 black nylon backpack, using industrial textile, launched its modern "quiet luxury" identity?',
      ['Prada', 'Bottega Veneta', 'Bally', 'Ferragamo'],
      0,
      'Prada\'s deliberately unglamorous nylon inverted 1980s luxury codes by signaling insider knowledge rather than obvious wealth display.',
    ],
  ],
  msc: [
    [
      'Christian Dior\'s spring/summer 1947 collection, which the press immediately dubbed the "New Look," was officially named what by Dior himself?',
      ['Corolle', 'Bar Suit', 'Trapeze', 'H-Line'],
      0,
      'Dior called his debut collection "Corolle" (with a companion line "En Huit"), named for the flower-corolla silhouette of its cinched waist and voluminous skirt; it was Harper\'s Bazaar editor-in-chief Carmel Snow who, on seeing it, exclaimed it was such a new look, and that press nickname stuck.',
    ],
    [
      'Which stretch fiber, patented by DuPont chemist Joseph Shivers in 1958 and sold under the trade name Lycra, revolutionized close fit in fashion and activewear?',
      ['Spandex', 'Nylon', 'Rayon', 'Qiana'],
      0,
      'Shivers developed a segmented polyurethane fiber that stretches to several times its length and snaps back, and DuPont marketed it from 1958 as Lycra; the generic names spandex and elastane refer to the same fiber class.',
    ],
    [
      'Alexander McQueen served as chief/head designer at which historic Paris couture house from 1996 to 2001, before departing to build his own label with backing from the Gucci Group?',
      ['Givenchy', 'Dior', 'Chloé', 'Balenciaga'],
      0,
      'McQueen was appointed head designer at Givenchy in 1996, succeeding John Galliano, who left to take over at Dior in the same reshuffle. McQueen\'s tenure there was famously uneasy: he found the house\'s clientele conservative for his darker, tailoring-driven aesthetic, and he openly clashed.',
    ],
    [
      'Yves Saint Laurent\'s celebrated 1965 collection translated shift dresses into color-blocked panels referencing which early-20th-century art movement, associated with painter Piet Mondrian?',
      ['De Stijl', 'Cubism', 'Constructivism', 'Bauhaus'],
      0,
      'Saint Laurent\'s autumn 1965 "Mondrian" dresses used the grid of black lines and primary-color rectangles from Piet Mondrian\'s paintings, which belong to the Dutch De Stijl movement (Mondrian\'s own theoretical branch of it was called Neoplasticism).',
    ],
    [
      'Which designer\'s spring 1993 "grunge" collection for Perry Ellis, built from thrift-store flannel and slip dresses in luxury fabrics, got him fired from the label within days of the show?',
      ['Marc Jacobs', 'Anna Sui', 'Todd Oldham', 'Isaac Mizrahi'],
      0,
      'Marc Jacobs, then Perry Ellis\'s design director, sent flannel shirts, combat boots, and knit caps down the runway rendered in cashmere and silk, taking Pacific Northwest grunge style and remaking it in couture-grade materials.',
    ],
    [
      'The "Antwerp Six," a group of Belgian avant-garde designers who drew international attention showing in London in the mid-to-late 1980s, included which of these designers?',
      ['Dries Van Noten', 'Rick Owens', 'Yohji Yamamoto', 'Riccardo Tisci'],
      0,
      'The Antwerp Six were Belgian graduates of the Royal Academy of Fine Arts in Antwerp: Dries Van Noten, Ann Demeulemeester, Dirk Bikkembergs, Walter Van Beirendonck, Dirk Van Saene, and Marina Yee, who traveled together to show in London and were nicknamed as a group by the British press.',
    ],
    [
      'Mary Quant, whose King\'s Road boutique Bazaar helped popularize the miniskirt in 1960s London, publicly shared credit for (and disputed sole ownership of) the style with which Paris-based designer, whose own high-fashion above-the-knee designs appeared around the same time?',
      ['André Courrèges', 'Yves Saint Laurent', 'Pierre Cardin', 'Paco Rabanne'],
      0,
      'Quant said the miniskirt was simply "in the air" in the mid-1960s and repeatedly named André Courrèges as the other main claimant, since his sleek, architectural above-the-knee shift dresses appeared on the Paris runway at almost the same moment her King\'s Road designs were reaching ordinary.',
    ],
    [
      'LVMH, the world\'s largest luxury conglomerate, was formed in 1987 through the merger of Louis Vuitton with which other major French company?',
      ['Moët Hennessy', 'Christian Dior SE', 'Kering (then PPR)', 'Richemont'],
      0,
      'Louis Vuitton, the leather goods maker, merged with Moët Hennessy, itself a 1971 combination of champagne house Moët & Chandon and cognac maker Hennessy, to form Louis Vuitton Moët Hennessy in 1987.',
    ],
    [
      'Rei Kawakubo\'s Comme des Garçons spring/summer 1997 collection, officially titled "Body Meets Dress, Dress Meets Body" and nicknamed "Lumps and Bumps," used goose-down padding sewn into garments to do what?',
      ['Distort the body\'s silhouette with irregular padded protrusions', 'Create exaggerated hourglass corsetry underneath tailored suits', 'Emphasize 1980s-style structured shoulder padding', 'Produce trompe l\'oeil printed illusions of a padded body'],
      0,
      'Kawakubo inserted lumps of down padding at seemingly random points on otherwise plain stretch garments, creating bulges at the back, hip, or shoulder that had nothing to do with conventional tailoring or flattering the wearer\'s actual shape.',
    ],
    [
      'Which waterproof-breathable membrane, developed by W.L. Gore and Robert Gore in 1969 and later trademarked as Gore-Tex, became essential to technical and outdoor-influenced fashion?',
      ['Gore-Tex', 'Tyvek', 'Neoprene', 'Polar fleece'],
      0,
      'Robert Gore discovered that rapidly stretching heated polytetrafluoroethylene (PTFE, the same polymer as Teflon) created a porous membrane with holes small enough to block liquid water but large enough to let water vapor escape, giving a fabric that was both waterproof and breathable, an.',
    ],
    [
      'Which quote, attributed to supermodel Linda Evangelista in a 1990 interview about her and Christy Turlington\'s daily rates, became emblematic of the excess of the late-1980s/early-1990s supermodel era?',
      ['"We don\'t wake up for less than $10,000 a day"', '"Never work for scale"', '"Beauty is pain"', '"Fashion fades, only style remains the same"'],
      0,
      'Evangelista made the remark to Vogue in 1990, and it was widely repeated afterward as shorthand for how a small handful of models, including Evangelista, Turlington, Naomi Campbell, Cindy Crawford, and Claudia Schiffer, had become genuine celebrities commanding fees once reserved for movie stars.',
    ],
    [
      'Tom Ford served as creative director of which Italian house from 1994 to 2004, credited with reviving its commercial fortunes through sleek, sexually charged minimalism?',
      ['Gucci', 'Yves Saint Laurent', 'Balenciaga', 'Bottega Veneta'],
      0,
      'Ford joined Gucci in 1990 and was promoted to creative director in 1994, when the house was near bankruptcy, and his glossy, body-conscious tailoring alongside Domenico De Sole\'s business leadership turned Gucci into one of the fastest-growing luxury brands of the late 1990s.',
    ],
    [
      'The now-standard fashion industry term "fast fashion" was reportedly coined by the New York Times in 1989 to describe which Spanish retailer\'s roughly 15-day design-to-store turnaround?',
      ['Zara', 'H&M', 'Topshop', 'Forever 21'],
      0,
      'The New York Times used the phrase in a 1989 piece describing how Zara could move a garment from initial sketch onto a store rail in about fifteen days, a turnaround so much faster than the industry\'s usual six-to-twelve-month lead times that it needed a new label of its own.',
    ],
    [
      'Vivienne Westwood and Malcolm McLaren\'s King\'s Road boutique, most associated with launching British punk fashion when it traded under this name from 1974 to 1976, was called what?',
      ['SEX', 'Let It Rock', 'Too Fast to Live Too Young to Die', 'World\'s End'],
      0,
      'The shop at 430 King\'s Road went through several name changes reflecting Westwood and McLaren\'s shifting obsessions, opening as Let It Rock (1971, selling teddy-boy revival clothes), becoming Too Fast to Live Too Young to Die (1972, biker-themed), then SEX (1974-76, fetish and bondage gear.',
    ],
    [
      'Halston\'s signature 1970s minimalist shirtdresses often used a suede-like synthetic fabric developed by the Japanese company Toray, prized for draping without any animal hide. What was it called?',
      ['Ultrasuede', 'Qiana', 'Ottoman silk', 'Ban-Lon'],
      0,
      'Ultrasuede, a nonwoven microfiber fabric, was developed by Toray Industries and gave designers the soft hand and matte look of suede leather without the weight, cost, or stiffness of the real material, letting it drape close to the body the way Halston\'s fluid, unstructured silhouettes required.',
    ],
  ],
  phd: [
    [
      'John Galliano\'s spring 2000 haute couture collection for Dior, which drew controversy for referencing the appearance and layered clothing of Paris\'s homeless population, was popularly known by what nickname?',
      ['The "clochard" (tramp) collection', 'The Ballets Russes collection', 'The French Revolution collection', 'The Marie Antoinette collection'],
      0,
      'Galliano sent models down the runway in newspaper-print gowns, tattered layers, and bag-lady-style wrapping inspired by Paris\'s homeless ("clochards"), a reference he said came from genuine research and even conversations with people living on the street, though critics accused him of.',
    ],
    [
      'Martin Margiela\'s work through the 1990s is frequently cited as pioneering fashion "deconstruction." Which technique is most associated with that reputation, exemplified by his 1997 collection built from white cotton toiles resembling tailor\'s dummies?',
      ['Exposing raw seams and construction marks instead of hiding them', 'Draping exclusively on the bias to eliminate darts', 'Laser-cutting all fabric edges to prevent any fraying at the seams', 'Sculpting garments directly onto a live model\'s body (moulage)'],
      0,
      'Margiela left seams unfinished, showed interior linings and construction lines on the outside of garments, and in the famous 1997 "Stockman" collection built pieces to look like the blank canvas dressmaker\'s dummies (branded Stockman, a real French mannequin manufacturer) rather than finished.',
    ],
    [
      'Issey Miyake\'s Pleats Please line, launched in 1993, reversed the traditional order of pleating a garment. What made its technique unusual?',
      ['The fabric was cut and sewn oversized first, then heat-pressed into pleats that shrank it to final size', 'The fabric was pleated first using a heated press, then cut and sewn according to a paper pattern', 'Pleats were laser-etched directly into the fabric\'s surface without any heat-press treatment at all', 'Pleats were created using a computer-controlled seamless knitting machine rather than heat-pressing'],
      0,
      'Ordinary pleating pleats the fabric first and then cuts and sews the pattern from it, but Miyake\'s team cut and constructed the garment two to three times larger than its finished size out of polyester, then sandwiched it between paper and heat-pressed it, permanently setting the pleats and.',
    ],
    [
      'The Paris fashion press coined a dismissive nickname for the stark, asymmetrical, largely black, deliberately unfinished tailoring shown by Rei Kawakubo and Yohji Yamamoto in the early 1980s. What was it?',
      ['"Hiroshima chic"', '"Le Grunge"', 'Anti-fashion minimalism', 'Post-punk deconstruction'],
      0,
      'When Kawakubo and Yamamoto showed in Paris in 1981-82, French critics, unsettled by torn, frayed, monochrome garments that rejected Western tailoring\'s fitted, symmetrical ideals, derisively nicknamed the look "Hiroshima chic," implying it resembled clothing from atomic bomb survivors, a.',
    ],
    [
      'The 1966 tuxedo suit for women known as "Le Smoking," a landmark in unisex tailoring worn to formal occasions where trousers on women were still unusual, was created by which designer?',
      ['Yves Saint Laurent', 'Pierre Cardin', 'André Courrèges', 'Paco Rabanne'],
      0,
      'Saint Laurent introduced Le Smoking in his 1966 collection, adapting the classic men\'s dinner jacket for a female silhouette while keeping its satin lapels and structured tailoring intact, and it became one of his most repeated motifs, reappearing across his collections for decades afterward.',
    ],
    [
      'Which luxury conglomerate, formerly Pinault-Printemps-Redoute (PPR), rebranded to its current name in 2013 to reflect its shift away from retail toward a pure luxury and sport portfolio?',
      ['Kering', 'Richemont', 'LVMH', 'Compagnie Financière Richemont'],
      0,
      'PPR, controlled by the Pinault family, had spent the 2000s and early 2010s selling off its department-store and mail-order retail businesses (including Printemps and Redcats) while building up its luxury and sportswear holdings, particularly Gucci (acquired 1999-2004) and Puma, and formally.',
    ],
    [
      'Which British designer\'s autumn/winter 1995-96 collection "Highland Rape," using torn tartan and exposed, distressed-looking models to evoke the historical Highland Clearances, drew accusations of misogyny that the designer publicly rejected?',
      ['Alexander McQueen', 'John Galliano', 'Vivienne Westwood', 'Christopher Bailey'],
      0,
      'McQueen staged the show to reference the brutal 18th-century Highland Clearances and broader English colonial violence against Scotland, his own ancestral background, using torn lace and tartan alongside models styled to look bruised and disheveled, a presentation many critics read at the time.',
    ],
    [
      'Miuccia Prada\'s 1985 black nylon backpack, credited with launching the brand\'s modern identity, used a technical fabric sourced from military and industrial suppliers commonly referred to in the fashion press by what name?',
      ['Pocono nylon', 'Ripstop nylon', 'Ballistic nylon', 'Cordura'],
      0,
      'Prada\'s black nylon, often referred to as Pocono, was a tough, matte industrial fabric more associated with tents, parachutes, and military gear than luxury goods, and Miuccia Prada\'s decision to build a status accessory out of something so deliberately unglamorous was itself the provocation,.',
    ],
    [
      'Phoebe Philo led which fashion house from 2008 to 2017, developing a minimalist, understated "quiet luxury" aesthetic later replaced by Hedi Slimane\'s more logo-forward rebrand?',
      ['Céline', 'Chloé', 'Loewe', 'Jil Sander'],
      0,
      'Philo took over creative direction at Céline in 2008 after an earlier stint at Chloé (2001-2006, where she had already built a cult following for relaxed, bohemian-luxe womenswear), and at Céline she developed clean lines, muted palettes, and functional-but-expensive silhouettes that became.',
    ],
    [
      'What is the fashion-industry term, now standard in fashion criticism, for the mid-2000s trend of luxury houses covering bags and accessories in large, highly visible monogram initials to drive entry-level luxury sales?',
      ['Logomania', 'Ambush marketing', 'Brand saturation', 'Visual merchandising'],
      0,
      'Logomania describes the period, roughly the late 1990s through mid-2000s, when houses like Louis Vuitton, Gucci, and Dior leaned heavily on oversized, instantly recognizable monogram prints (LV, GG, the Dior oblique) across bags, belts, and even entire garments, making brand recognition itself.',
    ],
    [
      'Alexander McQueen\'s spring/summer 1999 show "No. 13" ended with a now-iconic finale in which model Shalom Harlow, standing on a rotating turntable in a white dress, was spray-painted live by what?',
      ['Two industrial robotic arms', 'A team of assistants using airbrush guns', 'A single robotic arm borrowed from a car factory', 'Dancers throwing paint-filled balloons'],
      0,
      'Two Kuka-style industrial robots, more commonly used on car assembly lines, were programmed to spray black and yellow paint onto Harlow\'s rotating white dress as she extended and lowered her arms like a mechanical bird, creating a finale widely regarded as one of the most technically ambitious.',
    ],
    [
      'The CFDA (Council of Fashion Designers of America), formed to professionalize and promote American design as distinct from Paris couture, was founded in what decade?',
      ['The 1960s (1962)', 'The 1950s', 'The 1970s', 'The 1980s'],
      0,
      'The CFDA was founded in 1962 by designer and industry organizer Eleanor Lambert, who had already spent decades promoting American fashion through initiatives like the Press Week events she organized starting in 1943 to give domestic designers press coverage during the war years when Paris.',
    ],
    [
      'Cristóbal Balenciaga\'s 1967 wedding coat, admired as an example of his minimal-seam construction philosophy, was cut from a single piece of fabric folded to eliminate side seams entirely. What is this general pattern-cutting principle called?',
      ['Zero-waste flat-pattern cutting', 'Bias-cut draping', 'Moulage sculpting directly on the body', 'Gusset paneling'],
      0,
      'Balenciaga was famous among couturiers for his engineering-like approach to pattern cutting, often reducing a garment to the fewest possible seams by folding a single length of fabric so it wrapped the body with minimal cutting and piecing, a technique that produced strikingly clean silhouettes.',
    ],
    [
      'Which fashion week became the first to require official health/BMI certification for runway models, banning excessively underweight models in 2006 following the death of model Luisel Ramos?',
      ['Madrid\'s Pasarela Cibeles', 'Milan Fashion Week', 'Paris Fashion Week', 'London Fashion Week'],
      0,
      'Uruguayan model Luisel Ramos collapsed and died of heart failure linked to extreme dieting shortly after a runway show in 2006, and Madrid\'s Pasarela Cibeles fashion week responded that same September by requiring models to pass a body mass index threshold to walk in its shows, becoming the.',
    ],
    [
      'Which designer\'s 1997 launch of the "Rick Owens" label in Los Angeles built a signature aesthetic around draped, distressed leather and jersey often described by critics as "grunge goth," later earning a cult following distinct from the mainstream Paris houses?',
      ['Rick Owens', 'Ann Demeulemeester', 'Helmut Lang', 'Raf Simons'],
      0,
      'Rick Owens founded his eponymous label in Los Angeles in 1994 and showed his first proper runway collection under his own name in the late 1990s, building a following around draped, tonal, heavily distressed leather and jersey pieces that drew equally from punk, glam rock, and classical.',
    ],
  ],
  professor: [
    [
      'The 1973 "Battle of Versailles" fashion show pitted five French couturiers against five American designers in a charity gala. Which American designer\'s fluid jersey designs, modeled by a racially diverse cast choreographed with showstopping energy, is widely credited as decisive in the Americans\' surprise triumph?',
      ['Stephen Burrows', 'Halston', 'Oscar de la Renta', 'Bill Blass'],
      0,
      'The five Americans, Bill Blass, Halston, Anne Klein, Oscar de la Renta, and Stephen Burrows, were considered the underdogs against French couture royalty (Saint Laurent, Dior\'s Marc Bohan, Cardin, Givenchy, and Ungaro), but the American segment\'s energetic staging, set partly to a Josephine.',
    ],
    [
      'At the 1973 Battle of Versailles, one of the five competing French couture houses was represented not by its founder but by another designer, since the founder had already died over a decade earlier. Which house was this?',
      ['Christian Dior', 'Givenchy', 'Cardin', 'Ungaro'],
      0,
      'Christian Dior died suddenly in 1957, only a decade after founding his house, and by 1973 the label was being run creatively by Marc Bohan, who had held the position since 1961 and maintained the house\'s commercial success through the 1960s and 70s with a more restrained aesthetic than Dior\'s.',
    ],
    [
      'Polyester (PET) fiber, commercialized by DuPont under the trade name Dacron starting in 1951, enabled the wrinkle-resistant fabrics central to postwar ready-to-wear. What is PET short for?',
      ['Polyethylene terephthalate', 'Polyamide 6,6', 'Polyacrylonitrile', 'Cellulose triacetate'],
      0,
      'Polyethylene terephthalate is a synthetic polymer originally patented in Britain in the 1940s by chemists at the Calico Printers\' Association, then licensed to DuPont, which brought it to the American market as Dacron in 1951, prized for resisting wrinkles and holding pleats without ironing, a.',
    ],
    [
      'Halston\'s own-name fashion house lost much of its luxury retail cachet after a controversial 1983 licensing deal to design a mass-market line for which department-store chain, a deal now cited as a classic case study in brand dilution?',
      ['J.C. Penney', 'Sears', 'Kmart', 'Montgomery Ward'],
      0,
      'Halston signed a deal to design the "Halston III" collection exclusively for J.C. Penney in 1983, a mass-market chain far removed from the designer\'s Studio 54-era luxury clientele, and the move triggered an immediate backlash: Bergdorf Goodman, which had built its own designer floor around.',
    ],
    [
      'Which French couture pattern-making technique, taught as central to houses like Balenciaga\'s tailoring, involves draping and pinning fabric or a muslin toile directly onto a dress form rather than drafting entirely from flat measurements?',
      ['Moulage', 'Gorging', 'Toile de fond', 'Patronage'],
      0,
      'Moulage, from the French word for molding, involves sculpting fabric directly on a three-dimensional dress form (or occasionally a live model) to capture curves and fit before translating that shape into a final pattern, as opposed to drafting flat patterns purely from a set of body.',
    ],
    [
      'British designer Katharine Hamnett wore one of her own oversized protest T-shirts, reading "58% DON\'T WANT PERSHING," to a 1984 Downing Street reception, while meeting which sitting UK Prime Minister?',
      ['Margaret Thatcher', 'John Major', 'James Callaghan', 'Edward Heath'],
      0,
      'Hamnett\'s slogan referenced a real 1983 opinion poll showing that 58 percent of the British public opposed the deployment of American Pershing II nuclear missiles on UK soil during Cold War tensions, and she deliberately wore the shirt to a Downing Street fashion industry reception in 1984 to.',
    ],
    [
      'In Paris haute couture ateliers, garment-making has traditionally been divided between two workshop specializations by construction method. What are these two categories called?',
      ['Flou and tailleur', 'Petite main and premiere main', 'Cabine and atelier', 'Essayage and livraison'],
      0,
      'Flou refers to soft, draped garments like eveningwear and dresses built with fluid, unstructured techniques, while tailleur refers to structured tailoring, suits and coats requiring padding, canvas, and precise construction closer to menswear techniques, and most historic couture houses,.',
    ],
    [
      'Which organization, founded in 1868 and now operating under the Fédération de la Haute Couture et de la Mode, legally governs which houses may call their collections "haute couture," based on criteria like made-to-order construction and minimum staff and collection size?',
      ['The Chambre Syndicale de la Haute Couture', 'The CFDA', 'The British Fashion Council', 'Camera Nazionale della Moda Italiana'],
      0,
      'The Chambre Syndicale de la Haute Couture was established in Paris in 1868 to regulate the couture trade, and its successor federation still enforces strict criteria, made-to-order garments fitted to individual clients, a minimum number of full-time staff in a Paris atelier, and a set minimum.',
    ],
    [
      'Chinese couturier Guo Pei, later famous for Rihanna\'s 2015 Met Gala yellow cape gown, built early design experience in which sector before founding her own couture house, Rose Studio, in 1997?',
      ['A state-owned garment factory designing costume', 'An apprenticeship at a Parisian couture atelier', 'Ready-to-wear design under Kenzo in Japan', 'Private-label design for an American department store'],
      0,
      'After training at the Beijing Second Light Industry School\'s fashion design program, Guo Pei worked designing for a state-run clothing factory during a period when China\'s fashion industry was still largely organized around centrally planned production rather than an independent designer-led.',
    ],
    [
      'Issey Miyake\'s A-POC ("A Piece of Cloth") line, launched in 1998 with textile engineer Dai Fujiwara, produced entire garments using what production method?',
      ['A knitting machine generating a whole garment from one continuous tube of cloth', 'Laser-cut fabric panels bonded together using ultrasonic welding machines', '3D body-scanning data used to generate custom-fitted paper patterns', 'Injection-molded synthetic fiber sprayed directly onto a full mannequin'],
      0,
      'A-POC used industrial knitting and weaving machines programmed to produce an entire tubular length of fabric that already contained the outlines of finished garments woven or knitted directly into its structure, meaning a customer could simply cut along marked lines with scissors to remove a.',
    ],
    [
      'Miuccia Prada and Patrizio Bertelli launched a diffusion line in 1992-93 aimed at a younger, sportier customer than mainline Prada, naming it after Miuccia\'s own childhood nickname. What was the line called?',
      ['Miu Miu', 'Prada Sport', 'Prada Linea Rossa', 'Prada Uomo'],
      0,
      'Miu Miu, named after the nickname Miuccia Prada\'s family had used for her since childhood, launched as a separate, lower-priced label aimed at a younger customer, letting the company experiment with more overtly playful, sometimes deliberately unglamorous or "ugly" aesthetics that would have.',
    ],
    [
      'Coco Chanel closed her fashion house during World War II amid controversy over her wartime conduct, then relaunched it in which year with a comeback collection that French critics panned but that American buyers and press embraced?',
      ['1954', '1947', '1957', '1961'],
      0,
      'Chanel reopened her house in 1954 at age seventy, after having shuttered it in 1939 and spent the war years living at the Hôtel Ritz in Paris, a period later scrutinized over her relationship with a German intelligence officer, a controversy that has continued to shadow assessments of her legacy.',
    ],
    [
      'Hussein Chalayan\'s autumn/winter 2000 show "Afterwords," which ended with models transforming furniture, including a wooden coffee table collapsing into a wearable skirt, into clothing and luggage, was widely read as an allegory for what real-world experience, drawing on the designer\'s own background?',
      ['Refugees fleeing ethnic conflict, drawing on Chalayan\'s own Cypriot background', 'The Y2K technology panic gripping global media coverage that year', 'The fall of the Berlin Wall roughly a decade earlier', 'Rising sea levels and mass climate-driven displacement'],
      0,
      'Chalayan, born in Cyprus to Turkish Cypriot parents and raised partly amid the island\'s ethnic conflict and displacement following the 1974 division of Cyprus, staged "Afterwords" as a family sheltering indoors as violence approaches outside, ultimately fleeing by turning their own furniture,.',
    ],
    [
      'Yves Saint Laurent founded his own eponymous couture house in 1961 with business and romantic partner Pierre Bergé, after being controversially dismissed from which position the previous year?',
      ['Head designer of Christian Dior', 'Creative director of Balenciaga', 'Head designer of Givenchy', 'Design director of Chanel'],
      0,
      'Saint Laurent had succeeded Christian Dior himself as head designer of the House of Dior in 1957 at only twenty-one years old, following Dior\'s sudden death, and ran the house successfully for several years before being conscripted into the French army during the Algerian War in 1960, an.',
    ],
    [
      'Designer Rudi Gernreich\'s controversial 1964 "monokini" (topless swimsuit) was first modeled in widely published photographs by which figure, his longtime muse and collaborator?',
      ['Peggy Moffitt', 'Twiggy', 'Veruschka', 'Jean Shrimpton'],
      0,
      'Peggy Moffitt, an actress and model who worked almost exclusively with Gernreich and photographer William Claxton for most of her career, modeled the monokini in the photographs that launched it into international news coverage, generating enormous controversy and even church condemnations.',
    ],

  ],
};

export const FASHION_HISTORIC: CategoryContent = {
  bscba: [
    [
      'Which medieval garment, featuring a fitted torso closed with buttons rather than draped and belted, marked the true beginning of Western tailoring?',
      ['The cotehardie', 'The houppelande', 'The kirtle', 'The surcote'],
      0,
      'The cotehardie\'s close fit required tailors to develop shaped pattern pieces, a technical leap that distinguished tailoring from simple draped sewing.',
    ],
    [
      'What practical purpose did pattens serve in medieval and early modern streets?',
      ['Raised shoes above mud and filth', 'Marked social status and rank', 'Provided warmth in winter', 'Prevented theft of shoes'],
      0,
      'Pattens were wooden overshoes strapped over regular shoes to keep them elevated above mud in unpaved streets, used across social classes.',
    ],
    [
      'Which English sumptuary law of 1363 attempted to regulate dress by restricting what people of different ranks could wear?',
      ['Laws based on income and social rank', 'Laws based on gender', 'Laws based on marital status', 'Laws based on religious affiliation'],
      0,
      'Edward III\'s statute prescribed which grades of cloth, fur, and trim each social band could legally wear, linking clothing to social order.',
    ],
    [
      'Which 14th and 15th century robe is most distinctive for its enormous fullness, high collar, and often dagged or slashed sleeves?',
      ['The houppelande', 'The cotehardie', 'The kirtle', 'The gown'],
      0,
      'The houppelande\'s voluminous, high-necked design displayed wealth through fabric consumption and featured elaborate decorative sleeve edges.',
    ],
    [
      'What made fustian fabric unique in medieval European textile production?',
      ['A blend of linen warp and cotton weft', 'Pure silk taffeta', 'Knitted wool felt', 'Undyed cotton'],
      0,
      'Fustian combined European linen with imported cotton, creating a durable, moderately priced cloth suited for both clothing and furnishings.',
    ],
    [
      'What was the primary function of the linen coif worn in medieval dress?',
      ['To cover and contain the hair', 'To indicate marital status', 'To protect in combat', 'To signal occupation'],
      0,
      'The coif was a simple linen cap tied under the chin, worn across social classes as a practical hair-covering base layer beneath other headwear.',
    ],
    [
      'Which distinctive feature of the 12th-century bliaut is most visible in period sculpture and manuscript illustrations?',
      ['Its tightly fitted, pleated bodice', 'Its enormous trailing train', 'Its low neckline', 'Its rigid front panel'],
      0,
      'The bliaut\'s characteristic wrinkled bodice, achieved through tight side-lacing, marked a significant shift toward body-conscious women\'s dress.',
    ],
    [
      'How was the fur called vair constructed in medieval heraldic use?',
      ['Alternating pieces of blue-grey and white squirrel fur', 'Solid white ermine', 'Spotted lynx fur', 'Dyed red sable'],
      0,
      'Vair\'s distinctive checkerboard pattern of alternating squirrel fur colors made it a recognizable status marker and heraldic symbol.',
    ],
    [
      'What specific construction purpose did the laces called "points" serve in 15th-century men\'s dress?',
      ['They attached separate hose legs to the doublet', 'They decorated a belt', 'They fastened sleeves', 'They held a codpiece'],
      0,
      'Points were tipped laces that threaded through eyelets, connecting separate hose legs to the doublet to prevent them from sliding down.',
    ],
    [
      'How did the Spanish farthingale differ from the later French wheel farthingale in silhouette?',
      ['Spanish was cone-shaped, French was flat-topped', 'Spanish was wool, French was silk', 'Spanish required boning, French did not', 'Spanish was formal, French was casual'],
      0,
      'The Spanish version used graduated hoops for a smooth conical shape, while the French wheel pushed the skirt outward in a flat-topped drum shape.',
    ],
    [
      'What innovation allowed elaborate ruffs to hold their crisp folds in the late 16th century?',
      ['Starch, applied and set with heated poking sticks', 'Wire cage supports', 'Chemical stiffeners', 'Heat-pressing machines'],
      0,
      'Starch, introduced from the Low Countries, was applied to linen ruffs and shaped with heated tools to set the regular figure-eight folds.',
    ],
    [
      'What practical problem did the codpiece originally solve in 15th-century men\'s dress?',
      ['The gap left by short doublets and separate hose', 'The need to conceal armor', 'Cold weather protection for sensitive areas', 'Fashion decoration only'],
      0,
      'As doublets shortened and hose remained as separate legs, a fabric panel became necessary to cover the front crotch gap for modesty.',
    ],
    [
      'Why were Venetian chopine platform shoes particularly difficult to walk in at their most extreme heights?',
      ['Their extreme height made balance difficult', 'Their rigid construction limited movement', 'The weight of the platforms', 'They limited downward vision'],
      0,
      'Some chopines exceeded a foot in height, requiring wearers to be physically supported by servants or companions to maintain balance while walking.',
    ],
    [
      'What was the function of the stomacher in women\'s 16th-century dress?',
      ['It filled and shaped the V-shaped front opening of a bodice', 'It supported the skirt at the waist', 'It created hip padding', 'It reinforced the shoulders'],
      0,
      'The stiffened, often heavily decorated triangular stomacher filled the gap of open-fronted bodices and became a prominent focal point of the torso.',
    ],
    [
      'How did 18th-century panniers differ from earlier farthingale structures?',
      ['They extended width dramatically at the sides rather than all around', 'They were smaller and less visible', 'They used different materials', 'They were only worn by servants'],
      0,
      'Panniers used hip-level hoops that pushed the skirt outward at the sides while keeping it flat front to back, creating a distinctive drum-like silhouette.',
    ],
  ],
  msc: [
    [
      'Historians point to the mid-14th century as a hinge point in Western European clothing because a new fitted garment for men required a fundamentally different cutting method than earlier robes. Which garment exemplifies this shift toward true tailoring?',
      ['The cotehardie, a torso-hugging garment closed with a long row of buttons or laced at the side', 'The houppelande, a voluminous high-collared robe with trailing dagged sleeves, cut from wide uncut rectangles gathered into a belt', 'The chainse, a lightweight linen undertunic worn beneath a bliaut and laced loosely at the sides for ease of movement', 'The surcote ouvert, a sleeveless overgown with wide, fur-edged arm openings that exposed the fitted cotehardie or kirtle worn beneath'],
      0,
      'The cotehardie, which spread across Western Europe from roughly the 1330s onward, was cut in multiple shaped panels rather than draped from rectangles, and it was held to the body with buttons or side-lacing instead of a belt cinching loose fabric.',
    ],
    [
      'England\'s 1363 sumptuary statute under Edward III regulated dress primarily along which axis, distinguishing it from later Tudor laws that named specific banned fabrics outright?',
      ['Annual income and social rank, prescribing which grades of cloth and fur each class could wear', 'Religious affiliation, restricting particular garment colors and trims to clergy and members of religious orders alone', 'Regional origin, banning the import or wear of any cloth not woven within English county boundaries', 'Marital status, reserving certain veils and headdresses for widows and prohibiting them to unmarried women'],
      0,
      'The 1363 statute worked by sorting the population into income and rank bands, from ploughmen and servants up through esquires, knights, and merchants, and then specifying which grades of cloth, fur, and trim each band could legally wear.',
    ],
    [
      'The houppelande, fashionable across Europe from the late 14th into the 15th century, is most distinctively identified by which combination of features?',
      ['A high standing collar, voluminous full-length body, and long sleeves often cut with dagged or scalloped edges', 'A fitted bodice laced up the back with a separate detachable train pinned at the shoulder for formal court occasions', 'A short, waist-length jacket worn over hose with a codpiece at the front closure, typically paired with a low square neckline', 'A hoop-supported skirt worn beneath a stiffened, boned bodice that flattened the torso into a rigid conical shape'],
      0,
      'The houppelande was essentially a floor-length, high-necked robe cut with enormous fullness through the body and sleeves, often gathered into a belt so the excess fabric fell in heavy folds, and its sleeve and hem edges were frequently cut into dags, points, or leaf shapes that required skilled.',
    ],
    [
      'Fustian, a fabric common in medieval and early modern European clothing and bedding, is technically defined by which characteristic?',
      ['A woven blend combining a linen warp with a cotton weft', 'A pure silk taffeta woven with a moiré finish', 'A knitted wool fabric fulled to produce a dense, felt-like surface', 'A fabric woven entirely from raw, undyed cotton fiber'],
      0,
      'Fustian\'s defining feature was its mixed-fiber construction: European weavers, lacking a domestic cotton crop, used linen thread for the strong warp and imported raw cotton for the softer weft, producing a durable, moderately priced cloth.',
    ],
    [
      'Pattens, worn across medieval and early modern Europe, served what practical function in relation to the shoes worn beneath them?',
      ['They were wooden or thick-soled overshoes strapped on to raise the wearer\'s actual shoes above mud and street filth', 'They were the earliest form of raised heel built directly into the leather sole of a single shoe, replacing the need for a separate overshoe', 'They were decorative buckled overshoes worn only indoors as a mark of aristocratic status and removed before any outdoor errand', 'They were felted wool socks worn as the sole layer of footwear in place of leather shoes, common among rural laborers'],
      0,
      'Streets in medieval and early modern towns were unpaved or poorly paved and frequently thick with mud, animal waste, and standing water, so pattens were strapped on over a person\'s regular leather shoes to lift the good shoe\'s sole clear of the mess, and they were removed at a doorway before.',
    ],
    [
      'The medieval linen coif, worn by both men and women from roughly the 12th through 15th centuries, primarily served which purpose?',
      ['A close-fitting cap tied under the chin that covered the hair as a base layer beneath other headwear', 'A stiffened wire-framed hood worn exclusively by unmarried noblewomen at court as a marker of eligibility for marriage', 'A mail-lined skullcap worn only by knights beneath a great helm to cushion the head during combat', 'A wide-brimmed straw hat worn by agricultural laborers to block sun exposure during the harvest season'],
      0,
      'The coif was a simple linen cap that tied beneath the chin and covered the hair completely, and it was worn across social classes as a practical layer, often underneath a hat, hood, or veil, both to keep hair clean and controlled and, for men, sometimes as a base layer under a helm\'s padding.',
    ],
    [
      'The 12th-century bliaut, worn by aristocratic women, is most notable among costume historians for which distinctive construction detail?',
      ['A tightly fitted, wrinkled or pleated bodice achieved through lacing at the sides, paired with a full, flaring skirt', 'A stiff, boned front panel that flattened the torso beneath a low square neckline, worn over a separate laced kirtle', 'Wide horizontal bands of contrasting fur sewn around the hem and sleeve openings to signal the wearer\'s rank at court', 'A detachable train fastened with metal clasps at the back of the waist, allowing it to be removed for horseback riding'],
      0,
      'The bliaut\'s most argued-over feature is the wrinkled, closely gathered appearance of its bodice in period sculpture and manuscript images, which scholars now generally believe was achieved by lacing the garment tightly at the sides over an undergarment, creating characteristic horizontal.',
    ],
    [
      'In medieval heraldic and sumptuary use, the fur pattern called vair was distinguished from other prestige furs chiefly by which characteristic?',
      ['It was assembled from squirrel pelts sewn in alternating bell-shaped pieces of blue-grey back fur and white belly fur', 'It was a solid white fur reserved exclusively for royalty and taken only from winter ermine coats hunted in northern forests', 'It came from sable and was always dyed a deep crimson before being sewn into garments for high-ranking clergy', 'It was a spotted fur pattern created by leaving the natural markings of lynx pelts uncut and displaying them as a luxury trim'],
      0,
      'Vair came from the Baltic squirrel, whose back fur was blue-grey and belly fur white, and furriers cut and pieced these together in a repeating bell or cup pattern so the two colors alternated in a distinctive checkerboard-like arrangement, a design so recognizable it became a standard heraldic.',
    ],
    [
      'In 15th and 16th century men\'s dress, the small ties known as points served what specific construction function?',
      ['Laces that attached the separate legs of hose to the doublet, holding them up at the waist', 'Decorative metal tips sewn purely for ornament at the end of a nobleman\'s belt, signaling wealth through goldsmith work', 'Reinforced buttonholes used exclusively on ecclesiastical vestments to withstand repeated laundering over decades', 'Short leather straps that secured a sword scabbard to a waist belt, common among mounted men-at-arms'],
      0,
      'Before hose became a single fitted garment, men\'s hose were still often separate legs, and points, which were laces tipped with small metal aiglets, were threaded through matching eyelets on the doublet\'s lower edge and the hose top to tie the two garments together and keep the hose from.',
    ],
    [
      'The farthingale, which shaped women\'s skirts in the 16th century, existed in two major regional forms that produced noticeably different silhouettes. What distinguished the Spanish farthingale from the later French (wheel) farthingale?',
      ['The Spanish version used graduated hoops for a smooth cone shape, while the French wheel version used a hip-level roll that projected the skirt outward', 'The Spanish version was worn only by unmarried women at court, while the French version was reserved for married noblewomen attending formal state functions', 'The Spanish version was built from whalebone strips laced in horizontal channels, while the French version used only stiffened linen with no boning at all', 'The Spanish version supported the skirt from the shoulders via suspended straps, while the French version supported it entirely from the waist using a boned underbodice'],
      0,
      'The Spanish farthingale, verdugado, used a series of graduated hoops, often cane or reed, sewn into a petticoat so the skirt widened steadily from waist to hem in a smooth cone or bell shape.',
    ],
    [
      'The elaborate ruffs of the late 16th century required which specific technical innovation to be mass-producible and hold their crisp shape?',
      ['The introduction of starch, stiffened and shaped with heated poking sticks to set the figure-eight folds', 'The development of interior wire cages sewn permanently into the linen to hold each fold rigid without any need for laundering', 'The use of vulcanized rubber strips sewn between fabric layers to add spring and structure to the folded linen', 'A chemical bleaching process that stiffened linen fibers permanently without any added starch or subsequent pressing'],
      0,
      'Ruffs before the mid-16th century were modest and simply gathered, but the arrival of starch, reportedly introduced to England from the Low Countries in the 1560s, let launderers stiffen the linen and then use small heated metal or wooden poking sticks to press the fabric into the deep, regular.',
    ],
    [
      'The codpiece, prominent in men\'s fashion from roughly the 1450s through the late 16th century, originated primarily as a practical response to which change in garment construction?',
      ['The shortening of the doublet and the separation of hose into two legs, which left a gap at the front crotch that needed covering', 'A new religious requirement following the Council of Trent that men\'s garments fully conceal the body\'s silhouette in public settings', 'The introduction of plate armor cuisses, which required a matching civilian fashion accessory worn beneath the doublet', 'A shift to wearing hose without any accompanying undergarment, necessitating a modesty panel sewn directly to the hose'],
      0,
      'As doublets grew shorter through the 15th century and hose legs were still separately constructed rather than joined into one garment, an open gap remained at the front, and the codpiece began as a simple flap or triangular panel of fabric laced in place to cover that gap and preserve modesty.',
    ],
    [
      'Venetian chopines, extremely high platform shoes fashionable among wealthy women in 16th-century Italy, are most notable to costume historians for which practical consequence of their height?',
      ['Wearers frequently required servants or companions to physically support them while walking to avoid falling', 'They were designed to be removable in two pieces so the wearer could walk normally indoors without assistance', 'They incorporated a hidden spring mechanism in the sole to assist with balance while standing for long periods', 'They were worn exclusively while seated, functioning as a footrest rather than actual footwear during formal dinners'],
      0,
      'Some Venetian chopines reached extraordinary heights, with surviving examples measuring over a foot tall, and at that scale walking unassisted became genuinely difficult, so period accounts and images show women being steadied by servants or by a companion\'s arm, turning the shoe into a.',
    ],
    [
      'The stomacher, a stiffened triangular panel worn at the front of women\'s bodices from the 16th through 18th centuries, primarily served which function?',
      ['It filled and shaped the V-shaped gap at the front of an open-fronted bodice, often heavily boned or richly decorated as a focal point', 'It functioned as a detachable pocket sewn to the interior of the bodice for carrying small personal items such as coins or letters', 'It was a padded roll tied at the natural waist to exaggerate the hips beneath a skirt, common in earlier Tudor fashion', 'It reinforced the shoulder seams of a bodice to prevent tearing under the weight of an attached train during formal court appearances'],
      0,
      'Many fashionable bodices of this period were cut open at the front in a V or U shape rather than closed edge to edge, and the stomacher was a separate, often heavily boned and decorated triangular piece pinned or stitched in place to fill that gap, giving the torso a smooth, conical, rigid line.',
    ],
    [
      'Panniers, the side-hoop structures worn under women\'s skirts through much of the 18th century, produced a silhouette distinguished from earlier farthingales chiefly by which feature?',
      ['They extended the skirt\'s width dramatically at the sides and hips while remaining relatively flat from front to back', 'They raised the skirt\'s hemline several inches off the ground on a rigid internal frame to keep the hem clear of mud', 'They were worn only over the shoulders as suspended straps rather than tied at the waist, common among servant classes', 'They eliminated hip width entirely in favor of a fully cylindrical silhouette popular in the later Regency period'],
      0,
      'Where earlier farthingales tended to produce a roughly circular or conical skirt shape when viewed from above, 18th-century panniers used separate hoop structures at each hip, sometimes hinged so they could be raised to pass through a doorway, which pushed the skirt dramatically wide at the.',
    ],
  ],
  phd: [
    [
      'Opus anglicanum, the English ecclesiastical embroidery so prized across medieval Europe that papal inventories specifically requested it by name, achieved its dense gold surface through which specific stitching technique?',
      ['Underside couching, where the gold thread is laid on the surface and pulled slightly through to the back at each stitch, keeping the metal thread itself unpierced', 'Surface satin stitch worked directly with gold thread pulled fully through the linen ground on every pass', 'A knotted pile technique similar to carpet-making, with gold thread ends clipped level after knotting', 'Chain stitch worked in gold thread reinforced afterward with a wax-based fixative to prevent fraying'],
      0,
      'Underside couching let embroiderers lay expensive gold or silver-wrapped thread flat across the surface while a linen thread from beneath tugged tiny loops of it through to the back at regular intervals, so the precious metal thread was never itself pierced or pulled through the ground fabric,.',
    ],
    [
      'The coronation mantle of Roger II of Sicily (1133-34), now in Vienna, is a key artifact for historians of cross-cultural fashion influence because it combines Latin Christian ceremonial use with which textile tradition?',
      ['Islamic tiraz workshop production, complete with an Arabic inscription embroidered along its hem crediting the royal Palermo workshop', 'Byzantine imperial purple dye production using murex-derived Tyrian purple exclusively reserved for the Constantinople court', 'Chinese silk brocade imported directly along the Silk Road and cut down to size by local Sicilian tailors', 'Frankish Carolingian embroidery tradition transplanted to Sicily by Norman court chaplains'],
      0,
      'Roger II\'s red silk coronation mantle, embroidered with a striking gold lion attacking a camel, carries an Arabic inscription along its border naming the royal Palermo workshop and the year of manufacture, a direct product of the tiraz tradition of inscribed royal textile workshops that the.',
    ],
    [
      'Medieval English wardrobe accounts frequently distinguish \'cendal\' from other silks used for linings and banners. What did cendal specifically denote among historians reconstructing medieval textile terminology?',
      ['A lightweight, plain-woven silk taffeta-like fabric, cheaper than heavier silks and commonly used for linings, banners, and lower-cost garments', 'A heavyweight figured silk brocade woven with metallic thread, reserved for episcopal vestments', 'A napped wool broadcloth finished to imitate the sheen of silk at a fraction of the cost', 'A cotton-linen blend fabric imported from Egypt and mislabeled as silk in period accounts'],
      0,
      'Cendal was a thin, plain-weave silk, essentially a taffeta-weight fabric without elaborate figuring, which made it far cheaper than heavy figured silks like samite or baudekin while still carrying silk\'s desirable sheen, so it turned up constantly in wardrobe accounts lining garments, hoods,.',
    ],
    [
      'The quilted defensive garment known variously as the gambeson, aketon, or pourpoint achieved its protective stiffness primarily through which construction method?',
      ['Multiple layers of linen or wool padding stitched down in closely spaced parallel or diamond lines running through all layers', 'A single thick layer of boiled and hardened leather (cuir bouilli) sewn between two thin silk shells', 'Overlapping small metal plates riveted directly to a canvas foundation beneath a fabric outer layer', 'Horsehair stuffing packed loosely into pockets sewn at intervals across an unquilted outer shell'],
      0,
      'The defining feature of quilted garments like the gambeson or pourpoint was the dense, regularly spaced stitching, often in parallel lines, diamonds, or channels, run through multiple layers of linen, wool, or raw cotton wadding, which compressed and locked the padding in place so it couldn\'t.',
    ],
    [
      'Before the 16th-century arrival of cochineal from the Americas, the most prized brilliant red dye available to European textile producers came from which source?',
      ['Kermes, a scale insect harvested from Mediterranean oak trees, dried, and crushed to release its red dye compound', 'Brazilwood, an imported tropical hardwood whose shavings were boiled to extract a red dye', 'Madder root, cultivated widely across Europe and processed to yield its characteristic dye compound alone', 'Murex sea snails, crushed in bulk to produce the same Tyrian purple used by Roman emperors'],
      0,
      'Kermes came from a small scale insect, Kermes vermilio, that lives on Mediterranean oak species; the dried, crushed insect bodies yielded a strong, relatively fade-resistant crimson dye that was significantly more expensive than plant-based reds like madder because harvesting the tiny insects.',
    ],
    [
      'Woad, the primary European source of blue dye before large-scale imported indigo became common, produces its coloring compound from a plant that is chemically related to indigo in what specific way?',
      ['Both plants yield the same dye molecule, indigotin, but woad contains it in a much lower concentration than tropical indigo plants', 'Woad and indigo produce chemically distinct blue compounds that happen to look similar once fixed onto wool or linen fibers', 'Woad\'s blue compound only develops after mixing with a separate red dye derived from madder root', 'Indigo is a synthetic dye invented to imitate the natural blue produced by fermenting woad leaves'],
      0,
      'Woad (Isatis tinctoria) and tropical indigo (Indigofera species) both produce their blue color from the same underlying molecule, indigotin, generated through a fermentation process that converts a colorless precursor in the leaves into the insoluble blue dye, but woad leaves contain a far.',
    ],
    [
      'In late medieval England, aristocratic \'livery\' referred to which specific practice tied to clothing and social display?',
      ['The periodic distribution of cloth or ready-made garments, often in a lord\'s identifying colors, to retainers and household staff as part of their service', 'A tax levied on wool exports specifically earmarked to fund royal household clothing purchases', 'A guild-issued certificate permitting a tailor to work independently without further apprenticeship', 'A form of ecclesiastical dress reserved for cathedral choir members during major feast days'],
      0,
      'Livery in this sense meant the practice of a lord supplying his retainers, servants, and sometimes allied gentry with cloth or finished garments, typically in his own heraldic colors or badge, both as a practical form of payment in kind and as a visible display of the lord\'s following and.',
    ],
    [
      'The mantua, which emerged in England in the 1670s-80s as an alternative to the rigid boned bodice and separate skirt, is notable to dress historians chiefly for which structural departure?',
      ['It was cut and draped from a single loosely fitted length of fabric pleated into place at the waist rather than built from a separately boned, fitted bodice', 'It replaced woven wool entirely with knitted silk jersey, the first major fashionable use of knitted fabric for outerwear', 'It eliminated the underlying shift or chemise, being worn as the sole layer directly against the skin', 'It introduced the first fully symmetrical box-pleated back seen in European court dress'],
      0,
      'The mantua broke from the rigid, separately boned bodice-and-skirt construction that had dominated women\'s formal dress by instead draping and pleating a single length of fabric loosely around the body and gathering it at the waist, a far less structurally engineered garment that could be put.',
    ],
    [
      'The two dominant gown silhouettes of mid-to-late 18th century Europe, the robe a la francaise and the robe a l\'anglaise, are distinguished chiefly by which construction difference at the back?',
      ['The francaise has loose box pleats falling free from the shoulders to the floor, while the anglaise has fabric fitted closely to the back through the bodice via seaming', 'The francaise uses a bustle pad at the back waist while the anglaise instead relies on a full underskirt of layered petticoats', 'The francaise fastens with hooks down the center back while the anglaise fastens entirely at the front', 'The francaise is always constructed from silk while the anglaise is a specifically wool or linen daytime garment'],
      0,
      'The robe a la francaise kept the loose double box pleats, often called \'Watteau pleats\' after the painter who frequently depicted them, falling uninterrupted from the shoulders to the ground at the back, creating a train-like drape even when the front bodice was fitted and boned, while the.',
    ],
    [
      'Tablet weaving (also called card weaving), used across medieval Europe to produce narrow decorative trim, achieved its patterned bands through which mechanical process?',
      ['Small perforated cards threaded with warp yarns were rotated in sequence, twisting the threads to create patterned bands as weft passed through', 'A narrow horizontal loom with heddles raised by foot pedals wove the pattern automatically without manual thread manipulation', 'Individual pattern threads were embroidered onto a pre-woven plain band after the base weaving was complete', 'Warp threads were pre-dyed in a repeating sequence so the pattern emerged automatically from a plain weave structure'],
      0,
      'Tablet weaving used small, typically square cards with a hole punched near each corner, through which warp threads were threaded; turning the whole stack of cards forward or backward between weft passes twisted the warp threads around one another in controlled ways, and by threading different.',
    ],
    [
      'Fulling, an essential finishing process for European wool cloth throughout the medieval and early modern periods, transformed loosely woven wool into a denser fabric through which mechanism?',
      ['Repeated pounding or trampling of wet, soaped cloth caused the fibers to felt and interlock, shrinking and thickening the weave', 'Cloth was stretched on tenter frames and left to dry under tension, which permanently tightened the weave structure', 'Wool fibers were chemically treated with lime to dissolve surface scales and bond adjacent threads together', 'The cloth was repeatedly boiled in dye baths, and the heat alone caused the wool fibers to shrink and mat'],
      0,
      'Fulling worked by repeatedly pounding, trampling, or (later) mechanically hammering wet wool cloth that had been treated with soap or fuller\'s earth, and the combination of moisture, friction, and mechanical agitation caused the microscopic scales on individual wool fibers to catch on one.',
    ],
    [
      'The Champagne fairs of 12th and 13th century France played what specific role in the medieval European textile trade?',
      ['They served as a recurring, regulated marketplace where Flemish woolen cloth was traded for Italian-imported silks, dyes, and Mediterranean goods', 'They were the sole licensed production sites for royal French court garments under a crown monopoly', 'They functioned as an annual guild examination where journeyman weavers earned master status', 'They were church-organized textile donation events redistributing used clothing to the poor across France'],
      0,
      'The Champagne fairs, a cycle of regularly scheduled trading fairs held across several towns in that French region, sat at a geographically convenient crossroads between the great Flemish cloth-producing towns to the north and Italian merchants bringing silks, spices, dyestuffs, and other goods.',
    ],
    [
      'Alum\'s essential role in pre-modern European textile dyeing was as which specific type of agent?',
      ['A mordant, a chemical that bonds to both the fiber and the dye molecule, fixing color that would otherwise wash or rub out', 'A bleaching agent, used to strip natural fiber color before any dye was applied', 'A dye itself, producing a pale yellow color when used alone on wool or linen', 'A fiber-softening treatment applied after dyeing to improve the finished cloth\'s hand'],
      0,
      'Alum, a metal salt, worked as a mordant: soaking fiber or cloth in an alum solution before dyeing let aluminum ions bind onto the fiber, creating chemical anchor points that many natural dye molecules, which otherwise have poor direct affinity for wool, linen, or cotton, could then latch onto.',
    ],
    [
      'In technical textile terminology, what structurally distinguishes a damask weave from a brocade?',
      ['Damask creates its pattern using only the weave structure itself, while brocade introduces extra, often supplementary weft threads to build up a raised pattern', 'Damask is woven exclusively from silk while brocade can only be woven from wool or linen', 'Damask patterns are always monochrome while brocade patterns must use at least three colors', 'Damask is a knitted structure while brocade is strictly a woven one'],
      0,
      'Damask achieves its pattern purely through the weave structure itself, typically alternating satin-faced and sateen or plain-faced areas woven from a single set of warp and weft threads so the pattern appears through contrasting light reflection rather than added material, giving damask its.',
    ],
    [
      'Florence\'s Arte della Lana, one of medieval Europe\'s most powerful trade guilds, controlled which specific stage of the city\'s dominant textile industry?',
      ['The entire wool cloth production and finishing process, from importing raw wool through weaving, fulling, dyeing, and finishing for export', 'Exclusively the retail sale of finished garments within the city\'s markets, leaving production entirely unregulated', 'Only the dyeing stage, leaving weaving and finishing to separate, unaffiliated guilds', 'The import and resale of finished luxury silk textiles from Byzantine and Islamic sources'],
      0,
      'The Arte della Lana regulated and profited from the entire chain of wool cloth production in Florence, from securing and importing high-quality raw wool, often English or Spanish, through the many stages of spinning, weaving, fulling, and dyeing, down to finishing and preparing the cloth for.',
    ],
  ],
  professor: [
    [
      'The Bocksten Man, a mid-14th-century bog-preserved body discovered in Sweden in 1936 complete with clothing, is a key source for reconstructing ordinary (non-elite) male dress of the period because his preserved garments include which specific ensemble?',
      ['A hooded cloak, a long-sleeved tunic, and hose, along with a distinctive pointed hood, all in coarse wool rather than fine textiles', 'A complete suit of quilted armor worn beneath a mail shirt, indicating he was a low-ranking soldier', 'Fine silk hose and a velvet doublet, suggesting he was a wealthy merchant despite the bog context', 'Liturgical vestments, leading early researchers to identify him as a traveling cleric'],
      0,
      'The Bocksten Man\'s bog-preserved outfit, coarse wool rather than costly fabric, includes a tunic, hose, a cloak, and notably a long-tailed pointed hood, giving textile historians one of the few essentially complete, securely dated examples of ordinary mid-14th-century male civilian dress.',
    ],
    [
      'The attribution of the extant 14th-century quilted garment known as the Pourpoint of Charles de Blois (now in the Musee des Tissus, Lyon) to Charles de Blois himself rests primarily on which type of evidence, since no contemporary inventory explicitly names it as his?',
      ['A repeating heraldic motif woven into its silk fabric matching devices associated with Charles de Blois, combined with stylistic dating of the garment\'s cut', 'A signed maker\'s mark stitched into the garment\'s lining identifying the tailor by name and location', 'Documentary evidence from his funeral inventory explicitly listing the garment by this exact description', 'DNA testing of organic residue trapped within the quilting layers matching descendants of the Blois family'],
      0,
      'The pourpoint\'s attribution rests on the distinctive woven pattern in its silk satin outer fabric, a repeating design read by historians as connected to heraldic devices associated with Charles de Blois, a claimant to the Duchy of Brittany who died in 1364, combined with the garment\'s cut and.',
    ],
    [
      'The Norse Greenland garments recovered from the Herjolfsnes churchyard, dated roughly to the 14th and early 15th centuries, are notable to textile historians chiefly for demonstrating which garment-cutting technique?',
      ['The use of triangular gores inserted into side and center seams to add flare to the skirt of a garment cut from otherwise narrow, rectangular loom-width panels', 'An early form of bias-cut construction that let the fabric stretch diagonally across the body', 'The first known use of a set-in sleeve cut as a separate curved pattern piece', 'A continuous single-panel wraparound construction requiring no seams at all below the waist'],
      0,
      'The Herjolfsnes garments, remarkably preserved by Greenland\'s cold, and now held mainly in Denmark\'s National Museum, show clothing cut from the narrow widths that a simple upright loom of the period could produce, with triangular gores inserted into the seams to add flare and width to the.',
    ],
    [
      'The burial gown of Eleonora di Toledo, Grand Duchess of Tuscany, recovered from the Medici tombs and extensively studied since the 1980s, was constructed from which specific luxury textile?',
      ['A cut silk velvet with a pile-on-pile (voided) pattern structure, woven with areas of contrasting pile height to create its design', 'A plain wool broadcloth dyed with imported cochineal to achieve its deep red color', 'A cotton-linen blend fustian embroidered afterward with silk floss thread', 'A knitted silk jersey fabric, an unusually early example of fashionable knitwear'],
      0,
      'Eleonora di Toledo\'s burial gown was woven as a cut silk velvet using a pile-on-pile, or voided velvet, technique, where the loom\'s ability to raise pile in some areas while leaving others flat, or at a different pile height, created a self-patterned fabric with contrasting textures and light.',
    ],
    [
      'The blood-stained garments of the Sture family, killed in 1567 on the orders of King Erik XIV of Sweden and preserved in Uppsala Cathedral, have been used by historians and forensic researchers chiefly to study which combination of evidence?',
      ['The construction and cut of authentic mid-16th-century Swedish elite male dress alongside physical evidence of the specific weapon wounds that killed the wearers', 'The earliest known European use of machine-woven ribbon trim, predating industrial ribbon looms by two centuries', 'A previously unknown regional dye recipe reconstructed entirely from pigment residue in the bloodstains', 'The first documented use of interchangeable, mass-produced button sizes across multiple garments'],
      0,
      'The Sture garments survive because they were deliberately preserved as relics of a shocking political murder, giving historians an unusually well-documented, precisely dated set of real mid-16th-century Swedish elite menswear alongside direct physical evidence, cut and stab damage, of the.',
    ],
    [
      'The 13th-century tomb of the Infante Fernando de la Cerda in Spain preserved a set of items that are frequently cited in textile scholarship as some of the earliest surviving evidence in Europe for which specific technique?',
      ['True two-needle knitting, seen in silk cushion covers worked in a purl-and-knit pattern rather than the single-needle nalbinding technique used earlier', 'Machine-assisted warp knitting, centuries before any mechanical knitting frame is otherwise documented', 'Crochet worked with a hooked needle, predating other European crochet evidence by several centuries', 'Tapestry weaving using a horizontal treadle loom rather than a vertical warp-weighted one'],
      0,
      'The silk cushions found in the tomb of the Infante Fernando de la Cerda, who died in 1275, show a knit structure worked with two needles producing genuine knit and purl stitches, distinguishing them clearly from the older single-needle nalbinding (needle-binding) technique that had been used in.',
    ],
    [
      'The medieval English royal \'Great Wardrobe\' is significant to dress historians primarily as which type of source?',
      ['An administrative office whose surviving account rolls record detailed royal cloth and garment purchases, prices, and quantities, offering rare quantifiable evidence for court dress', 'A surviving physical building whose preserved architecture reveals how garments were stored and displayed at court', 'A single illuminated manuscript describing court dress etiquette in narrative rather than accounting form', 'A private collection of extant royal garments preserved intact since the medieval period'],
      0,
      'The Great Wardrobe was the English crown\'s administrative department responsible for purchasing and managing cloth, furs, and finished garments for the royal household, and its surviving account rolls, recording exactly what was bought, from whom, in what quantity, and at what price, give.',
    ],
    [
      'The medieval and early Renaissance practice of wearing \'mi-parti\' or parti-colored garments, split down the center into two contrasting colors or fabrics, was most consistently associated with which social function?',
      ['Displaying a lord\'s heraldic livery colors, servant status, or affiliation, making the wearer instantly identifiable by color at a distance', 'Signaling clerical rank within the church hierarchy, with specific color splits reserved for each ordained office', 'Marking a period of formal mourning, with one side representing grief and the other representing hope of resurrection', 'Indicating guild membership, with each trade assigned a specific pair of colors by municipal charter'],
      0,
      'Parti-colored dress, splitting a garment vertically into two different colors or fabrics, was most consistently used to display a lord\'s heraldic or livery colors, making retainers, servants, and sometimes the lord himself instantly recognizable at a distance by sight of his colors alone, a.',
    ],
    [
      'Nalbinding, the single-needle looped textile technique used in early medieval Europe (including well-documented Viking-age finds like those from Coppergate in York) for socks and mittens, is structurally distinguished from true knitting by which key characteristic?',
      ['Each new loop is pulled entirely through the previous one using a short length of thread repeatedly re-threaded through a single needle, rather than working live stitches held on two needles simultaneously', 'It requires no needle at all, being formed purely by finger-looping without any tool', 'It uses two needles like true knitting but produces a permanently fixed, unravelable fabric that cannot run or ladder', 'It is worked entirely in the round on a small circular frame with pegs, unlike the flat needles used for true knitting'],
      0,
      'Nalbinding used a single eyed needle and a comparatively short length of thread, which had to be periodically re-threaded as it was used up, to form each new loop by pulling it completely through the previous one, building a dense, non-runnable fabric one finished stitch at a time, structurally.',
    ],
    [
      'The fashion for \'slashing and puffing,\' cutting deliberate slits in an outer garment to pull contrasting fabric through in puffed sections, which spread across 16th-century Europe from German and Swiss fashion, is most commonly traced by historians to which originating context?',
      ['A practice popularly attributed to Swiss mercenary soldiers cutting and patching their clothing with looted or spare fabric after battles against Burgundian forces in the 1470s, later adopted deliberately as a style', 'An official German imperial fashion decree issued to distinguish free imperial city militia uniforms from territorial princes\' troops', 'A tailoring innovation developed specifically to accommodate quilted armor worn beneath civilian dress at court', 'A textile conservation technique originally used to repair moth-damaged fabric that became fashionable once visible'],
      0,
      'The popular historical account traces slashing and puffing to Swiss mercenary soldiers who, after victories over Burgundian forces in the 1470s (including the Burgundian Wars), supposedly patched their own damaged clothing with fabric looted from the defeated enemy\'s rich tents and baggage,.',
    ],
    [
      'Shot silk, also called changeable taffeta, achieves its characteristic shifting, two-tone color effect through which specific weave characteristic?',
      ['A warp of one color woven with a weft of a contrasting color, so the fabric\'s apparent color shifts depending on the viewing angle and which thread system catches the light', 'A single dye bath applied unevenly on purpose, leaving random patches of two different color saturations', 'Two separately woven layers of different colored silk bonded together back to back after weaving', 'An overprinted pattern applied after weaving using a resist-dye technique to create a two-tone illusion'],
      0,
      'Shot silk gets its shifting color effect from using genuinely different colored threads for the warp and weft, so a fabric might have, say, a blue warp and a red weft; because a plain or simple weave alternates which thread system dominates the visible surface as the viewing angle changes, the.',
    ],
    [
      'The Moy gown, a 16th-century wool garment recovered from an Irish bog near Moy, County Clare, is significant to Irish costume history chiefly because it demonstrates which point about regional dress in Ireland during this period?',
      ['That distinct, well-constructed regional Irish garment styles existed independently alongside, rather than as a simple copy of, contemporary English and continental fashion', 'That Irish wool garments of this period were universally undyed, contradicting documentary evidence of colorful Irish dress', 'That Irish gowns were constructed with the same graduated boning system used in contemporary English court bodices', 'That Ireland had no domestic wool weaving industry and relied entirely on imported English cloth for garment construction'],
      0,
      'The Moy gown, along with a small number of other Irish bog textile finds, gives rare physical evidence that Ireland had its own distinctive garment-cutting and construction traditions during this period, rather than dress in Ireland simply being a lagging or lesser copy of English and.',
    ],
    [
      'Modern textile conservation science can distinguish kermes-dyed from madder-dyed or cochineal-dyed historical red textiles primarily through which analytical method?',
      ['High-performance liquid chromatography (HPLC), which separates and identifies the specific chemical dye compounds present in a tiny extracted fiber sample', 'Simple visual comparison under ultraviolet light, since each dye source fluoresces a distinctly different color', 'Carbon-14 dating of the dye compound itself, which decays at a different rate depending on dye source', 'X-ray fluorescence spectroscopy, which detects trace heavy metals unique to each dye source'],
      0,
      'HPLC lets conservation scientists take a tiny sample from a historical textile, chemically extract the dye compounds present, and separate them into their individual chemical components, which can then be compared against known reference profiles for kermes, madder, cochineal, and other.',
    ],
    [
      'The Italian Renaissance luxury textile technique known as \'ciselé\' or voided velvet is defined by which specific structural feature?',
      ['Selective cutting of the pile loops in some areas while leaving them uncut in others, creating a pattern contrast between cut pile, uncut loop pile, and flat ground within the same woven textile', 'A double-thickness weave with an entirely separate backing fabric bonded on afterward for structural support', 'An embroidered overlay of metallic thread applied after the base velvet was completely woven and finished', 'A resist-dye process applied to plain velvet after weaving to create the appearance of a pattern'],
      0,
      'Ciselé, or voided, velvet was woven so that pile loops formed during weaving could be selectively cut in some areas while left uncut as loops in others, and some ground areas left with no pile at all, so a single piece of fabric combined cut pile, uncut loop pile, and flat woven ground in one.',
    ],
    [
      'The medieval European textile term \'baudekin\' (also rendered baldekin or the source of modern \'baldachin\'), used for a rich figured silk often woven with gold thread, derives its name from which trade-historical source?',
      ['Baghdad, reflecting the fabric\'s original association with luxury silk textiles reaching Europe through trade routes connected to that city', 'Bald, an Old English term for a specific weaving guild active in London\'s silk trade', 'Baudouin, a Flemish weaver credited with inventing the technique in the 13th century', 'Balducci, a Florentine merchant family that held an early monopoly on importing the fabric'],
      0,
      'Baudekin derives from Baghdad, reflecting how this rich, often gold-thread-woven silk textile reached medieval Europe closely associated with trade connections running through that great Islamic trading center, even though the fabric itself might ultimately have been produced across a range of.',
    ],

  ],
};
