import type { CategoryContent } from './row.js';

export const INORGANIC_CHEMISTRY: CategoryContent = {
  bscba: [
    [
      'What is the coordination number of the metal center in the complex [Cu(NH3)4]2+?',
      [
        '4',
        '2',
        '3',
        '6',
      ],
      0,
      'Four ammonia ligands directly bond to Cu(II), giving a coordination number of 4.',
    ],
    [
      'In crystal field theory, how does the energy of d-orbitals split in an octahedral metal complex?',
      [
        'The five d-orbitals are no longer degenerate; some are raised and some lowered in energy',
        'All five d-orbitals gain energy equally',
        'The d-orbitals split into s- and p-orbitals',
        'Only the dz2 orbital is affected by the ligand field',
      ],
      0,
      'Octahedral ligands break d-orbital degeneracy; t2g orbitals lower and eg orbitals raise relative to the barycenter.',
    ],
    [
      'What characterizes a Lewis acid-base interaction in coordination chemistry?',
      [
        'A coordinate covalent bond forms between an electron pair donor and an acceptor',
        'Transfer of protons between species',
        'Formation of ionic bonds between neutral ligands and metal ions',
        'Breaking of sigma bonds in the ligand',
      ],
      0,
      'Lewis acid (metal) accepts electrons from Lewis base (ligand), forming a coordinate covalent bond.',
    ],
    [
      'What is the primary difference between octahedral and tetrahedral coordination geometries?',
      [
        'Octahedral has 6 ligands in an approximately octahedral shape; tetrahedral has 4 ligands forming a tetrahedron',
        'Both geometries always have the same coordination number',
        'Tetrahedral is always more stable than octahedral',
        'The difference is only in color, not geometry',
      ],
      0,
      'Octahedral (CN=6, d-orbital splitting ~1.2 eV) is typical for d6–d9 metals; tetrahedral (CN=4, larger splitting) favors d0, d5, d10.',
    ],
    [
      'In transition metal chemistry, what does the spectrochemical series arrange?',
      [
        'Ligands in order of their crystal field splitting ability',
        'Metals in order of oxidation state stability',
        'Wavelengths of light absorbed by complexes',
        'Thermal stability of coordination compounds',
      ],
      0,
      'The series ranks ligands by Δ-splitting strength: CN− and CO are strong-field; I−, Br− are weak-field.',
    ],
    [
      'What type of isomerism is exhibited by [Co(NH3)5Cl]2+ and [Co(NH3)4(OH)]Cl?',
      [
        'Ionization isomerism',
        'Linkage isomerism',
        'Geometric isomerism',
        'Optical isomerism',
      ],
      0,
      'Ionization isomers differ in which anions are coordinated vs. counterions; one has Cl− bound, the other as a free ion.',
    ],
    [
      'In solid-state chemistry, what is a lattice parameter?',
      [
        'The distance between equivalent lattice points in a unit cell',
        'The number of atoms per unit cell',
        'The angle at which atoms repel each other',
        'The vibration frequency of atoms at equilibrium',
      ],
      0,
      'Lattice parameters (a, b, c, α, β, γ) define unit cell dimensions and are directly measurable by X-ray diffraction.',
    ],
    [
      'Which type of bond is characteristic of organometallic chemistry?',
      [
        'A direct metal-to-carbon covalent bond',
        'An ionic interaction via hydride transfer',
        'A hydrogen bond mediated by a bridging atom',
        'A van der Waals contact with no covalent character',
      ],
      0,
      'Organometallic compounds contain M–C σ bonds (alkyl) and π bonds (alkene, alkyne, carbene coordination).',
    ],
    [
      'What is the primary role of a catalyst in a metal-complex-catalyzed reaction?',
      [
        'Lower activation energy without being stoichiometrically consumed',
        'Shift the equilibrium constant to favor products',
        'Increase the enthalpy of the reaction',
        'Supply heat energy to the reaction system',
      ],
      0,
      'Catalysts lower Ea and are regenerated at the cycle end; they increase reaction rate but not ΔG.',
    ],
    [
      'In acid-base chemistry, what distinguishes a Brønsted acid from a Lewis acid?',
      [
        'Brønsted acids donate protons; Lewis acids accept electron pairs',
        'Brønsted acids are always stronger than Lewis acids',
        'Brønsted bases are related to Lewis bases by ionic bonding',
        'Lewis acids must be positively charged; Brønsted acids may be neutral',
      ],
      0,
      'Brønsted: H+ donor/acceptor. Lewis: electron pair acceptor/donor. All Brønsted acids are Lewis acids, but not vice versa (e.g., BF3).',
    ],
    [
      'What is hemoglobin\'s primary ligand in reversible oxygen binding?',
      [
        'The iron(II) center in a protoporphyrin IX heme group',
        'Histidine residues directly bind molecular oxygen',
        'Sulfide bridges coordinate oxygen molecules',
        'Carboxylate groups form reversible O2 adducts',
      ],
      0,
      'Fe(II) in heme porphyrin IX binds O2 reversibly; myoglobin operates similarly with higher oxygen affinity.',
    ],
    [
      'In the complex [Fe(CN)6]4−, how many electron pairs does cyanide donate to iron?',
      [
        '6 electron pairs (CN− is a 2-electron donor, 6 × 2 = 12 total)',
        '3 electron pairs',
        '6 unpaired electrons',
        '12 lone pairs from the ligands',
      ],
      0,
      'CN− donates 1 σ lone pair (2 electrons); six ligands donate 12 electrons total to form a very low-spin Fe(II) complex.',
    ],
    [
      'What is the typical coordination number for a tetrahedral complex?',
      [
        '4',
        '6',
        '8',
        '2',
      ],
      0,
      'Tetrahedral coordination places four ligands at the vertices of a tetrahedron around the central metal (CN = 4).',
    ],
    [
      'Which factor primarily determines whether a transition metal complex is colored?',
      [
        'd-orbital splitting allows visible-range electronic transitions between d-orbitals',
        'The presence of paramagnetic electrons in the complex',
        'The charge of the complex ion',
        'The mass of the ligand atoms',
      ],
      0,
      'Color arises from d–d transitions (if Δ falls in visible range, 400–700 nm) or charge-transfer absorptions.',
    ],
    [
      'What is the chelate effect, and why do chelating ligands form more stable complexes?',
      [
        'Multidentate ligands bind via multiple donor sites, increasing stability through entropic and enthalpic factors',
        'Chelating ligands form weaker bonds than monodentate equivalents',
        'Chelation requires ionic bonding only',
        'Chelating agents always contain nitrogen',
      ],
      0,
      'Chelation: multiple donors reduce the number of particles in solution (favorable ΔS); each donor-metal bond contributes to binding (cumulative ΔH).',
    ],
  ],
  msc: [
    [
      'Why does CN− cause larger crystal field splitting (Δ) than F− despite F− being smaller?',
      [
        'CN− is a strong σ-donor with significant π-backbonding from filled d-orbitals, while F− is purely σ-donating',
        'F− is a stronger field ligand because it is more electronegative',
        'Both ligands cause identical d-orbital splitting',
        'CN− and F− are incapable of forming octahedral complexes',
      ],
      0,
      'Strong-field ligands (CN−, CO) exploit π-backbonding; weak-field ligands (F−) donate σ only. π-interactions dramatically increase Δ.',
    ],
    [
      'In ligand field theory, what is the role of π-backbonding in metal-carbonyl complexes?',
      [
        'Metal d-electrons donate into unoccupied π* orbitals on CO, strengthening M–L bonding',
        'Ligand electrons are transferred irreversibly to the metal d-orbitals',
        'The metal oxidation state increases due to electron loss',
        'π-bonding is destructive and weakens complex stability',
      ],
      0,
      'Synergic effect: M→CO σ + CO←M π reinforce each other; π-backbonding lengthens C≡O and weakens it, increasing metal–ligand bond strength.',
    ],
    [
      'How does the Jahn–Teller effect manifest in octahedral Cu(II) d9 complexes?',
      [
        'Axial elongation or compression removes degeneracy, lowering ground-state energy',
        'The complex spontaneously expels one ligand to become square-pyramidal',
        'The metal oxidizes to Cu(III) to achieve a d8 configuration',
        'All octahedral Cu(II) complexes are perfectly symmetric',
      ],
      0,
      'Cu(II) d9 has one unpaired eg electron; distortion lifts this electron\'s degeneracy and stabilizes the complex (Jahn–Teller theorem).',
    ],
    [
      'What is the relationship between magnetic moment and unpaired d-electrons in transition metal complexes?',
      [
        'Unpaired electrons contribute ~1 Bohr magneton each; μ = √[n(n+2)] μB where n = unpaired electrons',
        'Magnetic moment is determined solely by atomic number',
        'Paired electrons in d-orbitals completely cancel all magnetism',
        'Only s-electrons contribute to the overall magnetic moment',
      ],
      0,
      'Spin-only approximation: μ ∝ √[n(n+2)]; orbital contributions and spin–orbit coupling refine this for first-row transition metals.',
    ],
    [
      'In the NaCl (rock-salt) structure, what is the coordination sphere of each ion?',
      [
        'Each Na+ is octahedrally surrounded by 6 Cl−, and each Cl− by 6 Na+',
        'Each ion is tetrahedrally coordinated to 4 opposite-charge neighbors',
        'Na+ and Cl− form alternating chains with CN = 2',
        'The structure is amorphous with no long-range order',
      ],
      0,
      'Rock-salt: both Na+ and Cl− adopt octahedral coordination (CN = 6) in an alternating FCC lattice. This high CN increases electrostatic stability.',
    ],
    [
      'What is the chelate effect, and how does it differ from simple ligand displacement?',
      [
        'Chelation provides entropic and enthalpic stabilization vs. monodentate ligands (chelate effect); reduces lability',
        'Monodentate ligands form stronger bonds than chelating ligands',
        'Chelation requires ionic bonding exclusively',
        'Chelating agents must contain only nitrogen donors',
      ],
      0,
      'Chelate effect: bidentate ligands increase ΔS (fewer particles) and provide cumulative ΔH; EDTA binds metal ions far more tightly than NH3.',
    ],
    [
      'How does electron density on the metal affect the reactivity of an organometallic complex?',
      [
        'Electron-rich metals are nucleophilic and attack electrophilic substrates; electron-poor metals attack nucleophilic substrates',
        'All metals exhibit identical reactivity regardless of electronic environment',
        'Only d10 metals are reactive in organometallic catalysis',
        'The ligand environment has no effect on metal reactivity',
      ],
      0,
      'Metal electronics (oxidation state, d-count, L-environment) determine electron density and reactivity: high e− density → nucleophilic.',
    ],
    [
      'What is the difference between "high-spin" and "low-spin" configurations in octahedral complexes?',
      [
        'High-spin: weak field → electrons spread across all 5 d-orbitals; low-spin: strong field → electrons fill lower orbitals first',
        'High-spin and low-spin refer to the nuclear spin state',
        'High-spin complexes are always tetrahedral; low-spin are octahedral',
        'The terms describe ligand steric bulk, not electronic effects',
      ],
      0,
      'Spin state depends on pairing energy P vs. splitting Δ: weak-field (Δ < P) → high-spin; strong-field (Δ > P) → low-spin.',
    ],
    [
      'In redox catalysis, how does the electron-transfer chain regenerate the catalyst?',
      [
        'Stepwise electron transfer: substrate reduced, intermediate oxidized back, catalyst regenerated and ready for the next cycle',
        'The metal center is permanently oxidized or reduced',
        'All electrons transfer simultaneously in a single step',
        'Reversibility is prevented to drive the reaction forward',
      ],
      0,
      'Catalytic cycle: M^n+ + substrate → M^(n±1) + product intermediate → M^n+ regenerated; the catalyst returns to its original oxidation state.',
    ],
    [
      'What structural role do histidine residues play in hemoproteins?',
      [
        'Histidine is the fifth axial ligand to heme iron, stabilizing the protein fold and tuning oxygen affinity',
        'Histidine directly binds oxygen molecules',
        'Histidine is bonded to the peptide backbone only',
        'Iron(III) hemoproteins never bind oxygen',
      ],
      0,
      'In hemoglobin and myoglobin, proximal histidine (imidazole N) bonds Fe(II) axially; the distal histidine assists O2 stabilization.',
    ],
    [
      'How does metal-to-ligand charge transfer (MLCT) differ from ligand-to-metal charge transfer (LMCT)?',
      [
        'MLCT: electron from metal d-orbital to ligand π*; LMCT: electron from filled ligand orbital to metal d-orbital',
        'Both processes are identical and the terms are interchangeable',
        'MLCT only occurs in neutral complexes; LMCT only in cationic species',
        'LMCT absorptions always occur at higher energy than MLCT',
      ],
      0,
      'MLCT favors low-valent, electron-rich metals (Ru(II)); LMCT favors high-valent, electron-poor metals (Fe(III)) and anionic ligands (O2−, S2−).',
    ],
    [
      'What is the empirical relationship between crystal field splitting (Δ) and absorption wavelength in d–d transitions?',
      [
        'The energy of the absorbed photon equals Δ; larger Δ shifts absorption to shorter wavelengths (blue shift)',
        'Δ is independent of absorption wavelength',
        'Longer wavelengths always correspond to larger crystal field splittings',
        'Absorption wavelength is determined by ligand mass, not splitting energy',
      ],
      0,
      'E_photon = hc/λ = Δ; strong-field complexes (large Δ) absorb at λ ~400 nm (blue); weak-field (small Δ) at λ ~900 nm (infrared).',
    ],
    [
      'In cytochrome P450 oxidation catalysis, what is the role of the iron center?',
      [
        'Fe(II) or Fe(III) cycles through oxidation states to activate O2 and form high-valent oxo species for hydroxylation',
        'Iron is a structural scaffold with no catalytic role',
        'Iron exclusively binds nitrogen and cannot interact with oxygen',
        'The protein backbone performs all oxygen activation',
      ],
      0,
      'P450: Fe(II) binds O2 → forms Fe(IV)=O (high-valent oxo) → hydroxylates C–H; essential for drug metabolism and biosynthesis.',
    ],
    [
      'What is the "18-electron rule" in organometallic chemistry?',
      [
        'Stable organometallic complexes often have 18 valence electrons, filling d, s, p orbitals like noble gases',
        'All metals must have exactly 18 d-electrons regardless of ligand',
        'The rule applies exclusively to main-group elements',
        '18 electrons guarantee complex decomposition',
      ],
      0,
      '18-electron rule: d10 + filled s/p = closed-shell analog to noble gas (Ar/Kr); promotes kinetic and thermodynamic stability.',
    ],
    [
      'How does the nephelauxetic effect relate to complex color in transition metals?',
      [
        'Ligand electron density expands d-orbitals, reducing interelectronic repulsion and decreasing Δ (red shift)',
        'Ligands increase effective nuclear charge on metal electrons',
        'Nephelauxetic effects always blue-shift complex colors',
        'Only p-block elements experience nephelauxetic effects',
      ],
      0,
      'Nephelauxetic ("cloud-expanding"): ligand electrons repel d-electrons, expanding d-orbital size; reduced d–d repulsion → smaller Δ → red shift.',
    ],
  ],
  phd: [
    [
      'In the angular overlap model (AOM), how do σ and π interactions contribute separately to d-orbital energies?',
      [
        'σ-donation and π-repulsion are treated as independent orbital overlaps; π from each ligand axis raises certain d-orbital energies (e.g., dxy, dxz)',
        'σ and π interactions have identical effects on all d-orbitals',
        'π-interactions have no effect on d-orbital energy levels',
        'All d-orbitals are equally stabilized by both σ and π interactions',
      ],
      0,
      'AOM: σ-bonding raises all d-orbitals; π-repulsion (perpendicular axes) raises dxy, dxz, dyz. Allows quantitative prediction of Δ.',
    ],
    [
      'What is the Bailar twist mechanism, and what does it explain?',
      [
        'An octahedral ↔ trigonal-prismatic pseudorotation allowing rapid ligand positional exchange without dissociating the complex',
        'A one-electron redox process yielding odd-electron intermediates',
        'Spontaneous decomposition of a complex at high temperature',
        'A symmetric rotation with no geometric changes',
      ],
      0,
      'Bailar twist: continuous octahedral → trigonal prism → octahedral distortion permutes ligand positions; explains stereochemical inversion in inert d3, d6 complexes.',
    ],
    [
      'How do σ-donation and π-backbonding in the M–CO bond reinforce one another (synergic effect)?',
      [
        'σ-donation increases metal e− density → enhanced π-backdonation to CO π*; weakens C≡O and stabilizes M–L bond',
        'π-backbonding cancels σ-donation effects',
        'σ-donation and π-backbonding are independent',
        'Only weak-field CO exhibits both σ and π interactions',
      ],
      0,
      'Synergic cycle: M→CO σ + CO←M π mutually reinforce; higher metal e− density strengthens both, making M–CO bonds exceptionally strong.',
    ],
    [
      'In the Born–Haber cycle, what is the lattice enthalpy and how is it related to crystal structure?',
      [
        'ΔH_latt is the energy to separate one mole of solid ionic compound into gaseous ions; correlates with ion size and charge',
        'Lattice enthalpy is the enthalpy of fusion',
        'Lattice enthalpy is the enthalpy of vaporization of one element',
        'Lattice enthalpy predicts only the color of the compound',
      ],
      0,
      'ΔH_latt ∝ (charges)/(inter-ionic distance); follows Born-Landé equation; larger charges and smaller ions increase ΔH_latt.',
    ],
    [
      'What role does spin–orbit coupling (SOC) play in electronic structure and spectroscopy of heavy transition metals?',
      [
        'SOC splits degenerate levels (fine structure), mixes spin and orbital angular momentum, and allows "forbidden" d–d transitions',
        'SOC is negligible for all first-row transition metals',
        'SOC makes singlet states unable to relax',
        'Only heavy metals exhibit SOC effects',
      ],
      0,
      'SOC ∝ Z^4; critical for 4d/5d metals; induces weak d–d transitions to become allowed (oscillator strength increase), raising absorbance intensities.',
    ],
    [
      'What is the role of the P-cluster in nitrogenase, and how does its redox state facilitate N2 reduction?',
      [
        '[Fe8S7Cys]^(++/+) oscillates oxidation states, shuttling electrons from the Fe protein to the FeMo-cofactor during N2 reduction',
        'The P-cluster has a fixed oxidation state and does not participate in electron transfer',
        'The P-cluster stores sulfide for N2 binding',
        'P-clusters are evolutionary relics with no function',
      ],
      0,
      'Nitrogenase P-cluster cycles between oxidation states, serving as the primary electron-transfer bridge; its redox potential is tuned by the protein.',
    ],
    [
      'What is the quantitative difference in packing efficiency between FCC and BCC structures?',
      [
        'FCC achieves ~74% packing (coordination number 12); BCC achieves ~68% (CN = 8); FCC is the close-packed arrangement',
        'BCC and FCC have identical packing efficiency',
        'BCC is always denser than FCC',
        'Packing fraction is independent of crystal geometry',
      ],
      0,
      'Close-packed structures (FCC, HCP): 74% packing, CN = 12; BCC: 68% packing, CN = 8. Packing efficiency is a fundamental structural descriptor.',
    ],
    [
      'In heterogeneous catalysis, what are ensemble effects and how do they control surface reactivity?',
      [
        'Substrate reactivity depends on the geometric arrangement and electronic state of metal surface atoms (specific facets, defects)',
        'All metal surfaces are chemically equivalent',
        'Heterogeneous catalysis depends only on bulk metal properties',
        'Surface structure has no influence on reaction mechanism',
      ],
      0,
      'Ensemble effects: substrate binds to multiple metals in a specific arrangement; changes in site density or compressive strain alter Ea and TOF.',
    ],
    [
      'What is the D4h point group, and which metal complexes adopt this geometry?',
      [
        'Square-planar (CN=4, coplanar): Pt(II), Au(III), Ni(II) with strong-field ligands; typically obeys 16-electron rule',
        'Tetrahedral complexes only; D4h cannot describe planar structures',
        'D4h is exclusive to octahedral geometries',
        'D4h is not a valid point group for transition metal complexes',
      ],
      0,
      'Square-planar D4h: 4 ligands in plane, metal at center. Examples: [PtCl4]2−, [AuCl4]−, cis-platin. Often features d8 metals.',
    ],
    [
      'In bonding models of transition metal carbonyls, explain the difference between synergic bonding and non-bonding electron repulsion.',
      [
        'Synergic: concerted σ-donation + π-backbonding mutually reinforce M–CO strength; non-bonding is incidental e−–e− repulsion',
        'Synergic bonding and non-bonding overlap are the same concept',
        'Non-bonding overlap is required for M–CO bonds; synergic bonding is rare',
        'Only CO exhibits synergic bonding; other ligands do not',
      ],
      0,
      'Synergic effect amplifies M–CO bonding via feedback; non-bonding e−–e− repulsion is a separate destabilizing factor. Synergy dominates.',
    ],
    [
      'What is oxidation state ambiguity in transition metal complexes with redox-active ligands?',
      [
        'Ligands like bipyridine, phenanthroline, semiquinones can accept/donate electrons; formal oxidation state assignment becomes ambiguous',
        'Oxidation states are always unambiguously assigned for all complexes',
        'Redox-active ligands are imaginary and do not exist',
        'Only metals, never ligands, participate in redox chemistry',
      ],
      0,
      'Redox-active ligands (bipy, phen, semiquinone): π-accepting or radical species that cycle oxidation states; true valence-state assignment is ambiguous.',
    ],
    [
      'In perovskite structures (ABX3), what does the Goldschmidt tolerance factor predict?',
      [
        't = (r_A + r_X) / [√2(r_B + r_X)]; t ≈ 1 cubic, t < 1 distorted/orthorhombic, t > 1 unfavorable',
        'The tolerance factor is irrelevant to perovskite stability',
        't is always 1 for all perovskites',
        'The tolerance factor predicts only color',
      ],
      0,
      'Tolerance factor: t ≈ 1 cubic perovskite; t < 1 tilting, octahedral rotation. Balances cation–anion radius ratios geometrically.',
    ],
    [
      'What is the Tolman electronic parameter (TEP) and how is it used in ligand characterization?',
      [
        'TEP is CO stretching frequency (ν_CO) of [Ni(L)(CO)3]; lower ν_CO → more donating ligand; quantifies electron-donation ability',
        'TEP measures ligand steric bulk only',
        'TEP is defined only for nitrogen-donor ligands',
        'Higher ν_CO values always indicate stronger donors',
      ],
      0,
      'Tolman parameter (cm−1): electron-rich ligands donate to Ni, lowering ν_CO; electron-poor (π-acceptors) withdraw, raising ν_CO. Quantitative donating ranking.',
    ],
    [
      'How do distortions from octahedral symmetry affect the d-orbital diagram?',
      [
        'Lowered symmetry removes degenerate orbital levels and splits them according to the new point group',
        'Distortions have no effect on d-orbital energies',
        'All distortions raise all d-orbitals equally',
        'Distortions increase octahedral symmetry',
      ],
      0,
      'Symmetry reduction (D4h, C3v, etc.) removes d-orbital degeneracy; axis-dependent orbitals split. This electronic origin drives Jahn–Teller distortions.',
    ],
    [
      'In heterometallic cluster complexes, what is the advantage of mixed-metal sites over homometallic clusters?',
      [
        'Different metals can activate distinct substrates or intermediates at nearby sites, enabling cooperative catalysis and substrate selectivity',
        'All metals in a cluster always behave identically',
        'Mixed-metal clusters are always less stable than single-metal clusters',
        'Different metals compete for the same site and reduce overall activity',
      ],
      0,
      'Heterometallic clusters: different metals tune redox potentials, substrate activation, and enable cooperative mechanisms (e.g., Fe–Co–S nitrogenase mimic).',
    ],
  ],
  professor: [
    [
      'How does ligand-field density-functional theory (LF-DFT) improve upon crystal field theory?',
      [
        'LF-DFT includes quantum-mechanical exchange, correlation, and covalency; enables non-empirical Δ calculation and f-orbital treatment',
        'LF-DFT is simply crystal field theory rebranded',
        'LF-DFT predicts only geometry',
        'LF-DFT has been superseded',
      ],
      0,
      'LF-DFT: all-electron or embedded-cluster DFT with ligand-field analysis; captures exchange/correlation and covalent mixing absent in CFT.',
    ],
    [
      'What is the spectroscopic origin of the yellow color in [Fe(H2O)6]3+, and why does LMCT dominate absorption?',
      [
        'Weak d–d transitions (~900 nm) are dwarfed by intense LMCT (OH2→Fe(III), ~400 nm); Fe(III) oxidizing power exceeds weak H2O-field strength',
        '[Fe(H2O)6]3+ is colorless',
        'Water is a strong-field ligand yielding low-spin Fe(III)',
        'All iron aquo complexes have identical spectra',
      ],
      0,
      '[Fe(H2O)6]3+ shows weak d–d (pale yellow); intense LMCT band (~400 nm) dominates because Fe(III) readily oxidizes H2O (Pourbaix diagram).',
    ],
    [
      'How does spin–orbit coupling facilitate intersystem crossing and nonradiative decay in metal complex photodynamics?',
      [
        'SOC mixes singlet and triplet states, lowering ISC barriers and accelerating radiationless relaxation to dark triplet states',
        'Spin–orbit coupling prevents all excited-state decay',
        'SOC is irrelevant to metal complex photophysics',
        'Only organic dyes experience intersystem crossing',
      ],
      0,
      'SOC (strong in 4d/5d) mixes S1 and T1 wavefunctions; lowers ISC barrier, promotes S1 → T1 transition, enabling long-lived phosphorescence.',
    ],
    [
      'What DFT-based framework explains substrate selectivity in nitrogenase (N2 vs. N2H+ reduction)?',
      [
        'Hydride-bonding intermediates, redox-state-dependent activation, and metal–sulfur cluster cooperativity; DFT modeling reveals state-specific selectivity',
        'Nitrogenase selects randomly',
        'Steric exclusion alone explains selectivity',
        'Quantum tunneling is the sole mechanism',
      ],
      0,
      'Nitrogenase selectivity: DFT shows hydride intermediates favor N2H+ at specific redox states; site geometry and cluster e−-transfer pathways enforce discrimination.',
    ],
    [
      'What is the p–d exchange interaction in transition metal oxides, and how does it control electronic properties?',
      [
        'Orbital mixing between metal d-bands and ligand p-bands modifies bandwidths, on-site energies, controlling charge-transfer character and insulator behavior',
        'p–d exchange is negligible in all oxides',
        'Only the d-band contributes; p-bands are inert',
        'p–d exchange always increases conductivity',
      ],
      0,
      'p–d mixing: ligand p-electrons couple to metal d-spins; lowers charge-transfer gap and is critical to Mott insulator vs. conductor boundary.',
    ],
    [
      'How does Marcus–Hush electron-transfer theory address reorganization energy in metal-complex redox catalysis?',
      [
        'λ = λ_inner (bond-length, vibrational) + λ_outer (solvent polarization); high-λ systems require large overpotentials for rapid ET',
        'Marcus theory is outdated',
        'Reorganization energy depends only on temperature',
        'All redox reactions have identical λ',
      ],
      0,
      'Marcus theory: λ_inner (geometry change) + λ_outer (solvent reorientation); high λ shifts reaction-coordinate minimum, raising Ea and overpotential.',
    ],
    [
      'What distinguishes inner-sphere from outer-sphere electron-transfer mechanisms catalyzed by transition metal complexes?',
      [
        'Inner-sphere: bridged ligand connects donor and acceptor, direct tunneling; outer-sphere: no bridge, electron hops through space',
        'Inner-sphere and outer-sphere mechanisms are identical',
        'Only outer-sphere mechanisms occur in biological systems',
        'Inner-sphere mechanisms always require a fully filled d-shell',
      ],
      0,
      'Inner-sphere: high rate ∝ bridge stability (OH− bridging Fe(II)–Fe(III)); outer-sphere: rate ∝ overlap at distance (hexaammine redox partners).',
    ],
    [
      'In homogeneous catalysis, what is the catalytic turnover number (TON) and what factors limit it?',
      [
        'TON = moles product / moles catalyst; limited by catalyst deactivation (side reactions, ligand loss, aggregation, product inhibition)',
        'TON is the speed of one catalytic cycle',
        'TON is independent of catalyst structure',
        'All homogeneous catalysts achieve infinite TON',
      ],
      0,
      'TON quantifies catalyst robustness; high TON requires kinetic stability against deactivation: ligand dissociation, redox-side reactions, precipitation.',
    ],
    [
      'In Type I blue copper centers, what electronic states enable rapid electron-transfer cycling in enzymes?',
      [
        'Cu(II) d9 distorted tetrahedral/trigonal; intense LMCT (600 nm, blue); reversible Cu(II)/(I) cycling with optimized geometry for fast ET',
        'Blue copper centers are always Cu(I) d10',
        'Blue copper has no electron-transfer role',
        'Blue color indicates copper poisoning',
      ],
      0,
      'Type I Cu(II): d9, intense LMCT (600 nm); geometrically optimized for rapid ET between redox partners; found in azurin, plantacyanin.',
    ],
    [
      'Why does [Fe(H2O)6]2+ have weak d–d transitions while FeS clusters show intense Fe–S charge-transfer absorption?',
      [
        '[Fe(H2O)6]2+ is d6 LS (weak d–d forbidden); FeS clusters exhibit strong Fe(d) → S(p*) MLCT (~400 nm) due to Fe–S covalency',
        '[Fe(H2O)6]2+ is always blue',
        'All iron complexes exhibit identical CT transitions',
        'Charge-transfer is irrelevant to iron biochemistry',
      ],
      0,
      '[Fe(H2O)6]2+ (d6, pale green) shows weak d–d (Δ ~10,000 cm−1); FeS clusters (nitrogenase, ferredoxin) display intense Fe–S MLCT due to high covalency.',
    ],
    [
      'How does the electronic nature of excited states (MC, MLCT, LMCT) influence photocatalytic performance in dye-sensitized solar cells?',
      [
        'MLCT states are long-lived (~1 μs), low-energy (~2 eV), enabling efficient electron injection into TiO2; MC states are reactive but short-lived',
        'All excited states are equally useful for photocatalysis',
        'Excited-state nature is irrelevant to photocatalytic efficiency',
        'Only LMCT states are useful',
      ],
      0,
      'DSSC: MLCT excited state of Ru(bpy)3 is long-lived (τ ~1 μs) and tuned for electron injection into TiO2 conduction band (E_inj favorable).',
    ],
    [
      'What does the Creutz–Taube complex [(NH3)5Ru–pyrazine–Ru(NH3)5]5+ reveal about valence delocalization?',
      [
        'This bridged Ru(II)–Ru(III) complex exhibits Robin–Day Class III delocalization; pyrazine bridge facilitates rapid e−-hopping, obscuring oxidation state',
        'Valence delocalization never occurs',
        'The Creutz–Taube complex is always trapped valence',
        'Bridging ligands prevent electron transfer',
      ],
      0,
      'Creutz–Taube: Class III mixed-valence (delocalized); IR/magnetic data show averaged Ru(II.5) valence; pyrazine π allows rapid inter-metal ET.',
    ],
    [
      'How do continuum solvation models (PCM, COSMO) refine DFT predictions of metal-complex redox potentials?',
      [
        'They solve Poisson–Boltzmann equation for bulk-solvent screening, correcting long-range Coulomb effects on ΔG(redox) vs. gas-phase DFT',
        'Solvation models have no effect on redox potential predictions',
        'Redox potentials depend exclusively on oxidation state',
        'Only explicit water molecules are relevant',
      ],
      0,
      'Continuum solvation (PCM): screens long-range Coulomb effects on oxidized/reduced states; refines computed E° predictions to within 0.1–0.2 V.',
    ],
    [
      'What is the role of hemilabile ligands in catalysis, and how do they differ from static chelating ligands?',
      [
        'Hemilabile ligands have one readily dissociable donor arm; dynamic fluxional behavior exposes substrate-binding sites without full decomposition',
        'Hemilabile ligands are permanently attached',
        'Static and hemilabile ligands have identical catalytic properties',
        'Hemilabile ligands only appear in stoichiometric reactions',
      ],
      0,
      'Hemilabile design: tailored dissociation energy of one arm balances substrate access (open site) with stability (one arm bound); improves TON/TOF.',
    ],
    [
      'What is the computational challenge in predicting spin-crossover (SCO) temperatures for iron(II) complexes?',
      [
        'Entropy contributions of molecular rearrangement (ΔS_vib) and electronic degeneracy must be calculated; small ΔG = ΔH − TΔS requires high accuracy',
        'SCO temperatures are experimentally fixed and never vary',
        'Only the enthalpy of the transition matters; entropy is irrelevant',
        'Computational methods always overestimate SCO temperatures by orders of magnitude',
      ],
      0,
      'SCO: DFT-predicted T_SCO requires accurate ΔH and ΔS (vibrational, electronic); narrow ΔG margin (~1 kJ/mol) demands high accuracy.',
    ],
  ],
};
