import type { CategoryContent } from './row.js';

/** Dutch & International IP Law. */

export const LAWIP: CategoryContent = {
  graduate: [
    [
      'The Dutch Burgerlijk Wetboek is organised into how many books?',
      ['ten', 'six', 'four', 'eight'],
      0,
      'The BW runs Book 1 (persons and family) through Book 10 (private international law), with Books 7 and 7A covering specific contracts. It replaced the old 1838 code in stages from 1970 to 1992.',
    ],
    [
      'The Hoge Raad der Nederlanden is best described as what?',
      [
        'The supreme court for civil, criminal and tax cases, reviewing on points of law',
        'The constitutional court that strikes down unconstitutional statutes passed by the States-General',
        'The highest administrative court for disputes with the government',
        'The court that tries government ministers for office-related offences',
      ],
      0,
      'The Hoge Raad does not retry facts; it is a court of cassation, checking whether the law was applied correctly. The Netherlands has no constitutional review of Acts of Parliament by the judiciary - Article 120 of the Constitution forbids it.',
    ],
    [
      'A trademark becomes vulnerable to cancellation for "genericide" when what happens?',
      [
        'It becomes the common name for the product in ordinary language, through the owner\'s own inaction',
        'It is used by a licensee without a written licence agreement',
        'It is registered in a class that does not match its actual use',
        'It is not renewed within five years of the original filing date set out in the relevant national trademark register',
      ],
      0,
      '"Aspirin" and "escalator" both lost trademark protection in the US this way. Owners defend against it by policing generic use and always pairing the mark with the product\'s generic name, e.g. "Velcro brand fasteners."',
    ],
    [
      'Under the Berne Convention, a member country may not require what as a condition of copyright protection?',
      [
        'Any formality, such as registration or a copyright notice',
        'Publication within the country of origin',
        'Translation into the language of the country claiming protection',
        'Payment of a filing fee to a national copyright office',
      ],
      0,
      'Berne\'s "no formalities" rule (Article 5(2)) is why copyright is automatic on creation almost everywhere. The US only joined Berne in 1989 and had to abandon its mandatory notice requirement to comply.',
    ],
    [
      'The standard Berne Convention minimum term for copyright is what?',
      [
        'Life of the author plus 50 years',
        'Life of the author plus 70 years',
        '50 years from first publication, regardless of authorship',
        '25 years from creation',
      ],
      0,
      'Berne sets the floor at life-plus-50; the EU raised its own term to life-plus-70 in 1993, and the US matched that in 1998 with the Sonny Bono Act. Many countries still sit at the Berne minimum.',
    ],
    [
      'The European Patent Office grants what kind of right?',
      [
        'A bundle of national patents in the designated states, not a single EU-wide patent',
        'A single patent enforceable identically in every EU member state',
        'A patent valid only in Germany, France and the UK, with no possibility of extension to any other contracting state',
        'A provisional right that must be confirmed by each country\'s own patent office',
      ],
      0,
      'A "European patent" granted by the EPO under the European Patent Convention is really a bundle: it must be validated and can be separately revoked or licensed in each designated country. The Unitary Patent, which finally creates one single right, only started operating in 2023.',
    ],
    [
      'To be patentable in most systems, an invention must be novel, non-obvious (inventive) and what?',
      ['Susceptible of industrial application', 'Filed by a corporation', 'Kept secret for one year before filing', 'Reduced to a physical prototype'],
      0,
      'Novelty, inventive step and industrial applicability are the three EPC pillars (Article 52). "Reduction to practice" is a US-specific historical concept from the old first-to-invent system, not a general requirement.',
    ],
    [
      'The Dutch word "auteursrecht" translates most directly to what?',
      ['Author\'s right', 'Publishing licence', 'Trade secret', 'Registered design'],
      0,
      'Continental European systems, including the Dutch one, frame copyright as an "author\'s right" centred on the creator\'s personal and moral connection to the work, in contrast with the Anglo-American "copyright" tradition, which historically centred on the economic right to copy.',
    ],
    [
      'The Benelux trademark and design system is unusual because it does what?',
      [
        'Registers a single mark valid across Belgium, the Netherlands and Luxembourg as one territory',
        'Requires separate filings in each of the three countries',
        'Only covers trademarks, not designs, since design protection is handled exclusively by each country\'s national office',
        'Grants protection automatically without any registration',
      ],
      0,
      'The Benelux Office for Intellectual Property (BOIP) predates the EU trademark system and still runs a genuinely unified three-country registration, one of the oldest supranational IP regimes in the world.',
    ],
    [
      'Hugo Grotius is most often credited as a foundational figure of what field?',
      ['International law, especially the law of the sea and just war theory', 'Dutch criminal procedure', 'Trademark law, particularly the registration procedures used by the Benelux Office for Intellectual Property', 'Modern tax law'],
      0,
      'Grotius\'s "Mare Liberum" (1609) argued the sea could not be owned by any nation, defending Dutch trading rights against Portuguese claims, and his "De Jure Belli ac Pacis" (1625) is a foundation of the modern law of war and peace.',
    ],
    [
      'WIPO, the World Intellectual Property Organization, operates as what?',
      [
        'A specialised agency of the United Nations administering IP treaties',
        'A branch of the World Trade Organization responsible specifically for enforcing trade-related sanctions',
        'An EU institution with authority only over member states',
        'A private industry association with no treaty-making role',
      ],
      0,
      'WIPO became a UN specialised agency in 1974 and administers treaties like the Paris Convention, Berne Convention, PCT and Madrid Protocol, though it has no independent enforcement power - that is left to national courts and, for trade-related disputes, the WTO.',
    ],
    [
      'The Paris Convention\'s "priority right" allows an applicant who files a patent or trademark in one member country to do what?',
      [
        'File in other member countries within a set period while keeping the original filing date',
        'Automatically receive protection in every other member country',
        'Extend the term of protection in the country of first filing by an additional period equal to the priority window itself',
        'Transfer the application to another applicant without a formal assignment',
      ],
      0,
      'The priority period is 12 months for patents and 6 months for trademarks and designs. It exists precisely because simultaneous worldwide filing was never realistic, so the Convention lets a later foreign filing be treated as if it happened on the first filing date.',
    ],
    [
      'The Raad van State (Council of State) in the Netherlands performs which dual role?',
      [
        'Advising the government on draft legislation and acting as the highest general administrative court',
        'Serving as the upper house of Parliament',
        'Prosecuting corruption cases against civil servants',
        'Auditing the national budget and publishing an annual report reviewed directly by the States-General each autumn',
      ],
      0,
      'This dual advisory-and-judicial role dates back to 1531 in some form, and the administrative court function was formally consolidated when the Netherlands reorganised administrative justice in the 1990s.',
    ],
    [
      'The economic rights in a copyrighted work (e.g. reproduction, distribution) differ from moral rights chiefly because moral rights do what?',
      [
        'Protect the author\'s personal connection to the work (attribution, integrity) and are generally non-transferable',
        'Can be freely bought and sold like any other property',
        'Only exist in common-law jurisdictions, where they were first codified in early twentieth-century statutes governing artistic and literary works',
        'Expire immediately on the work\'s first publication',
      ],
      0,
      'Moral rights - the right of attribution and the right against distortion or mutilation of the work - are treated in most civil-law systems, including the Dutch one, as inalienable even after the economic rights are assigned or sold.',
    ],
    [
      'EU law\'s relationship to Dutch domestic law is governed by the principle that EU law has what?',
      [
        'Primacy over conflicting national law, with directly effective provisions applied by Dutch courts',
        'No effect unless separately re-enacted by the Dutch parliament',
        'Effect only in tax and customs matters, and even then only after formal ratification by the States-General',
        'Primacy only over Dutch case law, not statutes',
      ],
      0,
      'The Netherlands\' famously EU-friendly (monist) constitutional tradition, combined with CJEU doctrines of primacy and direct effect established in cases like Van Gend en Loos - itself a Dutch case - means Dutch courts routinely set aside conflicting domestic provisions.',
    ],
  ],
  phd: [
    [
      'Van Gend en Loos (1963), the case that established direct effect in EU law, arose from a dispute over what?',
      [
        'A Dutch importer challenging a customs duty increase on a chemical product as contrary to the EEC Treaty',
        'A trademark dispute between two Dutch textile firms',
        'A Dutch copyright claim against a German publisher over unauthorised translation rights in a technical manual',
        'A patent infringement claim brought before the Hoge Raad',
      ],
      0,
      'Van Gend en Loos NV challenged a reclassification that raised the duty on formaldehyde-based glue imported from Germany, arguing it breached the Treaty\'s standstill on customs duties - a mundane trade dispute that produced one of the most important rulings in EU legal history.',
    ],
    [
      'The "likelihood of confusion" test in EU trademark law under the EUTMR weighs which factors together?',
      [
        'The similarity of the signs, the similarity of the goods/services, and the distinctiveness of the earlier mark, assessed globally',
        'Only whether the two marks are visually identical',
        'Only the reputation of the later-filed mark, regardless of any similarity between the goods or services offered under each sign or the earlier mark\'s own distinctiveness',
        'Only whether the goods are sold in the same physical shops',
      ],
      0,
      'The CJEU\'s "global assessment" doctrine, from cases like Sabel v Puma and Canon v MGM, treats these factors as interdependent - a highly distinctive earlier mark can create confusion even against a fairly dissimilar later sign, since distinctiveness and similarity trade off against each other.',
    ],
    [
      'Article 17 of the EU\'s 2019 Copyright Directive (formerly the contentious "Article 13") primarily addresses what?',
      [
        'The liability of online content-sharing platforms for copyright-infringing user uploads',
        'The harmonisation of copyright term across member states, a topic instead addressed by the separate Term Directive of 1993',
        'The right of academic authors to retain copyright in journal articles',
        'The scope of the private copying exception for physical media',
      ],
      0,
      'Article 17 makes platforms like YouTube directly liable for unauthorised uploads unless they obtain licences or make "best efforts" to prevent availability of notified works - a shift from the prior "safe harbour" hosting-liability model under the eCommerce Directive.',
    ],
    [
      'The Unified Patent Court (UPC), which began operating in 2023, has jurisdiction over what?',
      [
        'Infringement and validity of European patents and Unitary Patents across participating member states',
        'Only Unitary Patents, not classical European patents',
        'Only patent disputes involving pharmaceuticals',
        'Trademark disputes across the EU, a matter instead reserved exclusively to the EUIPO and national trademark courts',
      ],
      0,
      'The UPC gives a single court system jurisdiction over both the new Unitary Patent and, during a transition period, classical European patents (unless opted out), replacing the need to litigate infringement separately in each country - the single biggest structural change to European patent litigation in decades.',
    ],
    [
      'The Peace of Münster (1648), ending the Eighty Years\' War, is significant in international law for what?',
      [
        'Recognising the Dutch Republic\'s full sovereign independence from Spain',
        'Establishing the first European patent system',
        'Creating the Benelux customs union, an arrangement not formed until three centuries later, after the Second World War',
        'Founding the VOC as a chartered trading company',
      ],
      0,
      'Münster (part of the wider Peace of Westphalia) formally ended Spanish claims over the Republic after eighty years of revolt, and is often cited alongside Westphalia generally as an early landmark of the modern state-sovereignty system that underlies international law.',
    ],
    [
      'The "exhaustion of rights" doctrine in EU trademark and copyright law means what?',
      [
        'Once goods are first put on the market in the EEA with the rightsholder\'s consent, the rightsholder cannot block their further resale within the EEA',
        'A trademark right expires permanently after ten years',
        'Copyright cannot be exhausted, only trademarks can, since copyright is treated in most civil-law systems as a personal right attached permanently to its author regardless of any sale',
        'A rightsholder can block parallel imports from anywhere once goods leave the factory',
      ],
      0,
      'This is the legal basis for the EU\'s single market in genuine goods: cases like Silhouette v Hartlauer confirmed the EU applies regional (not international) exhaustion, so a rightsholder CAN still block parallel imports from outside the EEA even after EEA-consented first sale.',
    ],
    [
      'The Dutch "lex Wolff" / notion of "onrechtmatige daad" (wrongful act) in Book 6 BW corresponds most closely to which common-law concept?',
      ['Tort liability', 'Consideration in contract formation', 'Adverse possession', 'Promissory estoppel'],
      0,
      'Article 6:162 BW\'s onrechtmatige daad is the Dutch general tort provision, requiring a wrongful act attributable to the defendant, damage, and causation - structurally similar to common-law negligence but derived from a civilian codified-fault tradition rather than case-by-case duty analysis.',
    ],
    [
      'TRIPS (the WTO\'s Agreement on Trade-Related Aspects of Intellectual Property Rights) was significant because it did what?',
      [
        'Bound WTO members to minimum IP standards enforceable through WTO dispute settlement',
        'Abolished patents on pharmaceuticals in developing countries',
        'Replaced the Berne and Paris Conventions entirely',
        'Created WIPO as a new international body, when in fact WIPO had already existed as a UN specialised agency two decades earlier',
      ],
      0,
      'TRIPS (1994) was the first IP agreement backed by a binding, cross-retaliation-capable enforcement mechanism - a WTO member found in breach can face trade sanctions in unrelated sectors, which is far stronger than anything WIPO treaties alone provided.',
    ],
    [
      'The Dutch "Grand Pensionary" (Raadpensionaris) of Holland, exemplified by Johan de Witt, functioned as what?',
      [
        'The leading political officer of the States of Holland, often the Republic\'s de facto chief statesman during stadtholderless periods',
        'The military commander-in-chief of the Dutch army',
        'The presiding judge of the Hoge Raad\'s predecessor court',
        'The head of the VOC\'s board of directors, a role that in fact carried no formal political authority over the States of Holland whatsoever',
      ],
      0,
      'During the "First Stadtholderless Period" (1650-1672), with no stadtholder from the House of Orange in Holland, de Witt as Grand Pensionary effectively ran Republic policy - until the disastrous Rampjaar of 1672 saw him and his brother Cornelis lynched by an Orangist mob.',
    ],
    [
      'The CJEU\'s ruling in Levola Hengelo v Smilde Foods (2018) addressed whether what could be protected by copyright?',
      [
        'The taste of a food product',
        'The recipe for a Dutch cheese spread as a literary work',
        'The trademark "Heks\'nkaas" itself',
        'The packaging design of a spreadable cheese',
      ],
      0,
      'The CJEU held that taste cannot be copyrighted because it cannot be identified with sufficient precision and objectivity to meet the "work" requirement under EU copyright law - a Dutch case (over the herb-cheese spread Heks\'nkaas) that settled a genuinely open doctrinal question.',
    ],
    [
      'The Madrid Protocol allows a trademark owner to do what?',
      [
        'File one international application designating multiple member countries through a single WIPO-administered procedure',
        'Obtain a single trademark automatically valid worldwide',
        'Skip national examination entirely in every designated country',
        'Register a mark that is generic in its country of origin, something no international or national trademark system permits regardless of filing route',
      ],
      0,
      'Madrid centralises filing and renewal administratively, but each designated country\'s office still examines the mark under its own substantive law and can refuse it - it is a filing convenience, not a single unitary right, which is a common point of confusion.',
    ],
    [
      'The doctrine of "first sale" in US copyright law and "exhaustion" in EU law both limit which right?',
      [
        'The distribution right, once a particular copy has been lawfully sold',
        'The reproduction right for digital copies',
        'The moral right of attribution, which in most jurisdictions cannot be exhausted by any sale of a physical or digital copy',
        'The right to perform the work publicly',
      ],
      0,
      'Both doctrines let the owner of a lawfully acquired physical copy resell or lend it without the copyright holder\'s further permission, since the distribution right is considered spent (exhausted) by the first authorised sale of that specific copy - though EU case law (e.g. UsedSoft) controversially extended a version of this to some downloaded software.',
    ],
    [
      'The 1839 Treaty of London, which finalised Belgian independence from the Netherlands, also famously guaranteed what?',
      [
        'The perpetual neutrality of Belgium, later invoked by Britain in 1914',
        'Dutch sovereignty over the entire Scheldt estuary',
        'A permanent customs union between Belgium and the Netherlands',
        'Luxembourg\'s incorporation into the Netherlands, an arrangement that in fact never took effect under the treaty\'s final terms',
      ],
      0,
      'Britain\'s treaty obligation to defend Belgian neutrality became the proximate legal trigger for its declaration of war on Germany in August 1914 after the German invasion of Belgium - a nineteenth-century Dutch-Belgian settlement with an outsized twentieth-century consequence.',
    ],
    [
      'Under EU design law, an unregistered Community design gives the holder protection against what, specifically?',
      [
        'Deliberate copying only, not independent creation of a similar design',
        'Any identical or similar design regardless of how it was created',
        'Nothing - unregistered designs receive no EU-level protection at all',
        'Only designs registered in the same member state as the holder, an approach the EU regime does not follow at all',
      ],
      0,
      'This is the key practical difference from a registered Community design, which is a true monopoly right effective even against independent creators: the unregistered right (lasting only three years) requires proving the alleged infringer actually copied the design.',
    ],
    [
      'The 1585 Fall of Antwerp to Spanish forces during the Dutch Revolt had which major long-term economic consequence for Amsterdam?',
      [
        'A large influx of skilled merchants and refugees from the southern Netherlands fleeing north, fuelling Amsterdam\'s rise as a commercial centre',
        'The permanent loss of Amsterdam\'s access to the North Sea',
        'The transfer of the VOC\'s charter from Amsterdam to Antwerp',
        'A ban on Amsterdam trading with the Baltic region, a restriction that was never actually imposed by any Dutch, Spanish, or Hanseatic authority at any point during this period',
      ],
      0,
      'The Spanish reconquest of Antwerp, followed by the Dutch closure of the Scheldt to shipping, pushed capital, skilled labour and Calvinist merchants north - a migration widely credited as one of the key sparks of the Dutch Golden Age just as Antwerp\'s own commercial dominance collapsed.',
    ],
  ],
  professor: [
    [
      'In Sabam v Netlog (2012) and Scarlet Extended v SABAM (2011), the CJEU held that requiring an internet service provider to install a general content-filtering system to prevent copyright infringement would violate what?',
      [
        'The prohibition on imposing a general monitoring obligation under the eCommerce Directive, balanced against fundamental rights',
        'The Berne Convention\'s minimum term requirement',
        'The Paris Convention\'s national treatment principle',
        'The Rome Convention on performers\' rights, an instrument dealing with an entirely separate category of related rights unconnected to filtering obligations',
      ],
      0,
      'The Court held such filtering obligations would breach Article 15 of the eCommerce Directive (no general monitoring duty) and disproportionately burden the ISP\'s freedom to conduct business and users\' rights to data protection and free expression - a line of reasoning later complicated, but not overturned, by Article 17 of the 2019 Copyright Directive, which the Court had to separately reconcile in Poland v Parliament and Council (2022).',
    ],
    [
      'The Benelux Court of Justice, established in 1974, was historically significant as what?',
      [
        'One of the earliest international courts empowered to give preliminary rulings on shared Benelux legislation, including uniform trademark and design law',
        'The final court of appeal for all Dutch criminal cases, a function that in fact remains exclusively with the Hoge Raad der Nederlanden, as it always has been',
        'The first court to apply the CJEU\'s doctrine of direct effect',
        'The court that adjudicated the Dutch-Belgian border dispute over Baarle-Nassau',
      ],
      0,
      'It predates and partly modelled the preliminary-reference mechanism later scaled up hugely by the CJEU, and for decades was the authoritative interpreter of the Uniform Benelux Trademark and Designs Laws before EU-level unification largely displaced its IP docket.',
    ],
    [
      'The "Rampjaar" of 1672 saw the Dutch Republic simultaneously at war with which combination of powers?',
      [
        'France, England, and the bishoprics of Münster and Cologne',
        'Spain, Portugal, and the Holy Roman Empire',
        'Sweden, Denmark, and the Hanseatic League',
        'Austria, Prussia, and Poland-Lithuania, none of which were in fact involved in the Rampjaar coalition against the Republic',
      ],
      0,
      'The "Disaster Year" combined Louis XIV\'s invasion (the Franco-Dutch War) with the Third Anglo-Dutch War and attacks by the allied bishops of Münster and Cologne - a near-simultaneous four-front crisis that led directly to the lynching of Johan and Cornelis de Witt and William III\'s rise to power.',
    ],
    [
      'In the CJEU\'s Football Dataco v Yahoo! (2012) ruling, the Court held that copyright protection for a database under the Database Directive requires what, specifically excluding what?',
      [
        'Original selection or arrangement reflecting the author\'s free creative choices, excluding significant labour and skill in collecting the data',
        'Only that significant financial investment went into compiling the data',
        'That the database be registered with a national IP office before litigation',
        'That the data itself be original, regardless of arrangement, a requirement the Database Directive does not in fact impose on copyright protection',
      ],
      0,
      'This decoupled copyright protection from the separate sui generis database right (which does protect investment in obtaining/verifying/presenting data): "sweat of the brow" alone - here, the skill in scheduling football fixtures - cannot ground copyright, only genuine creative selection or arrangement can.',
    ],
    [
      'The doctrine from IHT Internationale Heiztechnik v Ideal-Standard (1994) on trademark exhaustion within corporate group restructurings addressed what specific scenario?',
      [
        'Whether a trademark assigned to an unrelated entity in one member state could still be used to block imports of genuine goods bearing the same mark from another member state after the assignment severed economic links',
        'Whether a franchisee could use a trademark after the franchise agreement ended',
        'Whether a trademark could be registered simultaneously by two unrelated companies in different EU states',
        'Whether trademark rights survive the bankruptcy of the original owner, a distinct insolvency-law question governed by national bankruptcy statutes and the EU Insolvency Regulation rather than by the CJEU\'s trademark exhaustion case law at issue in this particular reference',
      ],
      0,
      'The CJEU held that once trademark rights in different states are held by entities with no continuing economic connection, the assignee CAN block imports of the other party\'s genuine goods under that mark - voluntary fragmentation of ownership breaks exhaustion, unlike a mere corporate reorganisation retaining unified control.',
    ],
    [
      'The 1667 Treaty of Breda, ending the Second Anglo-Dutch War, is remembered for the territorial exchange in which the Dutch retained what, while ceding New Netherland (New York) to England?',
      [
        'Suriname and the nutmeg-producing island of Run in the Banda Islands',
        'Ceylon and the Cape Colony',
        'Formosa and the Pescadores',
        'Malacca and Batavia, two territories the Dutch already firmly held well before the 1667 treaty was ever negotiated',
      ],
      0,
      'The Dutch judged Suriname\'s sugar plantations and, crucially, sole control of nutmeg-rich Run (already effectively secured) more valuable than Manhattan - a decision that reads very differently with three and a half centuries of hindsight than it did to contemporaries fixated on the spice trade.',
    ],
    [
      'Article 6bis of the Berne Convention, on moral rights, was historically resisted by the United States chiefly because of tension with what feature of pre-1976 American copyright practice?',
      [
        'The "work made for hire" doctrine, under which the employer, not the individual creator, is deemed the author',
        'The absence of any copyright registration system',
        'The shorter US copyright term relative to Europe',
        'The US practice of granting copyright only to citizens, a restriction that in fact never existed under US copyright law at any point',
      ],
      0,
      'Work-for-hire assigns original authorship itself to the corporate employer, which sits awkwardly against a moral right premised on a personal bond between an individual creator and the work - part of why the US, on joining Berne in 1989, took the position that existing US law (trademark-style unfair competition and defamation remedies) already sufficed, rather than enacting a general moral rights statute.',
    ],
    [
      'The CJEU\'s "essential function" doctrine, developed from Hoffmann-La Roche v Centrafarm (1978) onward, defines a trademark\'s core legal purpose as what?',
      [
        'Guaranteeing the identity of origin of the marked goods or services to the consumer',
        'Maximising the economic return to the rightsholder',
        'Preventing any third party from ever using a similar sign',
        'Signalling the geographic origin of the goods, a function performed instead by geographical indications, not by ordinary trademark law',
      ],
      0,
      'This "origin function" reasoning (a Dutch-referred case, against the Dutch pharmaceutical repackager Centrafarm) is the doctrinal anchor the CJEU still uses to decide how far a trademark owner may control repackaging, rebranding and parallel trade - protection extends only so far as needed to preserve that guarantee-of-origin, not to shield the owner from all competition.',
    ],
    [
      'The 1780-1784 Fourth Anglo-Dutch War is distinguished from the prior three chiefly because it arose over what?',
      [
        'British retaliation against covert Dutch trade with the rebelling American colonies, exposed by the Amsterdam merchant William Lee\'s draft treaty',
        'A dispute over fishing rights in the North Sea',
        'Dutch support for the Jacobite rising, an episode that took place decades earlier and involved no formal Dutch state participation whatsoever, contrary to occasional popular claims',
        'Competition over the Spice Islands with the Portuguese',
      ],
      0,
      'The discovery of a draft Dutch-American treaty carried by the captured American diplomat Henry Laurens gave Britain a pretext to declare war before the Dutch could join the League of Armed Neutrality, and the war proved catastrophic for the already-declining Republic\'s trade and finances.',
    ],
    [
      'In Dutch copyright doctrine, the "geschriftenbescherming" (protection of writings) was a sui generis regime that protected what, before its abolition in 2018?',
      [
        'Non-original written texts (like schedules or catalogues) lacking the "own, original character" needed for full copyright',
        'Oral folklore and unwritten traditions',
        'Computer source code specifically',
        'Photographs lacking artistic merit, a category that in fact was never covered by this specifically text-focused sui generis doctrine',
      ],
      0,
      'This uniquely Dutch doctrine gave a thin protection (mainly against literal copying) to purely factual or functional texts that failed the ordinary originality threshold; it was scrapped by legislative amendment after the CJEU\'s Football Dataco and Infopaq line of cases made clear EU copyright law required a genuine originality standard with no room for a lesser national regime.',
    ],
    [
      'The Statute for the Kingdom of the Netherlands (1954) restructured the relationship between the Netherlands, Suriname and the Netherlands Antilles chiefly by doing what?',
      [
        'Establishing them as equal constituent countries within one Kingdom, replacing colonial subordination, short of full independence',
        'Granting Suriname and the Antilles immediate full independence',
        'Merging all three into a single unitary state, an outcome the 1954 Statute was in fact specifically designed to avoid at every stage of the negotiations',
        'Placing them under United Nations trusteeship',
      ],
      0,
      'The Statuut created a genuinely novel constitutional form - a Kingdom of formally equal countries sharing a head of state, defence and foreign affairs - that survives today between the Netherlands, Aruba, Curaçao and Sint Maarten, after Suriname exercised its right under the Statute to secede to full independence in 1975.',
    ],
    [
      'The CJEU\'s ruling in Deckmyn v Vandersteen (2014) on the parody exception under the InfoSoc Directive held that a "parody" must satisfy which two conditions, without needing to satisfy others often assumed?',
      [
        'Evoking the original work while being noticeably different from it, and constituting an expression of humour or mockery, without needing originality of its own or explicit attribution of a comic intent',
        'Being registered as a parody with a national copyright authority and obtaining prior consent from the original author, formalities that no EU member state\'s copyright law in fact requires for the exception to apply',
        'Being non-commercial and used only for private, personal purposes',
        'Being shorter than the original work and using no more than ten percent of it',
      ],
      0,
      'The Court also held, unusually, that national courts must weigh the legitimate interests of the original author against expression rights - and in the underlying dispute, a Belgian case about a racist reworking of a "Spike and Suzy" comic cover, left room for the parody defence to fail anyway if the parody\'s message conveyed a discriminatory message harmful to the original author\'s reputation.',
    ],
    [
      'Grotius\'s concept of "mare liberum" was directly opposed by the English jurist John Selden in a treatise arguing for what?',
      [
        '"Mare clausum" - that the sea, or portions of it, could indeed be subject to sovereign ownership and closure',
        'The abolition of all maritime trade regulation',
        'Universal freedom of navigation with no exceptions, a position Selden explicitly rejected rather than argued for in his own treatise',
        'Papal authority over division of the oceans between Spain and Portugal',
      ],
      0,
      'Selden\'s "Mare Clausum" (written around 1618 but published in 1635) was commissioned partly in response to Dutch fishing in what England considered its waters, and the Grotius-Selden dispute over open versus closed seas is still cited as the founding fault line of modern debates over maritime jurisdiction and, later, exclusive economic zones.',
    ],
    [
      'The "Slovak Telekom" and earlier "Bronner" lines of CJEU case law on refusal to license/supply as abuse of dominance under Article 102 TFEU are doctrinally significant to IP law because they define when what must yield to competition law?',
      [
        'An IP owner\'s right to refuse a licence, in narrow circumstances where refusal forecloses competition on a related market and the input is genuinely indispensable',
        'All patents automatically expire once the holder is found dominant in any market',
        'Trademark owners must license competitors on request in every EU member state',
        'Copyright cannot be enforced against a dominant firm under any circumstances, a blanket rule no EU competition or copyright authority has ever actually adopted in any reported decision',
      ],
      0,
      'Bronner (1998) set a demanding indispensability-plus-foreclosure test that made compulsory licensing under competition law genuinely exceptional (contrast the earlier, more interventionist Magill), and this tension between rewarding IP-driven investment and preventing anticompetitive foreclosure remains one of the most doctrinally contested intersections between IP and competition law in the EU.',
    ],
    [
      'The Twelve Years\' Truce (1609-1621) in the Eighty Years\' War is notable in Dutch legal and colonial history chiefly because it coincided with what?',
      [
        'A domestic religious-political crisis (the Arminian/Gomarist dispute) resolved at the Synod of Dort, and the chartering of the Dutch West India Company just after the truce lapsed',
        'The founding of the VOC, which had in fact already been chartered in 1602',
        'The abolition of the office of stadtholder, a step the Republic in fact never took at any single point in time before the French invasion of 1795 finally dissolved the Republic altogether for good',
        'The permanent cession of the Dutch East Indies to Portugal',
      ],
      0,
      'With the external war paused, internal tensions between Arminian "Remonstrants" (favouring provincial and States-of-Holland authority, associated with Grand Pensionary Oldenbarnevelt) and orthodox Calvinist "Gomarists" (backed by Stadtholder Maurice) escalated to the 1618-1619 Synod of Dort and Oldenbarnevelt\'s execution - a reminder that the Truce years were a fight over the Republic\'s internal constitutional balance, not merely a lull in the war with Spain.',
    ],
  ],
};
