import type { CategoryContent } from './row.js';

/**
 * Greek Mythology, Norse Mythology, Celtic & Arthurian Mythology, Assyrian & Phoenician History & Mythology.
 */

export const GREEK_MYTH: CategoryContent = {
  msc: [
    [
      'In Hesiod\'s Theogony, the Erinyes (Furies), the Giants, and the Meliae (ash-tree nymphs) are all said to spring from the same single event. What is it?',
      ['The blood of Uranus\'s castration falling on Gaia', 'The blood spilled during the Titanomachy soaking into the earth', 'Cronus\'s own blood scattering as he died', 'Typhon\'s blood scattered across the earth after his defeat'],
      0,
      'Hesiod\'s Theogony (lines 176-187) describes Cronus castrating his father Uranus with a sickle and casting the severed genitals away; the drops of blood that fell on Gaia (Earth) produced the Erinyes, the Giants, and the Meliae all at once.',
    ],
    [
      'According to Hesiod\'s Theogony, who is named as Prometheus\'s father?',
      ['Iapetus', 'Cronus', 'Oceanus', 'Hyperion'],
      0,
      'Hesiod\'s Theogony (line 510) identifies Iapetus, one of the twelve Titan children of Uranus and Gaia, as the father of Prometheus, Epimetheus, Atlas, and Menoetius.',
    ],
    [
      'In the Odyssey, on which island does Circe transform Odysseus\'s men into swine?',
      ['Aeaea', 'Ogygia', 'Scheria', 'Thrinacia'],
      0,
      'Circe\'s island in Homer\'s Odyssey (Book 10) is Aeaea, a wooded island where she lives in a stone hall with tame wolves and lions, and where she turns Odysseus\'s scouting party into pigs with a drugged potion before Odysseus resists her magic with Hermes\'s help.',
    ],
    [
      'In the standard mythographic account of the Augean stables labor, which two rivers does Heracles divert to flush them clean?',
      ['The Alpheus and the Peneus', 'The Achelous and the Scamander', 'The Ladon and the Erymanthus', 'The Styx and the Cocytus'],
      0,
      'Apollodorus\'s Bibliotheca (2.5.5) records that Heracles, tasked with cleaning decades of dung from King Augeas\'s stables in a single day, broke through the stable walls and diverted the courses of the Alpheus and Peneus rivers to wash the filth away, completing the labor through engineering rather',
    ],
    [
      'In Aeschylus\'s Oresteia, what do the Erinyes (Furies) become by the trilogy\'s resolution at Athens?',
      ['The Semnai, benevolent protectors honored at Athens', 'Permanent handmaidens serving Athena within her sacred temple', 'Newly appointed judges seated permanently on the Areopagus', 'Ceremonial servants attending Apollo at his Delphic shrine'],
      0,
      'At the end of Eumenides, the third play of Aeschylus\'s Oresteia, Athena persuades the vengeful Erinyes—who had hunted Orestes for matricide—to accept a transformed role as the Semnai Theai ("Venerable Ones"), protective deities given a shrine beneath the Areopagus and honored with civic cult in',
    ],
    [
      'According to Hesiod\'s Theogony, who is the mother of the nine Muses?',
      ['Mnemosyne', 'Themis', 'Eurynome', 'Leto'],
      0,
      'Hesiod\'s Theogony (lines 53-62) makes Mnemosyne, the Titaness personifying Memory, the mother of the nine Muses by Zeus, who lay with her for nine consecutive nights at Pieria; the Muses were then born to preside over song, poetry, and the memory of great deeds that oral poets needed to preserve.',
    ],
    [
      'Which of Heracles\'s Twelve Labors required him to capture a creature sacred to Artemis without shedding a drop of its blood?',
      ['The Ceryneian Hind', 'The Erymanthian Boar', 'The Nemean Lion', 'The Stymphalian Birds'],
      0,
      'The third labor sent Heracles after the Ceryneian Hind, a deer with golden antlers and bronze hooves sacred to Artemis, which he was ordered to bring back alive and unharmed—an unusually delicate constraint compared to the labors demanding he simply kill or subdue a monster.',
    ],
    [
      'In Apollonius Rhodius\'s Argonautica, what is the name of the giant bronze automaton that guards Crete and is defeated through Medea\'s magic?',
      ['Talos', 'Otus', 'Ephialtes', 'Geryon'],
      0,
      'Talos is the bronze giant, sometimes described as the last of the Bronze Age race or a creation of Hephaestus, who circles Crete three times daily hurling boulders at approaching ships to protect the island; in Apollonius\'s Argonautica, Medea defeats him not with force but by bewitching him with',
    ],
    [
      'According to Apollodorus\'s Bibliotheca, what is Sthenno\'s relation to Medusa?',
      ['Her sister, a Gorgon born to Phorcys and Ceto', 'Her mother, a sea deity married to Phorcys', 'Her daughter, born after Perseus\'s quest', 'Her aunt, another daughter of Ceto and Phorcys'],
      0,
      'The three Gorgons—Stheno (or Sthenno), Euryale, and Medusa—are sisters, daughters of the primordial sea deities Phorcys and Ceto, according to Hesiod\'s Theogony and later systematized in Apollodorus\'s Bibliotheca; of the three, only Medusa is mortal, which is why Perseus can kill her while her',
    ],
    [
      'In Iliad Book 19, which of Achilles\'s horses is briefly granted human speech by Hera to foretell his coming death?',
      ['Xanthus', 'Balius', 'Podargos', 'Aithon'],
      0,
      'In one of the Iliad\'s strangest passages, Hera gives voice to Xanthus, one of Achilles\'s immortal horses (a gift from Poseidon to Peleus), who speaks aloud to warn Achilles that although the horses will bring him safely from battle this day, his own death is near and not far off, at the hands of a',
    ],
    [
      'According to Pseudo-Apollodorus\'s Bibliotheca, Apollo grants Cassandra prophetic power in hope of winning her love. What does she then do that causes him to curse her prophecies with permanent disbelief rather than simply revoking the gift?',
      ['She accepts the gift but then refuses to fulfill her promised affection', 'She reveals the prophecy of Troy\'s fall to the Achaeans in secret', 'She dedicates herself permanently to Apollo\'s own priesthood at Delphi', 'She uses the gift to expose Apollo\'s other secret love affairs'],
      0,
      'Pseudo-Apollodorus\'s Bibliotheca (3.12.5) explains that Apollo, smitten with Cassandra, granted her the gift of prophecy in hopes of winning her affection; she accepted the power but then refused to give herself to him as promised, and in retaliation he cursed her so that no one would ever believe',
    ],
    [
      'According to Hesiod\'s Theogony, who are the four sons of the Titan Iapetus?',
      ['Atlas, Menoetius, Prometheus, and Epimetheus', 'Atlas, Prometheus, Epimetheus, and Coeus', 'Atlas, Hyperion, Prometheus, and Crius', 'Atlas, Epimetheus, Menoetius, and Perses'],
      0,
      'Hesiod\'s Theogony (lines 507-511) lists Atlas, Menoetius, Prometheus, and Epimetheus as the sons of Iapetus by the Oceanid Clymene, grouping them together right before recounting how each meets a distinct fate tied to the Titanomachy and its aftermath: Atlas condemned to hold up the sky, Menoetius',
    ],
    [
      'In the myth of the Seven Against Thebes, which side does the seer Amphiaraus support, despite foreseeing that he himself will die in the campaign?',
      ['The attacking army led by Polynices and Adrastus', 'The defending Theban side under Eteocles', 'Neither; he refuses to take part in the war at all', 'Creon\'s separate faction within Thebes'],
      0,
      'Amphiaraus, a renowned seer married to Adrastus\'s sister Eriphyle, foresaw that joining the expedition to install Polynices on the Theban throne would cost him his life, and tried to avoid the war entirely—but he had earlier sworn an oath to abide by Eriphyle\'s judgment in disputes with Adrastus,',
    ],
    [
      'In the Greek tradition preserved by Eratosthenes\' Catasterismi, who transforms the nymph Callisto into a bear?',
      ['Artemis', 'Hera', 'Zeus', 'Apollo'],
      0,
      'In the Greek astral-myth tradition recorded by Eratosthenes, Callisto was a companion of Artemis sworn to virginity who was seduced by Zeus; when her pregnancy was discovered, Artemis, furious at the broken vow, transformed her into a bear, and she was nearly killed by hunters (in some tellings',
    ],
    [
      'Who is the helmsman of the Argo renowned as the most skilled navigator among the Argonauts, prior to his death partway through the voyage?',
      ['Tiphys', 'Ancaeus', 'Peleus', 'Idmon'],
      0,
      'Tiphys, son of Hagnias, was chosen to steer the Argo because of his unmatched skill in reading stars, winds, and currents, a skill Athena herself is said to have helped him develop; he successfully navigates the ship through the perilous Symplegades (Clashing Rocks) before dying of illness partway',
    ],
  ],
  phd: [
    [
      'In the Homeric Hymn to Demeter, what is the name of the well at Eleusis where the disguised, grieving Demeter first sits down to rest?',
      ['The Parthenion Well', 'The Callichoron Well', 'The Castalian Spring', 'The Well of Persephone'],
      0,
      'The Homeric Hymn to Demeter describes the goddess, disguised as an old woman after Persephone\'s abduction, sitting down by the roadside at a well called the Parthenion ("Maiden\'s") Well near Eleusis, where the daughters of King Celeus find her and bring her into their household as a nurse for the',
    ],
    [
      'According to Pausanias, which Boeotian town\'s spring is identified as the site of Narcissus\'s death, in a skeptical local variant of the myth?',
      ['Thespiae', 'Delphi', 'Corinth', 'Thebes'],
      0,
      'Pausanias (9.31.7-9), touring Boeotia, records a local tradition at Thespiae linking a nearby spring to Narcissus\'s death, and even reports the more rationalizing local version in which Narcissus dies of grief after seeing not his own reflection but the face of a deceased twin sister he resembled,',
    ],
    [
      'In Apollonius Rhodius\'s Argonautica, who takes over as helmsman of the Argo after Tiphys dies partway through the voyage?',
      ['Ancaeus', 'Nauplius', 'Peleus', 'Euphemus'],
      0,
      'After Tiphys dies of sudden illness among the Mariandyni, the Argonauts are thrown into despair and briefly consider abandoning the voyage, until Hera\'s intervention through Ancaeus and Erginus revives their resolve; Ancaeus, son of Poseidon known for his seafaring skill, ultimately takes the helm',
    ],
    [
      'In Aeschylus\'s Prometheus Bound, two enforcers of Zeus named Kratos and Bia accompany Hephaestus to bind Prometheus to the rock. Which of the two actually speaks in the text, while the other remains silent throughout?',
      ['Kratos', 'Bia', 'Hephaestus', 'Hermes'],
      0,
      'In the opening scene of Prometheus Bound, Hephaestus is compelled by Zeus\'s servants Kratos (Strength) and Bia (Violence) to chain Prometheus to a crag in the Caucasus; Kratos delivers harsh, taunting lines urging Hephaestus to work faster and stop pitying the Titan, while Bia is present as a',
    ],
    [
      'In Euripides\'s Bacchae, after Agave returns to Thebes triumphantly displaying what she believes is a lion\'s head, who is the one to gently guide her back to sane recognition that it is in fact her son Pentheus\'s head?',
      ['Cadmus, her father', 'Tiresias, the blind seer', 'Autonoe, her sister', 'Dionysus himself, revealing his true form'],
      0,
      'In the final scenes of Euripides\'s Bacchae, Agave, still in Dionysiac ecstasy, returns to the palace boasting of the lion she has hunted with her bare hands; it is her own father Cadmus, arriving to bury Pentheus\'s scattered remains, who gently and painstakingly walks her back to clarity, forcing',
    ],
    [
      'Which surviving Greek mythographic work is the primary source preserving the detailed genealogy connecting Danaus\'s fifty daughters to the founding of the Argive royal line?',
      ['Pseudo-Apollodorus\'s Bibliotheca', 'Pausanias\'s Description of Greece', 'Diodorus Siculus\'s Bibliotheca Historica', 'Antoninus Liberalis\'s Metamorphoses'],
      0,
      'The Bibliotheca attributed to "Apollodorus" (almost certainly not the second-century BCE grammarian of that name, hence "Pseudo-Apollodorus") is the single most systematic surviving compilation of Greek genealogical myth, and it is the key source detailing how Danaus\'s fifty daughters, after',
    ],
    [
      'In Pindar\'s Olympian 1, which version of the Pelops myth does Pindar explicitly reject as slanderous gossip spread by envious neighbors?',
      ['That Tantalus served his son Pelops\'s flesh to the gods at a banquet', 'That Pelops cheated Oenomaus in the chariot race using a bribed charioteer', 'That Poseidon abducted Pelops out of erotic desire', 'That Tantalus stole ambrosia and nectar to share with mortals'],
      0,
      'In Olympian 1, composed to honor Hieron of Syracuse\'s chariot victory, Pindar retells the Pelops myth but pointedly rejects the gruesome version in which Tantalus serves his own son\'s flesh to the gods at a feast, declaring that he will not call any of the blessed gods a cannibal and blaming such',
    ],
    [
      'In Sophocles\'s Oedipus at Colonus, whose sacred grove offers Oedipus final sanctuary shortly before his mysterious death?',
      ['The Eumenides (Erinyes), at Colonus', 'Demeter and Persephone, at Eleusis', 'Athena, on the Acropolis', 'Poseidon, at Sounion'],
      0,
      'Oedipus at Colonus opens with the blind, exiled Oedipus arriving at a grove sacred to the Eumenides (the transformed Erinyes, also called the "kindly ones") just outside Athens, a site he recognizes from prophecy as the place fated to receive him at the end of his wandering; the local chorus is',
    ],
    [
      'According to the tradition preserved in Hesiod\'s Theogony, who is the father of the three elder Cyclopes—Brontes, Steropes, and Arges?',
      ['Uranus', 'Poseidon', 'Cronus', 'Oceanus'],
      0,
      'Hesiod\'s Theogony (lines 139-146) makes the three elder Cyclopes—Brontes (Thunder), Steropes (Lightning), and Arges (Bright)—sons of Uranus (Sky) and Gaia (Earth), born alongside the Titans and the hundred-handed Hecatoncheires as part of the same generation of primordial offspring; these Cyclopes',
    ],
    [
      'In Hesiod\'s Works and Days, what specific error does Epimetheus commit that seals mankind\'s fate, distinct from Prometheus\'s earlier theft of fire?',
      ['He accepts Pandora as his wife against Prometheus\'s warning', 'He opens Pandora\'s sealed jar himself out of overwhelming curiosity', 'He releases the destructive winds prematurely from their sealed container', 'He secretly steals a second portion of divine fire without permission'],
      0,
      'In Hesiod\'s Works and Days, after Prometheus steals fire for humanity, Zeus retaliates by having Pandora created and sent as a deceptive gift to mankind; Prometheus explicitly warns his brother Epimetheus not to accept her, but Epimetheus—true to his name, meaning "afterthought" or',
    ],
    [
      'Which epithet, reflected in the Odyssey Book 24 scene where Hermes leads the slain suitors\' souls to Hades, marks his specific role as guide of the dead?',
      ['Psychopompos', 'Argeiphontes', 'Diaktoros', 'Cyllenian'],
      0,
      'In Odyssey Book 24, Hermes uses his golden wand to summon and lead the souls of the suitors killed by Odysseus down to the underworld, gently guiding them like a flock of bats through the realms of the dead—a scene that later Greek tradition crystallized into the title Psychopompos, "guide of',
    ],
    [
      'According to Hesiod\'s Theogony, which four named monsters does Echidna bear (with Typhon or Orthus, depending on the passage)?',
      ['Orthus, Cerberus, the Hydra, and the Chimera', 'The Sphinx, the Nemean Lion, and Ladon', 'The Gorgons and the Graeae', 'The Harpies and the Sirens'],
      0,
      'Hesiod\'s Theogony (lines 306-325) lists Echidna, a half-woman, half-serpent monster, as the mother of Orthus (the two-headed hound later killed by Heracles), Cerberus (the multi-headed guardian of the underworld), the Lernaean Hydra, and the Chimera, all fathered in the text\'s telling by Typhon,',
    ],
    [
      'Which seer accompanying the Seven Against Thebes is swallowed alive into the earth during the army\'s retreat, rather than dying an ordinary death?',
      ['Amphiaraus', 'Tiresias', 'Melampus', 'Polyidus'],
      0,
      'Amphiaraus, forced by his oath to his wife Eriphyle into joining the doomed expedition against Thebes despite foreseeing his own death, is swallowed alive into the earth along with his chariot as he flees the battlefield, an intervention traditionally attributed to Zeus sparing him the indignity',
    ],
    [
      'In Euripides\'s Hippolytus, which goddess opens the play with a prologue declaring her intention to punish Hippolytus for scorning her?',
      ['Aphrodite', 'Artemis', 'Hera', 'Athena'],
      0,
      'Euripides\'s Hippolytus opens with Aphrodite herself delivering the prologue, announcing her anger at the young prince Hippolytus for rejecting sexuality and love entirely in favor of exclusive devotion to the virgin huntress Artemis, and revealing her plan to punish this slight by making his',
    ],
    [
      'According to Apollodorus, why does Eurystheus refuse to count Heracles\'s slaying of the Lernaean Hydra among the ten original labors, requiring two more to be added?',
      ['Because Heracles received help from his nephew Iolaus', 'Because Heracles used poisoned arrows, which Eurystheus ruled as cheating', 'Because the Hydra was not considered native to the Argolid region', 'Because Heracles killed it outside the officially appointed year'],
      0,
      'Apollodorus\'s Bibliotheca (2.5.2) records that after Heracles struggled against the Hydra\'s regenerating heads—every time he severed one, two grew back—he called on his nephew Iolaus, who cauterized each stump with a burning brand to prevent regrowth, allowing Heracles to finally finish the',
    ],
  ],
  professor: [
    [
      'In the Homeric Hymn to Apollo, which nymph presiding over a spring near Haliartus deceives the god into abandoning his plan to found his oracle at her site?',
      ['Telphousa', 'Castalia', 'Cassotis', 'Delphusa'],
      0,
      'In the Homeric Hymn to Apollo, the god initially scouts a spring called Telphousa (near Haliartus in Boeotia) as a potential site for his oracle, but the resident nymph of that same spring, unwilling to share her waters\' fame, persuades him that the noisy horses and mules watering nearby would be',
    ],
    [
      'According to Pausanias, which Arcadian mountain hosted a local cult claiming to be Zeus\'s actual birthplace, rivaling the Cretan Ida/Dikte tradition?',
      ['Mount Lykaion', 'Mount Kyllene', 'Mount Erymanthos', 'Mount Parnon'],
      0,
      'Pausanias, in his Description of Greece (8.38), records that the Arcadians maintained their own tradition centered on Mount Lykaion claiming Zeus was actually born and raised there rather than on Crete, complete with a sacred, restricted precinct at the summit that no shadow was said to fall',
    ],
    [
      'In the tradition behind the Argonautica, what are the names of the two sons Phineus blinds after his second wife falsely accuses them, sons he had by his first wife Cleopatra (daughter of Boreas)?',
      ['Plexippus and Pandion', 'Perdix and Polydectes', 'Idas and Lynceus', 'Calais and Zetes'],
      0,
      'Phineus of Salmydessus, later punished by the Harpies and rescued by the Argonauts, had earlier blinded his own two sons by his first wife Cleopatra—named Plexippus and Pandion in the tradition preserved through scholia to Apollonius\'s Argonautica and related sources—after his second wife falsely',
    ],
    [
      'In Nonnus\'s Dionysiaca, what is the name of the Indian king against whom Dionysus wages his lengthy mythic war?',
      ['Deriades', 'Lycurgus', 'Pentheus', 'Orontes'],
      0,
      'Nonnus of Panopolis\'s fifth-century CE epic Dionysiaca, the longest surviving poem from antiquity, devotes a substantial portion of its 48 books to Dionysus\'s campaign against Deriades, king of the Indians, who refuses to accept the god\'s rites and wages a protracted war against him before',
    ],
    [
      'In Quintus Smyrnaeus\'s Posthomerica, who kills the Amazon queen Penthesilea in single combat?',
      ['Achilles', 'Ajax', 'Diomedes', 'Neoptolemus'],
      0,
      'Quintus Smyrnaeus\'s Posthomerica, a Greek epic composed probably in the third century CE that bridges the narrative gap between the Iliad and the Odyssey, recounts how the Amazon queen Penthesilea arrives to aid Troy after Hector\'s death and fights fiercely before Achilles kills her in single',
    ],
    [
      'In the older tradition preserved in Homer\'s Odyssey (19.518-523), which woman accidentally kills her own son Itylus and is transformed into a nightingale—a myth later overshadowed in popularity by the Procne/Philomela version?',
      ['Aedon', 'Procne', 'Philomela', 'Niobe'],
      0,
      'The Odyssey\'s Book 19 contains a brief simile comparing Penelope\'s restless grief to the nightingale\'s song, identifying the bird as Aedon, wife of Zethus, who accidentally killed her own son Itylus (intending to kill a nephew out of jealousy over her sister-in-law\'s more numerous children) and',
    ],
    [
      'In Pindar\'s Pythian 4, which Argonaut receives a clod of Libyan earth from the disguised sea-god Triton and is told his descendants will one day rule Libya?',
      ['Euphemus', 'Periclymenus', 'Ancaeus', 'Idmon'],
      0,
      'Pindar\'s Pythian 4, composed for Arcesilas of Cyrene, retells how the Argonaut Euphemus, son of Poseidon, receives a clod of earth from a local divinity (Triton in disguise as a Libyan man) while the Argo passes near Lake Tritonis in North Africa, and is prophesied that his descendants will one',
    ],
    [
      'Aeschylus\'s Oresteia trilogy (Agamemnon, Libation Bearers, Eumenides) was originally staged alongside a satyr play. What was that satyr play\'s title?',
      ['Proteus', 'Sisyphus', 'Prometheus Pyrkaeus', 'Amymone'],
      0,
      'Athenian tragic trilogies at the City Dionysia were traditionally followed by a lighter satyr play performed by the same author on the same day, and for Aeschylus\'s Oresteia (produced in 458 BCE) that accompanying satyr play was titled Proteus, now almost entirely lost apart from a few scant',
    ],
    [
      'In Orphic cosmogonic tradition, who is Phanes, and from what does this primordial deity emerge to begin creation?',
      ['A hermaphroditic deity of light who emerges from the cosmic World Egg', 'A chthonic serpent-god who rises from the depths of Tartarus', 'The first Titan, born directly from Gaia\'s womb without a partner', 'A solar deity who rises from the stream of Oceanus each dawn'],
      0,
      'In Orphic cosmogonic literature—a distinct strand of Greek religious-poetic tradition running alongside, and sometimes in tension with, the more familiar Hesiodic cosmogony—the primordial deity Phanes (also called Protogonos, "firstborn") emerges from a cosmic egg laid by Chronos (Time) or Nyx',
    ],
    [
      'According to Hesiod\'s Theogony, which minor Titan, paired with the dawn-goddess Eos, fathers the winds Zephyrus, Boreas, and Notus?',
      ['Astraeus', 'Crius', 'Pallas', 'Perses'],
      0,
      'Hesiod\'s Theogony (lines 378-382) names Astraeus, a relatively obscure Titan, as the father—by Eos, goddess of the dawn—of the three named winds Zephyrus (west wind), Boreas (north wind), and Notus (south wind), as well as the morning star and other stars, tying meteorological and astral phenomena',
    ],
    [
      'According to Pausanias (2.21.5), in which city\'s agora was a mound said to contain Medusa\'s severed head buried beneath it?',
      ['Argos', 'Mycenae', 'Tiryns', 'Corinth'],
      0,
      'Pausanias, describing the sights of Argos in his Description of Greece, records a local tradition that a mound within the city\'s agora marked the burial place of Medusa\'s severed Gorgon head, which Perseus was said to have brought back through the Argolid region on his return from his quest,',
    ],
    [
      'In Homer\'s Iliad, Hector\'s dying prophecy (Book 22) names what specific combination as the actual agents of Achilles\'s coming death—distinct from the "vulnerable heel" tradition popularized centuries later?',
      ['Paris and Apollo, striking him at the Scaean Gates', 'Hector himself, in a rematch fought by his ghost', 'Memnon, wielding a poisoned Ethiopian blade', 'A rock hurled by defenders from Troy\'s walls'],
      0,
      'As Hector dies in Iliad Book 22, he curses Achilles with a specific prophecy: that Paris and Apollo will kill him at the Scaean Gates of Troy, a detail consistent with the broader epic tradition (elaborated further in the lost Aethiopis) in which Apollo guides Paris\'s arrow to strike Achilles',
    ],
    [
      'According to Apollodorus\'s account of the Calydonian Boar Hunt aftermath, Meleager\'s life is bound to what object, which his own mother Althaea ultimately burns, killing him?',
      ['A firebrand kept unburned since his infancy', 'A golden thread unraveling from the Fates\' loom', 'A sacred oak tree cursed by Artemis', 'A countdown of days revealed directly by the Moirai'],
      0,
      'According to Apollodorus\'s Bibliotheca, the Fates appeared at Meleager\'s birth and prophesied that he would live only as long as a particular firebrand, then burning on the hearth, remained unconsumed; his mother Althaea snatched it from the fire and hid it away to protect her son\'s life.',
    ],
    [
      'Hesiod\'s Theogony (lines 411-452) gives Hecate an unusually elevated role compared to her more marginal position in later classical Athenian religion. What specifically does Hesiod say Zeus grants her?',
      ['Honored power over earth, sea, and sky, granted by Zeus above her Titan peers', 'A subordinate role as Persephone\'s personal attendant confined entirely to the underworld realm', 'Status as a defeated rival goddess forcibly subdued during the Titanomachy', 'Recognition only as a minor nymph attending Artemis during her nightly hunts'],
      0,
      'Hesiod\'s Theogony devotes an unusually extended passage (lines 411-452) to Hecate, daughter of the Titans Perses and Asteria, describing how Zeus honored her earlier all other deities of her generation, granting her a share of power across earth, sea, and starry heaven, and stating that mortals',
    ],
    [
      'In Euripides\'s Helen, what alternate mythic tradition, following Stesichorus\'s Palinode, does the play dramatize regarding Helen\'s whereabouts during the Trojan War?',
      ['That the real Helen was spirited to Egypt by Hermes while a phantom double (eidolon) went to Troy', 'That Helen remained willingly in Sparta throughout the war while Paris was fooled by an illusion', 'That Helen died at Troy early in the war and was replaced by an illusion for its remainder', 'That Helen fled secretly to Crete and lived in hiding with Idomeneus until the war ended'],
      0,
      'Euripides\'s Helen dramatizes a striking alternate tradition, traceable back to the lyric poet Stesichorus\'s Palinode (a poem in which he supposedly recanted an earlier, more conventional account of Helen\'s guilt), in which the real Helen never went to Troy at all: Hermes spirited her away to Egypt',
    ],

  ],
  bscba: [
    [
      'Who is the king of the gods in Greek mythology?',
      ['Zeus', 'Poseidon', 'Hades', 'Kronos'],
      0,
      'Zeus rules Olympus as king of the gods and sky, wielding thunderbolts as his primary weapon. He is the father of many gods and heroes, including Athena, Apollo, and Heracles, and his authority over gods and mortals is rarely questioned successfully.',
    ],
    [
      'In Homer\'s Iliad, which Trojan prince kills the Greek hero Patroclus?',
      ['Hector', 'Achilles', 'Ajax', 'Diomedes'],
      0,
      'Hector, the greatest Trojan warrior and son of King Priam, kills Patroclus in battle, which triggers Achilles\' return to combat and shapes the remaining course of the Iliad.',
    ],
    [
      'Which goddess is born from Zeus\'s head fully formed and armored?',
      ['Athena', 'Aphrodite', 'Artemis', 'Hera'],
      0,
      'Athena emerges fully grown from Zeus\'s forehead, already clad in armor and ready for battle. She becomes the goddess of wisdom, warfare, and craft, and serves as a key ally to several Greek heroes.',
    ],
    [
      'What is the name of the monster with a human head and lion\'s body that Oedipus solves a riddle to pass?',
      ['The Sphinx', 'The Chimera', 'The Manticore', 'The Griffin'],
      0,
      'The Sphinx guards the path to Thebes and kills all who cannot answer her riddle: "What walks on four legs in the morning, two at midday, and three in the evening?" Oedipus correctly answers that it is man, and the Sphinx destroys herself.',
    ],
    [
      'Which son of Poseidon is famous for being the strongest man alive and required to complete Twelve Labors?',
      ['Heracles', 'Theseus', 'Perseus', 'Bellerophon'],
      0,
      'Heracles, half-mortal son of Zeus and the woman Alcmene, is renowned for his immense strength. He is forced by his cousin Eurystheus to complete twelve seemingly impossible tasks as punishment for a crime committed in madness.',
    ],
    [
      'In the story of Persephone, which god abducts her and takes her to rule as queen of the underworld?',
      ['Hades', 'Ares', 'Hermes', 'Apollo'],
      0,
      'Hades, god of the underworld, abducts Persephone while she gathers flowers and takes her to his dark kingdom. Her mother Demeter grieves, causing crops to wither, until Zeus negotiates a compromise: Persephone spends part of each year with each god.',
    ],
    [
      'Which Gorgon can be killed because she is the only mortal one of her three sisters?',
      ['Medusa', 'Stheno', 'Euryale', 'Ladon'],
      0,
      'Medusa is unique among the three Gorgons because she alone is mortal, making it possible for the hero Perseus to slay her by severing her head while looking at her reflection in his shield.',
    ],
    [
      'What does Prometheus steal from the gods and give to mankind, for which he is punished with eternal torment?',
      ['Fire', 'Ambrosia', 'Immortality', 'Prophecy'],
      0,
      'Prometheus steals divine fire and gives it to humans, enabling them to cook, work metal, and progress. As punishment, Zeus has him bound to a rock in the Caucasus where an eagle eats his liver daily for eternity.',
    ],
    [
      'Who is the Trojan prince and son of Aphrodite who survives the fall of Troy and founds Rome?',
      ['Aeneas', 'Paris', 'Hector', 'Priam'],
      0,
      'Aeneas, born to Aphrodite and the mortal Anchises, escapes Troy\'s destruction and travels to Italy, where his descendants eventually found Rome. His journey forms the subject of Virgil\'s epic, the Aeneid.',
    ],
    [
      'In the myth of Jason and the Argonauts, what is the object they seek?',
      ['The Golden Fleece', 'The Crown of Corinth', 'The Fleece of Hermes', 'The Treasure of Minos'],
      0,
      'Jason and his crew of heroes sail on the ship Argo to the distant land of Colchis to retrieve the Golden Fleece, a task that requires both courage and cunning, particularly with the help of the sorceress Medea.',
    ],
    [
      'Which goddess of love and beauty is born from the sea-foam and represents desire and beauty?',
      ['Aphrodite', 'Hera', 'Artemis', 'Athena'],
      0,
      'Aphrodite, often called the goddess of love, beauty, and desire, arose from the sea-foam according to Hesiod\'s account. She is typically depicted as among the most beautiful of the Olympian deities.',
    ],
    [
      'What is the curse that prevents Cassandra\'s prophecies from ever being believed, even when they prove correct?',
      ['No one believes her predictions', 'She speaks in riddles only', 'Her voice cannot be heard', 'She must speak in reverse'],
      0,
      'After Apollo grants Cassandra the gift of prophecy, she refuses his romantic advances, so he curses her: her prophecies are always accurate but never believed. She accurately predicts Troy\'s fall and her own death, but no one listens.',
    ],
    [
      'Which three-headed dog guards the entrance to the underworld?',
      ['Cerberus', 'Orthus', 'Garmr', 'Fenrir'],
      0,
      'Cerberus, born to the monstrous couple Typhon and Echidna, guards the gates of Hades\' underworld kingdom. Capturing or pacifying him is one of Heracles\' Twelve Labors.',
    ],
    [
      'In Greek mythology, who is the messenger god of commerce and travelers, known for his winged feet?',
      ['Hermes', 'Ares', 'Apollo', 'Poseidon'],
      0,
      'Hermes serves as the messenger of the gods and is typically depicted wearing winged sandals (talaria) and carrying a caduceus. He is also associated with commerce, thieves, and cunning, and guides souls to the underworld.',
    ],
    [
      'What does Pandora open despite being warned not to, releasing troubles into the world?',
      ['A sealed jar', 'A locked box', 'A forbidden door', 'A hidden chest'],
      0,
      'Pandora, the first woman created by the gods, is given a sealed jar and warned never to open it. Her curiosity overwhelms her, and when she opens it, all the world\'s evils, sorrows, and hardships escape, leaving only hope trapped inside.',
    ],
  ],
};

export const NORSE_MYTH: CategoryContent = {
  msc: [
    [
      'In Norse cosmology, which wolf is prophesied to catch and finally swallow the sun at Ragnarök?',
      ['Sköll', 'Hati', 'Fenrir', 'Garmr'],
      0,
      'Sköll ("Treachery") chases the sun-goddess Sól\'s chariot across the sky each day and is fated to catch and devour her at Ragnarök, while his brother Hati pursues and swallows the moon.',
    ],
    [
      'What is the name of the spear that always finds its mark, wielded by Odin and forged by dwarves?',
      ['Gungnir', 'Laevateinn', 'Gram', 'Tyrfing'],
      0,
      'Gungnir is Odin\'s personal weapon, made by the sons of Ívaldi in the dwarven treasure contest of Skáldskaparmál, and it never misses its target once thrown.',
    ],
    [
      'What is the name of the ship, said to be built from the untrimmed nails of the dead, that sails at Ragnarök?',
      ['Naglfar', 'Skíðblaðnir', 'Hringhorni', 'Ellidi'],
      0,
      'Naglfar is described in Gylfaginning as built entirely from the fingernails and toenails of dead men, and Snorri adds the folk warning that people should have their nails trimmed before death to avoid hastening the ship\'s completion.',
    ],
    [
      'Who is Odin\'s wife, the goddess associated with foreknowledge and the mother of Baldr?',
      ['Frigg', 'Freyja', 'Sif', 'Idunn'],
      0,
      'Frigg is the chief goddess of the Aesir, married to Odin, and the Prose Edda credits her with knowing the fates of all beings even though she rarely voices them, which is exactly why she cannot prevent Baldr\'s death despite sensing danger to him.',
    ],
    [
      'Which of the nine realms is described as the homeland of the giants (jötnar)?',
      ['Jötunheimr', 'Svartálfaheimr', 'Niflheimr', 'Múspellsheimr'],
      0,
      'Jötunheimr, "giant-world," is the realm of the jötnar, the frost- and mountain-giants who are the Aesir\'s recurring rivals and occasional in-laws. In Snorri\'s geography it lies east across rivers and wilderness, a frontier the gods must cross to visit, fight, or court giants.',
    ],
    [
      'What is the name of the well beneath one of Yggdrasil\'s roots, guarded by Mímir and associated with wisdom?',
      ['Mímisbrunnr', 'Urðarbrunnr', 'Hvergelmir', 'Bergelmir'],
      0,
      'Mímisbrunnr, "Mímir\'s well," lies beneath one of Yggdrasil\'s three roots and is the source of the wisdom Mímir drinks from daily. Odin sacrifices one of his eyes for a single drink from it, an act of self-mutilation for knowledge that parallels his later hanging on the tree for the runes.',
    ],
    [
      'According to Skáldskaparmál, whose golden hair did the dwarven sons of Ívaldi forge after Loki cut it off as a prank?',
      ['Sif', 'Freyja', 'Idunn', 'Gerðr'],
      0,
      'Loki, out of pure mischief, shears off the golden hair of Sif, Thor\'s wife, and to escape Thor\'s wrath bargains with dwarves to forge her a head of hair from real gold that will grow like natural hair once set in place.',
    ],
    [
      'What are the names of the two goats that pull Thor\'s chariot across the sky?',
      ['Tanngnjóstr and Tanngrisnir', 'Gulltoppr and Glaðr', 'Hugin and Munin', 'Geri and Freki'],
      0,
      'Tanngnjóstr ("teeth-grinder") and Tanngrisnir ("teeth-barer") draw Thor\'s chariot, and Snorri notes that Thor can slaughter and eat them at night and have them restored whole the next morning, provided the bones aren\'t damaged — an episode dramatized when a farmer\'s son cracks a bone for the',
    ],
    [
      'In the myth of the mead of poetry, whose blood did the dwarves Fjalar and Galar drain and mix with honey to create the mead that grants poetic inspiration?',
      ['Kvasir\'s', 'Mímir\'s', 'Ymir\'s', 'Baldr\'s'],
      0,
      'Kvasir is a being created from the spit the Aesir and Vanir mixed to seal their truce after the Aesir-Vanir war, made so wise that no question can stump him; the dwarves Fjalar and Galar murder him and drain his blood into vessels, mixing it with honey into a mead that turns anyone who drinks it',
    ],
    [
      'Which goddess owns a cloak of falcon feathers that lets the wearer transform into a bird and fly?',
      ['Freyja', 'Frigg', 'Idunn', 'Sif'],
      0,
      'Freyja possesses a feathered cloak that grants flight in falcon form, and she lends it out at key moments — Loki borrows it to fly into Jötunheimr searching for Thor\'s stolen hammer in Þrymskviða, and again to rescue Idunn after her abduction by the giant Þjazi.',
    ],
    [
      'According to Gylfaginning, which eight-legged horse — fathered by the stallion Svaðilfari and ridden by Odin down into Hel to learn the meaning of Baldr\'s ominous dreams — is famed as the swiftest of all mounts?',
      ['Sleipnir', 'Grani', 'Gulltoppr', 'Falhófnir'],
      0,
      'Sleipnir is Odin\'s gray horse, born when Loki (in mare form) drew off the giant builder\'s stallion Svaðilfari during the wall-raising of Asgard, and Snorri explicitly credits his eight legs with a swiftness no other horse can match.',
    ],
    [
      'In the tale explaining Sleipnir\'s birth, who took the form of a mare and became the horse\'s mother?',
      ['Loki', 'Freyja', 'Angrboða', 'Sigyn'],
      0,
      'To stop a giant builder from finishing Asgard\'s walls on time and claiming Freyja, the sun, and the moon as payment, Loki shapeshifts into a mare to distract the builder\'s stallion Svaðilfari, luring it from its work; the union produces Sleipnir, whom Loki later gives to Odin.',
    ],
    [
      'Which figure, overcome by grief, was placed on Baldr\'s funeral pyre alongside him?',
      ['Nanna', 'Frigg', 'Sif', 'Gefjun'],
      0,
      'Nanna, Baldr\'s wife, dies of a broken heart at the sight of her husband\'s body and is laid on the pyre with him aboard his ship Hringhorni, which the giantess Hyrrokkin pushes out to sea before it is set alight.',
    ],
    [
      'Which primordial giant was slain by Odin, Vili, and Vé, his body then used to build the world — earth from his flesh, sea from his blood, sky from his skull?',
      ['Ymir', 'Bergelmir', 'Thrúðgelmir', 'Búri'],
      0,
      'Ymir is the first being, formed when the melting frost of Niflheim met the heat of Muspelheim in the void of Ginnungagap, and his death at the hands of Odin and his brothers supplies the raw material for the physical world, a creation-by-dismemberment pattern shared with several Indo-European',
    ],
    [
      'What did Freyr give up to Skírnir in exchange for his help winning the giantess Gerðr as a bride?',
      ['his sword', 'his boar Gullinbursti', 'his ship Skíðblaðnir', 'his golden ring'],
      0,
      'Freyr falls lovesick after glimpsing the giantess Gerðr from Odin\'s high seat and sends his servant Skírnir to woo her on his behalf, paying for the errand with his self-swinging sword, one of his great treasures.',
    ],
  ],
  phd: [
    [
      'Which poem of the Poetic Edda contains the extended catalogue of dwarf names known as the Dvergatal?',
      ['Völuspá', 'Hávamál', 'Grímnismál', 'Vafþrúðnismál'],
      0,
      'Völuspá, the visionary account of the world\'s creation and destruction spoken by a völva to Odin, includes a lengthy passage listing dozens of dwarf names, generally treated by scholars as an inserted catalogue rather than integral narrative.',
    ],
    [
      'Þrymskviða, recounting the giant Þrymr\'s theft of Thor\'s hammer, survives primarily in which manuscript?',
      ['Codex Regius', 'Flateyjarbók', 'Hauksbók', 'AM 748 I b'],
      0,
      'Þrymskviða is preserved chiefly in the Codex Regius (GKS 2365 4to), the single most important manuscript of the Poetic Edda, compiled in Iceland around 1270 though drawing on older oral material.',
    ],
    [
      'Who is Loki\'s wife, who holds a bowl to catch the venom dripping onto him during his bound punishment?',
      ['Sigyn', 'Angrboða', 'Glut', 'Skaði'],
      0,
      'Sigyn sits beside the bound Loki holding a bowl to catch the venom a serpent drips onto his face, only leaving to empty it, at which point the venom that falls causes Loki\'s convulsions felt across the earth as earthquakes.',
    ],
    [
      'Gylfaginning names Fenrir, Jörmungandr, and Hel as Loki\'s monstrous children by which giantess?',
      ['Angrboða', 'Skaði', 'Gerðr', 'Járnsaxa'],
      0,
      'Angrboða ("the one who brings grief") is the giantess in Jötunheimr with whom Loki fathers Fenrir the wolf, Jörmungandr the world-serpent, and Hel, ruler of the underworld realm that bears her name; Gylfaginning describes Odin learning of a prophecy that the three will bring great harm to the gods',
    ],
    [
      'In Vafþrúðnismál, what final, unanswerable question does Odin ask the giant Vafþrúðnir to win the wisdom contest and reveal his own identity?',
      ['What did Odin whisper in Baldr\'s ear before he was placed on the pyre?', 'What is the name of the horse that will carry the sun after Ragnarök?', 'How many warriors will pass through each door of Valhalla?', 'What did Frigg promise the mistletoe in exchange for its oath?'],
      0,
      'Odin poses a question only he could know the answer to — what he himself whispered into his dead son Baldr\'s ear — and the giant Vafþrúðnir, unable to answer, realizes too late he has been matching wits with Odin in disguise and loses his life as the contest\'s stake.',
    ],
    [
      'According to Grímnismál, what is the name of the hawk that sits between the eyes of the unnamed eagle perched atop Yggdrasil?',
      ['Veðrfölnir', 'Ratatoskr', 'Hræsvelgr', 'Nidhögg'],
      0,
      'Veðrfölnir is the hawk said to sit between the eyes of the eagle at the crown of Yggdrasil, part of an elaborate vertical ecosystem the poem describes running the length of the World Tree, from the serpent Nidhögg gnawing its roots below to this eagle-and-hawk pairing at its top.',
    ],
    [
      'In Gylfaginning, which personified being defeats Thor in a wrestling match at the hall of Útgarða-Loki?',
      ['Elli, old age', 'Skaði, a giantess', 'Hyrrokkin, a giantess', 'Gerðr, a giantess'],
      0,
      'Elli, an old woman who is the personification of old age itself, wrestles Thor to a single knee during the trials at Útgarða-Loki\'s hall, and only afterward does the giant reveal that no one has ever withstood old age for as long as Thor managed, reframing an apparent humiliation as a genuine feat.',
    ],
    [
      'Which giantess pushes Baldr\'s ship Hringhorni into the sea with such force that it causes an earthquake?',
      ['Hyrrokkin', 'Elli', 'Angrboða', 'Gunnlöð'],
      0,
      'Hyrrokkin arrives riding a wolf with a snake for reins when the gods cannot launch Baldr\'s massive funeral ship themselves, and her single push sends it out with such violence that fire flies from the rollers and the earth shakes, according to Gylfaginning.',
    ],
    [
      'Which giantess, daughter of Suttungr, guards the mead of poetry inside the mountain Hnitbjörg and is seduced by Odin disguised as Bölverkr?',
      ['Gunnlöð', 'Skaði', 'Rindr', 'Angrboða'],
      0,
      'Gunnlöð is set to guard the mead her father Suttungr keeps hidden inside Hnitbjörg, and Odin, having bored through the mountain in serpent form and disguised himself as Bölverkr, spends three nights with her in exchange for three drinks of the mead, which he uses to drain the vessels entirely',
    ],
    [
      'Which son of Odin, born to the giantess Rindr, is fated to avenge Baldr\'s death by killing Höðr?',
      ['Váli', 'Víðarr', 'Hermóðr', 'Bragi'],
      0,
      'Váli is conceived specifically to grow at supernatural speed and kill Höðr, the blind god tricked by Loki into throwing the mistletoe dart that kills Baldr, and he carries out the killing the very night he is born according to the account preserved in Baldrs draumar and the Prose Edda.',
    ],
    [
      'Having given up his sword to win Gerðr, what weapon is Freyr said to fight with against Surt at Ragnarök?',
      ['a stag\'s antler', 'a spiked club', 'a boar-tusk spear', 'a sling'],
      0,
      'Freyr, left weaponless after trading his self-swinging sword to Skírnir, is instead said to fight Surt at Ragnarök with a stag\'s antler, and the sources agree he loses, becoming one of the gods explicitly prophesied to die in the final battle rather than survive it.',
    ],
    [
      'According to Grímnismál, what is the name of Freyja\'s hall within her field Fólkvangr, where she receives half of the slain?',
      ['Sessrúmnir', 'Fensalir', 'Bilskirnir', 'Glitnir'],
      0,
      'Sessrúmnir ("roomy-seated") is Freyja\'s hall, located in her field Fólkvangr, and Grímnismál states she chooses half of those who die in battle to come there, with Odin\'s Valhalla receiving the rest — a detail that quietly complicates the popular image of Valhalla as the sole afterlife destination',
    ],
    [
      'Which god owns the hall Glitnir, described as having a silver roof and pillars of gold, and is associated with settling disputes?',
      ['Forseti', 'Baldr', 'Víðarr', 'Bragi'],
      0,
      'Forseti, whose name is generally understood to mean something like "the presiding one," holds court in Glitnir and is said in both Grímnismál and Gylfaginning to settle all disputes brought before him, making him the closest thing in the Norse pantheon to a dedicated judicial figure.',
    ],
    [
      'According to the Prose Edda, which giant is said to steer the ship Naglfar at Ragnarök?',
      ['Hrymr', 'Surtr', 'Loki', 'Fenrir'],
      0,
      'Hrymr is named in the Prose Edda\'s account of Ragnarök as the giant who steers Naglfar, the ship built from dead men\'s nails, ferrying the forces of the frost-giants to the final battle against the Aesir.',
    ],
    [
      'Gleipnir, the ribbon-like binding that finally fetters Fenrir, was said by the dwarves to be forged from six impossible ingredients. Which of the following was genuinely one of them?',
      ['the sound of a cat\'s footfall', 'the roar of a slaughtered bull', 'the tears wept freely by a giant', 'the shadow cast by a flying raven'],
      0,
      'According to Gylfaginning, the dwarves who forge Gleipnir use six things that do not exist in nature: the sound of a cat\'s footfall, a woman\'s beard, the roots of a mountain, the sinews of a bear, the breath of a fish, and the spittle of a bird — and Snorri notes wryly that this is why, to this',
    ],
  ],
  professor: [
    [
      'What is the name of the primordial cow, formed from the melting ice, whose milk nourished the giant Ymir?',
      ['Auðumbla', 'Heiðrún', 'Eikþyrnir', 'Sæhrímnir'],
      0,
      'Auðumbla is the primeval cow described in Gylfaginning as licking salty rime-stones for nourishment, and in doing so uncovers Búri, ancestor of the Aesir, while her own milk sustains Ymir before his death.',
    ],
    [
      'According to Grímnismál, which hart stands atop Valhalla and drips liquid from its antlers down into Hvergelmir, the source of the world\'s rivers?',
      ['Eikþyrnir', 'Heiðrún', 'Dáinn', 'Duneyrr'],
      0,
      'Eikþyrnir is the hart named in Grímnismál as standing on Valhalla itself, and the liquid dripping from its antlers falls all the way down into Hvergelmir in Niflheim, from which the poem says the world\'s many named rivers originate, an image linking the loftiest point of the god\'s own hall',
    ],
    [
      'Which of the following is one of the four stags said in Grímnismál to gnaw at the shoots of Yggdrasil?',
      ['Duraþrór', 'Móðsognir', 'Nár', 'Náinn'],
      0,
      'Duraþrór is named alongside Dáinn, Dvalinn, and Duneyrr as one of four stags that feed on Yggdrasil\'s foliage according to Grímnismál\'s stanza 33, part of the poem\'s dense cataloguing of the tree\'s many inhabitants alongside the serpent Nidhögg below and the eagle earlier.',
    ],
    [
      'What is the name of the hound bound at Gnipahellir, guarding the entrance to Hel\'s realm, who breaks free at Ragnarök?',
      ['Garmr', 'Fenrir', 'Managarmr', 'Víðópnir'],
      0,
      'Garmr is described in Völuspá as howling before Gnipahellir, the cave-mouth entrance to Hel, and his breaking free of his bonds is listed among the signs that Ragnarök has begun, alongside Fenrir\'s own escape.',
    ],
    [
      'According to Völuspá, which named rooster crows to awaken the jötnar at the onset of Ragnarök?',
      ['Fjalar', 'Gullinkambi', 'Víðópnir', 'Hræsvelgr'],
      0,
      'Völuspá names three roosters that crow to herald Ragnarök: Fjalar crows for the giants, Gullinkambi ("gold-comb") crows over Valhalla to wake the gods and warriors, and an unnamed rust-red cock crows in the halls of Hel, a tripartite alarm system covering all three major factions at once.',
    ],
    [
      'Which giant, guardian of the mead of poetry, pursues Odin in eagle form after Odin steals the mead from his mountain hall Hnitbjörg?',
      ['Suttungr', 'Þjazi', 'Hrungnir', 'Baugi'],
      0,
      'Suttungr is the giant who keeps the mead of poetry hidden inside Hnitbjörg under his daughter Gunnlöð\'s guard, and when Odin, having drained the vessels, flees in the form of an eagle, Suttungr transforms into an eagle himself to give chase, nearly catching him before Odin reaches Asgard and the',
    ],
    [
      'In Hárbarðsljóð, Thor is mocked and delayed at a river crossing by a ferryman who calls himself Hárbarðr — a disguise later understood to be which god?',
      ['Odin', 'Loki', 'Heimdallr', 'Víðarr'],
      0,
      'Hárbarðr ("grey-beard") taunts Thor with a long exchange of boasts and insults from across a strait, refusing to ferry him over, and the poem is generally read by scholars as Odin in disguise deliberately humiliating his own son, drawing out an uncomfortable rivalry between the two gods\' differing',
    ],
    [
      'Which son of Thor, born to the giantess Járnsaxa, is prophesied to inherit Mjölnir after Ragnarök?',
      ['Magni', 'Móði', 'Víðarr', 'Váli'],
      0,
      'Magni ("strength") is Thor\'s son by the giantess Járnsaxa, and Vafþrúðnismál states that he and his brother Móði will inherit Mjölnir once Thor dies at Ragnarök, one of the rare pieces of Eddic material describing what happens to the gods\' possessions after the cataclysm rather than simply ending',
    ],
    [
      'In Lokasenna, Loki accuses Freyja of having committed incest with which relative, among his string of insults against the assembled gods?',
      ['her brother Freyr', 'her father Njörðr', 'her son Fjölnir', 'her uncle Ægir'],
      0,
      'Loki, working through the gods and goddesses one by one at Ægir\'s feast, accuses Freyja of having slept with every god and elf present and specifically names her brother Freyr among her lovers, an insult consistent with the poem\'s broader strategy of turning half-truths and reputational gossip',
    ],
    [
      'According to Vafþrúðnismál, what are the names of the two humans who survive Ragnarök by hiding within the wood Hoddmímis holt and go on to repopulate the earth?',
      ['Líf and Lífþrasir', 'Vidar and Vali', 'Magni and Móði', 'Baldr and Höðr'],
      0,
      'Líf and Lífþrasir are named as the pair who shelter in Hoddmímis holt, feeding on morning dew, surviving the fire and flood of Ragnarök entirely unharmed, and emerging afterward to repopulate a renewed earth, a detail preserved in Vafþrúðnismál\'s wisdom-contest catalogue of what happens after the',
    ],
    [
      'In the poem Grottasöngr, what do the giantess slaves Fenja and Menja grind on the magic mill Grotti for King Fróði before eventually turning the mill against him?',
      ['gold and peace', 'an invading army', 'the fate of the world', 'endless grain'],
      0,
      'Fenja and Menja, giantesses enslaved by King Fróði and forced to labor at the mill Grotti without rest, initially grind out gold, peace, and prosperity for his kingdom, fulfilling the request that earned them their servitude in the first place, before Fróði\'s greed in denying them rest drives them',
    ],
    [
      'According to Gylfaginning, who is named as the giantess mother of Odin, Vili, and Vé?',
      ['Bestla', 'Jörð', 'Frigg', 'Laufey'],
      0,
      'Bestla, daughter of the giant Bölþorn, marries Borr, son of the primeval Búri, and their union produces Odin and his brothers Vili and Vé, making the very first generation of the Aesir themselves half-giant by blood — a genealogical fact the mythology treats as unremarkable despite the later',
    ],
    [
      'A kenning tradition referenced in Skáldskaparmál describes Heimdallr as being the son of how many mothers?',
      ['nine', 'eight', 'three', 'seven'],
      0,
      'Heimdallr is called the son of nine mothers in kennings preserved in Skáldskaparmál, generally understood as a reference to the nine daughters of the sea-giant Ægir, personifications of the waves, making Heimdallr\'s birth an oceanic event rather than an ordinary divine parentage.',
    ],
    [
      'What is the name of Freyja\'s husband, whose mysterious disappearance causes her to wander the world weeping tears of gold?',
      ['Óðr', 'Óðinn', 'Óttar', 'Svipdagr'],
      0,
      'Óðr is named in the Prose Edda as Freyja\'s husband, and his absence — never clearly explained, whether death, travel, or estrangement — leaves Freyja grieving and wandering under various names through many lands, with her tears said to turn to gold wherever they fall, an image that also underlies',
    ],
    [
      'According to Gylfaginning, Víðarr is fated to kill Fenrir at Ragnarök using a shoe made from what material?',
      ['scraps of leather trimmed off by shoemakers', 'hide flayed from the wolf Managarmr', 'strands of hair plucked from Sif\'s head', 'bark stripped from Yggdrasil\'s roots'],
      0,
      'Víðarr\'s shoe, according to Snorri, is assembled over the whole of history from the small scraps of leather that shoemakers trim off and discard when finishing ordinary shoes, and Gylfaginning explicitly instructs that anyone wishing to help the gods at Ragnarök should throw away those leftover',
    ],

  ],
  bscba: [
    [
      'Which Norse god wields the hammer Mjölnir and is the god of thunder?',
      ['Thor', 'Odin', 'Freyr', 'Týr'],
      0,
      'Thor is the red-bearded god of thunder and storms, wielding the magical hammer Mjölnir, which returns to him after being thrown. He is immensely strong and one of the most beloved gods in Norse mythology.',
    ],
    [
      'What is the name of the great tree that holds all nine worlds together in Norse cosmology?',
      ['Yggdrasil', 'Mímisbrunnr', 'Bifrost', 'Jötunheimr'],
      0,
      'Yggdrasil is the World Tree whose roots connect to the nine realms of Norse cosmology. Its branches extend to every region, and creatures both great and small inhabit its trunk and branches.',
    ],
    [
      'Which pair of ravens does Odin send out daily to observe the world and bring him news?',
      ['Hugin and Munin', 'Sköll and Hati', 'Geri and Freki', 'Ratatoskr and Nidhögg'],
      0,
      'Hugin ("Thought") and Munin ("Memory") are Odin\'s ravens who fly across Midgard each day and return in the evening to report what they have seen, enabling Odin to stay informed of all that happens.',
    ],
    [
      'In Norse mythology, what is Ragnarök?',
      ['The end of the world and the gods', 'A magical realm hidden from mortals', 'The home of the jötnar', 'The bridge to Asgard'],
      0,
      'Ragnarök ("Twilight of the Gods") is the apocalyptic end of the Norse world, when Fenrir breaks free, Jörmungandr rises from the sea, and the final battle between gods and giants destroys the current cosmos, though some will survive to rebuild.',
    ],
    [
      'Who is Loki in Norse mythology, known for causing problems among the gods?',
      ['A giant shape-shifter and trickster', 'A frost giant king', 'A dwarven smith', 'An underworld guardian'],
      0,
      'Loki is a complex figure, part giant and part Aesir, known for his wit, cunning, and troublemaking. He orchestrates events leading to Ragnarök and is responsible for the death of the beloved god Baldr.',
    ],
    [
      'Which goddess is Odin\'s wife and knows the fates of all beings?',
      ['Frigg', 'Freyja', 'Skaði', 'Idunn'],
      0,
      'Frigg, queen of the Aesir, is Odin\'s wife and is credited with knowing the fates of all beings, though she rarely speaks of them. She attempts to protect her son Baldr from harm through her famous oaths-gathering.',
    ],
    [
      'What is the name of Odin\'s eight-legged horse, said to be the fastest steed in existence?',
      ['Sleipnir', 'Grani', 'Gulltoppr', 'Svadilfari'],
      0,
      'Sleipnir is Odin\'s magnificent eight-legged gray horse, capable of traveling between the nine worlds. His extra legs allow him speed and agility unmatched by any other mount.',
    ],
    [
      'Which magical drink grants poetic inspiration and is brewed from the blood of the wise Kvasir?',
      ['The Mead of Poetry', 'The Mead of Immortality', 'Kvasir\'s Gift', 'The Drink of Skalds'],
      0,
      'The Mead of Poetry is created when dwarves mix the blood of the wise Kvasir with honey. Whoever drinks it gains the power of inspired poetry, and Odin eventually steals it to share among the Aesir.',
    ],
    [
      'In Norse mythology, what creature is Fenrir?',
      ['A monstrous wolf', 'A giant serpent', 'A fire giant', 'A frost giant'],
      0,
      'Fenrir is a colossal wolf, son of Loki, so dangerous that the gods bind him with magical chains. He is prophesied to break free at Ragnarök and devour Odin himself during the final battle.',
    ],
    [
      'What is the name of the golden-haired apple goddess whose fruit grants immortality?',
      ['Idunn', 'Freyja', 'Sif', 'Gefjun'],
      0,
      'Idunn guards the golden apples of immortality that keep the Aesir eternally young. When the giant Þjazi abducts her, the gods begin to age, prompting a desperate rescue mission led by Loki.',
    ],
    [
      'Which weapon that never misses its target is wielded by Odin?',
      ['Gungnir', 'Gram', 'Tyrfing', 'Mistilteinn'],
      0,
      'Gungnir is Odin\'s spear (sometimes translated as a sword in popular retellings), forged by dwarves and enchanted to never miss its mark. When Odin throws it, he commands its flight and the bloodshed that follows.',
    ],
    [
      'Who are the three Norns that weave the fates of all beings at the base of Yggdrasil?',
      ['Urd, Verdandi, and Skuld', 'Morrigan, Brigid, and Danu', 'Sif, Idunn, and Frigg', 'Freyja, Gefjun, and Skaði'],
      0,
      'The three Norns (Urd meaning past, Verdandi meaning present, and Skuld meaning future) tend Yggdrasil and carve the fates of all beings into the tree, making them central to Norse cosmology.',
    ],
    [
      'Which Aesir god is known for his wisdom and lost an eye for a drink from the Well of Mimir?',
      ['Odin', 'Týr', 'Bragi', 'Vidar'],
      0,
      'Odin sacrificed one of his eyes to drink from Mimir\'s well to gain wisdom and knowledge. This act, along with his hanging on Yggdrasil, demonstrates his willingness to endure suffering for enlightenment.',
    ],
    [
      'What is the name of the ship built from the fingernails of the dead that carries giants at Ragnarök?',
      ['Naglfar', 'Hringhorni', 'Skíðblaðnir', 'Ellidi'],
      0,
      'Naglfar, a ship constructed entirely from the fingernails and toenails of dead men, carries Loki and the frost giants to battle at Ragnarök. The Norse people were advised to keep their nails trimmed to slow its completion.',
    ],
    [
      'In Norse myths, which realm is the home of the frost giants?',
      ['Jötunheimr', 'Muspelheim', 'Niflheim', 'Svartalfheim'],
      0,
      'Jötunheimr ("Giant-World") is the realm of the jötnar (giants), one of the nine worlds situated to the east of the other realms, separated by wilderness and rivers that mark its dangerous frontier.',
    ],
  ],
};

export const CELTIC_MYTH: CategoryContent = {
  msc: [
    [
      'In the Second Branch of the Mabinogi, what is the name of the Irish king who marries Branwen, daughter of Llŷr?',
      ['Matholwch', 'Efnysien', 'Manawydan', 'Gwern'],
      0,
      'Matholwch is the King of Ireland who weds Branwen to seal an alliance with her brother Bendigeidfran; the peace collapses when Branwen\'s jealous half-brother Efnysien mutilates Matholwch\'s horses, an insult that spirals into a devastating war between Britain and Ireland.',
    ],
    [
      'In Irish mythology, how does Lugh kill his own grandfather, the Fomorian king Balor, at the Second Battle of Mag Tuired?',
      ['With a sling and a stone flung into Balor\'s eye', 'With the barbed spear the Gáe Bulg', 'With the sword Fragarach', 'With the Dagda\'s death-dealing club, the lorg mór'],
      0,
      'Balor\'s single destructive eye had to be prised open by servants with a hook because its gaze annihilated whatever it fell upon, and Lugh seizes the moment to fire a sling-stone straight through it, turning the weapon back on the Fomorian host behind him.',
    ],
    [
      'Who is Cú Chulainn\'s loyal charioteer throughout the Ulster Cycle, present at his final stand?',
      ['Láeg mac Riangabra', 'Ferdiad mac Damáin', 'Conall Cernach', 'Fergus mac Róich'],
      0,
      'Láeg drives Cú Chulainn\'s scythed war-chariot through the Táin Bó Cúailnge and remains at his side to the end, dying alongside the Grey of Macha in a last attempt to protect his master\'s body from the sons of Cailitín.',
    ],
    [
      'Which early Welsh poem describes Arthur and his men sailing the ship Prydwen to raid the Otherworld (Annwn) for a magical cauldron?',
      ['Preiddeu Annwfn (The Spoils of Annwn)', 'Culhwch ac Olwen', 'Breuddwyd Rhonabwy (The Dream of Rhonabwy)', 'Y Gododdin'],
      0,
      'Preserved in the Book of Taliesin, this obscure and allusive poem has Arthur\'s warband storm a series of Otherworld fortresses to seize a cauldron warmed by the breath of nine maidens, with the haunting refrain that of the many who went, all but seven never returned.',
    ],
    [
      'In the Irish tale Cath Maige Tuired, what blemish does the poet Cairbre\'s satire raise on King Bres\'s face after Bres fails to uphold proper hospitality, costing him the kingship?',
      ['Boils, since Tuatha Dé Danann law barred a blemished man from kingship', 'A stammer that left him unable to pronounce judgments clearly', 'A squint in one eye, echoing Balor\'s baleful gaze', 'A raven-shaped birthmark, taken as an omen of doom'],
      0,
      'Cairbre, the poet of the Tuatha Dé Danann, composes a formal satire against Bres after being turned away from his hall without proper food, drink, or entertainment, and the poem\'s magic raises visible boils on the king\'s face overnight.',
    ],
    [
      'Which magical weapon does the Dagda possess that can kill nine men with one end of a blow and restore the dead to life with the other?',
      ['The Dagda\'s great club, the lorg mór', 'Fragarach, the sword of truth', 'The Cauldron of Plenty (Coire Ansic)', 'The Claíomh Solais (Sword of Light)'],
      0,
      'The lorg mór is dragged behind the Dagda so heavily that it is said to gouge a trench in the earth, a detail sometimes used to explain the origin of certain boundary ditches in Irish landscape lore.',
    ],
    [
      'In \'Culhwch and Olwen\', which giant sets Culhwch a series of nearly impossible tasks before allowing him to marry his daughter?',
      ['Ysbaddaden Bencawr', 'Custennin', 'Gwythyr ap Greidawl', 'Gwyn ap Nudd'],
      0,
      'Ysbaddaden knows, per prophecy, that he will die the day his daughter Olwen marries, so he stalls Culhwch with a catalogue of forty near-impossible tasks (anoethau), most famously hunting the great boar Twrch Trwyth to retrieve a comb and shears from between its ears.',
    ],
    [
      'Which 12th-century French poet first developed Lancelot into a major character and introduced his adulterous love affair with Guinevere?',
      ['Chrétien de Troyes', 'Geoffrey of Monmouth', 'Wace', 'Robert de Boron'],
      0,
      'Chrétien\'s \'Lancelot, le Chevalier de la Charrette\', written around 1177-1181 at the commission of Marie de France, Countess of Champagne, builds the courtly-love plot around Lancelot\'s willingness to endure shame (riding in a criminal\'s cart) to rescue the queen he loves in secret.',
    ],
    [
      'Which smith\'s fierce guard-hound does the young Sétanta kill, earning him the name Cú Chulainn?',
      ['Culann', 'Fergus mac Róich', 'Conchobar mac Nessa', 'Cathbad the druid'],
      0,
      'Arriving late to a feast at Culann\'s fort, the boy Sétanta is attacked by the smith\'s ferocious guard-dog and kills it in self-defence, then offers to serve as Culann\'s hound himself until a replacement can be reared, earning the name Cú Chulainn, \'Culann\'s Hound.',
    ],
    [
      'In the Fourth Branch of the Mabinogi, Math punishes Gwydion and Gilfaethwy by transforming them into three successive pairs of animals, each producing offspring. In what order are they transformed?',
      ['Stags, then wild boars, then wolves', 'Wolves, then wild boars, then stags', 'Wild boars, then wolves, then stags', 'Ravens, then wild boars, then wolves'],
      0,
      'Each year the brothers are turned into a different mated pair, and each pair\'s offspring is taken by Math and transformed into a human boy, fostered under names reflecting their animal origin, before the brothers move on to the next humiliating form.',
    ],
    [
      'In the First Branch of the Mabinogi, who is the King of Annwn (the Otherworld) with whom Pwyll exchanges places for a year?',
      ['Arawn', 'Hafgan', 'Gwyn ap Nudd', 'Beli Mawr'],
      0,
      'Pwyll agrees to swap appearances and kingdoms with Arawn for a year, culminating in Pwyll defeating Arawn\'s rival Hafgan in single combat, an act of loyalty that earns Pwyll the enduring epithet Pen Annwn, \'Head of Annwn.',
    ],
    [
      'What is the name of the terrifying battle-frenzy transformation that overtakes Cú Chulainn in combat, described vividly in the Táin Bó Cúailnge?',
      ['The ríastrad, or \'warp-spasm\'', 'A geis, or personal taboo', 'An aisling, or vision-dream', 'Imbas forosnai, a form of divination'],
      0,
      'During the ríastrad, Cú Chulainn\'s body twists grotesquely, one eye bulges out while the other sinks in, his hair stands on end, and a hero-light or halo is said to rise from his forehead, rendering him so terrifying that even his own allies fear approaching him.',
    ],
    [
      'In Malory\'s telling, which sword does the Lady of the Lake give Arthur after his original sword, drawn from the stone, breaks in combat with King Pellinore?',
      ['Excalibur', 'Clarent', 'Galatine', 'Carnwennan'],
      0,
      'Malory carefully distinguishes two swords: the one drawn from the stone or anvil, which proves Arthur\'s right to rule but shatters in an early duel, and Excalibur, given afterward by the Lady of the Lake along with a scabbard that magically prevents its bearer from losing blood.',
    ],
    [
      'Which of the Four Treasures brought to Ireland by the Tuatha Dé Danann is a stone said to cry out when touched by the rightful king?',
      ['The Lia Fáil (Stone of Fál)', 'The Claíomh Solais (Sword of Light)', 'The Cauldron of the Dagda', 'The Spear of Lugh'],
      0,
      'The Lia Fáil at Tara ties the mythology directly to Irish kingship ideology, since a shriek from the stone was taken as proof of sacral legitimacy, an idea that echoes wider Indo-European traditions linking sovereignty to a testing object or ordeal.',
    ],
    [
      'What is the name of the barbed spear technique, taught to Cú Chulainn by the warrior-woman Scáthach, that he uses to kill his foster-brother Ferdiad?',
      ['The Gáe Bulg', 'The Gáe Assail', 'The Claíomh Solais', 'Moralltach'],
      0,
      'Launched with the foot from underwater, the Gáe Bulg enters the body as a single wound but opens into dozens of barbs inside, making it impossible to survive or safely remove, and Scáthach is said to teach the technique to no one else.',
    ],
  ],
  phd: [
    [
      'Which 14th-century manuscript, alongside the slightly later Red Book of Hergest, is a principal source for the tales collected as the Mabinogion?',
      ['The White Book of Rhydderch', 'The Book of Taliesin', 'The Black Book of Carmarthen', 'The Book of Aneirin'],
      0,
      'The White Book of Rhydderch, compiled around the mid-14th century, and the Red Book of Hergest, from around a century later, are our two main complete manuscript witnesses to the native Welsh prose tales now grouped as the Mabinogion, though the stories themselves are believed to be considerably',
    ],
    [
      'In the classification of early Irish Otherworld-journey tales, what term describes a voyage tale like \'Immram Brain\', in which the hero deliberately sails by boat to Otherworldly islands?',
      ['Immram (voyage tale)', 'Echtrae (adventure tale)', 'Dindsenchas (place-name lore)', 'Tochmarc (wooing tale)'],
      0,
      'Immram, literally \'rowing about\', denotes tales structured around a deliberate sea voyage to a sequence of marvellous islands, distinguishing them from the echtrae genre, where the hero is typically drawn into the Otherworld unexpectedly, often lured by a supernatural visitor such as in \'Echtrae',
    ],
    [
      'The oldest surviving recension of the Táin Bó Cúailnge, compiled from two earlier written versions and preserved with visible narrative inconsistencies, is found in which manuscript?',
      ['Lebor na hUidre (the Book of the Dun Cow)', 'The Book of Leinster, a later polished redaction known as Recension II', 'The Stowe manuscript version', 'The Egerton manuscript version'],
      0,
      'Lebor na hUidre, compiled around 1106 and Ireland\'s oldest surviving manuscript substantially in the Irish language, preserves Recension I of the Táin, whose seams show clearly in doublets and contradictions, evidence that a scribe stitched together two older, now-lost written versions rather than',
    ],
    [
      'In Chrétien de Troyes\'s unfinished \'Perceval, le Conte du Graal\', what wound afflicts the Fisher King, leaving him unable to stand or ride?',
      ['A spear or javelin driven through both thighs', 'A curse laid on him by a wrathful enchantress', 'An arrow shot into his eye during a hunt', 'A sword wound to the chest from a jealous rival'],
      0,
      'The thigh wound is widely read by Grail scholars, following Jessie Weston\'s influential fertility-cult interpretation, as a euphemistic wound tied to potency and the land\'s own barrenness, linking the Fisher King\'s suffering to the wasteland motif that recurs across the Grail tradition.',
    ],
    [
      'Robert de Boron\'s \'Joseph d\'Arimathie\' is the first surviving text to explicitly identify the Grail as what?',
      ['The cup of the Last Supper, later used to catch Christ\'s blood', 'The Ark of the Covenant, said to have been carried west to Britain after the fall of Jerusalem', 'The stone bowl from the Wedding at Cana', 'The basin in which Pontius Pilate washed his hands'],
      0,
      'Before Robert de Boron, Chrétien de Troyes\'s \'graal\' is a comparatively ambiguous serving dish, but Robert\'s early 13th-century poem fixes it firmly as a sacred relic, the cup of the Last Supper later used by Joseph of Arimathea to collect Christ\'s blood, before it is carried to Britain.',
    ],
    [
      'In Geoffrey of Monmouth\'s \'Historia Regum Britanniae\', Arthur ends a long siege of Paris by killing which Roman-appointed ruler of Gaul in single combat?',
      ['Frollo', 'Lucius Hiberius', 'Petreius Cotta', 'Hoel of Brittany'],
      0,
      'Frollo governs Gaul on Rome\'s behalf, and after Arthur\'s army besieges Paris for roughly a month, the two agree to settle the war through single combat rather than mass bloodshed; Arthur wounds and then kills Frollo, winning Gaul without further siege warfare.',
    ],
    [
      'Preserved uniquely in the Black Book of Carmarthen, which early Welsh dialogue poem has Arthur boast of his warband\'s deeds to a gatekeeper demanding entry to a fortress?',
      ['Pa Gur yv y Porthaur (What Man is the Gatekeeper?)', 'Preiddeu Annwfn', 'Englynion y Beddau, the Stanzas of the Graves listing legendary burial sites', 'Culhwch ac Olwen'],
      0,
      'In this fragmentary poem, likely composed earlier than its 13th-century manuscript, Arthur lists the exploits of his companions, including Cai\'s battles against witches and monstrous cats, to a gatekeeper named Glewlwyd who refuses entry until convinced of the warband\'s worth.',
    ],
    [
      'Nuada loses his hand to the Fir Bolg champion Sreng, disqualifying him from kingship since the Tuatha Dé Danann required an unblemished ruler. In which conflict does this happen?',
      ['The First Battle of Mag Tuired, against the Fir Bolg', 'The Second Battle of Mag Tuired, against the Fomorians', 'The Battle of Tailtiu', 'The Battle of Crinna'],
      0,
      'Nuada\'s disqualification forces the Tuatha Dé Danann to install the half-Fomorian Bres as king, whose stinginess and failure to maintain proper hospitality is savaged in a satire by the poet Cairbre, providing the pretext for his removal once Nuada, fitted with a working prosthetic, can resume',
    ],
    [
      'Which god crafts Nuada\'s replacement silver arm, giving him the epithet Nuada Airgetlám?',
      ['Dian Cécht', 'Goibniu', 'Credne', 'Lugh'],
      0,
      'Dian Cécht, the Tuatha Dé Danann\'s god of healing, fashions a fully functioning silver prosthetic, though his own son Miach reportedly outdoes him by regrowing an arm of real flesh and bone from Nuada\'s severed limb, an act of professional one-upmanship that so enrages Dian Cécht he kills his son.',
    ],
    [
      'In the Welsh romance \'Owain, or the Lady of the Fountain\', what action summons a violent storm and the appearance of the fountain\'s guardian, the Black Knight?',
      ['Pouring water from a golden bowl onto a marble slab beside a great tree', 'Sounding a horn hidden beneath the fountain\'s roots', 'Casting a stolen ring into the fountain\'s waters', 'Reciting a specific triad of ritual names inscribed on a nearby standing stone beside the tree'],
      0,
      'The bowl-and-slab ritual triggers a violent storm followed by the arrival of the Black Knight, whom Owain fights, kills, and effectively replaces, marrying the knight\'s widow and taking on the role of the fountain\'s defender himself.',
    ],
    [
      'In the Vulgate Cycle\'s \'Lancelot propre\', which figure takes the infant Lancelot to her underwater fairy realm and raises him after his father\'s death, giving him the epithet \'du Lac\'?',
      ['The Lady of the Lake', 'Morgan le Fay, Arthur\'s powerful enchantress half-sister', 'Nimue', 'The Lady of Avalon'],
      0,
      'After King Ban\'s death, the Lady of the Lake, named Niniane or Viviane in various manuscripts, spirits away the infant Lancelot to her Otherworldly lake realm, educating him before sending him to Arthur\'s court fully formed as a knight, which accounts for his distinctive epithet.',
    ],
    [
      'In the Third Branch of the Mabinogi (\'Manawydan\'), what enchantment empties Dyfed of every person and animal except the four protagonists?',
      ['A dense mist descends, and when it clears everything living has vanished', 'A plague swiftly sweeps across the entire land, sparing only the four protagonists themselves', 'A great flood drowns the countryside around Arberth', 'A famine strikes after seven years of failed harvests'],
      0,
      'The mist and subsequent emptiness are eventually revealed as the vengeance of the enchanter Llwyd fab Cil Coed, acting on behalf of his friend Gwawl, who was humiliated in the First Branch during Pwyll and Rhiannon\'s wedding.',
    ],
    [
      'Which figure\'s curse, known as the Ces Noínden or \'pangs of Ulster\', incapacitates the Ulster warriors at the start of the Táin Bó Cúailnge, sparing only Cú Chulainn?',
      ['Macha, forced to race the king\'s horses while heavily pregnant', 'Medb, after being denied the kingship of Connacht', 'Emer, in retaliation for Cú Chulainn\'s infidelity', 'The Morrígan, angered by Cú Chulainn\'s rejection of her advances'],
      0,
      'Forced by King Conchobar\'s court to race against his horses despite being about to give birth, Macha wins the race but collapses and delivers twins at the finish line, cursing the men of Ulster to suffer birth-pang-like debility for five days and four nights whenever their strength is most needed.',
    ],
    [
      'In the Vulgate and Post-Vulgate traditions, who tricks a bewitched Lancelot into fathering Galahad by disguising herself as Guinevere?',
      ['Elaine of Corbenic, daughter of King Pelles', 'Elaine of Astolat, the \'Lily Maid\'', 'Guinevere herself, under an enchantment', 'Nimue, the enchantress who later traps Merlin'],
      0,
      'Elaine of Corbenic, daughter of the wounded Grail-keeper King Pelles, uses a magic ring or potion, administered in Malory\'s version through her servant Dame Brisen, to disguise herself as Guinevere so that Lancelot, his judgment clouded, sleeps with her and conceives the destined Grail-achiever',
    ],
    [
      'In \'Tochmarc Emire\' (The Wooing of Emer), what does Cú Chulainn primarily travel to Alba to learn from the warrior-woman Scáthach, at her father Forgall\'s instigation?',
      ['The arts of arms, including the fatal Gáe Bulg technique', 'The secret of eternal youth, guarded jealously by the otherworldly folk of Alba', 'The language of birds and beasts', 'The alchemy of poisons and antidotes'],
      0,
      'Forgall Manach, opposed to the match, sets Cú Chulainn a series of seemingly impossible bride-tasks in the hope he will die attempting them, including training under Scáthach in Alba, where he instead masters the full range of heroic feats of arms, including the technique that will later make him',
    ],
  ],
  professor: [
    [
      'The earliest surviving fragment of \'Culhwch ac Olwen\', dated palaeographically to around 1275 and roughly half a century older than the White Book of Rhydderch\'s complete text, survives in which manuscript?',
      ['Peniarth MS 6', 'Peniarth MS 4', 'Jesus College MS 111', 'Hengwrt MS 202'],
      0,
      'Peniarth MS 6 preserves only a fragment of the tale, but its early date is crucial evidence that \'Culhwch ac Olwen\', with its distinctive structure of impossible giant\'s tasks, was circulating in something close to its familiar form well before the Mabinogion collection as a whole was compiled in',
    ],
    [
      'Whose 1838-1849 translation and edition popularised the name \'Mabinogion\' for the collection, even though the term technically applies only to the Four Branches?',
      ['Lady Charlotte Guest', 'Ifor Williams', 'Gwyn Jones', 'John Rhys'],
      0,
      'Guest\'s multi-volume edition, presenting Welsh text alongside her English translation, introduced these tales to a wide English readership and fixed \'Mabinogion\' as the collection\'s popular title, even though later philological work, notably by Ifor Williams, established that the word properly',
    ],
    [
      'Which of Chrétien de Troyes\'s romances was left unfinished at his death and subsequently completed by four separate medieval continuators?',
      ['Perceval, le Conte du Graal', 'Yvain, le Chevalier au Lion', 'Lancelot, le Chevalier de la Charrette', 'Cligès'],
      0,
      'Chrétien\'s final romance breaks off at roughly nine thousand lines, and the mystery he left behind, chiefly why the lance bleeds and whom the grail serves, was deemed important enough that four continuators over subsequent decades, culminating in Gerbert de Montreuil\'s Fourth Continuation, added',
    ],
    [
      'Wolfram von Eschenbach\'s \'Parzival\' claims its ultimate source is a poem by a figure named Kyot, said to be from where?',
      ['Provence', 'Wales', 'Byzantium', 'Ireland'],
      0,
      'Wolfram claims Kyot (Guiot) found the Grail material in an Arabic astrological text by one \'Flegetanis\', discovered in Toledo, but no such source has ever been located, and most scholars treat the entire claim as an authorial fiction, a common medieval device for lending exotic, seemingly',
    ],
    [
      'Which text opens the Vulgate (Lancelot-Grail) Cycle and explicitly ties the Grail\'s history back through Joseph of Arimathea to the theological framework of the Fall of Adam and Eve?',
      ['The Estoire del Saint Graal', 'The Post-Vulgate Suite du Merlin', 'Perlesvaus', 'The Didot Perceval'],
      0,
      'Unlike Chrétien\'s more ambiguous romance object, the Estoire del Saint Graal frames the Grail\'s entire history within an explicit theology of sin and redemption, stretching back to Adam and Eve before tracing the vessel forward through Joseph of Arimathea\'s mission to Britain.',
    ],
    [
      'Which anonymous circa-1400 Middle English poem, closely adapting the French Vulgate \'Mort Artu\', served as a direct source for the climactic final books of Malory\'s \'Le Morte Darthur\'?',
      ['The stanzaic Le Morte Arthur', 'The alliterative Morte Arthure', 'Sir Gawain and the Green Knight', 'Layamon\'s Brut'],
      0,
      'Composed in eight-line stanzas, this poem closely follows the French Vulgate\'s account of the Round Table\'s fall, and Malory drew on it heavily, alongside the differently sourced alliterative \'Morte Arthure\' (which derives more from the Geoffrey of Monmouth and Wace chronicle tradition), for his',
    ],
    [
      'Which Anglo-Norman poet, in his 1155 \'Roman de Brut\', is credited with the earliest literary mention of the Round Table, an element entirely absent from Geoffrey of Monmouth\'s source text?',
      ['Wace', 'Layamon', 'Geoffrey of Monmouth', 'Marie de France'],
      0,
      'Wace\'s verse adaptation of Geoffrey\'s Latin \'Historia\' adds the detail that Arthur created the Round Table specifically so that none of his barons could claim precedence in seating, an innovation with no equivalent in Geoffrey and one that becomes central to virtually every subsequent Arthurian',
    ],
    [
      'According to the Welsh Triads, the Battle of Camlann is listed among the \'Three Futile Battles of the Island of Britain\' because it arose from what trivial cause?',
      ['A blow struck by Gwenhwyfach against her sister Gwenhwyfar', 'A disputed chess match between Arthur and Mordred', 'An insult offered to Merlin\'s prophecy', 'A quarrel over the ownership of a hunting dog'],
      0,
      'The \'Trioedd Ynys Prydein\', a medieval mnemonic genre grouping people and events into threes, present a Camlann origin story strikingly different from Geoffrey of Monmouth\'s political usurpation plot, instead tracing the catastrophe back to a personal blow struck by Guinevere\'s sister Gwenhwyfach',
    ],
    [
      'In which 11th/12th-century Latin saint\'s life, by Lifris of Llancarfan, does Arthur appear gambling at dice with Cai and Bedwyr while pursuing a fugitive who has claimed sanctuary?',
      ['Vita Cadoci (Life of St. Cadog)', 'Vita Gildae (Life of Gildas)', 'Vita Sancti Carantoci', 'The Historia Brittonum'],
      0,
      'In this hagiography, Arthur only relents from pursuing the fugitive after negotiation and the offer of compensating cattle, which famously transform into bundles of fern once handed over, a comic humiliation showing the secular hero subordinate to, or even outwitted by, the sanctity of the',
    ],
    [
      'Which early 13th-century text is the first surviving work to tell of a sword fixed in a stone, extractable only by Britain\'s rightful king, that the unproven young Arthur alone manages to draw?',
      ['Robert de Boron\'s Merlin', 'Geoffrey of Monmouth\'s Historia Regum Britanniae', 'The Vulgate Merlin', 'Malory\'s Le Morte Darthur'],
      0,
      'Robert de Boron\'s verse \'Merlin\' introduces the sword-in-the-stone test as miraculous proof of Arthur\'s legitimacy, a detail entirely absent from Geoffrey of Monmouth\'s earlier chronicle account, which instead has Arthur succeed his father Uther through more conventional dynastic means.',
    ],
    [
      'In the Welsh romance \'Peredur son of Efrawg\', the equivalent of the Grail procession features a platter bearing what, in place of a grail?',
      ['A man\'s severed, bleeding head', 'A chalice brimming with blood', 'A broken sword reforged from two halves', 'A coiled white serpent'],
      0,
      'This substitution has long divided scholars: some read the severed head as an independent, possibly more archaic native Welsh motif, while others see it as a garbled borrowing from, or distant relative of, the French Grail tradition found in Chrétien\'s parallel romance.',
    ],
    [
      'Which late-12th-century English chronicler explicitly attacked Geoffrey of Monmouth\'s Arthurian material as shameless, impudent lying dressed up as history?',
      ['William of Newburgh', 'Gerald of Wales', 'William of Malmesbury', 'Henry of Huntingdon'],
      0,
      'In the prologue to his \'Historia rerum Anglicarum\', William of Newburgh singled out Geoffrey\'s \'Historia Regum Britanniae\' for particularly forceful scorn, one of the earliest and sharpest contemporary rejections of Geoffrey\'s claim to be translating a genuine ancient British source.',
    ],
    [
      'The Modena Archivolt, a stone relief on Modena Cathedral in Italy carved sometime around 1120-1140, depicts armored knights attacking a tower to rescue whom, per its inscribed names?',
      ['A woman named Winlogee, held by a knight named Mardoc', 'Guinevere, held captive by Lancelot', 'Isolde, held by King Mark', 'An unnamed lady held by the giant Ysbaddaden'],
      0,
      'The relief\'s carved names, including \'Artus de Bretania\' and \'Isdernus\' among the attacking knights, are widely interpreted by scholars as Continental renderings of Arthur, Yder, Mordred (Mardoc), and Guinevere (Winlogee), making this possibly the earliest surviving depiction of Arthurian legend',
    ],
    [
      'In the Ulster Cycle death-tale \'Aided Chú Chulainn\', the hero ties himself upright to a standing stone so as to die on his feet. Who tricks him into breaking his geasa beforehand?',
      ['The sorceress daughters of Cailitín', 'Medb, seeking final revenge for the Táin', 'The Morrígan, in the form of a raven', 'Emer, unwittingly, through a broken promise'],
      0,
      'Seeking revenge for Cú Chulainn\'s earlier killing of their father, the daughters of Cailitín use sorcery to manipulate him into violating several of his personal taboos, including one forbidding him to eat dog meat, weakening him before he rides out to face his enemies already doomed.',
    ],
    [
      'The tale \'Buile Shuibhne\' (The Frenzy of Suibhne), about a king cursed to live as a deranged, bird-like wanderer, belongs to which of the four traditional cycles of early Irish literature?',
      ['The Cycle of the Kings', 'The Ulster Cycle', 'The Fenian Cycle', 'The Mythological Cycle, encompassing the Tuatha Dé Danann narratives'],
      0,
      'Modern scholarship divides early Irish narrative broadly into the Mythological Cycle (the Tuatha Dé Danann material), the Ulster Cycle (Cú Chulainn and the Táin), the Fenian Cycle (Fionn mac Cumhaill), and the Cycle of the Kings, a less overtly supernatural category focused on the doings, and',
    ],

  ],
  bscba: [
    [
      'In Arthurian legend, who is the legendary wizard and advisor to King Arthur?',
      ['Merlin', 'Lancelot', 'Guinevere', 'Morgana'],
      0,
      'Merlin is a powerful sorcerer and prophet who advises King Arthur throughout his reign. He is said to arrange Arthur\'s conception, help him claim the throne, and establish the Round Table, serving as Arthur\'s wisest counselor.',
    ],
    [
      'Who is Arthur\'s queen in Arthurian legend, known for her romance with Lancelot?',
      ['Guinevere', 'Morgana', 'Elaine', 'Vivien'],
      0,
      'Guinevere, wife of King Arthur and queen of Britain, becomes famous in medieval literature for her secret love affair with the knight Lancelot, which ultimately contributes to the downfall of Camelot.',
    ],
    [
      'Which hero of the Ulster Cycle is known for his superhuman strength and his battle-frenzy called the ríastrad?',
      ['Cú Chulainn', 'Fergus mac Róich', 'Conall Cernach', 'Lóegaire'],
      0,
      'Cú Chulainn is Ulster\'s greatest warrior, famous for his invincibility and his terrifying battle-frenzy, the ríastrad, where his body grotesquely transforms. He single-handedly holds an invading army at bay in the Táin Bó Cúailnge.',
    ],
    [
      'In the Mabinogion, what is the name of the Otherworld realm that exists alongside Wales?',
      ['Annwn', 'Avalon', 'Tír na nÓg', 'Mag Mell'],
      0,
      'Annwn is the Welsh name for the Otherworld, a magical realm that is sometimes accessible to mortals. Arthur famously raids Annwn\'s fortresses in the poem Preiddeu Annwfn seeking a magical cauldron.',
    ],
    [
      'Which Irish god is known as the "Good God" and associated with abundance and magic?',
      ['The Dagda', 'Lugh', 'Nuada', 'Balor'],
      0,
      'The Dagda ("Good God") is a powerful figure in Irish mythology, associated with fertility, magic, and warfare. He possesses a great club and a cauldron of plenty, making him central to the Tuatha Dé Danann\'s success.',
    ],
    [
      'What is the name of the magical sword that Arthur draws from a stone to prove his right to rule?',
      ['Excalibur', 'Caliburn', 'Dyrnwyn', 'Gram'],
      0,
      'Excalibur (also called Caliburn in some versions) is Arthur\'s famous sword, drawn from a stone or anvil by the young Arthur to prove his legitimacy as king. It is later replaced by another Excalibur given by the Lady of the Lake.',
    ],
    [
      'In Irish mythology, which people are the divine race of gods and goddesses who inhabit magical mounds?',
      ['The Tuatha Dé Danann', 'The Fomorians', 'The Fir Bolg', 'The Milesians'],
      0,
      'The Tuatha Dé Danann ("People of the Goddess Danu") are the Irish gods and goddesses who settle Ireland and live in magical sídhe mounds. They represent the pagan divine order replaced by the historical human settlers.',
    ],
    [
      'Which Arthurian knight is famous for his strength, courtesy, and his illicit love for Queen Guinevere?',
      ['Lancelot du Lac', 'Gawain', 'Bedivere', 'Kay'],
      0,
      'Lancelot du Lac is one of Arthur\'s greatest knights, famous for his strength, courtesy, and his illicit love for Queen Guinevere. He is often portrayed as one of the most skilled warriors in Camelot.',
    ],
    [
      'What is the name of King Arthur\'s circular table, designed so that no knight could claim superiority in seating?',
      ['The Round Table', 'The Table of Fellowship', 'The Circle of Knights', 'The Table of Equals'],
      0,
      'The Round Table is Arthur\'s famous dining table, designed with no head so that all knights seated at it are equal in status. It becomes a symbol of chivalry and fellowship in Arthurian legend.',
    ],
    [
      'In the Mabinogion, which character is magically created from flowers and given to Gwydion as a wife?',
      ['Blodeuedd', 'Rhiannon', 'Goewin', 'Branwen'],
      0,
      'Blodeuedd is conjured from flowers by the magician Math as a bride for his nephew Lleu. When she proves unfaithful, Gwydion transforms her into an owl as punishment, making her a symbol of infidelity in Welsh mythology.',
    ],
    [
      'Which Irish hero kills his grandfather Balor at the Second Battle of Mag Tuired?',
      ['Lugh', 'Balor', 'Indech', 'Bres'],
      0,
      'Lugh, grandson of the terrifying Fomorian king Balor, kills his grandfather in battle by firing a sling-stone through Balor\'s single destructive eye. This victory gives the Tuatha Dé Danann dominance over Ireland.',
    ],
    [
      'In Arthurian legend, what is the Holy Grail?',
      ['The cup used at the Last Supper', 'A magical chalice with healing powers', 'A sacred relic sought by knights', 'All of the earlier'],
      0,
      'The Holy Grail is depicted as the cup used by Christ at the Last Supper, said to possess miraculous healing powers. In Arthurian legend, it is sought by Arthur\'s knights, particularly Lancelot and Perceval, as the ultimate spiritual quest.',
    ],
    [
      'Which Arthurian knight is known for his adventures with a magical lion and resemblances to Chrétien\'s Yvain?',
      ['Owain', 'Bedivere', 'Lancelot', 'Gawain'],
      0,
      'Owain is a Welsh Arthurian knight famous for his adventures, particularly his encounter at a magical fountain and his rescue of a lion. His tale closely parallels Chrétien de Troyes\'s French romance Yvain.',
    ],
    [
      'In the Ulster Cycle, what is a geis?',
      ['A personal taboo or prohibition', 'A magical curse', 'A type of warrior training', 'A prophetic vision'],
      0,
      'A geis (or geasa in plural) is a magical obligation or taboo placed upon a person, often by supernatural forces or through magically sworn oaths. Violating a geis typically brings dire consequences, as with Cú Chulainn\'s prohibition against eating dog meat.',
    ],
    [
      'Which British king is said to be asleep in Avalon, waiting to return and restore Britain?',
      ['King Arthur', 'King Lear', 'King Uther', 'King Mark'],
      0,
      'King Arthur, after his final battle at Camlann, is said to have been carried to the magical island of Avalon by enchanted barge. According to legend, he sleeps there but will one day return ("Rex Quondam Rexque Futurus") to restore Britain.',
    ],
  ],
};
