import type { CategoryContent } from './row.js';

export const PHOTOGRAPHY: CategoryContent = {
  bscba: [
    [
      'What material forms the reflective surface of a daguerreotype?',
      [
        'Silver-plated copper sheet',
        'Polished glass with mercury backing',
        'Tin foil laminated to brass',
        'Aluminum alloy with silver nitrate coating',
      ],
      0,
      'Daguerreotypes consist of a silver layer electroplated onto copper, which provides the rigid, reflective base needed for the image.',
    ],
    [
      'In wet plate collodion photography, what chemical compound forms the photosensitive layer?',
      [
        'Silver iodide suspended in collodion',
        'Silver chloride in gelatin suspension',
        'Silver bromide crystals in egg white',
        'Copper sulfate mixed with potassium permanganate',
      ],
      0,
      'Wet plate collodion uses iodine mixed with collodion (nitrocellulose dissolved in ether), sensitized by immersion in silver nitrate.',
    ],
    [
      'What advantage did dry plate gelatin emulsions offer over wet collodion plates?',
      [
        'Could be exposed days or weeks after preparation',
        'Required no chemical processing in the darkroom',
        'Produced images with finer detail than any other process',
        'Could be easily reused by removing the emulsion',
      ],
      0,
      'Dry gelatin plates were pre-coated and could be stored for extended periods before use, eliminating on-site preparation.',
    ],
    [
      'What does ISO speed measure in film and digital sensors?',
      [
        'Light sensitivity of the imaging medium',
        'The maximum aperture opening of the lens',
        'The duration of the exposure in seconds',
        'The color temperature of the light source',
      ],
      0,
      'ISO quantifies sensitivity to light: higher ISO means more sensitivity but typically introduces visible grain or noise.',
    ],
    [
      'What does an f-stop number represent?',
      [
        'The ratio of the lens focal length to the aperture diameter',
        'The maximum shutter speed available on the camera',
        'The number of color filters in the optical path',
        'The focal distance at which the lens produces sharpest focus',
      ],
      0,
      'F-stops (f/1.8, f/4, f/16, etc.) express aperture size as a ratio; lower numbers mean wider apertures and more light.',
    ],
    [
      'Which photographic movement emphasized soft focus, hand-coloring, and painterly qualities?',
      [
        'Pictorialism',
        'Straight Photography',
        'Constructivism',
        'Photojournalism',
      ],
      0,
      'Pictorialism (late 19th–early 20th century) mimicked fine art painting through deliberate softness, texture, and manipulation.',
    ],
    [
      'What is the primary function of a darkroom safelight?',
      [
        'Allow safe working light without exposing undeveloped photographic materials',
        'Provide heat for chemical reactions during film development',
        'Monitor the density of chemical solutions',
        'Eliminate dust particles from the darkroom air',
      ],
      0,
      'Safelights (typically red or amber) emit wavelengths photographic emulsions cannot perceive, allowing safe work without fogging.',
    ],
    [
      'In Ansel Adams\'s Zone System, what does Zone V represent?',
      [
        'Middle gray (18% reflectance)',
        'Pure black with no detail',
        'Pure white with no detail',
        'The average brightness of landscape shadows',
      ],
      0,
      'Zone V is the system\'s reference middle tone at 18% reflectance. Zones above and below relate to it in one-stop increments.',
    ],
    [
      'What technique involves selectively blocking light during enlargement to darken areas of a photographic print?',
      [
        'Dodging',
        'Burning',
        'Solarization',
        'Intensification',
      ],
      0,
      'Dodging holds back light, making areas lighter. Burning adds light to darken areas—complementary darkroom techniques.',
    ],
    [
      'Which famous American photographer is known for large-format landscapes and the Zone System?',
      [
        'Ansel Adams',
        'Edward Weston',
        'Walker Evans',
        'Alfred Stieglitz',
      ],
      0,
      'Ansel Adams pioneered the Zone System and created iconic black-and-white landscapes of the American West.',
    ],
    [
      'What chemical compound is applied to glass or paper to create an albumen print?',
      [
        'Egg white (albumen) with silver nitrate',
        'Gelatin dissolved in potassium chloride',
        'Wax emulsion with cadmium sulfide',
        'Starch paste with copper acetate',
      ],
      0,
      'Albumen prints use a layer of egg white on paper to create a smooth surface, then sensitized with silver nitrate.',
    ],
    [
      'What is the "calotype" process also known as?',
      [
        'Talbotype (after William Henry Fox Talbot)',
        'Daguerreotype variant',
        'Ferrotype process',
        'Gelatin dry plate',
      ],
      0,
      'The calotype, invented by Talbot in 1841, produced a negative on paper—the ancestor of modern negative-based photography.',
    ],
    [
      'In street photography, what does "the decisive moment" refer to?',
      [
        'The instant when composition and subject converge at peak meaning',
        'The exact second when film must be developed',
        'The moment the camera shutter reaches maximum speed',
        'The time when natural light is most flattering',
      ],
      0,
      'Henri Cartier-Bresson\'s term for capturing the exact instant of perfect composition and meaning in an unfolded scene.',
    ],
    [
      'What is the primary purpose of film grain in black-and-white photography?',
      [
        'It is an unavoidable artifact of how silver halide crystals form the image',
        'It is added during printing to prevent image fading',
        'It improves the sharpness of fine details',
        'It allows light to reflect more evenly across the print',
      ],
      0,
      'Grain results from individual silver halide crystals in the emulsion; finer grain means higher resolution but lower sensitivity.',
    ],
    [
      'Which American photographer produced a systematic documentation project for the Farm Security Administration?',
      [
        'Walker Evans',
        'Margaret Bourke-White',
        'Paul Strand',
        'Minor White',
      ],
      0,
      'Walker Evans created a typological archive of American rural culture in the 1930s for the FSA, influencing documentary photography.',
    ],
  ],

  msc: [
    [
      'Why does a daguerreotype image appear reversed (laterally inverted)?',
      [
        'The single mirror-like surface reflects light at the camera lens angle',
        'The silver plating process reverses the molecular structure',
        'Daguerreotypes always required a mirror to be placed in front for viewing',
        'The image was chemically flipped during the sensitization process',
      ],
      0,
      'Daguerreotypes are unique reversed images because light directly exposes the polished metal surface without intervening film layers.',
    ],
    [
      'How did wet plate collodion photography differ fundamentally from earlier calotype processes?',
      [
        'Collodion emulsion adhered to glass, enabling far greater detail and reusability than paper negatives',
        'Calotypes used silver nitrate while collodion used only iodine compounds',
        'Collodion plates could be stored indefinitely before exposure',
        'Wet plate collodion produced visible grain while calotypes were grain-free',
      ],
      0,
      'Glass substrates and collodion emulsion offered superior resolution and cleaner negatives than paper; collodion dominated 1850s–1880s.',
    ],
    [
      'In what way does the sensitometric curve (D-log E) characterize film behavior?',
      [
        'It plots density (darkness) against log exposure, showing tonal range and film speed response',
        'It measures the time required for chemical development at various temperatures',
        'It predicts how grain size changes with different lighting conditions',
        'It indicates the color shift that occurs in aged emulsions',
      ],
      0,
      'The D-log(E) curve maps density vs. log exposure, revealing film latitude, gamma, and sensitivity—core sensitometric data.',
    ],
    [
      'Why is hyperfocal distance important in large-format landscape photography?',
      [
        'Focusing at hyperfocal distance maximizes depth of field from near to far without refocusing',
        'It prevents optical distortion in wide-angle lenses',
        'It determines the optimal shutter speed for hand-holding',
        'It compensates for the bellows extension on view cameras',
      ],
      0,
      'Setting focus at the hyperfocal distance ensures acceptable sharpness from half that distance to infinity.',
    ],
    [
      'What philosophical difference separated Pictorialism from Straight Photography?',
      [
        'Pictorialists pursued artistic control and painterly manipulation; Straight photographers emphasized unmanipulated subject revelation',
        'Straight photographers used color film while Pictorialists used only black-and-white',
        'Pictorialists required special lenses while Straight photographers used standard lenses',
        'Straight photography only worked outdoors; Pictorialism required studio lighting',
      ],
      0,
      'Straight Photography (Weston, Adams) rejected Pictorialist hand-manipulation, championing sharp focus and photographic form.',
    ],
    [
      'Which photographic movement explicitly documented rural American poverty and displacement during the Great Depression?',
      [
        'Farm Security Administration photography (1935–1944)',
        'Pictorialism movement (1890–1910)',
        'Modernist abstraction (1920–1940)',
        'Photo-Secession group (1905–1917)',
      ],
      0,
      'The FSA hired photographers to create a visual record of rural conditions and resettlement efforts—foundational documentary photography.',
    ],
    [
      'What is the chemical basis for archival permanence in platinum prints versus gelatin silver prints?',
      [
        'Platinum is chemically inert and resists fading; gelatin silver relies on unfixed residual salts that degrade over time',
        'Gelatin contains natural preservatives that platinum lacks',
        'Platinum prints require special light sources to remain stable',
        'Gelatin prints fade only if exposed to moisture',
      ],
      0,
      'Platinum metal is inert and extremely stable; gelatin silver prints degrade if incomplete fixing leaves reactive compounds.',
    ],
    [
      'In darkroom enlargement, why does burning certain areas require precise exposure time calculation?',
      [
        'Excessive burning causes the print paper to turn black; too little burns almost nothing visible',
        'Burning can cause chemical reactions that release toxic fumes',
        'Paper emulsion becomes temporarily insensitive after initial exposure',
        'Burn time directly affects the saturation of color in black-and-white prints',
      ],
      0,
      'Burning adds localized exposure; miscalculation yields muddy blacks (too much) or negligible darkening (too little).',
    ],
    [
      'What role did the Photo-Secession play in establishing photography as fine art?',
      [
        'It organized exhibitions and publications that positioned photography alongside painting and sculpture in galleries',
        'It invented the first color photography process',
        'It developed the first automated camera mechanisms',
        'It established patent laws protecting photographic inventions',
      ],
      0,
      'Stieglitz\'s Photo-Secession (1902) exhibited photography in art galleries and published Camera Notes, legitimizing it as serious art.',
    ],
    [
      'How does sensor demosaicing affect image quality in digital cameras?',
      [
        'Demosaicing algorithms reconstruct full-color images from Bayer-pattern data; poor algorithms introduce color fringing and noise',
        'Demosaicing has no effect on image quality; it is purely a mechanical process',
        'Demosaicing increases the effective pixel count of the sensor',
        'Demosaicing is only necessary for black-and-white digital photography',
      ],
      0,
      'Bayer sensors capture only one color per pixel; demosaicing reconstructs full RGB. Quality depends on algorithm sophistication.',
    ],
    [
      'What is the principle behind Ansel Adams\'s Zone System beyond practical metering?',
      [
        'It provides a conceptual framework linking exposure, development, and printing to achieve previsioned tonal outcomes',
        'It eliminates the need for light meters entirely',
        'It works only with large-format cameras',
        'It guarantees that all film stocks produce identical tones',
      ],
      0,
      'The Zone System links exposure and development to visualization: each zone increment controls tonal separation intentionally.',
    ],
    [
      'Why did wet plate collodion remain dominant despite the invention of dry plate gelatin emulsions?',
      [
        'Collodion initially offered superior image quality and required no pre-preparation; gelatin plates took time to become reliable',
        'Wet plates were cheaper to manufacture',
        'Dry plates could not be used outdoors',
        'Collodion was easier to sensitize than gelatin',
      ],
      0,
      'Wet plate image quality was superior and immediate; gelatin needed ~15 years of development before achieving comparable performance.',
    ],
    [
      'In color film photography, what causes the color shift in tungsten-balanced film exposed under daylight?',
      [
        'Daylight\'s higher color temperature (blue) overwhelms tungsten film\'s warm-shifted emulsion balance',
        'Tungsten film automatically corrects for any light source',
        'Daylight contains ultraviolet that bleaches color dyes',
        'The film\'s filters react chemically to sunlight',
      ],
      0,
      'Tungsten film (3200K) appears excessively blue in daylight (5500K); daylight film looks orange under tungsten.',
    ],
    [
      'What did Edward Weston mean by "previsualization" in his photographic practice?',
      [
        'Mentally composing the final print before releasing the shutter, then executing with precision',
        'Using multiple exposures to layer different compositions',
        'Photographing the same subject repeatedly until achieving the desired angle',
        'Sketching compositions in pencil before setting up the camera',
      ],
      0,
      'Weston\'s previsualization meant seeing the complete tonal range and composition before exposure—not relying on darkroom rescue.',
    ],
    [
      'How did street photographer Henri Cartier-Bresson\'s choice of rangefinder camera influence his work?',
      [
        'Rangefinders\' compactness and quiet shutter enabled unobtrusive observation; bright viewfinders supported spontaneous framing',
        'Rangefinders produced sharper images than view cameras',
        'Rangefinders were the only cameras capable of color photography then',
        'Rangefinders had superior autofocus systems',
      ],
      0,
      'The Leica rangefinder was compact, silent, and had a bright frame-line viewfinder—ideal for candid street photography.',
    ],
  ],

  phd: [
    [
      'Why did daguerreotype manufacturers specifically plate copper with silver rather than using solid silver sheets?',
      [
        'Copper provides structural rigidity and cost efficiency; silver plating achieves the reflective surface while avoiding material waste',
        'Silver was too brittle for the polishing required before sensitization',
        'Copper\'s oxidation created the photosensitive layer during iodine exposure',
        'Solid silver reacted chemically with the iodine compound and destroyed images',
      ],
      0,
      'Copper substrate ensures mechanical strength; thin silver plate is sufficient for reflection and cost-effective.',
    ],
    [
      'In wet plate collodion, what chemical role does iodine play versus the later bromine additions?',
      [
        'Iodine serves as the primary halide; bromine and chloride additions accelerate sensitization and expand dynamic range',
        'Iodine and bromine produce identical sensitization rates and sensitivity',
        'Bromine eliminated the need for silver nitrate immersion',
        'Iodine made plates unstable; bromine solved this entirely',
      ],
      0,
      'Iodine is the base halide; added bromides and chlorides increase sensitization speed without changing the fundamental process.',
    ],
    [
      'How do Bayer CFA arrays and demosaicing algorithms introduce color artifacts in digital sensors?',
      [
        'Adjacent pixels of different colors create color fringing at edges when interpolation fails; aliasing patterns emerge at fine detail',
        'Bayer arrays automatically reduce color saturation in all images',
        'Demosaicing uniformly blurs all color information',
        'Color artifacts only occur with defective sensors',
      ],
      0,
      'Bayer interpolation near edges can misassign colors; poor demosaicing creates artifacts especially at transitions.',
    ],
    [
      'In gelatin emulsion aging, what causes the physical blistering and desquamation of dried glass plates?',
      [
        'Differential expansion rates between gelatin and glass during humidity cycling; residual solvent evaporation creates internal stress',
        'Oxidation of the silver halide crystals',
        'Bacterial growth between the gelatin and glass',
        'Thermal expansion of the copper backing layer',
      ],
      0,
      'Gelatin and glass have different expansion coefficients; humidity fluctuation creates stress. Residual solvent migration accelerates damage.',
    ],
    [
      'What distinguishes apochromatic lens correction from standard achromatic designs?',
      [
        'Apochromatic elements correct for chromatic aberration at three wavelengths instead of two, reducing color fringing across spectrum',
        'Apochromatic lenses use reflective coatings while achromatic lenses use refraction only',
        'Apochromatic lenses are only usable in ultraviolet wavelengths',
        'Apochromatic and achromatic lenses are functionally identical',
      ],
      0,
      'Apo designs correct three spectral lines (vs. two in achromatic); superior color registration, especially at large apertures.',
    ],
    [
      'How do development kinetics differ between phenidone and hydroquinone developers?',
      [
        'Phenidone develops faster and preserves shadow detail better; hydroquinone offers higher contrast and longer working life per batch',
        'Hydroquinone is faster but produces more grain',
        'Phenidone requires higher temperatures than hydroquinone',
        'Both developers produce identical contrast curves',
      ],
      0,
      'Phenidone works quickly and gently (better shadow separation); hydroquinone is slower but produces higher contrast and longevity.',
    ],
    [
      'What philosophical and artistic premises underlay the Pictorialist movement and its alignment with Symbolism?',
      [
        'Pictorialists drew from Symbolist literature\'s emphasis on mood, subjective interpretation, and rejecting objective representation',
        'Pictorialism was purely a technical photographic innovation unrelated to artistic movements',
        'Pictorialists specifically rejected all fine art influences',
        'Pictorialism aligned with Realism, not Symbolism',
      ],
      0,
      'Pictorialists embraced Symbolist ideals: emotion and interpretation over documentation; art as inner vision, not external fact.',
    ],
    [
      'What methodological approach did Walker Evans employ in his Farm Security Administration typological documentation?',
      [
        'Systematic frontal framing and repeat subject typologies to create an objective visual archive transcending individual aesthetic preference',
        'Highly subjective emotional portraits emphasizing individual pathos',
        'Painterly composition mimicking fine art aesthetics',
        'Sequential narrative storytelling following families over years',
      ],
      0,
      'Evans developed a typological method: repeated frontal angles, deadpan lighting, systematic cataloging—a dispassionate archive aesthetic.',
    ],
    [
      'How do platinum print metal-salt interactions ensure extraordinary longevity compared to other printing processes?',
      [
        'Platinum metal deposits metallic elemental platinum in fibers during development; platinum is chemically inert and cannot oxidize or fade',
        'Platinum prints use special lacquer coatings that prevent light exposure',
        'Platinum printing uses archival paper that gelatin processes cannot access',
        'Platinum and gelatin prints are equally permanent',
      ],
      0,
      'Platinum deposits elemental Pt; chemically inert, it resists fading. Gelatin silver relies on reduced silver—easily oxidized.',
    ],
    [
      'In the Bayer CFA architecture, what is the purpose of microlenses above individual photodiodes?',
      [
        'Microlenses focus incident light onto the photodiode active area, improving collection efficiency and reducing angular sensitivity loss',
        'Microlenses eliminate hot pixels',
        'Microlenses separate color channels mechanically',
        'Microlenses serve only aesthetic purposes and do not affect image quality',
      ],
      0,
      'Microlenses concentrate light onto the active photodiode area, improving light collection efficiency at high pixel density.',
    ],
    [
      'What distinguishes digital raw file data processing (demosaicing, white balance) from in-camera JPEG rendering?',
      [
        'Raw files preserve unmosaiced sensor data allowing post-processing flexibility; JPEG applies fixed demosaicing, color science, and compression',
        'Raw files cannot be printed and JPEG files can only be printed',
        'Raw files always have lower resolution than JPEGs',
        'Raw and JPEG files are identical after demosaicing',
      ],
      0,
      'Raw preserves Bayer data for flexible post-processing; JPEG applies fixed demosaicing algorithms and color science in-camera.',
    ],
    [
      'How did early motion picture film stocks evolve regarding emulsion sensitivity and color reproduction?',
      [
        'Orthochromatic stocks (blind to red) gave way to panchromatic stocks; color film (1950s) required entirely new emulsion chemistry',
        'Film stocks have remained chemically unchanged since invention',
        'Color film existed since the 1920s but was suppressed for cost reasons',
        'Panchromatic film preceded orthochromatic film chronologically',
      ],
      0,
      'Ortho stocks (red-blind) dominated silents; panchromatic arrived 1920s–30s. Color film (Technicolor, Eastmancolor) arrived mid-20th century.',
    ],
    [
      'What technical constraints did large-format negative size impose on Ansel Adams\'s previsualization practice?',
      [
        'Large formats (4x5, 8x10) offered exceptional shadow detail and tonal separation but required precise exposure; errors were costly',
        'Large formats allowed unlimited bracketing and test shots',
        'Large formats produced images identical in quality to 35mm film',
        'Large formats had no impact on visualization because prints could always be enlarged',
      ],
      0,
      '8x10 negatives offer unmatched resolution and shadow separation but demand precise exposure; every sheet costs time and materials.',
    ],
    [
      'In the Constructivist and Bauhaus movements, how did photography\'s formal properties (sharp focus, high contrast, unusual angles) align with modernist visual ideology?',
      [
        'Photography\'s mechanical objectivity and tonal purity reflected modernism\'s embrace of industrial forms and rejection of romantic subjectivity',
        'Photography had no connection to Constructivism or Bauhaus',
        'Photography was rejected by Constructivists as insufficiently artistic',
        'Constructivists used photography only for documentary purposes',
      ],
      0,
      'Constructivists valued photography\'s apparent objectivity and geometric potential; sharp focus and angles matched modernist aesthetics.',
    ],
    [
      'What optical and functional trade-offs does the rangefinder focusing system impose on wide-angle coverage?',
      [
        'Wider lenses reduce parallax base, making accurate rangefinder focus increasingly difficult; below ~35mm rangefinder accuracy drops sharply',
        'Rangefinders work perfectly at all focal lengths',
        'Rangefinders are most accurate with wide lenses',
        'Wide-angle lenses eliminate the need for rangefinder focusing',
      ],
      0,
      'Rangefinder base is fixed; wider lenses magnify parallax errors. Below ~35mm, focusing by rangefinder becomes impractical.',
    ],
  ],

  professor: [
    [
      'Why did daguerreotype manufacturers employ bromine vapor sensitization after initial iodine coating on silver surfaces?',
      [
        'Bromine increased light sensitivity and extended the spectral response beyond iodine alone, reducing exposure times from minutes to seconds',
        'Bromine removed iodine compounds that contaminated the image',
        'Bromine improved the reflectivity of the silver surface',
        'Bromine and iodine served identical sensitization roles',
      ],
      0,
      'Bromine addition to iodized daguerreotype plates increased sensitivity by extending halide response; exposure times dropped dramatically.',
    ],
    [
      'In ferotype (tintype) emulsion formulation, how did iron oxide and collodion proportions determine image density and permanence?',
      [
        'Iron oxide concentration controlled emulsion density and UV protection; collodion ratio determined adhesion and flexibility under thermal stress',
        'Iron oxide and collodion were unrelated components',
        'Ferotypes used silver halide, not iron oxide',
        'Ferotype composition was standardized and never varied',
      ],
      0,
      'Tintype emulsions used iron oxide suspended in collodion; proportions balanced density, adhesion, and environmental stress resistance.',
    ],
    [
      'How do Color Filter Array demosaicing algorithms (linear interpolation vs. gradient-based vs. machine learning) differ in handling aliasing and color fringing?',
      [
        'Linear methods introduce visible fringing at edges; gradient-based methods preserve transitions better; ML approaches learn complex spatial patterns',
        'All demosaicing methods produce identical results',
        'Linear interpolation is superior to all other methods',
        'CFA demosaicing has no effect on aliasing',
      ],
      0,
      'Linear demosaicing causes fringing; gradient-aware algorithms suppress it by respecting edge direction. ML generalizes beyond hand-coded rules.',
    ],
    [
      'In photographic sensitometry, what does the shape of the D-log(E) curve\'s toe region reveal about film behavior in shadows?',
      [
        'The toe slope and length indicate film latitude in shadows: shallow toe = harsh shadow separation, long toe = gentle shadow rolloff',
        'The toe is unrelated to shadow rendering',
        'A steep toe always produces better shadow detail',
        'The toe affects only highlight behavior',
      ],
      0,
      'Curve toe determines shadow behavior: steep toe compresses shadows, gentle toe preserves detail; length controls shadow latitude.',
    ],
    [
      'Beyond simple focal-length correction, how do apochromatic lens designs reduce residual lateral color and spherochromatism?',
      [
        'Apo elements employ fluorite or special glass with anomalous dispersion to reduce secondary spectrum across wider apertures and focus bands',
        'Apochromatic lenses eliminate all optical aberrations',
        'Apochromatic lenses work only at stopped-down apertures',
        'Lateral color is only corrected by software, not optics',
      ],
      0,
      'Apo lenses use anomalous-dispersion elements (fluorite, special glass) to suppress secondary spectrum beyond standard achromatic limits.',
    ],
    [
      'In black-and-white film development, how do pH and buffer capacity of developer solutions influence the rate and selectivity of development reactions?',
      [
        'pH ~10.5 activates phenidone/hydroquinone; higher pH accelerates development but risks caustic effects; buffers stabilize pH across the reaction',
        'pH has no effect on development chemistry',
        'Lower pH always speeds development',
        'Buffers are irrelevant in developer composition',
      ],
      0,
      'Optimal pH (~10.5) balances development kinetics with safety. Buffers maintain pH stability, ensuring consistent, predictable development.',
    ],
    [
      'What does the Pictorialist movement\'s theoretical alignment with Art Nouveau and literary Decadence reveal about early photography\'s cultural positioning?',
      [
        'Pictorialists deliberately positioned photography as subjective artistic expression aligned with Symbolist and Decadent rejection of industrial positivism',
        'Pictorialism was purely technical with no cultural context',
        'Pictorialists aligned with scientific positivism and rejected subjectivity',
        'Photography\'s cultural role was identical to painting throughout the 19th century',
      ],
      0,
      'Pictorialists embraced Decadent and Art Nouveau aesthetics: rejecting progress-narrative, asserting subjectivity, and positioning art against industry.',
    ],
    [
      'In Walker Evans\'s FSA archive methodology, how did his conceptual framework of "American photographs" as ethnographic typology diverge from documentary tradition?',
      [
        'Evans pursued systematic, frontal typology (building equivalent sets) rather than narrative or emotional framing; a sociological rather than journalistic approach',
        'Evans employed standard photojournalistic narrative storytelling',
        'Evans rejected systematic methodology in favor of purely intuitive selection',
        'Evans\'s work was indistinguishable from other FSA photographers\' approaches',
      ],
      0,
      'Evans\'s typological method—frontal, deadpan, cataloging—created an ethnographic inventory rather than narrative documentary.',
    ],
    [
      'In platinum printing, how do the oxidation states of platinum salts (II vs. IV) and ferric compounds control the sensitization range and print tone?',
      [
        'Ferric salts (Fe³⁺) determine sensitization; platinum oxidation state (Pt²⁺ vs. Pt⁴⁺) governs metallic deposit and final tone from cold gray to warm sepia',
        'Platinum has only one oxidation state in printing',
        'Ferric salts have no role in platinum printing',
        'Oxidation states do not affect print tone or sensitivity',
      ],
      0,
      'Ferric compound ratio controls sensitization; platinum deposit state determines tone—cold grays from Pt⁴⁺, warmer from Pt²⁺.',
    ],
    [
      'How does read noise versus photon shot noise dominate in low-light digital capture, and how do high-ISO algorithms attempt to suppress each?',
      [
        'At low light, read noise dominates; high-ISO amplifies signal uniformly while temporal noise filtering targets read-noise spikes; photon noise requires exposure',
        'Read noise and photon noise are identical',
        'High-ISO amplification eliminates both noise types completely',
        'Photon shot noise only occurs at high ISO',
      ],
      0,
      'Read noise dominates shadows at base ISO; high-ISO amplification helps photon noise dominate. Algorithms use temporal filtering and frame stacking.',
    ],
    [
      'Beyond Ansel Adams\'s original nine-zone framework, how do modern sensitometric approaches extend Zone System thinking to digital capture and raw file optimization?',
      [
        'Digital practitioners use histogram-based zone mapping and exposure-latitude optimization; raw files offer extended shadow latitude vs. slide film',
        'Zone System is obsolete in the digital era',
        'Digital files have no equivalent to Zones',
        'Modern digital practice abandoned Adams\'s framework entirely',
      ],
      0,
      'Digital Zone extensions use histograms and raw latitude; raw capture recovers shadow detail impossible in slide film, expanding Adams\'s model.',
    ],
    [
      'In the shift from orthochromatic to panchromatic motion picture emulsions (1925–1935), what chemical emulsion innovations enabled red-sensitivity extension?',
      [
        'Introduction of merocyanine and other spectral sensitizers allowed dyes to shift peak sensitivity toward red; manufacturing required new coating processes',
        'Red sensitivity appeared spontaneously without chemical innovation',
        'Red sensitivity was always present but masked by dyes',
        'Panchromatic film required no chemical changes from orthochromatic stock',
      ],
      0,
      'Spectral sensitizers (merocyanine dyes) extended peak response into red; required new emulsion chemistry and manufacturing precision.',
    ],
    [
      'How did the mechanical constraints and precision demands of large-format view camera operation shape Ansel Adams\'s and other masters\' visual conceptualization?',
      [
        'Large format\'s slowness, expense, and inflexibility enforced previsualization discipline; camera movements (tilt, shift, swing) became conceptual tools for controlling perspective and focus plane',
        'Large format imposed no constraints on photographers\' thinking',
        'Large format made visualization impossible due to small ground glass',
        'Camera movements were purely for technical correction, not creative intention',
      ],
      0,
      'View cameras\' deliberate pace and precise control forced careful composition; movements became intentional design tools, not corrections.',
    ],
    [
      'In what ways did the Russian Constructivist embrace of photography (e.g., Rodchenko, Lisitsky) position the medium as ideologically aligned with revolutionary modernism?',
      [
        'Constructivists valued photography\'s apparent objectivity and mechanical repeatability as aligned with Marxist materialism; unusual angles and cropping asserted human design over passive documentation',
        'Constructivists rejected photography as bourgeois',
        'Photography was incidental to Constructivism\'s core ideology',
        'Constructivists used photography identically to traditional fine art',
      ],
      0,
      'Constructivists saw photography\'s mechanical basis as proof of workers\' visual culture; high angles and cropping asserted design over nature.',
    ],
    [
      'How do the optical characteristics of rangefinder conjugate-prism designs (separation distance, prism geometry) establish the limits of accurate focusing across focal lengths?',
      [
        'Base distance is fixed; shorter working distances reduce magnification of parallax movement; below ~35mm, parallax angle becomes subresolution and focusing becomes impractical',
        'Rangefinder geometry is unrelated to focal-length performance',
        'Rangefinders are equally accurate at all focal lengths',
        'Prism geometry changes automatically for each lens',
      ],
      0,
      'Fixed base means shorter lenses reduce parallax magnification; at wide angles, the parallax angle falls below focusing resolution.',
    ],
  ],
};
