import type { CategoryContent } from './row.js';

/**
 * Film & TV Technology (1980-Now).
 */

export const SCREEN_TECH: CategoryContent = {
  msc: [
    [
      'Which 1985 feature film contains the scene widely credited as the first fully computer-generated character to appear in a live-action motion picture?',
      ['Young Sherlock Holmes', 'Tron', 'The Last Starfighter', 'Flight of the Navigator'],
      0,
      'The stained-glass knight in Young Sherlock Holmes (1985) was rendered by Lucasfilm\'s Computer Graphics division (soon to become Pixar) and is credited as the first fully CG character composited into live-action film. Tron (1982) used CGI but not for characters performing alongside live actors. The shot proved a CG figure could be believably lit and composited into real footage.',
    ],
    [
      'Which 1995 film is recognized as the first feature-length film created entirely with computer-generated imagery, with no traditional cel animation or live-action photography?',
      ['Toy Story', 'Toy Story 2', 'A Bug\'s Life', 'The Lion King'],
      0,
      'Toy Story (1995) was the first fully CGI feature film, rendered on Pixar\'s RenderMan software. It proved CG animation could carry a feature-length narrative and led to a ten-picture deal with Disney. A Bug\'s Life (1998) was Pixar\'s second film; The Lion King (1994) was 2D cel animation.',
    ],
    [
      'Which nonlinear editing system, released in 1989 running on Apple Macintosh II hardware, became the first NLE to see widespread adoption across Hollywood feature and television post-production?',
      ['Avid Media Composer', 'Lightworks', 'EditDroid', 'Final Cut Pro'],
      0,
      'Avid Media Composer (1989) displaced Moviola and KEM flatbed editing as the industry standard, letting editors cut digitized footage nonlinearly on a Mac before conforming to film. EditDroid (1984) was an earlier laserdisc-based system but never achieved comparable market penetration. Final Cut Pro arrived in 1999.',
    ],
    [
      'Which 1992 film was the first feature released theatrically with a Dolby Digital 5.1 surround soundtrack?',
      ['Batman Returns', 'Terminator 2: Judgment Day', 'Jurassic Park', 'Star Trek VI: The Undiscovered Country'],
      0,
      'Batman Returns (1992) was the debut title for Dolby Digital, which encoded six discrete channels of digital audio optically on 35mm print. This let theaters play true 5.1 surround rather than the matrixed four-channel Dolby Stereo used since the late 1970s. Star Trek VI (1991) had tested an early prototype, but Batman Returns was the first commercial release.',
    ],
    [
      'Under the Digital Cinema Initiatives (DCI) specification, what is the pixel resolution of the \'cinema 4K\' digital projection format?',
      ['4096 x 2160', '3840 x 2160', '4096 x 2304', '4320 x 2160'],
      0,
      'DCI defines cinema 4K as 4096x2160, distinct from consumer UHD 4K of 3840x2160. The spec mandates JPEG2000 compression, 12-bit color depth, and XYZ color space. This lets a single digital print run on any compliant projector worldwide instead of shipping physical film reels.',
    ],
    [
      'The \'bullet time\' effect in The Matrix (1999), showing a subject rotating in slow motion while the camera appears to circle them, was achieved primarily using what technique?',
      ['An array of still cameras firing in a timed sequence around the subject', 'A single high-speed film camera on a motorized dolly track', 'Real-time computer-generated doubles composited over live actors', 'A rotating rig of mirrors reflecting one central camera'],
      0,
      'Manex Visual Effects built a rig of roughly 120 still cameras arranged in an arc, firing in timed sequence to capture different angles. Interpolated frames were generated digitally to smooth the sequence into fluid motion. This combined older \'time-slice\' photography with new digital interpolation software. The technique became so associated with the film that \'bullet time\' entered common usage.',
    ],
    [
      'Which digital cinema camera, launched in 2007 at roughly a tenth of the price of comparable competitors, is widely credited with kicking off affordable 4K digital cinematography adoption among independent filmmakers?',
      ['RED One', 'Sony CineAlta F900', 'Panavision Genesis', 'ARRI D-20'],
      0,
      'The RED One (2007) captured raw 4K footage at a price far below competing Sony and Panavision cameras. Its open RAW workflow and modular body attracted independent and mid-budget productions overnight. RED\'s Epic and Weapon lines followed. The Sony CineAlta F900 (2002) was an earlier landmark but only shot HD.',
    ],
    [
      'The Steadicam, a body-mounted rig that made possible smooth handheld tracking shots without a dolly track, was invented by whom?',
      ['Garrett Brown', 'Douglas Trumbull', 'Vilmos Zsigmond', 'Haskell Wexler'],
      0,
      'Garrett Brown developed the Steadicam in the mid-1970s, patenting a spring-arm harness that isolates camera movement from footsteps. It became a defining 1980s cinematography tool, including The Shining (1980), which Brown operated. Before the Steadicam, smooth moving shots required tracks, cranes, or less flexible rigs. Brown later developed concepts that fed into the Skycam aerial system.',
    ],
    [
      'Introduced in 2010, which digital cinema camera rapidly displaced earlier tape-based and CCD systems to become an industry-standard workhorse on Hollywood productions through the 2010s?',
      ['ARRI Alexa', 'Sony F65', 'RED Epic', 'Panavision Genesis'],
      0,
      'The ARRI Alexa (2010) combined a large-format CMOS sensor with color science close to film stock\'s latitude. It quickly became the most-used camera on major studio productions. Its ALEV sensor and Log-C encoding gave wide dynamic range for digital grading and delivery. The Sony F65 (2011) offered higher resolution but never achieved comparable market share.',
    ],
    [
      'The 2008 format war between HD-DVD and Blu-ray for next-generation home video was decided largely in Blu-ray\'s favor after which pivotal event?',
      ['Warner Bros. announced it would release films exclusively on Blu-ray', 'The FCC mandated Blu-ray as the sole legal HD format', 'Netflix announced it would only ship Blu-ray discs by mail', 'Toshiba\'s HD-DVD players were recalled for a fire hazard'],
      0,
      'Warner Bros.\' January 2008 announcement to abandon HD-DVD tipped studio support toward Blu-ray; within weeks Toshiba discontinued HD-DVD. Blu-ray\'s inclusion in PlayStation 3 gave it a large installed base that HD-DVD, backed by Toshiba and Microsoft\'s Xbox 360 add-on, could not match. There was no FCC mandate, as this was a commercial format war.',
    ],
    [
      'Andy Serkis\'s performance as Gollum in The Lord of the Rings: The Two Towers (2002), created via on-set motion capture and CG animation, was produced by which visual effects company?',
      ['Weta Digital', 'Industrial Light & Magic', 'Digital Domain', 'Rhythm & Hues'],
      0,
      'Weta Digital developed the motion-capture pipeline that let Serkis\'s on-set performance drive Gollum\'s digital body and face. This was an early landmark for \'performance capture\' as distinct from motion capture, which had mostly driven crowd simulations or stunt doubles. Weta\'s success with Gollum led studios to trust them with Kong in King Kong (2005) and Avatar\'s Na\'vi.',
    ],
    [
      'In film post-production, what does the term \'digital intermediate\' (DI) refer to?',
      ['Scanning a film\'s footage into digital form for color grading and effects work, before outputting back to film or digital formats', 'The rough assembly edit shown to a studio before visual effects shots are finished', 'A secondary digital audio mix used only for home video releases', 'The intermediate film stock used to duplicate a camera negative'],
      0,
      'The digital intermediate process scans camera negatives or ingests digital files for color grading, effects, and editing before outputting to film or DCP. Before DI, color correction happened photochemically, far less flexible. O Brother, Where Art Thou? (2000) is often cited as the first movie to use a full DI for its distinctive sepia-toned grade.',
    ],
    [
      'IMAX\'s digital projection system, introduced around 2008 as an alternative to the traditional 70mm IMAX film format, uses what projection method?',
      ['Dual synchronized 2K digital projectors', 'A single 8K laser projector with dual-lens optics', 'Triple-strip 35mm film run at high speed', 'A single 4K DLP projector with a wider gate aperture'],
      0,
      'IMAX Digital (2008+) paired two 2K projectors rather than the larger 15/70 film format, letting more theaters install IMAX screens cheaply. This digital rollout expanded IMAX\'s theater count but drew criticism for lacking the sharpness and brightness of true 70mm. IMAX later introduced laser digital projection for closer match. Christopher Nolan has advocated for true 70mm IMAX film.',
    ],
    [
      'Which technology, released by Apple in 2009, became the dominant method by which streaming services like Netflix deliver a video stream that automatically adjusts quality to a viewer\'s fluctuating internet connection?',
      ['HTTP Live Streaming (HLS)', 'Real-Time Streaming Protocol (RTSP)', 'Flash Video (FLV) progressive download', 'BitTorrent-based peer distribution'],
      0,
      'HTTP Live Streaming (2009) breaks video into segments at multiple bitrates, letting players switch based on bandwidth over ordinary HTTP. This adaptive bitrate approach became the backbone of how Netflix, YouTube, and others avoid buffering stalls. Older approaches like RTSP required dedicated servers and didn\'t adapt quality.',
    ],
    [
      'Dolby Atmos, an object-based cinema surround sound format that lets individual sound elements be placed and moved independently of fixed channels, made its theatrical debut with which 2012 film?',
      ['Brave', 'The Avengers', 'The Hobbit: An Unexpected Journey', 'Skyfall'],
      0,
      'Dolby Atmos premiered with Pixar\'s Brave (June 2012), introducing \'sound objects\' positioned anywhere in 3D theater space, not locked to fixed channels like 5.1 or 7.1. A renderer maps these objects onto whatever speakers each auditorium has, so the same mix scales from small multiplex to flagship auditorium. This object-based approach later expanded to home theater and music streaming.',
    ],
  ],
  phd: [
    [
      'Pixar\'s proprietary system used throughout the 1990s to digitally ink, paint, and composite traditionally hand-drawn animation cels—first deployed on The Rescuers Down Under (1990)—was called what?',
      ['CAPS (Computer Animation Production System)', 'SoftImage, a standalone 3D animation package unrelated to 2D cel work', 'Wavefront Explore, an early Unix-based 3D rendering and modeling toolkit', 'Cintel Digital, a telecine scanner used to transfer film to video'],
      0,
      'CAPS, developed by Pixar and Disney, replaced hand-inking and painting cels, letting artists digitally color scanned line drawings and composite layers with programmable camera moves. The Rescuers Down Under (1990) was the first film fully produced with it, enabling complex multiplane effects and cleaner color. CAPS is separate from RenderMan, which handled 3D CG rendering rather than 2D cel compositing.',
    ],
    [
      'Which 1988 film\'s transformation sequence, produced by ILM, is generally credited with popularizing the term \'morphing\' and the digital face/warp technique later used far more elaborately for Terminator 2\'s liquid-metal T-1000?',
      ['Willow', 'The Abyss', 'Indiana Jones and the Last Crusade', 'Star Trek V: The Final Frontier'],
      0,
      'Doug Smythe wrote the morphing software for Willow\'s (1988) sorceress-to-animal transformation, warping and cross-dissolving between creature stages. This became the basis for Terminator 2 (1991)\'s liquid-metal T-1000 morphing. The Abyss (1989) had a \'pseudopod\' CG character but not this morphing technique. Before this, film transformations relied on optical dissolves, which lacked control over which features moved.',
    ],
    [
      'Which computer workstation manufacturer\'s machines, prized through the late 1980s and 1990s for hardware-accelerated 3D graphics, were the standard platform used by ILM, Pixar, and other VFX houses before the 2000s shift to Linux-based PC render farms?',
      ['Silicon Graphics (SGI)', 'Sun Microsystems', 'NeXT', 'Digital Equipment Corporation (DEC)'],
      0,
      'Silicon Graphics workstations, running IRIX, dominated high-end computer graphics through the late 1980s-1990s with dedicated 3D rendering hardware. They powered landmark CG at ILM, Pixar, and Digital Domain, including Jurassic Park\'s dinosaurs and Terminator 2\'s morphing. By the early 2000s, commodity PC hardware running Linux became powerful and cheap enough that studios abandoned SGI for render farms of ordinary PCs.',
    ],
    [
      'The Digital Cinema Package (DCP) format mandated by the DCI specification compresses picture data using which image compression standard?',
      ['JPEG2000', 'H.264/AVC', 'ProRes 4444', 'MPEG-2'],
      0,
      'DCI requires each frame compressed independently as JPEG2000 rather than inter-frame compression like H.264. This frame-independence simplifies projector decoding and avoids motion-compensation artifacts at cinema screen sizes. Each DCP wraps JPEG2000 picture and uncompressed PCM audio in an MXF container with watermarking and AES encryption controlling which theaters can play it. This differs from H.264-based streaming used by Netflix.',
    ],
    [
      'ARRI\'s Alexa camera line offers a genuine \'global shutter\' option on some models, which avoids what specific artifact common with rolling-shutter CMOS sensors?',
      ['Skew or \'jello\' distortion of fast-moving objects captured line-by-line instead of all at once', 'Color moiré patterns produced when fine repeating textures like fabric weaves alias against the sensor\'s pixel grid', 'Elevated shadow noise and reduced low-light detail from smaller sensor photosites', 'Reduced dynamic range and highlight roll-off from limited photosite well depth'],
      0,
      'A rolling-shutter sensor reads rows sequentially, so fast horizontal motion and pans appear skewed or wobbly, an artifact nicknamed \'jello.\' A global shutter exposes every pixel simultaneously, eliminating this skew at the cost of higher sensor complexity and sometimes reduced dynamic range. Most digital cinema cameras default to rolling shutter and manage the artifact through shutter angle choices and stabilization. This tradeoff became a major debate topic as digital cameras replaced film.',
    ],
    [
      'The real-time, in-camera visual effects technique used on The Mandalorian (2019), which replaced traditional greenscreen with photorealistic backgrounds rendered live on a wraparound LED wall, is known by what name?',
      ['StageCraft', 'Volumetric Capture', 'The Volume Engine', 'LightCraft'],
      0,
      'StageCraft (ILM) surrounds actors with a curved LED wall (\'the Volume\') displaying photorealistic environments rendered in real time using Unreal Engine, tracked to match the camera\'s position for correct parallax. This lets cinematographers capture final-quality lighting on actors in-camera, rather than shooting green screen and compositing, which had been standard since the 1990s. The approach drew from techniques developed for live-event visualization and virtual production tools.',
    ],
    [
      'Which VFX studio developed the \'Massive\' software used to simulate autonomous, individually-reacting crowds of thousands of digital characters, first deployed for the battle sequences in The Lord of the Rings: The Two Towers (2002)?',
      ['Weta Digital', 'Digital Domain', 'Framestore', 'Industrial Light & Magic'],
      0,
      'Stephen Regelous built Massive to animate tens of thousands of soldiers or orcs for Lord of the Rings battles, giving each digital agent simple AI logic so crowds moved organically rather than looking copy-pasted. This was a major leap beyond earlier crowd techniques, which layered small numbers of hand-animated cycles. Massive became a standalone commercial product, licensed for crowd and flocking simulation far beyond fantasy films.',
    ],
    [
      'Digital de-aging of Robert De Niro across several decades in The Irishman (2019) primarily relied on what visual effects approach rather than simple digital makeup painted over the actor\'s real face?',
      ['Synchronized witness cameras capturing 3D facial data alongside the primary camera, used to digitally reconstruct a younger face', 'Deepfake-style neural network face-swapping trained on archival footage of the actor\'s younger self, applied frame-by-frame in post', 'Prosthetic silicone makeup combined with color grading and diffusion filters to reduce visible skin texture on camera', 'Dense motion-capture markers dotted across the actor\'s face driving a fully synthetic CG digital double built from scan data'],
      0,
      'For The Irishman, ILM built a custom rig using three witness cameras alongside the primary camera to capture De Niro\'s facial performance from multiple angles and under infrared light, generating enough 3D data to digitally reconstruct and de-age his face without motion capture markers. This differed from typical \'beauty work\' de-aging, which smooths skin with 2D makeup, and from deepfake neural techniques. The approach let actors perform without headgear or markers.',
    ],
    [
      'Chroma-key compositing traditionally favors green or blue screens over other colors primarily because of what technical reason?',
      ['Green and blue are the color channels furthest from human skin tones and least present in most subjects, making them easiest to key out cleanly, while green specifically also allows a cleaner matte due to how digital sensors sample color', 'Green and blue pigments have historically been the cheapest and most lightfast paint colors to manufacture and maintain on large studio backdrops over long shooting schedules', 'Green and blue screens reflect measurably less infrared light, which was believed to reduce heat buildup and overheating risk from nearby tungsten lighting equipment', 'Broadcast standards inherited from the analog television era specifically designate green and blue as the only two hues that keying and encoding hardware can fully remove without introducing visible compression or ringing artifacts'],
      0,
      'Chroma key isolates a background color that appears as little as possible in foreground subjects. Blue and green sit far from typical skin tones, making them easy to isolate and matte. Green is now preferred because most digital sensors have twice as many green photosites as red or blue, giving cleaner green channels. Blue screens were common in the film era because film stock and optical printing handled blue traveling mattes well, but that advantage diminished with digital. Choice also depends on costume and set colors.',
    ],
    [
      'Dolby Vision and HDR10 are both high-dynamic-range video standards, but Dolby Vision is distinguished chiefly by which technical feature?',
      ['Dynamic, scene-by-scene metadata telling the display how to map brightness and color per shot, rather than one static value for the whole program', 'A higher maximum brightness ceiling of 10,000 nits versus HDR10\'s fixed, non-negotiable 1,000-nit limit imposed uniformly across all supported content, displays, and mastering pipelines', 'Native mastering and delivery support for full 12-bit color depth versus HDR10\'s fixed 8-bit depth specified throughout its metadata standard', 'A mandatory 120 frames-per-second playback requirement specifically intended to reduce motion blur visible in very bright highlight regions'],
      0,
      'Both formats use the same PQ transfer function (SMPTE ST 2084) to encode wider brightness ranges than legacy SDR video. HDR10 embeds static metadata covering an entire program, while Dolby Vision carries dynamic metadata that can change scene-to-scene for more precise tone-mapping. This dynamic approach requires Dolby licensing and often a hardware chip, limiting adoption compared to open, royalty-free HDR10. Both support the same theoretical peak brightness ceiling of 10,000 nits.',
    ],
    [
      'For The Hobbit: An Unexpected Journey (2012), Peter Jackson shot and released the film at a high frame rate of 48 frames per second, using which digital cinema camera system to capture that frame rate natively in stereoscopic 3D?',
      ['RED Epic', 'ARRI Alexa Studio', 'Sony F65', 'Panavision Genesis'],
      0,
      'The Hobbit trilogy was shot on RED Epic cameras, chosen because they could natively capture 48fps in stereoscopic 3D. Jackson\'s goal was to reduce the strobing and motion blur that stereoscopic 3D exaggerates at 24fps. However, the higher frame rate\'s ultra-smooth motion drew criticism from audiences who found the \'hyperreal\' look distractingly video-like rather than filmic. This controversy became a cautionary case study for later high-frame-rate releases like Billy Lynn\'s Long Halftime Walk (2016).',
    ],
    [
      'On Avatar (2009), Weta Digital captured detailed facial performance using a lightweight headset camera combined with James Cameron\'s on-set previsualization system, which let him view actors composited into the virtual world through the viewfinder in real time. What was this real-time compositing system called?',
      ['Simulcam', 'Emotion Capture Suite', 'Contour Reality Capture', 'FaceRig'],
      0,
      'On Avatar, actors wore a lightweight headset with a camera capturing expression data, combined with Cameron\'s \'Simulcam\' system on set, letting the director see a real-time composite of actors against their eventual CG Pandoran environment. This was distinct from body motion capture, handled with traditional marker-suit mocap on a separate stage. The facial data drove detailed digital animation for the Na\'vi. The system let Cameron direct digital performances almost as if directing conventional live-action.',
    ],
    [
      'DaVinci Resolve, now the dominant professional color-grading application, was originally built around what kind of hardware-based workflow before becoming a primarily software tool?',
      ['A dedicated hardware color-correction system sold by da Vinci Systems, used mainly for telecine work transferring film to video', 'A plug-in suite bundled exclusively with Avid Media Composer, used specifically for online editorial finishing rather than standalone grading', 'A cloud-based rendering service that streamed color-graded dailies to studio executives and directors overnight for approval', 'A proprietary format for encoding look-up tables directly onto physical film negatives during the printing stage'],
      0,
      'Da Vinci Systems built dedicated hardware color correctors for telecine suites where film was transferred to video for broadcast. Their systems were known for a tactile trackball-based control panel still seen in color grading suites. Blackmagic Design acquired the company (2009), rebuilt the software as DaVinci Resolve, and lowered its price, eventually offering a free version. This drove adoption far beyond color suites into editing and VFX finishing.',
    ],
    [
      'The Academy Color Encoding System (ACES), developed by the Academy of Motion Picture Arts and Sciences and adopted increasingly since the early 2010s, primarily solves what production problem?',
      ['A standardized, device-independent color space letting footage from different cameras be graded consistently, with a predictable path to any output format', 'Compressing raw camera files losslessly using a studio-mandated codec to reduce on-set storage and data-wrangling costs across large multi-camera productions', 'Encrypting dailies footage cryptographically during transit from the set to a remote post-production or visual-effects facility located overseas', 'Automatically matching color, exposure, and white balance between shots cut from different takes of the same scene during the online conform stage'],
      0,
      'Before ACES, cameras recorded in proprietary color spaces, so colorists had to manage conversions for every source before combining footage. ACES defines a large, device-independent working color space plus standardized Transforms for specific cameras and displays. Footage from Alexa, RED, and iPhone can be brought into the same pipeline and output correctly to DCP, broadcast HDR, or future formats. Adoption grew through the 2010s as productions mixed cameras and needed archival masters for future remastering.',
    ],
    [
      'Digital \'wire removal\' and rig removal, which became routine VFX tasks through the 1990s, were primarily enabled by what underlying image-processing technique?',
      ['Frame-by-frame digital paint and clone-stamping, tracked across the shot, layering nearby background pixels over the wire or rig', 'Automatic machine-learning inpainting trained on a very large database of similar background textures, object shapes, and material patterns', 'Optical printing techniques that physically re-exposed a duplicate negative with the wire masked out using a hand-cut matte', 'Chroma-key removal of wires pre-painted in a specific ultraviolet-reflective paint visible only under UV lighting'],
      0,
      'Digital wire removal works by tracking the wire\'s path and painting over it using nearby background pixels, often cloned from unobstructed frames, a manual-but-tool-assisted process. This replaced older photochemical techniques like optical printing, which required re-exposing footage and couldn\'t handle wires crossing complex, moving backgrounds. Wire removal became prominent in wire-fu action choreography popularized by The Matrix (1999) and Crouching Tiger, Hidden Dragon (2000). Only in the 2020s did machine-learning tools start automating this manual paint work.',
    ],
  ],
  professor: [
    [
      'The ASC-CDL (American Society of Cinematographers Color Decision List), a standardized metadata format for portable basic color grading decisions, defines a grading adjustment using exactly which three parameters per color channel, plus one overall value?',
      ['Slope, offset, and power per RGB channel, plus an overall saturation value', 'Gain, gamma, and pedestal per RGB channel, plus an overall contrast value', 'Lift, gamma, and gain per RGB channel, plus an overall exposure value', 'Hue, saturation, and luminance per RGB channel, plus an overall white balance value'],
      0,
      'The ASC-CDL (2006) defines color correction as slope (gain), offset (lift), and power (gamma), applied independently to RGB, plus saturation—a small, portable parameter set versus proprietary controls. This lets color decisions made on set travel as metadata between software packages without baking platform-specific effects, since every compliant tool interprets the parameters identically. \'Lift, gamma, gain\' is a distinct informal vocabulary used in many grading tools\' UI, not the ASC-CDL\'s defined terms.',
    ],
    [
      'Pixar\'s RenderMan renderer, foundational to nearly all major CG feature animation through the 1990s and 2000s, was originally built around which rendering algorithm before later versions added path tracing and ray tracing support?',
      ['REYES (Renders Everything You Ever Saw), a micropolygon-based scanline rendering algorithm', 'Photon mapping combined with irradiance caching to approximate global illumination for offline rendering', 'Radiosity-based finite element rendering solving diffuse light transport across polygon patches', 'Signed distance field ray marching, a technique more associated with procedural and demoscene rendering'],
      0,
      'REYES (Lucasfilm, early 1980s) subdivides surfaces into tiny micropolygons and shades them efficiently in a scanline pipeline rather than full ray-tracing, far faster for feature animation but struggling with accurate reflections and global illumination. RenderMan kept REYES as its core engine for roughly three decades before RenderMan 19 (2014) added RIS, a path-tracing mode. Photon mapping and radiosity are used elsewhere, eventually in later RenderMan modes, but were not REYES\'s original core.',
    ],
    [
      'Texas Instruments\' Digital Light Processing (DLP) chip used in most digital cinema projectors relies on what core mechanical component to form an image?',
      ['A digital micromirror device (DMD): a chip covered in millions of hinged mirrors that tilt to reflect light toward or away from the lens', 'A liquid crystal panel, often using LCOS (liquid crystal on silicon) technology, that rotates the polarization of light passing through each pixel to control how much reaches the lens', 'An array of individually addressable laser diodes fired directly at the screen surface without any intermediate imaging chip', 'A phosphor-coated cathode-ray tube scanning three separate color beams across the screen in raster lines'],
      0,
      'DLP Cinema projectors use a digital micromirror device: a semiconductor chip bearing millions of microscopic mirrors, each corresponding to one pixel, that tilt thousands of times per second between \'on\' and \'off\' positions, with the proportion of on-time controlling perceived brightness. This differs from LCD/LCOS projection, which modulates light by rotating polarization through a liquid crystal layer, and from later laser-illuminated projectors, which use the same DMD chip but replace xenon lamps with laser diodes or phosphor-wheel modules for brighter, more color-accurate illumination. Barco, Christie, and NEC are the three companies licensed to build DLP Cinema projectors using TI\'s chip.',
    ],
    [
      'In JPEG2000, the compression standard mandated for Digital Cinema Packages, image data is transformed using what mathematical technique, distinguishing it from the discrete cosine transform used in JPEG and MPEG?',
      ['The discrete wavelet transform (DWT)', 'The Hadamard transform', 'Fast Fourier transform (FFT) with adaptive quantization', 'Vector quantization against a fixed codebook'],
      0,
      'JPEG2000 replaces JPEG and MPEG\'s discrete cosine transform with a discrete wavelet transform, decomposing an image into multiple resolution sub-bands rather than fixed 8x8 blocks, avoiding blocky macroblock artifacts and allowing smoother quality degradation. This frame-independent approach is why DCI mandated JPEG2000 for cinema: each frame compresses and decompresses on its own, without relying on motion-predicted inter-frame data like H.264, simplifying secure, frame-accurate projection. DCT-based approaches remain standard for consumer broadcast and streaming because they are computationally cheaper and benefit from inter-frame prediction.',
    ],
    [
      'The AV1 video codec, developed by the Alliance for Open Media and increasingly used by major streaming platforms since the late 2010s, was created primarily to solve what problem for the companies backing it?',
      ['Avoiding the licensing royalties charged for HEVC (H.265) by offering a comparably efficient, royalty-free open codec', 'Enabling frame rates above 120fps, which HEVC\'s specification hard-caps at 60fps', 'Supporting 16-bit color depth, which HEVC\'s specification limits to 10-bit', 'Reducing decode latency for live sports broadcast below what any prior codec could achieve'],
      0,
      'HEVC (H.265) became entangled in a fragmented and expensive patent-licensing landscape with multiple competing patent pools, discouraging companies like Google, Netflix, Amazon, and Microsoft from broad adoption. They formed the Alliance for Open Media and released AV1 (finalized 2018) as a comparably efficient, royalty-free alternative deployable without licensing fees. AV1 achieves meaningfully better compression efficiency than H.264 and competes closely with HEVC and VVC (H.266) at higher computational encoding cost, which slowed hardware decoder adoption in cheaper devices. Neither codec\'s adoption was driven by frame-rate or bit-depth ceilings.',
    ],
    [
      'High frame rate cinema formats like 48fps or 60fps face a challenge tied to how frames sample motion: what visual artifact does increasing capture frame rate primarily reduce compared to traditional 24fps?',
      ['Motion blur and strobing on fast-moving subjects or pans, since each frame integrates a shorter slice of time relative to the motion', 'Color banding across smooth gradients caused by insufficient bit depth per encoded frame at higher frame rates', 'Chromatic aberration introduced by camera lens elements that fail to refocus quickly enough between rapidly successive frame exposures at elevated capture rates', 'Rolling-shutter skew specific to CMOS sensor readout timing, which is unrelated to the overall frame rate chosen'],
      0,
      'At 24fps, each frame typically integrates roughly 1/48th of a second of motion with a standard 180-degree shutter angle, long enough to create visible blur or strobing on fine detail. Doubling or more the frame rate shortens the time each frame captures, reducing that blur and yielding a smoother, sharper motion image, the effect Peter Jackson sought with The Hobbit\'s 48fps release. This is unrelated to bit depth, chromatic aberration, or rolling-shutter skew. Critics raised an aesthetic tradeoff: reduced motion blur combined with sharper detail can make footage look uncannily \'smooth\' or \'video-like,\' a reaction rooted in audience conditioning to 24fps as \'filmic.\'',
    ],
    [
      'Volumetric capture rigs, used to generate fully three-dimensional, viewpoint-independent digital recordings of a live performance for VR and virtual production pipelines, typically rely on what core capture setup?',
      ['A large array of synchronized cameras, often dozens to over a hundred, surrounding the subject, whose footage is combined into a per-frame 3D mesh with texture', 'A single high-resolution LIDAR scanner performing a slow rotating sweep around the stationary subject', 'A stereo camera pair combined with an inertial motion-capture suit worn directly by the performer', 'A consumer-grade infrared depth sensor of the same basic type used in motion-gaming hardware, but scaled up significantly in resolution, frame rate, and effective capture range for professional use'],
      0,
      'Volumetric capture studios surround a performer with dozens to over a hundred synchronized cameras, often paired with depth sensors, whose combined footage lets photogrammetry-style software reconstruct a full 3D mesh with correct texture for every frame, producing an asset viewable and relit from any angle in real time. This differs fundamentally from a single-viewpoint depth sensor or LIDAR sweep, neither of which can capture full-body, all-angle geometry of a moving performer in real time. Volumetric capture has been used for VR experiences, some virtual production previs, and limited feature use for background or crowd assets.',
    ],
    [
      'Neural radiance fields (NeRF), a machine-learning technique that reconstructs a photorealistic 3D scene from a set of 2D photographs, have begun seeing early experimental adoption in VFX and virtual production pipelines primarily for what purpose?',
      ['Generating photorealistic, freely-navigable 3D backgrounds or set extensions from ordinary photographs, without manually modeling geometry by hand', 'Automatically generating precisely dialogue-matched lip-sync facial animation from an audio track, using a separately trained neural network model distinct from the scene-reconstruction pipeline', 'Replacing traditional motion-capture markers with skeletal pose estimation from a single unmarked handheld camera', 'Losslessly compressing raw camera footage for cheaper long-term archival storage on studio servers'],
      0,
      'A NeRF trains a small neural network to represent a scene\'s radiance and density as a continuous function learned from photographs taken from different viewpoints, letting a renderer generate photorealistic novel views, including views never photographed. VFX and virtual production teams use it as a faster alternative to traditional photogrammetry and manual environment modeling for background plates, set extensions, or LED-volume content. Early industry experimentation has explored NeRF-derived environments, though as of the mid-2020s the technique remained more common in research than mainstream pipelines, constrained by difficulty editing or relighting compared to traditional 3D assets.',
    ],
    [
      'IMAX\'s laser-illuminated digital projection system, introduced to close the quality gap with traditional 70mm IMAX film, primarily improves on earlier xenon-lamp digital projection in which specific respect?',
      ['Significantly higher achievable contrast ratio and black levels, alongside a wider color gamut, rather than simply higher raw resolution', 'A doubling of maximum frame rate from 60fps to 120fps for smoother motion', 'The ability to project in genuine 15/70 film-equivalent resolution for the first time from a digital source', 'Elimination of the need for a silver-coated projection screen previously required for 3D presentations'],
      0,
      'IMAX\'s laser projection systems, rolled out from the mid-2010s onward, use laser light sources rather than xenon bulbs, allowing dramatically deeper black levels and higher contrast ratios along with a wider, more saturated color gamut. This addresses criticism that earlier digital IMAX projection looked comparatively flat next to genuine 70mm film presentations. IMAX has been explicit that contrast and color gamut, not resolution alone, were the biggest perceptual quality gaps laser projection needed to close. IMAX with Laser still does not project at the frame area of a 15/70 film print, which remains a separate larger-format experience.',
    ],
    [
      'SMPTE ST 2084, the transfer function underlying both HDR10 and Dolby Vision, is more commonly known by what name, referencing its perceptually-based design goal?',
      ['The Perceptual Quantizer (PQ) curve', 'The Hybrid Log-Gamma (HLG) curve', 'The Rec. 709 gamma curve', 'The S-Log3 transfer function'],
      0,
      'The Perceptual Quantizer, standardized as SMPTE ST 2084 in 2014, maps digital code values to absolute brightness levels according to a model of human contrast sensitivity across a much wider luminance range than traditional gamma curves. HDR10 and Dolby Vision content can specify highlights far brighter than SDR\'s roughly 100-nit reference while allocating enough code values to shadow detail. Hybrid Log-Gamma, developed jointly by the BBC and NHK, is a competing HDR transfer function designed to remain backward-compatible with SDR displays without separate metadata, more common in live broadcast HDR than cinema. Rec. 709 is the SDR broadcast standard, and S-Log3 is Sony\'s proprietary on-set log curve, not HDR standards.',
    ],
    [
      'A Dolby Atmos cinema mix can carry how many discrete audio elements at once, combining traditional channel beds with independently positioned sound objects, according to Dolby\'s published specification?',
      ['Up to 128 simultaneous audio elements, a mix of channel-based beds and dynamic objects', 'Up to 64 simultaneous audio elements', 'Up to 256 simultaneous audio elements', 'An unlimited number, constrained only by the mixing engineer\'s available track count'],
      0,
      'Dolby\'s Atmos cinema specification allows up to 128 simultaneous audio elements delivered to a theater, combining traditional bed channels with dynamically positioned objects that the in-theater renderer maps onto whatever speaker configuration that auditorium has, from a modest multiplex to a flagship auditorium with dozens of speakers. This object-based approach lets the exact same Atmos master scale correctly across wildly different room sizes without a separate mix for each configuration, unlike fixed-channel-count formats like Dolby Digital 5.1 or DTS. Because the number is a hard specification limit, mixers must carefully manage element budgets on dense action or music sequences, sometimes collapsing less important sounds into bed channels.',
    ],
    [
      'Weta Digital\'s render farm for Avatar (2009), among the largest dedicated render farms ever assembled for a single film at the time, ran on which operating system?',
      ['Linux, a cluster of Linux-based rendering blades', 'A custom fork of IRIX maintained specifically by Weta', 'Windows Server, chosen for compatibility with Autodesk\'s Maya', 'Solaris, inherited from Weta\'s earlier Sun Microsystems infrastructure'],
      0,
      'By Avatar\'s production, Weta Digital\'s render farm, reported at roughly 40,000 processor cores across thousands of blade servers, ran on Linux, reflecting the broader VFX industry\'s shift away from proprietary Unix workstations like SGI\'s IRIX toward cheap, powerful, flexible Linux-based commodity hardware. This shift, driven by collapsing cost-per-flop of PC-class hardware and maturity of Linux rendering pipelines, let studios scale render capacity far beyond what proprietary Unix hardware of the 1990s could support, directly enabling vastly more complex CG environments. Windows has seen far more limited adoption in back-end render farm infrastructure.',
    ],
    [
      'The Bayer filter pattern, near-universal on single-sensor digital cameras including most cinema cameras, arranges color filters over photosites in what ratio of red, green, and blue?',
      ['One red, two green, and one blue filter per repeating 2x2 block, i.e. twice as many green photosites as red or blue', 'An equal one red, one green, one blue arrangement repeated across a 3x3 block, with the fourth cell left unfiltered for luminance', 'Two red and two blue photosites alternating in checkerboard fashion, with green derived entirely through interpolation from both', 'One red, one green, one blue, and one dedicated white unfiltered photosite per repeating 2x2 block'],
      0,
      'The Bayer pattern, patented by Kodak\'s Bryce Bayer in 1976, uses a repeating 2x2 block containing two green-filtered photosites diagonally opposite each other, plus one red and one blue, because the human eye is most sensitive to green light. Doubling green sampling density improves perceived sharpness and reduces luminance noise relative to an equal RGB split. A camera\'s image processor then demosaics the missing color information at each photosite from its neighbors to reconstruct a full-color image, a step that can introduce characteristic artifacts like color moiré. Some cinema cameras use alternative sensor designs to avoid Bayer demosaicing tradeoffs, but the vast majority remain Bayer-based.',
    ],
    [
      'Gaussian splatting, a real-time 3D scene reconstruction and rendering technique that emerged as a faster alternative to NeRF around 2023, represents a captured scene as what kind of underlying data structure?',
      ['A large collection of translucent 3D Gaussian ellipsoids, each with position, scale, orientation, and color, optimized to reproduce the source photographs', 'A dense voxel grid storing per-voxel opacity and color values sampled uniformly at a fixed spatial resolution throughout the scene', 'A single continuous neural network function queried per pixel at render time, structurally and architecturally identical to NeRF\'s implicit representation but implemented with a smaller, faster network', 'A traditional textured polygon mesh generated via multi-view photogrammetry, with Gaussian blur applied only to distant background geometry'],
      0,
      'Gaussian splatting represents a scene as millions of 3D Gaussian primitives, soft ellipsoidal blobs with position, scale, orientation, opacity, and view-dependent color, rather than a neural network function as in NeRF. It renders novel viewpoints extremely fast by directly \'splatting\' these Gaussians onto the screen rather than requiring dense per-pixel neural network queries. This combination of high visual quality and real-time rendering speed made it attractive for virtual production, game engines, and VFX pipelines exploring photogrammetry-style capture. It can be edited and relit more tractably than a NeRF\'s opaque neural weights. Unlike a polygon mesh, a Gaussian splat scene has no explicit connected surface geometry.',
    ],
    [
      'In broadcast engineering, SMPTE timecode\'s \'drop-frame\' variant exists specifically to reconcile which mismatch?',
      ['NTSC\'s actual 29.97fps frame rate against a timecode counter that counts in whole-number 30fps steps, which would otherwise drift from real elapsed clock time', 'The difference between PAL\'s 25 frames-per-second broadcast standard and film\'s traditional 24fps rate when converting European broadcast masters for North American theatrical and home-video distribution', 'Audio sample-rate drift between 48kHz and 44.1kHz recordings synchronized to the same production timecode track', 'The small offset introduced when a digital cinema package\'s 24fps master is projected at a theater\'s slightly different house frame rate'],
      0,
      'NTSC color video\'s frame rate is not exactly 30fps but 29.97fps, a deliberate reduction introduced in 1953. A timecode counter incrementing in exact whole-number 30-frame-per-second steps would drift noticeably ahead of true wall-clock elapsed time over a long program. Drop-frame timecode compensates by skipping two frame numbers, not two actual frames, every minute except every tenth minute, keeping the timecode display closely synchronized with real elapsed time, which matters for broadcast programs that must hit exact clock times and ad-break durations. Non-drop-frame timecode drifts against real clock time by roughly 3.6 seconds over a full hour, an error broadcast engineering can\'t tolerate for scheduled live television.',
    ],

  ],
  bscba: [
    [
      'What does the abbreviation "fps" stand for in video and cinematography?',
      ['Frames per second', 'Field per sample', 'Frequency of picture signal', 'Film processing standard'],
      0,
      'FPS (frames per second) measures how many individual images display per second, directly affecting perceived motion smoothness and the amount of motion blur visible in video and film.',
    ],
    [
      'Which color space uses red, green, and blue as its three primary color channels?',
      ['RGB', 'CMYK', 'HSL', 'YUV'],
      0,
      'RGB (red, green, blue) is the standard color space for digital cameras and displays, where all visible colors are created by varying the intensity of these three primary channels.',
    ],
    [
      'What is the standard frame rate traditionally used in theatrical cinema?',
      ['24 frames per second', '30 frames per second', '60 frames per second', '120 frames per second'],
      0,
      'Cinema has used 24fps as its standard frame rate since the 1920s when synchronized sound was introduced, and it remains the global cinema standard today.',
    ],
    [
      'What is the primary function of a codec in digital video?',
      ['Compresses and decompresses video data for efficient storage and transmission', 'Measures color accuracy between different cameras', 'Converts film footage to digital format', 'Synchronizes audio with video during playback'],
      0,
      'A codec (coder-decoder) compresses video for storage or transmission and decompresses it for playback, enabling efficient handling of large video files.',
    ],
    [
      'What is chroma key compositing primarily used for?',
      ['Replacing a colored background with another image', 'Correcting unwanted color casts in footage', 'Encrypting sensitive broadcast content', 'Measuring ambient light levels on set'],
      0,
      'Chroma key allows filmmakers to remove a solid-colored background from footage and composite a new one in its place, essential for green-screen and studio visual effects.',
    ],
    [
      'Which aspect ratio best matches the original theatrical cinema standard?',
      ['1.37:1 (Academy)', '1.85:1', '2.39:1 (Anamorphic)', '16:9 (Widescreen)'],
      0,
      'The Academy aspect ratio of 1.37:1 was the standard for theatrical films for decades before widescreen formats became common in the 1950s.',
    ],
    [
      'What is motion capture (mocap) primarily used for in film and animation?',
      ['Recording an actor\'s movement to drive digital character animation', 'Photographing live actors for traditional matte paintings', 'Stabilizing shaky handheld camera footage', 'Detecting artifacts in compressed video streams'],
      0,
      'Motion capture records an actor\'s physical movements using markers, translating them to digital characters while preserving natural performance and movement quality.',
    ],
    [
      'What is the primary purpose of color grading in post-production?',
      ['Adjusting color, brightness, and contrast to achieve a desired visual style', 'Repairing damaged or scratched film from original negatives', 'Removing unwanted objects from background scenery', 'Synchronizing footage from multiple cameras with different sensors'],
      0,
      'Color grading adjusts color, brightness, and contrast to establish mood and visual continuity, transforming raw footage into a polished final image.',
    ],
    [
      'What is a digital intermediate (DI) in film post-production?',
      ['Converting film footage to digital form for color correction and effects', 'The first rough assembly shown to studio executives', 'A safety backup copy of the original camera negative', 'A compressed format used for distributing dailies to remote crew'],
      0,
      'A digital intermediate allows filmmakers to perform digital color correction and effects work before outputting to film or digital delivery formats.',
    ],
    [
      'What best describes resolution in digital video?',
      ['The number of horizontal and vertical pixels in an image', 'The frame rate at which the video is recorded', 'The color bit depth assigned per channel', 'The dynamic range or brightness capability of a camera'],
      0,
      'Resolution refers to pixel dimensions of a video image, such as 1920x1080 or 3840x2160, affecting the sharpness and fine detail visible.',
    ],
    [
      'What is the primary advantage of RAW video formats compared to compressed formats?',
      ['Preserving maximum sensor data for flexibility in post-production color work', 'Achieving faster file transfer speeds over networks', 'Reducing storage requirements through smaller file sizes', 'Better compatibility with consumer playback devices'],
      0,
      'RAW video captures unprocessed sensor data without compression or color processing, preserving maximum information for creative and corrective adjustments.',
    ],
    [
      'What is an LED wall (or "Volume") in virtual production?',
      ['A display showing live-rendered backgrounds behind actors without greenscreen', 'A wall of lights used to brighten and illuminate studio sets', 'A storage device for recording additional simultaneous camera angles', 'A projection screen used to show pre-recorded environmental backgrounds'],
      0,
      'LED walls in virtual production display photorealistic environments rendered in real time, allowing actors and cameras to interact naturally with backgrounds.',
    ],
    [
      'What does the acronym HDR stand for in video technology?',
      ['High Dynamic Range', 'High Definition Recording', 'Horizontal Display Resolution', 'High Density Rendering'],
      0,
      'HDR (High Dynamic Range) video captures a wider brightness range than standard video, displaying more detail in both bright highlights and dark shadows.',
    ],
    [
      'In professional audio, what does PCM stand for?',
      ['Pulse Code Modulation', 'Phase-Corrected Measurement', 'Progressive Codec Mapping', 'Perceptual Color Model'],
      0,
      'PCM (Pulse Code Modulation) is the standard digital audio format that samples sound waves at regular intervals, used in broadcast and professional recording.',
    ],
    [
      'What primarily distinguishes a digital cinema projector from film projection?',
      ['Using electronic imaging technology instead of mechanically projecting film', 'Requiring specially manufactured silver-coated projection screens', 'Being unable to display stereoscopic 3D content', 'Producing less brightness than traditional film projectors'],
      0,
      'Digital cinema projectors use electronic imaging technology like DLP or lasers instead of mechanically projecting film, offering format flexibility and easier distribution.',
    ],
  ],
};
