import type { CategoryContent } from './row.js';

/**
 * Film & TV Technology (1980-Now).
 */

export const SCREEN_TECH: CategoryContent = {
  graduate: [
    [
      'Which 1985 feature film contains the scene widely credited as the first fully computer-generated character to appear in a live-action motion picture?',
      ['Young Sherlock Holmes', 'Tron', 'The Last Starfighter', 'Flight of the Navigator'],
      0,
      'The stained-glass knight that steps out of a church window in Young Sherlock Holmes (1985) was rendered by a small team at Lucasfilm\'s Computer Graphics division (soon to become Pixar), led by John Lasseter, and is generally credited as the first fully CG character composited into a live-action film. Tron (1982) used CGI extensively for vehicles and environments, but not for a character performing among live actors. The shot was only about a minute and a half long but proved a CG figure could be believably lit and composited into real footage, a direct precursor to the studio\'s later work on Jurassic Park. Trivia: the scene\'s animators had to hand-simulate the knight\'s stained-glass segments breaking apart, since no off-the-shelf fracture software existed yet.',
    ],
    [
      'Which 1995 film is recognized as the first feature-length film created entirely with computer-generated imagery, with no traditional cel animation or live-action photography?',
      ['Toy Story', 'Toy Story 2', 'A Bug\'s Life', 'The Lion King'],
      0,
      'Toy Story, released by Pixar in November 1995, was the first fully CGI feature film, rendered on Pixar\'s proprietary RenderMan software over roughly 800,000 machine-hours on a render farm of Sun workstations. It proved CG animation could carry a feature-length narrative and led directly to a ten-picture deal between Pixar and Disney. A Bug\'s Life (1998) was Pixar\'s second film but used a more advanced pipeline; The Lion King (1994) was traditional 2D cel animation. Trivia: Woody was originally written as a much less likeable character before a mid-production rewrite softened him.',
    ],
    [
      'Which nonlinear editing system, released in 1989 running on Apple Macintosh II hardware, became the first NLE to see widespread adoption across Hollywood feature and television post-production?',
      ['Avid Media Composer', 'Lightworks', 'EditDroid', 'Final Cut Pro'],
      0,
      'Avid Media Composer launched in 1989 and by the mid-1990s had displaced Moviola and KEM flatbed film editing as the industry standard, letting editors cut digitized footage nonlinearly on a Mac before conforming the final edit back to film via a negative cut list. EditDroid, built by Lucasfilm in 1984, was an earlier laserdisc-based nonlinear system but never achieved comparable market penetration. Final Cut Pro did not arrive until 1999. Trivia: the first feature film cut entirely on Avid was 1993\'s Lorenzo\'s Oil.',
    ],
    [
      'Which 1992 film was the first feature released theatrically with a Dolby Digital 5.1 surround soundtrack?',
      ['Batman Returns', 'Terminator 2: Judgment Day', 'Jurassic Park', 'Star Trek VI: The Undiscovered Country'],
      0,
      'Batman Returns premiered in June 1992 as the debut title for Dolby\'s new Dolby Digital format, which encoded six discrete channels of digital audio optically alongside the analog soundtrack on the same 35mm print. This let theaters play true 5.1 surround rather than the matrixed four-channel Dolby Stereo used since the late 1970s. Star Trek VI (1991) had tested an early prototype at a single theater, but Batman Returns was the first commercial general release. Trivia: the format needed a separate reader head bolted onto existing projectors, since the digital data was printed between the sprocket holes.',
    ],
    [
      'Under the Digital Cinema Initiatives (DCI) specification, what is the pixel resolution of the \'cinema 4K\' digital projection format?',
      ['4096 x 2160', '3840 x 2160', '4096 x 2304', '4320 x 2160'],
      0,
      'DCI, the consortium of major Hollywood studios that standardized digital projection in the mid-2000s, defines cinema 4K as 4096x2160, distinct from the consumer \'UHD\' 4K of 3840x2160 used in televisions. The spec also defines 2K (2048x1080) and mandates JPEG2000 compression, 12-bit color depth, and an XYZ color space for the Digital Cinema Package sent to theaters. This standardization, finalized around 2005, let a single digital print run on any compliant projector worldwide instead of shipping physical film reels. Trivia: DCI compliance also requires forensic watermarking embedded in every frame to trace leaked screener copies.',
    ],
    [
      'The \'bullet time\' effect in The Matrix (1999), showing a subject rotating in slow motion while the camera appears to circle them, was achieved primarily using what technique?',
      ['An array of still cameras firing in a timed sequence around the subject', 'A single high-speed film camera on a motorized dolly track', 'Real-time computer-generated doubles composited over live actors', 'A rotating rig of mirrors reflecting one central camera'],
      0,
      'Manex Visual Effects built a rig of roughly 120 still cameras arranged in an arc, firing in a precisely timed sequence so each frame captured a slightly different angle of the same frozen instant; interpolated frames were then generated digitally to smooth the sequence into fluid motion. This combined older \'time-slice\' photography, previously used in TV commercials, with new digital interpolation software written specifically for the film. The technique became so associated with the movie that \'bullet time\' entered common usage for any similar slow-motion rotating shot. Trivia: the actors performed against a green screen wearing motion-capture markers so backgrounds could be composited in separately.',
    ],
    [
      'Which digital cinema camera, launched in 2007 at roughly a tenth of the price of comparable competitors, is widely credited with kicking off affordable 4K digital cinematography adoption among independent filmmakers?',
      ['RED One', 'Sony CineAlta F900', 'Panavision Genesis', 'ARRI D-20'],
      0,
      'The RED One, built by RED Digital Cinema, shipped in 2007 capturing raw 4K footage to compact flash cards at a price point far below the Sony and Panavision cinema cameras that had dominated digital production since the early 2000s. Its open RAW workflow and modular body attracted independent and mid-budget productions almost overnight, and RED\'s subsequent Epic and Weapon lines pushed resolution into 5K, 6K, and 8K territory. The Sony CineAlta F900, used for Star Wars: Episode II in 2002, had been an earlier landmark but only shot standard HD. Trivia: RED\'s camera lineup is famously named after weapons of increasing size, from \'Scarlet\' to \'Epic\' to \'Weapon\' to \'Monstro.\'',
    ],
    [
      'The Steadicam, a body-mounted rig that made possible smooth handheld tracking shots without a dolly track, was invented by whom?',
      ['Garrett Brown', 'Douglas Trumbull', 'Vilmos Zsigmond', 'Haskell Wexler'],
      0,
      'Garrett Brown developed the Steadicam in the mid-1970s, patenting a spring-arm harness system that isolates camera movement from the operator\'s footsteps, and it became a defining tool of 1980s cinematography, including the long tracking shots of The Shining (1980), which Brown operated himself. Before the Steadicam, smooth moving shots required tracks, cranes, or far less flexible rigs. Brown later developed camera-stabilization concepts that fed into the Skycam aerial system seen at sporting events. Trivia: Brown personally trained Stanley Kubrick\'s crew on the device for The Shining\'s corridor and hedge-maze sequences.',
    ],
    [
      'Introduced in 2010, which digital cinema camera rapidly displaced earlier tape-based and CCD systems to become an industry-standard workhorse on Hollywood productions through the 2010s?',
      ['ARRI Alexa', 'Sony F65', 'RED Epic', 'Panavision Genesis'],
      0,
      'The ARRI Alexa, released in 2010, combined a single large-format CMOS sensor with color science and highlight handling that cinematographers found close to film stock\'s forgiving latitude, and it quickly became the most-used camera on major studio productions through the following decade. Its ALEV sensor and Log-C encoding gave a wide dynamic range suited to both digital-intermediate grading and broadcast delivery. Competing systems like the Sony F65 (2011) offered higher raw resolution but never achieved comparable market share. Trivia: many cinematographers kept shooting on the original Alexa Classic sensor for years after ARRI released higher-resolution successors, because of how that specific sensor rendered skin tones.',
    ],
    [
      'The 2008 format war between HD-DVD and Blu-ray for next-generation home video was decided largely in Blu-ray\'s favor after which pivotal event?',
      ['Warner Bros. announced it would release films exclusively on Blu-ray', 'The FCC mandated Blu-ray as the sole legal HD format', 'Netflix announced it would only ship Blu-ray discs by mail', 'Toshiba\'s HD-DVD players were recalled for a fire hazard'],
      0,
      'Warner Bros.\' January 2008 announcement that it would abandon HD-DVD and release future titles exclusively on Blu-ray, made just before that year\'s Consumer Electronics Show, tipped studio support decisively toward Sony\'s format; within weeks Toshiba discontinued HD-DVD hardware. Blu-ray\'s inclusion in every PlayStation 3 console had already given it a large installed base that HD-DVD, backed mainly by Toshiba and Microsoft\'s Xbox 360 add-on drive, could not match. There was no FCC mandate involved, since this was a commercial format war rather than a broadcast standard. Trivia: Blu-ray\'s name deliberately drops the \'e\' from \'blue\' because \'blue ray\' alone was deemed ineligible for trademark in some jurisdictions.',
    ],
    [
      'Andy Serkis\'s performance as Gollum in The Lord of the Rings: The Two Towers (2002), created via on-set motion capture and CG animation, was produced by which visual effects company?',
      ['Weta Digital', 'Industrial Light & Magic', 'Digital Domain', 'Rhythm & Hues'],
      0,
      'Weta Digital, the New Zealand studio co-founded by Peter Jackson and Richard Taylor, developed the motion-capture pipeline that let Serkis\'s on-set performance drive Gollum\'s digital body and face, blending it with hand-animated refinement rather than a pure motion-capture puppet. This was an early landmark for \'performance capture\' as distinct from earlier motion capture, which had mostly driven crowd simulations or stunt doubles rather than a lead character. Weta\'s success with Gollum directly led studios to trust the same team with Kong in King Kong (2005) and later Avatar\'s Na\'vi. Trivia: Serkis often performed his motion-capture scenes on set alongside the live actors, on his knees to match Gollum\'s smaller stature, rather than in an isolated capture volume.',
    ],
    [
      'In film post-production, what does the term \'digital intermediate\' (DI) refer to?',
      ['Scanning a film\'s footage into digital form for color grading and effects work, before outputting back to film or digital formats', 'The rough assembly edit shown to a studio before visual effects shots are finished', 'A secondary digital audio mix used only for home video releases', 'The intermediate film stock used to duplicate a camera negative'],
      0,
      'The digital intermediate process, which became standard through the 2000s, scans a movie\'s original camera negative or ingests native digital camera files into a high-resolution digital format so that color grading, effects compositing, and even some editing decisions can happen digitally before the final image is output to a new film print or a digital cinema package. Before DI, color correction happened photochemically by exposing successive film generations, a far less flexible and precise process. O Brother, Where Art Thou? (2000) is often cited as the first movie to use a full-length digital intermediate for its distinctive sepia-toned grade. Trivia: DI workflows also enabled \'digital dailies,\' letting a production see color-corrected footage the same day it was shot rather than waiting on a film lab.',
    ],
    [
      'IMAX\'s digital projection system, introduced around 2008 as an alternative to the traditional 70mm IMAX film format, uses what projection method?',
      ['Dual synchronized 2K digital projectors', 'A single 8K laser projector with dual-lens optics', 'Triple-strip 35mm film run at high speed', 'A single 4K DLP projector with a wider gate aperture'],
      0,
      'IMAX Digital, rolled out from 2008 onward, paired two 2K digital projectors running in tandem rather than the far larger 15/70 film format that had defined IMAX since 1970, letting far more theaters install IMAX-branded screens cheaply without the cost and logistics of enormous film prints. This digital rollout massively expanded IMAX\'s theater count worldwide but drew criticism from some filmmakers and audiences for lacking the sharpness and brightness of true 70mm presentations, prompting IMAX to later introduce laser digital projection for a closer match. Christopher Nolan has been a persistent advocate for shooting and exhibiting on true 70mm IMAX film specifically because of this gap. Trivia: an actual IMAX 15/70 film frame is roughly ten times the area of a standard 35mm frame.',
    ],
    [
      'Which technology, released by Apple in 2009, became the dominant method by which streaming services like Netflix deliver a video stream that automatically adjusts quality to a viewer\'s fluctuating internet connection?',
      ['HTTP Live Streaming (HLS)', 'Real-Time Streaming Protocol (RTSP)', 'Flash Video (FLV) progressive download', 'BitTorrent-based peer distribution'],
      0,
      'HTTP Live Streaming, introduced by Apple in 2009 primarily for iOS compatibility, breaks video into small segments encoded at multiple bitrates and lets the player switch between them in real time based on measured bandwidth, all delivered over ordinary HTTP rather than a specialized streaming protocol. This adaptive bitrate approach, alongside the competing but structurally similar MPEG-DASH standard, became the backbone of how Netflix, YouTube, and other platforms avoid buffering stalls on variable connections. Older approaches like RTSP required dedicated streaming servers and didn\'t adapt quality automatically. Trivia: HLS\'s reliance on ordinary web servers and standard HTTP caching is a major reason it could be delivered cheaply through generic content delivery networks rather than specialized streaming infrastructure.',
    ],
    [
      'Dolby Atmos, an object-based cinema surround sound format that lets individual sound elements be placed and moved independently of fixed channels, made its theatrical debut with which 2012 film?',
      ['Brave', 'The Avengers', 'The Hobbit: An Unexpected Journey', 'Skyfall'],
      0,
      'Dolby Atmos premiered with Pixar\'s Brave in June 2012 at Hollywood\'s El Capitan Theatre, introducing \'sound objects\' that can be positioned anywhere in a three-dimensional theater space, including overhead speakers, rather than being locked to a fixed number of channels like the 5.1 or 7.1 systems that preceded it. A renderer at each theater dynamically maps these objects onto however many speakers that specific auditorium has installed, so the same mix scales from a small multiplex to a massive flagship auditorium. This object-based approach later expanded into home theater receivers and, eventually, into music streaming as \'Dolby Atmos Music.\' Trivia: Atmos mixes can carry well over a hundred discrete audio objects plus traditional bed channels simultaneously.',
    ],
  ],
  phd: [
    [
      'Pixar\'s proprietary system used throughout the 1990s to digitally ink, paint, and composite traditionally hand-drawn animation cels—first deployed on The Rescuers Down Under (1990)—was called what?',
      ['CAPS (Computer Animation Production System)', 'SoftImage, a standalone 3D animation package unrelated to 2D cel work', 'Wavefront Explore, an early Unix-based 3D rendering and modeling toolkit', 'Cintel Digital, a telecine scanner used to transfer film to video'],
      0,
      'CAPS, developed jointly by Pixar and Disney feature animation, replaced the traditional photochemical process of inking and painting cels by hand and photographing them under a camera, letting artists digitally color scanned line drawings and composite multiple layers with programmable camera moves. The Rescuers Down Under (1990) was the first film fully produced with it, and it let Disney\'s subsequent renaissance-era films achieve more complex multiplane camera effects and cleaner color than hand-painted cels allowed. CAPS is a separate lineage from Pixar\'s RenderMan, which handled fully 3D CG rendering rather than 2D cel compositing. Trivia: Beauty and the Beast\'s ballroom sequence used CAPS to blend a fully 3D-modeled, camera-tracked room with traditionally animated 2D characters.',
    ],
    [
      'Which 1988 film\'s transformation sequence, produced by ILM, is generally credited with popularizing the term \'morphing\' and the digital face/warp technique later used far more elaborately for Terminator 2\'s liquid-metal T-1000?',
      ['Willow', 'The Abyss', 'Indiana Jones and the Last Crusade', 'Star Trek V: The Final Frontier'],
      0,
      'ILM programmer Doug Smythe wrote the morphing software used for Willow\'s (1988) sorceress-to-animal transformation sequence, warping and cross-dissolving between a sequence of photographed creature stages; this became the basis for the far more elaborate liquid-metal morphing in Terminator 2: Judgment Day (1991), where the same underlying warp-and-blend technique let the T-1000 appear to melt between forms. The Abyss (1989), also an ILM show, contributed the \'pseudopod\' water-tentacle CG character but not this specific morphing technique. Before this, film transformations relied on optical dissolves or makeup-based lap dissolves, which lacked control over exactly which features moved where. Trivia: the term \'morphing\' entered wider popular use largely because of Michael Jackson\'s 1991 \'Black or White\' music video, which used the same ILM-derived technique to blend faces of different people and dancers.',
    ],
    [
      'Which computer workstation manufacturer\'s machines, prized through the late 1980s and 1990s for hardware-accelerated 3D graphics, were the standard platform used by ILM, Pixar, and other VFX houses before the 2000s shift to Linux-based PC render farms?',
      ['Silicon Graphics (SGI)', 'Sun Microsystems', 'NeXT', 'Digital Equipment Corporation (DEC)'],
      0,
      'Silicon Graphics workstations, running the IRIX operating system, dominated high-end computer graphics through the late 1980s and 1990s because of dedicated hardware for 3D rendering and texture mapping, and they were the machines behind landmark CG work at ILM, Pixar, and Digital Domain, including Jurassic Park\'s dinosaurs and Terminator 2\'s morphing effects. By the early 2000s, commodity PC hardware running Linux had become powerful and cheap enough that studios abandoned proprietary SGI hardware for render farms of ordinary rack-mounted PCs, dramatically lowering the cost of large-scale CG production. Sun Microsystems workstations were used in some studios but were not as closely identified with the graphics-specific hardware acceleration SGI offered. Trivia: SGI\'s IRIX-running \'Indigo\' and \'Onyx\' machines appeared as on-screen prop computers in numerous 1990s films specifically because studios had them lying around.',
    ],
    [
      'The Digital Cinema Package (DCP) format mandated by the DCI specification compresses picture data using which image compression standard?',
      ['JPEG2000', 'H.264/AVC', 'ProRes 4444', 'MPEG-2'],
      0,
      'DCI\'s 2005 specification requires each frame of a digital cinema package to be compressed independently as a JPEG2000 image rather than using inter-frame video compression like H.264 or MPEG-2, common in broadcast and home video; this frame-independence simplifies projector decoding and avoids motion-compensation artifacts that heavily compressed inter-frame formats can show at cinema screen sizes. Each DCP also wraps its JPEG2000 picture essence and uncompressed PCM audio inside an MXF container, with forensic watermarking and AES encryption keys controlling which theaters and screening windows can decrypt and play the content. This is a very different pipeline from the H.264-based streaming delivery used by services like Netflix. Trivia: because JPEG2000 uses wavelet compression rather than the discrete cosine transform blocks of JPEG/MPEG, DCP frames don\'t show the blocky macroblocking artifacts characteristic of over-compressed streaming video.',
    ],
    [
      'ARRI\'s Alexa camera line offers a genuine \'global shutter\' option on some models, which avoids what specific artifact common with rolling-shutter CMOS sensors?',
      ['Skew or \'jello\' distortion of fast-moving objects captured line-by-line instead of all at once', 'Color moiré patterns produced when fine repeating textures like fabric weaves alias against the sensor\'s pixel grid', 'Elevated shadow noise and reduced low-light detail from smaller sensor photosites', 'Reduced dynamic range and highlight roll-off from limited photosite well depth'],
      0,
      'A rolling-shutter sensor reads out image rows sequentially rather than capturing the entire frame at a single instant, so fast horizontal motion, camera whip pans, or high-frequency vibration can appear skewed or wobbly, an artifact nicknamed \'jello.\' A global shutter sensor exposes every pixel simultaneously, eliminating this skew at the cost of typically higher sensor complexity and sometimes reduced dynamic range or increased noise compared to an equivalent rolling-shutter design, which is why most digital cinema cameras, including most Alexa models, still default to rolling shutter and manage the artifact through shutter angle choices and stabilization instead. This tradeoff became a major topic of debate as digital cameras replaced film, since film cameras had no rolling-shutter equivalent artifact at all. Trivia: rolling shutter skew is also why some early DSLR video famously showed vertical structures like flagpoles leaning at an angle during fast pans.',
    ],
    [
      'The real-time, in-camera visual effects technique used on The Mandalorian (2019), which replaced traditional greenscreen with photorealistic backgrounds rendered live on a wraparound LED wall, is known by what name?',
      ['StageCraft', 'Volumetric Capture', 'The Volume Engine', 'LightCraft'],
      0,
      'StageCraft, developed by Industrial Light & Magic for The Mandalorian, surrounds actors with a curved LED wall (colloquially \'the Volume\') displaying photorealistic environments rendered in real time using Unreal Engine\'s game-engine technology, tracked to match the camera\'s exact position so the background has correct parallax and perspective as the camera moves. This let cinematographers capture final-quality lighting interacting naturally on actors and reflective surfaces in-camera, rather than shooting against a flat green screen and compositing a background afterward, which had been standard practice since the 1990s. The approach drew heavily on techniques originally developed for live-event visualization and virtual production previsualization tools. Trivia: because the LED wall itself illuminates the actors, StageCraft largely eliminates the \'green spill\' problem that traditionally required actors\' skin and costumes to be carefully lit and later color-corrected to remove tinting from a green or blue screen.',
    ],
    [
      'Which VFX studio developed the \'Massive\' software used to simulate autonomous, individually-reacting crowds of thousands of digital characters, first deployed for the battle sequences in The Lord of the Rings: The Two Towers (2002)?',
      ['Weta Digital', 'Digital Domain', 'Framestore', 'Industrial Light & Magic'],
      0,
      'Weta Digital\'s Stephen Regelous built Massive specifically to animate tens of thousands of individual soldiers or orcs for the Lord of the Rings battle sequences, giving each digital agent its own simple AI logic so that crowds moved with organic variation rather than looking like copy-pasted, synchronized extras. This was a major leap beyond earlier crowd techniques, which typically layered small numbers of hand-animated cycles across a background. Massive became a standalone commercial product afterward, licensed by other studios for crowd and flocking simulation work far beyond fantasy battle films, including sports broadcasts and other franchises\' effects work. Trivia: Massive\'s agent-based logic was directly inspired by earlier flocking-simulation research used to animate bat swarms in Batman Returns (1992).',
    ],
    [
      'Digital de-aging of Robert De Niro across several decades in The Irishman (2019) primarily relied on what visual effects approach rather than simple digital makeup painted over the actor\'s real face?',
      ['Synchronized witness cameras capturing 3D facial data alongside the primary camera, used to digitally reconstruct a younger face', 'Deepfake-style neural network face-swapping trained on archival footage of the actor\'s younger self, applied frame-by-frame in post', 'Prosthetic silicone makeup combined with color grading and diffusion filters to reduce visible skin texture on camera', 'Dense motion-capture markers dotted across the actor\'s face driving a fully synthetic CG digital double built from scan data'],
      0,
      'For The Irishman, ILM built a custom rig using three additional witness cameras alongside the primary camera to capture De Niro\'s facial performance from multiple angles and under infrared light even in normal lighting conditions, generating enough 3D data to digitally reconstruct and de-age his face without motion capture markers or a fully synthetic digital double replacing his performance. This differed from typical \'beauty work\' de-aging, which often just smooths skin texture with 2D digital makeup, and from deepfake neural techniques, which use machine-learning models trained on archival footage rather than a dedicated on-set capture rig. The approach let De Niro, Pesci, and Pacino act without headgear or facial markers, preserving natural performance while giving VFX artists rich reference data to rebuild younger faces over months of post-production. Trivia: the custom camera rig was reportedly nicknamed \'the three-headed monster\' on set because of its bulky triple-camera housing.',
    ],
    [
      'Chroma-key compositing traditionally favors green or blue screens over other colors primarily because of what technical reason?',
      ['Green and blue are the color channels furthest from human skin tones and least present in most subjects, making them easiest to key out cleanly, while green specifically also allows a cleaner matte due to how digital sensors sample color', 'Green and blue pigments have historically been the cheapest and most lightfast paint colors to manufacture and maintain on large studio backdrops over long shooting schedules', 'Green and blue screens reflect measurably less infrared light, which was believed to reduce heat buildup and overheating risk from nearby tungsten lighting equipment', 'Broadcast standards inherited from the analog television era specifically designate green and blue as the only two hues that keying and encoding hardware can fully remove without introducing visible compression or ringing artifacts'],
      0,
      'Chroma key relies on isolating a background color that appears as little as possible in foreground subjects, and blue and green sit far from typical skin tones, making them statistically easy to isolate and matte out cleanly; green is now generally preferred over blue because most digital camera sensors use a Bayer filter pattern with twice as many green photosites as red or blue, giving the green channel less noise and finer detail to build a clean matte from. Blue screens remained common in the film era partly because blue-sensitive film stock and optical printing processes handled blue traveling mattes well, but that advantage diminished with digital capture. Choice of key color also depends on costume and set colors already used in a scene, since a green-costumed actor still needs a blue screen instead. Trivia: modern electronic chroma keying traces back to 1950s-60s television engineering, decades before the same traveling-matte principle appeared in earlier optical film compositing.',
    ],
    [
      'Dolby Vision and HDR10 are both high-dynamic-range video standards, but Dolby Vision is distinguished chiefly by which technical feature?',
      ['Dynamic, scene-by-scene metadata telling the display how to map brightness and color per shot, rather than one static value for the whole program', 'A higher maximum brightness ceiling of 10,000 nits versus HDR10\'s fixed, non-negotiable 1,000-nit limit imposed uniformly across all supported content, displays, and mastering pipelines', 'Native mastering and delivery support for full 12-bit color depth versus HDR10\'s fixed 8-bit depth specified throughout its metadata standard', 'A mandatory 120 frames-per-second playback requirement specifically intended to reduce motion blur visible in very bright highlight regions'],
      0,
      'Both formats use the same PQ transfer function (SMPTE ST 2084) to encode a wider brightness range than legacy SDR video, but HDR10 embeds a single static set of metadata values covering an entire program, while Dolby Vision carries dynamic metadata that can change scene-to-scene or even frame-to-frame, letting a display\'s tone-mapping adjust more precisely as a film cuts between a dim interior and a bright exterior. This dynamic approach requires Dolby licensing and often a hardware chip in the display, which is why Dolby Vision adoption has been more limited than the open, royalty-free HDR10 standard. Both standards support the same theoretical peak brightness ceiling of 10,000 nits in their metadata fields, even though no consumer display comes close to reaching it. Trivia: Samsung championed a rival dynamic-metadata format called HDR10+, partly to avoid paying Dolby\'s Dolby Vision licensing fees.',
    ],
    [
      'For The Hobbit: An Unexpected Journey (2012), Peter Jackson shot and released the film at a high frame rate of 48 frames per second, using which digital cinema camera system to capture that frame rate natively in stereoscopic 3D?',
      ['RED Epic', 'ARRI Alexa Studio', 'Sony F65', 'Panavision Genesis'],
      0,
      'The Hobbit trilogy was shot on RED Epic cameras, chosen partly because they could natively capture at 48 frames per second in stereoscopic 3D rigs without the frame-rate limitations some competing cinema cameras had at the time. Jackson\'s goal was to reduce the strobing and motion blur that stereoscopic 3D exaggerates at 24fps, but the higher frame rate\'s ultra-smooth motion drew significant criticism from audiences who found the \'hyperreal\' look distractingly close to video rather than film. This controversy became a cautionary case study cited whenever later films considered high-frame-rate release, including Ang Lee\'s Billy Lynn\'s Long Halftime Walk (2016) and Gemini Man (2019), both shot at even higher frame rates. Trivia: most theaters actually projected The Hobbit at standard 24fps anyway, since 48fps projection required specially upgraded digital projectors that only a minority of cinemas worldwide had installed.',
    ],
    [
      'On Avatar (2009), Weta Digital captured detailed facial performance using a lightweight headset camera combined with James Cameron\'s on-set previsualization system, which let him view actors composited into the virtual world through the viewfinder in real time. What was this real-time compositing system called?',
      ['Simulcam', 'Emotion Capture Suite', 'Contour Reality Capture', 'FaceRig'],
      0,
      'On Avatar, actors wore a lightweight headset with a small camera positioned in front of their face capturing detailed expression data, combined on set with James Cameron\'s \'Simulcam\' system, which let the director see a real-time composite of actors against their eventual CG Pandoran environment through the viewfinder while filming. This was distinct from body motion capture, handled with traditional marker-suit mocap on a separate stage, and the facial data was later used to drive far more detailed digital facial animation for the Na\'vi than earlier performance-capture films like The Polar Express had achieved. The combined system let Cameron direct actors\' digital performances almost as if directing conventional live-action, checking composition and blocking against the virtual world in real time. Trivia: Weta had to build entirely new muscle-and-skin simulation software, since the Na\'vi\'s proportions meant human facial capture data couldn\'t be mapped onto them using standard techniques.',
    ],
    [
      'DaVinci Resolve, now the dominant professional color-grading application, was originally built around what kind of hardware-based workflow before becoming a primarily software tool?',
      ['A dedicated hardware color-correction system sold by da Vinci Systems, used mainly for telecine work transferring film to video', 'A plug-in suite bundled exclusively with Avid Media Composer, used specifically for online editorial finishing rather than standalone grading', 'A cloud-based rendering service that streamed color-graded dailies to studio executives and directors overnight for approval', 'A proprietary format for encoding look-up tables directly onto physical film negatives during the printing stage'],
      0,
      'Da Vinci Systems originally built dedicated hardware color correctors used chiefly in telecine suites, where film was transferred to video for broadcast, and their systems became known for a tactile trackball-based control panel that remains a recognizable feature of color grading suites today. Blackmagic Design acquired the company in 2009, rebuilt the underlying software as DaVinci Resolve, and aggressively lowered its price, eventually offering a capable free version, which drove its adoption far beyond dedicated color suites into editing and even VFX finishing. This shift from expensive proprietary hardware toward affordable, feature-rich software mirrors a broader trend across post-production tools from the 2000s onward. Trivia: Resolve\'s node-based grading structure, where color operations are chained through connected nodes rather than a single linear stack of adjustments, remains one of its most distinguishing features against competitors like Adobe\'s Lumetri.',
    ],
    [
      'The Academy Color Encoding System (ACES), developed by the Academy of Motion Picture Arts and Sciences and adopted increasingly since the early 2010s, primarily solves what production problem?',
      ['A standardized, device-independent color space letting footage from different cameras be graded consistently, with a predictable path to any output format', 'Compressing raw camera files losslessly using a studio-mandated codec to reduce on-set storage and data-wrangling costs across large multi-camera productions', 'Encrypting dailies footage cryptographically during transit from the set to a remote post-production or visual-effects facility located overseas', 'Automatically matching color, exposure, and white balance between shots cut from different takes of the same scene during the online conform stage'],
      0,
      'Before ACES, different cameras, and even different firmware versions of the same camera, recorded color in their own proprietary color spaces and gammas, meaning colorists had to individually manage conversions for every source before combining footage in a single grade, with results that weren\'t always reproducible across facilities or years later during a remaster. ACES defines a large, device-independent working color space plus standardized Input and Output Device Transforms for specific cameras and displays, so footage from an Alexa, a RED, and an iPhone can be brought into the same color-managed pipeline and output correctly to a cinema DCP, a broadcast HDR master, or a future format not yet invented. Adoption grew through the 2010s as productions increasingly mixed camera systems and needed archival masters that would remain viable for future remastering. Trivia: ACES uses an unusually wide color space, AP0, that includes far more colors than any camera or display can actually capture or reproduce, specifically to future-proof the standard.',
    ],
    [
      'Digital \'wire removal\' and rig removal, which became routine VFX tasks through the 1990s, were primarily enabled by what underlying image-processing technique?',
      ['Frame-by-frame digital paint and clone-stamping, tracked across the shot, layering nearby background pixels over the wire or rig', 'Automatic machine-learning inpainting trained on a very large database of similar background textures, object shapes, and material patterns', 'Optical printing techniques that physically re-exposed a duplicate negative with the wire masked out using a hand-cut matte', 'Chroma-key removal of wires pre-painted in a specific ultraviolet-reflective paint visible only under UV lighting'],
      0,
      'Digital wire and rig removal works by tracking the wire or rig\'s path frame by frame and painting over it using nearby background pixels, often cloned and warped from a few frames earlier or later where the area is unobstructed, a manual-but-tool-assisted process rather than an automated one for most of this technology\'s history. This replaced older, far more limited photochemical techniques like careful optical printing to mask a visible wire, which required re-exposing footage and couldn\'t handle a wire crossing over complex, moving backgrounds. Wire removal became especially prominent in wire-fu action choreography popularized internationally by The Matrix (1999) and Crouching Tiger, Hidden Dragon (2000), where visible support rigs needed to vanish from nearly every actor\'s harness shot. Only in the 2020s did machine-learning-assisted inpainting tools start meaningfully automating parts of this previously fully manual paint work. Trivia: some early wire-removal work was actually done practically on set using thinner, near-invisible wire gauges combined with backlighting tricks, with digital paintwork only cleaning up what remained visible.',
    ],
  ],
  professor: [
    [
      'The ASC-CDL (American Society of Cinematographers Color Decision List), a standardized metadata format for portable basic color grading decisions, defines a grading adjustment using exactly which three parameters per color channel, plus one overall value?',
      ['Slope, offset, and power per RGB channel, plus an overall saturation value', 'Gain, gamma, and pedestal per RGB channel, plus an overall contrast value', 'Lift, gamma, and gain per RGB channel, plus an overall exposure value', 'Hue, saturation, and luminance per RGB channel, plus an overall white balance value'],
      0,
      'The ASC-CDL, standardized in 2006 by the ASC\'s Technology Committee, defines a primary color correction as slope (multiplying values, akin to gain), offset (adding a value, akin to lift), and power (a gamma-like exponent), applied independently to red, green, and blue, plus a single saturation adjustment, deliberately a small, portable parameter set rather than every tool\'s proprietary grading controls. This lets a color decision made on set or in an editorial suite travel as simple metadata between different software packages without baking in a platform-specific effect, since every ASC-CDL-compliant tool interprets slope/offset/power/saturation identically. \'Lift, gamma, gain\' is a very similar but distinct informal color-correction vocabulary used inside many grading tools\' UI, not the ASC-CDL\'s own defined terms. Trivia: ASC-CDL values are commonly exchanged as a simple XML file, letting a studio\'s DIT hand off looks to an offline editor with no proprietary software dependency at all.',
    ],
    [
      'Pixar\'s RenderMan renderer, foundational to nearly all major CG feature animation through the 1990s and 2000s, was originally built around which rendering algorithm before later versions added path tracing and ray tracing support?',
      ['REYES (Renders Everything You Ever Saw), a micropolygon-based scanline rendering algorithm', 'Photon mapping combined with irradiance caching to approximate global illumination for offline rendering', 'Radiosity-based finite element rendering solving diffuse light transport across polygon patches', 'Signed distance field ray marching, a technique more associated with procedural and demoscene rendering'],
      0,
      'REYES, developed at Lucasfilm\'s computer graphics group in the early 1980s and detailed in a 1987 paper, subdivides surfaces into tiny \'micropolygons\' roughly the size of a pixel and shades them efficiently in a scanline pipeline rather than a full ray-traced one, dramatically faster than contemporary ray tracers for the richly-shaded surfaces feature animation demanded, at the cost of struggling with physically accurate reflections and global illumination. RenderMan retained REYES as its core engine for roughly three decades of Pixar and licensed third-party productions before RenderMan 19 (2014) added RIS, a true path-tracing mode, as physically-based rendering became computationally feasible for feature production. Photon mapping and radiosity are legitimate global-illumination techniques used elsewhere in the industry, and eventually inside RenderMan\'s later modes, but were not REYES\'s original core algorithm. Trivia: the REYES paper\'s authors included Pixar co-founders Loren Carpenter and Robert Cook, and the algorithm\'s name is a deliberate pun unrelated to computer graphics.',
    ],
    [
      'Texas Instruments\' Digital Light Processing (DLP) chip used in most digital cinema projectors relies on what core mechanical component to form an image?',
      ['A digital micromirror device (DMD): a chip covered in millions of hinged mirrors that tilt to reflect light toward or away from the lens', 'A liquid crystal panel, often using LCOS (liquid crystal on silicon) technology, that rotates the polarization of light passing through each pixel to control how much reaches the lens', 'An array of individually addressable laser diodes fired directly at the screen surface without any intermediate imaging chip', 'A phosphor-coated cathode-ray tube scanning three separate color beams across the screen in raster lines'],
      0,
      'DLP Cinema projectors, dominant since their commercial rollout in the early 2000s, use a digital micromirror device: a semiconductor chip bearing millions of microscopic mirrors, each corresponding to one pixel, that tilt thousands of times per second between an \'on\' position reflecting light through the lens and an \'off\' position reflecting it away, with the proportion of on-time per mirror controlling perceived brightness. This differs fundamentally from LCD/LCOS projection, which modulates light by rotating its polarization through a liquid crystal layer rather than physically tilting mirrors, and from later laser-illuminated projectors, which still typically use the same DMD imaging chip but replace the xenon lamp with laser diodes or phosphor-wheel laser modules for brighter, more color-accurate illumination. Barco, Christie, and NEC are the three companies licensed to build DLP Cinema projectors using TI\'s chip. Trivia: a single cinema DMD chip contains well over two million mirrors, each smaller than a human red blood cell.',
    ],
    [
      'In JPEG2000, the compression standard mandated for Digital Cinema Packages, image data is transformed using what mathematical technique, distinguishing it from the discrete cosine transform used in JPEG and MPEG?',
      ['The discrete wavelet transform (DWT)', 'The Hadamard transform', 'Fast Fourier transform (FFT) with adaptive quantization', 'Vector quantization against a fixed codebook'],
      0,
      'JPEG2000 replaces JPEG and MPEG\'s block-based discrete cosine transform with a discrete wavelet transform, decomposing an image into multiple resolution sub-bands rather than fixed 8x8 pixel blocks, avoiding the blocky macroblock artifacts of heavy DCT-based compression and allowing smoother quality degradation and easier scalability. This wavelet-based, frame-independent approach is a core reason DCI mandated JPEG2000 for cinema distribution: each frame compresses and decompresses on its own, without relying on motion-predicted inter-frame data the way H.264 does, simplifying secure, frame-accurate projection at cinema scale. DCT-based approaches remain standard for consumer broadcast and streaming because they are computationally cheaper and benefit from inter-frame prediction that cinema packages deliberately forgo. Trivia: JPEG2000 was also adopted by some digital archives specifically because its wavelet compression handles high-resolution scanned documents with less visible artifacting than legacy JPEG.',
    ],
    [
      'The AV1 video codec, developed by the Alliance for Open Media and increasingly used by major streaming platforms since the late 2010s, was created primarily to solve what problem for the companies backing it?',
      ['Avoiding the licensing royalties charged for HEVC (H.265) by offering a comparably efficient, royalty-free open codec', 'Enabling frame rates above 120fps, which HEVC\'s specification hard-caps at 60fps', 'Supporting 16-bit color depth, which HEVC\'s specification limits to 10-bit', 'Reducing decode latency for live sports broadcast below what any prior codec could achieve'],
      0,
      'HEVC (H.265), the efficient successor to the widely licensed H.264/AVC codec, became entangled in a fragmented and expensive patent-licensing landscape with multiple competing patent pools, discouraging companies like Google, Netflix, Amazon, and Microsoft from broad adoption; they formed the Alliance for Open Media and released AV1 (finalized 2018) as a comparably efficient, royalty-free alternative deployable without per-unit or per-stream licensing fees. AV1 achieves meaningfully better compression efficiency than H.264 and competes closely with HEVC and VVC (H.266) at higher computational encoding cost, which slowed hardware decoder adoption in cheaper devices for years. Neither codec\'s core adoption driver was frame-rate or bit-depth ceilings; both support high frame rates and higher bit depths within their specifications. Trivia: Netflix was among the first major streaming services to roll out AV1 streams broadly, initially prioritizing lower-bandwidth mobile devices where AV1\'s efficiency gains mattered most.',
    ],
    [
      'High frame rate cinema formats like 48fps or 60fps face a challenge tied to how frames sample motion: what visual artifact does increasing capture frame rate primarily reduce compared to traditional 24fps?',
      ['Motion blur and strobing on fast-moving subjects or pans, since each frame integrates a shorter slice of time relative to the motion', 'Color banding across smooth gradients caused by insufficient bit depth per encoded frame at higher frame rates', 'Chromatic aberration introduced by camera lens elements that fail to refocus quickly enough between rapidly successive frame exposures at elevated capture rates', 'Rolling-shutter skew specific to CMOS sensor readout timing, which is unrelated to the overall frame rate chosen'],
      0,
      'At 24fps, each frame typically integrates roughly 1/48th of a second of motion with a standard 180-degree shutter angle, long enough relative to fast motion or camera pans to create visible blur or strobing on fine detail; doubling or more the frame rate shortens the time each frame captures, reducing that blur and strobing and yielding a smoother, sharper motion image, precisely the effect Peter Jackson sought with The Hobbit\'s 48fps release. This is unrelated to bit depth, chromatic aberration, or rolling-shutter skew, which are separate sensor and optical phenomena. The tradeoff critics raised is aesthetic: reduced motion blur combined with sharper digital detail can make footage look uncannily \'smooth\' or \'video-like,\' a reaction rooted in decades of audience conditioning to 24fps\'s blur characteristics as \'filmic.\' Trivia: some directors deliberately shoot select high-motion sequences at high frame rate while keeping dialogue scenes closer to a traditional cadence, specifically to manage this perceptual reaction.',
    ],
    [
      'Volumetric capture rigs, used to generate fully three-dimensional, viewpoint-independent digital recordings of a live performance for VR and virtual production pipelines, typically rely on what core capture setup?',
      ['A large array of synchronized cameras, often dozens to over a hundred, surrounding the subject, whose footage is combined into a per-frame 3D mesh with texture', 'A single high-resolution LIDAR scanner performing a slow rotating sweep around the stationary subject', 'A stereo camera pair combined with an inertial motion-capture suit worn directly by the performer', 'A consumer-grade infrared depth sensor of the same basic type used in motion-gaming hardware, but scaled up significantly in resolution, frame rate, and effective capture range for professional use'],
      0,
      'Volumetric capture studios surround a performer with dozens to well over a hundred synchronized cameras, often paired with depth sensors, whose combined footage lets photogrammetry-style software reconstruct a full 3D mesh with correct texture for every frame of the performance, producing an asset viewable and relit from any angle in real time, unlike traditional 2D footage or even stereo 3D. This differs fundamentally from a single-viewpoint depth sensor or a LIDAR sweep, neither of which can capture full-body, all-angle geometry of a moving performer in real time. Volumetric capture has been used for VR experiences, some virtual production previs, and limited feature use exploring the technology for background or crowd assets. Trivia: because volumetric capture generates genuinely new 3D geometry per frame rather than reusing a rigged model, resulting file sizes and processing costs are dramatically higher than traditional motion capture, which only records joint-position data applied to a pre-built digital character.',
    ],
    [
      'Neural radiance fields (NeRF), a machine-learning technique that reconstructs a photorealistic 3D scene from a set of 2D photographs, have begun seeing early experimental adoption in VFX and virtual production pipelines primarily for what purpose?',
      ['Generating photorealistic, freely-navigable 3D backgrounds or set extensions from ordinary photographs, without manually modeling geometry by hand', 'Automatically generating precisely dialogue-matched lip-sync facial animation from an audio track, using a separately trained neural network model distinct from the scene-reconstruction pipeline', 'Replacing traditional motion-capture markers with skeletal pose estimation from a single unmarked handheld camera', 'Losslessly compressing raw camera footage for cheaper long-term archival storage on studio servers'],
      0,
      'A NeRF trains a small neural network to represent a scene\'s radiance and density as a continuous function learned from photographs taken from different viewpoints, letting a renderer generate photorealistic novel views of that scene, including views never actually photographed, attractive to VFX and virtual production teams as a faster alternative to traditional photogrammetry and manual environment modeling for background plates, set extensions, or LED-volume content. Early industry experimentation has explored NeRF-derived environments feeding into LED-volume backgrounds or previs, though as of the mid-2020s the technique remained more common in research than in widespread mainstream pipelines, constrained by difficulty editing or relighting a NeRF scene compared to traditional 3D assets. Pose estimation, lip-sync generation, and lossless compression are all real, separate machine-learning applications in production pipelines but not what NeRF specifically targets. Trivia: the original NeRF paper, published by researchers at UC Berkeley and Google in 2020, sparked a wave of follow-up techniques, including Gaussian splatting, aimed at making reconstruction faster and more directly editable.',
    ],
    [
      'IMAX\'s laser-illuminated digital projection system, introduced to close the quality gap with traditional 70mm IMAX film, primarily improves on earlier xenon-lamp digital projection in which specific respect?',
      ['Significantly higher achievable contrast ratio and black levels, alongside a wider color gamut, rather than simply higher raw resolution', 'A doubling of maximum frame rate from 60fps to 120fps for smoother motion', 'The ability to project in genuine 15/70 film-equivalent resolution for the first time from a digital source', 'Elimination of the need for a silver-coated projection screen previously required for 3D presentations'],
      0,
      'IMAX\'s laser projection systems, rolled out from the mid-2010s onward, use laser light sources rather than xenon bulbs, allowing dramatically deeper black levels and higher contrast ratios along with a wider, more saturated color gamut, addressing the criticism that earlier digital IMAX projection looked comparatively flat next to genuine 70mm film presentations even at similar or higher pixel resolution. Raw resolution improvements happened somewhat independently, but IMAX has been explicit that contrast and color gamut, not resolution alone, were the biggest perceptual quality gaps laser projection needed to close. IMAX with Laser still does not project at the literal frame area of a 15/70 film print, which remains a separate, larger-format experience Christopher Nolan and a handful of other filmmakers continue to shoot and release specifically to preserve. Trivia: silver screens are specifically an artifact of polarized 3D projection requirements, unrelated to the laser-versus-xenon light source distinction.',
    ],
    [
      'SMPTE ST 2084, the transfer function underlying both HDR10 and Dolby Vision, is more commonly known by what name, referencing its perceptually-based design goal?',
      ['The Perceptual Quantizer (PQ) curve', 'The Hybrid Log-Gamma (HLG) curve', 'The Rec. 709 gamma curve', 'The S-Log3 transfer function'],
      0,
      'The Perceptual Quantizer, standardized as SMPTE ST 2084 in 2014 based on research by Dolby engineers, maps digital code values to absolute brightness levels according to a model of human contrast sensitivity across a much wider luminance range than traditional gamma curves used for standard-dynamic-range video, allowing HDR10 and Dolby Vision content to specify highlights far brighter than SDR\'s roughly 100-nit reference while still allocating enough code values to shadow detail. Hybrid Log-Gamma, developed jointly by the BBC and Japan\'s NHK, is a competing HDR transfer function designed to remain backward-compatible with SDR displays without needing separate metadata, making it more common in live broadcast HDR than in cinema or streaming HDR. Rec. 709 and S-Log3 are unrelated: Rec. 709 is the long-standing SDR broadcast gamma standard, and S-Log3 is Sony\'s proprietary log encoding curve for on-set capture, not a delivery HDR standard. Trivia: PQ\'s absolute-brightness design means the same code value always corresponds to the same nit level regardless of the display, unlike traditional relative gamma curves.',
    ],
    [
      'A Dolby Atmos cinema mix can carry how many discrete audio elements at once, combining traditional channel beds with independently positioned sound objects, according to Dolby\'s published specification?',
      ['Up to 128 simultaneous audio elements, a mix of channel-based beds and dynamic objects', 'Up to 64 simultaneous audio elements', 'Up to 256 simultaneous audio elements', 'An unlimited number, constrained only by the mixing engineer\'s available track count'],
      0,
      'Dolby\'s Atmos cinema specification allows up to 128 simultaneous audio elements delivered to a theater, combining traditional bed channels functioning similarly to a standard 7.1 or 9.1 layout with dynamically positioned objects that the in-theater renderer maps onto whatever speaker configuration that auditorium has installed, from a modest multiplex screen up to a flagship premium auditorium with dozens of speakers including overhead arrays. This object-based approach lets the exact same Atmos master scale correctly across wildly different room sizes and speaker counts without a separate mix for each configuration, unlike the fixed-channel-count approach of earlier formats like Dolby Digital 5.1 or DTS. Because the number is a hard specification limit, mixers must carefully manage element budgets on dense action or music sequences, sometimes collapsing less important sounds into bed channels rather than keeping them as discrete objects. Trivia: consumer Dolby Atmos in home AV receivers uses the same object-based philosophy but is delivered through Dolby Digital Plus or TrueHD as a transport layer, with far fewer physical speakers typically available to render the height information.',
    ],
    [
      'Weta Digital\'s render farm for Avatar (2009), among the largest dedicated render farms ever assembled for a single film at the time, ran on which operating system?',
      ['Linux, a cluster of Linux-based rendering blades', 'A custom fork of IRIX maintained specifically by Weta', 'Windows Server, chosen for compatibility with Autodesk\'s Maya', 'Solaris, inherited from Weta\'s earlier Sun Microsystems infrastructure'],
      0,
      'By Avatar\'s production, Weta Digital\'s render farm, reported at roughly 40,000 processor cores across thousands of blade servers, ran on Linux, reflecting the broader VFX industry\'s shift away from proprietary Unix workstations like SGI\'s IRIX or Sun\'s Solaris toward cheap, powerful, flexible Linux-based commodity hardware that had taken hold industry-wide through the 2000s. This shift, driven by the collapsing cost-per-flop of PC-class hardware and the maturity of Linux rendering pipelines, let studios scale render capacity far beyond what proprietary Unix hardware of the 1990s could economically support, directly enabling the vastly more complex CG environments and characters that would have been computationally impractical a decade earlier. Windows has seen far more limited adoption in back-end render farm infrastructure historically, more common on artist workstations for specific software than as the render farm operating system itself. Trivia: Weta\'s Avatar render farm reportedly generated enough data that the studio\'s storage and data-management challenges were themselves a significant engineering effort separate from the rendering computation itself.',
    ],
    [
      'The Bayer filter pattern, near-universal on single-sensor digital cameras including most cinema cameras, arranges color filters over photosites in what ratio of red, green, and blue?',
      ['One red, two green, and one blue filter per repeating 2x2 block, i.e. twice as many green photosites as red or blue', 'An equal one red, one green, one blue arrangement repeated across a 3x3 block, with the fourth cell left unfiltered for luminance', 'Two red and two blue photosites alternating in checkerboard fashion, with green derived entirely through interpolation from both', 'One red, one green, one blue, and one dedicated white unfiltered photosite per repeating 2x2 block'],
      0,
      'The Bayer pattern, patented by Kodak\'s Bryce Bayer in 1976, uses a repeating 2x2 block containing two green-filtered photosites diagonally opposite each other, plus one red and one blue, because the human eye is most sensitive to green light and detail, so doubling green sampling density improves perceived sharpness and reduces luminance noise relative to an equal RGB split. A camera\'s image processor then interpolates, or demosaics, the missing color information at each photosite from its neighbors to reconstruct a full-color image, a step that can itself introduce characteristic artifacts like color moiré on fine repeating patterns. Some cinema and other cameras use alternative sensor designs specifically to avoid Bayer demosaicing tradeoffs, but the vast majority of digital cinema cameras, including most ARRI and RED models, remain Bayer-based. Trivia: this same green-favoring logic is part of why chroma-key compositors generally prefer green screens over blue, since the green channel typically carries the cleanest, least noisy detail to build a matte from.',
    ],
    [
      'Gaussian splatting, a real-time 3D scene reconstruction and rendering technique that emerged as a faster alternative to NeRF around 2023, represents a captured scene as what kind of underlying data structure?',
      ['A large collection of translucent 3D Gaussian ellipsoids, each with position, scale, orientation, and color, optimized to reproduce the source photographs', 'A dense voxel grid storing per-voxel opacity and color values sampled uniformly at a fixed spatial resolution throughout the scene', 'A single continuous neural network function queried per pixel at render time, structurally and architecturally identical to NeRF\'s implicit representation but implemented with a smaller, faster network', 'A traditional textured polygon mesh generated via multi-view photogrammetry, with Gaussian blur applied only to distant background geometry'],
      0,
      'Gaussian splatting, introduced in a widely cited 2023 paper, represents a scene as millions of 3D Gaussian primitives, soft ellipsoidal blobs with position, scale, orientation, opacity, and view-dependent color, rather than a neural network function as in NeRF or a discrete voxel grid, and renders novel viewpoints extremely fast by directly \'splatting\' these Gaussians onto the screen rather than requiring the dense per-pixel neural network queries NeRF relies on. This combination of high visual quality and real-time rendering speed made it immediately attractive for virtual production, game engines, and VFX pipelines exploring photogrammetry-style capture, since it can be edited and relit more tractably than a NeRF\'s opaque neural weights, and several vendors began experimenting with it for LED-volume content and previs almost immediately after publication. Unlike a polygon mesh, a Gaussian splat scene has no explicit connected surface geometry, which is part of what makes traditional mesh-based editing and rigging tools awkward to apply to it directly. Trivia: the technique\'s speed made live Gaussian splat scene capture and viewing on consumer-grade hardware possible within roughly a year of the original paper\'s publication.',
    ],
    [
      'In broadcast engineering, SMPTE timecode\'s \'drop-frame\' variant exists specifically to reconcile which mismatch?',
      ['NTSC\'s actual 29.97fps frame rate against a timecode counter that counts in whole-number 30fps steps, which would otherwise drift from real elapsed clock time', 'The difference between PAL\'s 25 frames-per-second broadcast standard and film\'s traditional 24fps rate when converting European broadcast masters for North American theatrical and home-video distribution', 'Audio sample-rate drift between 48kHz and 44.1kHz recordings synchronized to the same production timecode track', 'The small offset introduced when a digital cinema package\'s 24fps master is projected at a theater\'s slightly different house frame rate'],
      0,
      'NTSC color video\'s frame rate is not exactly 30fps but 29.97fps, a deliberate small reduction introduced in 1953 to prevent interference between the color subcarrier signal and the audio carrier, which means a timecode counter incrementing in exact whole-number 30-frame-per-second steps would, over a long program, drift noticeably ahead of true wall-clock elapsed time. Drop-frame timecode compensates by skipping two frame numbers, not two actual frames of video, every minute except every tenth minute, keeping the timecode display closely synchronized with real elapsed time over long durations, which matters enormously for broadcast programs that must hit exact clock times and ad-break durations. Non-drop-frame timecode, which counts every frame without skipping, remains simpler for pure frame-accurate editing math but drifts against real clock time by roughly 3.6 seconds over a full hour, an error broadcast engineering can\'t tolerate for scheduled live television. Trivia: drop-frame timecode is conventionally displayed with a semicolon before the frames field instead of the colon used for non-drop-frame, letting engineers tell the two apart at a glance.',
    ],

  ],
};
